MODULE CPLNG_TYPES_MOD

   USE PARKIND1, ONLY: JPIM, JPRD

   IMPLICIT NONE

   PRIVATE

   PUBLIC CPLNG_FLD_TYPE

   TYPE CPLNG_FLD_TYPE
      INTEGER(KIND=JPIM),ALLOCATABLE :: ID(:,:)
      CHARACTER(LEN=128)             :: NAME
      INTEGER(KIND=JPIM)             :: TYPE
      INTEGER(KIND=JPIM)             :: INOUT
      INTEGER(KIND=JPIM)             :: STAGE
      INTEGER(KIND=JPIM)             :: NUM_LVL
      INTEGER(KIND=JPIM)             :: NUM_CAT
      REAL(KIND=JPRD),   ALLOCATABLE :: D(:,:,:)
   END TYPE CPLNG_FLD_TYPE

END MODULE CPLNG_TYPES_MOD
