MODULE MODEL_ATMOS_OCEAN_COUPLING_MOD
  USE YOMMCC, ONLY : TMCC
  USE YOMCOM, ONLY : TCOM
  USE YOMCOU, ONLY : TCOU
  IMPLICIT NONE

  TYPE MODEL_ATMOS_OCEAN_COUPLING_TYPE

    TYPE(TMCC)  :: YRMCC
    TYPE(TCOM)  :: YRCOM
    TYPE(TCOU)  :: YRCOU

    CONTAINS

     
    
  END TYPE MODEL_ATMOS_OCEAN_COUPLING_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  

END MODULE MODEL_ATMOS_OCEAN_COUPLING_MOD
