MODULE STACK_MOD

USE FIELD_MODULE

IMPLICIT NONE

TYPE STACK
  CLASS (FIELD_2D), POINTER :: F_P 
  INTEGER*8 :: L, U
CONTAINS 
  PROCEDURE :: INIT => INIT_STACK
  PROCEDURE :: FINAL => FINAL_STACK
END TYPE

CONTAINS

SUBROUTINE INIT_STACK (SELF, KSIZE, KGPBLKS)

CLASS (STACK) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KSIZE, KGPBLKS

TYPE(FIELD_2D_OWNER), POINTER :: YLFO 

ALLOCATE (YLFO)
CALL YLFO%INIT (PERSISTENT=.TRUE., UBOUNDS=[KSIZE,KGPBLKS], LBOUNDS=[1,1])
SELF%F_P => YLFO
CALL YLFO%SYNC_DEVICE_RDWR

END SUBROUTINE

SUBROUTINE FINAL_STACK (SELF)

CLASS (STACK) :: SELF

CALL SELF%F_P%FINAL
DEALLOCATE (SELF%F_P)
SELF%F_P => NULL ()

END SUBROUTINE

SUBROUTINE STACK_ABORT (CDF, KL)

!$acc routine (STACK_ABORT) seq

CHARACTER(LEN=*) :: CDF
INTEGER :: KL

PRINT *, CDF, ':', KL
STOP

END SUBROUTINE

END MODULE
