MODULE UTIL_TECUCONVCA_MOD

USE YOE_CUCONVCA, ONLY : TECUCONVCA


INTERFACE SAVE
MODULE PROCEDURE SAVE_TECUCONVCA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECUCONVCA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TECUCONVCA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TECUCONVCA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TECUCONVCA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECUCONVCA), INTENT (IN), TARGET :: YD
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG

WRITE (KLUN) YD%NLIVES
WRITE (KLUN) YD%NFERTYRS
WRITE (KLUN) YD%NSPINUP
LNCELLCU = ALLOCATED (YD%NCELLCU)
WRITE (KLUN) LNCELLCU
IF (LNCELLCU) THEN
  WRITE (KLUN) LBOUND (YD%NCELLCU)
  WRITE (KLUN) UBOUND (YD%NCELLCU)
  WRITE (KLUN) YD%NCELLCU
ENDIF
LNFERTCU = ALLOCATED (YD%NFERTCU)
WRITE (KLUN) LNFERTCU
IF (LNFERTCU) THEN
  WRITE (KLUN) LBOUND (YD%NFERTCU)
  WRITE (KLUN) UBOUND (YD%NFERTCU)
  WRITE (KLUN) YD%NFERTCU
ENDIF
LNBLS = ALLOCATED (YD%NBLS)
WRITE (KLUN) LNBLS
IF (LNBLS) THEN
  WRITE (KLUN) LBOUND (YD%NBLS)
  WRITE (KLUN) UBOUND (YD%NBLS)
  WRITE (KLUN) YD%NBLS
ENDIF
LNBSS = ALLOCATED (YD%NBSS)
WRITE (KLUN) LNBSS
IF (LNBSS) THEN
  WRITE (KLUN) LBOUND (YD%NBSS)
  WRITE (KLUN) UBOUND (YD%NBSS)
  WRITE (KLUN) YD%NBSS
ENDIF
LNRNBLS = ALLOCATED (YD%NRNBLS)
WRITE (KLUN) LNRNBLS
IF (LNRNBLS) THEN
  WRITE (KLUN) LBOUND (YD%NRNBLS)
  WRITE (KLUN) UBOUND (YD%NRNBLS)
  WRITE (KLUN) YD%NRNBLS
ENDIF
LNRNBSS = ALLOCATED (YD%NRNBSS)
WRITE (KLUN) LNRNBSS
IF (LNRNBSS) THEN
  WRITE (KLUN) LBOUND (YD%NRNBSS)
  WRITE (KLUN) UBOUND (YD%NRNBSS)
  WRITE (KLUN) YD%NRNBSS
ENDIF
LNBEW = ALLOCATED (YD%NBEW)
WRITE (KLUN) LNBEW
IF (LNBEW) THEN
  WRITE (KLUN) LBOUND (YD%NBEW)
  WRITE (KLUN) UBOUND (YD%NBEW)
  WRITE (KLUN) YD%NBEW
ENDIF
LNBNS = ALLOCATED (YD%NBNS)
WRITE (KLUN) LNBNS
IF (LNBNS) THEN
  WRITE (KLUN) LBOUND (YD%NBNS)
  WRITE (KLUN) UBOUND (YD%NBNS)
  WRITE (KLUN) YD%NBNS
ENDIF
LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
WRITE (KLUN) LRCUCONVCA
IF (LRCUCONVCA) THEN
  WRITE (KLUN) LBOUND (YD%RCUCONVCA)
  WRITE (KLUN) UBOUND (YD%RCUCONVCA)
  WRITE (KLUN) YD%RCUCONVCA
ENDIF
LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
WRITE (KLUN) LRNLCONVCA
IF (LRNLCONVCA) THEN
  WRITE (KLUN) LBOUND (YD%RNLCONVCA)
  WRITE (KLUN) UBOUND (YD%RNLCONVCA)
  WRITE (KLUN) YD%RNLCONVCA
ENDIF
LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
WRITE (KLUN) LRCAPECONVCA
IF (LRCAPECONVCA) THEN
  WRITE (KLUN) LBOUND (YD%RCAPECONVCA)
  WRITE (KLUN) UBOUND (YD%RCAPECONVCA)
  WRITE (KLUN) YD%RCAPECONVCA
ENDIF
LRWASALIVE = ALLOCATED (YD%RWASALIVE)
WRITE (KLUN) LRWASALIVE
IF (LRWASALIVE) THEN
  WRITE (KLUN) LBOUND (YD%RWASALIVE)
  WRITE (KLUN) UBOUND (YD%RWASALIVE)
  WRITE (KLUN) YD%RWASALIVE
ENDIF
LRWGHTCU = ALLOCATED (YD%RWGHTCU)
WRITE (KLUN) LRWGHTCU
IF (LRWGHTCU) THEN
  WRITE (KLUN) LBOUND (YD%RWGHTCU)
  WRITE (KLUN) UBOUND (YD%RWGHTCU)
  WRITE (KLUN) YD%RWGHTCU
ENDIF
LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
WRITE (KLUN) LRLATLONNBLS
IF (LRLATLONNBLS) THEN
  WRITE (KLUN) LBOUND (YD%RLATLONNBLS)
  WRITE (KLUN) UBOUND (YD%RLATLONNBLS)
  WRITE (KLUN) YD%RLATLONNBLS
ENDIF
LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
WRITE (KLUN) LRLATLONNBSS
IF (LRLATLONNBSS) THEN
  WRITE (KLUN) LBOUND (YD%RLATLONNBSS)
  WRITE (KLUN) UBOUND (YD%RLATLONNBSS)
  WRITE (KLUN) YD%RLATLONNBSS
ENDIF
WRITE (KLUN) YD%RPROB_SURVIVE
WRITE (KLUN) YD%RPROB_BIRTH
WRITE (KLUN) YD%RPROB_FUN_FERT_S
WRITE (KLUN) YD%RPROB_FUN_UW_DW_S
WRITE (KLUN) YD%RPROB_FUN_FERT_B
WRITE (KLUN) YD%RPROB_FUN_UW_DW_B
LRLONDEP = ALLOCATED (YD%RLONDEP)
WRITE (KLUN) LRLONDEP
IF (LRLONDEP) THEN
  WRITE (KLUN) LBOUND (YD%RLONDEP)
  WRITE (KLUN) UBOUND (YD%RLONDEP)
  WRITE (KLUN) YD%RLONDEP
ENDIF
LRLATDEP = ALLOCATED (YD%RLATDEP)
WRITE (KLUN) LRLATDEP
IF (LRLATDEP) THEN
  WRITE (KLUN) LBOUND (YD%RLATDEP)
  WRITE (KLUN) UBOUND (YD%RLATDEP)
  WRITE (KLUN) YD%RLATDEP
ENDIF
WRITE (KLUN) YD%RCA_SEEDPROB
WRITE (KLUN) YD%RCADELX
WRITE (KLUN) YD%LCUCONV_CA
WRITE (KLUN) YD%LCA_ADVECT
WRITE (KLUN) YD%LCA_GLOBAL
WRITE (KLUN) YD%LCA_SMOOTH
WRITE (KLUN) YD%LCA_TEST
WRITE (KLUN) YD%LCA_ADVTEST
WRITE (KLUN) YD%LCA_RANTROP
WRITE (KLUN) YD%LCA_NBDEBUG
WRITE (KLUN) YD%LCA_EXTRACT
WRITE (KLUN) YD%CA_FORC
WRITE (KLUN) YD%CA_WIND
WRITE (KLUN) YD%CA_PROB
WRITE (KLUN) YD%NFRCASEED
WRITE (KLUN) YD%NTESTPROC
WRITE (KLUN) YD%NTESTGP
WRITE (KLUN) YD%NDXUNREAL
WRITE (KLUN) YD%NDYUNREAL
LSLLONG = ALLOCATED (YD%SLLONG)
WRITE (KLUN) LSLLONG
IF (LSLLONG) THEN
  WRITE (KLUN) LBOUND (YD%SLLONG)
  WRITE (KLUN) UBOUND (YD%SLLONG)
  WRITE (KLUN) YD%SLLONG
ENDIF
LSLLAT = ALLOCATED (YD%SLLAT)
WRITE (KLUN) LSLLAT
IF (LSLLAT) THEN
  WRITE (KLUN) LBOUND (YD%SLLAT)
  WRITE (KLUN) UBOUND (YD%SLLAT)
  WRITE (KLUN) YD%SLLAT
ENDIF
LSLDLONG = ALLOCATED (YD%SLDLONG)
WRITE (KLUN) LSLDLONG
IF (LSLDLONG) THEN
  WRITE (KLUN) LBOUND (YD%SLDLONG)
  WRITE (KLUN) UBOUND (YD%SLDLONG)
  WRITE (KLUN) YD%SLDLONG
ENDIF
LSLDLAT = ALLOCATED (YD%SLDLAT)
WRITE (KLUN) LSLDLAT
IF (LSLDLAT) THEN
  WRITE (KLUN) LBOUND (YD%SLDLAT)
  WRITE (KLUN) UBOUND (YD%SLDLAT)
  WRITE (KLUN) YD%SLDLAT
ENDIF
LSLDDLAT = ALLOCATED (YD%SLDDLAT)
WRITE (KLUN) LSLDDLAT
IF (LSLDDLAT) THEN
  WRITE (KLUN) LBOUND (YD%SLDDLAT)
  WRITE (KLUN) UBOUND (YD%SLDDLAT)
  WRITE (KLUN) YD%SLDDLAT
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TECUCONVCA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECUCONVCA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG

READ (KLUN) YD%NLIVES
READ (KLUN) YD%NFERTYRS
READ (KLUN) YD%NSPINUP
READ (KLUN) LNCELLCU
IF (LNCELLCU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NCELLCU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NCELLCU
ENDIF
READ (KLUN) LNFERTCU
IF (LNFERTCU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NFERTCU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NFERTCU
ENDIF
READ (KLUN) LNBLS
IF (LNBLS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NBLS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NBLS
ENDIF
READ (KLUN) LNBSS
IF (LNBSS) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%NBSS (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%NBSS
ENDIF
READ (KLUN) LNRNBLS
IF (LNRNBLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NRNBLS (IL1(1):IU1(1)))
  READ (KLUN) YD%NRNBLS
ENDIF
READ (KLUN) LNRNBSS
IF (LNRNBSS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NRNBSS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NRNBSS
ENDIF
READ (KLUN) LNBEW
IF (LNBEW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%NBEW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%NBEW
ENDIF
READ (KLUN) LNBNS
IF (LNBNS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%NBNS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%NBNS
ENDIF
READ (KLUN) LRCUCONVCA
IF (LRCUCONVCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCUCONVCA (IL1(1):IU1(1)))
  READ (KLUN) YD%RCUCONVCA
ENDIF
READ (KLUN) LRNLCONVCA
IF (LRNLCONVCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RNLCONVCA (IL1(1):IU1(1)))
  READ (KLUN) YD%RNLCONVCA
ENDIF
READ (KLUN) LRCAPECONVCA
IF (LRCAPECONVCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCAPECONVCA (IL1(1):IU1(1)))
  READ (KLUN) YD%RCAPECONVCA
ENDIF
READ (KLUN) LRWASALIVE
IF (LRWASALIVE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RWASALIVE (IL1(1):IU1(1)))
  READ (KLUN) YD%RWASALIVE
ENDIF
READ (KLUN) LRWGHTCU
IF (LRWGHTCU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RWGHTCU (IL1(1):IU1(1)))
  READ (KLUN) YD%RWGHTCU
ENDIF
READ (KLUN) LRLATLONNBLS
IF (LRLATLONNBLS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLATLONNBLS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RLATLONNBLS
ENDIF
READ (KLUN) LRLATLONNBSS
IF (LRLATLONNBSS) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RLATLONNBSS (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%RLATLONNBSS
ENDIF
READ (KLUN) YD%RPROB_SURVIVE
READ (KLUN) YD%RPROB_BIRTH
READ (KLUN) YD%RPROB_FUN_FERT_S
READ (KLUN) YD%RPROB_FUN_UW_DW_S
READ (KLUN) YD%RPROB_FUN_FERT_B
READ (KLUN) YD%RPROB_FUN_UW_DW_B
READ (KLUN) LRLONDEP
IF (LRLONDEP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLONDEP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RLONDEP
ENDIF
READ (KLUN) LRLATDEP
IF (LRLATDEP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLATDEP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RLATDEP
ENDIF
READ (KLUN) YD%RCA_SEEDPROB
READ (KLUN) YD%RCADELX
READ (KLUN) YD%LCUCONV_CA
READ (KLUN) YD%LCA_ADVECT
READ (KLUN) YD%LCA_GLOBAL
READ (KLUN) YD%LCA_SMOOTH
READ (KLUN) YD%LCA_TEST
READ (KLUN) YD%LCA_ADVTEST
READ (KLUN) YD%LCA_RANTROP
READ (KLUN) YD%LCA_NBDEBUG
READ (KLUN) YD%LCA_EXTRACT
READ (KLUN) YD%CA_FORC
READ (KLUN) YD%CA_WIND
READ (KLUN) YD%CA_PROB
READ (KLUN) YD%NFRCASEED
READ (KLUN) YD%NTESTPROC
READ (KLUN) YD%NTESTGP
READ (KLUN) YD%NDXUNREAL
READ (KLUN) YD%NDYUNREAL
READ (KLUN) LSLLONG
IF (LSLLONG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLLONG (IL1(1):IU1(1)))
  READ (KLUN) YD%SLLONG
ENDIF
READ (KLUN) LSLLAT
IF (LSLLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%SLLAT
ENDIF
READ (KLUN) LSLDLONG
IF (LSLDLONG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLDLONG (IL1(1):IU1(1)))
  READ (KLUN) YD%SLDLONG
ENDIF
READ (KLUN) LSLDLAT
IF (LSLDLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLDLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%SLDLAT
ENDIF
READ (KLUN) LSLDDLAT
IF (LSLDDLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLDDLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%SLDDLAT
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TECUCONVCA (YD, LDCREATED)
IMPLICIT NONE
TYPE (TECUCONVCA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF



LNCELLCU = ALLOCATED (YD%NCELLCU)
IF (LNCELLCU) THEN
  !$acc enter data create (YD%NCELLCU)
  !$acc update device (YD%NCELLCU)
  !$acc enter data attach (YD%NCELLCU)
ENDIF

LNFERTCU = ALLOCATED (YD%NFERTCU)
IF (LNFERTCU) THEN
  !$acc enter data create (YD%NFERTCU)
  !$acc update device (YD%NFERTCU)
  !$acc enter data attach (YD%NFERTCU)
ENDIF

LNBLS = ALLOCATED (YD%NBLS)
IF (LNBLS) THEN
  !$acc enter data create (YD%NBLS)
  !$acc update device (YD%NBLS)
  !$acc enter data attach (YD%NBLS)
ENDIF

LNBSS = ALLOCATED (YD%NBSS)
IF (LNBSS) THEN
  !$acc enter data create (YD%NBSS)
  !$acc update device (YD%NBSS)
  !$acc enter data attach (YD%NBSS)
ENDIF

LNRNBLS = ALLOCATED (YD%NRNBLS)
IF (LNRNBLS) THEN
  !$acc enter data create (YD%NRNBLS)
  !$acc update device (YD%NRNBLS)
  !$acc enter data attach (YD%NRNBLS)
ENDIF

LNRNBSS = ALLOCATED (YD%NRNBSS)
IF (LNRNBSS) THEN
  !$acc enter data create (YD%NRNBSS)
  !$acc update device (YD%NRNBSS)
  !$acc enter data attach (YD%NRNBSS)
ENDIF

LNBEW = ALLOCATED (YD%NBEW)
IF (LNBEW) THEN
  !$acc enter data create (YD%NBEW)
  !$acc update device (YD%NBEW)
  !$acc enter data attach (YD%NBEW)
ENDIF

LNBNS = ALLOCATED (YD%NBNS)
IF (LNBNS) THEN
  !$acc enter data create (YD%NBNS)
  !$acc update device (YD%NBNS)
  !$acc enter data attach (YD%NBNS)
ENDIF

LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
IF (LRCUCONVCA) THEN
  !$acc enter data create (YD%RCUCONVCA)
  !$acc update device (YD%RCUCONVCA)
  !$acc enter data attach (YD%RCUCONVCA)
ENDIF

LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
IF (LRNLCONVCA) THEN
  !$acc enter data create (YD%RNLCONVCA)
  !$acc update device (YD%RNLCONVCA)
  !$acc enter data attach (YD%RNLCONVCA)
ENDIF

LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
IF (LRCAPECONVCA) THEN
  !$acc enter data create (YD%RCAPECONVCA)
  !$acc update device (YD%RCAPECONVCA)
  !$acc enter data attach (YD%RCAPECONVCA)
ENDIF

LRWASALIVE = ALLOCATED (YD%RWASALIVE)
IF (LRWASALIVE) THEN
  !$acc enter data create (YD%RWASALIVE)
  !$acc update device (YD%RWASALIVE)
  !$acc enter data attach (YD%RWASALIVE)
ENDIF

LRWGHTCU = ALLOCATED (YD%RWGHTCU)
IF (LRWGHTCU) THEN
  !$acc enter data create (YD%RWGHTCU)
  !$acc update device (YD%RWGHTCU)
  !$acc enter data attach (YD%RWGHTCU)
ENDIF

LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
IF (LRLATLONNBLS) THEN
  !$acc enter data create (YD%RLATLONNBLS)
  !$acc update device (YD%RLATLONNBLS)
  !$acc enter data attach (YD%RLATLONNBLS)
ENDIF

LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
IF (LRLATLONNBSS) THEN
  !$acc enter data create (YD%RLATLONNBSS)
  !$acc update device (YD%RLATLONNBSS)
  !$acc enter data attach (YD%RLATLONNBSS)
ENDIF







LRLONDEP = ALLOCATED (YD%RLONDEP)
IF (LRLONDEP) THEN
  !$acc enter data create (YD%RLONDEP)
  !$acc update device (YD%RLONDEP)
  !$acc enter data attach (YD%RLONDEP)
ENDIF

LRLATDEP = ALLOCATED (YD%RLATDEP)
IF (LRLATDEP) THEN
  !$acc enter data create (YD%RLATDEP)
  !$acc update device (YD%RLATDEP)
  !$acc enter data attach (YD%RLATDEP)
ENDIF




















LSLLONG = ALLOCATED (YD%SLLONG)
IF (LSLLONG) THEN
  !$acc enter data create (YD%SLLONG)
  !$acc update device (YD%SLLONG)
  !$acc enter data attach (YD%SLLONG)
ENDIF

LSLLAT = ALLOCATED (YD%SLLAT)
IF (LSLLAT) THEN
  !$acc enter data create (YD%SLLAT)
  !$acc update device (YD%SLLAT)
  !$acc enter data attach (YD%SLLAT)
ENDIF

LSLDLONG = ALLOCATED (YD%SLDLONG)
IF (LSLDLONG) THEN
  !$acc enter data create (YD%SLDLONG)
  !$acc update device (YD%SLDLONG)
  !$acc enter data attach (YD%SLDLONG)
ENDIF

LSLDLAT = ALLOCATED (YD%SLDLAT)
IF (LSLDLAT) THEN
  !$acc enter data create (YD%SLDLAT)
  !$acc update device (YD%SLDLAT)
  !$acc enter data attach (YD%SLDLAT)
ENDIF

LSLDDLAT = ALLOCATED (YD%SLDDLAT)
IF (LSLDDLAT) THEN
  !$acc enter data create (YD%SLDDLAT)
  !$acc update device (YD%SLDDLAT)
  !$acc enter data attach (YD%SLDDLAT)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TECUCONVCA (YD, LDDELETED)
IMPLICIT NONE
TYPE (TECUCONVCA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG




LNCELLCU = ALLOCATED (YD%NCELLCU)
IF (LNCELLCU) THEN
  !$acc exit data detach (YD%NCELLCU)
  !$acc exit data delete (YD%NCELLCU)
ENDIF

LNFERTCU = ALLOCATED (YD%NFERTCU)
IF (LNFERTCU) THEN
  !$acc exit data detach (YD%NFERTCU)
  !$acc exit data delete (YD%NFERTCU)
ENDIF

LNBLS = ALLOCATED (YD%NBLS)
IF (LNBLS) THEN
  !$acc exit data detach (YD%NBLS)
  !$acc exit data delete (YD%NBLS)
ENDIF

LNBSS = ALLOCATED (YD%NBSS)
IF (LNBSS) THEN
  !$acc exit data detach (YD%NBSS)
  !$acc exit data delete (YD%NBSS)
ENDIF

LNRNBLS = ALLOCATED (YD%NRNBLS)
IF (LNRNBLS) THEN
  !$acc exit data detach (YD%NRNBLS)
  !$acc exit data delete (YD%NRNBLS)
ENDIF

LNRNBSS = ALLOCATED (YD%NRNBSS)
IF (LNRNBSS) THEN
  !$acc exit data detach (YD%NRNBSS)
  !$acc exit data delete (YD%NRNBSS)
ENDIF

LNBEW = ALLOCATED (YD%NBEW)
IF (LNBEW) THEN
  !$acc exit data detach (YD%NBEW)
  !$acc exit data delete (YD%NBEW)
ENDIF

LNBNS = ALLOCATED (YD%NBNS)
IF (LNBNS) THEN
  !$acc exit data detach (YD%NBNS)
  !$acc exit data delete (YD%NBNS)
ENDIF

LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
IF (LRCUCONVCA) THEN
  !$acc exit data detach (YD%RCUCONVCA)
  !$acc exit data delete (YD%RCUCONVCA)
ENDIF

LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
IF (LRNLCONVCA) THEN
  !$acc exit data detach (YD%RNLCONVCA)
  !$acc exit data delete (YD%RNLCONVCA)
ENDIF

LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
IF (LRCAPECONVCA) THEN
  !$acc exit data detach (YD%RCAPECONVCA)
  !$acc exit data delete (YD%RCAPECONVCA)
ENDIF

LRWASALIVE = ALLOCATED (YD%RWASALIVE)
IF (LRWASALIVE) THEN
  !$acc exit data detach (YD%RWASALIVE)
  !$acc exit data delete (YD%RWASALIVE)
ENDIF

LRWGHTCU = ALLOCATED (YD%RWGHTCU)
IF (LRWGHTCU) THEN
  !$acc exit data detach (YD%RWGHTCU)
  !$acc exit data delete (YD%RWGHTCU)
ENDIF

LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
IF (LRLATLONNBLS) THEN
  !$acc exit data detach (YD%RLATLONNBLS)
  !$acc exit data delete (YD%RLATLONNBLS)
ENDIF

LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
IF (LRLATLONNBSS) THEN
  !$acc exit data detach (YD%RLATLONNBSS)
  !$acc exit data delete (YD%RLATLONNBSS)
ENDIF







LRLONDEP = ALLOCATED (YD%RLONDEP)
IF (LRLONDEP) THEN
  !$acc exit data detach (YD%RLONDEP)
  !$acc exit data delete (YD%RLONDEP)
ENDIF

LRLATDEP = ALLOCATED (YD%RLATDEP)
IF (LRLATDEP) THEN
  !$acc exit data detach (YD%RLATDEP)
  !$acc exit data delete (YD%RLATDEP)
ENDIF




















LSLLONG = ALLOCATED (YD%SLLONG)
IF (LSLLONG) THEN
  !$acc exit data detach (YD%SLLONG)
  !$acc exit data delete (YD%SLLONG)
ENDIF

LSLLAT = ALLOCATED (YD%SLLAT)
IF (LSLLAT) THEN
  !$acc exit data detach (YD%SLLAT)
  !$acc exit data delete (YD%SLLAT)
ENDIF

LSLDLONG = ALLOCATED (YD%SLDLONG)
IF (LSLDLONG) THEN
  !$acc exit data detach (YD%SLDLONG)
  !$acc exit data delete (YD%SLDLONG)
ENDIF

LSLDLAT = ALLOCATED (YD%SLDLAT)
IF (LSLDLAT) THEN
  !$acc exit data detach (YD%SLDLAT)
  !$acc exit data delete (YD%SLDLAT)
ENDIF

LSLDDLAT = ALLOCATED (YD%SLDDLAT)
IF (LSLDDLAT) THEN
  !$acc exit data detach (YD%SLDDLAT)
  !$acc exit data delete (YD%SLDDLAT)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
