MODULE UTIL_TERIP_MOD

USE YOERIP, ONLY : TERIP


INTERFACE SAVE
MODULE PROCEDURE SAVE_TERIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TERIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TERIP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TERIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TERIP (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TERIP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RCODECM
WRITE (KLUN) YD%RSIDECM
WRITE (KLUN) YD%RCOVSRM
WRITE (KLUN) YD%RSIVSRM
WRITE (KLUN) YD%RSOVRM
WRITE (KLUN) YD%RWSOVRM
END SUBROUTINE

SUBROUTINE LOAD_TERIP (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TERIP), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RCODECM
READ (KLUN) YD%RSIDECM
READ (KLUN) YD%RCOVSRM
READ (KLUN) YD%RSIVSRM
READ (KLUN) YD%RSOVRM
READ (KLUN) YD%RWSOVRM
END SUBROUTINE


SUBROUTINE COPY_TERIP (YD, LDCREATED)
IMPLICIT NONE
CLASS (TERIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF






END SUBROUTINE

SUBROUTINE WIPE_TERIP (YD, LDDELETED)
IMPLICIT NONE
CLASS (TERIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED







LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
