MODULE UTIL_TECLD_MOD

USE YOECLD, ONLY : TECLD

INTERFACE SAVE
MODULE PROCEDURE SAVE_TECLD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECLD
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TECLD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECLD), INTENT (IN), TARGET :: YD
LOGICAL :: LCETA
LCETA = ALLOCATED (YD%CETA)
WRITE (KLUN) LCETA
IF (LCETA) THEN
  WRITE (KLUN) LBOUND (YD%CETA)
  WRITE (KLUN) UBOUND (YD%CETA)
  WRITE (KLUN) YD%CETA
ENDIF
WRITE (KLUN) YD%RANVA
WRITE (KLUN) YD%RANVB
WRITE (KLUN) YD%RANVH
WRITE (KLUN) YD%RCCA
WRITE (KLUN) YD%RCCB
WRITE (KLUN) YD%RCCC
WRITE (KLUN) YD%RCFCT
WRITE (KLUN) YD%RCLWMR
WRITE (KLUN) YD%RCSCAL
WRITE (KLUN) YD%RDECORR_CF
WRITE (KLUN) YD%RDECORR_CW
WRITE (KLUN) YD%RETAHB
WRITE (KLUN) YD%RETAMB
WRITE (KLUN) YD%RLOIA
WRITE (KLUN) YD%RLOIB
WRITE (KLUN) YD%RLOIC
WRITE (KLUN) YD%RLOID
WRITE (KLUN) YD%RLONIA
WRITE (KLUN) YD%RLONIB
WRITE (KLUN) YD%RRHH
WRITE (KLUN) YD%RRHL
WRITE (KLUN) YD%RGAMMAS
WRITE (KLUN) YD%REPSCR
WRITE (KLUN) YD%REPSEC
WRITE (KLUN) YD%LOMEGA
END SUBROUTINE

SUBROUTINE LOAD_TECLD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECLD), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LCETA
READ (KLUN) LCETA
IF (LCETA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CETA (IL1(1):IU1(1)))
  READ (KLUN) YD%CETA
ENDIF
READ (KLUN) YD%RANVA
READ (KLUN) YD%RANVB
READ (KLUN) YD%RANVH
READ (KLUN) YD%RCCA
READ (KLUN) YD%RCCB
READ (KLUN) YD%RCCC
READ (KLUN) YD%RCFCT
READ (KLUN) YD%RCLWMR
READ (KLUN) YD%RCSCAL
READ (KLUN) YD%RDECORR_CF
READ (KLUN) YD%RDECORR_CW
READ (KLUN) YD%RETAHB
READ (KLUN) YD%RETAMB
READ (KLUN) YD%RLOIA
READ (KLUN) YD%RLOIB
READ (KLUN) YD%RLOIC
READ (KLUN) YD%RLOID
READ (KLUN) YD%RLONIA
READ (KLUN) YD%RLONIB
READ (KLUN) YD%RRHH
READ (KLUN) YD%RRHL
READ (KLUN) YD%RGAMMAS
READ (KLUN) YD%REPSCR
READ (KLUN) YD%REPSEC
READ (KLUN) YD%LOMEGA
END SUBROUTINE






END MODULE
