MODULE UTIL_TDIMV_MOD

USE YOMDIMV, ONLY : TDIMV

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDIMV
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIMV
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDIMV
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDIMV
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDIMV (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIMV), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NFLEVG
WRITE (KLUN) YD%NFLEVL
WRITE (KLUN) YD%NFLEVLMX
WRITE (KLUN) YD%NFLSUR
WRITE (KLUN) YD%NFLSUL
WRITE (KLUN) YD%NFLSA
WRITE (KLUN) YD%NFLEN
WRITE (KLUN) YD%NIOLEVG
END SUBROUTINE

SUBROUTINE LOAD_TDIMV (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIMV), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NFLEVG
READ (KLUN) YD%NFLEVL
READ (KLUN) YD%NFLEVLMX
READ (KLUN) YD%NFLSUR
READ (KLUN) YD%NFLSUL
READ (KLUN) YD%NFLSA
READ (KLUN) YD%NFLEN
READ (KLUN) YD%NIOLEVG
END SUBROUTINE


SUBROUTINE COPY_TDIMV (YD, LDCREATED)

IMPLICIT NONE
TYPE (TDIMV), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF








END SUBROUTINE

SUBROUTINE WIPE_TDIMV (YD, LDDELETED)

IMPLICIT NONE
TYPE (TDIMV), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED









LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
