MODULE UTIL_TYPE_GFLD_MOD

USE YOM_YGFL, ONLY : TYPE_GFLD

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_GFLD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_GFLD
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TYPE_GFLD (KLUN, YD)
USE UTIL_TYPE_AERO_WVL_DIAG_MOD
USE UTIL_TYPE_GFL_COMP_MOD
USE UTIL_TYPE_GFL_NAML_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFLD), INTENT (IN), TARGET :: YD
INTEGER :: J1, J2
LOGICAL :: LYA, LYAERAOT, LYAERLISI, LYAERO, LYAEROCLIM, LYAEROUT, LYCHEM, LYCPF, LYCRM, LYCVGQ
LOGICAL :: LYCVV, LYDAL, LYDOM, LYEDRP, LYEFB1, LYEFB2, LYEFB3, LYERA40, LYEXT, LYEZDIAG
LOGICAL :: LYFORC, LYFQTUR, LYFSD, LYFSTUR, LYG, LYGHG, LYH, LYI, LYICONV, LYIRAD
LOGICAL :: LYL, LYLASTCOMP, LYLCONV, LYLIMA, LYLRAD, LYLRCH4, LYMXL, LYNOGW, LYO3, LYPHYCTY
LOGICAL :: LYPHYS, LYQ, LYQVA, LYR, LYRCONV, LYRKTH, LYRKTQC, LYRKTQV, LYRSPEC, LYS
LOGICAL :: LYSCONV, LYSDSAT, LYSHTUR, LYSLDIA, LYSPF, LYSRC, LYTKE, LYTTE, LYUAL, LYUEN
LOGICAL :: LYUNEBH, LYUOM, LYUVP
WRITE (KLUN) YD%NUMFLDS
WRITE (KLUN) YD%NDERS
WRITE (KLUN) YD%NUMSPFLDS
WRITE (KLUN) YD%NUMGPFLDS
WRITE (KLUN) YD%NUMFLDS9
WRITE (KLUN) YD%NUMFLDS1
WRITE (KLUN) YD%NUMSPFLDS1
WRITE (KLUN) YD%NUMFLDS5
WRITE (KLUN) YD%NUMFLDSPHY
WRITE (KLUN) YD%NUMFLDS_SPL
WRITE (KLUN) YD%NUMFLDS_SL1
WRITE (KLUN) YD%NUMFLDSPC
WRITE (KLUN) YD%NDIM
WRITE (KLUN) YD%NUMFLDSPT
WRITE (KLUN) YD%NDIM0
WRITE (KLUN) YD%NDIM9
WRITE (KLUN) YD%NDIM1
WRITE (KLUN) YD%NDIM5
WRITE (KLUN) YD%NDIMSLP
WRITE (KLUN) YD%NDIM_SPL
WRITE (KLUN) YD%NDIMPT
WRITE (KLUN) YD%NDIMPC
WRITE (KLUN) YD%NGFL_EXT
WRITE (KLUN) YD%NGFL_FORC
WRITE (KLUN) YD%NGFL_EZDIAG
WRITE (KLUN) YD%NGHG
WRITE (KLUN) YD%NGHG_ASSIM
WRITE (KLUN) YD%NAERO
WRITE (KLUN) YD%NACTAERO
WRITE (KLUN) YD%NDDHAERO
WRITE (KLUN) YD%NERA40
WRITE (KLUN) YD%NNOGW
WRITE (KLUN) YD%NEDRP
WRITE (KLUN) YD%NAEROUT
WRITE (KLUN) YD%NAEROCLIM
WRITE (KLUN) YD%NUVP
WRITE (KLUN) YD%NSLDIA
WRITE (KLUN) YD%NSLDIAGP
WRITE (KLUN) YD%NCRM
WRITE (KLUN) YD%NFSD
WRITE (KLUN) YD%LAERCHEM
WRITE (KLUN) YD%LTRCMFIX
WRITE (KLUN) YD%LTRCMFIX_PS
WRITE (KLUN) YD%LAERAOT
WRITE (KLUN) YD%LAERLISI
WRITE (KLUN) YD%LAEROUT
WRITE (KLUN) YD%LAEROCLIM
WRITE (KLUN) YD%LUVPOUT
WRITE (KLUN) YD%LSPPTGFL
WRITE (KLUN) YD%NGEMS
WRITE (KLUN) YD%NCHEM
WRITE (KLUN) YD%NCHEM_ASSIM
WRITE (KLUN) YD%NCHEM_FLX
WRITE (KLUN) YD%NCHEM_FLXO
WRITE (KLUN) YD%NCHEM_DV
WRITE (KLUN) YD%NCHEM_TC
WRITE (KLUN) YD%NCHEM_SCV
WRITE (KLUN) YD%NLIMA
WRITE (KLUN) YD%NAERO_WVL_DIAG
WRITE (KLUN) YD%NAERO_WVL_DIAG_TYPES
WRITE (KLUN) YD%NNEGAFIX
WRITE (KLUN) YD%NOPTNEGFIX
WRITE (KLUN) YD%LQM3DCONS
WRITE (KLUN) YD%LADVNEGFIX
WRITE (KLUN) YD%LTRCMFBC
WRITE (KLUN) YD%LTRCMFPR
WRITE (KLUN) YD%LTRCMFMG
WRITE (KLUN) YD%LTRCMFP
WRITE (KLUN) YD%LTRCMFA_DIF
WRITE (KLUN) YD%LTRCMFA_LAP
WRITE (KLUN) YD%LTRCMFA_VER
WRITE (KLUN) YD%LEXTRADF
WRITE (KLUN) YD%NFLDSFIX
WRITE (KLUN) YD%NOPTMFBC
WRITE (KLUN) YD%NOPTMFPR
WRITE (KLUN) YD%NOPTVFE
WRITE (KLUN) YD%NMFDIAGLEV
WRITE (KLUN) YD%NMFIXFLDS
WRITE (KLUN) YD%NNEGFLDS
WRITE (KLUN) YD%ZMFIXEPS
WRITE (KLUN) YD%NFMG
WRITE (KLUN) YD%NMGFLDS
DO J1 = LBOUND (YD%YCOMP, 1), UBOUND (YD%YCOMP, 1)
  CALL SAVE (KLUN, YD%YCOMP (J1))
ENDDO
LYLASTCOMP = ASSOCIATED (YD%YLASTCOMP)
WRITE (KLUN) LYLASTCOMP
IF (LYLASTCOMP) THEN
  CALL SAVE (KLUN, YD%YLASTCOMP)
ENDIF
LYQ = ASSOCIATED (YD%YQ)
WRITE (KLUN) LYQ
IF (LYQ) THEN
  CALL SAVE (KLUN, YD%YQ)
ENDIF
LYI = ASSOCIATED (YD%YI)
WRITE (KLUN) LYI
IF (LYI) THEN
  CALL SAVE (KLUN, YD%YI)
ENDIF
LYL = ASSOCIATED (YD%YL)
WRITE (KLUN) LYL
IF (LYL) THEN
  CALL SAVE (KLUN, YD%YL)
ENDIF
LYLCONV = ASSOCIATED (YD%YLCONV)
WRITE (KLUN) LYLCONV
IF (LYLCONV) THEN
  CALL SAVE (KLUN, YD%YLCONV)
ENDIF
LYICONV = ASSOCIATED (YD%YICONV)
WRITE (KLUN) LYICONV
IF (LYICONV) THEN
  CALL SAVE (KLUN, YD%YICONV)
ENDIF
LYRCONV = ASSOCIATED (YD%YRCONV)
WRITE (KLUN) LYRCONV
IF (LYRCONV) THEN
  CALL SAVE (KLUN, YD%YRCONV)
ENDIF
LYSCONV = ASSOCIATED (YD%YSCONV)
WRITE (KLUN) LYSCONV
IF (LYSCONV) THEN
  CALL SAVE (KLUN, YD%YSCONV)
ENDIF
LYIRAD = ASSOCIATED (YD%YIRAD)
WRITE (KLUN) LYIRAD
IF (LYIRAD) THEN
  CALL SAVE (KLUN, YD%YIRAD)
ENDIF
LYLRAD = ASSOCIATED (YD%YLRAD)
WRITE (KLUN) LYLRAD
IF (LYLRAD) THEN
  CALL SAVE (KLUN, YD%YLRAD)
ENDIF
LYS = ASSOCIATED (YD%YS)
WRITE (KLUN) LYS
IF (LYS) THEN
  CALL SAVE (KLUN, YD%YS)
ENDIF
LYR = ASSOCIATED (YD%YR)
WRITE (KLUN) LYR
IF (LYR) THEN
  CALL SAVE (KLUN, YD%YR)
ENDIF
LYG = ASSOCIATED (YD%YG)
WRITE (KLUN) LYG
IF (LYG) THEN
  CALL SAVE (KLUN, YD%YG)
ENDIF
LYH = ASSOCIATED (YD%YH)
WRITE (KLUN) LYH
IF (LYH) THEN
  CALL SAVE (KLUN, YD%YH)
ENDIF
LYTKE = ASSOCIATED (YD%YTKE)
WRITE (KLUN) LYTKE
IF (LYTKE) THEN
  CALL SAVE (KLUN, YD%YTKE)
ENDIF
LYTTE = ASSOCIATED (YD%YTTE)
WRITE (KLUN) LYTTE
IF (LYTTE) THEN
  CALL SAVE (KLUN, YD%YTTE)
ENDIF
LYEFB1 = ASSOCIATED (YD%YEFB1)
WRITE (KLUN) LYEFB1
IF (LYEFB1) THEN
  CALL SAVE (KLUN, YD%YEFB1)
ENDIF
LYEFB2 = ASSOCIATED (YD%YEFB2)
WRITE (KLUN) LYEFB2
IF (LYEFB2) THEN
  CALL SAVE (KLUN, YD%YEFB2)
ENDIF
LYEFB3 = ASSOCIATED (YD%YEFB3)
WRITE (KLUN) LYEFB3
IF (LYEFB3) THEN
  CALL SAVE (KLUN, YD%YEFB3)
ENDIF
LYA = ASSOCIATED (YD%YA)
WRITE (KLUN) LYA
IF (LYA) THEN
  CALL SAVE (KLUN, YD%YA)
ENDIF
LYO3 = ASSOCIATED (YD%YO3)
WRITE (KLUN) LYO3
IF (LYO3) THEN
  CALL SAVE (KLUN, YD%YO3)
ENDIF
LYSRC = ASSOCIATED (YD%YSRC)
WRITE (KLUN) LYSRC
IF (LYSRC) THEN
  CALL SAVE (KLUN, YD%YSRC)
ENDIF
LYMXL = ASSOCIATED (YD%YMXL)
WRITE (KLUN) LYMXL
IF (LYMXL) THEN
  CALL SAVE (KLUN, YD%YMXL)
ENDIF
LYSHTUR = ASSOCIATED (YD%YSHTUR)
WRITE (KLUN) LYSHTUR
IF (LYSHTUR) THEN
  CALL SAVE (KLUN, YD%YSHTUR)
ENDIF
LYFQTUR = ASSOCIATED (YD%YFQTUR)
WRITE (KLUN) LYFQTUR
IF (LYFQTUR) THEN
  CALL SAVE (KLUN, YD%YFQTUR)
ENDIF
LYFSTUR = ASSOCIATED (YD%YFSTUR)
WRITE (KLUN) LYFSTUR
IF (LYFSTUR) THEN
  CALL SAVE (KLUN, YD%YFSTUR)
ENDIF
LYCPF = ASSOCIATED (YD%YCPF)
WRITE (KLUN) LYCPF
IF (LYCPF) THEN
  CALL SAVE (KLUN, YD%YCPF)
ENDIF
LYSPF = ASSOCIATED (YD%YSPF)
WRITE (KLUN) LYSPF
IF (LYSPF) THEN
  CALL SAVE (KLUN, YD%YSPF)
ENDIF
LYCVGQ = ASSOCIATED (YD%YCVGQ)
WRITE (KLUN) LYCVGQ
IF (LYCVGQ) THEN
  CALL SAVE (KLUN, YD%YCVGQ)
ENDIF
LYQVA = ASSOCIATED (YD%YQVA)
WRITE (KLUN) LYQVA
IF (LYQVA) THEN
  CALL SAVE (KLUN, YD%YQVA)
ENDIF
LYGHG = ASSOCIATED (YD%YGHG)
WRITE (KLUN) LYGHG
IF (LYGHG) THEN
  WRITE (KLUN) LBOUND (YD%YGHG)
  WRITE (KLUN) UBOUND (YD%YGHG)
  DO J1 = LBOUND (YD%YGHG, 1), UBOUND (YD%YGHG, 1)
    CALL SAVE (KLUN, YD%YGHG (J1))
  ENDDO
ENDIF
LYCHEM = ASSOCIATED (YD%YCHEM)
WRITE (KLUN) LYCHEM
IF (LYCHEM) THEN
  WRITE (KLUN) LBOUND (YD%YCHEM)
  WRITE (KLUN) UBOUND (YD%YCHEM)
  DO J1 = LBOUND (YD%YCHEM, 1), UBOUND (YD%YCHEM, 1)
    CALL SAVE (KLUN, YD%YCHEM (J1))
  ENDDO
ENDIF
LYAERO = ASSOCIATED (YD%YAERO)
WRITE (KLUN) LYAERO
IF (LYAERO) THEN
  WRITE (KLUN) LBOUND (YD%YAERO)
  WRITE (KLUN) UBOUND (YD%YAERO)
  DO J1 = LBOUND (YD%YAERO, 1), UBOUND (YD%YAERO, 1)
    CALL SAVE (KLUN, YD%YAERO (J1))
  ENDDO
ENDIF
LYLRCH4 = ASSOCIATED (YD%YLRCH4)
WRITE (KLUN) LYLRCH4
IF (LYLRCH4) THEN
  CALL SAVE (KLUN, YD%YLRCH4)
ENDIF
LYFORC = ASSOCIATED (YD%YFORC)
WRITE (KLUN) LYFORC
IF (LYFORC) THEN
  WRITE (KLUN) LBOUND (YD%YFORC)
  WRITE (KLUN) UBOUND (YD%YFORC)
  DO J1 = LBOUND (YD%YFORC, 1), UBOUND (YD%YFORC, 1)
    CALL SAVE (KLUN, YD%YFORC (J1))
  ENDDO
ENDIF
LYEZDIAG = ASSOCIATED (YD%YEZDIAG)
WRITE (KLUN) LYEZDIAG
IF (LYEZDIAG) THEN
  WRITE (KLUN) LBOUND (YD%YEZDIAG)
  WRITE (KLUN) UBOUND (YD%YEZDIAG)
  DO J1 = LBOUND (YD%YEZDIAG, 1), UBOUND (YD%YEZDIAG, 1)
    CALL SAVE (KLUN, YD%YEZDIAG (J1))
  ENDDO
ENDIF
LYERA40 = ASSOCIATED (YD%YERA40)
WRITE (KLUN) LYERA40
IF (LYERA40) THEN
  WRITE (KLUN) LBOUND (YD%YERA40)
  WRITE (KLUN) UBOUND (YD%YERA40)
  DO J1 = LBOUND (YD%YERA40, 1), UBOUND (YD%YERA40, 1)
    CALL SAVE (KLUN, YD%YERA40 (J1))
  ENDDO
ENDIF
LYNOGW = ASSOCIATED (YD%YNOGW)
WRITE (KLUN) LYNOGW
IF (LYNOGW) THEN
  WRITE (KLUN) LBOUND (YD%YNOGW)
  WRITE (KLUN) UBOUND (YD%YNOGW)
  DO J1 = LBOUND (YD%YNOGW, 1), UBOUND (YD%YNOGW, 1)
    CALL SAVE (KLUN, YD%YNOGW (J1))
  ENDDO
ENDIF
LYEDRP = ASSOCIATED (YD%YEDRP)
WRITE (KLUN) LYEDRP
IF (LYEDRP) THEN
  WRITE (KLUN) LBOUND (YD%YEDRP)
  WRITE (KLUN) UBOUND (YD%YEDRP)
  DO J1 = LBOUND (YD%YEDRP, 1), UBOUND (YD%YEDRP, 1)
    CALL SAVE (KLUN, YD%YEDRP (J1))
  ENDDO
ENDIF
LYSLDIA = ASSOCIATED (YD%YSLDIA)
WRITE (KLUN) LYSLDIA
IF (LYSLDIA) THEN
  WRITE (KLUN) LBOUND (YD%YSLDIA)
  WRITE (KLUN) UBOUND (YD%YSLDIA)
  DO J1 = LBOUND (YD%YSLDIA, 1), UBOUND (YD%YSLDIA, 1)
    CALL SAVE (KLUN, YD%YSLDIA (J1))
  ENDDO
ENDIF
LYAERAOT = ASSOCIATED (YD%YAERAOT)
WRITE (KLUN) LYAERAOT
IF (LYAERAOT) THEN
  WRITE (KLUN) LBOUND (YD%YAERAOT)
  WRITE (KLUN) UBOUND (YD%YAERAOT)
  DO J1 = LBOUND (YD%YAERAOT, 1), UBOUND (YD%YAERAOT, 1)
    CALL SAVE (KLUN, YD%YAERAOT (J1))
  ENDDO
ENDIF
LYAERLISI = ASSOCIATED (YD%YAERLISI)
WRITE (KLUN) LYAERLISI
IF (LYAERLISI) THEN
  WRITE (KLUN) LBOUND (YD%YAERLISI)
  WRITE (KLUN) UBOUND (YD%YAERLISI)
  DO J1 = LBOUND (YD%YAERLISI, 1), UBOUND (YD%YAERLISI, 1)
    CALL SAVE (KLUN, YD%YAERLISI (J1))
  ENDDO
ENDIF
LYAEROUT = ASSOCIATED (YD%YAEROUT)
WRITE (KLUN) LYAEROUT
IF (LYAEROUT) THEN
  WRITE (KLUN) LBOUND (YD%YAEROUT)
  WRITE (KLUN) UBOUND (YD%YAEROUT)
  DO J1 = LBOUND (YD%YAEROUT, 1), UBOUND (YD%YAEROUT, 1)
    CALL SAVE (KLUN, YD%YAEROUT (J1))
  ENDDO
ENDIF
LYAEROCLIM = ASSOCIATED (YD%YAEROCLIM)
WRITE (KLUN) LYAEROCLIM
IF (LYAEROCLIM) THEN
  WRITE (KLUN) LBOUND (YD%YAEROCLIM)
  WRITE (KLUN) UBOUND (YD%YAEROCLIM)
  DO J1 = LBOUND (YD%YAEROCLIM, 1), UBOUND (YD%YAEROCLIM, 1)
    CALL SAVE (KLUN, YD%YAEROCLIM (J1))
  ENDDO
ENDIF
LYUVP = ASSOCIATED (YD%YUVP)
WRITE (KLUN) LYUVP
IF (LYUVP) THEN
  WRITE (KLUN) LBOUND (YD%YUVP)
  WRITE (KLUN) UBOUND (YD%YUVP)
  DO J1 = LBOUND (YD%YUVP, 1), UBOUND (YD%YUVP, 1)
    CALL SAVE (KLUN, YD%YUVP (J1))
  ENDDO
ENDIF
LYPHYS = ASSOCIATED (YD%YPHYS)
WRITE (KLUN) LYPHYS
IF (LYPHYS) THEN
  WRITE (KLUN) LBOUND (YD%YPHYS)
  WRITE (KLUN) UBOUND (YD%YPHYS)
  DO J1 = LBOUND (YD%YPHYS, 1), UBOUND (YD%YPHYS, 1)
    CALL SAVE (KLUN, YD%YPHYS (J1))
  ENDDO
ENDIF
LYPHYCTY = ASSOCIATED (YD%YPHYCTY)
WRITE (KLUN) LYPHYCTY
IF (LYPHYCTY) THEN
  CALL SAVE (KLUN, YD%YPHYCTY)
ENDIF
LYRSPEC = ASSOCIATED (YD%YRSPEC)
WRITE (KLUN) LYRSPEC
IF (LYRSPEC) THEN
  CALL SAVE (KLUN, YD%YRSPEC)
ENDIF
LYSDSAT = ASSOCIATED (YD%YSDSAT)
WRITE (KLUN) LYSDSAT
IF (LYSDSAT) THEN
  CALL SAVE (KLUN, YD%YSDSAT)
ENDIF
LYCVV = ASSOCIATED (YD%YCVV)
WRITE (KLUN) LYCVV
IF (LYCVV) THEN
  CALL SAVE (KLUN, YD%YCVV)
ENDIF
LYRKTH = ASSOCIATED (YD%YRKTH)
WRITE (KLUN) LYRKTH
IF (LYRKTH) THEN
  CALL SAVE (KLUN, YD%YRKTH)
ENDIF
LYRKTQV = ASSOCIATED (YD%YRKTQV)
WRITE (KLUN) LYRKTQV
IF (LYRKTQV) THEN
  CALL SAVE (KLUN, YD%YRKTQV)
ENDIF
LYRKTQC = ASSOCIATED (YD%YRKTQC)
WRITE (KLUN) LYRKTQC
IF (LYRKTQC) THEN
  CALL SAVE (KLUN, YD%YRKTQC)
ENDIF
LYUOM = ASSOCIATED (YD%YUOM)
WRITE (KLUN) LYUOM
IF (LYUOM) THEN
  CALL SAVE (KLUN, YD%YUOM)
ENDIF
LYUAL = ASSOCIATED (YD%YUAL)
WRITE (KLUN) LYUAL
IF (LYUAL) THEN
  CALL SAVE (KLUN, YD%YUAL)
ENDIF
LYDOM = ASSOCIATED (YD%YDOM)
WRITE (KLUN) LYDOM
IF (LYDOM) THEN
  CALL SAVE (KLUN, YD%YDOM)
ENDIF
LYDAL = ASSOCIATED (YD%YDAL)
WRITE (KLUN) LYDAL
IF (LYDAL) THEN
  CALL SAVE (KLUN, YD%YDAL)
ENDIF
LYUEN = ASSOCIATED (YD%YUEN)
WRITE (KLUN) LYUEN
IF (LYUEN) THEN
  CALL SAVE (KLUN, YD%YUEN)
ENDIF
LYUNEBH = ASSOCIATED (YD%YUNEBH)
WRITE (KLUN) LYUNEBH
IF (LYUNEBH) THEN
  CALL SAVE (KLUN, YD%YUNEBH)
ENDIF
LYCRM = ASSOCIATED (YD%YCRM)
WRITE (KLUN) LYCRM
IF (LYCRM) THEN
  WRITE (KLUN) LBOUND (YD%YCRM)
  WRITE (KLUN) UBOUND (YD%YCRM)
  DO J1 = LBOUND (YD%YCRM, 1), UBOUND (YD%YCRM, 1)
    CALL SAVE (KLUN, YD%YCRM (J1))
  ENDDO
ENDIF
LYLIMA = ASSOCIATED (YD%YLIMA)
WRITE (KLUN) LYLIMA
IF (LYLIMA) THEN
  WRITE (KLUN) LBOUND (YD%YLIMA)
  WRITE (KLUN) UBOUND (YD%YLIMA)
  DO J1 = LBOUND (YD%YLIMA, 1), UBOUND (YD%YLIMA, 1)
    CALL SAVE (KLUN, YD%YLIMA (J1))
  ENDDO
ENDIF
LYFSD = ASSOCIATED (YD%YFSD)
WRITE (KLUN) LYFSD
IF (LYFSD) THEN
  CALL SAVE (KLUN, YD%YFSD)
ENDIF
LYEXT = ASSOCIATED (YD%YEXT)
WRITE (KLUN) LYEXT
IF (LYEXT) THEN
  WRITE (KLUN) LBOUND (YD%YEXT)
  WRITE (KLUN) UBOUND (YD%YEXT)
  DO J1 = LBOUND (YD%YEXT, 1), UBOUND (YD%YEXT, 1)
    CALL SAVE (KLUN, YD%YEXT (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YQ_NL)
CALL SAVE (KLUN, YD%YI_NL)
CALL SAVE (KLUN, YD%YL_NL)
CALL SAVE (KLUN, YD%YLCONV_NL)
CALL SAVE (KLUN, YD%YICONV_NL)
CALL SAVE (KLUN, YD%YRCONV_NL)
CALL SAVE (KLUN, YD%YSCONV_NL)
CALL SAVE (KLUN, YD%YIRAD_NL)
CALL SAVE (KLUN, YD%YLRAD_NL)
CALL SAVE (KLUN, YD%YS_NL)
CALL SAVE (KLUN, YD%YR_NL)
CALL SAVE (KLUN, YD%YG_NL)
CALL SAVE (KLUN, YD%YH_NL)
CALL SAVE (KLUN, YD%YTKE_NL)
CALL SAVE (KLUN, YD%YTTE_NL)
CALL SAVE (KLUN, YD%YEFB1_NL)
CALL SAVE (KLUN, YD%YEFB2_NL)
CALL SAVE (KLUN, YD%YEFB3_NL)
CALL SAVE (KLUN, YD%YA_NL)
CALL SAVE (KLUN, YD%YO3_NL)
CALL SAVE (KLUN, YD%YSRC_NL)
CALL SAVE (KLUN, YD%YMXL_NL)
CALL SAVE (KLUN, YD%YSHTUR_NL)
CALL SAVE (KLUN, YD%YFQTUR_NL)
CALL SAVE (KLUN, YD%YFSTUR_NL)
CALL SAVE (KLUN, YD%YCPF_NL)
CALL SAVE (KLUN, YD%YSPF_NL)
CALL SAVE (KLUN, YD%YCVGQ_NL)
CALL SAVE (KLUN, YD%YQVA_NL)
DO J1 = LBOUND (YD%YGHG_NL, 1), UBOUND (YD%YGHG_NL, 1)
  CALL SAVE (KLUN, YD%YGHG_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YCHEM_NL, 1), UBOUND (YD%YCHEM_NL, 1)
  CALL SAVE (KLUN, YD%YCHEM_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YAERO_NL, 1), UBOUND (YD%YAERO_NL, 1)
  CALL SAVE (KLUN, YD%YAERO_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YERA40_NL, 1), UBOUND (YD%YERA40_NL, 1)
  CALL SAVE (KLUN, YD%YERA40_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YNOGW_NL, 1), UBOUND (YD%YNOGW_NL, 1)
  CALL SAVE (KLUN, YD%YNOGW_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YEDRP_NL, 1), UBOUND (YD%YEDRP_NL, 1)
  CALL SAVE (KLUN, YD%YEDRP_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YSLDIA_NL, 1), UBOUND (YD%YSLDIA_NL, 1)
  CALL SAVE (KLUN, YD%YSLDIA_NL (J1))
ENDDO
CALL SAVE (KLUN, YD%YLRCH4_NL)
DO J1 = LBOUND (YD%YAERAOT_NL, 1), UBOUND (YD%YAERAOT_NL, 1)
  CALL SAVE (KLUN, YD%YAERAOT_NL (J1))
ENDDO
DO J2 = LBOUND (YD%YAERLISI_NL, 2), UBOUND (YD%YAERLISI_NL, 2)
  DO J1 = LBOUND (YD%YAERLISI_NL, 1), UBOUND (YD%YAERLISI_NL, 1)
    CALL SAVE (KLUN, YD%YAERLISI_NL (J1, J2))
  ENDDO
ENDDO
DO J1 = LBOUND (YD%YAEROUT_NL, 1), UBOUND (YD%YAEROUT_NL, 1)
  CALL SAVE (KLUN, YD%YAEROUT_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YAEROCLIM_NL, 1), UBOUND (YD%YAEROCLIM_NL, 1)
  CALL SAVE (KLUN, YD%YAEROCLIM_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YUVP_NL, 1), UBOUND (YD%YUVP_NL, 1)
  CALL SAVE (KLUN, YD%YUVP_NL (J1))
ENDDO
CALL SAVE (KLUN, YD%YRKTH_NL)
CALL SAVE (KLUN, YD%YRKTQV_NL)
CALL SAVE (KLUN, YD%YRKTQC_NL)
DO J1 = LBOUND (YD%YCRM_NL, 1), UBOUND (YD%YCRM_NL, 1)
  CALL SAVE (KLUN, YD%YCRM_NL (J1))
ENDDO
CALL SAVE (KLUN, YD%YPHYCTY_NL)
CALL SAVE (KLUN, YD%YFSD_NL)
CALL SAVE (KLUN, YD%YRSPEC_NL)
CALL SAVE (KLUN, YD%YSDSAT_NL)
CALL SAVE (KLUN, YD%YCVV_NL)
DO J1 = LBOUND (YD%YFORC_NL, 1), UBOUND (YD%YFORC_NL, 1)
  CALL SAVE (KLUN, YD%YFORC_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YEZDIAG_NL, 1), UBOUND (YD%YEZDIAG_NL, 1)
  CALL SAVE (KLUN, YD%YEZDIAG_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YEXT_NL, 1), UBOUND (YD%YEXT_NL, 1)
  CALL SAVE (KLUN, YD%YEXT_NL (J1))
ENDDO
CALL SAVE (KLUN, YD%YUOM_NL)
CALL SAVE (KLUN, YD%YUAL_NL)
CALL SAVE (KLUN, YD%YDOM_NL)
CALL SAVE (KLUN, YD%YDAL_NL)
CALL SAVE (KLUN, YD%YUEN_NL)
CALL SAVE (KLUN, YD%YUNEBH_NL)
DO J1 = LBOUND (YD%YAERO_WVL_DIAG_NL, 1), UBOUND (YD%YAERO_WVL_DIAG_NL, 1)
  CALL SAVE (KLUN, YD%YAERO_WVL_DIAG_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YLIMA_NL, 1), UBOUND (YD%YLIMA_NL, 1)
  CALL SAVE (KLUN, YD%YLIMA_NL (J1))
ENDDO
END SUBROUTINE

SUBROUTINE LOAD_TYPE_GFLD (KLUN, YD)
USE UTIL_TYPE_AERO_WVL_DIAG_MOD
USE UTIL_TYPE_GFL_COMP_MOD
USE UTIL_TYPE_GFL_NAML_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFLD), INTENT (OUT), TARGET :: YD
INTEGER :: J1, J2
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYA, LYAERAOT, LYAERLISI, LYAERO, LYAEROCLIM, LYAEROUT, LYCHEM, LYCPF, LYCRM, LYCVGQ
LOGICAL :: LYCVV, LYDAL, LYDOM, LYEDRP, LYEFB1, LYEFB2, LYEFB3, LYERA40, LYEXT, LYEZDIAG
LOGICAL :: LYFORC, LYFQTUR, LYFSD, LYFSTUR, LYG, LYGHG, LYH, LYI, LYICONV, LYIRAD
LOGICAL :: LYL, LYLASTCOMP, LYLCONV, LYLIMA, LYLRAD, LYLRCH4, LYMXL, LYNOGW, LYO3, LYPHYCTY
LOGICAL :: LYPHYS, LYQ, LYQVA, LYR, LYRCONV, LYRKTH, LYRKTQC, LYRKTQV, LYRSPEC, LYS
LOGICAL :: LYSCONV, LYSDSAT, LYSHTUR, LYSLDIA, LYSPF, LYSRC, LYTKE, LYTTE, LYUAL, LYUEN
LOGICAL :: LYUNEBH, LYUOM, LYUVP
READ (KLUN) YD%NUMFLDS
READ (KLUN) YD%NDERS
READ (KLUN) YD%NUMSPFLDS
READ (KLUN) YD%NUMGPFLDS
READ (KLUN) YD%NUMFLDS9
READ (KLUN) YD%NUMFLDS1
READ (KLUN) YD%NUMSPFLDS1
READ (KLUN) YD%NUMFLDS5
READ (KLUN) YD%NUMFLDSPHY
READ (KLUN) YD%NUMFLDS_SPL
READ (KLUN) YD%NUMFLDS_SL1
READ (KLUN) YD%NUMFLDSPC
READ (KLUN) YD%NDIM
READ (KLUN) YD%NUMFLDSPT
READ (KLUN) YD%NDIM0
READ (KLUN) YD%NDIM9
READ (KLUN) YD%NDIM1
READ (KLUN) YD%NDIM5
READ (KLUN) YD%NDIMSLP
READ (KLUN) YD%NDIM_SPL
READ (KLUN) YD%NDIMPT
READ (KLUN) YD%NDIMPC
READ (KLUN) YD%NGFL_EXT
READ (KLUN) YD%NGFL_FORC
READ (KLUN) YD%NGFL_EZDIAG
READ (KLUN) YD%NGHG
READ (KLUN) YD%NGHG_ASSIM
READ (KLUN) YD%NAERO
READ (KLUN) YD%NACTAERO
READ (KLUN) YD%NDDHAERO
READ (KLUN) YD%NERA40
READ (KLUN) YD%NNOGW
READ (KLUN) YD%NEDRP
READ (KLUN) YD%NAEROUT
READ (KLUN) YD%NAEROCLIM
READ (KLUN) YD%NUVP
READ (KLUN) YD%NSLDIA
READ (KLUN) YD%NSLDIAGP
READ (KLUN) YD%NCRM
READ (KLUN) YD%NFSD
READ (KLUN) YD%LAERCHEM
READ (KLUN) YD%LTRCMFIX
READ (KLUN) YD%LTRCMFIX_PS
READ (KLUN) YD%LAERAOT
READ (KLUN) YD%LAERLISI
READ (KLUN) YD%LAEROUT
READ (KLUN) YD%LAEROCLIM
READ (KLUN) YD%LUVPOUT
READ (KLUN) YD%LSPPTGFL
READ (KLUN) YD%NGEMS
READ (KLUN) YD%NCHEM
READ (KLUN) YD%NCHEM_ASSIM
READ (KLUN) YD%NCHEM_FLX
READ (KLUN) YD%NCHEM_FLXO
READ (KLUN) YD%NCHEM_DV
READ (KLUN) YD%NCHEM_TC
READ (KLUN) YD%NCHEM_SCV
READ (KLUN) YD%NLIMA
READ (KLUN) YD%NAERO_WVL_DIAG
READ (KLUN) YD%NAERO_WVL_DIAG_TYPES
READ (KLUN) YD%NNEGAFIX
READ (KLUN) YD%NOPTNEGFIX
READ (KLUN) YD%LQM3DCONS
READ (KLUN) YD%LADVNEGFIX
READ (KLUN) YD%LTRCMFBC
READ (KLUN) YD%LTRCMFPR
READ (KLUN) YD%LTRCMFMG
READ (KLUN) YD%LTRCMFP
READ (KLUN) YD%LTRCMFA_DIF
READ (KLUN) YD%LTRCMFA_LAP
READ (KLUN) YD%LTRCMFA_VER
READ (KLUN) YD%LEXTRADF
READ (KLUN) YD%NFLDSFIX
READ (KLUN) YD%NOPTMFBC
READ (KLUN) YD%NOPTMFPR
READ (KLUN) YD%NOPTVFE
READ (KLUN) YD%NMFDIAGLEV
READ (KLUN) YD%NMFIXFLDS
READ (KLUN) YD%NNEGFLDS
READ (KLUN) YD%ZMFIXEPS
READ (KLUN) YD%NFMG
READ (KLUN) YD%NMGFLDS
DO J1 = LBOUND (YD%YCOMP, 1), UBOUND (YD%YCOMP, 1)
  CALL LOAD (KLUN, YD%YCOMP (J1))
ENDDO
READ (KLUN) LYLASTCOMP
IF (LYLASTCOMP) THEN
  ALLOCATE (YD%YLASTCOMP)
  CALL LOAD (KLUN, YD%YLASTCOMP)
ELSE
  NULLIFY (YD%YLASTCOMP)
ENDIF
READ (KLUN) LYQ
IF (LYQ) THEN
  ALLOCATE (YD%YQ)
  CALL LOAD (KLUN, YD%YQ)
ELSE
  NULLIFY (YD%YQ)
ENDIF
READ (KLUN) LYI
IF (LYI) THEN
  ALLOCATE (YD%YI)
  CALL LOAD (KLUN, YD%YI)
ELSE
  NULLIFY (YD%YI)
ENDIF
READ (KLUN) LYL
IF (LYL) THEN
  ALLOCATE (YD%YL)
  CALL LOAD (KLUN, YD%YL)
ELSE
  NULLIFY (YD%YL)
ENDIF
READ (KLUN) LYLCONV
IF (LYLCONV) THEN
  ALLOCATE (YD%YLCONV)
  CALL LOAD (KLUN, YD%YLCONV)
ELSE
  NULLIFY (YD%YLCONV)
ENDIF
READ (KLUN) LYICONV
IF (LYICONV) THEN
  ALLOCATE (YD%YICONV)
  CALL LOAD (KLUN, YD%YICONV)
ELSE
  NULLIFY (YD%YICONV)
ENDIF
READ (KLUN) LYRCONV
IF (LYRCONV) THEN
  ALLOCATE (YD%YRCONV)
  CALL LOAD (KLUN, YD%YRCONV)
ELSE
  NULLIFY (YD%YRCONV)
ENDIF
READ (KLUN) LYSCONV
IF (LYSCONV) THEN
  ALLOCATE (YD%YSCONV)
  CALL LOAD (KLUN, YD%YSCONV)
ELSE
  NULLIFY (YD%YSCONV)
ENDIF
READ (KLUN) LYIRAD
IF (LYIRAD) THEN
  ALLOCATE (YD%YIRAD)
  CALL LOAD (KLUN, YD%YIRAD)
ELSE
  NULLIFY (YD%YIRAD)
ENDIF
READ (KLUN) LYLRAD
IF (LYLRAD) THEN
  ALLOCATE (YD%YLRAD)
  CALL LOAD (KLUN, YD%YLRAD)
ELSE
  NULLIFY (YD%YLRAD)
ENDIF
READ (KLUN) LYS
IF (LYS) THEN
  ALLOCATE (YD%YS)
  CALL LOAD (KLUN, YD%YS)
ELSE
  NULLIFY (YD%YS)
ENDIF
READ (KLUN) LYR
IF (LYR) THEN
  ALLOCATE (YD%YR)
  CALL LOAD (KLUN, YD%YR)
ELSE
  NULLIFY (YD%YR)
ENDIF
READ (KLUN) LYG
IF (LYG) THEN
  ALLOCATE (YD%YG)
  CALL LOAD (KLUN, YD%YG)
ELSE
  NULLIFY (YD%YG)
ENDIF
READ (KLUN) LYH
IF (LYH) THEN
  ALLOCATE (YD%YH)
  CALL LOAD (KLUN, YD%YH)
ELSE
  NULLIFY (YD%YH)
ENDIF
READ (KLUN) LYTKE
IF (LYTKE) THEN
  ALLOCATE (YD%YTKE)
  CALL LOAD (KLUN, YD%YTKE)
ELSE
  NULLIFY (YD%YTKE)
ENDIF
READ (KLUN) LYTTE
IF (LYTTE) THEN
  ALLOCATE (YD%YTTE)
  CALL LOAD (KLUN, YD%YTTE)
ELSE
  NULLIFY (YD%YTTE)
ENDIF
READ (KLUN) LYEFB1
IF (LYEFB1) THEN
  ALLOCATE (YD%YEFB1)
  CALL LOAD (KLUN, YD%YEFB1)
ELSE
  NULLIFY (YD%YEFB1)
ENDIF
READ (KLUN) LYEFB2
IF (LYEFB2) THEN
  ALLOCATE (YD%YEFB2)
  CALL LOAD (KLUN, YD%YEFB2)
ELSE
  NULLIFY (YD%YEFB2)
ENDIF
READ (KLUN) LYEFB3
IF (LYEFB3) THEN
  ALLOCATE (YD%YEFB3)
  CALL LOAD (KLUN, YD%YEFB3)
ELSE
  NULLIFY (YD%YEFB3)
ENDIF
READ (KLUN) LYA
IF (LYA) THEN
  ALLOCATE (YD%YA)
  CALL LOAD (KLUN, YD%YA)
ELSE
  NULLIFY (YD%YA)
ENDIF
READ (KLUN) LYO3
IF (LYO3) THEN
  ALLOCATE (YD%YO3)
  CALL LOAD (KLUN, YD%YO3)
ELSE
  NULLIFY (YD%YO3)
ENDIF
READ (KLUN) LYSRC
IF (LYSRC) THEN
  ALLOCATE (YD%YSRC)
  CALL LOAD (KLUN, YD%YSRC)
ELSE
  NULLIFY (YD%YSRC)
ENDIF
READ (KLUN) LYMXL
IF (LYMXL) THEN
  ALLOCATE (YD%YMXL)
  CALL LOAD (KLUN, YD%YMXL)
ELSE
  NULLIFY (YD%YMXL)
ENDIF
READ (KLUN) LYSHTUR
IF (LYSHTUR) THEN
  ALLOCATE (YD%YSHTUR)
  CALL LOAD (KLUN, YD%YSHTUR)
ELSE
  NULLIFY (YD%YSHTUR)
ENDIF
READ (KLUN) LYFQTUR
IF (LYFQTUR) THEN
  ALLOCATE (YD%YFQTUR)
  CALL LOAD (KLUN, YD%YFQTUR)
ELSE
  NULLIFY (YD%YFQTUR)
ENDIF
READ (KLUN) LYFSTUR
IF (LYFSTUR) THEN
  ALLOCATE (YD%YFSTUR)
  CALL LOAD (KLUN, YD%YFSTUR)
ELSE
  NULLIFY (YD%YFSTUR)
ENDIF
READ (KLUN) LYCPF
IF (LYCPF) THEN
  ALLOCATE (YD%YCPF)
  CALL LOAD (KLUN, YD%YCPF)
ELSE
  NULLIFY (YD%YCPF)
ENDIF
READ (KLUN) LYSPF
IF (LYSPF) THEN
  ALLOCATE (YD%YSPF)
  CALL LOAD (KLUN, YD%YSPF)
ELSE
  NULLIFY (YD%YSPF)
ENDIF
READ (KLUN) LYCVGQ
IF (LYCVGQ) THEN
  ALLOCATE (YD%YCVGQ)
  CALL LOAD (KLUN, YD%YCVGQ)
ELSE
  NULLIFY (YD%YCVGQ)
ENDIF
READ (KLUN) LYQVA
IF (LYQVA) THEN
  ALLOCATE (YD%YQVA)
  CALL LOAD (KLUN, YD%YQVA)
ELSE
  NULLIFY (YD%YQVA)
ENDIF
READ (KLUN) LYGHG
IF (LYGHG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YGHG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YGHG, 1), UBOUND (YD%YGHG, 1)
    CALL LOAD (KLUN, YD%YGHG (J1))
  ENDDO
ELSE
  NULLIFY (YD%YGHG)
ENDIF
READ (KLUN) LYCHEM
IF (LYCHEM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YCHEM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YCHEM, 1), UBOUND (YD%YCHEM, 1)
    CALL LOAD (KLUN, YD%YCHEM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YCHEM)
ENDIF
READ (KLUN) LYAERO
IF (LYAERO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YAERO (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAERO, 1), UBOUND (YD%YAERO, 1)
    CALL LOAD (KLUN, YD%YAERO (J1))
  ENDDO
ELSE
  NULLIFY (YD%YAERO)
ENDIF
READ (KLUN) LYLRCH4
IF (LYLRCH4) THEN
  ALLOCATE (YD%YLRCH4)
  CALL LOAD (KLUN, YD%YLRCH4)
ELSE
  NULLIFY (YD%YLRCH4)
ENDIF
READ (KLUN) LYFORC
IF (LYFORC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YFORC (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YFORC, 1), UBOUND (YD%YFORC, 1)
    CALL LOAD (KLUN, YD%YFORC (J1))
  ENDDO
ELSE
  NULLIFY (YD%YFORC)
ENDIF
READ (KLUN) LYEZDIAG
IF (LYEZDIAG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YEZDIAG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YEZDIAG, 1), UBOUND (YD%YEZDIAG, 1)
    CALL LOAD (KLUN, YD%YEZDIAG (J1))
  ENDDO
ELSE
  NULLIFY (YD%YEZDIAG)
ENDIF
READ (KLUN) LYERA40
IF (LYERA40) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YERA40 (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YERA40, 1), UBOUND (YD%YERA40, 1)
    CALL LOAD (KLUN, YD%YERA40 (J1))
  ENDDO
ELSE
  NULLIFY (YD%YERA40)
ENDIF
READ (KLUN) LYNOGW
IF (LYNOGW) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YNOGW (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YNOGW, 1), UBOUND (YD%YNOGW, 1)
    CALL LOAD (KLUN, YD%YNOGW (J1))
  ENDDO
ELSE
  NULLIFY (YD%YNOGW)
ENDIF
READ (KLUN) LYEDRP
IF (LYEDRP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YEDRP (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YEDRP, 1), UBOUND (YD%YEDRP, 1)
    CALL LOAD (KLUN, YD%YEDRP (J1))
  ENDDO
ELSE
  NULLIFY (YD%YEDRP)
ENDIF
READ (KLUN) LYSLDIA
IF (LYSLDIA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YSLDIA (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YSLDIA, 1), UBOUND (YD%YSLDIA, 1)
    CALL LOAD (KLUN, YD%YSLDIA (J1))
  ENDDO
ELSE
  NULLIFY (YD%YSLDIA)
ENDIF
READ (KLUN) LYAERAOT
IF (LYAERAOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YAERAOT (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAERAOT, 1), UBOUND (YD%YAERAOT, 1)
    CALL LOAD (KLUN, YD%YAERAOT (J1))
  ENDDO
ELSE
  NULLIFY (YD%YAERAOT)
ENDIF
READ (KLUN) LYAERLISI
IF (LYAERLISI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YAERLISI (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAERLISI, 1), UBOUND (YD%YAERLISI, 1)
    CALL LOAD (KLUN, YD%YAERLISI (J1))
  ENDDO
ELSE
  NULLIFY (YD%YAERLISI)
ENDIF
READ (KLUN) LYAEROUT
IF (LYAEROUT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YAEROUT (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAEROUT, 1), UBOUND (YD%YAEROUT, 1)
    CALL LOAD (KLUN, YD%YAEROUT (J1))
  ENDDO
ELSE
  NULLIFY (YD%YAEROUT)
ENDIF
READ (KLUN) LYAEROCLIM
IF (LYAEROCLIM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YAEROCLIM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAEROCLIM, 1), UBOUND (YD%YAEROCLIM, 1)
    CALL LOAD (KLUN, YD%YAEROCLIM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YAEROCLIM)
ENDIF
READ (KLUN) LYUVP
IF (LYUVP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YUVP (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YUVP, 1), UBOUND (YD%YUVP, 1)
    CALL LOAD (KLUN, YD%YUVP (J1))
  ENDDO
ELSE
  NULLIFY (YD%YUVP)
ENDIF
READ (KLUN) LYPHYS
IF (LYPHYS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YPHYS (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YPHYS, 1), UBOUND (YD%YPHYS, 1)
    CALL LOAD (KLUN, YD%YPHYS (J1))
  ENDDO
ELSE
  NULLIFY (YD%YPHYS)
ENDIF
READ (KLUN) LYPHYCTY
IF (LYPHYCTY) THEN
  ALLOCATE (YD%YPHYCTY)
  CALL LOAD (KLUN, YD%YPHYCTY)
ELSE
  NULLIFY (YD%YPHYCTY)
ENDIF
READ (KLUN) LYRSPEC
IF (LYRSPEC) THEN
  ALLOCATE (YD%YRSPEC)
  CALL LOAD (KLUN, YD%YRSPEC)
ELSE
  NULLIFY (YD%YRSPEC)
ENDIF
READ (KLUN) LYSDSAT
IF (LYSDSAT) THEN
  ALLOCATE (YD%YSDSAT)
  CALL LOAD (KLUN, YD%YSDSAT)
ELSE
  NULLIFY (YD%YSDSAT)
ENDIF
READ (KLUN) LYCVV
IF (LYCVV) THEN
  ALLOCATE (YD%YCVV)
  CALL LOAD (KLUN, YD%YCVV)
ELSE
  NULLIFY (YD%YCVV)
ENDIF
READ (KLUN) LYRKTH
IF (LYRKTH) THEN
  ALLOCATE (YD%YRKTH)
  CALL LOAD (KLUN, YD%YRKTH)
ELSE
  NULLIFY (YD%YRKTH)
ENDIF
READ (KLUN) LYRKTQV
IF (LYRKTQV) THEN
  ALLOCATE (YD%YRKTQV)
  CALL LOAD (KLUN, YD%YRKTQV)
ELSE
  NULLIFY (YD%YRKTQV)
ENDIF
READ (KLUN) LYRKTQC
IF (LYRKTQC) THEN
  ALLOCATE (YD%YRKTQC)
  CALL LOAD (KLUN, YD%YRKTQC)
ELSE
  NULLIFY (YD%YRKTQC)
ENDIF
READ (KLUN) LYUOM
IF (LYUOM) THEN
  ALLOCATE (YD%YUOM)
  CALL LOAD (KLUN, YD%YUOM)
ELSE
  NULLIFY (YD%YUOM)
ENDIF
READ (KLUN) LYUAL
IF (LYUAL) THEN
  ALLOCATE (YD%YUAL)
  CALL LOAD (KLUN, YD%YUAL)
ELSE
  NULLIFY (YD%YUAL)
ENDIF
READ (KLUN) LYDOM
IF (LYDOM) THEN
  ALLOCATE (YD%YDOM)
  CALL LOAD (KLUN, YD%YDOM)
ELSE
  NULLIFY (YD%YDOM)
ENDIF
READ (KLUN) LYDAL
IF (LYDAL) THEN
  ALLOCATE (YD%YDAL)
  CALL LOAD (KLUN, YD%YDAL)
ELSE
  NULLIFY (YD%YDAL)
ENDIF
READ (KLUN) LYUEN
IF (LYUEN) THEN
  ALLOCATE (YD%YUEN)
  CALL LOAD (KLUN, YD%YUEN)
ELSE
  NULLIFY (YD%YUEN)
ENDIF
READ (KLUN) LYUNEBH
IF (LYUNEBH) THEN
  ALLOCATE (YD%YUNEBH)
  CALL LOAD (KLUN, YD%YUNEBH)
ELSE
  NULLIFY (YD%YUNEBH)
ENDIF
READ (KLUN) LYCRM
IF (LYCRM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YCRM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YCRM, 1), UBOUND (YD%YCRM, 1)
    CALL LOAD (KLUN, YD%YCRM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YCRM)
ENDIF
READ (KLUN) LYLIMA
IF (LYLIMA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YLIMA (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YLIMA, 1), UBOUND (YD%YLIMA, 1)
    CALL LOAD (KLUN, YD%YLIMA (J1))
  ENDDO
ELSE
  NULLIFY (YD%YLIMA)
ENDIF
READ (KLUN) LYFSD
IF (LYFSD) THEN
  ALLOCATE (YD%YFSD)
  CALL LOAD (KLUN, YD%YFSD)
ELSE
  NULLIFY (YD%YFSD)
ENDIF
READ (KLUN) LYEXT
IF (LYEXT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YEXT (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YEXT, 1), UBOUND (YD%YEXT, 1)
    CALL LOAD (KLUN, YD%YEXT (J1))
  ENDDO
ELSE
  NULLIFY (YD%YEXT)
ENDIF
CALL LOAD (KLUN, YD%YQ_NL)
CALL LOAD (KLUN, YD%YI_NL)
CALL LOAD (KLUN, YD%YL_NL)
CALL LOAD (KLUN, YD%YLCONV_NL)
CALL LOAD (KLUN, YD%YICONV_NL)
CALL LOAD (KLUN, YD%YRCONV_NL)
CALL LOAD (KLUN, YD%YSCONV_NL)
CALL LOAD (KLUN, YD%YIRAD_NL)
CALL LOAD (KLUN, YD%YLRAD_NL)
CALL LOAD (KLUN, YD%YS_NL)
CALL LOAD (KLUN, YD%YR_NL)
CALL LOAD (KLUN, YD%YG_NL)
CALL LOAD (KLUN, YD%YH_NL)
CALL LOAD (KLUN, YD%YTKE_NL)
CALL LOAD (KLUN, YD%YTTE_NL)
CALL LOAD (KLUN, YD%YEFB1_NL)
CALL LOAD (KLUN, YD%YEFB2_NL)
CALL LOAD (KLUN, YD%YEFB3_NL)
CALL LOAD (KLUN, YD%YA_NL)
CALL LOAD (KLUN, YD%YO3_NL)
CALL LOAD (KLUN, YD%YSRC_NL)
CALL LOAD (KLUN, YD%YMXL_NL)
CALL LOAD (KLUN, YD%YSHTUR_NL)
CALL LOAD (KLUN, YD%YFQTUR_NL)
CALL LOAD (KLUN, YD%YFSTUR_NL)
CALL LOAD (KLUN, YD%YCPF_NL)
CALL LOAD (KLUN, YD%YSPF_NL)
CALL LOAD (KLUN, YD%YCVGQ_NL)
CALL LOAD (KLUN, YD%YQVA_NL)
DO J1 = LBOUND (YD%YGHG_NL, 1), UBOUND (YD%YGHG_NL, 1)
  CALL LOAD (KLUN, YD%YGHG_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YCHEM_NL, 1), UBOUND (YD%YCHEM_NL, 1)
  CALL LOAD (KLUN, YD%YCHEM_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YAERO_NL, 1), UBOUND (YD%YAERO_NL, 1)
  CALL LOAD (KLUN, YD%YAERO_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YERA40_NL, 1), UBOUND (YD%YERA40_NL, 1)
  CALL LOAD (KLUN, YD%YERA40_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YNOGW_NL, 1), UBOUND (YD%YNOGW_NL, 1)
  CALL LOAD (KLUN, YD%YNOGW_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YEDRP_NL, 1), UBOUND (YD%YEDRP_NL, 1)
  CALL LOAD (KLUN, YD%YEDRP_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YSLDIA_NL, 1), UBOUND (YD%YSLDIA_NL, 1)
  CALL LOAD (KLUN, YD%YSLDIA_NL (J1))
ENDDO
CALL LOAD (KLUN, YD%YLRCH4_NL)
DO J1 = LBOUND (YD%YAERAOT_NL, 1), UBOUND (YD%YAERAOT_NL, 1)
  CALL LOAD (KLUN, YD%YAERAOT_NL (J1))
ENDDO
DO J2 = LBOUND (YD%YAERLISI_NL, 2), UBOUND (YD%YAERLISI_NL, 2)
  DO J1 = LBOUND (YD%YAERLISI_NL, 1), UBOUND (YD%YAERLISI_NL, 1)
    CALL LOAD (KLUN, YD%YAERLISI_NL (J1, J2))
  ENDDO
ENDDO
DO J1 = LBOUND (YD%YAEROUT_NL, 1), UBOUND (YD%YAEROUT_NL, 1)
  CALL LOAD (KLUN, YD%YAEROUT_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YAEROCLIM_NL, 1), UBOUND (YD%YAEROCLIM_NL, 1)
  CALL LOAD (KLUN, YD%YAEROCLIM_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YUVP_NL, 1), UBOUND (YD%YUVP_NL, 1)
  CALL LOAD (KLUN, YD%YUVP_NL (J1))
ENDDO
CALL LOAD (KLUN, YD%YRKTH_NL)
CALL LOAD (KLUN, YD%YRKTQV_NL)
CALL LOAD (KLUN, YD%YRKTQC_NL)
DO J1 = LBOUND (YD%YCRM_NL, 1), UBOUND (YD%YCRM_NL, 1)
! CALL LOAD (KLUN, YD%YCRM_NL (J1))
ENDDO
CALL LOAD (KLUN, YD%YPHYCTY_NL)
CALL LOAD (KLUN, YD%YFSD_NL)
CALL LOAD (KLUN, YD%YRSPEC_NL)
CALL LOAD (KLUN, YD%YSDSAT_NL)
CALL LOAD (KLUN, YD%YCVV_NL)
DO J1 = LBOUND (YD%YFORC_NL, 1), UBOUND (YD%YFORC_NL, 1)
  CALL LOAD (KLUN, YD%YFORC_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YEZDIAG_NL, 1), UBOUND (YD%YEZDIAG_NL, 1)
  CALL LOAD (KLUN, YD%YEZDIAG_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YEXT_NL, 1), UBOUND (YD%YEXT_NL, 1)
  CALL LOAD (KLUN, YD%YEXT_NL (J1))
ENDDO
CALL LOAD (KLUN, YD%YUOM_NL)
CALL LOAD (KLUN, YD%YUAL_NL)
CALL LOAD (KLUN, YD%YDOM_NL)
CALL LOAD (KLUN, YD%YDAL_NL)
CALL LOAD (KLUN, YD%YUEN_NL)
CALL LOAD (KLUN, YD%YUNEBH_NL)
DO J1 = LBOUND (YD%YAERO_WVL_DIAG_NL, 1), UBOUND (YD%YAERO_WVL_DIAG_NL, 1)
  CALL LOAD (KLUN, YD%YAERO_WVL_DIAG_NL (J1))
ENDDO
DO J1 = LBOUND (YD%YLIMA_NL, 1), UBOUND (YD%YLIMA_NL, 1)
  CALL LOAD (KLUN, YD%YLIMA_NL (J1))
ENDDO
END SUBROUTINE






END MODULE
