MODULE UTIL_MODEL_GENERAL_CONF_TYPE_MOD

USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_GENERAL_CONF_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE UTIL_GEOMETRY_MOD
USE UTIL_TACVDIM_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TRIP_MOD
USE UTIL_TYPE_GFLD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LGEOM
LGEOM = ASSOCIATED (YD%GEOM)
WRITE (KLUN) LGEOM
IF (LGEOM) THEN
  CALL SAVE (KLUN, YD%GEOM)
ENDIF
CALL SAVE (KLUN, YD%YRDIMF)
CALL SAVE (KLUN, YD%YGFL)
CALL SAVE (KLUN, YD%YRRIP)
CALL SAVE (KLUN, YD%YRDIMACV)
WRITE (KLUN) YD%LMODEL_WITH_SPECRT
END SUBROUTINE

SUBROUTINE LOAD_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE UTIL_GEOMETRY_MOD
USE UTIL_TACVDIM_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TRIP_MOD
USE UTIL_TYPE_GFLD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LGEOM
READ (KLUN) LGEOM
IF (LGEOM) THEN
  ALLOCATE (YD%GEOM)
  CALL LOAD (KLUN, YD%GEOM)
ELSE
  NULLIFY (YD%GEOM)
ENDIF
CALL LOAD (KLUN, YD%YRDIMF)
CALL LOAD (KLUN, YD%YGFL)
CALL LOAD (KLUN, YD%YRRIP)
CALL LOAD (KLUN, YD%YRDIMACV)
READ (KLUN) YD%LMODEL_WITH_SPECRT
END SUBROUTINE


SUBROUTINE COPY_MODEL_GENERAL_CONF_TYPE (YD, LDCREATED)
USE UTIL_GEOMETRY_MOD
USE UTIL_TACVDIM_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TRIP_MOD
USE UTIL_TYPE_GFLD_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LGEOM

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LGEOM = ASSOCIATED (YD%GEOM)
IF (LGEOM) THEN
  !$acc enter data create (YD%GEOM)
  !$acc update device (YD%GEOM)
  CALL COPY (YD%GEOM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%GEOM)
ENDIF

CALL COPY (YD%YRDIMF, LDCREATED=.TRUE.)

CALL COPY (YD%YGFL, LDCREATED=.TRUE.)

CALL COPY (YD%YRRIP, LDCREATED=.TRUE.)

CALL COPY (YD%YRDIMACV, LDCREATED=.TRUE.)


END SUBROUTINE



END MODULE
