MODULE UTIL_MODEL_CHEM_TYPE_MOD

USE MODEL_CHEM_MOD, ONLY : MODEL_CHEM_TYPE
USE UTIL_TCHEM_MOD
USE UTIL_TCOMPO_MOD
USE UTIL_TOZO_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_CHEM_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_CHEM_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_CHEM_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_CHEM_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_CHEM_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_CHEM_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YROZO)
CALL SAVE (KLUN, YD%YRCHEM)
CALL SAVE (KLUN, YD%YRCOMPO)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_CHEM_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_CHEM_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YROZO)
CALL LOAD (KLUN, YD%YRCHEM)
CALL LOAD (KLUN, YD%YRCOMPO)
END SUBROUTINE


SUBROUTINE COPY_MODEL_CHEM_TYPE (YD, LDCREATED)
IMPLICIT NONE
CLASS (MODEL_CHEM_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YROZO, LDCREATED=.TRUE.)

CALL COPY (YD%YRCHEM, LDCREATED=.TRUE.)

CALL COPY (YD%YRCOMPO, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_CHEM_TYPE (YD, LDDELETED)
IMPLICIT NONE
CLASS (MODEL_CHEM_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YROZO, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCHEM, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCOMPO, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
