MODULE UTIL_TLOUIS_MOD

USE YOMLOUIS, ONLY : TLOUIS


INTERFACE SAVE
MODULE PROCEDURE SAVE_TLOUIS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLOUIS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLOUIS
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TLOUIS
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TLOUIS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLOUIS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RLOUIS_S0
WRITE (KLUN) YD%PLOUIS_S0
WRITE (KLUN) YD%RLOUIS_GU1
WRITE (KLUN) YD%RLOUIS_GU2
WRITE (KLUN) YD%PLOUIS_GU1
WRITE (KLUN) YD%PLOUIS_GU2
WRITE (KLUN) YD%RLOUIS_GS1
WRITE (KLUN) YD%RLOUIS_GS2
WRITE (KLUN) YD%RLOUIS_GS3
WRITE (KLUN) YD%RLOUIS_GS4
WRITE (KLUN) YD%PLOUIS_GS1
WRITE (KLUN) YD%PLOUIS_GS2
WRITE (KLUN) YD%PLOUIS_GS3
WRITE (KLUN) YD%PLOUIS_GS4
END SUBROUTINE

SUBROUTINE LOAD_TLOUIS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLOUIS), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RLOUIS_S0
READ (KLUN) YD%PLOUIS_S0
READ (KLUN) YD%RLOUIS_GU1
READ (KLUN) YD%RLOUIS_GU2
READ (KLUN) YD%PLOUIS_GU1
READ (KLUN) YD%PLOUIS_GU2
READ (KLUN) YD%RLOUIS_GS1
READ (KLUN) YD%RLOUIS_GS2
READ (KLUN) YD%RLOUIS_GS3
READ (KLUN) YD%RLOUIS_GS4
READ (KLUN) YD%PLOUIS_GS1
READ (KLUN) YD%PLOUIS_GS2
READ (KLUN) YD%PLOUIS_GS3
READ (KLUN) YD%PLOUIS_GS4
END SUBROUTINE


SUBROUTINE COPY_TLOUIS (YD, LDCREATED)
IMPLICIT NONE
TYPE (TLOUIS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF














END SUBROUTINE

SUBROUTINE WIPE_TLOUIS (YD, LDDELETED)
IMPLICIT NONE
TYPE (TLOUIS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
