MODULE UTIL_TELWRAD_MOD

USE YOELWRAD, ONLY : TELWRAD

INTERFACE SAVE
MODULE PROCEDURE SAVE_TELWRAD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TELWRAD
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TELWRAD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TELWRAD), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NLEVLWC
WRITE (KLUN) YD%NLWFR
WRITE (KLUN) YD%NLOOPLW
WRITE (KLUN) YD%NLOOPLWO
WRITE (KLUN) YD%NPROMALW
WRITE (KLUN) YD%NLASTLW
WRITE (KLUN) YD%LOPTLWPR
WRITE (KLUN) YD%LWLCLHR
END SUBROUTINE

SUBROUTINE LOAD_TELWRAD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TELWRAD), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NLEVLWC
READ (KLUN) YD%NLWFR
READ (KLUN) YD%NLOOPLW
READ (KLUN) YD%NLOOPLWO
READ (KLUN) YD%NPROMALW
READ (KLUN) YD%NLASTLW
READ (KLUN) YD%LOPTLWPR
READ (KLUN) YD%LWLCLHR
END SUBROUTINE






END MODULE
