MODULE UTIL_TACV_CONFIG_MOD

USE TYPE_ACV, ONLY : TACV_CONFIG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TACV_CONFIG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TACV_CONFIG
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TACV_CONFIG (KLUN, YD)
USE UTIL_TACV_CONFIG_BASE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACV_CONFIG), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYRCONFIG
WRITE (KLUN) YD%NACV
LYRCONFIG = ALLOCATED (YD%YRCONFIG)
WRITE (KLUN) LYRCONFIG
IF (LYRCONFIG) THEN
  WRITE (KLUN) LBOUND (YD%YRCONFIG)
  WRITE (KLUN) UBOUND (YD%YRCONFIG)
  DO J1 = LBOUND (YD%YRCONFIG, 1), UBOUND (YD%YRCONFIG, 1)
    CALL SAVE (KLUN, YD%YRCONFIG (J1))
  ENDDO
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TACV_CONFIG (KLUN, YD)
USE UTIL_TACV_CONFIG_BASE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACV_CONFIG), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYRCONFIG
READ (KLUN) YD%NACV
READ (KLUN) LYRCONFIG
IF (LYRCONFIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCONFIG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCONFIG, 1), UBOUND (YD%YRCONFIG, 1)
    CALL LOAD (KLUN, YD%YRCONFIG (J1))
  ENDDO
ENDIF
END SUBROUTINE




END MODULE
