MODULE UTIL_TRSCAW_MOD

USE INTDYNSL_MOD, ONLY : TRSCAW

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRSCAW
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRSCAW
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRSCAW
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRSCAW), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_WCLO
WRITE (KLUN) YD%M_WCLA
WRITE (KLUN) YD%M_WVINTW
WRITE (KLUN) YD%M_WCLOSLD
WRITE (KLUN) YD%M_WCLASLD
WRITE (KLUN) YD%M_WCLOSLT
WRITE (KLUN) YD%M_WCLASLT
WRITE (KLUN) YD%M_WVINTWSLD
WRITE (KLUN) YD%M_WVINTWSLT
WRITE (KLUN) YD%M_WCLOMAD
WRITE (KLUN) YD%M_WCLAMAD
WRITE (KLUN) YD%M_WVINTWMAD
WRITE (KLUN) YD%M_WVINTWS
WRITE (KLUN) YD%M_WVDERW
WRITE (KLUN) YD%M_WHVW
WRITE (KLUN) YD%M_CW
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TRSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRSCAW), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_WCLO
READ (KLUN) YD%M_WCLA
READ (KLUN) YD%M_WVINTW
READ (KLUN) YD%M_WCLOSLD
READ (KLUN) YD%M_WCLASLD
READ (KLUN) YD%M_WCLOSLT
READ (KLUN) YD%M_WCLASLT
READ (KLUN) YD%M_WVINTWSLD
READ (KLUN) YD%M_WVINTWSLT
READ (KLUN) YD%M_WCLOMAD
READ (KLUN) YD%M_WCLAMAD
READ (KLUN) YD%M_WVINTWMAD
READ (KLUN) YD%M_WVINTWS
READ (KLUN) YD%M_WVDERW
READ (KLUN) YD%M_WHVW
READ (KLUN) YD%M_CW
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TRSCAW (YD, LDCREATED)

IMPLICIT NONE
TYPE (TRSCAW), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

















END SUBROUTINE



END MODULE
