MODULE UTIL_TTNH_MOD

USE YOMTNH, ONLY : TTNH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTNH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTNH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TTNH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TTNH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TTNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTNH), INTENT (IN), TARGET :: YD
LOGICAL :: LTRAJNH
WRITE (KLUN) YD%NLENNH95B
LTRAJNH = ALLOCATED (YD%TRAJNH)
WRITE (KLUN) LTRAJNH
IF (LTRAJNH) THEN
  WRITE (KLUN) LBOUND (YD%TRAJNH)
  WRITE (KLUN) UBOUND (YD%TRAJNH)
  WRITE (KLUN) YD%TRAJNH
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TTNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTNH), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LTRAJNH
READ (KLUN) YD%NLENNH95B
READ (KLUN) LTRAJNH
IF (LTRAJNH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TRAJNH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TRAJNH
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TTNH (YD, LDCREATED)

IMPLICIT NONE
TYPE (TTNH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LTRAJNH

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

LTRAJNH = ALLOCATED (YD%TRAJNH)
IF (LTRAJNH) THEN
  !$acc enter data create (YD%TRAJNH)
  !$acc update device (YD%TRAJNH)
  !$acc enter data attach (YD%TRAJNH)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TTNH (YD, LDDELETED)

IMPLICIT NONE
TYPE (TTNH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LTRAJNH


LTRAJNH = ALLOCATED (YD%TRAJNH)
IF (LTRAJNH) THEN
  !$acc exit data detach (YD%TRAJNH)
  !$acc exit data delete (YD%TRAJNH)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
