MODULE UTIL_MODEL_CHEM_TYPE_MOD

USE MODEL_CHEM_MOD, ONLY : MODEL_CHEM_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_CHEM_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_CHEM_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_CHEM_TYPE (KLUN, YD)
USE UTIL_TCHEM_MOD
USE UTIL_TCOMPO_MOD
USE UTIL_TOZO_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_CHEM_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YROZO)
CALL SAVE (KLUN, YD%YRCHEM)
CALL SAVE (KLUN, YD%YRCOMPO)
END SUBROUTINE
SUBROUTINE LOAD_MODEL_CHEM_TYPE (KLUN, YD)
USE UTIL_TCHEM_MOD
USE UTIL_TCOMPO_MOD
USE UTIL_TOZO_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_CHEM_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YROZO)
CALL LOAD (KLUN, YD%YRCHEM)
CALL LOAD (KLUN, YD%YRCOMPO)
END SUBROUTINE




END MODULE
