MODULE UTIL_TCDDH_MOD

USE YOMCDDH, ONLY : TCDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCDDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCDDH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCDDH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
LCADHTLS = ALLOCATED (YD%CADHTLS)
WRITE (KLUN) LCADHTLS
IF (LCADHTLS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTLS)
  WRITE (KLUN) UBOUND (YD%CADHTLS)
  WRITE (KLUN) YD%CADHTLS
ENDIF
LCADHTSS = ALLOCATED (YD%CADHTSS)
WRITE (KLUN) LCADHTSS
IF (LCADHTSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTSS)
  WRITE (KLUN) UBOUND (YD%CADHTSS)
  WRITE (KLUN) YD%CADHTSS
ENDIF
LCADHTTS = ALLOCATED (YD%CADHTTS)
WRITE (KLUN) LCADHTTS
IF (LCADHTTS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTTS)
  WRITE (KLUN) UBOUND (YD%CADHTTS)
  WRITE (KLUN) YD%CADHTTS
ENDIF
LCADHTIS = ALLOCATED (YD%CADHTIS)
WRITE (KLUN) LCADHTIS
IF (LCADHTIS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTIS)
  WRITE (KLUN) UBOUND (YD%CADHTIS)
  WRITE (KLUN) YD%CADHTIS
ENDIF
LCADHSSS = ALLOCATED (YD%CADHSSS)
WRITE (KLUN) LCADHSSS
IF (LCADHSSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHSSS)
  WRITE (KLUN) UBOUND (YD%CADHSSS)
  WRITE (KLUN) YD%CADHSSS
ENDIF
LCADHIIS = ALLOCATED (YD%CADHIIS)
WRITE (KLUN) LCADHIIS
IF (LCADHIIS) THEN
  WRITE (KLUN) LBOUND (YD%CADHIIS)
  WRITE (KLUN) UBOUND (YD%CADHIIS)
  WRITE (KLUN) YD%CADHIIS
ENDIF
LCADHWLS = ALLOCATED (YD%CADHWLS)
WRITE (KLUN) LCADHWLS
IF (LCADHWLS) THEN
  WRITE (KLUN) LBOUND (YD%CADHWLS)
  WRITE (KLUN) UBOUND (YD%CADHWLS)
  WRITE (KLUN) YD%CADHWLS
ENDIF
LCADHFSS = ALLOCATED (YD%CADHFSS)
WRITE (KLUN) LCADHFSS
IF (LCADHFSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHFSS)
  WRITE (KLUN) UBOUND (YD%CADHFSS)
  WRITE (KLUN) YD%CADHFSS
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TCDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
READ (KLUN) LCADHTLS
IF (LCADHTLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTLS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTLS
ENDIF
READ (KLUN) LCADHTSS
IF (LCADHTSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTSS
ENDIF
READ (KLUN) LCADHTTS
IF (LCADHTTS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTTS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTTS
ENDIF
READ (KLUN) LCADHTIS
IF (LCADHTIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTIS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTIS
ENDIF
READ (KLUN) LCADHSSS
IF (LCADHSSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHSSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHSSS
ENDIF
READ (KLUN) LCADHIIS
IF (LCADHIIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHIIS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHIIS
ENDIF
READ (KLUN) LCADHWLS
IF (LCADHWLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHWLS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHWLS
ENDIF
READ (KLUN) LCADHFSS
IF (LCADHFSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHFSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHFSS
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TCDDH (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LCADHTLS = ALLOCATED (YD%CADHTLS)
IF (LCADHTLS) THEN
  !$acc enter data create (YD%CADHTLS)
  !$acc update device (YD%CADHTLS)
  !$acc enter data attach (YD%CADHTLS)
ENDIF

LCADHTSS = ALLOCATED (YD%CADHTSS)
IF (LCADHTSS) THEN
  !$acc enter data create (YD%CADHTSS)
  !$acc update device (YD%CADHTSS)
  !$acc enter data attach (YD%CADHTSS)
ENDIF

LCADHTTS = ALLOCATED (YD%CADHTTS)
IF (LCADHTTS) THEN
  !$acc enter data create (YD%CADHTTS)
  !$acc update device (YD%CADHTTS)
  !$acc enter data attach (YD%CADHTTS)
ENDIF

LCADHTIS = ALLOCATED (YD%CADHTIS)
IF (LCADHTIS) THEN
  !$acc enter data create (YD%CADHTIS)
  !$acc update device (YD%CADHTIS)
  !$acc enter data attach (YD%CADHTIS)
ENDIF

LCADHSSS = ALLOCATED (YD%CADHSSS)
IF (LCADHSSS) THEN
  !$acc enter data create (YD%CADHSSS)
  !$acc update device (YD%CADHSSS)
  !$acc enter data attach (YD%CADHSSS)
ENDIF

LCADHIIS = ALLOCATED (YD%CADHIIS)
IF (LCADHIIS) THEN
  !$acc enter data create (YD%CADHIIS)
  !$acc update device (YD%CADHIIS)
  !$acc enter data attach (YD%CADHIIS)
ENDIF

LCADHWLS = ALLOCATED (YD%CADHWLS)
IF (LCADHWLS) THEN
  !$acc enter data create (YD%CADHWLS)
  !$acc update device (YD%CADHWLS)
  !$acc enter data attach (YD%CADHWLS)
ENDIF

LCADHFSS = ALLOCATED (YD%CADHFSS)
IF (LCADHFSS) THEN
  !$acc enter data create (YD%CADHFSS)
  !$acc update device (YD%CADHFSS)
  !$acc enter data attach (YD%CADHFSS)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TCDDH (YD, LDDELETED)

IMPLICIT NONE
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS

LCADHTLS = ALLOCATED (YD%CADHTLS)
IF (LCADHTLS) THEN
  !$acc exit data detach (YD%CADHTLS)
  !$acc exit data delete (YD%CADHTLS)
ENDIF

LCADHTSS = ALLOCATED (YD%CADHTSS)
IF (LCADHTSS) THEN
  !$acc exit data detach (YD%CADHTSS)
  !$acc exit data delete (YD%CADHTSS)
ENDIF

LCADHTTS = ALLOCATED (YD%CADHTTS)
IF (LCADHTTS) THEN
  !$acc exit data detach (YD%CADHTTS)
  !$acc exit data delete (YD%CADHTTS)
ENDIF

LCADHTIS = ALLOCATED (YD%CADHTIS)
IF (LCADHTIS) THEN
  !$acc exit data detach (YD%CADHTIS)
  !$acc exit data delete (YD%CADHTIS)
ENDIF

LCADHSSS = ALLOCATED (YD%CADHSSS)
IF (LCADHSSS) THEN
  !$acc exit data detach (YD%CADHSSS)
  !$acc exit data delete (YD%CADHSSS)
ENDIF

LCADHIIS = ALLOCATED (YD%CADHIIS)
IF (LCADHIIS) THEN
  !$acc exit data detach (YD%CADHIIS)
  !$acc exit data delete (YD%CADHIIS)
ENDIF

LCADHWLS = ALLOCATED (YD%CADHWLS)
IF (LCADHWLS) THEN
  !$acc exit data detach (YD%CADHWLS)
  !$acc exit data delete (YD%CADHWLS)
ENDIF

LCADHFSS = ALLOCATED (YD%CADHFSS)
IF (LCADHFSS) THEN
  !$acc exit data detach (YD%CADHFSS)
  !$acc exit data delete (YD%CADHFSS)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
