MODULE UTIL_TGPDDH_MOD

USE YOMGPDDH, ONLY : TGPDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGPDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGPDDH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TGPDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGPDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LGFLTNDHD_DDH, LGFLTNDSL_DDH, LGMVTNDHD_DDH, LGMVTNDSI_DDH, LGMVTNDSL_DDH
LGMVTNDHD_DDH = ALLOCATED (YD%GMVTNDHD_DDH)
WRITE (KLUN) LGMVTNDHD_DDH
IF (LGMVTNDHD_DDH) THEN
  WRITE (KLUN) LBOUND (YD%GMVTNDHD_DDH)
  WRITE (KLUN) UBOUND (YD%GMVTNDHD_DDH)
  WRITE (KLUN) YD%GMVTNDHD_DDH
ENDIF
LGFLTNDHD_DDH = ALLOCATED (YD%GFLTNDHD_DDH)
WRITE (KLUN) LGFLTNDHD_DDH
IF (LGFLTNDHD_DDH) THEN
  WRITE (KLUN) LBOUND (YD%GFLTNDHD_DDH)
  WRITE (KLUN) UBOUND (YD%GFLTNDHD_DDH)
  WRITE (KLUN) YD%GFLTNDHD_DDH
ENDIF
LGMVTNDSI_DDH = ALLOCATED (YD%GMVTNDSI_DDH)
WRITE (KLUN) LGMVTNDSI_DDH
IF (LGMVTNDSI_DDH) THEN
  WRITE (KLUN) LBOUND (YD%GMVTNDSI_DDH)
  WRITE (KLUN) UBOUND (YD%GMVTNDSI_DDH)
  WRITE (KLUN) YD%GMVTNDSI_DDH
ENDIF
LGMVTNDSL_DDH = ALLOCATED (YD%GMVTNDSL_DDH)
WRITE (KLUN) LGMVTNDSL_DDH
IF (LGMVTNDSL_DDH) THEN
  WRITE (KLUN) LBOUND (YD%GMVTNDSL_DDH)
  WRITE (KLUN) UBOUND (YD%GMVTNDSL_DDH)
  WRITE (KLUN) YD%GMVTNDSL_DDH
ENDIF
LGFLTNDSL_DDH = ALLOCATED (YD%GFLTNDSL_DDH)
WRITE (KLUN) LGFLTNDSL_DDH
IF (LGFLTNDSL_DDH) THEN
  WRITE (KLUN) LBOUND (YD%GFLTNDSL_DDH)
  WRITE (KLUN) UBOUND (YD%GFLTNDSL_DDH)
  WRITE (KLUN) YD%GFLTNDSL_DDH
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TGPDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGPDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL4(4), IU4(4)
LOGICAL :: LGFLTNDHD_DDH, LGFLTNDSL_DDH, LGMVTNDHD_DDH, LGMVTNDSI_DDH, LGMVTNDSL_DDH
READ (KLUN) LGMVTNDHD_DDH
IF (LGMVTNDHD_DDH) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GMVTNDHD_DDH (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GMVTNDHD_DDH
ENDIF
READ (KLUN) LGFLTNDHD_DDH
IF (LGFLTNDHD_DDH) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GFLTNDHD_DDH (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GFLTNDHD_DDH
ENDIF
READ (KLUN) LGMVTNDSI_DDH
IF (LGMVTNDSI_DDH) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GMVTNDSI_DDH (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GMVTNDSI_DDH
ENDIF
READ (KLUN) LGMVTNDSL_DDH
IF (LGMVTNDSL_DDH) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GMVTNDSL_DDH (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GMVTNDSL_DDH
ENDIF
READ (KLUN) LGFLTNDSL_DDH
IF (LGFLTNDSL_DDH) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GFLTNDSL_DDH (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GFLTNDSL_DDH
ENDIF
END SUBROUTINE




END MODULE
