MODULE UTIL_TECUMF2_MOD

USE YOECUMF2, ONLY : TECUMF2


INTERFACE SAVE
MODULE PROCEDURE SAVE_TECUMF2
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECUMF2
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TECUMF2
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TECUMF2
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TECUMF2 (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TECUMF2), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%ENTRORG2
WRITE (KLUN) YD%DETRPEN2
WRITE (KLUN) YD%ENTSHALP2
WRITE (KLUN) YD%ENTSTPC12
WRITE (KLUN) YD%ENTSTPC22
WRITE (KLUN) YD%ENTRDD2
WRITE (KLUN) YD%RMFCMIN2
WRITE (KLUN) YD%RMFDEPS2
WRITE (KLUN) YD%RDEPTHS2
WRITE (KLUN) YD%RPRCON2
WRITE (KLUN) YD%RTAU2
WRITE (KLUN) YD%RCPECONS2
WRITE (KLUN) YD%RCUCOV2
WRITE (KLUN) YD%RTAUMEL2
WRITE (KLUN) YD%RUVPER2
WRITE (KLUN) YD%RMFSOLCT2
WRITE (KLUN) YD%RMFSOLTQ2
WRITE (KLUN) YD%RMFSOLUV2
WRITE (KLUN) YD%RMFSOLRHS2
WRITE (KLUN) YD%RMFCFL2
WRITE (KLUN) YD%RMFLIA2
WRITE (KLUN) YD%RCAPDCYCL2
WRITE (KLUN) YD%RTAU02
WRITE (KLUN) YD%LMFMID2
WRITE (KLUN) YD%LMFDD2
WRITE (KLUN) YD%LMFDUDV2
WRITE (KLUN) YD%LMFUVDIS2
WRITE (KLUN) YD%LMFWETB2
WRITE (KLUN) YD%LMFGLAC2
WRITE (KLUN) YD%NJKT12
WRITE (KLUN) YD%NJKT22
WRITE (KLUN) YD%NJKT32
END SUBROUTINE

SUBROUTINE LOAD_TECUMF2 (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TECUMF2), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%ENTRORG2
READ (KLUN) YD%DETRPEN2
READ (KLUN) YD%ENTSHALP2
READ (KLUN) YD%ENTSTPC12
READ (KLUN) YD%ENTSTPC22
READ (KLUN) YD%ENTRDD2
READ (KLUN) YD%RMFCMIN2
READ (KLUN) YD%RMFDEPS2
READ (KLUN) YD%RDEPTHS2
READ (KLUN) YD%RPRCON2
READ (KLUN) YD%RTAU2
READ (KLUN) YD%RCPECONS2
READ (KLUN) YD%RCUCOV2
READ (KLUN) YD%RTAUMEL2
READ (KLUN) YD%RUVPER2
READ (KLUN) YD%RMFSOLCT2
READ (KLUN) YD%RMFSOLTQ2
READ (KLUN) YD%RMFSOLUV2
READ (KLUN) YD%RMFSOLRHS2
READ (KLUN) YD%RMFCFL2
READ (KLUN) YD%RMFLIA2
READ (KLUN) YD%RCAPDCYCL2
READ (KLUN) YD%RTAU02
READ (KLUN) YD%LMFMID2
READ (KLUN) YD%LMFDD2
READ (KLUN) YD%LMFDUDV2
READ (KLUN) YD%LMFUVDIS2
READ (KLUN) YD%LMFWETB2
READ (KLUN) YD%LMFGLAC2
READ (KLUN) YD%NJKT12
READ (KLUN) YD%NJKT22
READ (KLUN) YD%NJKT32
END SUBROUTINE


SUBROUTINE COPY_TECUMF2 (YD, LDCREATED)
IMPLICIT NONE
CLASS (TECUMF2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
































END SUBROUTINE

SUBROUTINE WIPE_TECUMF2 (YD, LDDELETED)
IMPLICIT NONE
CLASS (TECUMF2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

































LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
