MODULE UTIL_TEAERLID_MOD

USE YOEAERLID, ONLY : TEAERLID

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERLID
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERLID
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEAERLID (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERLID), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NAELID
WRITE (KLUN) YD%NWLID
WRITE (KLUN) YD%NAERLISI
WRITE (KLUN) YD%JWLID
WRITE (KLUN) YD%RWLID
WRITE (KLUN) YD%RLICO2
WRITE (KLUN) YD%RLIO2
WRITE (KLUN) YD%RLINO2
WRITE (KLUN) YD%RLIO3
WRITE (KLUN) YD%RLICLS
WRITE (KLUN) YD%RLIDELT
WRITE (KLUN) YD%RLINS
WRITE (KLUN) YD%RLIPREF
WRITE (KLUN) YD%RLITREF
WRITE (KLUN) YD%RLIT0
WRITE (KLUN) YD%RLIDDZ
END SUBROUTINE

SUBROUTINE LOAD_TEAERLID (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERLID), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NAELID
READ (KLUN) YD%NWLID
READ (KLUN) YD%NAERLISI
READ (KLUN) YD%JWLID
READ (KLUN) YD%RWLID
READ (KLUN) YD%RLICO2
READ (KLUN) YD%RLIO2
READ (KLUN) YD%RLINO2
READ (KLUN) YD%RLIO3
READ (KLUN) YD%RLICLS
READ (KLUN) YD%RLIDELT
READ (KLUN) YD%RLINS
READ (KLUN) YD%RLIPREF
READ (KLUN) YD%RLITREF
READ (KLUN) YD%RLIT0
READ (KLUN) YD%RLIDDZ
END SUBROUTINE






END MODULE
