MODULE UTIL_TEOVLP_MOD

USE YOEOVLP, ONLY : TEOVLP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEOVLP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEOVLP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEOVLP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOVLP), INTENT (IN), TARGET :: YD
LOGICAL :: LRA1OVLP
LRA1OVLP = ALLOCATED (YD%RA1OVLP)
WRITE (KLUN) LRA1OVLP
IF (LRA1OVLP) THEN
  WRITE (KLUN) LBOUND (YD%RA1OVLP)
  WRITE (KLUN) UBOUND (YD%RA1OVLP)
  WRITE (KLUN) YD%RA1OVLP
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TEOVLP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOVLP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRA1OVLP
READ (KLUN) LRA1OVLP
IF (LRA1OVLP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RA1OVLP (IL1(1):IU1(1)))
  READ (KLUN) YD%RA1OVLP
ENDIF
END SUBROUTINE




END MODULE
