MODULE UTIL_VARIABLE_BASE_MOD

USE VARIABLE_MODULE, ONLY : VARIABLE_BASE






CONTAINS

SUBROUTINE SAVE_VARIABLE_BASE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (VARIABLE_BASE), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NAME
WRITE (KLUN) YD%CNAME
WRITE (KLUN) YD%IGRBCODE
WRITE (KLUN) YD%LACTIVE
WRITE (KLUN) YD%LT1
WRITE (KLUN) YD%LT9
WRITE (KLUN) YD%LPH9
WRITE (KLUN) YD%LDL
WRITE (KLUN) YD%LDM
WRITE (KLUN) YD%LDL9
WRITE (KLUN) YD%LDM9
WRITE (KLUN) YD%LADV
WRITE (KLUN) YD%LGP
WRITE (KLUN) YD%LWATER
WRITE (KLUN) YD%LTHERMACT
WRITE (KLUN) YD%LCDERS
WRITE (KLUN) YD%RCP
WRITE (KLUN) YD%R
END SUBROUTINE

SUBROUTINE LOAD_VARIABLE_BASE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (VARIABLE_BASE), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NAME
READ (KLUN) YD%CNAME
READ (KLUN) YD%IGRBCODE
READ (KLUN) YD%LACTIVE
READ (KLUN) YD%LT1
READ (KLUN) YD%LT9
READ (KLUN) YD%LPH9
READ (KLUN) YD%LDL
READ (KLUN) YD%LDM
READ (KLUN) YD%LDL9
READ (KLUN) YD%LDM9
READ (KLUN) YD%LADV
READ (KLUN) YD%LGP
READ (KLUN) YD%LWATER
READ (KLUN) YD%LTHERMACT
READ (KLUN) YD%LCDERS
READ (KLUN) YD%RCP
READ (KLUN) YD%R
END SUBROUTINE






END MODULE
