MODULE UTIL_TERIP_MOD

USE YOERIP, ONLY : TERIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TERIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TERIP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TERIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TERIP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RCODECM
WRITE (KLUN) YD%RSIDECM
WRITE (KLUN) YD%RCOVSRM
WRITE (KLUN) YD%RSIVSRM
WRITE (KLUN) YD%RSOVRM
WRITE (KLUN) YD%RWSOVRM
END SUBROUTINE

SUBROUTINE LOAD_TERIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TERIP), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RCODECM
READ (KLUN) YD%RSIDECM
READ (KLUN) YD%RCOVSRM
READ (KLUN) YD%RSIVSRM
READ (KLUN) YD%RSOVRM
READ (KLUN) YD%RWSOVRM
END SUBROUTINE






END MODULE
