MODULE UTIL_TARPHY_MOD

USE YOMARPHY, ONLY : TARPHY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TARPHY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TARPHY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TARPHY
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TARPHY
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TARPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TARPHY), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LMPA
WRITE (KLUN) YD%LMSE
WRITE (KLUN) YD%LMICRO
WRITE (KLUN) YD%LTURB
WRITE (KLUN) YD%LKFBCONV
WRITE (KLUN) YD%LKFBD
WRITE (KLUN) YD%LKFBS
WRITE (KLUN) YD%LMFSHAL
WRITE (KLUN) YD%LUSECHEM
WRITE (KLUN) YD%LORILAM
WRITE (KLUN) YD%LRDUST
WRITE (KLUN) YD%LRCO2
WRITE (KLUN) YD%LINITCHEM
WRITE (KLUN) YD%LINITORILAM
WRITE (KLUN) YD%LINITDUST
WRITE (KLUN) YD%LRDEPOS
WRITE (KLUN) YD%LBUFLUX
WRITE (KLUN) YD%CCOUPLING
WRITE (KLUN) YD%LMDUST
WRITE (KLUN) YD%LSURFEX_KFROM
WRITE (KLUN) YD%LGRADHPHY
WRITE (KLUN) YD%NFLDCORE
WRITE (KLUN) YD%NGRADIENTS
END SUBROUTINE

SUBROUTINE LOAD_TARPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TARPHY), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LMPA
READ (KLUN) YD%LMSE
READ (KLUN) YD%LMICRO
READ (KLUN) YD%LTURB
READ (KLUN) YD%LKFBCONV
READ (KLUN) YD%LKFBD
READ (KLUN) YD%LKFBS
READ (KLUN) YD%LMFSHAL
READ (KLUN) YD%LUSECHEM
READ (KLUN) YD%LORILAM
READ (KLUN) YD%LRDUST
READ (KLUN) YD%LRCO2
READ (KLUN) YD%LINITCHEM
READ (KLUN) YD%LINITORILAM
READ (KLUN) YD%LINITDUST
READ (KLUN) YD%LRDEPOS
READ (KLUN) YD%LBUFLUX
READ (KLUN) YD%CCOUPLING
READ (KLUN) YD%LMDUST
READ (KLUN) YD%LSURFEX_KFROM
READ (KLUN) YD%LGRADHPHY
READ (KLUN) YD%NFLDCORE
READ (KLUN) YD%NGRADIENTS
END SUBROUTINE


SUBROUTINE COPY_TARPHY (YD, LDCREATED)

IMPLICIT NONE
TYPE (TARPHY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF























END SUBROUTINE

SUBROUTINE WIPE_TARPHY (YD, LDDELETED)

IMPLICIT NONE
TYPE (TARPHY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
























LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
