MODULE UTIL_THSLMER_MOD

USE YOMHSLMER, ONLY : THSLMER


INTERFACE SAVE
MODULE PROCEDURE SAVE_THSLMER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_THSLMER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_THSLMER
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_THSLMER
END INTERFACE



CONTAINS

SUBROUTINE SAVE_THSLMER (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (THSLMER), INTENT (IN), TARGET :: YD
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW

LRIPI = ALLOCATED (YD%RIPI)
WRITE (KLUN) LRIPI
IF (LRIPI) THEN
  WRITE (KLUN) LBOUND (YD%RIPI)
  WRITE (KLUN) UBOUND (YD%RIPI)
  WRITE (KLUN) YD%RIPI
ENDIF
LRSLD = ALLOCATED (YD%RSLD)
WRITE (KLUN) LRSLD
IF (LRSLD) THEN
  WRITE (KLUN) LBOUND (YD%RSLD)
  WRITE (KLUN) UBOUND (YD%RSLD)
  WRITE (KLUN) YD%RSLD
ENDIF
LRSLDW = ALLOCATED (YD%RSLDW)
WRITE (KLUN) LRSLDW
IF (LRSLDW) THEN
  WRITE (KLUN) LBOUND (YD%RSLDW)
  WRITE (KLUN) UBOUND (YD%RSLDW)
  WRITE (KLUN) YD%RSLDW
ENDIF
LR3DTW = ALLOCATED (YD%R3DTW)
WRITE (KLUN) LR3DTW
IF (LR3DTW) THEN
  WRITE (KLUN) LBOUND (YD%R3DTW)
  WRITE (KLUN) UBOUND (YD%R3DTW)
  WRITE (KLUN) YD%R3DTW
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_THSLMER (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (THSLMER), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW

READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RIPI
ENDIF
READ (KLUN) LRSLD
IF (LRSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSLD
ENDIF
READ (KLUN) LRSLDW
IF (LRSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RSLDW
ENDIF
READ (KLUN) LR3DTW
IF (LR3DTW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%R3DTW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%R3DTW
ENDIF
END SUBROUTINE


SUBROUTINE COPY_THSLMER (YD, LDCREATED)
IMPLICIT NONE
TYPE (THSLMER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  !$acc enter data create (YD%RIPI)
  !$acc update device (YD%RIPI)
  !$acc enter data attach (YD%RIPI)
ENDIF

LRSLD = ALLOCATED (YD%RSLD)
IF (LRSLD) THEN
  !$acc enter data create (YD%RSLD)
  !$acc update device (YD%RSLD)
  !$acc enter data attach (YD%RSLD)
ENDIF

LRSLDW = ALLOCATED (YD%RSLDW)
IF (LRSLDW) THEN
  !$acc enter data create (YD%RSLDW)
  !$acc update device (YD%RSLDW)
  !$acc enter data attach (YD%RSLDW)
ENDIF

LR3DTW = ALLOCATED (YD%R3DTW)
IF (LR3DTW) THEN
  !$acc enter data create (YD%R3DTW)
  !$acc update device (YD%R3DTW)
  !$acc enter data attach (YD%R3DTW)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_THSLMER (YD, LDDELETED)
IMPLICIT NONE
TYPE (THSLMER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW

LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  !$acc exit data detach (YD%RIPI)
  !$acc exit data delete (YD%RIPI)
ENDIF

LRSLD = ALLOCATED (YD%RSLD)
IF (LRSLD) THEN
  !$acc exit data detach (YD%RSLD)
  !$acc exit data delete (YD%RSLD)
ENDIF

LRSLDW = ALLOCATED (YD%RSLDW)
IF (LRSLDW) THEN
  !$acc exit data detach (YD%RSLDW)
  !$acc exit data delete (YD%RSLDW)
ENDIF

LR3DTW = ALLOCATED (YD%R3DTW)
IF (LR3DTW) THEN
  !$acc exit data detach (YD%R3DTW)
  !$acc exit data delete (YD%R3DTW)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
