MODULE UTIL_TCUMFS_MOD

USE YOMCUMFS, ONLY : TCUMFS


INTERFACE SAVE
MODULE PROCEDURE SAVE_TCUMFS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCUMFS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCUMFS
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCUMFS
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCUMFS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TCUMFS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LECUMFS
WRITE (KLUN) YD%LREGCV
WRITE (KLUN) YD%LMFCFL2_SHSTEP
END SUBROUTINE

SUBROUTINE LOAD_TCUMFS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TCUMFS), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LECUMFS
READ (KLUN) YD%LREGCV
READ (KLUN) YD%LMFCFL2_SHSTEP
END SUBROUTINE


SUBROUTINE COPY_TCUMFS (YD, LDCREATED)
IMPLICIT NONE
CLASS (TCUMFS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF



END SUBROUTINE

SUBROUTINE WIPE_TCUMFS (YD, LDDELETED)
IMPLICIT NONE
CLASS (TCUMFS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED




LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
