MODULE UTIL_TCVMNH_MOD

USE YOMCVMNH, ONLY : TCVMNH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCVMNH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCVMNH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TCVMNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVMNH), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LDEEP
WRITE (KLUN) YD%LSHALLOW
WRITE (KLUN) YD%LDIAGCONV
WRITE (KLUN) YD%LSETTADJ
WRITE (KLUN) YD%LREFRESH_ALL
WRITE (KLUN) YD%LDOWN
WRITE (KLUN) YD%LSMOOTH
WRITE (KLUN) YD%OTADJD
WRITE (KLUN) YD%OTADJS
WRITE (KLUN) YD%NSETENS
WRITE (KLUN) YD%NIICE
WRITE (KLUN) YD%XA25
WRITE (KLUN) YD%XCRAD
WRITE (KLUN) YD%XCDEPTH
WRITE (KLUN) YD%XCDEPTH_D
WRITE (KLUN) YD%XDTPERT
WRITE (KLUN) YD%XENTR
WRITE (KLUN) YD%XZLCL
WRITE (KLUN) YD%XZPBL
WRITE (KLUN) YD%XWTRIG
WRITE (KLUN) YD%XNHGAM
WRITE (KLUN) YD%XTFRZ1
WRITE (KLUN) YD%XTFRZ2
WRITE (KLUN) YD%XSTABT
WRITE (KLUN) YD%XSTABC
WRITE (KLUN) YD%XAW
WRITE (KLUN) YD%XBW
WRITE (KLUN) YD%XATPERT
WRITE (KLUN) YD%XBTPERT
END SUBROUTINE
SUBROUTINE LOAD_TCVMNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVMNH), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LDEEP
READ (KLUN) YD%LSHALLOW
READ (KLUN) YD%LDIAGCONV
READ (KLUN) YD%LSETTADJ
READ (KLUN) YD%LREFRESH_ALL
READ (KLUN) YD%LDOWN
READ (KLUN) YD%LSMOOTH
READ (KLUN) YD%OTADJD
READ (KLUN) YD%OTADJS
READ (KLUN) YD%NSETENS
READ (KLUN) YD%NIICE
READ (KLUN) YD%XA25
READ (KLUN) YD%XCRAD
READ (KLUN) YD%XCDEPTH
READ (KLUN) YD%XCDEPTH_D
READ (KLUN) YD%XDTPERT
READ (KLUN) YD%XENTR
READ (KLUN) YD%XZLCL
READ (KLUN) YD%XZPBL
READ (KLUN) YD%XWTRIG
READ (KLUN) YD%XNHGAM
READ (KLUN) YD%XTFRZ1
READ (KLUN) YD%XTFRZ2
READ (KLUN) YD%XSTABT
READ (KLUN) YD%XSTABC
READ (KLUN) YD%XAW
READ (KLUN) YD%XBW
READ (KLUN) YD%XATPERT
READ (KLUN) YD%XBTPERT
END SUBROUTINE




END MODULE
