MODULE UTIL_TCST_MOD

USE YOMCST, ONLY : TCST

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCST
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCST
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCST
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCST (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCST), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RPI
WRITE (KLUN) YD%RCLUM
WRITE (KLUN) YD%RHPLA
WRITE (KLUN) YD%RKBOL
WRITE (KLUN) YD%RNAVO
WRITE (KLUN) YD%RDAY
WRITE (KLUN) YD%RDAYI
WRITE (KLUN) YD%RHOUR
WRITE (KLUN) YD%REA
WRITE (KLUN) YD%REPSM
WRITE (KLUN) YD%RSIYEA
WRITE (KLUN) YD%RSIDAY
WRITE (KLUN) YD%ROMEGA
WRITE (KLUN) YD%RA
WRITE (KLUN) YD%RG
WRITE (KLUN) YD%R1SA
WRITE (KLUN) YD%DEG2RAD
WRITE (KLUN) YD%RSIGMA
WRITE (KLUN) YD%RI0
WRITE (KLUN) YD%R
WRITE (KLUN) YD%RMD
WRITE (KLUN) YD%RMV
WRITE (KLUN) YD%RMO3
WRITE (KLUN) YD%RD
WRITE (KLUN) YD%RV
WRITE (KLUN) YD%RCPD
WRITE (KLUN) YD%RCPV
WRITE (KLUN) YD%RCVD
WRITE (KLUN) YD%RCVV
WRITE (KLUN) YD%RKAPPA
WRITE (KLUN) YD%RETV
WRITE (KLUN) YD%RMCO2
WRITE (KLUN) YD%RMCH4
WRITE (KLUN) YD%RMN2O
WRITE (KLUN) YD%RMCO
WRITE (KLUN) YD%RMHCHO
WRITE (KLUN) YD%RMNO2
WRITE (KLUN) YD%RMSO2
WRITE (KLUN) YD%RMSO4
WRITE (KLUN) YD%RMCFC11
WRITE (KLUN) YD%RMCFC12
WRITE (KLUN) YD%RMHCFC22
WRITE (KLUN) YD%RMCCL4
WRITE (KLUN) YD%RCW
WRITE (KLUN) YD%RCS
WRITE (KLUN) YD%RATM
WRITE (KLUN) YD%RTT
WRITE (KLUN) YD%RLVTT
WRITE (KLUN) YD%RLSTT
WRITE (KLUN) YD%RLVZER
WRITE (KLUN) YD%RLSZER
WRITE (KLUN) YD%RLMLT
WRITE (KLUN) YD%RDT
WRITE (KLUN) YD%RESTT
WRITE (KLUN) YD%RGAMW
WRITE (KLUN) YD%RBETW
WRITE (KLUN) YD%RALPW
WRITE (KLUN) YD%RGAMS
WRITE (KLUN) YD%RBETS
WRITE (KLUN) YD%RALPS
WRITE (KLUN) YD%RALPD
WRITE (KLUN) YD%RBETD
WRITE (KLUN) YD%RGAMD
END SUBROUTINE

SUBROUTINE LOAD_TCST (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCST), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RPI
READ (KLUN) YD%RCLUM
READ (KLUN) YD%RHPLA
READ (KLUN) YD%RKBOL
READ (KLUN) YD%RNAVO
READ (KLUN) YD%RDAY
READ (KLUN) YD%RDAYI
READ (KLUN) YD%RHOUR
READ (KLUN) YD%REA
READ (KLUN) YD%REPSM
READ (KLUN) YD%RSIYEA
READ (KLUN) YD%RSIDAY
READ (KLUN) YD%ROMEGA
READ (KLUN) YD%RA
READ (KLUN) YD%RG
READ (KLUN) YD%R1SA
READ (KLUN) YD%DEG2RAD
READ (KLUN) YD%RSIGMA
READ (KLUN) YD%RI0
READ (KLUN) YD%R
READ (KLUN) YD%RMD
READ (KLUN) YD%RMV
READ (KLUN) YD%RMO3
READ (KLUN) YD%RD
READ (KLUN) YD%RV
READ (KLUN) YD%RCPD
READ (KLUN) YD%RCPV
READ (KLUN) YD%RCVD
READ (KLUN) YD%RCVV
READ (KLUN) YD%RKAPPA
READ (KLUN) YD%RETV
READ (KLUN) YD%RMCO2
READ (KLUN) YD%RMCH4
READ (KLUN) YD%RMN2O
READ (KLUN) YD%RMCO
READ (KLUN) YD%RMHCHO
READ (KLUN) YD%RMNO2
READ (KLUN) YD%RMSO2
READ (KLUN) YD%RMSO4
READ (KLUN) YD%RMCFC11
READ (KLUN) YD%RMCFC12
READ (KLUN) YD%RMHCFC22
READ (KLUN) YD%RMCCL4
READ (KLUN) YD%RCW
READ (KLUN) YD%RCS
READ (KLUN) YD%RATM
READ (KLUN) YD%RTT
READ (KLUN) YD%RLVTT
READ (KLUN) YD%RLSTT
READ (KLUN) YD%RLVZER
READ (KLUN) YD%RLSZER
READ (KLUN) YD%RLMLT
READ (KLUN) YD%RDT
READ (KLUN) YD%RESTT
READ (KLUN) YD%RGAMW
READ (KLUN) YD%RBETW
READ (KLUN) YD%RALPW
READ (KLUN) YD%RGAMS
READ (KLUN) YD%RBETS
READ (KLUN) YD%RALPS
READ (KLUN) YD%RALPD
READ (KLUN) YD%RBETD
READ (KLUN) YD%RGAMD
END SUBROUTINE


SUBROUTINE COPY_TCST (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCST), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF































































END SUBROUTINE



END MODULE
