MODULE UTIL_TVSLETA_MOD

USE YOMVSLETA, ONLY : TVSLETA


INTERFACE SAVE
MODULE PROCEDURE SAVE_TVSLETA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVSLETA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVSLETA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVSLETA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVSLETA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH

LVCUICO = ALLOCATED (YD%VCUICO)
WRITE (KLUN) LVCUICO
IF (LVCUICO) THEN
  WRITE (KLUN) LBOUND (YD%VCUICO)
  WRITE (KLUN) UBOUND (YD%VCUICO)
  WRITE (KLUN) YD%VCUICO
ENDIF
LVCUICOH = ALLOCATED (YD%VCUICOH)
WRITE (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  WRITE (KLUN) LBOUND (YD%VCUICOH)
  WRITE (KLUN) UBOUND (YD%VCUICOH)
  WRITE (KLUN) YD%VCUICOH
ENDIF
LVSLD = ALLOCATED (YD%VSLD)
WRITE (KLUN) LVSLD
IF (LVSLD) THEN
  WRITE (KLUN) LBOUND (YD%VSLD)
  WRITE (KLUN) UBOUND (YD%VSLD)
  WRITE (KLUN) YD%VSLD
ENDIF
LVSLDH = ALLOCATED (YD%VSLDH)
WRITE (KLUN) LVSLDH
IF (LVSLDH) THEN
  WRITE (KLUN) LBOUND (YD%VSLDH)
  WRITE (KLUN) UBOUND (YD%VSLDH)
  WRITE (KLUN) YD%VSLDH
ENDIF
LVSLDW = ALLOCATED (YD%VSLDW)
WRITE (KLUN) LVSLDW
IF (LVSLDW) THEN
  WRITE (KLUN) LBOUND (YD%VSLDW)
  WRITE (KLUN) UBOUND (YD%VSLDW)
  WRITE (KLUN) YD%VSLDW
ENDIF
LVSLDWH = ALLOCATED (YD%VSLDWH)
WRITE (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  WRITE (KLUN) LBOUND (YD%VSLDWH)
  WRITE (KLUN) UBOUND (YD%VSLDWH)
  WRITE (KLUN) YD%VSLDWH
ENDIF
LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
WRITE (KLUN) LGAMMA_WENO
IF (LGAMMA_WENO) THEN
  WRITE (KLUN) LBOUND (YD%GAMMA_WENO)
  WRITE (KLUN) UBOUND (YD%GAMMA_WENO)
  WRITE (KLUN) YD%GAMMA_WENO
ENDIF
LVRDETAR = ALLOCATED (YD%VRDETAR)
WRITE (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  WRITE (KLUN) LBOUND (YD%VRDETAR)
  WRITE (KLUN) UBOUND (YD%VRDETAR)
  WRITE (KLUN) YD%VRDETAR
ENDIF
WRITE (KLUN) YD%NRLEVX
WRITE (KLUN) YD%VRLEVX
LNVAUTF = ALLOCATED (YD%NVAUTF)
WRITE (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  WRITE (KLUN) LBOUND (YD%NVAUTF)
  WRITE (KLUN) UBOUND (YD%NVAUTF)
  WRITE (KLUN) YD%NVAUTF
ENDIF
LNVAUTH = ALLOCATED (YD%NVAUTH)
WRITE (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  WRITE (KLUN) LBOUND (YD%NVAUTH)
  WRITE (KLUN) UBOUND (YD%NVAUTH)
  WRITE (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVSLETA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH

READ (KLUN) LVCUICO
IF (LVCUICO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VCUICO
ENDIF
READ (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICOH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VCUICOH
ENDIF
READ (KLUN) LVSLD
IF (LVSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VSLD
ENDIF
READ (KLUN) LVSLDH
IF (LVSLDH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLDH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VSLDH
ENDIF
READ (KLUN) LVSLDW
IF (LVSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%VSLDW
ENDIF
READ (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDWH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%VSLDWH
ENDIF
READ (KLUN) LGAMMA_WENO
IF (LGAMMA_WENO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GAMMA_WENO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GAMMA_WENO
ENDIF
READ (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRDETAR (IL1(1):IU1(1)))
  READ (KLUN) YD%VRDETAR
ENDIF
READ (KLUN) YD%NRLEVX
READ (KLUN) YD%VRLEVX
READ (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTF (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTF
ENDIF
READ (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTH (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVSLETA (YD, LDCREATED)
IMPLICIT NONE
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LVCUICO = ALLOCATED (YD%VCUICO)
IF (LVCUICO) THEN
  !$acc enter data create (YD%VCUICO)
  !$acc update device (YD%VCUICO)
  !$acc enter data attach (YD%VCUICO)
ENDIF

LVCUICOH = ALLOCATED (YD%VCUICOH)
IF (LVCUICOH) THEN
  !$acc enter data create (YD%VCUICOH)
  !$acc update device (YD%VCUICOH)
  !$acc enter data attach (YD%VCUICOH)
ENDIF

LVSLD = ALLOCATED (YD%VSLD)
IF (LVSLD) THEN
  !$acc enter data create (YD%VSLD)
  !$acc update device (YD%VSLD)
  !$acc enter data attach (YD%VSLD)
ENDIF

LVSLDH = ALLOCATED (YD%VSLDH)
IF (LVSLDH) THEN
  !$acc enter data create (YD%VSLDH)
  !$acc update device (YD%VSLDH)
  !$acc enter data attach (YD%VSLDH)
ENDIF

LVSLDW = ALLOCATED (YD%VSLDW)
IF (LVSLDW) THEN
  !$acc enter data create (YD%VSLDW)
  !$acc update device (YD%VSLDW)
  !$acc enter data attach (YD%VSLDW)
ENDIF

LVSLDWH = ALLOCATED (YD%VSLDWH)
IF (LVSLDWH) THEN
  !$acc enter data create (YD%VSLDWH)
  !$acc update device (YD%VSLDWH)
  !$acc enter data attach (YD%VSLDWH)
ENDIF

LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
IF (LGAMMA_WENO) THEN
  !$acc enter data create (YD%GAMMA_WENO)
  !$acc update device (YD%GAMMA_WENO)
  !$acc enter data attach (YD%GAMMA_WENO)
ENDIF

LVRDETAR = ALLOCATED (YD%VRDETAR)
IF (LVRDETAR) THEN
  !$acc enter data create (YD%VRDETAR)
  !$acc update device (YD%VRDETAR)
  !$acc enter data attach (YD%VRDETAR)
ENDIF



LNVAUTF = ALLOCATED (YD%NVAUTF)
IF (LNVAUTF) THEN
  !$acc enter data create (YD%NVAUTF)
  !$acc update device (YD%NVAUTF)
  !$acc enter data attach (YD%NVAUTF)
ENDIF

LNVAUTH = ALLOCATED (YD%NVAUTH)
IF (LNVAUTH) THEN
  !$acc enter data create (YD%NVAUTH)
  !$acc update device (YD%NVAUTH)
  !$acc enter data attach (YD%NVAUTH)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TVSLETA (YD, LDDELETED)
IMPLICIT NONE
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH

LVCUICO = ALLOCATED (YD%VCUICO)
IF (LVCUICO) THEN
  !$acc exit data detach (YD%VCUICO)
  !$acc exit data delete (YD%VCUICO)
ENDIF

LVCUICOH = ALLOCATED (YD%VCUICOH)
IF (LVCUICOH) THEN
  !$acc exit data detach (YD%VCUICOH)
  !$acc exit data delete (YD%VCUICOH)
ENDIF

LVSLD = ALLOCATED (YD%VSLD)
IF (LVSLD) THEN
  !$acc exit data detach (YD%VSLD)
  !$acc exit data delete (YD%VSLD)
ENDIF

LVSLDH = ALLOCATED (YD%VSLDH)
IF (LVSLDH) THEN
  !$acc exit data detach (YD%VSLDH)
  !$acc exit data delete (YD%VSLDH)
ENDIF

LVSLDW = ALLOCATED (YD%VSLDW)
IF (LVSLDW) THEN
  !$acc exit data detach (YD%VSLDW)
  !$acc exit data delete (YD%VSLDW)
ENDIF

LVSLDWH = ALLOCATED (YD%VSLDWH)
IF (LVSLDWH) THEN
  !$acc exit data detach (YD%VSLDWH)
  !$acc exit data delete (YD%VSLDWH)
ENDIF

LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
IF (LGAMMA_WENO) THEN
  !$acc exit data detach (YD%GAMMA_WENO)
  !$acc exit data delete (YD%GAMMA_WENO)
ENDIF

LVRDETAR = ALLOCATED (YD%VRDETAR)
IF (LVRDETAR) THEN
  !$acc exit data detach (YD%VRDETAR)
  !$acc exit data delete (YD%VRDETAR)
ENDIF



LNVAUTF = ALLOCATED (YD%NVAUTF)
IF (LNVAUTF) THEN
  !$acc exit data detach (YD%NVAUTF)
  !$acc exit data delete (YD%NVAUTF)
ENDIF

LNVAUTH = ALLOCATED (YD%NVAUTH)
IF (LNVAUTH) THEN
  !$acc exit data detach (YD%NVAUTH)
  !$acc exit data delete (YD%NVAUTH)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
