MODULE UTIL_TLSCAW_MOD

USE INTDYNSL_MOD, ONLY : TLSCAW

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLSCAW
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLSCAW
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TLSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLSCAW), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_WDLO
WRITE (KLUN) YD%M_WDLAT
WRITE (KLUN) YD%M_WDVER
WRITE (KLUN) YD%M_WDLOMAD
WRITE (KLUN) YD%M_WDLAMAD
WRITE (KLUN) YD%M_WDVERMAD
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TLSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLSCAW), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_WDLO
READ (KLUN) YD%M_WDLAT
READ (KLUN) YD%M_WDVER
READ (KLUN) YD%M_WDLOMAD
READ (KLUN) YD%M_WDLAMAD
READ (KLUN) YD%M_WDVERMAD
READ (KLUN) YD%NDIM
END SUBROUTINE






END MODULE
