MODULE UTIL_MODEL_PHYSICS_MF_TYPE_MOD

USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE
USE UTIL_SL_STRUCT_MOD
USE UTIL_TARPHY_MOD
USE UTIL_TCVMNH_MOD
USE UTIL_TLOUIS_MOD
USE UTIL_TMSE_MOD
USE UTIL_TNORGWD_MOD
USE UTIL_TPARAR_MOD
USE UTIL_TPHY0_MOD
USE UTIL_TPHY1_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY3_MOD
USE UTIL_TPHYDS_MOD
USE UTIL_TPHY_MOD
USE UTIL_TSIMPHL_MOD
USE UTIL_TTOPH_MOD
USE UTIL_TVDOZ_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_MF_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_MF_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRPHY)
CALL SAVE (KLUN, YD%YRPHY0)
CALL SAVE (KLUN, YD%YRPHY1)
CALL SAVE (KLUN, YD%YRPHY2)
CALL SAVE (KLUN, YD%YRPHY3)
CALL SAVE (KLUN, YD%YRPHYDS)
CALL SAVE (KLUN, YD%YRCVMNH)
CALL SAVE (KLUN, YD%YRTOPH)
CALL SAVE (KLUN, YD%YRVDOZ)
CALL SAVE (KLUN, YD%YRSIMPHL)
CALL SAVE (KLUN, YD%YRARPHY)
CALL SAVE (KLUN, YD%YRPARAR)
CALL SAVE (KLUN, YD%YRMSE)
CALL SAVE (KLUN, YD%YRLOUIS)
CALL SAVE (KLUN, YD%YRNORGWD)
CALL SAVE (KLUN, YD%YRGR)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_MF_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRPHY)
CALL LOAD (KLUN, YD%YRPHY0)
CALL LOAD (KLUN, YD%YRPHY1)
CALL LOAD (KLUN, YD%YRPHY2)
CALL LOAD (KLUN, YD%YRPHY3)
CALL LOAD (KLUN, YD%YRPHYDS)
CALL LOAD (KLUN, YD%YRCVMNH)
CALL LOAD (KLUN, YD%YRTOPH)
CALL LOAD (KLUN, YD%YRVDOZ)
CALL LOAD (KLUN, YD%YRSIMPHL)
CALL LOAD (KLUN, YD%YRARPHY)
CALL LOAD (KLUN, YD%YRPARAR)
CALL LOAD (KLUN, YD%YRMSE)
CALL LOAD (KLUN, YD%YRLOUIS)
CALL LOAD (KLUN, YD%YRNORGWD)
CALL LOAD (KLUN, YD%YRGR)
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_MF_TYPE (YD, LDCREATED)
IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRPHY, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHY0, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHY1, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHY2, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHY3, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHYDS, LDCREATED=.TRUE.)

CALL COPY (YD%YRCVMNH, LDCREATED=.TRUE.)

CALL COPY (YD%YRTOPH, LDCREATED=.TRUE.)

CALL COPY (YD%YRVDOZ, LDCREATED=.TRUE.)

CALL COPY (YD%YRSIMPHL, LDCREATED=.TRUE.)

CALL COPY (YD%YRARPHY, LDCREATED=.TRUE.)

CALL COPY (YD%YRPARAR, LDCREATED=.TRUE.)

CALL COPY (YD%YRMSE, LDCREATED=.TRUE.)

CALL COPY (YD%YRLOUIS, LDCREATED=.TRUE.)

CALL COPY (YD%YRNORGWD, LDCREATED=.TRUE.)

CALL COPY (YD%YRGR, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_MF_TYPE (YD, LDDELETED)
IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRPHY, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHY0, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHY1, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHY2, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHY3, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHYDS, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCVMNH, LDDELETED=.TRUE.)

CALL WIPE (YD%YRTOPH, LDDELETED=.TRUE.)

CALL WIPE (YD%YRVDOZ, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSIMPHL, LDDELETED=.TRUE.)

CALL WIPE (YD%YRARPHY, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPARAR, LDDELETED=.TRUE.)

CALL WIPE (YD%YRMSE, LDDELETED=.TRUE.)

CALL WIPE (YD%YRLOUIS, LDDELETED=.TRUE.)

CALL WIPE (YD%YRNORGWD, LDDELETED=.TRUE.)

CALL WIPE (YD%YRGR, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
