MODULE UTIL_TCOMPO_MOD

USE YOMCOMPO, ONLY : TCOMPO

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCOMPO
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCOMPO
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCOMPO
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCOMPO
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCOMPO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOMPO), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LCHEM_DIA
WRITE (KLUN) YD%LCHEM_DDFLX
WRITE (KLUN) YD%LCOMPO_DDFLX_DIR
WRITE (KLUN) YD%LCHEM_TROPO
WRITE (KLUN) YD%LGHG_ACCO2
WRITE (KLUN) YD%LCO2SFC
WRITE (KLUN) YD%LCH4SFC
WRITE (KLUN) YD%LAEROSFC
WRITE (KLUN) YD%LFIRE
WRITE (KLUN) YD%LINJ
WRITE (KLUN) YD%LINJ_CHEM
WRITE (KLUN) YD%LINJ_GHG
WRITE (KLUN) YD%LCOMPO_DCVOC
WRITE (KLUN) YD%LCOMPO_DCANT
WRITE (KLUN) YD%LCOMPO_DCBB
WRITE (KLUN) YD%LCOMPO_DCDD
WRITE (KLUN) YD%LVOLC_ALTI
WRITE (KLUN) YD%LANT_HIGH
WRITE (KLUN) YD%LAERNITRATE
WRITE (KLUN) YD%LAERRESUSPENSION
WRITE (KLUN) YD%LAERSOA
WRITE (KLUN) YD%LAERNUCL
WRITE (KLUN) YD%AERO_SCHEME
END SUBROUTINE

SUBROUTINE LOAD_TCOMPO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOMPO), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LCHEM_DIA
READ (KLUN) YD%LCHEM_DDFLX
READ (KLUN) YD%LCOMPO_DDFLX_DIR
READ (KLUN) YD%LCHEM_TROPO
READ (KLUN) YD%LGHG_ACCO2
READ (KLUN) YD%LCO2SFC
READ (KLUN) YD%LCH4SFC
READ (KLUN) YD%LAEROSFC
READ (KLUN) YD%LFIRE
READ (KLUN) YD%LINJ
READ (KLUN) YD%LINJ_CHEM
READ (KLUN) YD%LINJ_GHG
READ (KLUN) YD%LCOMPO_DCVOC
READ (KLUN) YD%LCOMPO_DCANT
READ (KLUN) YD%LCOMPO_DCBB
READ (KLUN) YD%LCOMPO_DCDD
READ (KLUN) YD%LVOLC_ALTI
READ (KLUN) YD%LANT_HIGH
READ (KLUN) YD%LAERNITRATE
READ (KLUN) YD%LAERRESUSPENSION
READ (KLUN) YD%LAERSOA
READ (KLUN) YD%LAERNUCL
READ (KLUN) YD%AERO_SCHEME
END SUBROUTINE


SUBROUTINE COPY_TCOMPO (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCOMPO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF























END SUBROUTINE

SUBROUTINE WIPE_TCOMPO (YD, LDDELETED)

IMPLICIT NONE
TYPE (TCOMPO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
























LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
