MODULE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VPRECIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_VPRECIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_VPRECIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_VPRECIP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_VPRECIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_VPRECIP (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP), INTENT (IN), TARGET :: YD
LOGICAL :: LF_PRECIP
LF_PRECIP = ASSOCIATED (YD%F_PRECIP)
WRITE (KLUN) LF_PRECIP
IF (LF_PRECIP) THEN
  CALL SAVE (KLUN, YD%F_PRECIP)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_VPRECIP (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_PRECIP
NULLIFY (YD%PPRECIP)
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_PRECIP
IF (LF_PRECIP) THEN
  CALL LOAD (KLUN, YD%F_PRECIP)
ELSE
  NULLIFY (YD%F_PRECIP)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE


SUBROUTINE COPY_SURFACE_VIEW_GROUP_VPRECIP (YD, LDCREATED)
USE UTIL_FIELD_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VPRECIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_PRECIP

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LF_PRECIP = ASSOCIATED (YD%F_PRECIP)
IF (LF_PRECIP) THEN
  !$acc enter data create (YD%F_PRECIP)
  !$acc update device (YD%F_PRECIP)
  CALL COPY (YD%F_PRECIP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PRECIP)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_SURFACE_VIEW_GROUP_VPRECIP (YD, LDDELETED)
USE UTIL_FIELD_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VPRECIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LF_PRECIP

LF_PRECIP = ASSOCIATED (YD%F_PRECIP)
IF (LF_PRECIP) THEN
  !$acc exit data detach (YD%F_PRECIP)
  CALL WIPE (YD%F_PRECIP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PRECIP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
MODULE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VPRECIP2

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_VPRECIP2
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_VPRECIP2
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_VPRECIP2
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_VPRECIP2
END INTERFACE



CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_VPRECIP2 (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP2), INTENT (IN), TARGET :: YD
LOGICAL :: LF_PRECIP2
LF_PRECIP2 = ASSOCIATED (YD%F_PRECIP2)
WRITE (KLUN) LF_PRECIP2
IF (LF_PRECIP2) THEN
  CALL SAVE (KLUN, YD%F_PRECIP2)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_VPRECIP2 (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP2), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_PRECIP2
NULLIFY (YD%PPRECIP2)
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_PRECIP2
IF (LF_PRECIP2) THEN
  CALL LOAD (KLUN, YD%F_PRECIP2)
ELSE
  NULLIFY (YD%F_PRECIP2)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE


SUBROUTINE COPY_SURFACE_VIEW_GROUP_VPRECIP2 (YD, LDCREATED)
USE UTIL_FIELD_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VPRECIP2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_PRECIP2

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LF_PRECIP2 = ASSOCIATED (YD%F_PRECIP2)
IF (LF_PRECIP2) THEN
  !$acc enter data create (YD%F_PRECIP2)
  !$acc update device (YD%F_PRECIP2)
  CALL COPY (YD%F_PRECIP2, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PRECIP2)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_SURFACE_VIEW_GROUP_VPRECIP2 (YD, LDDELETED)
USE UTIL_FIELD_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VPRECIP2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LF_PRECIP2

LF_PRECIP2 = ASSOCIATED (YD%F_PRECIP2)
IF (LF_PRECIP2) THEN
  !$acc exit data detach (YD%F_PRECIP2)
  CALL WIPE (YD%F_PRECIP2, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PRECIP2)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
