MODULE UTIL_TVSLETA_MOD

USE YOMVSLETA, ONLY : TVSLETA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVSLETA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVSLETA
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TVSLETA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LVCUICO = ALLOCATED (YD%VCUICO)
WRITE (KLUN) LVCUICO
IF (LVCUICO) THEN
  WRITE (KLUN) LBOUND (YD%VCUICO)
  WRITE (KLUN) UBOUND (YD%VCUICO)
  WRITE (KLUN) YD%VCUICO
ENDIF
LVCUICOH = ALLOCATED (YD%VCUICOH)
WRITE (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  WRITE (KLUN) LBOUND (YD%VCUICOH)
  WRITE (KLUN) UBOUND (YD%VCUICOH)
  WRITE (KLUN) YD%VCUICOH
ENDIF
LVSLD = ALLOCATED (YD%VSLD)
WRITE (KLUN) LVSLD
IF (LVSLD) THEN
  WRITE (KLUN) LBOUND (YD%VSLD)
  WRITE (KLUN) UBOUND (YD%VSLD)
  WRITE (KLUN) YD%VSLD
ENDIF
LVSLDH = ALLOCATED (YD%VSLDH)
WRITE (KLUN) LVSLDH
IF (LVSLDH) THEN
  WRITE (KLUN) LBOUND (YD%VSLDH)
  WRITE (KLUN) UBOUND (YD%VSLDH)
  WRITE (KLUN) YD%VSLDH
ENDIF
LVSLDW = ALLOCATED (YD%VSLDW)
WRITE (KLUN) LVSLDW
IF (LVSLDW) THEN
  WRITE (KLUN) LBOUND (YD%VSLDW)
  WRITE (KLUN) UBOUND (YD%VSLDW)
  WRITE (KLUN) YD%VSLDW
ENDIF
LVSLDWH = ALLOCATED (YD%VSLDWH)
WRITE (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  WRITE (KLUN) LBOUND (YD%VSLDWH)
  WRITE (KLUN) UBOUND (YD%VSLDWH)
  WRITE (KLUN) YD%VSLDWH
ENDIF
LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
WRITE (KLUN) LGAMMA_WENO
IF (LGAMMA_WENO) THEN
  WRITE (KLUN) LBOUND (YD%GAMMA_WENO)
  WRITE (KLUN) UBOUND (YD%GAMMA_WENO)
  WRITE (KLUN) YD%GAMMA_WENO
ENDIF
LVRDETAR = ALLOCATED (YD%VRDETAR)
WRITE (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  WRITE (KLUN) LBOUND (YD%VRDETAR)
  WRITE (KLUN) UBOUND (YD%VRDETAR)
  WRITE (KLUN) YD%VRDETAR
ENDIF
WRITE (KLUN) YD%NRLEVX
WRITE (KLUN) YD%VRLEVX
LNVAUTF = ALLOCATED (YD%NVAUTF)
WRITE (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  WRITE (KLUN) LBOUND (YD%NVAUTF)
  WRITE (KLUN) UBOUND (YD%NVAUTF)
  WRITE (KLUN) YD%NVAUTF
ENDIF
LNVAUTH = ALLOCATED (YD%NVAUTH)
WRITE (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  WRITE (KLUN) LBOUND (YD%NVAUTH)
  WRITE (KLUN) UBOUND (YD%NVAUTH)
  WRITE (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVSLETA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
READ (KLUN) LVCUICO
IF (LVCUICO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VCUICO
ENDIF
READ (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICOH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VCUICOH
ENDIF
READ (KLUN) LVSLD
IF (LVSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VSLD
ENDIF
READ (KLUN) LVSLDH
IF (LVSLDH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLDH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VSLDH
ENDIF
READ (KLUN) LVSLDW
IF (LVSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%VSLDW
ENDIF
READ (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDWH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%VSLDWH
ENDIF
READ (KLUN) LGAMMA_WENO
IF (LGAMMA_WENO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GAMMA_WENO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GAMMA_WENO
ENDIF
READ (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRDETAR (IL1(1):IU1(1)))
  READ (KLUN) YD%VRDETAR
ENDIF
READ (KLUN) YD%NRLEVX
READ (KLUN) YD%VRLEVX
READ (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTF (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTF
ENDIF
READ (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTH (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE






END MODULE
