MODULE UTIL_TSLREP_MOD

USE YOMSLREP, ONLY : TSLREP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSLREP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSLREP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSLREP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSLREP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSLREP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLREP), INTENT (IN), TARGET :: YD
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN
WRITE (KLUN) YD%NGPTOTAD
LNADMAP = ALLOCATED (YD%NADMAP)
WRITE (KLUN) LNADMAP
IF (LNADMAP) THEN
  WRITE (KLUN) LBOUND (YD%NADMAP)
  WRITE (KLUN) UBOUND (YD%NADMAP)
  WRITE (KLUN) YD%NADMAP
ENDIF
LNADCORE = ALLOCATED (YD%NADCORE)
WRITE (KLUN) LNADCORE
IF (LNADCORE) THEN
  WRITE (KLUN) LBOUND (YD%NADCORE)
  WRITE (KLUN) UBOUND (YD%NADCORE)
  WRITE (KLUN) YD%NADCORE
ENDIF
LLADCORE = ALLOCATED (YD%LADCORE)
WRITE (KLUN) LLADCORE
IF (LLADCORE) THEN
  WRITE (KLUN) LBOUND (YD%LADCORE)
  WRITE (KLUN) UBOUND (YD%LADCORE)
  WRITE (KLUN) YD%LADCORE
ENDIF
LRSASIGN = ALLOCATED (YD%RSASIGN)
WRITE (KLUN) LRSASIGN
IF (LRSASIGN) THEN
  WRITE (KLUN) LBOUND (YD%RSASIGN)
  WRITE (KLUN) UBOUND (YD%RSASIGN)
  WRITE (KLUN) YD%RSASIGN
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TSLREP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLREP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN
READ (KLUN) YD%NGPTOTAD
READ (KLUN) LNADMAP
IF (LNADMAP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NADMAP (IL1(1):IU1(1)))
  READ (KLUN) YD%NADMAP
ENDIF
READ (KLUN) LNADCORE
IF (LNADCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NADCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%NADCORE
ENDIF
READ (KLUN) LLADCORE
IF (LLADCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LADCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%LADCORE
ENDIF
READ (KLUN) LRSASIGN
IF (LRSASIGN) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSASIGN (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSASIGN
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TSLREP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TSLREP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

LNADMAP = ALLOCATED (YD%NADMAP)
IF (LNADMAP) THEN
  !$acc enter data create (YD%NADMAP)
  !$acc update device (YD%NADMAP)
  !$acc enter data attach (YD%NADMAP)
ENDIF

LNADCORE = ALLOCATED (YD%NADCORE)
IF (LNADCORE) THEN
  !$acc enter data create (YD%NADCORE)
  !$acc update device (YD%NADCORE)
  !$acc enter data attach (YD%NADCORE)
ENDIF

LLADCORE = ALLOCATED (YD%LADCORE)
IF (LLADCORE) THEN
  !$acc enter data create (YD%LADCORE)
  !$acc update device (YD%LADCORE)
  !$acc enter data attach (YD%LADCORE)
ENDIF

LRSASIGN = ALLOCATED (YD%RSASIGN)
IF (LRSASIGN) THEN
  !$acc enter data create (YD%RSASIGN)
  !$acc update device (YD%RSASIGN)
  !$acc enter data attach (YD%RSASIGN)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TSLREP (YD, LDDELETED)

IMPLICIT NONE
TYPE (TSLREP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN


LNADMAP = ALLOCATED (YD%NADMAP)
IF (LNADMAP) THEN
  !$acc exit data detach (YD%NADMAP)
  !$acc exit data delete (YD%NADMAP)
ENDIF

LNADCORE = ALLOCATED (YD%NADCORE)
IF (LNADCORE) THEN
  !$acc exit data detach (YD%NADCORE)
  !$acc exit data delete (YD%NADCORE)
ENDIF

LLADCORE = ALLOCATED (YD%LADCORE)
IF (LLADCORE) THEN
  !$acc exit data detach (YD%LADCORE)
  !$acc exit data delete (YD%LADCORE)
ENDIF

LRSASIGN = ALLOCATED (YD%RSASIGN)
IF (LRSASIGN) THEN
  !$acc exit data detach (YD%RSASIGN)
  !$acc exit data delete (YD%RSASIGN)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
