MODULE UTIL_FIELD_VARIABLES_MOD

USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

INTERFACE SAVE
MODULE PROCEDURE SAVE_FIELD_VARIABLES
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_FIELD_VARIABLES
END INTERFACE




CONTAINS

SUBROUTINE SAVE_FIELD_VARIABLES (KLUN, YD)
USE UTIL_GEOMETRY_VARIABLES_MOD
USE UTIL_VARIABLE_3D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (FIELD_VARIABLES), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%Q)
CALL SAVE (KLUN, YD%O3)
CALL SAVE (KLUN, YD%GEOMETRY)
END SUBROUTINE

SUBROUTINE LOAD_FIELD_VARIABLES (KLUN, YD)
USE UTIL_GEOMETRY_VARIABLES_MOD
USE UTIL_VARIABLE_3D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (FIELD_VARIABLES), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%Q)
CALL LOAD (KLUN, YD%O3)
NULLIFY (YD%GHG)
NULLIFY (YD%CHEM)
NULLIFY (YD%AERO)
NULLIFY (YD%FORC)
NULLIFY (YD%EZDIAG)
NULLIFY (YD%ERA40)
NULLIFY (YD%NOGW)
NULLIFY (YD%EDRP)
NULLIFY (YD%SLDIA)
NULLIFY (YD%AERAOT)
NULLIFY (YD%AERLISI)
NULLIFY (YD%AEROUT)
NULLIFY (YD%AEROCLIM)
NULLIFY (YD%UVP)
NULLIFY (YD%PHYS)
NULLIFY (YD%CRM)
NULLIFY (YD%LIMA)
NULLIFY (YD%EXT)
CALL LOAD (KLUN, YD%GEOMETRY)
END SUBROUTINE






END MODULE
