MODULE UTIL_TENEUR_MOD

USE YOENEUR, ONLY : TENEUR


INTERFACE SAVE
MODULE PROCEDURE SAVE_TENEUR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TENEUR
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TENEUR
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TENEUR
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TENEUR (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TENEUR), INTENT (IN), TARGET :: YD
LOGICAL :: LAAM_NN, LBBM_NN, LENTREEMOY, LNBNEUR, LPDFSDX, LRAPIN, LRAPOUT, LSORTIEMOY, LWNELN

WRITE (KLUN) YD%NCOU
WRITE (KLUN) YD%NBR
WRITE (KLUN) YD%NBNEURMAX
WRITE (KLUN) YD%KLEV_NN
LNBNEUR = ALLOCATED (YD%NBNEUR)
WRITE (KLUN) LNBNEUR
IF (LNBNEUR) THEN
  WRITE (KLUN) LBOUND (YD%NBNEUR)
  WRITE (KLUN) UBOUND (YD%NBNEUR)
  WRITE (KLUN) YD%NBNEUR
ENDIF
LWNELN = ALLOCATED (YD%WNELN)
WRITE (KLUN) LWNELN
IF (LWNELN) THEN
  WRITE (KLUN) LBOUND (YD%WNELN)
  WRITE (KLUN) UBOUND (YD%WNELN)
  WRITE (KLUN) YD%WNELN
ENDIF
LENTREEMOY = ALLOCATED (YD%ENTREEMOY)
WRITE (KLUN) LENTREEMOY
IF (LENTREEMOY) THEN
  WRITE (KLUN) LBOUND (YD%ENTREEMOY)
  WRITE (KLUN) UBOUND (YD%ENTREEMOY)
  WRITE (KLUN) YD%ENTREEMOY
ENDIF
LRAPIN = ALLOCATED (YD%RAPIN)
WRITE (KLUN) LRAPIN
IF (LRAPIN) THEN
  WRITE (KLUN) LBOUND (YD%RAPIN)
  WRITE (KLUN) UBOUND (YD%RAPIN)
  WRITE (KLUN) YD%RAPIN
ENDIF
LSORTIEMOY = ALLOCATED (YD%SORTIEMOY)
WRITE (KLUN) LSORTIEMOY
IF (LSORTIEMOY) THEN
  WRITE (KLUN) LBOUND (YD%SORTIEMOY)
  WRITE (KLUN) UBOUND (YD%SORTIEMOY)
  WRITE (KLUN) YD%SORTIEMOY
ENDIF
LRAPOUT = ALLOCATED (YD%RAPOUT)
WRITE (KLUN) LRAPOUT
IF (LRAPOUT) THEN
  WRITE (KLUN) LBOUND (YD%RAPOUT)
  WRITE (KLUN) UBOUND (YD%RAPOUT)
  WRITE (KLUN) YD%RAPOUT
ENDIF
LPDFSDX = ALLOCATED (YD%PDFSDX)
WRITE (KLUN) LPDFSDX
IF (LPDFSDX) THEN
  WRITE (KLUN) LBOUND (YD%PDFSDX)
  WRITE (KLUN) UBOUND (YD%PDFSDX)
  WRITE (KLUN) YD%PDFSDX
ENDIF
LAAM_NN = ALLOCATED (YD%AAM_NN)
WRITE (KLUN) LAAM_NN
IF (LAAM_NN) THEN
  WRITE (KLUN) LBOUND (YD%AAM_NN)
  WRITE (KLUN) UBOUND (YD%AAM_NN)
  WRITE (KLUN) YD%AAM_NN
ENDIF
LBBM_NN = ALLOCATED (YD%BBM_NN)
WRITE (KLUN) LBBM_NN
IF (LBBM_NN) THEN
  WRITE (KLUN) LBOUND (YD%BBM_NN)
  WRITE (KLUN) UBOUND (YD%BBM_NN)
  WRITE (KLUN) YD%BBM_NN
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TENEUR (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TENEUR), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL4(4), IU4(4)
LOGICAL :: LAAM_NN, LBBM_NN, LENTREEMOY, LNBNEUR, LPDFSDX, LRAPIN, LRAPOUT, LSORTIEMOY, LWNELN

READ (KLUN) YD%NCOU
READ (KLUN) YD%NBR
READ (KLUN) YD%NBNEURMAX
READ (KLUN) YD%KLEV_NN
READ (KLUN) LNBNEUR
IF (LNBNEUR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NBNEUR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NBNEUR
ENDIF
READ (KLUN) LWNELN
IF (LWNELN) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%WNELN (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%WNELN
ENDIF
READ (KLUN) LENTREEMOY
IF (LENTREEMOY) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%ENTREEMOY (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%ENTREEMOY
ENDIF
READ (KLUN) LRAPIN
IF (LRAPIN) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RAPIN (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RAPIN
ENDIF
READ (KLUN) LSORTIEMOY
IF (LSORTIEMOY) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SORTIEMOY (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SORTIEMOY
ENDIF
READ (KLUN) LRAPOUT
IF (LRAPOUT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RAPOUT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RAPOUT
ENDIF
READ (KLUN) LPDFSDX
IF (LPDFSDX) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%PDFSDX (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%PDFSDX
ENDIF
READ (KLUN) LAAM_NN
IF (LAAM_NN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%AAM_NN (IL1(1):IU1(1)))
  READ (KLUN) YD%AAM_NN
ENDIF
READ (KLUN) LBBM_NN
IF (LBBM_NN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%BBM_NN (IL1(1):IU1(1)))
  READ (KLUN) YD%BBM_NN
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TENEUR (YD, LDCREATED)
IMPLICIT NONE
CLASS (TENEUR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LAAM_NN, LBBM_NN, LENTREEMOY, LNBNEUR, LPDFSDX, LRAPIN, LRAPOUT, LSORTIEMOY, LWNELN

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




LNBNEUR = ALLOCATED (YD%NBNEUR)
IF (LNBNEUR) THEN
  !$acc enter data create (YD%NBNEUR)
  !$acc update device (YD%NBNEUR)
  !$acc enter data attach (YD%NBNEUR)
ENDIF

LWNELN = ALLOCATED (YD%WNELN)
IF (LWNELN) THEN
  !$acc enter data create (YD%WNELN)
  !$acc update device (YD%WNELN)
  !$acc enter data attach (YD%WNELN)
ENDIF

LENTREEMOY = ALLOCATED (YD%ENTREEMOY)
IF (LENTREEMOY) THEN
  !$acc enter data create (YD%ENTREEMOY)
  !$acc update device (YD%ENTREEMOY)
  !$acc enter data attach (YD%ENTREEMOY)
ENDIF

LRAPIN = ALLOCATED (YD%RAPIN)
IF (LRAPIN) THEN
  !$acc enter data create (YD%RAPIN)
  !$acc update device (YD%RAPIN)
  !$acc enter data attach (YD%RAPIN)
ENDIF

LSORTIEMOY = ALLOCATED (YD%SORTIEMOY)
IF (LSORTIEMOY) THEN
  !$acc enter data create (YD%SORTIEMOY)
  !$acc update device (YD%SORTIEMOY)
  !$acc enter data attach (YD%SORTIEMOY)
ENDIF

LRAPOUT = ALLOCATED (YD%RAPOUT)
IF (LRAPOUT) THEN
  !$acc enter data create (YD%RAPOUT)
  !$acc update device (YD%RAPOUT)
  !$acc enter data attach (YD%RAPOUT)
ENDIF

LPDFSDX = ALLOCATED (YD%PDFSDX)
IF (LPDFSDX) THEN
  !$acc enter data create (YD%PDFSDX)
  !$acc update device (YD%PDFSDX)
  !$acc enter data attach (YD%PDFSDX)
ENDIF

LAAM_NN = ALLOCATED (YD%AAM_NN)
IF (LAAM_NN) THEN
  !$acc enter data create (YD%AAM_NN)
  !$acc update device (YD%AAM_NN)
  !$acc enter data attach (YD%AAM_NN)
ENDIF

LBBM_NN = ALLOCATED (YD%BBM_NN)
IF (LBBM_NN) THEN
  !$acc enter data create (YD%BBM_NN)
  !$acc update device (YD%BBM_NN)
  !$acc enter data attach (YD%BBM_NN)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TENEUR (YD, LDDELETED)
IMPLICIT NONE
CLASS (TENEUR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LAAM_NN, LBBM_NN, LENTREEMOY, LNBNEUR, LPDFSDX, LRAPIN, LRAPOUT, LSORTIEMOY, LWNELN





LNBNEUR = ALLOCATED (YD%NBNEUR)
IF (LNBNEUR) THEN
  !$acc exit data detach (YD%NBNEUR)
  !$acc exit data delete (YD%NBNEUR)
ENDIF

LWNELN = ALLOCATED (YD%WNELN)
IF (LWNELN) THEN
  !$acc exit data detach (YD%WNELN)
  !$acc exit data delete (YD%WNELN)
ENDIF

LENTREEMOY = ALLOCATED (YD%ENTREEMOY)
IF (LENTREEMOY) THEN
  !$acc exit data detach (YD%ENTREEMOY)
  !$acc exit data delete (YD%ENTREEMOY)
ENDIF

LRAPIN = ALLOCATED (YD%RAPIN)
IF (LRAPIN) THEN
  !$acc exit data detach (YD%RAPIN)
  !$acc exit data delete (YD%RAPIN)
ENDIF

LSORTIEMOY = ALLOCATED (YD%SORTIEMOY)
IF (LSORTIEMOY) THEN
  !$acc exit data detach (YD%SORTIEMOY)
  !$acc exit data delete (YD%SORTIEMOY)
ENDIF

LRAPOUT = ALLOCATED (YD%RAPOUT)
IF (LRAPOUT) THEN
  !$acc exit data detach (YD%RAPOUT)
  !$acc exit data delete (YD%RAPOUT)
ENDIF

LPDFSDX = ALLOCATED (YD%PDFSDX)
IF (LPDFSDX) THEN
  !$acc exit data detach (YD%PDFSDX)
  !$acc exit data delete (YD%PDFSDX)
ENDIF

LAAM_NN = ALLOCATED (YD%AAM_NN)
IF (LAAM_NN) THEN
  !$acc exit data detach (YD%AAM_NN)
  !$acc exit data delete (YD%AAM_NN)
ENDIF

LBBM_NN = ALLOCATED (YD%BBM_NN)
IF (LBBM_NN) THEN
  !$acc exit data detach (YD%BBM_NN)
  !$acc exit data delete (YD%BBM_NN)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
