MODULE UTIL_TACVDIM_MOD

USE TYPE_ACV, ONLY : TACVDIM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TACVDIM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TACVDIM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TACVDIM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TACVDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACVDIM), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LACV_1D
WRITE (KLUN) YD%LACV_2D
WRITE (KLUN) YD%LACV_3D
WRITE (KLUN) YD%NACV_1D
WRITE (KLUN) YD%NACVSP_2D
WRITE (KLUN) YD%NACVGP_2D
WRITE (KLUN) YD%NACV_2D
WRITE (KLUN) YD%NACVSP_3D
WRITE (KLUN) YD%NACVGP_3D
WRITE (KLUN) YD%NACV_3D
WRITE (KLUN) YD%NACV_ALL
END SUBROUTINE

SUBROUTINE LOAD_TACVDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACVDIM), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LACV_1D
READ (KLUN) YD%LACV_2D
READ (KLUN) YD%LACV_3D
READ (KLUN) YD%NACV_1D
READ (KLUN) YD%NACVSP_2D
READ (KLUN) YD%NACVGP_2D
READ (KLUN) YD%NACV_2D
READ (KLUN) YD%NACVSP_3D
READ (KLUN) YD%NACVGP_3D
READ (KLUN) YD%NACV_3D
READ (KLUN) YD%NACV_ALL
END SUBROUTINE


SUBROUTINE COPY_TACVDIM (YD, LDCREATED)

IMPLICIT NONE
TYPE (TACVDIM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF











END SUBROUTINE



END MODULE
