MODULE UTIL_MODEL_DYNAMICS_TYPE_MOD

USE MODEL_DYNAMICS_MOD, ONLY : MODEL_DYNAMICS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DYNAMICS_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRDYNA)
CALL SAVE (KLUN, YD%YRDYN)
CALL SAVE (KLUN, YD%YREDYN)
CALL SAVE (KLUN, YD%YRSPNG)
CALL SAVE (KLUN, YD%YRPTRGPPC)
CALL SAVE (KLUN, YD%YYTLSCAW)
CALL SAVE (KLUN, YD%YYTLSCAWH)
CALL SAVE (KLUN, YD%YYTRSCAW)
CALL SAVE (KLUN, YD%YYTRSCAWH)
CALL SAVE (KLUN, YD%YYTSCO)
CALL SAVE (KLUN, YD%YYTCCO)
CALL SAVE (KLUN, YD%YRSLREP)
CALL SAVE (KLUN, YD%YRPTRSLB1)
CALL SAVE (KLUN, YD%YRPTRSLB2)
CALL SAVE (KLUN, YD%YRPTRSLB15)
CALL SAVE (KLUN, YD%YRTNH)
CALL SAVE (KLUN, YD%YRSL)
CALL SAVE (KLUN, YD%YRAD)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRDYNA)
CALL LOAD (KLUN, YD%YRDYN)
CALL LOAD (KLUN, YD%YREDYN)
CALL LOAD (KLUN, YD%YRSPNG)
CALL LOAD (KLUN, YD%YRPTRGPPC)
CALL LOAD (KLUN, YD%YYTLSCAW)
CALL LOAD (KLUN, YD%YYTLSCAWH)
CALL LOAD (KLUN, YD%YYTRSCAW)
CALL LOAD (KLUN, YD%YYTRSCAWH)
CALL LOAD (KLUN, YD%YYTSCO)
CALL LOAD (KLUN, YD%YYTCCO)
CALL LOAD (KLUN, YD%YRSLREP)
CALL LOAD (KLUN, YD%YRPTRSLB1)
CALL LOAD (KLUN, YD%YRPTRSLB2)
CALL LOAD (KLUN, YD%YRPTRSLB15)
CALL LOAD (KLUN, YD%YRTNH)
CALL LOAD (KLUN, YD%YRSL)
CALL LOAD (KLUN, YD%YRAD)
END SUBROUTINE






END MODULE
