MODULE UTIL_TACV_CONFIG_MOD

USE TYPE_ACV, ONLY : TACV_CONFIG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TACV_CONFIG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TACV_CONFIG
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TACV_CONFIG
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TACV_CONFIG
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TACV_CONFIG (KLUN, YD)
USE UTIL_TACV_CONFIG_BASE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACV_CONFIG), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYRCONFIG
WRITE (KLUN) YD%NACV
LYRCONFIG = ALLOCATED (YD%YRCONFIG)
WRITE (KLUN) LYRCONFIG
IF (LYRCONFIG) THEN
  WRITE (KLUN) LBOUND (YD%YRCONFIG)
  WRITE (KLUN) UBOUND (YD%YRCONFIG)
  DO J1 = LBOUND (YD%YRCONFIG, 1), UBOUND (YD%YRCONFIG, 1)
    CALL SAVE (KLUN, YD%YRCONFIG (J1))
  ENDDO
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TACV_CONFIG (KLUN, YD)
USE UTIL_TACV_CONFIG_BASE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACV_CONFIG), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYRCONFIG
READ (KLUN) YD%NACV
READ (KLUN) LYRCONFIG
IF (LYRCONFIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCONFIG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCONFIG, 1), UBOUND (YD%YRCONFIG, 1)
    CALL LOAD (KLUN, YD%YRCONFIG (J1))
  ENDDO
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TACV_CONFIG (YD, LDCREATED)
USE UTIL_TACV_CONFIG_BASE_MOD
IMPLICIT NONE
TYPE (TACV_CONFIG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
INTEGER :: J1
LOGICAL :: LYRCONFIG

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

LYRCONFIG = ALLOCATED (YD%YRCONFIG)
IF (LYRCONFIG) THEN
  !$acc enter data create (YD%YRCONFIG)
  !$acc update device (YD%YRCONFIG)
  DO J1 = LBOUND (YD%YRCONFIG, 1), UBOUND (YD%YRCONFIG, 1)
    CALL COPY (YD%YRCONFIG (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YRCONFIG)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TACV_CONFIG (YD, LDDELETED)
USE UTIL_TACV_CONFIG_BASE_MOD
IMPLICIT NONE
TYPE (TACV_CONFIG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
INTEGER :: J1
LOGICAL :: LYRCONFIG


LYRCONFIG = ALLOCATED (YD%YRCONFIG)
IF (LYRCONFIG) THEN
  !$acc exit data detach (YD%YRCONFIG)
  DO J1 = LBOUND (YD%YRCONFIG, 1), UBOUND (YD%YRCONFIG, 1)
    CALL WIPE (YD%YRCONFIG (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YRCONFIG)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
