MODULE UTIL_TRADF_MOD

USE YOMRADF, ONLY : TRADF

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRADF
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRADF
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TRADF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADF), INTENT (IN), TARGET :: YD
LOGICAL :: LDERIVATIVELW, LEDRO, LEMTC, LEMTD, LEMTU, LRMOON, LSRCDIR, LSRFDIR, LSRLWD, LSRLWDC
LOGICAL :: LSRLWDCS, LSRSWD, LSRSWDC, LSRSWDCS, LSRSWDUV, LSRSWDV, LSRSWPAR, LSRSWPARC, LSRSWTINC, LSRSWUVB
LOGICAL :: LTAUAER, LTRSC, LTRSW
LEMTD = ALLOCATED (YD%EMTD)
WRITE (KLUN) LEMTD
IF (LEMTD) THEN
  WRITE (KLUN) LBOUND (YD%EMTD)
  WRITE (KLUN) UBOUND (YD%EMTD)
  WRITE (KLUN) YD%EMTD
ENDIF
LTRSW = ALLOCATED (YD%TRSW)
WRITE (KLUN) LTRSW
IF (LTRSW) THEN
  WRITE (KLUN) LBOUND (YD%TRSW)
  WRITE (KLUN) UBOUND (YD%TRSW)
  WRITE (KLUN) YD%TRSW
ENDIF
LEMTC = ALLOCATED (YD%EMTC)
WRITE (KLUN) LEMTC
IF (LEMTC) THEN
  WRITE (KLUN) LBOUND (YD%EMTC)
  WRITE (KLUN) UBOUND (YD%EMTC)
  WRITE (KLUN) YD%EMTC
ENDIF
LTRSC = ALLOCATED (YD%TRSC)
WRITE (KLUN) LTRSC
IF (LTRSC) THEN
  WRITE (KLUN) LBOUND (YD%TRSC)
  WRITE (KLUN) UBOUND (YD%TRSC)
  WRITE (KLUN) YD%TRSC
ENDIF
LEMTU = ALLOCATED (YD%EMTU)
WRITE (KLUN) LEMTU
IF (LEMTU) THEN
  WRITE (KLUN) LBOUND (YD%EMTU)
  WRITE (KLUN) UBOUND (YD%EMTU)
  WRITE (KLUN) YD%EMTU
ENDIF
LTAUAER = ALLOCATED (YD%TAUAER)
WRITE (KLUN) LTAUAER
IF (LTAUAER) THEN
  WRITE (KLUN) LBOUND (YD%TAUAER)
  WRITE (KLUN) UBOUND (YD%TAUAER)
  WRITE (KLUN) YD%TAUAER
ENDIF
LSRSWD = ALLOCATED (YD%SRSWD)
WRITE (KLUN) LSRSWD
IF (LSRSWD) THEN
  WRITE (KLUN) LBOUND (YD%SRSWD)
  WRITE (KLUN) UBOUND (YD%SRSWD)
  WRITE (KLUN) YD%SRSWD
ENDIF
LSRLWDC = ALLOCATED (YD%SRLWDC)
WRITE (KLUN) LSRLWDC
IF (LSRLWDC) THEN
  WRITE (KLUN) LBOUND (YD%SRLWDC)
  WRITE (KLUN) UBOUND (YD%SRLWDC)
  WRITE (KLUN) YD%SRLWDC
ENDIF
LSRLWD = ALLOCATED (YD%SRLWD)
WRITE (KLUN) LSRLWD
IF (LSRLWD) THEN
  WRITE (KLUN) LBOUND (YD%SRLWD)
  WRITE (KLUN) UBOUND (YD%SRLWD)
  WRITE (KLUN) YD%SRLWD
ENDIF
LSRSWDC = ALLOCATED (YD%SRSWDC)
WRITE (KLUN) LSRSWDC
IF (LSRSWDC) THEN
  WRITE (KLUN) LBOUND (YD%SRSWDC)
  WRITE (KLUN) UBOUND (YD%SRSWDC)
  WRITE (KLUN) YD%SRSWDC
ENDIF
LSRSWDCS = ALLOCATED (YD%SRSWDCS)
WRITE (KLUN) LSRSWDCS
IF (LSRSWDCS) THEN
  WRITE (KLUN) LBOUND (YD%SRSWDCS)
  WRITE (KLUN) UBOUND (YD%SRSWDCS)
  WRITE (KLUN) YD%SRSWDCS
ENDIF
LSRLWDCS = ALLOCATED (YD%SRLWDCS)
WRITE (KLUN) LSRLWDCS
IF (LSRLWDCS) THEN
  WRITE (KLUN) LBOUND (YD%SRLWDCS)
  WRITE (KLUN) UBOUND (YD%SRLWDCS)
  WRITE (KLUN) YD%SRLWDCS
ENDIF
LSRSWDV = ALLOCATED (YD%SRSWDV)
WRITE (KLUN) LSRSWDV
IF (LSRSWDV) THEN
  WRITE (KLUN) LBOUND (YD%SRSWDV)
  WRITE (KLUN) UBOUND (YD%SRSWDV)
  WRITE (KLUN) YD%SRSWDV
ENDIF
LSRSWDUV = ALLOCATED (YD%SRSWDUV)
WRITE (KLUN) LSRSWDUV
IF (LSRSWDUV) THEN
  WRITE (KLUN) LBOUND (YD%SRSWDUV)
  WRITE (KLUN) UBOUND (YD%SRSWDUV)
  WRITE (KLUN) YD%SRSWDUV
ENDIF
LEDRO = ALLOCATED (YD%EDRO)
WRITE (KLUN) LEDRO
IF (LEDRO) THEN
  WRITE (KLUN) LBOUND (YD%EDRO)
  WRITE (KLUN) UBOUND (YD%EDRO)
  WRITE (KLUN) YD%EDRO
ENDIF
LSRSWPAR = ALLOCATED (YD%SRSWPAR)
WRITE (KLUN) LSRSWPAR
IF (LSRSWPAR) THEN
  WRITE (KLUN) LBOUND (YD%SRSWPAR)
  WRITE (KLUN) UBOUND (YD%SRSWPAR)
  WRITE (KLUN) YD%SRSWPAR
ENDIF
LSRSWUVB = ALLOCATED (YD%SRSWUVB)
WRITE (KLUN) LSRSWUVB
IF (LSRSWUVB) THEN
  WRITE (KLUN) LBOUND (YD%SRSWUVB)
  WRITE (KLUN) UBOUND (YD%SRSWUVB)
  WRITE (KLUN) YD%SRSWUVB
ENDIF
LSRSWPARC = ALLOCATED (YD%SRSWPARC)
WRITE (KLUN) LSRSWPARC
IF (LSRSWPARC) THEN
  WRITE (KLUN) LBOUND (YD%SRSWPARC)
  WRITE (KLUN) UBOUND (YD%SRSWPARC)
  WRITE (KLUN) YD%SRSWPARC
ENDIF
LSRSWTINC = ALLOCATED (YD%SRSWTINC)
WRITE (KLUN) LSRSWTINC
IF (LSRSWTINC) THEN
  WRITE (KLUN) LBOUND (YD%SRSWTINC)
  WRITE (KLUN) UBOUND (YD%SRSWTINC)
  WRITE (KLUN) YD%SRSWTINC
ENDIF
LSRFDIR = ALLOCATED (YD%SRFDIR)
WRITE (KLUN) LSRFDIR
IF (LSRFDIR) THEN
  WRITE (KLUN) LBOUND (YD%SRFDIR)
  WRITE (KLUN) UBOUND (YD%SRFDIR)
  WRITE (KLUN) YD%SRFDIR
ENDIF
LSRCDIR = ALLOCATED (YD%SRCDIR)
WRITE (KLUN) LSRCDIR
IF (LSRCDIR) THEN
  WRITE (KLUN) LBOUND (YD%SRCDIR)
  WRITE (KLUN) UBOUND (YD%SRCDIR)
  WRITE (KLUN) YD%SRCDIR
ENDIF
LRMOON = ALLOCATED (YD%RMOON)
WRITE (KLUN) LRMOON
IF (LRMOON) THEN
  WRITE (KLUN) LBOUND (YD%RMOON)
  WRITE (KLUN) UBOUND (YD%RMOON)
  WRITE (KLUN) YD%RMOON
ENDIF
LDERIVATIVELW = ASSOCIATED (YD%DERIVATIVELW)
WRITE (KLUN) LDERIVATIVELW
IF (LDERIVATIVELW) THEN
  WRITE (KLUN) LBOUND (YD%DERIVATIVELW)
  WRITE (KLUN) UBOUND (YD%DERIVATIVELW)
  WRITE (KLUN) YD%DERIVATIVELW
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TRADF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADF), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LDERIVATIVELW, LEDRO, LEMTC, LEMTD, LEMTU, LRMOON, LSRCDIR, LSRFDIR, LSRLWD, LSRLWDC
LOGICAL :: LSRLWDCS, LSRSWD, LSRSWDC, LSRSWDCS, LSRSWDUV, LSRSWDV, LSRSWPAR, LSRSWPARC, LSRSWTINC, LSRSWUVB
LOGICAL :: LTAUAER, LTRSC, LTRSW
READ (KLUN) LEMTD
IF (LEMTD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EMTD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EMTD
ENDIF
READ (KLUN) LTRSW
IF (LTRSW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%TRSW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%TRSW
ENDIF
READ (KLUN) LEMTC
IF (LEMTC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EMTC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EMTC
ENDIF
READ (KLUN) LTRSC
IF (LTRSC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%TRSC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%TRSC
ENDIF
READ (KLUN) LEMTU
IF (LEMTU) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EMTU (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EMTU
ENDIF
READ (KLUN) LTAUAER
IF (LTAUAER) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%TAUAER (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%TAUAER
ENDIF
READ (KLUN) LSRSWD
IF (LSRSWD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWD
ENDIF
READ (KLUN) LSRLWDC
IF (LSRLWDC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRLWDC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRLWDC
ENDIF
READ (KLUN) LSRLWD
IF (LSRLWD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SRLWD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SRLWD
ENDIF
READ (KLUN) LSRSWDC
IF (LSRSWDC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWDC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWDC
ENDIF
READ (KLUN) LSRSWDCS
IF (LSRSWDCS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWDCS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWDCS
ENDIF
READ (KLUN) LSRLWDCS
IF (LSRLWDCS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRLWDCS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRLWDCS
ENDIF
READ (KLUN) LSRSWDV
IF (LSRSWDV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWDV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWDV
ENDIF
READ (KLUN) LSRSWDUV
IF (LSRSWDUV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWDUV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWDUV
ENDIF
READ (KLUN) LEDRO
IF (LEDRO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EDRO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EDRO
ENDIF
READ (KLUN) LSRSWPAR
IF (LSRSWPAR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWPAR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWPAR
ENDIF
READ (KLUN) LSRSWUVB
IF (LSRSWUVB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWUVB (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWUVB
ENDIF
READ (KLUN) LSRSWPARC
IF (LSRSWPARC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWPARC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWPARC
ENDIF
READ (KLUN) LSRSWTINC
IF (LSRSWTINC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRSWTINC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRSWTINC
ENDIF
READ (KLUN) LSRFDIR
IF (LSRFDIR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRFDIR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRFDIR
ENDIF
READ (KLUN) LSRCDIR
IF (LSRCDIR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SRCDIR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SRCDIR
ENDIF
READ (KLUN) LRMOON
IF (LRMOON) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMOON (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RMOON
ENDIF
READ (KLUN) LDERIVATIVELW
IF (LDERIVATIVELW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%DERIVATIVELW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%DERIVATIVELW
ELSE
  NULLIFY (YD%DERIVATIVELW)
ENDIF
END SUBROUTINE






END MODULE
