MODULE UTIL_TLSCAW_MOD

USE INTDYNSL_MOD, ONLY : TLSCAW

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLSCAW
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLSCAW
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLSCAW
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TLSCAW
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TLSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLSCAW), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_WDLO
WRITE (KLUN) YD%M_WDLAT
WRITE (KLUN) YD%M_WDVER
WRITE (KLUN) YD%M_WDLOMAD
WRITE (KLUN) YD%M_WDLAMAD
WRITE (KLUN) YD%M_WDVERMAD
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TLSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLSCAW), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_WDLO
READ (KLUN) YD%M_WDLAT
READ (KLUN) YD%M_WDVER
READ (KLUN) YD%M_WDLOMAD
READ (KLUN) YD%M_WDLAMAD
READ (KLUN) YD%M_WDVERMAD
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TLSCAW (YD, LDCREATED)

IMPLICIT NONE
TYPE (TLSCAW), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF







END SUBROUTINE

SUBROUTINE WIPE_TLSCAW (YD, LDDELETED)

IMPLICIT NONE
TYPE (TLSCAW), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED








LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
