MODULE UTIL_TXFU_MOD

USE YOMXFU_TYPE, ONLY : TXFU

INTERFACE SAVE
MODULE PROCEDURE SAVE_TXFU
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TXFU
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TXFU (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TXFU_KEYS_MOD, ONLY : TXFU_KEYS, SAVE_TXFU_KEYS
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TXFU), INTENT (IN), TARGET :: YD
CLASS (TXFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_CAPE, LF_CLPH, LF_CLWC, LF_CLWC2, LF_CTOP, LF_DICQ, LF_DICS, LF_DITQ, LF_DITS, LF_FCHSP, LF_FEVL, LF_FEVV, LF_FLWSP, LF_FONTE, LF_FTR, LF_HUN, LF_HUX, LF_MOCON, LF_MRT, LF_NBBAS, LF_NBCON, LF_NBHAU, LF_NBMOY, LF_NEB, LF_NEBT, LF_NUCLS, LF_NVCLS, LF_PLCG, LF_PLCH, LF_PLCL, LF_PLCN, LF_PLSG, LF_PLSH, LF_PLSL, LF_PLSN, LF_PTYPE, LF_PTYPE2, LF_PTYPESEV, LF_PTYPESEV2, LF_QCLS, LF_QICE, LF_QLI, LF_RHCLS, LF_RMNWINDCALC, LF_RMWINDCALC, LF_RSO, LF_RTH, LF_RUISL, LF_RUISP, LF_RUISS, LF_SIC, LF_TCLS, LF_THW, LF_TN, LF_TPWCLS, LF_TRCU, LF_TRCV, LF_TRDU, LF_TRDV, LF_TRTU, LF_TRTV, LF_TX, LF_UCLS, LF_UGST, LF_UGST2, LF_VCLS, LF_VEIN, LF_VGST, LF_VGST2, LF_VISICLD, LF_VISICLD2, LF_VISIHYD, LF_VISIHYD2, LF_XDIAGH
YLSUPER => YD
CALL SAVE_TXFU_KEYS (KLUN, YLSUPER)
LF_RMWINDCALC = ASSOCIATED (YD%F_RMWINDCALC)
WRITE (KLUN) LF_RMWINDCALC
IF (LF_RMWINDCALC) THEN
  CALL SAVE (KLUN, YD%F_RMWINDCALC)
ENDIF
LF_RMNWINDCALC = ASSOCIATED (YD%F_RMNWINDCALC)
WRITE (KLUN) LF_RMNWINDCALC
IF (LF_RMNWINDCALC) THEN
  CALL SAVE (KLUN, YD%F_RMNWINDCALC)
ENDIF
WRITE (KLUN) YD%MEANPERIOD
WRITE (KLUN) YD%NMEANSTEPS
WRITE (KLUN) YD%NXGSTPERIOD
WRITE (KLUN) YD%NXGSTPERIOD2
WRITE (KLUN) YD%NVISIPERIOD
WRITE (KLUN) YD%NVISIPERIOD2
WRITE (KLUN) YD%NXGSTTS
WRITE (KLUN) YD%NTYPXFU
WRITE (KLUN) YD%NXFUTS
WRITE (KLUN) YD%NFRXFU
WRITE (KLUN) YD%NRAZTS
WRITE (KLUN) YD%NFRRAZ
WRITE (KLUN) YD%N1RAZ
WRITE (KLUN) YD%NFDXFU
WRITE (KLUN) YD%LRESET
WRITE (KLUN) YD%LRESET_GST
WRITE (KLUN) YD%LRESET_GST2
WRITE (KLUN) YD%LRESET_PRECIP
WRITE (KLUN) YD%LRESET_PRECIP2
WRITE (KLUN) YD%LRESET_VISI
WRITE (KLUN) YD%LRESET_VISI2
WRITE (KLUN) YD%LREAXFU
LF_CAPE = ASSOCIATED (YD%F_CAPE)
WRITE (KLUN) LF_CAPE
IF (LF_CAPE) THEN
  CALL SAVE (KLUN, YD%F_CAPE)
ENDIF
CALL SAVE (KLUN, YD%YCAPE)
LF_CLPH = ASSOCIATED (YD%F_CLPH)
WRITE (KLUN) LF_CLPH
IF (LF_CLPH) THEN
  CALL SAVE (KLUN, YD%F_CLPH)
ENDIF
CALL SAVE (KLUN, YD%YCLPH)
LF_CLWC2 = ASSOCIATED (YD%F_CLWC2)
WRITE (KLUN) LF_CLWC2
IF (LF_CLWC2) THEN
  CALL SAVE (KLUN, YD%F_CLWC2)
ENDIF
CALL SAVE (KLUN, YD%YCLWC2)
LF_CLWC = ASSOCIATED (YD%F_CLWC)
WRITE (KLUN) LF_CLWC
IF (LF_CLWC) THEN
  CALL SAVE (KLUN, YD%F_CLWC)
ENDIF
CALL SAVE (KLUN, YD%YCLWC)
LF_CTOP = ASSOCIATED (YD%F_CTOP)
WRITE (KLUN) LF_CTOP
IF (LF_CTOP) THEN
  CALL SAVE (KLUN, YD%F_CTOP)
ENDIF
CALL SAVE (KLUN, YD%YCTOP)
LF_DICQ = ASSOCIATED (YD%F_DICQ)
WRITE (KLUN) LF_DICQ
IF (LF_DICQ) THEN
  CALL SAVE (KLUN, YD%F_DICQ)
ENDIF
CALL SAVE (KLUN, YD%YDICQ)
LF_DICS = ASSOCIATED (YD%F_DICS)
WRITE (KLUN) LF_DICS
IF (LF_DICS) THEN
  CALL SAVE (KLUN, YD%F_DICS)
ENDIF
CALL SAVE (KLUN, YD%YDICS)
LF_DITQ = ASSOCIATED (YD%F_DITQ)
WRITE (KLUN) LF_DITQ
IF (LF_DITQ) THEN
  CALL SAVE (KLUN, YD%F_DITQ)
ENDIF
CALL SAVE (KLUN, YD%YDITQ)
LF_DITS = ASSOCIATED (YD%F_DITS)
WRITE (KLUN) LF_DITS
IF (LF_DITS) THEN
  CALL SAVE (KLUN, YD%F_DITS)
ENDIF
CALL SAVE (KLUN, YD%YDITS)
LF_FCHSP = ASSOCIATED (YD%F_FCHSP)
WRITE (KLUN) LF_FCHSP
IF (LF_FCHSP) THEN
  CALL SAVE (KLUN, YD%F_FCHSP)
ENDIF
CALL SAVE (KLUN, YD%YFCHSP)
LF_FEVL = ASSOCIATED (YD%F_FEVL)
WRITE (KLUN) LF_FEVL
IF (LF_FEVL) THEN
  CALL SAVE (KLUN, YD%F_FEVL)
ENDIF
CALL SAVE (KLUN, YD%YFEVL)
LF_FEVV = ASSOCIATED (YD%F_FEVV)
WRITE (KLUN) LF_FEVV
IF (LF_FEVV) THEN
  CALL SAVE (KLUN, YD%F_FEVV)
ENDIF
CALL SAVE (KLUN, YD%YFEVV)
LF_FLWSP = ASSOCIATED (YD%F_FLWSP)
WRITE (KLUN) LF_FLWSP
IF (LF_FLWSP) THEN
  CALL SAVE (KLUN, YD%F_FLWSP)
ENDIF
CALL SAVE (KLUN, YD%YFLWSP)
LF_FONTE = ASSOCIATED (YD%F_FONTE)
WRITE (KLUN) LF_FONTE
IF (LF_FONTE) THEN
  CALL SAVE (KLUN, YD%F_FONTE)
ENDIF
CALL SAVE (KLUN, YD%YFONTE)
LF_FTR = ASSOCIATED (YD%F_FTR)
WRITE (KLUN) LF_FTR
IF (LF_FTR) THEN
  CALL SAVE (KLUN, YD%F_FTR)
ENDIF
CALL SAVE (KLUN, YD%YFTR)
LF_HUN = ASSOCIATED (YD%F_HUN)
WRITE (KLUN) LF_HUN
IF (LF_HUN) THEN
  CALL SAVE (KLUN, YD%F_HUN)
ENDIF
CALL SAVE (KLUN, YD%YHUN)
LF_HUX = ASSOCIATED (YD%F_HUX)
WRITE (KLUN) LF_HUX
IF (LF_HUX) THEN
  CALL SAVE (KLUN, YD%F_HUX)
ENDIF
CALL SAVE (KLUN, YD%YHUX)
LF_MOCON = ASSOCIATED (YD%F_MOCON)
WRITE (KLUN) LF_MOCON
IF (LF_MOCON) THEN
  CALL SAVE (KLUN, YD%F_MOCON)
ENDIF
CALL SAVE (KLUN, YD%YMOCON)
LF_MRT = ASSOCIATED (YD%F_MRT)
WRITE (KLUN) LF_MRT
IF (LF_MRT) THEN
  CALL SAVE (KLUN, YD%F_MRT)
ENDIF
CALL SAVE (KLUN, YD%YMRT)
LF_NBBAS = ASSOCIATED (YD%F_NBBAS)
WRITE (KLUN) LF_NBBAS
IF (LF_NBBAS) THEN
  CALL SAVE (KLUN, YD%F_NBBAS)
ENDIF
CALL SAVE (KLUN, YD%YNBBAS)
LF_NBCON = ASSOCIATED (YD%F_NBCON)
WRITE (KLUN) LF_NBCON
IF (LF_NBCON) THEN
  CALL SAVE (KLUN, YD%F_NBCON)
ENDIF
CALL SAVE (KLUN, YD%YNBCON)
LF_NBHAU = ASSOCIATED (YD%F_NBHAU)
WRITE (KLUN) LF_NBHAU
IF (LF_NBHAU) THEN
  CALL SAVE (KLUN, YD%F_NBHAU)
ENDIF
CALL SAVE (KLUN, YD%YNBHAU)
LF_NBMOY = ASSOCIATED (YD%F_NBMOY)
WRITE (KLUN) LF_NBMOY
IF (LF_NBMOY) THEN
  CALL SAVE (KLUN, YD%F_NBMOY)
ENDIF
CALL SAVE (KLUN, YD%YNBMOY)
LF_NEB = ASSOCIATED (YD%F_NEB)
WRITE (KLUN) LF_NEB
IF (LF_NEB) THEN
  CALL SAVE (KLUN, YD%F_NEB)
ENDIF
CALL SAVE (KLUN, YD%YNEB)
LF_NEBT = ASSOCIATED (YD%F_NEBT)
WRITE (KLUN) LF_NEBT
IF (LF_NEBT) THEN
  CALL SAVE (KLUN, YD%F_NEBT)
ENDIF
CALL SAVE (KLUN, YD%YNEBT)
LF_NUCLS = ASSOCIATED (YD%F_NUCLS)
WRITE (KLUN) LF_NUCLS
IF (LF_NUCLS) THEN
  CALL SAVE (KLUN, YD%F_NUCLS)
ENDIF
CALL SAVE (KLUN, YD%YNUCLS)
LF_NVCLS = ASSOCIATED (YD%F_NVCLS)
WRITE (KLUN) LF_NVCLS
IF (LF_NVCLS) THEN
  CALL SAVE (KLUN, YD%F_NVCLS)
ENDIF
CALL SAVE (KLUN, YD%YNVCLS)
LF_PLCG = ASSOCIATED (YD%F_PLCG)
WRITE (KLUN) LF_PLCG
IF (LF_PLCG) THEN
  CALL SAVE (KLUN, YD%F_PLCG)
ENDIF
CALL SAVE (KLUN, YD%YPLCG)
LF_PLCH = ASSOCIATED (YD%F_PLCH)
WRITE (KLUN) LF_PLCH
IF (LF_PLCH) THEN
  CALL SAVE (KLUN, YD%F_PLCH)
ENDIF
CALL SAVE (KLUN, YD%YPLCH)
LF_PLCL = ASSOCIATED (YD%F_PLCL)
WRITE (KLUN) LF_PLCL
IF (LF_PLCL) THEN
  CALL SAVE (KLUN, YD%F_PLCL)
ENDIF
CALL SAVE (KLUN, YD%YPLCL)
LF_PLCN = ASSOCIATED (YD%F_PLCN)
WRITE (KLUN) LF_PLCN
IF (LF_PLCN) THEN
  CALL SAVE (KLUN, YD%F_PLCN)
ENDIF
CALL SAVE (KLUN, YD%YPLCN)
LF_PLSG = ASSOCIATED (YD%F_PLSG)
WRITE (KLUN) LF_PLSG
IF (LF_PLSG) THEN
  CALL SAVE (KLUN, YD%F_PLSG)
ENDIF
CALL SAVE (KLUN, YD%YPLSG)
LF_PLSH = ASSOCIATED (YD%F_PLSH)
WRITE (KLUN) LF_PLSH
IF (LF_PLSH) THEN
  CALL SAVE (KLUN, YD%F_PLSH)
ENDIF
CALL SAVE (KLUN, YD%YPLSH)
LF_PLSL = ASSOCIATED (YD%F_PLSL)
WRITE (KLUN) LF_PLSL
IF (LF_PLSL) THEN
  CALL SAVE (KLUN, YD%F_PLSL)
ENDIF
CALL SAVE (KLUN, YD%YPLSL)
LF_PLSN = ASSOCIATED (YD%F_PLSN)
WRITE (KLUN) LF_PLSN
IF (LF_PLSN) THEN
  CALL SAVE (KLUN, YD%F_PLSN)
ENDIF
CALL SAVE (KLUN, YD%YPLSN)
LF_PTYPE2 = ASSOCIATED (YD%F_PTYPE2)
WRITE (KLUN) LF_PTYPE2
IF (LF_PTYPE2) THEN
  CALL SAVE (KLUN, YD%F_PTYPE2)
ENDIF
CALL SAVE (KLUN, YD%YPTYPE2)
LF_PTYPE = ASSOCIATED (YD%F_PTYPE)
WRITE (KLUN) LF_PTYPE
IF (LF_PTYPE) THEN
  CALL SAVE (KLUN, YD%F_PTYPE)
ENDIF
CALL SAVE (KLUN, YD%YPTYPE)
LF_PTYPESEV2 = ASSOCIATED (YD%F_PTYPESEV2)
WRITE (KLUN) LF_PTYPESEV2
IF (LF_PTYPESEV2) THEN
  CALL SAVE (KLUN, YD%F_PTYPESEV2)
ENDIF
CALL SAVE (KLUN, YD%YPTYPESEV2)
LF_PTYPESEV = ASSOCIATED (YD%F_PTYPESEV)
WRITE (KLUN) LF_PTYPESEV
IF (LF_PTYPESEV) THEN
  CALL SAVE (KLUN, YD%F_PTYPESEV)
ENDIF
CALL SAVE (KLUN, YD%YPTYPESEV)
LF_QCLS = ASSOCIATED (YD%F_QCLS)
WRITE (KLUN) LF_QCLS
IF (LF_QCLS) THEN
  CALL SAVE (KLUN, YD%F_QCLS)
ENDIF
CALL SAVE (KLUN, YD%YQCLS)
LF_QICE = ASSOCIATED (YD%F_QICE)
WRITE (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL SAVE (KLUN, YD%F_QICE)
ENDIF
CALL SAVE (KLUN, YD%YQICE)
LF_QLI = ASSOCIATED (YD%F_QLI)
WRITE (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL SAVE (KLUN, YD%F_QLI)
ENDIF
CALL SAVE (KLUN, YD%YQLI)
LF_RHCLS = ASSOCIATED (YD%F_RHCLS)
WRITE (KLUN) LF_RHCLS
IF (LF_RHCLS) THEN
  CALL SAVE (KLUN, YD%F_RHCLS)
ENDIF
CALL SAVE (KLUN, YD%YRHCLS)
LF_RSO = ASSOCIATED (YD%F_RSO)
WRITE (KLUN) LF_RSO
IF (LF_RSO) THEN
  CALL SAVE (KLUN, YD%F_RSO)
ENDIF
CALL SAVE (KLUN, YD%YRSO)
LF_RTH = ASSOCIATED (YD%F_RTH)
WRITE (KLUN) LF_RTH
IF (LF_RTH) THEN
  CALL SAVE (KLUN, YD%F_RTH)
ENDIF
CALL SAVE (KLUN, YD%YRTH)
LF_RUISL = ASSOCIATED (YD%F_RUISL)
WRITE (KLUN) LF_RUISL
IF (LF_RUISL) THEN
  CALL SAVE (KLUN, YD%F_RUISL)
ENDIF
CALL SAVE (KLUN, YD%YRUISL)
LF_RUISP = ASSOCIATED (YD%F_RUISP)
WRITE (KLUN) LF_RUISP
IF (LF_RUISP) THEN
  CALL SAVE (KLUN, YD%F_RUISP)
ENDIF
CALL SAVE (KLUN, YD%YRUISP)
LF_RUISS = ASSOCIATED (YD%F_RUISS)
WRITE (KLUN) LF_RUISS
IF (LF_RUISS) THEN
  CALL SAVE (KLUN, YD%F_RUISS)
ENDIF
CALL SAVE (KLUN, YD%YRUISS)
LF_SIC = ASSOCIATED (YD%F_SIC)
WRITE (KLUN) LF_SIC
IF (LF_SIC) THEN
  CALL SAVE (KLUN, YD%F_SIC)
ENDIF
CALL SAVE (KLUN, YD%YSIC)
LF_TCLS = ASSOCIATED (YD%F_TCLS)
WRITE (KLUN) LF_TCLS
IF (LF_TCLS) THEN
  CALL SAVE (KLUN, YD%F_TCLS)
ENDIF
CALL SAVE (KLUN, YD%YTCLS)
LF_THW = ASSOCIATED (YD%F_THW)
WRITE (KLUN) LF_THW
IF (LF_THW) THEN
  CALL SAVE (KLUN, YD%F_THW)
ENDIF
CALL SAVE (KLUN, YD%YTHW)
LF_TN = ASSOCIATED (YD%F_TN)
WRITE (KLUN) LF_TN
IF (LF_TN) THEN
  CALL SAVE (KLUN, YD%F_TN)
ENDIF
CALL SAVE (KLUN, YD%YTN)
LF_TPWCLS = ASSOCIATED (YD%F_TPWCLS)
WRITE (KLUN) LF_TPWCLS
IF (LF_TPWCLS) THEN
  CALL SAVE (KLUN, YD%F_TPWCLS)
ENDIF
CALL SAVE (KLUN, YD%YTPWCLS)
LF_TRCU = ASSOCIATED (YD%F_TRCU)
WRITE (KLUN) LF_TRCU
IF (LF_TRCU) THEN
  CALL SAVE (KLUN, YD%F_TRCU)
ENDIF
CALL SAVE (KLUN, YD%YTRCU)
LF_TRCV = ASSOCIATED (YD%F_TRCV)
WRITE (KLUN) LF_TRCV
IF (LF_TRCV) THEN
  CALL SAVE (KLUN, YD%F_TRCV)
ENDIF
CALL SAVE (KLUN, YD%YTRCV)
LF_TRDU = ASSOCIATED (YD%F_TRDU)
WRITE (KLUN) LF_TRDU
IF (LF_TRDU) THEN
  CALL SAVE (KLUN, YD%F_TRDU)
ENDIF
CALL SAVE (KLUN, YD%YTRDU)
LF_TRDV = ASSOCIATED (YD%F_TRDV)
WRITE (KLUN) LF_TRDV
IF (LF_TRDV) THEN
  CALL SAVE (KLUN, YD%F_TRDV)
ENDIF
CALL SAVE (KLUN, YD%YTRDV)
LF_TRTU = ASSOCIATED (YD%F_TRTU)
WRITE (KLUN) LF_TRTU
IF (LF_TRTU) THEN
  CALL SAVE (KLUN, YD%F_TRTU)
ENDIF
CALL SAVE (KLUN, YD%YTRTU)
LF_TRTV = ASSOCIATED (YD%F_TRTV)
WRITE (KLUN) LF_TRTV
IF (LF_TRTV) THEN
  CALL SAVE (KLUN, YD%F_TRTV)
ENDIF
CALL SAVE (KLUN, YD%YTRTV)
LF_TX = ASSOCIATED (YD%F_TX)
WRITE (KLUN) LF_TX
IF (LF_TX) THEN
  CALL SAVE (KLUN, YD%F_TX)
ENDIF
CALL SAVE (KLUN, YD%YTX)
LF_UCLS = ASSOCIATED (YD%F_UCLS)
WRITE (KLUN) LF_UCLS
IF (LF_UCLS) THEN
  CALL SAVE (KLUN, YD%F_UCLS)
ENDIF
CALL SAVE (KLUN, YD%YUCLS)
LF_UGST2 = ASSOCIATED (YD%F_UGST2)
WRITE (KLUN) LF_UGST2
IF (LF_UGST2) THEN
  CALL SAVE (KLUN, YD%F_UGST2)
ENDIF
CALL SAVE (KLUN, YD%YUGST2)
LF_UGST = ASSOCIATED (YD%F_UGST)
WRITE (KLUN) LF_UGST
IF (LF_UGST) THEN
  CALL SAVE (KLUN, YD%F_UGST)
ENDIF
CALL SAVE (KLUN, YD%YUGST)
LF_VCLS = ASSOCIATED (YD%F_VCLS)
WRITE (KLUN) LF_VCLS
IF (LF_VCLS) THEN
  CALL SAVE (KLUN, YD%F_VCLS)
ENDIF
CALL SAVE (KLUN, YD%YVCLS)
LF_VEIN = ASSOCIATED (YD%F_VEIN)
WRITE (KLUN) LF_VEIN
IF (LF_VEIN) THEN
  CALL SAVE (KLUN, YD%F_VEIN)
ENDIF
CALL SAVE (KLUN, YD%YVEIN)
LF_VGST2 = ASSOCIATED (YD%F_VGST2)
WRITE (KLUN) LF_VGST2
IF (LF_VGST2) THEN
  CALL SAVE (KLUN, YD%F_VGST2)
ENDIF
CALL SAVE (KLUN, YD%YVGST2)
LF_VGST = ASSOCIATED (YD%F_VGST)
WRITE (KLUN) LF_VGST
IF (LF_VGST) THEN
  CALL SAVE (KLUN, YD%F_VGST)
ENDIF
CALL SAVE (KLUN, YD%YVGST)
LF_VISICLD2 = ASSOCIATED (YD%F_VISICLD2)
WRITE (KLUN) LF_VISICLD2
IF (LF_VISICLD2) THEN
  CALL SAVE (KLUN, YD%F_VISICLD2)
ENDIF
CALL SAVE (KLUN, YD%YVISICLD2)
LF_VISICLD = ASSOCIATED (YD%F_VISICLD)
WRITE (KLUN) LF_VISICLD
IF (LF_VISICLD) THEN
  CALL SAVE (KLUN, YD%F_VISICLD)
ENDIF
CALL SAVE (KLUN, YD%YVISICLD)
LF_VISIHYD2 = ASSOCIATED (YD%F_VISIHYD2)
WRITE (KLUN) LF_VISIHYD2
IF (LF_VISIHYD2) THEN
  CALL SAVE (KLUN, YD%F_VISIHYD2)
ENDIF
CALL SAVE (KLUN, YD%YVISIHYD2)
LF_VISIHYD = ASSOCIATED (YD%F_VISIHYD)
WRITE (KLUN) LF_VISIHYD
IF (LF_VISIHYD) THEN
  CALL SAVE (KLUN, YD%F_VISIHYD)
ENDIF
CALL SAVE (KLUN, YD%YVISIHYD)
LF_XDIAGH = ASSOCIATED (YD%F_XDIAGH)
WRITE (KLUN) LF_XDIAGH
IF (LF_XDIAGH) THEN
  CALL SAVE (KLUN, YD%F_XDIAGH)
ENDIF
CALL SAVE (KLUN, YD%YXDIAGH)
END SUBROUTINE
SUBROUTINE LOAD_TXFU (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TXFU_KEYS_MOD, ONLY : TXFU_KEYS, LOAD_TXFU_KEYS

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TXFU), INTENT (OUT), TARGET :: YD
CLASS (TXFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_CAPE, LF_CLPH, LF_CLWC, LF_CLWC2, LF_CTOP, LF_DICQ, LF_DICS, LF_DITQ, LF_DITS, LF_FCHSP, LF_FEVL, LF_FEVV, LF_FLWSP, LF_FONTE, LF_FTR, LF_HUN, LF_HUX, LF_MOCON, LF_MRT, LF_NBBAS, LF_NBCON, LF_NBHAU, LF_NBMOY, LF_NEB, LF_NEBT, LF_NUCLS, LF_NVCLS, LF_PLCG, LF_PLCH, LF_PLCL, LF_PLCN, LF_PLSG, LF_PLSH, LF_PLSL, LF_PLSN, LF_PTYPE, LF_PTYPE2, LF_PTYPESEV, LF_PTYPESEV2, LF_QCLS, LF_QICE, LF_QLI, LF_RHCLS, LF_RMNWINDCALC, LF_RMWINDCALC, LF_RSO, LF_RTH, LF_RUISL, LF_RUISP, LF_RUISS, LF_SIC, LF_TCLS, LF_THW, LF_TN, LF_TPWCLS, LF_TRCU, LF_TRCV, LF_TRDU, LF_TRDV, LF_TRTU, LF_TRTV, LF_TX, LF_UCLS, LF_UGST, LF_UGST2, LF_VCLS, LF_VEIN, LF_VGST, LF_VGST2, LF_VISICLD, LF_VISICLD2, LF_VISIHYD, LF_VISIHYD2, LF_XDIAGH
YLSUPER => YD
CALL LOAD_TXFU_KEYS (KLUN, YLSUPER)
NULLIFY (YD%RMWINDCALC_B)
NULLIFY (YD%RMWINDCALC)
READ (KLUN) LF_RMWINDCALC
IF (LF_RMWINDCALC) THEN
  CALL LOAD (KLUN, YD%F_RMWINDCALC)
ELSE
  NULLIFY (YD%F_RMWINDCALC)
ENDIF
NULLIFY (YD%RMNWINDCALC_B)
NULLIFY (YD%RMNWINDCALC)
READ (KLUN) LF_RMNWINDCALC
IF (LF_RMNWINDCALC) THEN
  CALL LOAD (KLUN, YD%F_RMNWINDCALC)
ELSE
  NULLIFY (YD%F_RMNWINDCALC)
ENDIF
READ (KLUN) YD%MEANPERIOD
READ (KLUN) YD%NMEANSTEPS
READ (KLUN) YD%NXGSTPERIOD
READ (KLUN) YD%NXGSTPERIOD2
READ (KLUN) YD%NVISIPERIOD
READ (KLUN) YD%NVISIPERIOD2
READ (KLUN) YD%NXGSTTS
READ (KLUN) YD%NTYPXFU
READ (KLUN) YD%NXFUTS
READ (KLUN) YD%NFRXFU
READ (KLUN) YD%NRAZTS
READ (KLUN) YD%NFRRAZ
READ (KLUN) YD%N1RAZ
READ (KLUN) YD%NFDXFU
READ (KLUN) YD%LRESET
READ (KLUN) YD%LRESET_GST
READ (KLUN) YD%LRESET_GST2
READ (KLUN) YD%LRESET_PRECIP
READ (KLUN) YD%LRESET_PRECIP2
READ (KLUN) YD%LRESET_VISI
READ (KLUN) YD%LRESET_VISI2
READ (KLUN) YD%LREAXFU
NULLIFY (YD%XFUBUF_B)
NULLIFY (YD%CAPE)
READ (KLUN) LF_CAPE
IF (LF_CAPE) THEN
  CALL LOAD (KLUN, YD%F_CAPE)
ELSE
  NULLIFY (YD%F_CAPE)
ENDIF
CALL LOAD (KLUN, YD%YCAPE)
NULLIFY (YD%CLPH)
READ (KLUN) LF_CLPH
IF (LF_CLPH) THEN
  CALL LOAD (KLUN, YD%F_CLPH)
ELSE
  NULLIFY (YD%F_CLPH)
ENDIF
CALL LOAD (KLUN, YD%YCLPH)
NULLIFY (YD%CLWC2)
READ (KLUN) LF_CLWC2
IF (LF_CLWC2) THEN
  CALL LOAD (KLUN, YD%F_CLWC2)
ELSE
  NULLIFY (YD%F_CLWC2)
ENDIF
CALL LOAD (KLUN, YD%YCLWC2)
NULLIFY (YD%CLWC)
READ (KLUN) LF_CLWC
IF (LF_CLWC) THEN
  CALL LOAD (KLUN, YD%F_CLWC)
ELSE
  NULLIFY (YD%F_CLWC)
ENDIF
CALL LOAD (KLUN, YD%YCLWC)
NULLIFY (YD%CTOP)
READ (KLUN) LF_CTOP
IF (LF_CTOP) THEN
  CALL LOAD (KLUN, YD%F_CTOP)
ELSE
  NULLIFY (YD%F_CTOP)
ENDIF
CALL LOAD (KLUN, YD%YCTOP)
NULLIFY (YD%DICQ)
READ (KLUN) LF_DICQ
IF (LF_DICQ) THEN
  CALL LOAD (KLUN, YD%F_DICQ)
ELSE
  NULLIFY (YD%F_DICQ)
ENDIF
CALL LOAD (KLUN, YD%YDICQ)
NULLIFY (YD%DICS)
READ (KLUN) LF_DICS
IF (LF_DICS) THEN
  CALL LOAD (KLUN, YD%F_DICS)
ELSE
  NULLIFY (YD%F_DICS)
ENDIF
CALL LOAD (KLUN, YD%YDICS)
NULLIFY (YD%DITQ)
READ (KLUN) LF_DITQ
IF (LF_DITQ) THEN
  CALL LOAD (KLUN, YD%F_DITQ)
ELSE
  NULLIFY (YD%F_DITQ)
ENDIF
CALL LOAD (KLUN, YD%YDITQ)
NULLIFY (YD%DITS)
READ (KLUN) LF_DITS
IF (LF_DITS) THEN
  CALL LOAD (KLUN, YD%F_DITS)
ELSE
  NULLIFY (YD%F_DITS)
ENDIF
CALL LOAD (KLUN, YD%YDITS)
NULLIFY (YD%FCHSP)
READ (KLUN) LF_FCHSP
IF (LF_FCHSP) THEN
  CALL LOAD (KLUN, YD%F_FCHSP)
ELSE
  NULLIFY (YD%F_FCHSP)
ENDIF
CALL LOAD (KLUN, YD%YFCHSP)
NULLIFY (YD%FEVL)
READ (KLUN) LF_FEVL
IF (LF_FEVL) THEN
  CALL LOAD (KLUN, YD%F_FEVL)
ELSE
  NULLIFY (YD%F_FEVL)
ENDIF
CALL LOAD (KLUN, YD%YFEVL)
NULLIFY (YD%FEVV)
READ (KLUN) LF_FEVV
IF (LF_FEVV) THEN
  CALL LOAD (KLUN, YD%F_FEVV)
ELSE
  NULLIFY (YD%F_FEVV)
ENDIF
CALL LOAD (KLUN, YD%YFEVV)
NULLIFY (YD%FLWSP)
READ (KLUN) LF_FLWSP
IF (LF_FLWSP) THEN
  CALL LOAD (KLUN, YD%F_FLWSP)
ELSE
  NULLIFY (YD%F_FLWSP)
ENDIF
CALL LOAD (KLUN, YD%YFLWSP)
NULLIFY (YD%FONTE)
READ (KLUN) LF_FONTE
IF (LF_FONTE) THEN
  CALL LOAD (KLUN, YD%F_FONTE)
ELSE
  NULLIFY (YD%F_FONTE)
ENDIF
CALL LOAD (KLUN, YD%YFONTE)
NULLIFY (YD%FTR)
READ (KLUN) LF_FTR
IF (LF_FTR) THEN
  CALL LOAD (KLUN, YD%F_FTR)
ELSE
  NULLIFY (YD%F_FTR)
ENDIF
CALL LOAD (KLUN, YD%YFTR)
NULLIFY (YD%HUN)
READ (KLUN) LF_HUN
IF (LF_HUN) THEN
  CALL LOAD (KLUN, YD%F_HUN)
ELSE
  NULLIFY (YD%F_HUN)
ENDIF
CALL LOAD (KLUN, YD%YHUN)
NULLIFY (YD%HUX)
READ (KLUN) LF_HUX
IF (LF_HUX) THEN
  CALL LOAD (KLUN, YD%F_HUX)
ELSE
  NULLIFY (YD%F_HUX)
ENDIF
CALL LOAD (KLUN, YD%YHUX)
NULLIFY (YD%MOCON)
READ (KLUN) LF_MOCON
IF (LF_MOCON) THEN
  CALL LOAD (KLUN, YD%F_MOCON)
ELSE
  NULLIFY (YD%F_MOCON)
ENDIF
CALL LOAD (KLUN, YD%YMOCON)
NULLIFY (YD%MRT)
READ (KLUN) LF_MRT
IF (LF_MRT) THEN
  CALL LOAD (KLUN, YD%F_MRT)
ELSE
  NULLIFY (YD%F_MRT)
ENDIF
CALL LOAD (KLUN, YD%YMRT)
NULLIFY (YD%NBBAS)
READ (KLUN) LF_NBBAS
IF (LF_NBBAS) THEN
  CALL LOAD (KLUN, YD%F_NBBAS)
ELSE
  NULLIFY (YD%F_NBBAS)
ENDIF
CALL LOAD (KLUN, YD%YNBBAS)
NULLIFY (YD%NBCON)
READ (KLUN) LF_NBCON
IF (LF_NBCON) THEN
  CALL LOAD (KLUN, YD%F_NBCON)
ELSE
  NULLIFY (YD%F_NBCON)
ENDIF
CALL LOAD (KLUN, YD%YNBCON)
NULLIFY (YD%NBHAU)
READ (KLUN) LF_NBHAU
IF (LF_NBHAU) THEN
  CALL LOAD (KLUN, YD%F_NBHAU)
ELSE
  NULLIFY (YD%F_NBHAU)
ENDIF
CALL LOAD (KLUN, YD%YNBHAU)
NULLIFY (YD%NBMOY)
READ (KLUN) LF_NBMOY
IF (LF_NBMOY) THEN
  CALL LOAD (KLUN, YD%F_NBMOY)
ELSE
  NULLIFY (YD%F_NBMOY)
ENDIF
CALL LOAD (KLUN, YD%YNBMOY)
NULLIFY (YD%NEB)
READ (KLUN) LF_NEB
IF (LF_NEB) THEN
  CALL LOAD (KLUN, YD%F_NEB)
ELSE
  NULLIFY (YD%F_NEB)
ENDIF
CALL LOAD (KLUN, YD%YNEB)
NULLIFY (YD%NEBT)
READ (KLUN) LF_NEBT
IF (LF_NEBT) THEN
  CALL LOAD (KLUN, YD%F_NEBT)
ELSE
  NULLIFY (YD%F_NEBT)
ENDIF
CALL LOAD (KLUN, YD%YNEBT)
NULLIFY (YD%NUCLS)
READ (KLUN) LF_NUCLS
IF (LF_NUCLS) THEN
  CALL LOAD (KLUN, YD%F_NUCLS)
ELSE
  NULLIFY (YD%F_NUCLS)
ENDIF
CALL LOAD (KLUN, YD%YNUCLS)
NULLIFY (YD%NVCLS)
READ (KLUN) LF_NVCLS
IF (LF_NVCLS) THEN
  CALL LOAD (KLUN, YD%F_NVCLS)
ELSE
  NULLIFY (YD%F_NVCLS)
ENDIF
CALL LOAD (KLUN, YD%YNVCLS)
NULLIFY (YD%PLCG)
READ (KLUN) LF_PLCG
IF (LF_PLCG) THEN
  CALL LOAD (KLUN, YD%F_PLCG)
ELSE
  NULLIFY (YD%F_PLCG)
ENDIF
CALL LOAD (KLUN, YD%YPLCG)
NULLIFY (YD%PLCH)
READ (KLUN) LF_PLCH
IF (LF_PLCH) THEN
  CALL LOAD (KLUN, YD%F_PLCH)
ELSE
  NULLIFY (YD%F_PLCH)
ENDIF
CALL LOAD (KLUN, YD%YPLCH)
NULLIFY (YD%PLCL)
READ (KLUN) LF_PLCL
IF (LF_PLCL) THEN
  CALL LOAD (KLUN, YD%F_PLCL)
ELSE
  NULLIFY (YD%F_PLCL)
ENDIF
CALL LOAD (KLUN, YD%YPLCL)
NULLIFY (YD%PLCN)
READ (KLUN) LF_PLCN
IF (LF_PLCN) THEN
  CALL LOAD (KLUN, YD%F_PLCN)
ELSE
  NULLIFY (YD%F_PLCN)
ENDIF
CALL LOAD (KLUN, YD%YPLCN)
NULLIFY (YD%PLSG)
READ (KLUN) LF_PLSG
IF (LF_PLSG) THEN
  CALL LOAD (KLUN, YD%F_PLSG)
ELSE
  NULLIFY (YD%F_PLSG)
ENDIF
CALL LOAD (KLUN, YD%YPLSG)
NULLIFY (YD%PLSH)
READ (KLUN) LF_PLSH
IF (LF_PLSH) THEN
  CALL LOAD (KLUN, YD%F_PLSH)
ELSE
  NULLIFY (YD%F_PLSH)
ENDIF
CALL LOAD (KLUN, YD%YPLSH)
NULLIFY (YD%PLSL)
READ (KLUN) LF_PLSL
IF (LF_PLSL) THEN
  CALL LOAD (KLUN, YD%F_PLSL)
ELSE
  NULLIFY (YD%F_PLSL)
ENDIF
CALL LOAD (KLUN, YD%YPLSL)
NULLIFY (YD%PLSN)
READ (KLUN) LF_PLSN
IF (LF_PLSN) THEN
  CALL LOAD (KLUN, YD%F_PLSN)
ELSE
  NULLIFY (YD%F_PLSN)
ENDIF
CALL LOAD (KLUN, YD%YPLSN)
NULLIFY (YD%PTYPE2)
READ (KLUN) LF_PTYPE2
IF (LF_PTYPE2) THEN
  CALL LOAD (KLUN, YD%F_PTYPE2)
ELSE
  NULLIFY (YD%F_PTYPE2)
ENDIF
CALL LOAD (KLUN, YD%YPTYPE2)
NULLIFY (YD%PTYPE)
READ (KLUN) LF_PTYPE
IF (LF_PTYPE) THEN
  CALL LOAD (KLUN, YD%F_PTYPE)
ELSE
  NULLIFY (YD%F_PTYPE)
ENDIF
CALL LOAD (KLUN, YD%YPTYPE)
NULLIFY (YD%PTYPESEV2)
READ (KLUN) LF_PTYPESEV2
IF (LF_PTYPESEV2) THEN
  CALL LOAD (KLUN, YD%F_PTYPESEV2)
ELSE
  NULLIFY (YD%F_PTYPESEV2)
ENDIF
CALL LOAD (KLUN, YD%YPTYPESEV2)
NULLIFY (YD%PTYPESEV)
READ (KLUN) LF_PTYPESEV
IF (LF_PTYPESEV) THEN
  CALL LOAD (KLUN, YD%F_PTYPESEV)
ELSE
  NULLIFY (YD%F_PTYPESEV)
ENDIF
CALL LOAD (KLUN, YD%YPTYPESEV)
NULLIFY (YD%QCLS)
READ (KLUN) LF_QCLS
IF (LF_QCLS) THEN
  CALL LOAD (KLUN, YD%F_QCLS)
ELSE
  NULLIFY (YD%F_QCLS)
ENDIF
CALL LOAD (KLUN, YD%YQCLS)
NULLIFY (YD%QICE)
READ (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL LOAD (KLUN, YD%F_QICE)
ELSE
  NULLIFY (YD%F_QICE)
ENDIF
CALL LOAD (KLUN, YD%YQICE)
NULLIFY (YD%QLI)
READ (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL LOAD (KLUN, YD%F_QLI)
ELSE
  NULLIFY (YD%F_QLI)
ENDIF
CALL LOAD (KLUN, YD%YQLI)
NULLIFY (YD%RHCLS)
READ (KLUN) LF_RHCLS
IF (LF_RHCLS) THEN
  CALL LOAD (KLUN, YD%F_RHCLS)
ELSE
  NULLIFY (YD%F_RHCLS)
ENDIF
CALL LOAD (KLUN, YD%YRHCLS)
NULLIFY (YD%RSO)
READ (KLUN) LF_RSO
IF (LF_RSO) THEN
  CALL LOAD (KLUN, YD%F_RSO)
ELSE
  NULLIFY (YD%F_RSO)
ENDIF
CALL LOAD (KLUN, YD%YRSO)
NULLIFY (YD%RTH)
READ (KLUN) LF_RTH
IF (LF_RTH) THEN
  CALL LOAD (KLUN, YD%F_RTH)
ELSE
  NULLIFY (YD%F_RTH)
ENDIF
CALL LOAD (KLUN, YD%YRTH)
NULLIFY (YD%RUISL)
READ (KLUN) LF_RUISL
IF (LF_RUISL) THEN
  CALL LOAD (KLUN, YD%F_RUISL)
ELSE
  NULLIFY (YD%F_RUISL)
ENDIF
CALL LOAD (KLUN, YD%YRUISL)
NULLIFY (YD%RUISP)
READ (KLUN) LF_RUISP
IF (LF_RUISP) THEN
  CALL LOAD (KLUN, YD%F_RUISP)
ELSE
  NULLIFY (YD%F_RUISP)
ENDIF
CALL LOAD (KLUN, YD%YRUISP)
NULLIFY (YD%RUISS)
READ (KLUN) LF_RUISS
IF (LF_RUISS) THEN
  CALL LOAD (KLUN, YD%F_RUISS)
ELSE
  NULLIFY (YD%F_RUISS)
ENDIF
CALL LOAD (KLUN, YD%YRUISS)
NULLIFY (YD%SIC)
READ (KLUN) LF_SIC
IF (LF_SIC) THEN
  CALL LOAD (KLUN, YD%F_SIC)
ELSE
  NULLIFY (YD%F_SIC)
ENDIF
CALL LOAD (KLUN, YD%YSIC)
NULLIFY (YD%TCLS)
READ (KLUN) LF_TCLS
IF (LF_TCLS) THEN
  CALL LOAD (KLUN, YD%F_TCLS)
ELSE
  NULLIFY (YD%F_TCLS)
ENDIF
CALL LOAD (KLUN, YD%YTCLS)
NULLIFY (YD%THW)
READ (KLUN) LF_THW
IF (LF_THW) THEN
  CALL LOAD (KLUN, YD%F_THW)
ELSE
  NULLIFY (YD%F_THW)
ENDIF
CALL LOAD (KLUN, YD%YTHW)
NULLIFY (YD%TN)
READ (KLUN) LF_TN
IF (LF_TN) THEN
  CALL LOAD (KLUN, YD%F_TN)
ELSE
  NULLIFY (YD%F_TN)
ENDIF
CALL LOAD (KLUN, YD%YTN)
NULLIFY (YD%TPWCLS)
READ (KLUN) LF_TPWCLS
IF (LF_TPWCLS) THEN
  CALL LOAD (KLUN, YD%F_TPWCLS)
ELSE
  NULLIFY (YD%F_TPWCLS)
ENDIF
CALL LOAD (KLUN, YD%YTPWCLS)
NULLIFY (YD%TRCU)
READ (KLUN) LF_TRCU
IF (LF_TRCU) THEN
  CALL LOAD (KLUN, YD%F_TRCU)
ELSE
  NULLIFY (YD%F_TRCU)
ENDIF
CALL LOAD (KLUN, YD%YTRCU)
NULLIFY (YD%TRCV)
READ (KLUN) LF_TRCV
IF (LF_TRCV) THEN
  CALL LOAD (KLUN, YD%F_TRCV)
ELSE
  NULLIFY (YD%F_TRCV)
ENDIF
CALL LOAD (KLUN, YD%YTRCV)
NULLIFY (YD%TRDU)
READ (KLUN) LF_TRDU
IF (LF_TRDU) THEN
  CALL LOAD (KLUN, YD%F_TRDU)
ELSE
  NULLIFY (YD%F_TRDU)
ENDIF
CALL LOAD (KLUN, YD%YTRDU)
NULLIFY (YD%TRDV)
READ (KLUN) LF_TRDV
IF (LF_TRDV) THEN
  CALL LOAD (KLUN, YD%F_TRDV)
ELSE
  NULLIFY (YD%F_TRDV)
ENDIF
CALL LOAD (KLUN, YD%YTRDV)
NULLIFY (YD%TRTU)
READ (KLUN) LF_TRTU
IF (LF_TRTU) THEN
  CALL LOAD (KLUN, YD%F_TRTU)
ELSE
  NULLIFY (YD%F_TRTU)
ENDIF
CALL LOAD (KLUN, YD%YTRTU)
NULLIFY (YD%TRTV)
READ (KLUN) LF_TRTV
IF (LF_TRTV) THEN
  CALL LOAD (KLUN, YD%F_TRTV)
ELSE
  NULLIFY (YD%F_TRTV)
ENDIF
CALL LOAD (KLUN, YD%YTRTV)
NULLIFY (YD%TX)
READ (KLUN) LF_TX
IF (LF_TX) THEN
  CALL LOAD (KLUN, YD%F_TX)
ELSE
  NULLIFY (YD%F_TX)
ENDIF
CALL LOAD (KLUN, YD%YTX)
NULLIFY (YD%UCLS)
READ (KLUN) LF_UCLS
IF (LF_UCLS) THEN
  CALL LOAD (KLUN, YD%F_UCLS)
ELSE
  NULLIFY (YD%F_UCLS)
ENDIF
CALL LOAD (KLUN, YD%YUCLS)
NULLIFY (YD%UGST2)
READ (KLUN) LF_UGST2
IF (LF_UGST2) THEN
  CALL LOAD (KLUN, YD%F_UGST2)
ELSE
  NULLIFY (YD%F_UGST2)
ENDIF
CALL LOAD (KLUN, YD%YUGST2)
NULLIFY (YD%UGST)
READ (KLUN) LF_UGST
IF (LF_UGST) THEN
  CALL LOAD (KLUN, YD%F_UGST)
ELSE
  NULLIFY (YD%F_UGST)
ENDIF
CALL LOAD (KLUN, YD%YUGST)
NULLIFY (YD%VCLS)
READ (KLUN) LF_VCLS
IF (LF_VCLS) THEN
  CALL LOAD (KLUN, YD%F_VCLS)
ELSE
  NULLIFY (YD%F_VCLS)
ENDIF
CALL LOAD (KLUN, YD%YVCLS)
NULLIFY (YD%VEIN)
READ (KLUN) LF_VEIN
IF (LF_VEIN) THEN
  CALL LOAD (KLUN, YD%F_VEIN)
ELSE
  NULLIFY (YD%F_VEIN)
ENDIF
CALL LOAD (KLUN, YD%YVEIN)
NULLIFY (YD%VGST2)
READ (KLUN) LF_VGST2
IF (LF_VGST2) THEN
  CALL LOAD (KLUN, YD%F_VGST2)
ELSE
  NULLIFY (YD%F_VGST2)
ENDIF
CALL LOAD (KLUN, YD%YVGST2)
NULLIFY (YD%VGST)
READ (KLUN) LF_VGST
IF (LF_VGST) THEN
  CALL LOAD (KLUN, YD%F_VGST)
ELSE
  NULLIFY (YD%F_VGST)
ENDIF
CALL LOAD (KLUN, YD%YVGST)
NULLIFY (YD%VISICLD2)
READ (KLUN) LF_VISICLD2
IF (LF_VISICLD2) THEN
  CALL LOAD (KLUN, YD%F_VISICLD2)
ELSE
  NULLIFY (YD%F_VISICLD2)
ENDIF
CALL LOAD (KLUN, YD%YVISICLD2)
NULLIFY (YD%VISICLD)
READ (KLUN) LF_VISICLD
IF (LF_VISICLD) THEN
  CALL LOAD (KLUN, YD%F_VISICLD)
ELSE
  NULLIFY (YD%F_VISICLD)
ENDIF
CALL LOAD (KLUN, YD%YVISICLD)
NULLIFY (YD%VISIHYD2)
READ (KLUN) LF_VISIHYD2
IF (LF_VISIHYD2) THEN
  CALL LOAD (KLUN, YD%F_VISIHYD2)
ELSE
  NULLIFY (YD%F_VISIHYD2)
ENDIF
CALL LOAD (KLUN, YD%YVISIHYD2)
NULLIFY (YD%VISIHYD)
READ (KLUN) LF_VISIHYD
IF (LF_VISIHYD) THEN
  CALL LOAD (KLUN, YD%F_VISIHYD)
ELSE
  NULLIFY (YD%F_VISIHYD)
ENDIF
CALL LOAD (KLUN, YD%YVISIHYD)
NULLIFY (YD%XDIAGH)
READ (KLUN) LF_XDIAGH
IF (LF_XDIAGH) THEN
  CALL LOAD (KLUN, YD%F_XDIAGH)
ELSE
  NULLIFY (YD%F_XDIAGH)
ENDIF
CALL LOAD (KLUN, YD%YXDIAGH)
END SUBROUTINE




END MODULE
