MODULE UTIL_TCSGEOM_MOD

USE YOMCSGEOM, ONLY : TCSGEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCSGEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCSGEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCSGEOM
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCSGEOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCSGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGEOM), INTENT (IN), TARGET :: YD
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LRCOLON = ASSOCIATED (YD%RCOLON)
WRITE (KLUN) LRCOLON
IF (LRCOLON) THEN
  WRITE (KLUN) LBOUND (YD%RCOLON)
  WRITE (KLUN) UBOUND (YD%RCOLON)
  WRITE (KLUN) YD%RCOLON
ENDIF
LRSILON = ASSOCIATED (YD%RSILON)
WRITE (KLUN) LRSILON
IF (LRSILON) THEN
  WRITE (KLUN) LBOUND (YD%RSILON)
  WRITE (KLUN) UBOUND (YD%RSILON)
  WRITE (KLUN) YD%RSILON
ENDIF
LRINDX = ASSOCIATED (YD%RINDX)
WRITE (KLUN) LRINDX
IF (LRINDX) THEN
  WRITE (KLUN) LBOUND (YD%RINDX)
  WRITE (KLUN) UBOUND (YD%RINDX)
  WRITE (KLUN) YD%RINDX
ENDIF
LRINDY = ASSOCIATED (YD%RINDY)
WRITE (KLUN) LRINDY
IF (LRINDY) THEN
  WRITE (KLUN) LBOUND (YD%RINDY)
  WRITE (KLUN) UBOUND (YD%RINDY)
  WRITE (KLUN) YD%RINDY
ENDIF
LRATATH = ASSOCIATED (YD%RATATH)
WRITE (KLUN) LRATATH
IF (LRATATH) THEN
  WRITE (KLUN) LBOUND (YD%RATATH)
  WRITE (KLUN) UBOUND (YD%RATATH)
  WRITE (KLUN) YD%RATATH
ENDIF
LRATATX = ASSOCIATED (YD%RATATX)
WRITE (KLUN) LRATATX
IF (LRATATX) THEN
  WRITE (KLUN) LBOUND (YD%RATATX)
  WRITE (KLUN) UBOUND (YD%RATATX)
  WRITE (KLUN) YD%RATATX
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TCSGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGEOM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
READ (KLUN) LRCOLON
IF (LRCOLON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCOLON (IL1(1):IU1(1)))
  READ (KLUN) YD%RCOLON
ELSE
  NULLIFY (YD%RCOLON)
ENDIF
READ (KLUN) LRSILON
IF (LRSILON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSILON (IL1(1):IU1(1)))
  READ (KLUN) YD%RSILON
ELSE
  NULLIFY (YD%RSILON)
ENDIF
READ (KLUN) LRINDX
IF (LRINDX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RINDX (IL1(1):IU1(1)))
  READ (KLUN) YD%RINDX
ELSE
  NULLIFY (YD%RINDX)
ENDIF
READ (KLUN) LRINDY
IF (LRINDY) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RINDY (IL1(1):IU1(1)))
  READ (KLUN) YD%RINDY
ELSE
  NULLIFY (YD%RINDY)
ENDIF
READ (KLUN) LRATATH
IF (LRATATH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RATATH (IL1(1):IU1(1)))
  READ (KLUN) YD%RATATH
ELSE
  NULLIFY (YD%RATATH)
ENDIF
READ (KLUN) LRATATX
IF (LRATATX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RATATX (IL1(1):IU1(1)))
  READ (KLUN) YD%RATATX
ELSE
  NULLIFY (YD%RATATX)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TCSGEOM (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRCOLON = ASSOCIATED (YD%RCOLON)
IF (LRCOLON) THEN
  !$acc enter data create (YD%RCOLON)
  !$acc update device (YD%RCOLON)
  !$acc enter data attach (YD%RCOLON)
ENDIF

LRSILON = ASSOCIATED (YD%RSILON)
IF (LRSILON) THEN
  !$acc enter data create (YD%RSILON)
  !$acc update device (YD%RSILON)
  !$acc enter data attach (YD%RSILON)
ENDIF

LRINDX = ASSOCIATED (YD%RINDX)
IF (LRINDX) THEN
  !$acc enter data create (YD%RINDX)
  !$acc update device (YD%RINDX)
  !$acc enter data attach (YD%RINDX)
ENDIF

LRINDY = ASSOCIATED (YD%RINDY)
IF (LRINDY) THEN
  !$acc enter data create (YD%RINDY)
  !$acc update device (YD%RINDY)
  !$acc enter data attach (YD%RINDY)
ENDIF

LRATATH = ASSOCIATED (YD%RATATH)
IF (LRATATH) THEN
  !$acc enter data create (YD%RATATH)
  !$acc update device (YD%RATATH)
  !$acc enter data attach (YD%RATATH)
ENDIF

LRATATX = ASSOCIATED (YD%RATATX)
IF (LRATATX) THEN
  !$acc enter data create (YD%RATATX)
  !$acc update device (YD%RATATX)
  !$acc enter data attach (YD%RATATX)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TCSGEOM (YD, LDDELETED)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

LRCOLON = ASSOCIATED (YD%RCOLON)
IF (LRCOLON) THEN
  !$acc exit data detach (YD%RCOLON)
  !$acc exit data delete (YD%RCOLON)
ENDIF

LRSILON = ASSOCIATED (YD%RSILON)
IF (LRSILON) THEN
  !$acc exit data detach (YD%RSILON)
  !$acc exit data delete (YD%RSILON)
ENDIF

LRINDX = ASSOCIATED (YD%RINDX)
IF (LRINDX) THEN
  !$acc exit data detach (YD%RINDX)
  !$acc exit data delete (YD%RINDX)
ENDIF

LRINDY = ASSOCIATED (YD%RINDY)
IF (LRINDY) THEN
  !$acc exit data detach (YD%RINDY)
  !$acc exit data delete (YD%RINDY)
ENDIF

LRATATH = ASSOCIATED (YD%RATATH)
IF (LRATATH) THEN
  !$acc exit data detach (YD%RATATH)
  !$acc exit data delete (YD%RATATH)
ENDIF

LRATATX = ASSOCIATED (YD%RATATX)
IF (LRATATX) THEN
  !$acc exit data detach (YD%RATATX)
  !$acc exit data delete (YD%RATATX)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
