MODULE UTIL_THSLMER_MOD

USE YOMHSLMER, ONLY : THSLMER

INTERFACE SAVE
MODULE PROCEDURE SAVE_THSLMER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_THSLMER
END INTERFACE




CONTAINS

SUBROUTINE SAVE_THSLMER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (THSLMER), INTENT (IN), TARGET :: YD
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW
LRIPI = ALLOCATED (YD%RIPI)
WRITE (KLUN) LRIPI
IF (LRIPI) THEN
  WRITE (KLUN) LBOUND (YD%RIPI)
  WRITE (KLUN) UBOUND (YD%RIPI)
  WRITE (KLUN) YD%RIPI
ENDIF
LRSLD = ALLOCATED (YD%RSLD)
WRITE (KLUN) LRSLD
IF (LRSLD) THEN
  WRITE (KLUN) LBOUND (YD%RSLD)
  WRITE (KLUN) UBOUND (YD%RSLD)
  WRITE (KLUN) YD%RSLD
ENDIF
LRSLDW = ALLOCATED (YD%RSLDW)
WRITE (KLUN) LRSLDW
IF (LRSLDW) THEN
  WRITE (KLUN) LBOUND (YD%RSLDW)
  WRITE (KLUN) UBOUND (YD%RSLDW)
  WRITE (KLUN) YD%RSLDW
ENDIF
LR3DTW = ALLOCATED (YD%R3DTW)
WRITE (KLUN) LR3DTW
IF (LR3DTW) THEN
  WRITE (KLUN) LBOUND (YD%R3DTW)
  WRITE (KLUN) UBOUND (YD%R3DTW)
  WRITE (KLUN) YD%R3DTW
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_THSLMER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (THSLMER), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW
READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RIPI
ENDIF
READ (KLUN) LRSLD
IF (LRSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSLD
ENDIF
READ (KLUN) LRSLDW
IF (LRSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RSLDW
ENDIF
READ (KLUN) LR3DTW
IF (LR3DTW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%R3DTW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%R3DTW
ENDIF
END SUBROUTINE




END MODULE
