MODULE UTIL_TCCO_MOD

USE INTDYNSL_MOD, ONLY : TCCO

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCCO
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCCO
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCCO
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCCO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCCO), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_RLON
WRITE (KLUN) YD%M_RLAT
WRITE (KLUN) YD%M_RQX
WRITE (KLUN) YD%M_RQY
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TCCO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCCO), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_RLON
READ (KLUN) YD%M_RLAT
READ (KLUN) YD%M_RQX
READ (KLUN) YD%M_RQY
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TCCO (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCCO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





END SUBROUTINE



END MODULE
