MODULE UTIL_TSPDDH_MOD

USE YOMSPDDH, ONLY : TSPDDH


INTERFACE SAVE
MODULE PROCEDURE SAVE_TSPDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSPDDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSPDDH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSPDDH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSPDDH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LSPTNDHD_DIV, LSPTNDHD_GFL, LSPTNDHD_SNHX, LSPTNDHD_SPD, LSPTNDHD_SVD, LSPTNDHD_T, LSPTNDHD_VOR, LSPTNDSI_DIV, LSPTNDSI_SPD, LSPTNDSI_SVD
LOGICAL :: LSPTNDSI_T, LSPTNDSI_VOR

LSPTNDHD_VOR = ALLOCATED (YD%SPTNDHD_VOR)
WRITE (KLUN) LSPTNDHD_VOR
IF (LSPTNDHD_VOR) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_VOR)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_VOR)
  WRITE (KLUN) YD%SPTNDHD_VOR
ENDIF
LSPTNDHD_DIV = ALLOCATED (YD%SPTNDHD_DIV)
WRITE (KLUN) LSPTNDHD_DIV
IF (LSPTNDHD_DIV) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_DIV)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_DIV)
  WRITE (KLUN) YD%SPTNDHD_DIV
ENDIF
LSPTNDHD_T = ALLOCATED (YD%SPTNDHD_T)
WRITE (KLUN) LSPTNDHD_T
IF (LSPTNDHD_T) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_T)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_T)
  WRITE (KLUN) YD%SPTNDHD_T
ENDIF
LSPTNDHD_SPD = ALLOCATED (YD%SPTNDHD_SPD)
WRITE (KLUN) LSPTNDHD_SPD
IF (LSPTNDHD_SPD) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_SPD)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_SPD)
  WRITE (KLUN) YD%SPTNDHD_SPD
ENDIF
LSPTNDHD_SVD = ALLOCATED (YD%SPTNDHD_SVD)
WRITE (KLUN) LSPTNDHD_SVD
IF (LSPTNDHD_SVD) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_SVD)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_SVD)
  WRITE (KLUN) YD%SPTNDHD_SVD
ENDIF
LSPTNDHD_SNHX = ALLOCATED (YD%SPTNDHD_SNHX)
WRITE (KLUN) LSPTNDHD_SNHX
IF (LSPTNDHD_SNHX) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_SNHX)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_SNHX)
  WRITE (KLUN) YD%SPTNDHD_SNHX
ENDIF
LSPTNDHD_GFL = ALLOCATED (YD%SPTNDHD_GFL)
WRITE (KLUN) LSPTNDHD_GFL
IF (LSPTNDHD_GFL) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDHD_GFL)
  WRITE (KLUN) UBOUND (YD%SPTNDHD_GFL)
  WRITE (KLUN) YD%SPTNDHD_GFL
ENDIF
LSPTNDSI_VOR = ALLOCATED (YD%SPTNDSI_VOR)
WRITE (KLUN) LSPTNDSI_VOR
IF (LSPTNDSI_VOR) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDSI_VOR)
  WRITE (KLUN) UBOUND (YD%SPTNDSI_VOR)
  WRITE (KLUN) YD%SPTNDSI_VOR
ENDIF
LSPTNDSI_DIV = ALLOCATED (YD%SPTNDSI_DIV)
WRITE (KLUN) LSPTNDSI_DIV
IF (LSPTNDSI_DIV) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDSI_DIV)
  WRITE (KLUN) UBOUND (YD%SPTNDSI_DIV)
  WRITE (KLUN) YD%SPTNDSI_DIV
ENDIF
LSPTNDSI_T = ALLOCATED (YD%SPTNDSI_T)
WRITE (KLUN) LSPTNDSI_T
IF (LSPTNDSI_T) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDSI_T)
  WRITE (KLUN) UBOUND (YD%SPTNDSI_T)
  WRITE (KLUN) YD%SPTNDSI_T
ENDIF
LSPTNDSI_SPD = ALLOCATED (YD%SPTNDSI_SPD)
WRITE (KLUN) LSPTNDSI_SPD
IF (LSPTNDSI_SPD) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDSI_SPD)
  WRITE (KLUN) UBOUND (YD%SPTNDSI_SPD)
  WRITE (KLUN) YD%SPTNDSI_SPD
ENDIF
LSPTNDSI_SVD = ALLOCATED (YD%SPTNDSI_SVD)
WRITE (KLUN) LSPTNDSI_SVD
IF (LSPTNDSI_SVD) THEN
  WRITE (KLUN) LBOUND (YD%SPTNDSI_SVD)
  WRITE (KLUN) UBOUND (YD%SPTNDSI_SVD)
  WRITE (KLUN) YD%SPTNDSI_SVD
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TSPDDH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LSPTNDHD_DIV, LSPTNDHD_GFL, LSPTNDHD_SNHX, LSPTNDHD_SPD, LSPTNDHD_SVD, LSPTNDHD_T, LSPTNDHD_VOR, LSPTNDSI_DIV, LSPTNDSI_SPD, LSPTNDSI_SVD
LOGICAL :: LSPTNDSI_T, LSPTNDSI_VOR

READ (KLUN) LSPTNDHD_VOR
IF (LSPTNDHD_VOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDHD_VOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDHD_VOR
ENDIF
READ (KLUN) LSPTNDHD_DIV
IF (LSPTNDHD_DIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDHD_DIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDHD_DIV
ENDIF
READ (KLUN) LSPTNDHD_T
IF (LSPTNDHD_T) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDHD_T (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDHD_T
ENDIF
READ (KLUN) LSPTNDHD_SPD
IF (LSPTNDHD_SPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDHD_SPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDHD_SPD
ENDIF
READ (KLUN) LSPTNDHD_SVD
IF (LSPTNDHD_SVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDHD_SVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDHD_SVD
ENDIF
READ (KLUN) LSPTNDHD_SNHX
IF (LSPTNDHD_SNHX) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDHD_SNHX (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDHD_SNHX
ENDIF
READ (KLUN) LSPTNDHD_GFL
IF (LSPTNDHD_GFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SPTNDHD_GFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SPTNDHD_GFL
ENDIF
READ (KLUN) LSPTNDSI_VOR
IF (LSPTNDSI_VOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDSI_VOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDSI_VOR
ENDIF
READ (KLUN) LSPTNDSI_DIV
IF (LSPTNDSI_DIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDSI_DIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDSI_DIV
ENDIF
READ (KLUN) LSPTNDSI_T
IF (LSPTNDSI_T) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDSI_T (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDSI_T
ENDIF
READ (KLUN) LSPTNDSI_SPD
IF (LSPTNDSI_SPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDSI_SPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDSI_SPD
ENDIF
READ (KLUN) LSPTNDSI_SVD
IF (LSPTNDSI_SVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTNDSI_SVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTNDSI_SVD
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TSPDDH (YD, LDCREATED)
IMPLICIT NONE
TYPE (TSPDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LSPTNDHD_DIV, LSPTNDHD_GFL, LSPTNDHD_SNHX, LSPTNDHD_SPD, LSPTNDHD_SVD, LSPTNDHD_T, LSPTNDHD_VOR, LSPTNDSI_DIV, LSPTNDSI_SPD, LSPTNDSI_SVD
LOGICAL :: LSPTNDSI_T, LSPTNDSI_VOR

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LSPTNDHD_VOR = ALLOCATED (YD%SPTNDHD_VOR)
IF (LSPTNDHD_VOR) THEN
  !$acc enter data create (YD%SPTNDHD_VOR)
  !$acc update device (YD%SPTNDHD_VOR)
  !$acc enter data attach (YD%SPTNDHD_VOR)
ENDIF

LSPTNDHD_DIV = ALLOCATED (YD%SPTNDHD_DIV)
IF (LSPTNDHD_DIV) THEN
  !$acc enter data create (YD%SPTNDHD_DIV)
  !$acc update device (YD%SPTNDHD_DIV)
  !$acc enter data attach (YD%SPTNDHD_DIV)
ENDIF

LSPTNDHD_T = ALLOCATED (YD%SPTNDHD_T)
IF (LSPTNDHD_T) THEN
  !$acc enter data create (YD%SPTNDHD_T)
  !$acc update device (YD%SPTNDHD_T)
  !$acc enter data attach (YD%SPTNDHD_T)
ENDIF

LSPTNDHD_SPD = ALLOCATED (YD%SPTNDHD_SPD)
IF (LSPTNDHD_SPD) THEN
  !$acc enter data create (YD%SPTNDHD_SPD)
  !$acc update device (YD%SPTNDHD_SPD)
  !$acc enter data attach (YD%SPTNDHD_SPD)
ENDIF

LSPTNDHD_SVD = ALLOCATED (YD%SPTNDHD_SVD)
IF (LSPTNDHD_SVD) THEN
  !$acc enter data create (YD%SPTNDHD_SVD)
  !$acc update device (YD%SPTNDHD_SVD)
  !$acc enter data attach (YD%SPTNDHD_SVD)
ENDIF

LSPTNDHD_SNHX = ALLOCATED (YD%SPTNDHD_SNHX)
IF (LSPTNDHD_SNHX) THEN
  !$acc enter data create (YD%SPTNDHD_SNHX)
  !$acc update device (YD%SPTNDHD_SNHX)
  !$acc enter data attach (YD%SPTNDHD_SNHX)
ENDIF

LSPTNDHD_GFL = ALLOCATED (YD%SPTNDHD_GFL)
IF (LSPTNDHD_GFL) THEN
  !$acc enter data create (YD%SPTNDHD_GFL)
  !$acc update device (YD%SPTNDHD_GFL)
  !$acc enter data attach (YD%SPTNDHD_GFL)
ENDIF

LSPTNDSI_VOR = ALLOCATED (YD%SPTNDSI_VOR)
IF (LSPTNDSI_VOR) THEN
  !$acc enter data create (YD%SPTNDSI_VOR)
  !$acc update device (YD%SPTNDSI_VOR)
  !$acc enter data attach (YD%SPTNDSI_VOR)
ENDIF

LSPTNDSI_DIV = ALLOCATED (YD%SPTNDSI_DIV)
IF (LSPTNDSI_DIV) THEN
  !$acc enter data create (YD%SPTNDSI_DIV)
  !$acc update device (YD%SPTNDSI_DIV)
  !$acc enter data attach (YD%SPTNDSI_DIV)
ENDIF

LSPTNDSI_T = ALLOCATED (YD%SPTNDSI_T)
IF (LSPTNDSI_T) THEN
  !$acc enter data create (YD%SPTNDSI_T)
  !$acc update device (YD%SPTNDSI_T)
  !$acc enter data attach (YD%SPTNDSI_T)
ENDIF

LSPTNDSI_SPD = ALLOCATED (YD%SPTNDSI_SPD)
IF (LSPTNDSI_SPD) THEN
  !$acc enter data create (YD%SPTNDSI_SPD)
  !$acc update device (YD%SPTNDSI_SPD)
  !$acc enter data attach (YD%SPTNDSI_SPD)
ENDIF

LSPTNDSI_SVD = ALLOCATED (YD%SPTNDSI_SVD)
IF (LSPTNDSI_SVD) THEN
  !$acc enter data create (YD%SPTNDSI_SVD)
  !$acc update device (YD%SPTNDSI_SVD)
  !$acc enter data attach (YD%SPTNDSI_SVD)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TSPDDH (YD, LDDELETED)
IMPLICIT NONE
TYPE (TSPDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LSPTNDHD_DIV, LSPTNDHD_GFL, LSPTNDHD_SNHX, LSPTNDHD_SPD, LSPTNDHD_SVD, LSPTNDHD_T, LSPTNDHD_VOR, LSPTNDSI_DIV, LSPTNDSI_SPD, LSPTNDSI_SVD
LOGICAL :: LSPTNDSI_T, LSPTNDSI_VOR

LSPTNDHD_VOR = ALLOCATED (YD%SPTNDHD_VOR)
IF (LSPTNDHD_VOR) THEN
  !$acc exit data detach (YD%SPTNDHD_VOR)
  !$acc exit data delete (YD%SPTNDHD_VOR)
ENDIF

LSPTNDHD_DIV = ALLOCATED (YD%SPTNDHD_DIV)
IF (LSPTNDHD_DIV) THEN
  !$acc exit data detach (YD%SPTNDHD_DIV)
  !$acc exit data delete (YD%SPTNDHD_DIV)
ENDIF

LSPTNDHD_T = ALLOCATED (YD%SPTNDHD_T)
IF (LSPTNDHD_T) THEN
  !$acc exit data detach (YD%SPTNDHD_T)
  !$acc exit data delete (YD%SPTNDHD_T)
ENDIF

LSPTNDHD_SPD = ALLOCATED (YD%SPTNDHD_SPD)
IF (LSPTNDHD_SPD) THEN
  !$acc exit data detach (YD%SPTNDHD_SPD)
  !$acc exit data delete (YD%SPTNDHD_SPD)
ENDIF

LSPTNDHD_SVD = ALLOCATED (YD%SPTNDHD_SVD)
IF (LSPTNDHD_SVD) THEN
  !$acc exit data detach (YD%SPTNDHD_SVD)
  !$acc exit data delete (YD%SPTNDHD_SVD)
ENDIF

LSPTNDHD_SNHX = ALLOCATED (YD%SPTNDHD_SNHX)
IF (LSPTNDHD_SNHX) THEN
  !$acc exit data detach (YD%SPTNDHD_SNHX)
  !$acc exit data delete (YD%SPTNDHD_SNHX)
ENDIF

LSPTNDHD_GFL = ALLOCATED (YD%SPTNDHD_GFL)
IF (LSPTNDHD_GFL) THEN
  !$acc exit data detach (YD%SPTNDHD_GFL)
  !$acc exit data delete (YD%SPTNDHD_GFL)
ENDIF

LSPTNDSI_VOR = ALLOCATED (YD%SPTNDSI_VOR)
IF (LSPTNDSI_VOR) THEN
  !$acc exit data detach (YD%SPTNDSI_VOR)
  !$acc exit data delete (YD%SPTNDSI_VOR)
ENDIF

LSPTNDSI_DIV = ALLOCATED (YD%SPTNDSI_DIV)
IF (LSPTNDSI_DIV) THEN
  !$acc exit data detach (YD%SPTNDSI_DIV)
  !$acc exit data delete (YD%SPTNDSI_DIV)
ENDIF

LSPTNDSI_T = ALLOCATED (YD%SPTNDSI_T)
IF (LSPTNDSI_T) THEN
  !$acc exit data detach (YD%SPTNDSI_T)
  !$acc exit data delete (YD%SPTNDSI_T)
ENDIF

LSPTNDSI_SPD = ALLOCATED (YD%SPTNDSI_SPD)
IF (LSPTNDSI_SPD) THEN
  !$acc exit data detach (YD%SPTNDSI_SPD)
  !$acc exit data delete (YD%SPTNDSI_SPD)
ENDIF

LSPTNDSI_SVD = ALLOCATED (YD%SPTNDSI_SVD)
IF (LSPTNDSI_SVD) THEN
  !$acc exit data detach (YD%SPTNDSI_SVD)
  !$acc exit data delete (YD%SPTNDSI_SVD)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
