MODULE UTIL_TVERTICAL_GEOM_MOD

USE YOMVERT, ONLY : TVERTICAL_GEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVERTICAL_GEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVERTICAL_GEOM
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TVERTICAL_GEOM (KLUN, YD)
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRVAB)
CALL SAVE (KLUN, YD%YRVETA)
CALL SAVE (KLUN, YD%YRVFE)
END SUBROUTINE

SUBROUTINE LOAD_TVERTICAL_GEOM (KLUN, YD)
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVERTICAL_GEOM), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRVAB)
CALL LOAD (KLUN, YD%YRVETA)
CALL LOAD (KLUN, YD%YRVFE)
END SUBROUTINE






END MODULE
