MODULE UTIL_TYPE_AERO_DESC_MOD

USE YOEAERATM, ONLY : TYPE_AERO_DESC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_AERO_DESC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_AERO_DESC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_AERO_DESC
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_AERO_DESC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_AERO_DESC), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%CNAME
WRITE (KLUN) YD%IGRBCODE
WRITE (KLUN) YD%NTYP
WRITE (KLUN) YD%NBIN
WRITE (KLUN) YD%IGRIBDIAG
WRITE (KLUN) YD%RDDEPVSEA
WRITE (KLUN) YD%RDDEPVLIC
WRITE (KLUN) YD%RSEDIMV
WRITE (KLUN) YD%RSCAVIN
WRITE (KLUN) YD%RSCAVBCR
WRITE (KLUN) YD%RSCAVBCS
WRITE (KLUN) YD%COPTCLASS
WRITE (KLUN) YD%CHYGCLASS
WRITE (KLUN) YD%IAEROCV
END SUBROUTINE

SUBROUTINE LOAD_TYPE_AERO_DESC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_AERO_DESC), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%CNAME
READ (KLUN) YD%IGRBCODE
READ (KLUN) YD%NTYP
READ (KLUN) YD%NBIN
READ (KLUN) YD%IGRIBDIAG
READ (KLUN) YD%RDDEPVSEA
READ (KLUN) YD%RDDEPVLIC
READ (KLUN) YD%RSEDIMV
READ (KLUN) YD%RSCAVIN
READ (KLUN) YD%RSCAVBCR
READ (KLUN) YD%RSCAVBCS
READ (KLUN) YD%COPTCLASS
READ (KLUN) YD%CHYGCLASS
READ (KLUN) YD%IAEROCV
END SUBROUTINE


SUBROUTINE COPY_TYPE_AERO_DESC (YD, LDCREATED)

IMPLICIT NONE
TYPE (TYPE_AERO_DESC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF














END SUBROUTINE



END MODULE
