MODULE UTIL_TEGEO_MOD

USE YEMGEO, ONLY : TEGEO

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGEO
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGEO
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEGEO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGEO), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%ERPK
WRITE (KLUN) YD%ELON1
WRITE (KLUN) YD%ELAT1
WRITE (KLUN) YD%ELON2
WRITE (KLUN) YD%ELAT2
WRITE (KLUN) YD%ELON0
WRITE (KLUN) YD%ELAT0
WRITE (KLUN) YD%ELONC
WRITE (KLUN) YD%ELATC
WRITE (KLUN) YD%EDELX
WRITE (KLUN) YD%EDELY
WRITE (KLUN) YD%ELX
WRITE (KLUN) YD%ELY
WRITE (KLUN) YD%EXWN
WRITE (KLUN) YD%EYWN
WRITE (KLUN) YD%RCORI_ACAD
WRITE (KLUN) YD%RLAT_ACAD
WRITE (KLUN) YD%RLON_ACAD
WRITE (KLUN) YD%LMAP
WRITE (KLUN) YD%LMRT
WRITE (KLUN) YD%LREDEL_IN_METRES
END SUBROUTINE
SUBROUTINE LOAD_TEGEO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGEO), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%ERPK
READ (KLUN) YD%ELON1
READ (KLUN) YD%ELAT1
READ (KLUN) YD%ELON2
READ (KLUN) YD%ELAT2
READ (KLUN) YD%ELON0
READ (KLUN) YD%ELAT0
READ (KLUN) YD%ELONC
READ (KLUN) YD%ELATC
READ (KLUN) YD%EDELX
READ (KLUN) YD%EDELY
READ (KLUN) YD%ELX
READ (KLUN) YD%ELY
READ (KLUN) YD%EXWN
READ (KLUN) YD%EYWN
READ (KLUN) YD%RCORI_ACAD
READ (KLUN) YD%RLAT_ACAD
READ (KLUN) YD%RLON_ACAD
READ (KLUN) YD%LMAP
READ (KLUN) YD%LMRT
READ (KLUN) YD%LREDEL_IN_METRES
END SUBROUTINE




END MODULE
