MODULE UTIL_TERDI_MOD

USE YOERDI, ONLY : TERDI

INTERFACE SAVE
MODULE PROCEDURE SAVE_TERDI
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TERDI
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TERDI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TERDI), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RRAE
WRITE (KLUN) YD%RSUNDUR
WRITE (KLUN) YD%RCARDI
WRITE (KLUN) YD%RCH4
WRITE (KLUN) YD%RN2O
WRITE (KLUN) YD%RNO2
WRITE (KLUN) YD%RO3
WRITE (KLUN) YD%RCCL4
WRITE (KLUN) YD%RCFC11
WRITE (KLUN) YD%RCFC12
WRITE (KLUN) YD%RCFC22
WRITE (KLUN) YD%REPCLC
WRITE (KLUN) YD%REPH2O
WRITE (KLUN) YD%RCCO2
WRITE (KLUN) YD%RCCH4
WRITE (KLUN) YD%RCN2O
WRITE (KLUN) YD%RCNO2
WRITE (KLUN) YD%RCCFC11
WRITE (KLUN) YD%RCCFC12
WRITE (KLUN) YD%RCCFC22
WRITE (KLUN) YD%RCCCL4
WRITE (KLUN) YD%RSOLINC
END SUBROUTINE
SUBROUTINE LOAD_TERDI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TERDI), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RRAE
READ (KLUN) YD%RSUNDUR
READ (KLUN) YD%RCARDI
READ (KLUN) YD%RCH4
READ (KLUN) YD%RN2O
READ (KLUN) YD%RNO2
READ (KLUN) YD%RO3
READ (KLUN) YD%RCCL4
READ (KLUN) YD%RCFC11
READ (KLUN) YD%RCFC12
READ (KLUN) YD%RCFC22
READ (KLUN) YD%REPCLC
READ (KLUN) YD%REPH2O
READ (KLUN) YD%RCCO2
READ (KLUN) YD%RCCH4
READ (KLUN) YD%RCN2O
READ (KLUN) YD%RCNO2
READ (KLUN) YD%RCCFC11
READ (KLUN) YD%RCCFC12
READ (KLUN) YD%RCCFC22
READ (KLUN) YD%RCCCL4
READ (KLUN) YD%RSOLINC
END SUBROUTINE




END MODULE
