MODULE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD

USE MODEL_PHYSICS_SIMPLINEAR_MOD, ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_SIMPLINEAR_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_SIMPLINEAR_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_SIMPLINEAR_TYPE (KLUN, YD)
USE UTIL_SPHYS_HIST_TYPE_MOD
USE UTIL_TCUMFS_MOD
USE UTIL_TECUMF2_MOD
USE UTIL_TEGWDWMS_MOD
USE UTIL_TEPHLI_MOD
USE UTIL_TNCL_MOD
USE UTIL_TPHLC_MOD
USE UTIL_TPHNC_MOD
USE UTIL_TSRFTLAD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LGPHIST
CALL SAVE (KLUN, YD%YREPHLI)
CALL SAVE (KLUN, YD%YRCUMFS)
CALL SAVE (KLUN, YD%YREGWDWMS)
CALL SAVE (KLUN, YD%YRECUMF2)
CALL SAVE (KLUN, YD%YRPHLC)
CALL SAVE (KLUN, YD%YRPHNC)
CALL SAVE (KLUN, YD%YRNCL)
CALL SAVE (KLUN, YD%YRSRFTLAD)
LGPHIST = ASSOCIATED (YD%GPHIST)
WRITE (KLUN) LGPHIST
IF (LGPHIST) THEN
  WRITE (KLUN) LBOUND (YD%GPHIST)
  WRITE (KLUN) UBOUND (YD%GPHIST)
  DO J1 = LBOUND (YD%GPHIST, 1), UBOUND (YD%GPHIST, 1)
    CALL SAVE (KLUN, YD%GPHIST (J1))
  ENDDO
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_MODEL_PHYSICS_SIMPLINEAR_TYPE (KLUN, YD)
USE UTIL_SPHYS_HIST_TYPE_MOD
USE UTIL_TCUMFS_MOD
USE UTIL_TECUMF2_MOD
USE UTIL_TEGWDWMS_MOD
USE UTIL_TEPHLI_MOD
USE UTIL_TNCL_MOD
USE UTIL_TPHLC_MOD
USE UTIL_TPHNC_MOD
USE UTIL_TSRFTLAD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LGPHIST
CALL LOAD (KLUN, YD%YREPHLI)
CALL LOAD (KLUN, YD%YRCUMFS)
CALL LOAD (KLUN, YD%YREGWDWMS)
CALL LOAD (KLUN, YD%YRECUMF2)
CALL LOAD (KLUN, YD%YRPHLC)
CALL LOAD (KLUN, YD%YRPHNC)
CALL LOAD (KLUN, YD%YRNCL)
CALL LOAD (KLUN, YD%YRSRFTLAD)
READ (KLUN) LGPHIST
IF (LGPHIST) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GPHIST (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%GPHIST, 1), UBOUND (YD%GPHIST, 1)
    CALL LOAD (KLUN, YD%GPHIST (J1))
  ENDDO
ELSE
  NULLIFY (YD%GPHIST)
ENDIF
END SUBROUTINE




END MODULE
