MODULE UTIL_TACVGRIB_MOD

USE TYPE_ACV, ONLY : TACVGRIB

INTERFACE SAVE
MODULE PROCEDURE SAVE_TACVGRIB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TACVGRIB
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TACVGRIB
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TACVGRIB
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TACVGRIB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACVGRIB), INTENT (IN), TARGET :: YD
LOGICAL :: LMACVGRB_1D, LMACVGRB_2D, LMACVGRB_3D, LMACVGRB_ALL
LMACVGRB_1D = ALLOCATED (YD%MACVGRB_1D)
WRITE (KLUN) LMACVGRB_1D
IF (LMACVGRB_1D) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_1D)
  WRITE (KLUN) UBOUND (YD%MACVGRB_1D)
  WRITE (KLUN) YD%MACVGRB_1D
ENDIF
LMACVGRB_2D = ALLOCATED (YD%MACVGRB_2D)
WRITE (KLUN) LMACVGRB_2D
IF (LMACVGRB_2D) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_2D)
  WRITE (KLUN) UBOUND (YD%MACVGRB_2D)
  WRITE (KLUN) YD%MACVGRB_2D
ENDIF
LMACVGRB_3D = ALLOCATED (YD%MACVGRB_3D)
WRITE (KLUN) LMACVGRB_3D
IF (LMACVGRB_3D) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_3D)
  WRITE (KLUN) UBOUND (YD%MACVGRB_3D)
  WRITE (KLUN) YD%MACVGRB_3D
ENDIF
LMACVGRB_ALL = ALLOCATED (YD%MACVGRB_ALL)
WRITE (KLUN) LMACVGRB_ALL
IF (LMACVGRB_ALL) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_ALL)
  WRITE (KLUN) UBOUND (YD%MACVGRB_ALL)
  WRITE (KLUN) YD%MACVGRB_ALL
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TACVGRIB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACVGRIB), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMACVGRB_1D, LMACVGRB_2D, LMACVGRB_3D, LMACVGRB_ALL
READ (KLUN) LMACVGRB_1D
IF (LMACVGRB_1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_1D (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_1D
ENDIF
READ (KLUN) LMACVGRB_2D
IF (LMACVGRB_2D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_2D (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_2D
ENDIF
READ (KLUN) LMACVGRB_3D
IF (LMACVGRB_3D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_3D (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_3D
ENDIF
READ (KLUN) LMACVGRB_ALL
IF (LMACVGRB_ALL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_ALL (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_ALL
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TACVGRIB (YD, LDCREATED)

IMPLICIT NONE
TYPE (TACVGRIB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LMACVGRB_1D, LMACVGRB_2D, LMACVGRB_3D, LMACVGRB_ALL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LMACVGRB_1D = ALLOCATED (YD%MACVGRB_1D)
IF (LMACVGRB_1D) THEN
  !$acc enter data create (YD%MACVGRB_1D)
  !$acc update device (YD%MACVGRB_1D)
  !$acc enter data attach (YD%MACVGRB_1D)
ENDIF

LMACVGRB_2D = ALLOCATED (YD%MACVGRB_2D)
IF (LMACVGRB_2D) THEN
  !$acc enter data create (YD%MACVGRB_2D)
  !$acc update device (YD%MACVGRB_2D)
  !$acc enter data attach (YD%MACVGRB_2D)
ENDIF

LMACVGRB_3D = ALLOCATED (YD%MACVGRB_3D)
IF (LMACVGRB_3D) THEN
  !$acc enter data create (YD%MACVGRB_3D)
  !$acc update device (YD%MACVGRB_3D)
  !$acc enter data attach (YD%MACVGRB_3D)
ENDIF

LMACVGRB_ALL = ALLOCATED (YD%MACVGRB_ALL)
IF (LMACVGRB_ALL) THEN
  !$acc enter data create (YD%MACVGRB_ALL)
  !$acc update device (YD%MACVGRB_ALL)
  !$acc enter data attach (YD%MACVGRB_ALL)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TACVGRIB (YD, LDDELETED)

IMPLICIT NONE
TYPE (TACVGRIB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LMACVGRB_1D, LMACVGRB_2D, LMACVGRB_3D, LMACVGRB_ALL

LMACVGRB_1D = ALLOCATED (YD%MACVGRB_1D)
IF (LMACVGRB_1D) THEN
  !$acc exit data detach (YD%MACVGRB_1D)
  !$acc exit data delete (YD%MACVGRB_1D)
ENDIF

LMACVGRB_2D = ALLOCATED (YD%MACVGRB_2D)
IF (LMACVGRB_2D) THEN
  !$acc exit data detach (YD%MACVGRB_2D)
  !$acc exit data delete (YD%MACVGRB_2D)
ENDIF

LMACVGRB_3D = ALLOCATED (YD%MACVGRB_3D)
IF (LMACVGRB_3D) THEN
  !$acc exit data detach (YD%MACVGRB_3D)
  !$acc exit data delete (YD%MACVGRB_3D)
ENDIF

LMACVGRB_ALL = ALLOCATED (YD%MACVGRB_ALL)
IF (LMACVGRB_ALL) THEN
  !$acc exit data detach (YD%MACVGRB_ALL)
  !$acc exit data delete (YD%MACVGRB_ALL)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
