MODULE UTIL_TPADDH_MOD

USE YOMPADDH, ONLY : TPADDH


INTERFACE SAVE
MODULE PROCEDURE SAVE_TPADDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPADDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPADDH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPADDH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TPADDH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPADDH), INTENT (IN), TARGET :: YD
LOGICAL :: LNGLALIST, LNGPUMASK

LNGLALIST = ALLOCATED (YD%NGLALIST)
WRITE (KLUN) LNGLALIST
IF (LNGLALIST) THEN
  WRITE (KLUN) LBOUND (YD%NGLALIST)
  WRITE (KLUN) UBOUND (YD%NGLALIST)
  WRITE (KLUN) YD%NGLALIST
ENDIF
LNGPUMASK = ALLOCATED (YD%NGPUMASK)
WRITE (KLUN) LNGPUMASK
IF (LNGPUMASK) THEN
  WRITE (KLUN) LBOUND (YD%NGPUMASK)
  WRITE (KLUN) UBOUND (YD%NGPUMASK)
  WRITE (KLUN) YD%NGPUMASK
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TPADDH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPADDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LNGLALIST, LNGPUMASK

READ (KLUN) LNGLALIST
IF (LNGLALIST) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGLALIST (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGLALIST
ENDIF
READ (KLUN) LNGPUMASK
IF (LNGPUMASK) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGPUMASK (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGPUMASK
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TPADDH (YD, LDCREATED)
IMPLICIT NONE
CLASS (TPADDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LNGLALIST, LNGPUMASK

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LNGLALIST = ALLOCATED (YD%NGLALIST)
IF (LNGLALIST) THEN
  !$acc enter data create (YD%NGLALIST)
  !$acc update device (YD%NGLALIST)
  !$acc enter data attach (YD%NGLALIST)
ENDIF

LNGPUMASK = ALLOCATED (YD%NGPUMASK)
IF (LNGPUMASK) THEN
  !$acc enter data create (YD%NGPUMASK)
  !$acc update device (YD%NGPUMASK)
  !$acc enter data attach (YD%NGPUMASK)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TPADDH (YD, LDDELETED)
IMPLICIT NONE
CLASS (TPADDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LNGLALIST, LNGPUMASK

LNGLALIST = ALLOCATED (YD%NGLALIST)
IF (LNGLALIST) THEN
  !$acc exit data detach (YD%NGLALIST)
  !$acc exit data delete (YD%NGLALIST)
ENDIF

LNGPUMASK = ALLOCATED (YD%NGPUMASK)
IF (LNGPUMASK) THEN
  !$acc exit data detach (YD%NGPUMASK)
  !$acc exit data delete (YD%NGPUMASK)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
