MODULE UTIL_TEAERMAP_MOD

USE YOEAERMAP, ONLY : TEAERMAP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERMAP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERMAP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERMAP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEAERMAP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEAERMAP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERMAP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NDUSRCP
WRITE (KLUN) YD%RDDUAER
WRITE (KLUN) YD%RDUSRCP
END SUBROUTINE

SUBROUTINE LOAD_TEAERMAP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERMAP), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NDUSRCP
READ (KLUN) YD%RDDUAER
READ (KLUN) YD%RDUSRCP
END SUBROUTINE


SUBROUTINE COPY_TEAERMAP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEAERMAP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF



END SUBROUTINE

SUBROUTINE WIPE_TEAERMAP (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEAERMAP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED




LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
