MODULE UTIL_TYPE_SURF_GEN_MOD

USE SURFACE_FIELDS_MIX, ONLY : TYPE_SURF_GEN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_SURF_GEN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_SURF_GEN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_SURF_GEN
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TYPE_SURF_GEN
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_SURF_GEN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_SURF_GEN), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NUMFLDS
WRITE (KLUN) YD%NDIM
WRITE (KLUN) YD%NLEVS
WRITE (KLUN) YD%IPTR
WRITE (KLUN) YD%IPTR5
WRITE (KLUN) YD%NDIM5
WRITE (KLUN) YD%NOFFTRAJ
WRITE (KLUN) YD%NOFFTRAJ_CST
WRITE (KLUN) YD%CGRPNAME
WRITE (KLUN) YD%L3D
WRITE (KLUN) YD%LMTL
WRITE (KLUN) YD%FINALISED
END SUBROUTINE

SUBROUTINE LOAD_TYPE_SURF_GEN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_SURF_GEN), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NUMFLDS
READ (KLUN) YD%NDIM
READ (KLUN) YD%NLEVS
READ (KLUN) YD%IPTR
READ (KLUN) YD%IPTR5
READ (KLUN) YD%NDIM5
READ (KLUN) YD%NOFFTRAJ
READ (KLUN) YD%NOFFTRAJ_CST
READ (KLUN) YD%CGRPNAME
READ (KLUN) YD%L3D
READ (KLUN) YD%LMTL
READ (KLUN) YD%FINALISED
END SUBROUTINE


SUBROUTINE COPY_TYPE_SURF_GEN (YD, LDCREATED)

IMPLICIT NONE
TYPE (TYPE_SURF_GEN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF












END SUBROUTINE

SUBROUTINE WIPE_TYPE_SURF_GEN (YD, LDDELETED)

IMPLICIT NONE
TYPE (TYPE_SURF_GEN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED













LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
