MODULE UTIL_TSPECTRALPLANCK_MOD

USE YOE_SPECTRAL_PLANCK, ONLY : TSPECTRALPLANCK


INTERFACE SAVE
MODULE PROCEDURE SAVE_TSPECTRALPLANCK
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSPECTRALPLANCK
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSPECTRALPLANCK
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSPECTRALPLANCK
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSPECTRALPLANCK (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPECTRALPLANCK), INTENT (IN), TARGET :: YD
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND

WRITE (KLUN) YD%NINTERVALS
WRITE (KLUN) YD%NTEMPS
WRITE (KLUN) YD%TEMP1
WRITE (KLUN) YD%DTEMP
LPLANCK_LUT = ALLOCATED (YD%PLANCK_LUT)
WRITE (KLUN) LPLANCK_LUT
IF (LPLANCK_LUT) THEN
  WRITE (KLUN) LBOUND (YD%PLANCK_LUT)
  WRITE (KLUN) UBOUND (YD%PLANCK_LUT)
  WRITE (KLUN) YD%PLANCK_LUT
ENDIF
LWAVLEN_BOUND = ALLOCATED (YD%WAVLEN_BOUND)
WRITE (KLUN) LWAVLEN_BOUND
IF (LWAVLEN_BOUND) THEN
  WRITE (KLUN) LBOUND (YD%WAVLEN_BOUND)
  WRITE (KLUN) UBOUND (YD%WAVLEN_BOUND)
  WRITE (KLUN) YD%WAVLEN_BOUND
ENDIF
LINTERVAL_MAP = ALLOCATED (YD%INTERVAL_MAP)
WRITE (KLUN) LINTERVAL_MAP
IF (LINTERVAL_MAP) THEN
  WRITE (KLUN) LBOUND (YD%INTERVAL_MAP)
  WRITE (KLUN) UBOUND (YD%INTERVAL_MAP)
  WRITE (KLUN) YD%INTERVAL_MAP
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TSPECTRALPLANCK (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPECTRALPLANCK), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND

READ (KLUN) YD%NINTERVALS
READ (KLUN) YD%NTEMPS
READ (KLUN) YD%TEMP1
READ (KLUN) YD%DTEMP
READ (KLUN) LPLANCK_LUT
IF (LPLANCK_LUT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%PLANCK_LUT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%PLANCK_LUT
ENDIF
READ (KLUN) LWAVLEN_BOUND
IF (LWAVLEN_BOUND) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%WAVLEN_BOUND (IL1(1):IU1(1)))
  READ (KLUN) YD%WAVLEN_BOUND
ENDIF
READ (KLUN) LINTERVAL_MAP
IF (LINTERVAL_MAP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%INTERVAL_MAP (IL1(1):IU1(1)))
  READ (KLUN) YD%INTERVAL_MAP
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TSPECTRALPLANCK (YD, LDCREATED)
IMPLICIT NONE
TYPE (TSPECTRALPLANCK), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




LPLANCK_LUT = ALLOCATED (YD%PLANCK_LUT)
IF (LPLANCK_LUT) THEN
  !$acc enter data create (YD%PLANCK_LUT)
  !$acc update device (YD%PLANCK_LUT)
  !$acc enter data attach (YD%PLANCK_LUT)
ENDIF

LWAVLEN_BOUND = ALLOCATED (YD%WAVLEN_BOUND)
IF (LWAVLEN_BOUND) THEN
  !$acc enter data create (YD%WAVLEN_BOUND)
  !$acc update device (YD%WAVLEN_BOUND)
  !$acc enter data attach (YD%WAVLEN_BOUND)
ENDIF

LINTERVAL_MAP = ALLOCATED (YD%INTERVAL_MAP)
IF (LINTERVAL_MAP) THEN
  !$acc enter data create (YD%INTERVAL_MAP)
  !$acc update device (YD%INTERVAL_MAP)
  !$acc enter data attach (YD%INTERVAL_MAP)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TSPECTRALPLANCK (YD, LDDELETED)
IMPLICIT NONE
TYPE (TSPECTRALPLANCK), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND





LPLANCK_LUT = ALLOCATED (YD%PLANCK_LUT)
IF (LPLANCK_LUT) THEN
  !$acc exit data detach (YD%PLANCK_LUT)
  !$acc exit data delete (YD%PLANCK_LUT)
ENDIF

LWAVLEN_BOUND = ALLOCATED (YD%WAVLEN_BOUND)
IF (LWAVLEN_BOUND) THEN
  !$acc exit data detach (YD%WAVLEN_BOUND)
  !$acc exit data delete (YD%WAVLEN_BOUND)
ENDIF

LINTERVAL_MAP = ALLOCATED (YD%INTERVAL_MAP)
IF (LINTERVAL_MAP) THEN
  !$acc exit data detach (YD%INTERVAL_MAP)
  !$acc exit data delete (YD%INTERVAL_MAP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
