MODULE UTIL_TEPHY_MOD

USE YOEPHY, ONLY : TEPHY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEPHY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEPHY
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEPHY), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LEPHYS
WRITE (KLUN) YD%LECOND
WRITE (KLUN) YD%LECUMF
WRITE (KLUN) YD%LEDCLD
WRITE (KLUN) YD%LEEVAP
WRITE (KLUN) YD%LEGWDG
WRITE (KLUN) YD%LEGWWMS
WRITE (KLUN) YD%LEOZOC
WRITE (KLUN) YD%LEQNGT
WRITE (KLUN) YD%LERADI
WRITE (KLUN) YD%LERADS
WRITE (KLUN) YD%LESICE
WRITE (KLUN) YD%LESURF
WRITE (KLUN) YD%LEVDIF
WRITE (KLUN) YD%LAGPHY
WRITE (KLUN) YD%LEPCLD
WRITE (KLUN) YD%LEO3CH
WRITE (KLUN) YD%LO3CH_SAFE
WRITE (KLUN) YD%LO3CH_OLDVER
WRITE (KLUN) YD%LO3CH_BMS
WRITE (KLUN) YD%LO3CH_HLO
WRITE (KLUN) YD%CO3CHEM
WRITE (KLUN) YD%LECO2DIU
WRITE (KLUN) YD%LNEEONLINE
WRITE (KLUN) YD%LBUD23
WRITE (KLUN) YD%LPPTILES
WRITE (KLUN) YD%LBUDCYCLE
WRITE (KLUN) YD%LEMETHOX
WRITE (KLUN) YD%LECURR
WRITE (KLUN) YD%LESURFTRAJ
WRITE (KLUN) YD%LVDFTRAC
WRITE (KLUN) YD%LMFTRAC
WRITE (KLUN) YD%LMFSCAV
WRITE (KLUN) YD%LERAIN
WRITE (KLUN) YD%LEMWAVE
WRITE (KLUN) YD%LEGBRAD
WRITE (KLUN) YD%LERAINGG
WRITE (KLUN) YD%LESMOS
WRITE (KLUN) YD%LEOCWA
WRITE (KLUN) YD%LEOCCO
WRITE (KLUN) YD%LEOCSA
WRITE (KLUN) YD%LEOCLA
WRITE (KLUN) YD%LEVGEN
WRITE (KLUN) YD%LESSRO
WRITE (KLUN) YD%LEFLAKE
WRITE (KLUN) YD%LEOCML
WRITE (KLUN) YD%LEOBC
WRITE (KLUN) YD%LEOBCMAX
WRITE (KLUN) YD%REOBCMAX
WRITE (KLUN) YD%LEOBCICE
WRITE (KLUN) YD%LEOCLAKE
WRITE (KLUN) YD%LEOLAKESST
WRITE (KLUN) YD%LOCMLTKE
WRITE (KLUN) YD%LECLIPQT0
WRITE (KLUN) YD%LECLIPCLDT0
WRITE (KLUN) YD%LDUCTDIA
WRITE (KLUN) YD%LDIAGTURB_EC
WRITE (KLUN) YD%LSLPHY
WRITE (KLUN) YD%LESN09
WRITE (KLUN) YD%LELAIV
WRITE (KLUN) YD%LECTESSEL
WRITE (KLUN) YD%LEAGS
WRITE (KLUN) YD%LSPCRM
WRITE (KLUN) YD%LELIGHT
WRITE (KLUN) YD%RTHRFRTI
WRITE (KLUN) YD%RCIMIN
WRITE (KLUN) YD%RLAIINT
WRITE (KLUN) YD%NPRACCL
WRITE (KLUN) YD%NLIMODE
WRITE (KLUN) YD%LECLIM10D
WRITE (KLUN) YD%LESNML
WRITE (KLUN) YD%NSNMLWS
WRITE (KLUN) YD%LBFASCO2
WRITE (KLUN) YD%NCO2CLIMYY1
WRITE (KLUN) YD%NCO2CLIMYY2
WRITE (KLUN) YD%NCO2CLIMN1
WRITE (KLUN) YD%NCO2CLIMN2
WRITE (KLUN) YD%NCO2CLIMFRQ
WRITE (KLUN) YD%NALBEDOSCHEME
WRITE (KLUN) YD%NEMISSSCHEME
WRITE (KLUN) YD%RALFMINPSN
WRITE (KLUN) YD%RNORTHML
WRITE (KLUN) YD%RSOUTHML
WRITE (KLUN) YD%RWESTML
WRITE (KLUN) YD%REASTML
WRITE (KLUN) YD%INVML
WRITE (KLUN) YD%LFPOS_EC_PHYS
WRITE (KLUN) YD%LFPOS_ACC_RESET
WRITE (KLUN) YD%LRAD_CLOUD_INHOMOG
END SUBROUTINE
SUBROUTINE LOAD_TEPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEPHY), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LEPHYS
READ (KLUN) YD%LECOND
READ (KLUN) YD%LECUMF
READ (KLUN) YD%LEDCLD
READ (KLUN) YD%LEEVAP
READ (KLUN) YD%LEGWDG
READ (KLUN) YD%LEGWWMS
READ (KLUN) YD%LEOZOC
READ (KLUN) YD%LEQNGT
READ (KLUN) YD%LERADI
READ (KLUN) YD%LERADS
READ (KLUN) YD%LESICE
READ (KLUN) YD%LESURF
READ (KLUN) YD%LEVDIF
READ (KLUN) YD%LAGPHY
READ (KLUN) YD%LEPCLD
READ (KLUN) YD%LEO3CH
READ (KLUN) YD%LO3CH_SAFE
READ (KLUN) YD%LO3CH_OLDVER
READ (KLUN) YD%LO3CH_BMS
READ (KLUN) YD%LO3CH_HLO
READ (KLUN) YD%CO3CHEM
READ (KLUN) YD%LECO2DIU
READ (KLUN) YD%LNEEONLINE
READ (KLUN) YD%LBUD23
READ (KLUN) YD%LPPTILES
READ (KLUN) YD%LBUDCYCLE
READ (KLUN) YD%LEMETHOX
READ (KLUN) YD%LECURR
READ (KLUN) YD%LESURFTRAJ
READ (KLUN) YD%LVDFTRAC
READ (KLUN) YD%LMFTRAC
READ (KLUN) YD%LMFSCAV
READ (KLUN) YD%LERAIN
READ (KLUN) YD%LEMWAVE
READ (KLUN) YD%LEGBRAD
READ (KLUN) YD%LERAINGG
READ (KLUN) YD%LESMOS
READ (KLUN) YD%LEOCWA
READ (KLUN) YD%LEOCCO
READ (KLUN) YD%LEOCSA
READ (KLUN) YD%LEOCLA
READ (KLUN) YD%LEVGEN
READ (KLUN) YD%LESSRO
READ (KLUN) YD%LEFLAKE
READ (KLUN) YD%LEOCML
READ (KLUN) YD%LEOBC
READ (KLUN) YD%LEOBCMAX
READ (KLUN) YD%REOBCMAX
READ (KLUN) YD%LEOBCICE
READ (KLUN) YD%LEOCLAKE
READ (KLUN) YD%LEOLAKESST
READ (KLUN) YD%LOCMLTKE
READ (KLUN) YD%LECLIPQT0
READ (KLUN) YD%LECLIPCLDT0
READ (KLUN) YD%LDUCTDIA
READ (KLUN) YD%LDIAGTURB_EC
READ (KLUN) YD%LSLPHY
READ (KLUN) YD%LESN09
READ (KLUN) YD%LELAIV
READ (KLUN) YD%LECTESSEL
READ (KLUN) YD%LEAGS
READ (KLUN) YD%LSPCRM
READ (KLUN) YD%LELIGHT
READ (KLUN) YD%RTHRFRTI
READ (KLUN) YD%RCIMIN
READ (KLUN) YD%RLAIINT
READ (KLUN) YD%NPRACCL
READ (KLUN) YD%NLIMODE
READ (KLUN) YD%LECLIM10D
READ (KLUN) YD%LESNML
READ (KLUN) YD%NSNMLWS
READ (KLUN) YD%LBFASCO2
READ (KLUN) YD%NCO2CLIMYY1
READ (KLUN) YD%NCO2CLIMYY2
READ (KLUN) YD%NCO2CLIMN1
READ (KLUN) YD%NCO2CLIMN2
READ (KLUN) YD%NCO2CLIMFRQ
READ (KLUN) YD%NALBEDOSCHEME
READ (KLUN) YD%NEMISSSCHEME
READ (KLUN) YD%RALFMINPSN
READ (KLUN) YD%RNORTHML
READ (KLUN) YD%RSOUTHML
READ (KLUN) YD%RWESTML
READ (KLUN) YD%REASTML
READ (KLUN) YD%INVML
READ (KLUN) YD%LFPOS_EC_PHYS
READ (KLUN) YD%LFPOS_ACC_RESET
READ (KLUN) YD%LRAD_CLOUD_INHOMOG
END SUBROUTINE




END MODULE
