MODULE UTIL_TEMCICA_MOD

USE YOE_MCICA, ONLY : TEMCICA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEMCICA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEMCICA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEMCICA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEMCICA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEMCICA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEMCICA), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%XCW
WRITE (KLUN) YD%XCW_D
WRITE (KLUN) YD%NMCI1
WRITE (KLUN) YD%NMCI2
END SUBROUTINE

SUBROUTINE LOAD_TEMCICA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEMCICA), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%XCW
READ (KLUN) YD%XCW_D
READ (KLUN) YD%NMCI1
READ (KLUN) YD%NMCI2
END SUBROUTINE


SUBROUTINE COPY_TEMCICA (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEMCICA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




END SUBROUTINE

SUBROUTINE WIPE_TEMCICA (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEMCICA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED





LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
