MODULE UTIL_TVERTICAL_GEOM_MOD

USE YOMVERT, ONLY : TVERTICAL_GEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVERTICAL_GEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVERTICAL_GEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVERTICAL_GEOM
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVERTICAL_GEOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVERTICAL_GEOM (KLUN, YD)
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRVAB)
CALL SAVE (KLUN, YD%YRVETA)
CALL SAVE (KLUN, YD%YRVFE)
END SUBROUTINE

SUBROUTINE LOAD_TVERTICAL_GEOM (KLUN, YD)
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVERTICAL_GEOM), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRVAB)
CALL LOAD (KLUN, YD%YRVETA)
CALL LOAD (KLUN, YD%YRVFE)
END SUBROUTINE


SUBROUTINE COPY_TVERTICAL_GEOM (YD, LDCREATED)
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRVAB, LDCREATED=.TRUE.)

CALL COPY (YD%YRVETA, LDCREATED=.TRUE.)

CALL COPY (YD%YRVFE, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_TVERTICAL_GEOM (YD, LDDELETED)
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRVAB, LDDELETED=.TRUE.)

CALL WIPE (YD%YRVETA, LDDELETED=.TRUE.)

CALL WIPE (YD%YRVFE, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
