MODULE UTIL_TEMCICA_MOD

USE YOE_MCICA, ONLY : TEMCICA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEMCICA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEMCICA
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEMCICA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEMCICA), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%XCW
WRITE (KLUN) YD%XCW_D
WRITE (KLUN) YD%NMCI1
WRITE (KLUN) YD%NMCI2
END SUBROUTINE
SUBROUTINE LOAD_TEMCICA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEMCICA), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%XCW
READ (KLUN) YD%XCW_D
READ (KLUN) YD%NMCI1
READ (KLUN) YD%NMCI2
END SUBROUTINE




END MODULE
