MODULE UTIL_TPHY2_MOD

USE YOMPHY2, ONLY : TPHY2


INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHY2
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY2
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHY2
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPHY2
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TPHY2 (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPHY2), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NTSHM
WRITE (KLUN) YD%NTSML
WRITE (KLUN) YD%TSPHY
WRITE (KLUN) YD%XMUCVPP
WRITE (KLUN) YD%XMULAF
WRITE (KLUN) YD%XDAMP
WRITE (KLUN) YD%HCLP
WRITE (KLUN) YD%HTCLS
WRITE (KLUN) YD%HVCLS
WRITE (KLUN) YD%HTSHM
WRITE (KLUN) YD%HTSML
WRITE (KLUN) YD%HWMOHIGH
WRITE (KLUN) YD%HWMOLOW
WRITE (KLUN) YD%GZ0RAF
WRITE (KLUN) YD%FACRAF
WRITE (KLUN) YD%FACRAFCV
WRITE (KLUN) YD%FACRAFDCAPE
WRITE (KLUN) YD%GCAPERAF
WRITE (KLUN) YD%HTKERAF
WRITE (KLUN) YD%LRAFTUR
WRITE (KLUN) YD%LMULAF
WRITE (KLUN) YD%LWMOCLOUD
WRITE (KLUN) YD%LRAFTKE
END SUBROUTINE

SUBROUTINE LOAD_TPHY2 (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPHY2), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NTSHM
READ (KLUN) YD%NTSML
READ (KLUN) YD%TSPHY
READ (KLUN) YD%XMUCVPP
READ (KLUN) YD%XMULAF
READ (KLUN) YD%XDAMP
READ (KLUN) YD%HCLP
READ (KLUN) YD%HTCLS
READ (KLUN) YD%HVCLS
READ (KLUN) YD%HTSHM
READ (KLUN) YD%HTSML
READ (KLUN) YD%HWMOHIGH
READ (KLUN) YD%HWMOLOW
READ (KLUN) YD%GZ0RAF
READ (KLUN) YD%FACRAF
READ (KLUN) YD%FACRAFCV
READ (KLUN) YD%FACRAFDCAPE
READ (KLUN) YD%GCAPERAF
READ (KLUN) YD%HTKERAF
READ (KLUN) YD%LRAFTUR
READ (KLUN) YD%LMULAF
READ (KLUN) YD%LWMOCLOUD
READ (KLUN) YD%LRAFTKE
END SUBROUTINE


SUBROUTINE COPY_TPHY2 (YD, LDCREATED)
IMPLICIT NONE
CLASS (TPHY2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF























END SUBROUTINE

SUBROUTINE WIPE_TPHY2 (YD, LDDELETED)
IMPLICIT NONE
CLASS (TPHY2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
























LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
