MODULE UTIL_TLEP_MOD

USE YEMLAP, ONLY : TLEP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLEP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLEP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TLEP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLEP), INTENT (IN), TARGET :: YD
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO, LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
LNCPL2M = ALLOCATED (YD%NCPL2M)
WRITE (KLUN) LNCPL2M
IF (LNCPL2M) THEN
  WRITE (KLUN) LBOUND (YD%NCPL2M)
  WRITE (KLUN) UBOUND (YD%NCPL2M)
  WRITE (KLUN) YD%NCPL2M
ENDIF
LNCPL4M = ALLOCATED (YD%NCPL4M)
WRITE (KLUN) LNCPL4M
IF (LNCPL4M) THEN
  WRITE (KLUN) LBOUND (YD%NCPL4M)
  WRITE (KLUN) UBOUND (YD%NCPL4M)
  WRITE (KLUN) YD%NCPL4M
ENDIF
LNCPLM = ALLOCATED (YD%NCPLM)
WRITE (KLUN) LNCPLM
IF (LNCPLM) THEN
  WRITE (KLUN) LBOUND (YD%NCPLM)
  WRITE (KLUN) UBOUND (YD%NCPLM)
  WRITE (KLUN) YD%NCPLM
ENDIF
LNCPL2N = ALLOCATED (YD%NCPL2N)
WRITE (KLUN) LNCPL2N
IF (LNCPL2N) THEN
  WRITE (KLUN) LBOUND (YD%NCPL2N)
  WRITE (KLUN) UBOUND (YD%NCPL2N)
  WRITE (KLUN) YD%NCPL2N
ENDIF
LNCPL4N = ALLOCATED (YD%NCPL4N)
WRITE (KLUN) LNCPL4N
IF (LNCPL4N) THEN
  WRITE (KLUN) LBOUND (YD%NCPL4N)
  WRITE (KLUN) UBOUND (YD%NCPL4N)
  WRITE (KLUN) YD%NCPL4N
ENDIF
LNCPLN = ALLOCATED (YD%NCPLN)
WRITE (KLUN) LNCPLN
IF (LNCPLN) THEN
  WRITE (KLUN) LBOUND (YD%NCPLN)
  WRITE (KLUN) UBOUND (YD%NCPLN)
  WRITE (KLUN) YD%NCPLN
ENDIF
LRLEPDIN = ALLOCATED (YD%RLEPDIN)
WRITE (KLUN) LRLEPDIN
IF (LRLEPDIN) THEN
  WRITE (KLUN) LBOUND (YD%RLEPDIN)
  WRITE (KLUN) UBOUND (YD%RLEPDIN)
  WRITE (KLUN) YD%RLEPDIN
ENDIF
LRLEPINN = ALLOCATED (YD%RLEPINN)
WRITE (KLUN) LRLEPINN
IF (LRLEPINN) THEN
  WRITE (KLUN) LBOUND (YD%RLEPINN)
  WRITE (KLUN) UBOUND (YD%RLEPINN)
  WRITE (KLUN) YD%RLEPINN
ENDIF
LRLEPDIM = ALLOCATED (YD%RLEPDIM)
WRITE (KLUN) LRLEPDIM
IF (LRLEPDIM) THEN
  WRITE (KLUN) LBOUND (YD%RLEPDIM)
  WRITE (KLUN) UBOUND (YD%RLEPDIM)
  WRITE (KLUN) YD%RLEPDIM
ENDIF
LRLEPINM = ALLOCATED (YD%RLEPINM)
WRITE (KLUN) LRLEPINM
IF (LRLEPINM) THEN
  WRITE (KLUN) LBOUND (YD%RLEPINM)
  WRITE (KLUN) UBOUND (YD%RLEPINM)
  WRITE (KLUN) YD%RLEPINM
ENDIF
LNESM0 = ALLOCATED (YD%NESM0)
WRITE (KLUN) LNESM0
IF (LNESM0) THEN
  WRITE (KLUN) LBOUND (YD%NESM0)
  WRITE (KLUN) UBOUND (YD%NESM0)
  WRITE (KLUN) YD%NESM0
ENDIF
LNESPZERO = ALLOCATED (YD%NESPZERO)
WRITE (KLUN) LNESPZERO
IF (LNESPZERO) THEN
  WRITE (KLUN) LBOUND (YD%NESPZERO)
  WRITE (KLUN) UBOUND (YD%NESPZERO)
  WRITE (KLUN) YD%NESPZERO
ENDIF
LNESM0G = ALLOCATED (YD%NESM0G)
WRITE (KLUN) LNESM0G
IF (LNESM0G) THEN
  WRITE (KLUN) LBOUND (YD%NESM0G)
  WRITE (KLUN) UBOUND (YD%NESM0G)
  WRITE (KLUN) YD%NESM0G
ENDIF
LNPME = ALLOCATED (YD%NPME)
WRITE (KLUN) LNPME
IF (LNPME) THEN
  WRITE (KLUN) LBOUND (YD%NPME)
  WRITE (KLUN) UBOUND (YD%NPME)
  WRITE (KLUN) YD%NPME
ENDIF
LNPNE = ALLOCATED (YD%NPNE)
WRITE (KLUN) LNPNE
IF (LNPNE) THEN
  WRITE (KLUN) LBOUND (YD%NPNE)
  WRITE (KLUN) UBOUND (YD%NPNE)
  WRITE (KLUN) YD%NPNE
ENDIF
LMVALUE = ALLOCATED (YD%MVALUE)
WRITE (KLUN) LMVALUE
IF (LMVALUE) THEN
  WRITE (KLUN) LBOUND (YD%MVALUE)
  WRITE (KLUN) UBOUND (YD%MVALUE)
  WRITE (KLUN) YD%MVALUE
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TLEP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLEP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO, LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
READ (KLUN) LNCPL2M
IF (LNCPL2M) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL2M (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL2M
ENDIF
READ (KLUN) LNCPL4M
IF (LNCPL4M) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL4M (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL4M
ENDIF
READ (KLUN) LNCPLM
IF (LNCPLM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPLM (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPLM
ENDIF
READ (KLUN) LNCPL2N
IF (LNCPL2N) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL2N (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL2N
ENDIF
READ (KLUN) LNCPL4N
IF (LNCPL4N) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL4N (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL4N
ENDIF
READ (KLUN) LNCPLN
IF (LNCPLN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPLN (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPLN
ENDIF
READ (KLUN) LRLEPDIN
IF (LRLEPDIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPDIN (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPDIN
ENDIF
READ (KLUN) LRLEPINN
IF (LRLEPINN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPINN (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPINN
ENDIF
READ (KLUN) LRLEPDIM
IF (LRLEPDIM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPDIM (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPDIM
ENDIF
READ (KLUN) LRLEPINM
IF (LRLEPINM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPINM (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPINM
ENDIF
READ (KLUN) LNESM0
IF (LNESM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NESM0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NESM0
ENDIF
READ (KLUN) LNESPZERO
IF (LNESPZERO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NESPZERO (IL1(1):IU1(1)))
  READ (KLUN) YD%NESPZERO
ENDIF
READ (KLUN) LNESM0G
IF (LNESM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NESM0G (IL1(1):IU1(1)))
  READ (KLUN) YD%NESM0G
ENDIF
READ (KLUN) LNPME
IF (LNPME) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPME (IL1(1):IU1(1)))
  READ (KLUN) YD%NPME
ENDIF
READ (KLUN) LNPNE
IF (LNPNE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPNE (IL1(1):IU1(1)))
  READ (KLUN) YD%NPNE
ENDIF
READ (KLUN) LMVALUE
IF (LMVALUE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MVALUE (IL1(1):IU1(1)))
  READ (KLUN) YD%MVALUE
ENDIF
END SUBROUTINE




END MODULE
