MODULE UTIL_TDPHY_MOD

USE YOMDPHY, ONLY : TDPHY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDPHY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDPHY
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TDPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPHY), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NCSS
WRITE (KLUN) YD%NVXP
WRITE (KLUN) YD%NVXP2
WRITE (KLUN) YD%NCXP
WRITE (KLUN) YD%NCSI
WRITE (KLUN) YD%NCOM
WRITE (KLUN) YD%NCSNEC
WRITE (KLUN) YD%NTILES
WRITE (KLUN) YD%NVEXTR
WRITE (KLUN) YD%NVEXTRDI
WRITE (KLUN) YD%NVEXTRRAD
WRITE (KLUN) YD%NVEXTRDYN
WRITE (KLUN) YD%NVXTR2
WRITE (KLUN) YD%NVECOUT
WRITE (KLUN) YD%NCEXTR
WRITE (KLUN) YD%NVCLIS
WRITE (KLUN) YD%NTOZ1D
WRITE (KLUN) YD%NTOZ2D
WRITE (KLUN) YD%NTOZ3D
WRITE (KLUN) YD%NTSSG
WRITE (KLUN) YD%LTPROF
WRITE (KLUN) YD%LDIRCLSMOD
WRITE (KLUN) YD%LDIRSICMOD
END SUBROUTINE

SUBROUTINE LOAD_TDPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPHY), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NCSS
READ (KLUN) YD%NVXP
READ (KLUN) YD%NVXP2
READ (KLUN) YD%NCXP
READ (KLUN) YD%NCSI
READ (KLUN) YD%NCOM
READ (KLUN) YD%NCSNEC
READ (KLUN) YD%NTILES
READ (KLUN) YD%NVEXTR
READ (KLUN) YD%NVEXTRDI
READ (KLUN) YD%NVEXTRRAD
READ (KLUN) YD%NVEXTRDYN
READ (KLUN) YD%NVXTR2
READ (KLUN) YD%NVECOUT
READ (KLUN) YD%NCEXTR
READ (KLUN) YD%NVCLIS
READ (KLUN) YD%NTOZ1D
READ (KLUN) YD%NTOZ2D
READ (KLUN) YD%NTOZ3D
READ (KLUN) YD%NTSSG
READ (KLUN) YD%LTPROF
READ (KLUN) YD%LDIRCLSMOD
READ (KLUN) YD%LDIRSICMOD
END SUBROUTINE






END MODULE
