MODULE UTIL_TPTRSLB2_MOD

USE PTRSLB2, ONLY : TPTRSLB2


INTERFACE SAVE
MODULE PROCEDURE SAVE_TPTRSLB2
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPTRSLB2
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPTRSLB2
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPTRSLB2
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TPTRSLB2 (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPTRSLB2), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NFLDSLB2
WRITE (KLUN) YD%MSLBUF2
WRITE (KLUN) YD%MSLB2DBBC1
WRITE (KLUN) YD%MSLB2DPHI1
WRITE (KLUN) YD%MSLB2USI
WRITE (KLUN) YD%MSLB2VSI
WRITE (KLUN) YD%MSLB2TSI
WRITE (KLUN) YD%MSLB2PDSI
WRITE (KLUN) YD%MSLB2VDSI
WRITE (KLUN) YD%MSLB2SPSI
WRITE (KLUN) YD%MSLB2VVEL
WRITE (KLUN) YD%MSLB2URL
WRITE (KLUN) YD%MSLB2VRL
WRITE (KLUN) YD%MSLB2WRL
WRITE (KLUN) YD%MSLB2URL5
WRITE (KLUN) YD%MSLB2VRL5
WRITE (KLUN) YD%MSLB2WRL5
WRITE (KLUN) YD%MSLB2USI5
WRITE (KLUN) YD%MSLB2VSI5
WRITE (KLUN) YD%MSLB2U15
WRITE (KLUN) YD%MSLB2V15
WRITE (KLUN) YD%MSLB2T15
WRITE (KLUN) YD%MSLB2Q15
WRITE (KLUN) YD%MSLB2KAPPA
WRITE (KLUN) YD%MSLB2KAPPAT
WRITE (KLUN) YD%MSLB2KAPPAM
WRITE (KLUN) YD%MSLB2KAPPAH
WRITE (KLUN) YD%MSLB2KAPPA5
WRITE (KLUN) YD%MSLB2KAPPAT5
WRITE (KLUN) YD%MSLB2GWF
WRITE (KLUN) YD%MSLB2GDW
WRITE (KLUN) YD%MSLB2GWS
WRITE (KLUN) YD%MSLB2STDDISU
WRITE (KLUN) YD%MSLB2STDDISV
WRITE (KLUN) YD%MSLB2STDDISW
END SUBROUTINE

SUBROUTINE LOAD_TPTRSLB2 (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPTRSLB2), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NFLDSLB2
READ (KLUN) YD%MSLBUF2
READ (KLUN) YD%MSLB2DBBC1
READ (KLUN) YD%MSLB2DPHI1
READ (KLUN) YD%MSLB2USI
READ (KLUN) YD%MSLB2VSI
READ (KLUN) YD%MSLB2TSI
READ (KLUN) YD%MSLB2PDSI
READ (KLUN) YD%MSLB2VDSI
READ (KLUN) YD%MSLB2SPSI
READ (KLUN) YD%MSLB2VVEL
READ (KLUN) YD%MSLB2URL
READ (KLUN) YD%MSLB2VRL
READ (KLUN) YD%MSLB2WRL
READ (KLUN) YD%MSLB2URL5
READ (KLUN) YD%MSLB2VRL5
READ (KLUN) YD%MSLB2WRL5
READ (KLUN) YD%MSLB2USI5
READ (KLUN) YD%MSLB2VSI5
READ (KLUN) YD%MSLB2U15
READ (KLUN) YD%MSLB2V15
READ (KLUN) YD%MSLB2T15
READ (KLUN) YD%MSLB2Q15
READ (KLUN) YD%MSLB2KAPPA
READ (KLUN) YD%MSLB2KAPPAT
READ (KLUN) YD%MSLB2KAPPAM
READ (KLUN) YD%MSLB2KAPPAH
READ (KLUN) YD%MSLB2KAPPA5
READ (KLUN) YD%MSLB2KAPPAT5
READ (KLUN) YD%MSLB2GWF
READ (KLUN) YD%MSLB2GDW
READ (KLUN) YD%MSLB2GWS
READ (KLUN) YD%MSLB2STDDISU
READ (KLUN) YD%MSLB2STDDISV
READ (KLUN) YD%MSLB2STDDISW
END SUBROUTINE


SUBROUTINE COPY_TPTRSLB2 (YD, LDCREATED)
IMPLICIT NONE
CLASS (TPTRSLB2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF



































END SUBROUTINE

SUBROUTINE WIPE_TPTRSLB2 (YD, LDDELETED)
IMPLICIT NONE
CLASS (TPTRSLB2), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED




































LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
