MODULE UTIL_TEDBUG_MOD

USE YOEDBUG, ONLY : TEDBUG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEDBUG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEDBUG
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEDBUG
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEDBUG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEDBUG), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%KSTPDBG
WRITE (KLUN) YD%NSTPDBG
END SUBROUTINE

SUBROUTINE LOAD_TEDBUG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEDBUG), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%KSTPDBG
READ (KLUN) YD%NSTPDBG
END SUBROUTINE


SUBROUTINE COPY_TEDBUG (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEDBUG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF


END SUBROUTINE



END MODULE
