MODULE UTIL_MODEL_MOD

USE TYPE_MODEL, ONLY : MODEL
USE UTIL_MODEL_ATMOS_OCEAN_COUPLING_TYPE_MOD
USE UTIL_MODEL_CHEM_TYPE_MOD
USE UTIL_MODEL_DIAGNOSTICS_TYPE_MOD
USE UTIL_MODEL_DYNAMICS_TYPE_MOD
USE UTIL_MODEL_GENERAL_CONF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_AEROSOL_TYPE_MOD
USE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_GENERAL_TYPE_MOD
USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_RADIATION_TYPE_MOD
USE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD
USE UTIL_MODEL_PHYSICS_STOCHAST_TYPE_MOD
USE UTIL_TCST_MOD
USE UTIL_TELBC_MODEL_MOD
USE UTIL_TEWCOU_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL), INTENT (IN), TARGET :: YD
LOGICAL :: LYRCST, LYRML_LBC

WRITE (KLUN) YD%LINEAR_MODEL
CALL SAVE (KLUN, YD%YRML_GCONF)
CALL SAVE (KLUN, YD%YRML_AOC)
CALL SAVE (KLUN, YD%YRML_DYN)
CALL SAVE (KLUN, YD%YRML_PHY_G)
CALL SAVE (KLUN, YD%YRML_PHY_EC)
CALL SAVE (KLUN, YD%YRML_PHY_SLIN)
CALL SAVE (KLUN, YD%YRML_PHY_AER)
CALL SAVE (KLUN, YD%YRML_PHY_RAD)
CALL SAVE (KLUN, YD%YRML_PHY_STOCH)
CALL SAVE (KLUN, YD%YRML_PHY_MF)
CALL SAVE (KLUN, YD%YRML_CHEM)
CALL SAVE (KLUN, YD%YRML_DIAG)
CALL SAVE (KLUN, YD%YREWCOU)
LYRCST = ASSOCIATED (YD%YRCST)
WRITE (KLUN) LYRCST
IF (LYRCST) THEN
  CALL SAVE (KLUN, YD%YRCST)
ENDIF
LYRML_LBC = ASSOCIATED (YD%YRML_LBC)
WRITE (KLUN) LYRML_LBC
IF (LYRML_LBC) THEN
  CALL SAVE (KLUN, YD%YRML_LBC)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_MODEL (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL), INTENT (OUT), TARGET :: YD
LOGICAL :: LYRCST, LYRML_LBC

READ (KLUN) YD%LINEAR_MODEL
CALL LOAD (KLUN, YD%YRML_GCONF)
CALL LOAD (KLUN, YD%YRML_AOC)
CALL LOAD (KLUN, YD%YRML_DYN)
CALL LOAD (KLUN, YD%YRML_PHY_G)
CALL LOAD (KLUN, YD%YRML_PHY_EC)
CALL LOAD (KLUN, YD%YRML_PHY_SLIN)
CALL LOAD (KLUN, YD%YRML_PHY_AER)
CALL LOAD (KLUN, YD%YRML_PHY_RAD)
CALL LOAD (KLUN, YD%YRML_PHY_STOCH)
CALL LOAD (KLUN, YD%YRML_PHY_MF)
CALL LOAD (KLUN, YD%YRML_CHEM)
CALL LOAD (KLUN, YD%YRML_DIAG)
CALL LOAD (KLUN, YD%YREWCOU)
READ (KLUN) LYRCST
IF (LYRCST) THEN
  ALLOCATE (YD%YRCST)
  CALL LOAD (KLUN, YD%YRCST)
ELSE
  NULLIFY (YD%YRCST)
ENDIF
READ (KLUN) LYRML_LBC
IF (LYRML_LBC) THEN
  ALLOCATE (YD%YRML_LBC)
  CALL LOAD (KLUN, YD%YRML_LBC)
ELSE
  NULLIFY (YD%YRML_LBC)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_MODEL (YD, LDCREATED)
IMPLICIT NONE
CLASS (MODEL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LYRCST, LYRML_LBC

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

CALL COPY (YD%YRML_GCONF, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_AOC, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_DYN, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_G, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_EC, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_SLIN, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_AER, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_RAD, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_STOCH, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_PHY_MF, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_CHEM, LDCREATED=.TRUE.)

CALL COPY (YD%YRML_DIAG, LDCREATED=.TRUE.)

CALL COPY (YD%YREWCOU, LDCREATED=.TRUE.)

LYRCST = ASSOCIATED (YD%YRCST)
IF (LYRCST) THEN
  !$acc enter data create (YD%YRCST)
  !$acc update device (YD%YRCST)
  CALL COPY (YD%YRCST, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRCST)
ENDIF

LYRML_LBC = ASSOCIATED (YD%YRML_LBC)
IF (LYRML_LBC) THEN
  !$acc enter data create (YD%YRML_LBC)
  !$acc update device (YD%YRML_LBC)
  CALL COPY (YD%YRML_LBC, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRML_LBC)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_MODEL (YD, LDDELETED)
IMPLICIT NONE
CLASS (MODEL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LYRCST, LYRML_LBC


CALL WIPE (YD%YRML_GCONF, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_AOC, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_DYN, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_G, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_EC, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_SLIN, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_AER, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_RAD, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_STOCH, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_PHY_MF, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_CHEM, LDDELETED=.TRUE.)

CALL WIPE (YD%YRML_DIAG, LDDELETED=.TRUE.)

CALL WIPE (YD%YREWCOU, LDDELETED=.TRUE.)

LYRCST = ASSOCIATED (YD%YRCST)
IF (LYRCST) THEN
  !$acc exit data detach (YD%YRCST)
  CALL WIPE (YD%YRCST, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRCST)
ENDIF

LYRML_LBC = ASSOCIATED (YD%YRML_LBC)
IF (LYRML_LBC) THEN
  !$acc exit data detach (YD%YRML_LBC)
  CALL WIPE (YD%YRML_LBC, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRML_LBC)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
