MODULE UTIL_GEOMETRY_VARIABLES_MOD

USE FIELD_VARIABLES_MOD, ONLY : GEOMETRY_VARIABLES

INTERFACE SAVE
MODULE PROCEDURE SAVE_GEOMETRY_VARIABLES
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_GEOMETRY_VARIABLES
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_GEOMETRY_VARIABLES
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_GEOMETRY_VARIABLES
END INTERFACE



CONTAINS

SUBROUTINE SAVE_GEOMETRY_VARIABLES (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY_VARIABLES), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%GM)
END SUBROUTINE

SUBROUTINE LOAD_GEOMETRY_VARIABLES (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY_VARIABLES), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%GM)
END SUBROUTINE


SUBROUTINE COPY_GEOMETRY_VARIABLES (YD, LDCREATED)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
TYPE (GEOMETRY_VARIABLES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%GM, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_GEOMETRY_VARIABLES (YD, LDDELETED)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
TYPE (GEOMETRY_VARIABLES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%GM, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
