MODULE UTIL_SL_STRUCT_MOD

USE EINT_MOD, ONLY : SL_STRUCT

INTERFACE SAVE
MODULE PROCEDURE SAVE_SL_STRUCT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SL_STRUCT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_SL_STRUCT
END INTERFACE



CONTAINS

SUBROUTINE SAVE_SL_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SL_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL :: LDIST1GP, LLCOMPLAT, LLSLCOMM, LLSLCORE, LMASK_SL1, LMASK_SL2, LMASK_SL2T, LMASK_SLD, LMASK_SLTOT, LNLATGLO
LOGICAL :: LNLOENG, LNSLCOMM, LNSLCORE, LNSLEXT, LNSLMAP, LNSLOFF, LNSLONL, LNSLPTSEAST, LNSLPTSWEST, LNSLRECVPOS
LOGICAL :: LNSLRECVPTR, LNSLSENDPOS, LNSLSENDPTR, LNSLSTA
WRITE (KLUN) YD%CVER
WRITE (KLUN) YD%NSLGROUP
LNSLSTA = ALLOCATED (YD%NSLSTA)
WRITE (KLUN) LNSLSTA
IF (LNSLSTA) THEN
  WRITE (KLUN) LBOUND (YD%NSLSTA)
  WRITE (KLUN) UBOUND (YD%NSLSTA)
  WRITE (KLUN) YD%NSLSTA
ENDIF
LNSLONL = ALLOCATED (YD%NSLONL)
WRITE (KLUN) LNSLONL
IF (LNSLONL) THEN
  WRITE (KLUN) LBOUND (YD%NSLONL)
  WRITE (KLUN) UBOUND (YD%NSLONL)
  WRITE (KLUN) YD%NSLONL
ENDIF
LNSLOFF = ALLOCATED (YD%NSLOFF)
WRITE (KLUN) LNSLOFF
IF (LNSLOFF) THEN
  WRITE (KLUN) LBOUND (YD%NSLOFF)
  WRITE (KLUN) UBOUND (YD%NSLOFF)
  WRITE (KLUN) YD%NSLOFF
ENDIF
LNSLPTSWEST = ALLOCATED (YD%NSLPTSWEST)
WRITE (KLUN) LNSLPTSWEST
IF (LNSLPTSWEST) THEN
  WRITE (KLUN) LBOUND (YD%NSLPTSWEST)
  WRITE (KLUN) UBOUND (YD%NSLPTSWEST)
  WRITE (KLUN) YD%NSLPTSWEST
ENDIF
LNSLPTSEAST = ALLOCATED (YD%NSLPTSEAST)
WRITE (KLUN) LNSLPTSEAST
IF (LNSLPTSEAST) THEN
  WRITE (KLUN) LBOUND (YD%NSLPTSEAST)
  WRITE (KLUN) UBOUND (YD%NSLPTSEAST)
  WRITE (KLUN) YD%NSLPTSEAST
ENDIF
LNSLEXT = ALLOCATED (YD%NSLEXT)
WRITE (KLUN) LNSLEXT
IF (LNSLEXT) THEN
  WRITE (KLUN) LBOUND (YD%NSLEXT)
  WRITE (KLUN) UBOUND (YD%NSLEXT)
  WRITE (KLUN) YD%NSLEXT
ENDIF
LLCOMPLAT = ALLOCATED (YD%LCOMPLAT)
WRITE (KLUN) LLCOMPLAT
IF (LLCOMPLAT) THEN
  WRITE (KLUN) LBOUND (YD%LCOMPLAT)
  WRITE (KLUN) UBOUND (YD%LCOMPLAT)
  WRITE (KLUN) YD%LCOMPLAT
ENDIF
LNLATGLO = ALLOCATED (YD%NLATGLO)
WRITE (KLUN) LNLATGLO
IF (LNLATGLO) THEN
  WRITE (KLUN) LBOUND (YD%NLATGLO)
  WRITE (KLUN) UBOUND (YD%NLATGLO)
  WRITE (KLUN) YD%NLATGLO
ENDIF
LDIST1GP = ALLOCATED (YD%DIST1GP)
WRITE (KLUN) LDIST1GP
IF (LDIST1GP) THEN
  WRITE (KLUN) LBOUND (YD%DIST1GP)
  WRITE (KLUN) UBOUND (YD%DIST1GP)
  WRITE (KLUN) YD%DIST1GP
ENDIF
LNSLSENDPOS = ALLOCATED (YD%NSLSENDPOS)
WRITE (KLUN) LNSLSENDPOS
IF (LNSLSENDPOS) THEN
  WRITE (KLUN) LBOUND (YD%NSLSENDPOS)
  WRITE (KLUN) UBOUND (YD%NSLSENDPOS)
  WRITE (KLUN) YD%NSLSENDPOS
ENDIF
LNSLRECVPOS = ALLOCATED (YD%NSLRECVPOS)
WRITE (KLUN) LNSLRECVPOS
IF (LNSLRECVPOS) THEN
  WRITE (KLUN) LBOUND (YD%NSLRECVPOS)
  WRITE (KLUN) UBOUND (YD%NSLRECVPOS)
  WRITE (KLUN) YD%NSLRECVPOS
ENDIF
LNSLSENDPTR = ALLOCATED (YD%NSLSENDPTR)
WRITE (KLUN) LNSLSENDPTR
IF (LNSLSENDPTR) THEN
  WRITE (KLUN) LBOUND (YD%NSLSENDPTR)
  WRITE (KLUN) UBOUND (YD%NSLSENDPTR)
  WRITE (KLUN) YD%NSLSENDPTR
ENDIF
LNSLRECVPTR = ALLOCATED (YD%NSLRECVPTR)
WRITE (KLUN) LNSLRECVPTR
IF (LNSLRECVPTR) THEN
  WRITE (KLUN) LBOUND (YD%NSLRECVPTR)
  WRITE (KLUN) UBOUND (YD%NSLRECVPTR)
  WRITE (KLUN) YD%NSLRECVPTR
ENDIF
LNSLCOMM = ALLOCATED (YD%NSLCOMM)
WRITE (KLUN) LNSLCOMM
IF (LNSLCOMM) THEN
  WRITE (KLUN) LBOUND (YD%NSLCOMM)
  WRITE (KLUN) UBOUND (YD%NSLCOMM)
  WRITE (KLUN) YD%NSLCOMM
ENDIF
LLSLCOMM = ALLOCATED (YD%LSLCOMM)
WRITE (KLUN) LLSLCOMM
IF (LLSLCOMM) THEN
  WRITE (KLUN) LBOUND (YD%LSLCOMM)
  WRITE (KLUN) UBOUND (YD%LSLCOMM)
  WRITE (KLUN) YD%LSLCOMM
ENDIF
WRITE (KLUN) YD%NASLB1
WRITE (KLUN) YD%NASLB1_TRUE
WRITE (KLUN) YD%NSLPAD
WRITE (KLUN) YD%LSLT_ARRAYS_INIT
WRITE (KLUN) YD%LSLONDEM
WRITE (KLUN) YD%LSLONDEM_ACTIVE
WRITE (KLUN) YD%NUNUSEDHALO
WRITE (KLUN) YD%DISTUNUSEDHALO
LMASK_SL1 = ALLOCATED (YD%MASK_SL1)
WRITE (KLUN) LMASK_SL1
IF (LMASK_SL1) THEN
  WRITE (KLUN) LBOUND (YD%MASK_SL1)
  WRITE (KLUN) UBOUND (YD%MASK_SL1)
  WRITE (KLUN) YD%MASK_SL1
ENDIF
LMASK_SL2 = ALLOCATED (YD%MASK_SL2)
WRITE (KLUN) LMASK_SL2
IF (LMASK_SL2) THEN
  WRITE (KLUN) LBOUND (YD%MASK_SL2)
  WRITE (KLUN) UBOUND (YD%MASK_SL2)
  WRITE (KLUN) YD%MASK_SL2
ENDIF
LMASK_SL2T = ALLOCATED (YD%MASK_SL2T)
WRITE (KLUN) LMASK_SL2T
IF (LMASK_SL2T) THEN
  WRITE (KLUN) LBOUND (YD%MASK_SL2T)
  WRITE (KLUN) UBOUND (YD%MASK_SL2T)
  WRITE (KLUN) YD%MASK_SL2T
ENDIF
LMASK_SLD = ALLOCATED (YD%MASK_SLD)
WRITE (KLUN) LMASK_SLD
IF (LMASK_SLD) THEN
  WRITE (KLUN) LBOUND (YD%MASK_SLD)
  WRITE (KLUN) UBOUND (YD%MASK_SLD)
  WRITE (KLUN) YD%MASK_SLD
ENDIF
WRITE (KLUN) YD%NSLPROCS
WRITE (KLUN) YD%NSLRPT
WRITE (KLUN) YD%NSLSPT
WRITE (KLUN) YD%NSLWIDEN
WRITE (KLUN) YD%NSLWIDES
WRITE (KLUN) YD%NSLWIDEE
WRITE (KLUN) YD%NSLWIDEW
WRITE (KLUN) YD%NSLWIDE
LNSLMAP = ALLOCATED (YD%NSLMAP)
WRITE (KLUN) LNSLMAP
IF (LNSLMAP) THEN
  WRITE (KLUN) LBOUND (YD%NSLMAP)
  WRITE (KLUN) UBOUND (YD%NSLMAP)
  WRITE (KLUN) YD%NSLMAP
ENDIF
LNSLCORE = ALLOCATED (YD%NSLCORE)
WRITE (KLUN) LNSLCORE
IF (LNSLCORE) THEN
  WRITE (KLUN) LBOUND (YD%NSLCORE)
  WRITE (KLUN) UBOUND (YD%NSLCORE)
  WRITE (KLUN) YD%NSLCORE
ENDIF
LLSLCORE = ALLOCATED (YD%LSLCORE)
WRITE (KLUN) LLSLCORE
IF (LLSLCORE) THEN
  WRITE (KLUN) LBOUND (YD%LSLCORE)
  WRITE (KLUN) UBOUND (YD%LSLCORE)
  WRITE (KLUN) YD%LSLCORE
ENDIF
LMASK_SLTOT = ALLOCATED (YD%MASK_SLTOT)
WRITE (KLUN) LMASK_SLTOT
IF (LMASK_SLTOT) THEN
  WRITE (KLUN) LBOUND (YD%MASK_SLTOT)
  WRITE (KLUN) UBOUND (YD%MASK_SLTOT)
  WRITE (KLUN) YD%MASK_SLTOT
ENDIF
WRITE (KLUN) YD%NDGLG
WRITE (KLUN) YD%NDLON
WRITE (KLUN) YD%NDGSAG
WRITE (KLUN) YD%NDGENG
WRITE (KLUN) YD%NDGSAL
WRITE (KLUN) YD%NDGENL
WRITE (KLUN) YD%NDGSAH
WRITE (KLUN) YD%NDGENH
WRITE (KLUN) YD%NGPTOT
WRITE (KLUN) YD%NDGUXL
WRITE (KLUN) YD%NDLUNG
WRITE (KLUN) YD%NDLUXG
WRITE (KLUN) YD%NDGUNG
WRITE (KLUN) YD%NDGUXG
WRITE (KLUN) YD%NDSUR1
WRITE (KLUN) YD%NDLSUR
WRITE (KLUN) YD%NDGSUR
WRITE (KLUN) YD%NPTRFLOFF
WRITE (KLUN) YD%NFRSTLOFF
WRITE (KLUN) YD%MYFRSTACTLAT
WRITE (KLUN) YD%MYLSTACTLAT
LNLOENG = ALLOCATED (YD%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (YD%NLOENG)
  WRITE (KLUN) UBOUND (YD%NLOENG)
  WRITE (KLUN) YD%NLOENG
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SL_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SL_STRUCT), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LDIST1GP, LLCOMPLAT, LLSLCOMM, LLSLCORE, LMASK_SL1, LMASK_SL2, LMASK_SL2T, LMASK_SLD, LMASK_SLTOT, LNLATGLO
LOGICAL :: LNLOENG, LNSLCOMM, LNSLCORE, LNSLEXT, LNSLMAP, LNSLOFF, LNSLONL, LNSLPTSEAST, LNSLPTSWEST, LNSLRECVPOS
LOGICAL :: LNSLRECVPTR, LNSLSENDPOS, LNSLSENDPTR, LNSLSTA
READ (KLUN) YD%CVER
READ (KLUN) YD%NSLGROUP
READ (KLUN) LNSLSTA
IF (LNSLSTA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLSTA (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLSTA
ENDIF
READ (KLUN) LNSLONL
IF (LNSLONL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLONL (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLONL
ENDIF
READ (KLUN) LNSLOFF
IF (LNSLOFF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLOFF (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLOFF
ENDIF
READ (KLUN) LNSLPTSWEST
IF (LNSLPTSWEST) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLPTSWEST (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLPTSWEST
ENDIF
READ (KLUN) LNSLPTSEAST
IF (LNSLPTSEAST) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLPTSEAST (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLPTSEAST
ENDIF
READ (KLUN) LNSLEXT
IF (LNSLEXT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSLEXT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSLEXT
ENDIF
READ (KLUN) LLCOMPLAT
IF (LLCOMPLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LCOMPLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%LCOMPLAT
ENDIF
READ (KLUN) LNLATGLO
IF (LNLATGLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLATGLO (IL1(1):IU1(1)))
  READ (KLUN) YD%NLATGLO
ENDIF
READ (KLUN) LDIST1GP
IF (LDIST1GP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%DIST1GP (IL1(1):IU1(1)))
  READ (KLUN) YD%DIST1GP
ENDIF
READ (KLUN) LNSLSENDPOS
IF (LNSLSENDPOS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLSENDPOS (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLSENDPOS
ENDIF
READ (KLUN) LNSLRECVPOS
IF (LNSLRECVPOS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLRECVPOS (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLRECVPOS
ENDIF
READ (KLUN) LNSLSENDPTR
IF (LNSLSENDPTR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLSENDPTR (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLSENDPTR
ENDIF
READ (KLUN) LNSLRECVPTR
IF (LNSLRECVPTR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLRECVPTR (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLRECVPTR
ENDIF
READ (KLUN) LNSLCOMM
IF (LNSLCOMM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLCOMM (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLCOMM
ENDIF
READ (KLUN) LLSLCOMM
IF (LLSLCOMM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%LSLCOMM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%LSLCOMM
ENDIF
READ (KLUN) YD%NASLB1
READ (KLUN) YD%NASLB1_TRUE
READ (KLUN) YD%NSLPAD
READ (KLUN) YD%LSLT_ARRAYS_INIT
READ (KLUN) YD%LSLONDEM
READ (KLUN) YD%LSLONDEM_ACTIVE
READ (KLUN) YD%NUNUSEDHALO
READ (KLUN) YD%DISTUNUSEDHALO
READ (KLUN) LMASK_SL1
IF (LMASK_SL1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SL1 (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SL1
ENDIF
READ (KLUN) LMASK_SL2
IF (LMASK_SL2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SL2 (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SL2
ENDIF
READ (KLUN) LMASK_SL2T
IF (LMASK_SL2T) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASK_SL2T (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%MASK_SL2T
ENDIF
READ (KLUN) LMASK_SLD
IF (LMASK_SLD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SLD (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SLD
ENDIF
READ (KLUN) YD%NSLPROCS
READ (KLUN) YD%NSLRPT
READ (KLUN) YD%NSLSPT
READ (KLUN) YD%NSLWIDEN
READ (KLUN) YD%NSLWIDES
READ (KLUN) YD%NSLWIDEE
READ (KLUN) YD%NSLWIDEW
READ (KLUN) YD%NSLWIDE
READ (KLUN) LNSLMAP
IF (LNSLMAP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSLMAP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSLMAP
ENDIF
READ (KLUN) LNSLCORE
IF (LNSLCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLCORE
ENDIF
READ (KLUN) LLSLCORE
IF (LLSLCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LSLCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%LSLCORE
ENDIF
READ (KLUN) LMASK_SLTOT
IF (LMASK_SLTOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SLTOT (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SLTOT
ENDIF
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NDGUXL
READ (KLUN) YD%NDLUNG
READ (KLUN) YD%NDLUXG
READ (KLUN) YD%NDGUNG
READ (KLUN) YD%NDGUXG
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
END SUBROUTINE


SUBROUTINE COPY_SL_STRUCT (YD, LDCREATED)

IMPLICIT NONE
TYPE (SL_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LDIST1GP, LLCOMPLAT, LLSLCOMM, LLSLCORE, LMASK_SL1, LMASK_SL2, LMASK_SL2T, LMASK_SLD, LMASK_SLTOT, LNLATGLO
LOGICAL :: LNLOENG, LNSLCOMM, LNSLCORE, LNSLEXT, LNSLMAP, LNSLOFF, LNSLONL, LNSLPTSEAST, LNSLPTSWEST, LNSLRECVPOS
LOGICAL :: LNSLRECVPTR, LNSLSENDPOS, LNSLSENDPTR, LNSLSTA

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF


LNSLSTA = ALLOCATED (YD%NSLSTA)
IF (LNSLSTA) THEN
  !$acc enter data create (YD%NSLSTA)
  !$acc update device (YD%NSLSTA)
  !$acc enter data attach (YD%NSLSTA)
ENDIF

LNSLONL = ALLOCATED (YD%NSLONL)
IF (LNSLONL) THEN
  !$acc enter data create (YD%NSLONL)
  !$acc update device (YD%NSLONL)
  !$acc enter data attach (YD%NSLONL)
ENDIF

LNSLOFF = ALLOCATED (YD%NSLOFF)
IF (LNSLOFF) THEN
  !$acc enter data create (YD%NSLOFF)
  !$acc update device (YD%NSLOFF)
  !$acc enter data attach (YD%NSLOFF)
ENDIF

LNSLPTSWEST = ALLOCATED (YD%NSLPTSWEST)
IF (LNSLPTSWEST) THEN
  !$acc enter data create (YD%NSLPTSWEST)
  !$acc update device (YD%NSLPTSWEST)
  !$acc enter data attach (YD%NSLPTSWEST)
ENDIF

LNSLPTSEAST = ALLOCATED (YD%NSLPTSEAST)
IF (LNSLPTSEAST) THEN
  !$acc enter data create (YD%NSLPTSEAST)
  !$acc update device (YD%NSLPTSEAST)
  !$acc enter data attach (YD%NSLPTSEAST)
ENDIF

LNSLEXT = ALLOCATED (YD%NSLEXT)
IF (LNSLEXT) THEN
  !$acc enter data create (YD%NSLEXT)
  !$acc update device (YD%NSLEXT)
  !$acc enter data attach (YD%NSLEXT)
ENDIF

LLCOMPLAT = ALLOCATED (YD%LCOMPLAT)
IF (LLCOMPLAT) THEN
  !$acc enter data create (YD%LCOMPLAT)
  !$acc update device (YD%LCOMPLAT)
  !$acc enter data attach (YD%LCOMPLAT)
ENDIF

LNLATGLO = ALLOCATED (YD%NLATGLO)
IF (LNLATGLO) THEN
  !$acc enter data create (YD%NLATGLO)
  !$acc update device (YD%NLATGLO)
  !$acc enter data attach (YD%NLATGLO)
ENDIF

LDIST1GP = ALLOCATED (YD%DIST1GP)
IF (LDIST1GP) THEN
  !$acc enter data create (YD%DIST1GP)
  !$acc update device (YD%DIST1GP)
  !$acc enter data attach (YD%DIST1GP)
ENDIF

LNSLSENDPOS = ALLOCATED (YD%NSLSENDPOS)
IF (LNSLSENDPOS) THEN
  !$acc enter data create (YD%NSLSENDPOS)
  !$acc update device (YD%NSLSENDPOS)
  !$acc enter data attach (YD%NSLSENDPOS)
ENDIF

LNSLRECVPOS = ALLOCATED (YD%NSLRECVPOS)
IF (LNSLRECVPOS) THEN
  !$acc enter data create (YD%NSLRECVPOS)
  !$acc update device (YD%NSLRECVPOS)
  !$acc enter data attach (YD%NSLRECVPOS)
ENDIF

LNSLSENDPTR = ALLOCATED (YD%NSLSENDPTR)
IF (LNSLSENDPTR) THEN
  !$acc enter data create (YD%NSLSENDPTR)
  !$acc update device (YD%NSLSENDPTR)
  !$acc enter data attach (YD%NSLSENDPTR)
ENDIF

LNSLRECVPTR = ALLOCATED (YD%NSLRECVPTR)
IF (LNSLRECVPTR) THEN
  !$acc enter data create (YD%NSLRECVPTR)
  !$acc update device (YD%NSLRECVPTR)
  !$acc enter data attach (YD%NSLRECVPTR)
ENDIF

LNSLCOMM = ALLOCATED (YD%NSLCOMM)
IF (LNSLCOMM) THEN
  !$acc enter data create (YD%NSLCOMM)
  !$acc update device (YD%NSLCOMM)
  !$acc enter data attach (YD%NSLCOMM)
ENDIF

LLSLCOMM = ALLOCATED (YD%LSLCOMM)
IF (LLSLCOMM) THEN
  !$acc enter data create (YD%LSLCOMM)
  !$acc update device (YD%LSLCOMM)
  !$acc enter data attach (YD%LSLCOMM)
ENDIF









LMASK_SL1 = ALLOCATED (YD%MASK_SL1)
IF (LMASK_SL1) THEN
  !$acc enter data create (YD%MASK_SL1)
  !$acc update device (YD%MASK_SL1)
  !$acc enter data attach (YD%MASK_SL1)
ENDIF

LMASK_SL2 = ALLOCATED (YD%MASK_SL2)
IF (LMASK_SL2) THEN
  !$acc enter data create (YD%MASK_SL2)
  !$acc update device (YD%MASK_SL2)
  !$acc enter data attach (YD%MASK_SL2)
ENDIF

LMASK_SL2T = ALLOCATED (YD%MASK_SL2T)
IF (LMASK_SL2T) THEN
  !$acc enter data create (YD%MASK_SL2T)
  !$acc update device (YD%MASK_SL2T)
  !$acc enter data attach (YD%MASK_SL2T)
ENDIF

LMASK_SLD = ALLOCATED (YD%MASK_SLD)
IF (LMASK_SLD) THEN
  !$acc enter data create (YD%MASK_SLD)
  !$acc update device (YD%MASK_SLD)
  !$acc enter data attach (YD%MASK_SLD)
ENDIF









LNSLMAP = ALLOCATED (YD%NSLMAP)
IF (LNSLMAP) THEN
  !$acc enter data create (YD%NSLMAP)
  !$acc update device (YD%NSLMAP)
  !$acc enter data attach (YD%NSLMAP)
ENDIF

LNSLCORE = ALLOCATED (YD%NSLCORE)
IF (LNSLCORE) THEN
  !$acc enter data create (YD%NSLCORE)
  !$acc update device (YD%NSLCORE)
  !$acc enter data attach (YD%NSLCORE)
ENDIF

LLSLCORE = ALLOCATED (YD%LSLCORE)
IF (LLSLCORE) THEN
  !$acc enter data create (YD%LSLCORE)
  !$acc update device (YD%LSLCORE)
  !$acc enter data attach (YD%LSLCORE)
ENDIF

LMASK_SLTOT = ALLOCATED (YD%MASK_SLTOT)
IF (LMASK_SLTOT) THEN
  !$acc enter data create (YD%MASK_SLTOT)
  !$acc update device (YD%MASK_SLTOT)
  !$acc enter data attach (YD%MASK_SLTOT)
ENDIF






















LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  !$acc enter data create (YD%NLOENG)
  !$acc update device (YD%NLOENG)
  !$acc enter data attach (YD%NLOENG)
ENDIF

END SUBROUTINE



END MODULE
