MODULE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VPRECIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_VPRECIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_VPRECIP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_VPRECIP (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP), INTENT (IN), TARGET :: YD
LOGICAL :: LF_PRECIP, LPPRECIP
LPPRECIP = ASSOCIATED (YD%PPRECIP)
WRITE (KLUN) LPPRECIP
IF (LPPRECIP) THEN
  WRITE (KLUN) LBOUND (YD%PPRECIP)
  WRITE (KLUN) UBOUND (YD%PPRECIP)
  WRITE (KLUN) YD%PPRECIP
ENDIF
LF_PRECIP = ASSOCIATED (YD%F_PRECIP)
WRITE (KLUN) LF_PRECIP
IF (LF_PRECIP) THEN
  CALL SAVE (KLUN, YD%F_PRECIP)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_VPRECIP (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LF_PRECIP, LPPRECIP
READ (KLUN) LPPRECIP
IF (LPPRECIP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%PPRECIP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%PPRECIP
ELSE
  NULLIFY (YD%PPRECIP)
ENDIF
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_PRECIP
IF (LF_PRECIP) THEN
  CALL LOAD (KLUN, YD%F_PRECIP)
ELSE
  NULLIFY (YD%F_PRECIP)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE






END MODULE
MODULE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VPRECIP2

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_VPRECIP2
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_VPRECIP2
END INTERFACE




CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_VPRECIP2 (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP2), INTENT (IN), TARGET :: YD
LOGICAL :: LF_PRECIP2, LPPRECIP2
LPPRECIP2 = ASSOCIATED (YD%PPRECIP2)
WRITE (KLUN) LPPRECIP2
IF (LPPRECIP2) THEN
  WRITE (KLUN) LBOUND (YD%PPRECIP2)
  WRITE (KLUN) UBOUND (YD%PPRECIP2)
  WRITE (KLUN) YD%PPRECIP2
ENDIF
LF_PRECIP2 = ASSOCIATED (YD%F_PRECIP2)
WRITE (KLUN) LF_PRECIP2
IF (LF_PRECIP2) THEN
  CALL SAVE (KLUN, YD%F_PRECIP2)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_VPRECIP2 (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_VPRECIP2), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LF_PRECIP2, LPPRECIP2
READ (KLUN) LPPRECIP2
IF (LPPRECIP2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%PPRECIP2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%PPRECIP2
ELSE
  NULLIFY (YD%PPRECIP2)
ENDIF
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_PRECIP2
IF (LF_PRECIP2) THEN
  CALL LOAD (KLUN, YD%F_PRECIP2)
ELSE
  NULLIFY (YD%F_PRECIP2)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE






END MODULE
