MODULE UTIL_SURFACE_VARIABLE_GROUP_RESVR_MOD

USE SURFACE_VARIABLES_MOD, ONLY : SURFACE_VARIABLE_GROUP_RESVR

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VARIABLE_GROUP_RESVR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VARIABLE_GROUP_RESVR
END INTERFACE




CONTAINS

SUBROUTINE SAVE_SURFACE_VARIABLE_GROUP_RESVR (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VARIABLE_GROUP_RESVR), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%VT)
CALL SAVE (KLUN, YD%VW)
CALL SAVE (KLUN, YD%VFC)
CALL SAVE (KLUN, YD%VIC)
CALL SAVE (KLUN, YD%VFP1)
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VARIABLE_GROUP_RESVR (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VARIABLE_GROUP_RESVR), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%VT)
CALL LOAD (KLUN, YD%VW)
CALL LOAD (KLUN, YD%VFC)
CALL LOAD (KLUN, YD%VIC)
CALL LOAD (KLUN, YD%VFP1)
NULLIFY (YD%F_GROUP)
END SUBROUTINE






END MODULE
