MODULE UTIL_TCHEM_MOD

USE YOMCHEM, ONLY : TCHEM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCHEM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCHEM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCHEM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCHEM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCHEM), INTENT (IN), TARGET :: YD
LOGICAL :: LTCO2DG, LTCOTOP
WRITE (KLUN) YD%CHEM_SCHEME
WRITE (KLUN) YD%LCHEM_DIAC
WRITE (KLUN) YD%LCHEM_BASCOE_JON
WRITE (KLUN) YD%LCHEM_JOUT
WRITE (KLUN) YD%LCHEM_LIGHT
WRITE (KLUN) YD%LCHEM_ACNOX
WRITE (KLUN) YD%KCHEM_NOXADV
WRITE (KLUN) YD%LCHEM_REVCHEM
WRITE (KLUN) YD%LCHEM_STMA
WRITE (KLUN) YD%LCHEM_ANAO3
WRITE (KLUN) YD%SMASSCOR
WRITE (KLUN) YD%LCHEM_0NOX
WRITE (KLUN) YD%LCHEM_ANACH4
WRITE (KLUN) YD%LCHEM_CONVSCAV
WRITE (KLUN) YD%LCHEM_CSHAPE
WRITE (KLUN) YD%LCHEM_WDFR
WRITE (KLUN) YD%LCHEM_HTAP
WRITE (KLUN) YD%KCHEM_YEARPI
WRITE (KLUN) YD%RCH4CONST
WRITE (KLUN) YD%KCHEM_SOLVE
WRITE (KLUN) YD%LCHEM_O3RAD
WRITE (KLUN) YD%LCHEM_DVOL
WRITE (KLUN) YD%LCHEM_AEROI
WRITE (KLUN) YD%IEXTR_FREE
WRITE (KLUN) YD%NUCOCH1
WRITE (KLUN) YD%NUCOCH2
WRITE (KLUN) YD%NCHEM_LCOCOEF
WRITE (KLUN) YD%CHEM_LCOVERS
WRITE (KLUN) YD%LCHEM_LCOMESO
WRITE (KLUN) YD%LCHEM_LCOCSTCLIM
WRITE (KLUN) YD%RCHEM_LCOTAUTOP
WRITE (KLUN) YD%RCHEM_LCOCLIMTOP
WRITE (KLUN) YD%LCHEM_LCOLIMIT
WRITE (KLUN) YD%RCHEM_LCOCOEFA1
WRITE (KLUN) YD%CSOLMET_ASIS
WRITE (KLUN) YD%M_SOLITER_ASIS
WRITE (KLUN) YD%SOLCV_ASIS
WRITE (KLUN) YD%RTOL_ASIS
WRITE (KLUN) YD%ATOL_ASIS
WRITE (KLUN) YD%N_F_RTOL_ASIS
WRITE (KLUN) YD%N_F_ATOL_ASIS
LTCO2DG = ALLOCATED (YD%TCO2DG)
WRITE (KLUN) LTCO2DG
IF (LTCO2DG) THEN
  WRITE (KLUN) LBOUND (YD%TCO2DG)
  WRITE (KLUN) UBOUND (YD%TCO2DG)
  WRITE (KLUN) YD%TCO2DG
ENDIF
LTCOTOP = ALLOCATED (YD%TCOTOP)
WRITE (KLUN) LTCOTOP
IF (LTCOTOP) THEN
  WRITE (KLUN) LBOUND (YD%TCOTOP)
  WRITE (KLUN) UBOUND (YD%TCOTOP)
  WRITE (KLUN) YD%TCOTOP
ENDIF
WRITE (KLUN) YD%LCHEM_ARPCLIM
END SUBROUTINE

SUBROUTINE LOAD_TCHEM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCHEM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LTCO2DG, LTCOTOP
READ (KLUN) YD%CHEM_SCHEME
READ (KLUN) YD%LCHEM_DIAC
READ (KLUN) YD%LCHEM_BASCOE_JON
READ (KLUN) YD%LCHEM_JOUT
READ (KLUN) YD%LCHEM_LIGHT
READ (KLUN) YD%LCHEM_ACNOX
READ (KLUN) YD%KCHEM_NOXADV
READ (KLUN) YD%LCHEM_REVCHEM
READ (KLUN) YD%LCHEM_STMA
READ (KLUN) YD%LCHEM_ANAO3
READ (KLUN) YD%SMASSCOR
READ (KLUN) YD%LCHEM_0NOX
READ (KLUN) YD%LCHEM_ANACH4
READ (KLUN) YD%LCHEM_CONVSCAV
READ (KLUN) YD%LCHEM_CSHAPE
READ (KLUN) YD%LCHEM_WDFR
READ (KLUN) YD%LCHEM_HTAP
READ (KLUN) YD%KCHEM_YEARPI
READ (KLUN) YD%RCH4CONST
READ (KLUN) YD%KCHEM_SOLVE
READ (KLUN) YD%LCHEM_O3RAD
READ (KLUN) YD%LCHEM_DVOL
READ (KLUN) YD%LCHEM_AEROI
READ (KLUN) YD%IEXTR_FREE
READ (KLUN) YD%NUCOCH1
READ (KLUN) YD%NUCOCH2
READ (KLUN) YD%NCHEM_LCOCOEF
READ (KLUN) YD%CHEM_LCOVERS
READ (KLUN) YD%LCHEM_LCOMESO
READ (KLUN) YD%LCHEM_LCOCSTCLIM
READ (KLUN) YD%RCHEM_LCOTAUTOP
READ (KLUN) YD%RCHEM_LCOCLIMTOP
READ (KLUN) YD%LCHEM_LCOLIMIT
READ (KLUN) YD%RCHEM_LCOCOEFA1
READ (KLUN) YD%CSOLMET_ASIS
READ (KLUN) YD%M_SOLITER_ASIS
READ (KLUN) YD%SOLCV_ASIS
READ (KLUN) YD%RTOL_ASIS
READ (KLUN) YD%ATOL_ASIS
READ (KLUN) YD%N_F_RTOL_ASIS
READ (KLUN) YD%N_F_ATOL_ASIS
READ (KLUN) LTCO2DG
IF (LTCO2DG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TCO2DG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TCO2DG
ENDIF
READ (KLUN) LTCOTOP
IF (LTCOTOP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%TCOTOP (IL1(1):IU1(1)))
  READ (KLUN) YD%TCOTOP
ENDIF
READ (KLUN) YD%LCHEM_ARPCLIM
END SUBROUTINE


SUBROUTINE COPY_TCHEM (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCHEM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LTCO2DG, LTCOTOP

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









































LTCO2DG = ALLOCATED (YD%TCO2DG)
IF (LTCO2DG) THEN
  !$acc enter data create (YD%TCO2DG)
  !$acc update device (YD%TCO2DG)
  !$acc enter data attach (YD%TCO2DG)
ENDIF

LTCOTOP = ALLOCATED (YD%TCOTOP)
IF (LTCOTOP) THEN
  !$acc enter data create (YD%TCOTOP)
  !$acc update device (YD%TCOTOP)
  !$acc enter data attach (YD%TCOTOP)
ENDIF


END SUBROUTINE



END MODULE
