MODULE UTIL_TVSPLIP_MOD

USE YOMVSPLIP, ONLY : TVSPLIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVSPLIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVSPLIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVSPLIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVSPLIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSPLIP), INTENT (IN), TARGET :: YD
LOGICAL :: LRFVV, LRVSPC, LRVSPTRI
LRVSPTRI = ALLOCATED (YD%RVSPTRI)
WRITE (KLUN) LRVSPTRI
IF (LRVSPTRI) THEN
  WRITE (KLUN) LBOUND (YD%RVSPTRI)
  WRITE (KLUN) UBOUND (YD%RVSPTRI)
  WRITE (KLUN) YD%RVSPTRI
ENDIF
LRVSPC = ALLOCATED (YD%RVSPC)
WRITE (KLUN) LRVSPC
IF (LRVSPC) THEN
  WRITE (KLUN) LBOUND (YD%RVSPC)
  WRITE (KLUN) UBOUND (YD%RVSPC)
  WRITE (KLUN) YD%RVSPC
ENDIF
LRFVV = ALLOCATED (YD%RFVV)
WRITE (KLUN) LRFVV
IF (LRFVV) THEN
  WRITE (KLUN) LBOUND (YD%RFVV)
  WRITE (KLUN) UBOUND (YD%RFVV)
  WRITE (KLUN) YD%RFVV
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVSPLIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSPLIP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LRFVV, LRVSPC, LRVSPTRI
READ (KLUN) LRVSPTRI
IF (LRVSPTRI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RVSPTRI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RVSPTRI
ENDIF
READ (KLUN) LRVSPC
IF (LRVSPC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVSPC (IL1(1):IU1(1)))
  READ (KLUN) YD%RVSPC
ENDIF
READ (KLUN) LRFVV
IF (LRFVV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RFVV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RFVV
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVSPLIP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TVSPLIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRFVV, LRVSPC, LRVSPTRI

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRVSPTRI = ALLOCATED (YD%RVSPTRI)
IF (LRVSPTRI) THEN
  !$acc enter data create (YD%RVSPTRI)
  !$acc update device (YD%RVSPTRI)
  !$acc enter data attach (YD%RVSPTRI)
ENDIF

LRVSPC = ALLOCATED (YD%RVSPC)
IF (LRVSPC) THEN
  !$acc enter data create (YD%RVSPC)
  !$acc update device (YD%RVSPC)
  !$acc enter data attach (YD%RVSPC)
ENDIF

LRFVV = ALLOCATED (YD%RFVV)
IF (LRFVV) THEN
  !$acc enter data create (YD%RFVV)
  !$acc update device (YD%RFVV)
  !$acc enter data attach (YD%RFVV)
ENDIF

END SUBROUTINE



END MODULE
