MODULE UTIL_TEWCOU_MOD

USE YOEWCOU, ONLY : TEWCOU

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEWCOU
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEWCOU
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEWCOU
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEWCOU
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEWCOU (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEWCOU), INTENT (IN), TARGET :: YD
LOGICAL :: LIWV_LAT, LIWV_LON, LMASK_WAVE_IN, LMASK_WAVE_OUT, LMWVIN_RECVBUF, LMWVIN_RECVCNT, LMWVIN_RECVOFF, LMWVIN_SENDBUF, LMWVIN_SENDCNT, LMWVIN_SENDIND
LOGICAL :: LMWVIN_SENDOFF, LWV_W2IWGHT
WRITE (KLUN) YD%NATMFLX
WRITE (KLUN) YD%NLONW
WRITE (KLUN) YD%NLATW
WRITE (KLUN) YD%NLON1W
WRITE (KLUN) YD%NLAT1W
WRITE (KLUN) YD%NNORXW
WRITE (KLUN) YD%NSTPW
WRITE (KLUN) YD%NGRIB_HANDLE_FOR_WAM
WRITE (KLUN) YD%RSOUTW
WRITE (KLUN) YD%RNORTW
WRITE (KLUN) YD%RDEGREW
WRITE (KLUN) YD%RMISSW
WRITE (KLUN) YD%LWCOU
WRITE (KLUN) YD%LWCOU2W
WRITE (KLUN) YD%LWCOUNORMS
WRITE (KLUN) YD%LWCUR
WRITE (KLUN) YD%LWSTOKES
WRITE (KLUN) YD%LWFLUX
WRITE (KLUN) YD%CBEGDAT
LMASK_WAVE_IN = ALLOCATED (YD%MASK_WAVE_IN)
WRITE (KLUN) LMASK_WAVE_IN
IF (LMASK_WAVE_IN) THEN
  WRITE (KLUN) LBOUND (YD%MASK_WAVE_IN)
  WRITE (KLUN) UBOUND (YD%MASK_WAVE_IN)
  WRITE (KLUN) YD%MASK_WAVE_IN
ENDIF
LMASK_WAVE_OUT = ALLOCATED (YD%MASK_WAVE_OUT)
WRITE (KLUN) LMASK_WAVE_OUT
IF (LMASK_WAVE_OUT) THEN
  WRITE (KLUN) LBOUND (YD%MASK_WAVE_OUT)
  WRITE (KLUN) UBOUND (YD%MASK_WAVE_OUT)
  WRITE (KLUN) YD%MASK_WAVE_OUT
ENDIF
WRITE (KLUN) YD%LWVIN_MASK_NOT_SET
WRITE (KLUN) YD%LWVOUT_MASK_NOT_SET
WRITE (KLUN) YD%LWVIN_UNINITIALISED
WRITE (KLUN) YD%MWVIN_SENDTOT
WRITE (KLUN) YD%MWVIN_RECVTOT
LMWVIN_SENDCNT = ALLOCATED (YD%MWVIN_SENDCNT)
WRITE (KLUN) LMWVIN_SENDCNT
IF (LMWVIN_SENDCNT) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_SENDCNT)
  WRITE (KLUN) UBOUND (YD%MWVIN_SENDCNT)
  WRITE (KLUN) YD%MWVIN_SENDCNT
ENDIF
LMWVIN_RECVCNT = ALLOCATED (YD%MWVIN_RECVCNT)
WRITE (KLUN) LMWVIN_RECVCNT
IF (LMWVIN_RECVCNT) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_RECVCNT)
  WRITE (KLUN) UBOUND (YD%MWVIN_RECVCNT)
  WRITE (KLUN) YD%MWVIN_RECVCNT
ENDIF
LMWVIN_SENDOFF = ALLOCATED (YD%MWVIN_SENDOFF)
WRITE (KLUN) LMWVIN_SENDOFF
IF (LMWVIN_SENDOFF) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_SENDOFF)
  WRITE (KLUN) UBOUND (YD%MWVIN_SENDOFF)
  WRITE (KLUN) YD%MWVIN_SENDOFF
ENDIF
LMWVIN_RECVOFF = ALLOCATED (YD%MWVIN_RECVOFF)
WRITE (KLUN) LMWVIN_RECVOFF
IF (LMWVIN_RECVOFF) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_RECVOFF)
  WRITE (KLUN) UBOUND (YD%MWVIN_RECVOFF)
  WRITE (KLUN) YD%MWVIN_RECVOFF
ENDIF
LMWVIN_SENDBUF = ALLOCATED (YD%MWVIN_SENDBUF)
WRITE (KLUN) LMWVIN_SENDBUF
IF (LMWVIN_SENDBUF) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_SENDBUF)
  WRITE (KLUN) UBOUND (YD%MWVIN_SENDBUF)
  WRITE (KLUN) YD%MWVIN_SENDBUF
ENDIF
LMWVIN_RECVBUF = ALLOCATED (YD%MWVIN_RECVBUF)
WRITE (KLUN) LMWVIN_RECVBUF
IF (LMWVIN_RECVBUF) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_RECVBUF)
  WRITE (KLUN) UBOUND (YD%MWVIN_RECVBUF)
  WRITE (KLUN) YD%MWVIN_RECVBUF
ENDIF
LMWVIN_SENDIND = ALLOCATED (YD%MWVIN_SENDIND)
WRITE (KLUN) LMWVIN_SENDIND
IF (LMWVIN_SENDIND) THEN
  WRITE (KLUN) LBOUND (YD%MWVIN_SENDIND)
  WRITE (KLUN) UBOUND (YD%MWVIN_SENDIND)
  WRITE (KLUN) YD%MWVIN_SENDIND
ENDIF
WRITE (KLUN) YD%LWFRSTIME
WRITE (KLUN) YD%LWINIT
WRITE (KLUN) YD%NADV_WAVE
WRITE (KLUN) YD%NWV_W2IWGHT
LIWV_LON = ALLOCATED (YD%IWV_LON)
WRITE (KLUN) LIWV_LON
IF (LIWV_LON) THEN
  WRITE (KLUN) LBOUND (YD%IWV_LON)
  WRITE (KLUN) UBOUND (YD%IWV_LON)
  WRITE (KLUN) YD%IWV_LON
ENDIF
LIWV_LAT = ALLOCATED (YD%IWV_LAT)
WRITE (KLUN) LIWV_LAT
IF (LIWV_LAT) THEN
  WRITE (KLUN) LBOUND (YD%IWV_LAT)
  WRITE (KLUN) UBOUND (YD%IWV_LAT)
  WRITE (KLUN) YD%IWV_LAT
ENDIF
LWV_W2IWGHT = ALLOCATED (YD%WV_W2IWGHT)
WRITE (KLUN) LWV_W2IWGHT
IF (LWV_W2IWGHT) THEN
  WRITE (KLUN) LBOUND (YD%WV_W2IWGHT)
  WRITE (KLUN) UBOUND (YD%WV_W2IWGHT)
  WRITE (KLUN) YD%WV_W2IWGHT
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TEWCOU (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEWCOU), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LIWV_LAT, LIWV_LON, LMASK_WAVE_IN, LMASK_WAVE_OUT, LMWVIN_RECVBUF, LMWVIN_RECVCNT, LMWVIN_RECVOFF, LMWVIN_SENDBUF, LMWVIN_SENDCNT, LMWVIN_SENDIND
LOGICAL :: LMWVIN_SENDOFF, LWV_W2IWGHT
READ (KLUN) YD%NATMFLX
READ (KLUN) YD%NLONW
READ (KLUN) YD%NLATW
READ (KLUN) YD%NLON1W
READ (KLUN) YD%NLAT1W
READ (KLUN) YD%NNORXW
READ (KLUN) YD%NSTPW
READ (KLUN) YD%NGRIB_HANDLE_FOR_WAM
READ (KLUN) YD%RSOUTW
READ (KLUN) YD%RNORTW
READ (KLUN) YD%RDEGREW
READ (KLUN) YD%RMISSW
READ (KLUN) YD%LWCOU
READ (KLUN) YD%LWCOU2W
READ (KLUN) YD%LWCOUNORMS
READ (KLUN) YD%LWCUR
READ (KLUN) YD%LWSTOKES
READ (KLUN) YD%LWFLUX
READ (KLUN) YD%CBEGDAT
READ (KLUN) LMASK_WAVE_IN
IF (LMASK_WAVE_IN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_WAVE_IN (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_WAVE_IN
ENDIF
READ (KLUN) LMASK_WAVE_OUT
IF (LMASK_WAVE_OUT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASK_WAVE_OUT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%MASK_WAVE_OUT
ENDIF
READ (KLUN) YD%LWVIN_MASK_NOT_SET
READ (KLUN) YD%LWVOUT_MASK_NOT_SET
READ (KLUN) YD%LWVIN_UNINITIALISED
READ (KLUN) YD%MWVIN_SENDTOT
READ (KLUN) YD%MWVIN_RECVTOT
READ (KLUN) LMWVIN_SENDCNT
IF (LMWVIN_SENDCNT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_SENDCNT (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_SENDCNT
ENDIF
READ (KLUN) LMWVIN_RECVCNT
IF (LMWVIN_RECVCNT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_RECVCNT (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_RECVCNT
ENDIF
READ (KLUN) LMWVIN_SENDOFF
IF (LMWVIN_SENDOFF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_SENDOFF (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_SENDOFF
ENDIF
READ (KLUN) LMWVIN_RECVOFF
IF (LMWVIN_RECVOFF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_RECVOFF (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_RECVOFF
ENDIF
READ (KLUN) LMWVIN_SENDBUF
IF (LMWVIN_SENDBUF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_SENDBUF (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_SENDBUF
ENDIF
READ (KLUN) LMWVIN_RECVBUF
IF (LMWVIN_RECVBUF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_RECVBUF (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_RECVBUF
ENDIF
READ (KLUN) LMWVIN_SENDIND
IF (LMWVIN_SENDIND) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MWVIN_SENDIND (IL1(1):IU1(1)))
  READ (KLUN) YD%MWVIN_SENDIND
ENDIF
READ (KLUN) YD%LWFRSTIME
READ (KLUN) YD%LWINIT
READ (KLUN) YD%NADV_WAVE
READ (KLUN) YD%NWV_W2IWGHT
READ (KLUN) LIWV_LON
IF (LIWV_LON) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%IWV_LON (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%IWV_LON
ENDIF
READ (KLUN) LIWV_LAT
IF (LIWV_LAT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%IWV_LAT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%IWV_LAT
ENDIF
READ (KLUN) LWV_W2IWGHT
IF (LWV_W2IWGHT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%WV_W2IWGHT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%WV_W2IWGHT
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TEWCOU (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEWCOU), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LIWV_LAT, LIWV_LON, LMASK_WAVE_IN, LMASK_WAVE_OUT, LMWVIN_RECVBUF, LMWVIN_RECVCNT, LMWVIN_RECVOFF, LMWVIN_SENDBUF, LMWVIN_SENDCNT, LMWVIN_SENDIND
LOGICAL :: LMWVIN_SENDOFF, LWV_W2IWGHT

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF



















LMASK_WAVE_IN = ALLOCATED (YD%MASK_WAVE_IN)
IF (LMASK_WAVE_IN) THEN
  !$acc enter data create (YD%MASK_WAVE_IN)
  !$acc update device (YD%MASK_WAVE_IN)
  !$acc enter data attach (YD%MASK_WAVE_IN)
ENDIF

LMASK_WAVE_OUT = ALLOCATED (YD%MASK_WAVE_OUT)
IF (LMASK_WAVE_OUT) THEN
  !$acc enter data create (YD%MASK_WAVE_OUT)
  !$acc update device (YD%MASK_WAVE_OUT)
  !$acc enter data attach (YD%MASK_WAVE_OUT)
ENDIF






LMWVIN_SENDCNT = ALLOCATED (YD%MWVIN_SENDCNT)
IF (LMWVIN_SENDCNT) THEN
  !$acc enter data create (YD%MWVIN_SENDCNT)
  !$acc update device (YD%MWVIN_SENDCNT)
  !$acc enter data attach (YD%MWVIN_SENDCNT)
ENDIF

LMWVIN_RECVCNT = ALLOCATED (YD%MWVIN_RECVCNT)
IF (LMWVIN_RECVCNT) THEN
  !$acc enter data create (YD%MWVIN_RECVCNT)
  !$acc update device (YD%MWVIN_RECVCNT)
  !$acc enter data attach (YD%MWVIN_RECVCNT)
ENDIF

LMWVIN_SENDOFF = ALLOCATED (YD%MWVIN_SENDOFF)
IF (LMWVIN_SENDOFF) THEN
  !$acc enter data create (YD%MWVIN_SENDOFF)
  !$acc update device (YD%MWVIN_SENDOFF)
  !$acc enter data attach (YD%MWVIN_SENDOFF)
ENDIF

LMWVIN_RECVOFF = ALLOCATED (YD%MWVIN_RECVOFF)
IF (LMWVIN_RECVOFF) THEN
  !$acc enter data create (YD%MWVIN_RECVOFF)
  !$acc update device (YD%MWVIN_RECVOFF)
  !$acc enter data attach (YD%MWVIN_RECVOFF)
ENDIF

LMWVIN_SENDBUF = ALLOCATED (YD%MWVIN_SENDBUF)
IF (LMWVIN_SENDBUF) THEN
  !$acc enter data create (YD%MWVIN_SENDBUF)
  !$acc update device (YD%MWVIN_SENDBUF)
  !$acc enter data attach (YD%MWVIN_SENDBUF)
ENDIF

LMWVIN_RECVBUF = ALLOCATED (YD%MWVIN_RECVBUF)
IF (LMWVIN_RECVBUF) THEN
  !$acc enter data create (YD%MWVIN_RECVBUF)
  !$acc update device (YD%MWVIN_RECVBUF)
  !$acc enter data attach (YD%MWVIN_RECVBUF)
ENDIF

LMWVIN_SENDIND = ALLOCATED (YD%MWVIN_SENDIND)
IF (LMWVIN_SENDIND) THEN
  !$acc enter data create (YD%MWVIN_SENDIND)
  !$acc update device (YD%MWVIN_SENDIND)
  !$acc enter data attach (YD%MWVIN_SENDIND)
ENDIF





LIWV_LON = ALLOCATED (YD%IWV_LON)
IF (LIWV_LON) THEN
  !$acc enter data create (YD%IWV_LON)
  !$acc update device (YD%IWV_LON)
  !$acc enter data attach (YD%IWV_LON)
ENDIF

LIWV_LAT = ALLOCATED (YD%IWV_LAT)
IF (LIWV_LAT) THEN
  !$acc enter data create (YD%IWV_LAT)
  !$acc update device (YD%IWV_LAT)
  !$acc enter data attach (YD%IWV_LAT)
ENDIF

LWV_W2IWGHT = ALLOCATED (YD%WV_W2IWGHT)
IF (LWV_W2IWGHT) THEN
  !$acc enter data create (YD%WV_W2IWGHT)
  !$acc update device (YD%WV_W2IWGHT)
  !$acc enter data attach (YD%WV_W2IWGHT)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TEWCOU (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEWCOU), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LIWV_LAT, LIWV_LON, LMASK_WAVE_IN, LMASK_WAVE_OUT, LMWVIN_RECVBUF, LMWVIN_RECVCNT, LMWVIN_RECVOFF, LMWVIN_SENDBUF, LMWVIN_SENDCNT, LMWVIN_SENDIND
LOGICAL :: LMWVIN_SENDOFF, LWV_W2IWGHT




















LMASK_WAVE_IN = ALLOCATED (YD%MASK_WAVE_IN)
IF (LMASK_WAVE_IN) THEN
  !$acc exit data detach (YD%MASK_WAVE_IN)
  !$acc exit data delete (YD%MASK_WAVE_IN)
ENDIF

LMASK_WAVE_OUT = ALLOCATED (YD%MASK_WAVE_OUT)
IF (LMASK_WAVE_OUT) THEN
  !$acc exit data detach (YD%MASK_WAVE_OUT)
  !$acc exit data delete (YD%MASK_WAVE_OUT)
ENDIF






LMWVIN_SENDCNT = ALLOCATED (YD%MWVIN_SENDCNT)
IF (LMWVIN_SENDCNT) THEN
  !$acc exit data detach (YD%MWVIN_SENDCNT)
  !$acc exit data delete (YD%MWVIN_SENDCNT)
ENDIF

LMWVIN_RECVCNT = ALLOCATED (YD%MWVIN_RECVCNT)
IF (LMWVIN_RECVCNT) THEN
  !$acc exit data detach (YD%MWVIN_RECVCNT)
  !$acc exit data delete (YD%MWVIN_RECVCNT)
ENDIF

LMWVIN_SENDOFF = ALLOCATED (YD%MWVIN_SENDOFF)
IF (LMWVIN_SENDOFF) THEN
  !$acc exit data detach (YD%MWVIN_SENDOFF)
  !$acc exit data delete (YD%MWVIN_SENDOFF)
ENDIF

LMWVIN_RECVOFF = ALLOCATED (YD%MWVIN_RECVOFF)
IF (LMWVIN_RECVOFF) THEN
  !$acc exit data detach (YD%MWVIN_RECVOFF)
  !$acc exit data delete (YD%MWVIN_RECVOFF)
ENDIF

LMWVIN_SENDBUF = ALLOCATED (YD%MWVIN_SENDBUF)
IF (LMWVIN_SENDBUF) THEN
  !$acc exit data detach (YD%MWVIN_SENDBUF)
  !$acc exit data delete (YD%MWVIN_SENDBUF)
ENDIF

LMWVIN_RECVBUF = ALLOCATED (YD%MWVIN_RECVBUF)
IF (LMWVIN_RECVBUF) THEN
  !$acc exit data detach (YD%MWVIN_RECVBUF)
  !$acc exit data delete (YD%MWVIN_RECVBUF)
ENDIF

LMWVIN_SENDIND = ALLOCATED (YD%MWVIN_SENDIND)
IF (LMWVIN_SENDIND) THEN
  !$acc exit data detach (YD%MWVIN_SENDIND)
  !$acc exit data delete (YD%MWVIN_SENDIND)
ENDIF





LIWV_LON = ALLOCATED (YD%IWV_LON)
IF (LIWV_LON) THEN
  !$acc exit data detach (YD%IWV_LON)
  !$acc exit data delete (YD%IWV_LON)
ENDIF

LIWV_LAT = ALLOCATED (YD%IWV_LAT)
IF (LIWV_LAT) THEN
  !$acc exit data detach (YD%IWV_LAT)
  !$acc exit data delete (YD%IWV_LAT)
ENDIF

LWV_W2IWGHT = ALLOCATED (YD%WV_W2IWGHT)
IF (LWV_W2IWGHT) THEN
  !$acc exit data detach (YD%WV_W2IWGHT)
  !$acc exit data delete (YD%WV_W2IWGHT)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
