MODULE UTIL_TEMMP_MOD

USE YEMMP, ONLY : TEMMP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEMMP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEMMP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEMMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEMMP), INTENT (IN), TARGET :: YD
LOGICAL :: LMYENS, LNEALLNS, LNEPROCN, LNEPTRNS, LNUEMPP
LNEPROCN = ASSOCIATED (YD%NEPROCN)
WRITE (KLUN) LNEPROCN
IF (LNEPROCN) THEN
  WRITE (KLUN) LBOUND (YD%NEPROCN)
  WRITE (KLUN) UBOUND (YD%NEPROCN)
  WRITE (KLUN) YD%NEPROCN
ENDIF
WRITE (KLUN) YD%NUEMP
LMYENS = ASSOCIATED (YD%MYENS)
WRITE (KLUN) LMYENS
IF (LMYENS) THEN
  WRITE (KLUN) LBOUND (YD%MYENS)
  WRITE (KLUN) UBOUND (YD%MYENS)
  WRITE (KLUN) YD%MYENS
ENDIF
LNUEMPP = ASSOCIATED (YD%NUEMPP)
WRITE (KLUN) LNUEMPP
IF (LNUEMPP) THEN
  WRITE (KLUN) LBOUND (YD%NUEMPP)
  WRITE (KLUN) UBOUND (YD%NUEMPP)
  WRITE (KLUN) YD%NUEMPP
ENDIF
LNEALLNS = ASSOCIATED (YD%NEALLNS)
WRITE (KLUN) LNEALLNS
IF (LNEALLNS) THEN
  WRITE (KLUN) LBOUND (YD%NEALLNS)
  WRITE (KLUN) UBOUND (YD%NEALLNS)
  WRITE (KLUN) YD%NEALLNS
ENDIF
LNEPTRNS = ASSOCIATED (YD%NEPTRNS)
WRITE (KLUN) LNEPTRNS
IF (LNEPTRNS) THEN
  WRITE (KLUN) LBOUND (YD%NEPTRNS)
  WRITE (KLUN) UBOUND (YD%NEPTRNS)
  WRITE (KLUN) YD%NEPTRNS
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TEMMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEMMP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMYENS, LNEALLNS, LNEPROCN, LNEPTRNS, LNUEMPP
READ (KLUN) LNEPROCN
IF (LNEPROCN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NEPROCN (IL1(1):IU1(1)))
  READ (KLUN) YD%NEPROCN
ELSE
  NULLIFY (YD%NEPROCN)
ENDIF
READ (KLUN) YD%NUEMP
READ (KLUN) LMYENS
IF (LMYENS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYENS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYENS
ELSE
  NULLIFY (YD%MYENS)
ENDIF
READ (KLUN) LNUEMPP
IF (LNUEMPP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUEMPP (IL1(1):IU1(1)))
  READ (KLUN) YD%NUEMPP
ELSE
  NULLIFY (YD%NUEMPP)
ENDIF
READ (KLUN) LNEALLNS
IF (LNEALLNS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NEALLNS (IL1(1):IU1(1)))
  READ (KLUN) YD%NEALLNS
ELSE
  NULLIFY (YD%NEALLNS)
ENDIF
READ (KLUN) LNEPTRNS
IF (LNEPTRNS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NEPTRNS (IL1(1):IU1(1)))
  READ (KLUN) YD%NEPTRNS
ELSE
  NULLIFY (YD%NEPTRNS)
ENDIF
END SUBROUTINE






END MODULE
