MODULE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD

USE MODEL_PHYSICS_ECMWF_MOD, ONLY : MODEL_PHYSICS_ECMWF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_ECMWF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_ECMWF_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_ECMWF_TYPE (KLUN, YD)
USE UTIL_TECLDP_MOD
USE UTIL_TECLD_MOD
USE UTIL_TECND_MOD
USE UTIL_TECUCONVCA_MOD
USE UTIL_TECUMF_MOD
USE UTIL_TEGWD_MOD
USE UTIL_TEGWWMS_MOD
USE UTIL_TEPHY_MOD
USE UTIL_TTHF_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YREPHY)
CALL SAVE (KLUN, YD%YRECLD)
CALL SAVE (KLUN, YD%YRECLDP)
CALL SAVE (KLUN, YD%YRECND)
CALL SAVE (KLUN, YD%YRECUMF)
CALL SAVE (KLUN, YD%YRECUCONVCA)
CALL SAVE (KLUN, YD%YREGWD)
CALL SAVE (KLUN, YD%YREGWWMS)
CALL SAVE (KLUN, YD%YRTHF)
END SUBROUTINE
SUBROUTINE LOAD_MODEL_PHYSICS_ECMWF_TYPE (KLUN, YD)
USE UTIL_TECLDP_MOD
USE UTIL_TECLD_MOD
USE UTIL_TECND_MOD
USE UTIL_TECUCONVCA_MOD
USE UTIL_TECUMF_MOD
USE UTIL_TEGWD_MOD
USE UTIL_TEGWWMS_MOD
USE UTIL_TEPHY_MOD
USE UTIL_TTHF_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YREPHY)
CALL LOAD (KLUN, YD%YRECLD)
CALL LOAD (KLUN, YD%YRECLDP)
CALL LOAD (KLUN, YD%YRECND)
CALL LOAD (KLUN, YD%YRECUMF)
CALL LOAD (KLUN, YD%YRECUCONVCA)
CALL LOAD (KLUN, YD%YREGWD)
CALL LOAD (KLUN, YD%YREGWWMS)
CALL LOAD (KLUN, YD%YRTHF)
END SUBROUTINE




END MODULE
