MODULE UTIL_VARIABLE_2D_MOD

USE VARIABLE_MODULE, ONLY : VARIABLE_2D

INTERFACE SAVE
MODULE PROCEDURE SAVE_VARIABLE_2D
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_VARIABLE_2D
END INTERFACE




CONTAINS

SUBROUTINE SAVE_VARIABLE_2D (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_VARIABLE_BASE_MOD, ONLY : VARIABLE_BASE, SAVE_VARIABLE_BASE
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (VARIABLE_2D), INTENT (IN), TARGET :: YD
CLASS (VARIABLE_BASE), POINTER :: YLSUPER
LOGICAL :: LFDL, LFDL9, LFDM, LFDM9, LFPH9, LFT0, LFT1, LFT9
YLSUPER => YD
CALL SAVE_VARIABLE_BASE (KLUN, YLSUPER)
LFT0 = ASSOCIATED (YD%FT0)
WRITE (KLUN) LFT0
IF (LFT0) THEN
  CALL SAVE (KLUN, YD%FT0)
ENDIF
LFT1 = ASSOCIATED (YD%FT1)
WRITE (KLUN) LFT1
IF (LFT1) THEN
  CALL SAVE (KLUN, YD%FT1)
ENDIF
LFT9 = ASSOCIATED (YD%FT9)
WRITE (KLUN) LFT9
IF (LFT9) THEN
  CALL SAVE (KLUN, YD%FT9)
ENDIF
LFPH9 = ASSOCIATED (YD%FPH9)
WRITE (KLUN) LFPH9
IF (LFPH9) THEN
  CALL SAVE (KLUN, YD%FPH9)
ENDIF
LFDL = ASSOCIATED (YD%FDL)
WRITE (KLUN) LFDL
IF (LFDL) THEN
  CALL SAVE (KLUN, YD%FDL)
ENDIF
LFDM = ASSOCIATED (YD%FDM)
WRITE (KLUN) LFDM
IF (LFDM) THEN
  CALL SAVE (KLUN, YD%FDM)
ENDIF
LFDL9 = ASSOCIATED (YD%FDL9)
WRITE (KLUN) LFDL9
IF (LFDL9) THEN
  CALL SAVE (KLUN, YD%FDL9)
ENDIF
LFDM9 = ASSOCIATED (YD%FDM9)
WRITE (KLUN) LFDM9
IF (LFDM9) THEN
  CALL SAVE (KLUN, YD%FDM9)
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_VARIABLE_2D (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_VARIABLE_BASE_MOD, ONLY : VARIABLE_BASE, LOAD_VARIABLE_BASE

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (VARIABLE_2D), INTENT (OUT), TARGET :: YD
CLASS (VARIABLE_BASE), POINTER :: YLSUPER
LOGICAL :: LFDL, LFDL9, LFDM, LFDM9, LFPH9, LFT0, LFT1, LFT9
YLSUPER => YD
CALL LOAD_VARIABLE_BASE (KLUN, YLSUPER)
NULLIFY (YD%P)
NULLIFY (YD%T0)
NULLIFY (YD%T1)
NULLIFY (YD%T9)
NULLIFY (YD%PH9)
NULLIFY (YD%DL)
NULLIFY (YD%DM)
NULLIFY (YD%DL9)
NULLIFY (YD%DM9)
READ (KLUN) LFT0
IF (LFT0) THEN
  CALL LOAD (KLUN, YD%FT0)
ELSE
  NULLIFY (YD%FT0)
ENDIF
READ (KLUN) LFT1
IF (LFT1) THEN
  CALL LOAD (KLUN, YD%FT1)
ELSE
  NULLIFY (YD%FT1)
ENDIF
READ (KLUN) LFT9
IF (LFT9) THEN
  CALL LOAD (KLUN, YD%FT9)
ELSE
  NULLIFY (YD%FT9)
ENDIF
READ (KLUN) LFPH9
IF (LFPH9) THEN
  CALL LOAD (KLUN, YD%FPH9)
ELSE
  NULLIFY (YD%FPH9)
ENDIF
READ (KLUN) LFDL
IF (LFDL) THEN
  CALL LOAD (KLUN, YD%FDL)
ELSE
  NULLIFY (YD%FDL)
ENDIF
READ (KLUN) LFDM
IF (LFDM) THEN
  CALL LOAD (KLUN, YD%FDM)
ELSE
  NULLIFY (YD%FDM)
ENDIF
READ (KLUN) LFDL9
IF (LFDL9) THEN
  CALL LOAD (KLUN, YD%FDL9)
ELSE
  NULLIFY (YD%FDL9)
ENDIF
READ (KLUN) LFDM9
IF (LFDM9) THEN
  CALL LOAD (KLUN, YD%FDM9)
ELSE
  NULLIFY (YD%FDM9)
ENDIF
END SUBROUTINE




END MODULE
