MODULE UTIL_TPHY3_MOD

USE YOMPHY3, ONLY : TPHY3

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHY3
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY3
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TPHY3 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY3), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%N_SPBAND
WRITE (KLUN) YD%RTL
WRITE (KLUN) YD%BSFSA
WRITE (KLUN) YD%BSFSI
WRITE (KLUN) YD%BSFSN
WRITE (KLUN) YD%BSFTA
WRITE (KLUN) YD%BSFTI
WRITE (KLUN) YD%BSFTN
WRITE (KLUN) YD%EARRT
WRITE (KLUN) YD%EOASA
WRITE (KLUN) YD%EOASI
WRITE (KLUN) YD%EOASN
WRITE (KLUN) YD%EOATA
WRITE (KLUN) YD%EOATI
WRITE (KLUN) YD%EOATN
WRITE (KLUN) YD%EODSA
WRITE (KLUN) YD%EODSI
WRITE (KLUN) YD%EODSN
WRITE (KLUN) YD%EODTA
WRITE (KLUN) YD%EODTI
WRITE (KLUN) YD%EODTN
WRITE (KLUN) YD%EORAY
WRITE (KLUN) YD%GCA
WRITE (KLUN) YD%GCB
WRITE (KLUN) YD%GCC
WRITE (KLUN) YD%GCD4
WRITE (KLUN) YD%GCE4
WRITE (KLUN) YD%GIREC1
WRITE (KLUN) YD%GIREC2
WRITE (KLUN) YD%GIREC3
WRITE (KLUN) YD%GIREC4
WRITE (KLUN) YD%QCO2
WRITE (KLUN) YD%RII0
WRITE (KLUN) YD%USAA
WRITE (KLUN) YD%USAI
WRITE (KLUN) YD%USAN
WRITE (KLUN) YD%USBA
WRITE (KLUN) YD%USBI
WRITE (KLUN) YD%USBN
WRITE (KLUN) YD%VDP
WRITE (KLUN) YD%VNP
WRITE (KLUN) YD%REXP_NEB
WRITE (KLUN) YD%FCM_DEL_A
WRITE (KLUN) YD%FCM_DEL_D
WRITE (KLUN) YD%FCM_MU_A
WRITE (KLUN) YD%FCM_MU_D
WRITE (KLUN) YD%FCM_N_I
WRITE (KLUN) YD%FCM_N_L
WRITE (KLUN) YD%FCM_AI
WRITE (KLUN) YD%FCM_AL
WRITE (KLUN) YD%FCM_B_AI
WRITE (KLUN) YD%FCM_B_AL
WRITE (KLUN) YD%FCM_B_BI
WRITE (KLUN) YD%FCM_B_BL
WRITE (KLUN) YD%FCM_DEL_AI
WRITE (KLUN) YD%FCM_DEL_AL
WRITE (KLUN) YD%FCM_DEL_DI
WRITE (KLUN) YD%FCM_DEL_DL
WRITE (KLUN) YD%FCM_MU_AI
WRITE (KLUN) YD%FCM_MU_AL
WRITE (KLUN) YD%FCM_MU_DI
WRITE (KLUN) YD%FCM_MU_DL
WRITE (KLUN) YD%FCM_NU_AI
WRITE (KLUN) YD%FCM_NU_AL
WRITE (KLUN) YD%FCM_NU_DI
WRITE (KLUN) YD%FCM_NU_DL
WRITE (KLUN) YD%FCM_IWC2DE
WRITE (KLUN) YD%FCM_LWC2RE
WRITE (KLUN) YD%FCM_P_AI
WRITE (KLUN) YD%FCM_P_AL
WRITE (KLUN) YD%FCM_P_DI
WRITE (KLUN) YD%FCM_P_DL
WRITE (KLUN) YD%FCM_P_GI
WRITE (KLUN) YD%FCM_P_GL
WRITE (KLUN) YD%FCM_Q_AI
WRITE (KLUN) YD%FCM_Q_AL
WRITE (KLUN) YD%FCM_Q_DI
WRITE (KLUN) YD%FCM_Q_DL
WRITE (KLUN) YD%FCM_Q_GI
WRITE (KLUN) YD%FCM_Q_GL
WRITE (KLUN) YD%FSM_AA
WRITE (KLUN) YD%FSM_BB
WRITE (KLUN) YD%FSM_CC
WRITE (KLUN) YD%FSM_DD
WRITE (KLUN) YD%FSM_EE
WRITE (KLUN) YD%FSM_FF
WRITE (KLUN) YD%FSM_GG
WRITE (KLUN) YD%FSM_HH
WRITE (KLUN) YD%FSM_II
WRITE (KLUN) YD%GOLCA
WRITE (KLUN) YD%GOLCB
WRITE (KLUN) YD%GOLCC
WRITE (KLUN) YD%FGTS_A
WRITE (KLUN) YD%FGTS_B
WRITE (KLUN) YD%FGTS_C
WRITE (KLUN) YD%FGTS_ALPHA
WRITE (KLUN) YD%FGTS_DELTA0
WRITE (KLUN) YD%FGTS_D
WRITE (KLUN) YD%FGTS_P00
WRITE (KLUN) YD%FGTS_P
WRITE (KLUN) YD%FGTS_Q
WRITE (KLUN) YD%FGTS_OA
WRITE (KLUN) YD%FGTS_OB
WRITE (KLUN) YD%FGTS_OC
WRITE (KLUN) YD%FGTS_OD
WRITE (KLUN) YD%FGTC_A
WRITE (KLUN) YD%FGTC_B
WRITE (KLUN) YD%FGTC_C
WRITE (KLUN) YD%FGTC_ALPHA
WRITE (KLUN) YD%FGTC_DELTA0
WRITE (KLUN) YD%FGTC_D
WRITE (KLUN) YD%FGTC_P00
WRITE (KLUN) YD%FGTC_P
WRITE (KLUN) YD%FGTC_Q
WRITE (KLUN) YD%FGTC_OA
WRITE (KLUN) YD%FGTC_OB
WRITE (KLUN) YD%FGTC_OC
WRITE (KLUN) YD%FGTC_OD
WRITE (KLUN) YD%FGTT_A
WRITE (KLUN) YD%FGTT_B
WRITE (KLUN) YD%FGTT_C
WRITE (KLUN) YD%FGTT_ALPHA
WRITE (KLUN) YD%FGTT_DELTA0
WRITE (KLUN) YD%FGTT_D
WRITE (KLUN) YD%FGTT_P00
WRITE (KLUN) YD%FGTT_P
WRITE (KLUN) YD%FGTT_Q
WRITE (KLUN) YD%FGTT_OA
WRITE (KLUN) YD%FGTT_OB
WRITE (KLUN) YD%FGTT_OC
WRITE (KLUN) YD%FGTT_OD
WRITE (KLUN) YD%FRS_K_SCAT0
WRITE (KLUN) YD%FRS_P_CRIT
WRITE (KLUN) YD%FRS_BETA
WRITE (KLUN) YD%RLAMB_SOLID
WRITE (KLUN) YD%RLAMB_WATER
WRITE (KLUN) YD%RMIXD
WRITE (KLUN) YD%RMIXP0
END SUBROUTINE
SUBROUTINE LOAD_TPHY3 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY3), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%N_SPBAND
READ (KLUN) YD%RTL
READ (KLUN) YD%BSFSA
READ (KLUN) YD%BSFSI
READ (KLUN) YD%BSFSN
READ (KLUN) YD%BSFTA
READ (KLUN) YD%BSFTI
READ (KLUN) YD%BSFTN
READ (KLUN) YD%EARRT
READ (KLUN) YD%EOASA
READ (KLUN) YD%EOASI
READ (KLUN) YD%EOASN
READ (KLUN) YD%EOATA
READ (KLUN) YD%EOATI
READ (KLUN) YD%EOATN
READ (KLUN) YD%EODSA
READ (KLUN) YD%EODSI
READ (KLUN) YD%EODSN
READ (KLUN) YD%EODTA
READ (KLUN) YD%EODTI
READ (KLUN) YD%EODTN
READ (KLUN) YD%EORAY
READ (KLUN) YD%GCA
READ (KLUN) YD%GCB
READ (KLUN) YD%GCC
READ (KLUN) YD%GCD4
READ (KLUN) YD%GCE4
READ (KLUN) YD%GIREC1
READ (KLUN) YD%GIREC2
READ (KLUN) YD%GIREC3
READ (KLUN) YD%GIREC4
READ (KLUN) YD%QCO2
READ (KLUN) YD%RII0
READ (KLUN) YD%USAA
READ (KLUN) YD%USAI
READ (KLUN) YD%USAN
READ (KLUN) YD%USBA
READ (KLUN) YD%USBI
READ (KLUN) YD%USBN
READ (KLUN) YD%VDP
READ (KLUN) YD%VNP
READ (KLUN) YD%REXP_NEB
READ (KLUN) YD%FCM_DEL_A
READ (KLUN) YD%FCM_DEL_D
READ (KLUN) YD%FCM_MU_A
READ (KLUN) YD%FCM_MU_D
READ (KLUN) YD%FCM_N_I
READ (KLUN) YD%FCM_N_L
READ (KLUN) YD%FCM_AI
READ (KLUN) YD%FCM_AL
READ (KLUN) YD%FCM_B_AI
READ (KLUN) YD%FCM_B_AL
READ (KLUN) YD%FCM_B_BI
READ (KLUN) YD%FCM_B_BL
READ (KLUN) YD%FCM_DEL_AI
READ (KLUN) YD%FCM_DEL_AL
READ (KLUN) YD%FCM_DEL_DI
READ (KLUN) YD%FCM_DEL_DL
READ (KLUN) YD%FCM_MU_AI
READ (KLUN) YD%FCM_MU_AL
READ (KLUN) YD%FCM_MU_DI
READ (KLUN) YD%FCM_MU_DL
READ (KLUN) YD%FCM_NU_AI
READ (KLUN) YD%FCM_NU_AL
READ (KLUN) YD%FCM_NU_DI
READ (KLUN) YD%FCM_NU_DL
READ (KLUN) YD%FCM_IWC2DE
READ (KLUN) YD%FCM_LWC2RE
READ (KLUN) YD%FCM_P_AI
READ (KLUN) YD%FCM_P_AL
READ (KLUN) YD%FCM_P_DI
READ (KLUN) YD%FCM_P_DL
READ (KLUN) YD%FCM_P_GI
READ (KLUN) YD%FCM_P_GL
READ (KLUN) YD%FCM_Q_AI
READ (KLUN) YD%FCM_Q_AL
READ (KLUN) YD%FCM_Q_DI
READ (KLUN) YD%FCM_Q_DL
READ (KLUN) YD%FCM_Q_GI
READ (KLUN) YD%FCM_Q_GL
READ (KLUN) YD%FSM_AA
READ (KLUN) YD%FSM_BB
READ (KLUN) YD%FSM_CC
READ (KLUN) YD%FSM_DD
READ (KLUN) YD%FSM_EE
READ (KLUN) YD%FSM_FF
READ (KLUN) YD%FSM_GG
READ (KLUN) YD%FSM_HH
READ (KLUN) YD%FSM_II
READ (KLUN) YD%GOLCA
READ (KLUN) YD%GOLCB
READ (KLUN) YD%GOLCC
READ (KLUN) YD%FGTS_A
READ (KLUN) YD%FGTS_B
READ (KLUN) YD%FGTS_C
READ (KLUN) YD%FGTS_ALPHA
READ (KLUN) YD%FGTS_DELTA0
READ (KLUN) YD%FGTS_D
READ (KLUN) YD%FGTS_P00
READ (KLUN) YD%FGTS_P
READ (KLUN) YD%FGTS_Q
READ (KLUN) YD%FGTS_OA
READ (KLUN) YD%FGTS_OB
READ (KLUN) YD%FGTS_OC
READ (KLUN) YD%FGTS_OD
READ (KLUN) YD%FGTC_A
READ (KLUN) YD%FGTC_B
READ (KLUN) YD%FGTC_C
READ (KLUN) YD%FGTC_ALPHA
READ (KLUN) YD%FGTC_DELTA0
READ (KLUN) YD%FGTC_D
READ (KLUN) YD%FGTC_P00
READ (KLUN) YD%FGTC_P
READ (KLUN) YD%FGTC_Q
READ (KLUN) YD%FGTC_OA
READ (KLUN) YD%FGTC_OB
READ (KLUN) YD%FGTC_OC
READ (KLUN) YD%FGTC_OD
READ (KLUN) YD%FGTT_A
READ (KLUN) YD%FGTT_B
READ (KLUN) YD%FGTT_C
READ (KLUN) YD%FGTT_ALPHA
READ (KLUN) YD%FGTT_DELTA0
READ (KLUN) YD%FGTT_D
READ (KLUN) YD%FGTT_P00
READ (KLUN) YD%FGTT_P
READ (KLUN) YD%FGTT_Q
READ (KLUN) YD%FGTT_OA
READ (KLUN) YD%FGTT_OB
READ (KLUN) YD%FGTT_OC
READ (KLUN) YD%FGTT_OD
READ (KLUN) YD%FRS_K_SCAT0
READ (KLUN) YD%FRS_P_CRIT
READ (KLUN) YD%FRS_BETA
READ (KLUN) YD%RLAMB_SOLID
READ (KLUN) YD%RLAMB_WATER
READ (KLUN) YD%RMIXD
READ (KLUN) YD%RMIXP0
END SUBROUTINE




END MODULE
