MODULE UTIL_TCFU_MOD

USE YOMCFU_TYPE, ONLY : TCFU

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCFU
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCFU
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TCFU (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TCFU_KEYS_MOD, ONLY : TCFU_KEYS, SAVE_TCFU_KEYS
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCFU), INTENT (IN), TARGET :: YD
CLASS (TCFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_FCCQL, LF_FCCQN, LF_FCHSP, LF_FCL, LF_FCLL, LF_FCLN, LF_FCS, LF_FCSQL, LF_FCSQN, LF_FDICQ, LF_FDICS, LF_FDISH, LF_FDITQ, LF_FDITS, LF_FDUTP, LF_FEVL, LF_FEVN, LF_FEVV, LF_FGEL, LF_FGELS, LF_FLASH, LF_FLWSP, LF_FNEB, LF_FNEBT, LF_FONTE, LF_FPLCG, LF_FPLCH, LF_FPLCL, LF_FPLCN, LF_FPLSG, LF_FPLSH, LF_FPLSL, LF_FPLSN, LF_FRSDNI, LF_FRSGNI, LF_FRSO, LF_FRSOC0, LF_FRSOC1, LF_FRSODS, LF_FRSOLU, LF_FRSOPS, LF_FRSOPT, LF_FRTH, LF_FRTHC0, LF_FRTHC1, LF_FRTHDS, LF_FTOPH, LF_FTR, LF_NEBBAS, LF_NEBCON, LF_NEBHAU, LF_NEBMOY, LF_OZONT, LF_QICE, LF_QLI, LF_QTOT, LF_RUISL, LF_RUISP, LF_RUISS, LF_SNS, LF_SPRES, LF_STRCU, LF_STRCV, LF_STRDU, LF_STRDV, LF_STRTU, LF_STRTV, LF_WS
YLSUPER => YD
CALL SAVE_TCFU_KEYS (KLUN, YLSUPER)
WRITE (KLUN) YD%NCFUTS
WRITE (KLUN) YD%NFRRC
WRITE (KLUN) YD%NFRCFU
WRITE (KLUN) YD%NFDCFU
WRITE (KLUN) YD%NTYPCFU
WRITE (KLUN) YD%NMTFLASH
WRITE (KLUN) YD%CALFLASH1
WRITE (KLUN) YD%CALFLASH2
WRITE (KLUN) YD%LREACFU
LF_FCCQL = ASSOCIATED (YD%F_FCCQL)
WRITE (KLUN) LF_FCCQL
IF (LF_FCCQL) THEN
  CALL SAVE (KLUN, YD%F_FCCQL)
ENDIF
CALL SAVE (KLUN, YD%YFCCQL)
LF_FCCQN = ASSOCIATED (YD%F_FCCQN)
WRITE (KLUN) LF_FCCQN
IF (LF_FCCQN) THEN
  CALL SAVE (KLUN, YD%F_FCCQN)
ENDIF
CALL SAVE (KLUN, YD%YFCCQN)
LF_FCHSP = ASSOCIATED (YD%F_FCHSP)
WRITE (KLUN) LF_FCHSP
IF (LF_FCHSP) THEN
  CALL SAVE (KLUN, YD%F_FCHSP)
ENDIF
CALL SAVE (KLUN, YD%YFCHSP)
LF_FCL = ASSOCIATED (YD%F_FCL)
WRITE (KLUN) LF_FCL
IF (LF_FCL) THEN
  CALL SAVE (KLUN, YD%F_FCL)
ENDIF
CALL SAVE (KLUN, YD%YFCL)
LF_FCLL = ASSOCIATED (YD%F_FCLL)
WRITE (KLUN) LF_FCLL
IF (LF_FCLL) THEN
  CALL SAVE (KLUN, YD%F_FCLL)
ENDIF
CALL SAVE (KLUN, YD%YFCLL)
LF_FCLN = ASSOCIATED (YD%F_FCLN)
WRITE (KLUN) LF_FCLN
IF (LF_FCLN) THEN
  CALL SAVE (KLUN, YD%F_FCLN)
ENDIF
CALL SAVE (KLUN, YD%YFCLN)
LF_FCSQL = ASSOCIATED (YD%F_FCSQL)
WRITE (KLUN) LF_FCSQL
IF (LF_FCSQL) THEN
  CALL SAVE (KLUN, YD%F_FCSQL)
ENDIF
CALL SAVE (KLUN, YD%YFCSQL)
LF_FCSQN = ASSOCIATED (YD%F_FCSQN)
WRITE (KLUN) LF_FCSQN
IF (LF_FCSQN) THEN
  CALL SAVE (KLUN, YD%F_FCSQN)
ENDIF
CALL SAVE (KLUN, YD%YFCSQN)
LF_FCS = ASSOCIATED (YD%F_FCS)
WRITE (KLUN) LF_FCS
IF (LF_FCS) THEN
  CALL SAVE (KLUN, YD%F_FCS)
ENDIF
CALL SAVE (KLUN, YD%YFCS)
LF_FDICQ = ASSOCIATED (YD%F_FDICQ)
WRITE (KLUN) LF_FDICQ
IF (LF_FDICQ) THEN
  CALL SAVE (KLUN, YD%F_FDICQ)
ENDIF
CALL SAVE (KLUN, YD%YFDICQ)
LF_FDICS = ASSOCIATED (YD%F_FDICS)
WRITE (KLUN) LF_FDICS
IF (LF_FDICS) THEN
  CALL SAVE (KLUN, YD%F_FDICS)
ENDIF
CALL SAVE (KLUN, YD%YFDICS)
LF_FDISH = ASSOCIATED (YD%F_FDISH)
WRITE (KLUN) LF_FDISH
IF (LF_FDISH) THEN
  CALL SAVE (KLUN, YD%F_FDISH)
ENDIF
CALL SAVE (KLUN, YD%YFDISH)
LF_FDITQ = ASSOCIATED (YD%F_FDITQ)
WRITE (KLUN) LF_FDITQ
IF (LF_FDITQ) THEN
  CALL SAVE (KLUN, YD%F_FDITQ)
ENDIF
CALL SAVE (KLUN, YD%YFDITQ)
LF_FDITS = ASSOCIATED (YD%F_FDITS)
WRITE (KLUN) LF_FDITS
IF (LF_FDITS) THEN
  CALL SAVE (KLUN, YD%F_FDITS)
ENDIF
CALL SAVE (KLUN, YD%YFDITS)
LF_FDUTP = ASSOCIATED (YD%F_FDUTP)
WRITE (KLUN) LF_FDUTP
IF (LF_FDUTP) THEN
  CALL SAVE (KLUN, YD%F_FDUTP)
ENDIF
CALL SAVE (KLUN, YD%YFDUTP)
LF_FEVL = ASSOCIATED (YD%F_FEVL)
WRITE (KLUN) LF_FEVL
IF (LF_FEVL) THEN
  CALL SAVE (KLUN, YD%F_FEVL)
ENDIF
CALL SAVE (KLUN, YD%YFEVL)
LF_FEVN = ASSOCIATED (YD%F_FEVN)
WRITE (KLUN) LF_FEVN
IF (LF_FEVN) THEN
  CALL SAVE (KLUN, YD%F_FEVN)
ENDIF
CALL SAVE (KLUN, YD%YFEVN)
LF_FEVV = ASSOCIATED (YD%F_FEVV)
WRITE (KLUN) LF_FEVV
IF (LF_FEVV) THEN
  CALL SAVE (KLUN, YD%F_FEVV)
ENDIF
CALL SAVE (KLUN, YD%YFEVV)
LF_FGEL = ASSOCIATED (YD%F_FGEL)
WRITE (KLUN) LF_FGEL
IF (LF_FGEL) THEN
  CALL SAVE (KLUN, YD%F_FGEL)
ENDIF
CALL SAVE (KLUN, YD%YFGEL)
LF_FGELS = ASSOCIATED (YD%F_FGELS)
WRITE (KLUN) LF_FGELS
IF (LF_FGELS) THEN
  CALL SAVE (KLUN, YD%F_FGELS)
ENDIF
CALL SAVE (KLUN, YD%YFGELS)
LF_FLASH = ASSOCIATED (YD%F_FLASH)
WRITE (KLUN) LF_FLASH
IF (LF_FLASH) THEN
  CALL SAVE (KLUN, YD%F_FLASH)
ENDIF
CALL SAVE (KLUN, YD%YFLASH)
LF_FLWSP = ASSOCIATED (YD%F_FLWSP)
WRITE (KLUN) LF_FLWSP
IF (LF_FLWSP) THEN
  CALL SAVE (KLUN, YD%F_FLWSP)
ENDIF
CALL SAVE (KLUN, YD%YFLWSP)
LF_FNEB = ASSOCIATED (YD%F_FNEB)
WRITE (KLUN) LF_FNEB
IF (LF_FNEB) THEN
  CALL SAVE (KLUN, YD%F_FNEB)
ENDIF
CALL SAVE (KLUN, YD%YFNEB)
LF_FNEBT = ASSOCIATED (YD%F_FNEBT)
WRITE (KLUN) LF_FNEBT
IF (LF_FNEBT) THEN
  CALL SAVE (KLUN, YD%F_FNEBT)
ENDIF
CALL SAVE (KLUN, YD%YFNEBT)
LF_FONTE = ASSOCIATED (YD%F_FONTE)
WRITE (KLUN) LF_FONTE
IF (LF_FONTE) THEN
  CALL SAVE (KLUN, YD%F_FONTE)
ENDIF
CALL SAVE (KLUN, YD%YFONTE)
LF_FPLCG = ASSOCIATED (YD%F_FPLCG)
WRITE (KLUN) LF_FPLCG
IF (LF_FPLCG) THEN
  CALL SAVE (KLUN, YD%F_FPLCG)
ENDIF
CALL SAVE (KLUN, YD%YFPLCG)
LF_FPLCH = ASSOCIATED (YD%F_FPLCH)
WRITE (KLUN) LF_FPLCH
IF (LF_FPLCH) THEN
  CALL SAVE (KLUN, YD%F_FPLCH)
ENDIF
CALL SAVE (KLUN, YD%YFPLCH)
LF_FPLCL = ASSOCIATED (YD%F_FPLCL)
WRITE (KLUN) LF_FPLCL
IF (LF_FPLCL) THEN
  CALL SAVE (KLUN, YD%F_FPLCL)
ENDIF
CALL SAVE (KLUN, YD%YFPLCL)
LF_FPLCN = ASSOCIATED (YD%F_FPLCN)
WRITE (KLUN) LF_FPLCN
IF (LF_FPLCN) THEN
  CALL SAVE (KLUN, YD%F_FPLCN)
ENDIF
CALL SAVE (KLUN, YD%YFPLCN)
LF_FPLSG = ASSOCIATED (YD%F_FPLSG)
WRITE (KLUN) LF_FPLSG
IF (LF_FPLSG) THEN
  CALL SAVE (KLUN, YD%F_FPLSG)
ENDIF
CALL SAVE (KLUN, YD%YFPLSG)
LF_FPLSH = ASSOCIATED (YD%F_FPLSH)
WRITE (KLUN) LF_FPLSH
IF (LF_FPLSH) THEN
  CALL SAVE (KLUN, YD%F_FPLSH)
ENDIF
CALL SAVE (KLUN, YD%YFPLSH)
LF_FPLSL = ASSOCIATED (YD%F_FPLSL)
WRITE (KLUN) LF_FPLSL
IF (LF_FPLSL) THEN
  CALL SAVE (KLUN, YD%F_FPLSL)
ENDIF
CALL SAVE (KLUN, YD%YFPLSL)
LF_FPLSN = ASSOCIATED (YD%F_FPLSN)
WRITE (KLUN) LF_FPLSN
IF (LF_FPLSN) THEN
  CALL SAVE (KLUN, YD%F_FPLSN)
ENDIF
CALL SAVE (KLUN, YD%YFPLSN)
LF_FRSDNI = ASSOCIATED (YD%F_FRSDNI)
WRITE (KLUN) LF_FRSDNI
IF (LF_FRSDNI) THEN
  CALL SAVE (KLUN, YD%F_FRSDNI)
ENDIF
CALL SAVE (KLUN, YD%YFRSDNI)
LF_FRSGNI = ASSOCIATED (YD%F_FRSGNI)
WRITE (KLUN) LF_FRSGNI
IF (LF_FRSGNI) THEN
  CALL SAVE (KLUN, YD%F_FRSGNI)
ENDIF
CALL SAVE (KLUN, YD%YFRSGNI)
LF_FRSOC0 = ASSOCIATED (YD%F_FRSOC0)
WRITE (KLUN) LF_FRSOC0
IF (LF_FRSOC0) THEN
  CALL SAVE (KLUN, YD%F_FRSOC0)
ENDIF
CALL SAVE (KLUN, YD%YFRSOC0)
LF_FRSOC1 = ASSOCIATED (YD%F_FRSOC1)
WRITE (KLUN) LF_FRSOC1
IF (LF_FRSOC1) THEN
  CALL SAVE (KLUN, YD%F_FRSOC1)
ENDIF
CALL SAVE (KLUN, YD%YFRSOC1)
LF_FRSODS = ASSOCIATED (YD%F_FRSODS)
WRITE (KLUN) LF_FRSODS
IF (LF_FRSODS) THEN
  CALL SAVE (KLUN, YD%F_FRSODS)
ENDIF
CALL SAVE (KLUN, YD%YFRSODS)
LF_FRSOLU = ASSOCIATED (YD%F_FRSOLU)
WRITE (KLUN) LF_FRSOLU
IF (LF_FRSOLU) THEN
  CALL SAVE (KLUN, YD%F_FRSOLU)
ENDIF
CALL SAVE (KLUN, YD%YFRSOLU)
LF_FRSOPS = ASSOCIATED (YD%F_FRSOPS)
WRITE (KLUN) LF_FRSOPS
IF (LF_FRSOPS) THEN
  CALL SAVE (KLUN, YD%F_FRSOPS)
ENDIF
CALL SAVE (KLUN, YD%YFRSOPS)
LF_FRSOPT = ASSOCIATED (YD%F_FRSOPT)
WRITE (KLUN) LF_FRSOPT
IF (LF_FRSOPT) THEN
  CALL SAVE (KLUN, YD%F_FRSOPT)
ENDIF
CALL SAVE (KLUN, YD%YFRSOPT)
LF_FRSO = ASSOCIATED (YD%F_FRSO)
WRITE (KLUN) LF_FRSO
IF (LF_FRSO) THEN
  CALL SAVE (KLUN, YD%F_FRSO)
ENDIF
CALL SAVE (KLUN, YD%YFRSO)
LF_FRTHC0 = ASSOCIATED (YD%F_FRTHC0)
WRITE (KLUN) LF_FRTHC0
IF (LF_FRTHC0) THEN
  CALL SAVE (KLUN, YD%F_FRTHC0)
ENDIF
CALL SAVE (KLUN, YD%YFRTHC0)
LF_FRTHC1 = ASSOCIATED (YD%F_FRTHC1)
WRITE (KLUN) LF_FRTHC1
IF (LF_FRTHC1) THEN
  CALL SAVE (KLUN, YD%F_FRTHC1)
ENDIF
CALL SAVE (KLUN, YD%YFRTHC1)
LF_FRTHDS = ASSOCIATED (YD%F_FRTHDS)
WRITE (KLUN) LF_FRTHDS
IF (LF_FRTHDS) THEN
  CALL SAVE (KLUN, YD%F_FRTHDS)
ENDIF
CALL SAVE (KLUN, YD%YFRTHDS)
LF_FRTH = ASSOCIATED (YD%F_FRTH)
WRITE (KLUN) LF_FRTH
IF (LF_FRTH) THEN
  CALL SAVE (KLUN, YD%F_FRTH)
ENDIF
CALL SAVE (KLUN, YD%YFRTH)
LF_FTOPH = ASSOCIATED (YD%F_FTOPH)
WRITE (KLUN) LF_FTOPH
IF (LF_FTOPH) THEN
  CALL SAVE (KLUN, YD%F_FTOPH)
ENDIF
CALL SAVE (KLUN, YD%YFTOPH)
LF_FTR = ASSOCIATED (YD%F_FTR)
WRITE (KLUN) LF_FTR
IF (LF_FTR) THEN
  CALL SAVE (KLUN, YD%F_FTR)
ENDIF
CALL SAVE (KLUN, YD%YFTR)
LF_NEBBAS = ASSOCIATED (YD%F_NEBBAS)
WRITE (KLUN) LF_NEBBAS
IF (LF_NEBBAS) THEN
  CALL SAVE (KLUN, YD%F_NEBBAS)
ENDIF
CALL SAVE (KLUN, YD%YNEBBAS)
LF_NEBCON = ASSOCIATED (YD%F_NEBCON)
WRITE (KLUN) LF_NEBCON
IF (LF_NEBCON) THEN
  CALL SAVE (KLUN, YD%F_NEBCON)
ENDIF
CALL SAVE (KLUN, YD%YNEBCON)
LF_NEBHAU = ASSOCIATED (YD%F_NEBHAU)
WRITE (KLUN) LF_NEBHAU
IF (LF_NEBHAU) THEN
  CALL SAVE (KLUN, YD%F_NEBHAU)
ENDIF
CALL SAVE (KLUN, YD%YNEBHAU)
LF_NEBMOY = ASSOCIATED (YD%F_NEBMOY)
WRITE (KLUN) LF_NEBMOY
IF (LF_NEBMOY) THEN
  CALL SAVE (KLUN, YD%F_NEBMOY)
ENDIF
CALL SAVE (KLUN, YD%YNEBMOY)
LF_OZONT = ASSOCIATED (YD%F_OZONT)
WRITE (KLUN) LF_OZONT
IF (LF_OZONT) THEN
  CALL SAVE (KLUN, YD%F_OZONT)
ENDIF
CALL SAVE (KLUN, YD%YOZONT)
LF_QICE = ASSOCIATED (YD%F_QICE)
WRITE (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL SAVE (KLUN, YD%F_QICE)
ENDIF
CALL SAVE (KLUN, YD%YQICE)
LF_QLI = ASSOCIATED (YD%F_QLI)
WRITE (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL SAVE (KLUN, YD%F_QLI)
ENDIF
CALL SAVE (KLUN, YD%YQLI)
LF_QTOT = ASSOCIATED (YD%F_QTOT)
WRITE (KLUN) LF_QTOT
IF (LF_QTOT) THEN
  CALL SAVE (KLUN, YD%F_QTOT)
ENDIF
CALL SAVE (KLUN, YD%YQTOT)
LF_RUISL = ASSOCIATED (YD%F_RUISL)
WRITE (KLUN) LF_RUISL
IF (LF_RUISL) THEN
  CALL SAVE (KLUN, YD%F_RUISL)
ENDIF
CALL SAVE (KLUN, YD%YRUISL)
LF_RUISP = ASSOCIATED (YD%F_RUISP)
WRITE (KLUN) LF_RUISP
IF (LF_RUISP) THEN
  CALL SAVE (KLUN, YD%F_RUISP)
ENDIF
CALL SAVE (KLUN, YD%YRUISP)
LF_RUISS = ASSOCIATED (YD%F_RUISS)
WRITE (KLUN) LF_RUISS
IF (LF_RUISS) THEN
  CALL SAVE (KLUN, YD%F_RUISS)
ENDIF
CALL SAVE (KLUN, YD%YRUISS)
LF_SNS = ASSOCIATED (YD%F_SNS)
WRITE (KLUN) LF_SNS
IF (LF_SNS) THEN
  CALL SAVE (KLUN, YD%F_SNS)
ENDIF
CALL SAVE (KLUN, YD%YSNS)
LF_SPRES = ASSOCIATED (YD%F_SPRES)
WRITE (KLUN) LF_SPRES
IF (LF_SPRES) THEN
  CALL SAVE (KLUN, YD%F_SPRES)
ENDIF
CALL SAVE (KLUN, YD%YSPRES)
LF_STRCU = ASSOCIATED (YD%F_STRCU)
WRITE (KLUN) LF_STRCU
IF (LF_STRCU) THEN
  CALL SAVE (KLUN, YD%F_STRCU)
ENDIF
CALL SAVE (KLUN, YD%YSTRCU)
LF_STRCV = ASSOCIATED (YD%F_STRCV)
WRITE (KLUN) LF_STRCV
IF (LF_STRCV) THEN
  CALL SAVE (KLUN, YD%F_STRCV)
ENDIF
CALL SAVE (KLUN, YD%YSTRCV)
LF_STRDU = ASSOCIATED (YD%F_STRDU)
WRITE (KLUN) LF_STRDU
IF (LF_STRDU) THEN
  CALL SAVE (KLUN, YD%F_STRDU)
ENDIF
CALL SAVE (KLUN, YD%YSTRDU)
LF_STRDV = ASSOCIATED (YD%F_STRDV)
WRITE (KLUN) LF_STRDV
IF (LF_STRDV) THEN
  CALL SAVE (KLUN, YD%F_STRDV)
ENDIF
CALL SAVE (KLUN, YD%YSTRDV)
LF_STRTU = ASSOCIATED (YD%F_STRTU)
WRITE (KLUN) LF_STRTU
IF (LF_STRTU) THEN
  CALL SAVE (KLUN, YD%F_STRTU)
ENDIF
CALL SAVE (KLUN, YD%YSTRTU)
LF_STRTV = ASSOCIATED (YD%F_STRTV)
WRITE (KLUN) LF_STRTV
IF (LF_STRTV) THEN
  CALL SAVE (KLUN, YD%F_STRTV)
ENDIF
CALL SAVE (KLUN, YD%YSTRTV)
LF_WS = ASSOCIATED (YD%F_WS)
WRITE (KLUN) LF_WS
IF (LF_WS) THEN
  CALL SAVE (KLUN, YD%F_WS)
ENDIF
CALL SAVE (KLUN, YD%YWS)
END SUBROUTINE
SUBROUTINE LOAD_TCFU (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TCFU_KEYS_MOD, ONLY : TCFU_KEYS, LOAD_TCFU_KEYS

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCFU), INTENT (OUT), TARGET :: YD
CLASS (TCFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_FCCQL, LF_FCCQN, LF_FCHSP, LF_FCL, LF_FCLL, LF_FCLN, LF_FCS, LF_FCSQL, LF_FCSQN, LF_FDICQ, LF_FDICS, LF_FDISH, LF_FDITQ, LF_FDITS, LF_FDUTP, LF_FEVL, LF_FEVN, LF_FEVV, LF_FGEL, LF_FGELS, LF_FLASH, LF_FLWSP, LF_FNEB, LF_FNEBT, LF_FONTE, LF_FPLCG, LF_FPLCH, LF_FPLCL, LF_FPLCN, LF_FPLSG, LF_FPLSH, LF_FPLSL, LF_FPLSN, LF_FRSDNI, LF_FRSGNI, LF_FRSO, LF_FRSOC0, LF_FRSOC1, LF_FRSODS, LF_FRSOLU, LF_FRSOPS, LF_FRSOPT, LF_FRTH, LF_FRTHC0, LF_FRTHC1, LF_FRTHDS, LF_FTOPH, LF_FTR, LF_NEBBAS, LF_NEBCON, LF_NEBHAU, LF_NEBMOY, LF_OZONT, LF_QICE, LF_QLI, LF_QTOT, LF_RUISL, LF_RUISP, LF_RUISS, LF_SNS, LF_SPRES, LF_STRCU, LF_STRCV, LF_STRDU, LF_STRDV, LF_STRTU, LF_STRTV, LF_WS
YLSUPER => YD
CALL LOAD_TCFU_KEYS (KLUN, YLSUPER)
READ (KLUN) YD%NCFUTS
READ (KLUN) YD%NFRRC
READ (KLUN) YD%NFRCFU
READ (KLUN) YD%NFDCFU
READ (KLUN) YD%NTYPCFU
READ (KLUN) YD%NMTFLASH
READ (KLUN) YD%CALFLASH1
READ (KLUN) YD%CALFLASH2
READ (KLUN) YD%LREACFU
NULLIFY (YD%CFUBUF_B)
NULLIFY (YD%FCCQL)
READ (KLUN) LF_FCCQL
IF (LF_FCCQL) THEN
  CALL LOAD (KLUN, YD%F_FCCQL)
ELSE
  NULLIFY (YD%F_FCCQL)
ENDIF
CALL LOAD (KLUN, YD%YFCCQL)
NULLIFY (YD%FCCQN)
READ (KLUN) LF_FCCQN
IF (LF_FCCQN) THEN
  CALL LOAD (KLUN, YD%F_FCCQN)
ELSE
  NULLIFY (YD%F_FCCQN)
ENDIF
CALL LOAD (KLUN, YD%YFCCQN)
NULLIFY (YD%FCHSP)
READ (KLUN) LF_FCHSP
IF (LF_FCHSP) THEN
  CALL LOAD (KLUN, YD%F_FCHSP)
ELSE
  NULLIFY (YD%F_FCHSP)
ENDIF
CALL LOAD (KLUN, YD%YFCHSP)
NULLIFY (YD%FCL)
READ (KLUN) LF_FCL
IF (LF_FCL) THEN
  CALL LOAD (KLUN, YD%F_FCL)
ELSE
  NULLIFY (YD%F_FCL)
ENDIF
CALL LOAD (KLUN, YD%YFCL)
NULLIFY (YD%FCLL)
READ (KLUN) LF_FCLL
IF (LF_FCLL) THEN
  CALL LOAD (KLUN, YD%F_FCLL)
ELSE
  NULLIFY (YD%F_FCLL)
ENDIF
CALL LOAD (KLUN, YD%YFCLL)
NULLIFY (YD%FCLN)
READ (KLUN) LF_FCLN
IF (LF_FCLN) THEN
  CALL LOAD (KLUN, YD%F_FCLN)
ELSE
  NULLIFY (YD%F_FCLN)
ENDIF
CALL LOAD (KLUN, YD%YFCLN)
NULLIFY (YD%FCSQL)
READ (KLUN) LF_FCSQL
IF (LF_FCSQL) THEN
  CALL LOAD (KLUN, YD%F_FCSQL)
ELSE
  NULLIFY (YD%F_FCSQL)
ENDIF
CALL LOAD (KLUN, YD%YFCSQL)
NULLIFY (YD%FCSQN)
READ (KLUN) LF_FCSQN
IF (LF_FCSQN) THEN
  CALL LOAD (KLUN, YD%F_FCSQN)
ELSE
  NULLIFY (YD%F_FCSQN)
ENDIF
CALL LOAD (KLUN, YD%YFCSQN)
NULLIFY (YD%FCS)
READ (KLUN) LF_FCS
IF (LF_FCS) THEN
  CALL LOAD (KLUN, YD%F_FCS)
ELSE
  NULLIFY (YD%F_FCS)
ENDIF
CALL LOAD (KLUN, YD%YFCS)
NULLIFY (YD%FDICQ)
READ (KLUN) LF_FDICQ
IF (LF_FDICQ) THEN
  CALL LOAD (KLUN, YD%F_FDICQ)
ELSE
  NULLIFY (YD%F_FDICQ)
ENDIF
CALL LOAD (KLUN, YD%YFDICQ)
NULLIFY (YD%FDICS)
READ (KLUN) LF_FDICS
IF (LF_FDICS) THEN
  CALL LOAD (KLUN, YD%F_FDICS)
ELSE
  NULLIFY (YD%F_FDICS)
ENDIF
CALL LOAD (KLUN, YD%YFDICS)
NULLIFY (YD%FDISH)
READ (KLUN) LF_FDISH
IF (LF_FDISH) THEN
  CALL LOAD (KLUN, YD%F_FDISH)
ELSE
  NULLIFY (YD%F_FDISH)
ENDIF
CALL LOAD (KLUN, YD%YFDISH)
NULLIFY (YD%FDITQ)
READ (KLUN) LF_FDITQ
IF (LF_FDITQ) THEN
  CALL LOAD (KLUN, YD%F_FDITQ)
ELSE
  NULLIFY (YD%F_FDITQ)
ENDIF
CALL LOAD (KLUN, YD%YFDITQ)
NULLIFY (YD%FDITS)
READ (KLUN) LF_FDITS
IF (LF_FDITS) THEN
  CALL LOAD (KLUN, YD%F_FDITS)
ELSE
  NULLIFY (YD%F_FDITS)
ENDIF
CALL LOAD (KLUN, YD%YFDITS)
NULLIFY (YD%FDUTP)
READ (KLUN) LF_FDUTP
IF (LF_FDUTP) THEN
  CALL LOAD (KLUN, YD%F_FDUTP)
ELSE
  NULLIFY (YD%F_FDUTP)
ENDIF
CALL LOAD (KLUN, YD%YFDUTP)
NULLIFY (YD%FEVL)
READ (KLUN) LF_FEVL
IF (LF_FEVL) THEN
  CALL LOAD (KLUN, YD%F_FEVL)
ELSE
  NULLIFY (YD%F_FEVL)
ENDIF
CALL LOAD (KLUN, YD%YFEVL)
NULLIFY (YD%FEVN)
READ (KLUN) LF_FEVN
IF (LF_FEVN) THEN
  CALL LOAD (KLUN, YD%F_FEVN)
ELSE
  NULLIFY (YD%F_FEVN)
ENDIF
CALL LOAD (KLUN, YD%YFEVN)
NULLIFY (YD%FEVV)
READ (KLUN) LF_FEVV
IF (LF_FEVV) THEN
  CALL LOAD (KLUN, YD%F_FEVV)
ELSE
  NULLIFY (YD%F_FEVV)
ENDIF
CALL LOAD (KLUN, YD%YFEVV)
NULLIFY (YD%FGEL)
READ (KLUN) LF_FGEL
IF (LF_FGEL) THEN
  CALL LOAD (KLUN, YD%F_FGEL)
ELSE
  NULLIFY (YD%F_FGEL)
ENDIF
CALL LOAD (KLUN, YD%YFGEL)
NULLIFY (YD%FGELS)
READ (KLUN) LF_FGELS
IF (LF_FGELS) THEN
  CALL LOAD (KLUN, YD%F_FGELS)
ELSE
  NULLIFY (YD%F_FGELS)
ENDIF
CALL LOAD (KLUN, YD%YFGELS)
NULLIFY (YD%FLASH)
READ (KLUN) LF_FLASH
IF (LF_FLASH) THEN
  CALL LOAD (KLUN, YD%F_FLASH)
ELSE
  NULLIFY (YD%F_FLASH)
ENDIF
CALL LOAD (KLUN, YD%YFLASH)
NULLIFY (YD%FLWSP)
READ (KLUN) LF_FLWSP
IF (LF_FLWSP) THEN
  CALL LOAD (KLUN, YD%F_FLWSP)
ELSE
  NULLIFY (YD%F_FLWSP)
ENDIF
CALL LOAD (KLUN, YD%YFLWSP)
NULLIFY (YD%FNEB)
READ (KLUN) LF_FNEB
IF (LF_FNEB) THEN
  CALL LOAD (KLUN, YD%F_FNEB)
ELSE
  NULLIFY (YD%F_FNEB)
ENDIF
CALL LOAD (KLUN, YD%YFNEB)
NULLIFY (YD%FNEBT)
READ (KLUN) LF_FNEBT
IF (LF_FNEBT) THEN
  CALL LOAD (KLUN, YD%F_FNEBT)
ELSE
  NULLIFY (YD%F_FNEBT)
ENDIF
CALL LOAD (KLUN, YD%YFNEBT)
NULLIFY (YD%FONTE)
READ (KLUN) LF_FONTE
IF (LF_FONTE) THEN
  CALL LOAD (KLUN, YD%F_FONTE)
ELSE
  NULLIFY (YD%F_FONTE)
ENDIF
CALL LOAD (KLUN, YD%YFONTE)
NULLIFY (YD%FPLCG)
READ (KLUN) LF_FPLCG
IF (LF_FPLCG) THEN
  CALL LOAD (KLUN, YD%F_FPLCG)
ELSE
  NULLIFY (YD%F_FPLCG)
ENDIF
CALL LOAD (KLUN, YD%YFPLCG)
NULLIFY (YD%FPLCH)
READ (KLUN) LF_FPLCH
IF (LF_FPLCH) THEN
  CALL LOAD (KLUN, YD%F_FPLCH)
ELSE
  NULLIFY (YD%F_FPLCH)
ENDIF
CALL LOAD (KLUN, YD%YFPLCH)
NULLIFY (YD%FPLCL)
READ (KLUN) LF_FPLCL
IF (LF_FPLCL) THEN
  CALL LOAD (KLUN, YD%F_FPLCL)
ELSE
  NULLIFY (YD%F_FPLCL)
ENDIF
CALL LOAD (KLUN, YD%YFPLCL)
NULLIFY (YD%FPLCN)
READ (KLUN) LF_FPLCN
IF (LF_FPLCN) THEN
  CALL LOAD (KLUN, YD%F_FPLCN)
ELSE
  NULLIFY (YD%F_FPLCN)
ENDIF
CALL LOAD (KLUN, YD%YFPLCN)
NULLIFY (YD%FPLSG)
READ (KLUN) LF_FPLSG
IF (LF_FPLSG) THEN
  CALL LOAD (KLUN, YD%F_FPLSG)
ELSE
  NULLIFY (YD%F_FPLSG)
ENDIF
CALL LOAD (KLUN, YD%YFPLSG)
NULLIFY (YD%FPLSH)
READ (KLUN) LF_FPLSH
IF (LF_FPLSH) THEN
  CALL LOAD (KLUN, YD%F_FPLSH)
ELSE
  NULLIFY (YD%F_FPLSH)
ENDIF
CALL LOAD (KLUN, YD%YFPLSH)
NULLIFY (YD%FPLSL)
READ (KLUN) LF_FPLSL
IF (LF_FPLSL) THEN
  CALL LOAD (KLUN, YD%F_FPLSL)
ELSE
  NULLIFY (YD%F_FPLSL)
ENDIF
CALL LOAD (KLUN, YD%YFPLSL)
NULLIFY (YD%FPLSN)
READ (KLUN) LF_FPLSN
IF (LF_FPLSN) THEN
  CALL LOAD (KLUN, YD%F_FPLSN)
ELSE
  NULLIFY (YD%F_FPLSN)
ENDIF
CALL LOAD (KLUN, YD%YFPLSN)
NULLIFY (YD%FRSDNI)
READ (KLUN) LF_FRSDNI
IF (LF_FRSDNI) THEN
  CALL LOAD (KLUN, YD%F_FRSDNI)
ELSE
  NULLIFY (YD%F_FRSDNI)
ENDIF
CALL LOAD (KLUN, YD%YFRSDNI)
NULLIFY (YD%FRSGNI)
READ (KLUN) LF_FRSGNI
IF (LF_FRSGNI) THEN
  CALL LOAD (KLUN, YD%F_FRSGNI)
ELSE
  NULLIFY (YD%F_FRSGNI)
ENDIF
CALL LOAD (KLUN, YD%YFRSGNI)
NULLIFY (YD%FRSOC0)
READ (KLUN) LF_FRSOC0
IF (LF_FRSOC0) THEN
  CALL LOAD (KLUN, YD%F_FRSOC0)
ELSE
  NULLIFY (YD%F_FRSOC0)
ENDIF
CALL LOAD (KLUN, YD%YFRSOC0)
NULLIFY (YD%FRSOC1)
READ (KLUN) LF_FRSOC1
IF (LF_FRSOC1) THEN
  CALL LOAD (KLUN, YD%F_FRSOC1)
ELSE
  NULLIFY (YD%F_FRSOC1)
ENDIF
CALL LOAD (KLUN, YD%YFRSOC1)
NULLIFY (YD%FRSODS)
READ (KLUN) LF_FRSODS
IF (LF_FRSODS) THEN
  CALL LOAD (KLUN, YD%F_FRSODS)
ELSE
  NULLIFY (YD%F_FRSODS)
ENDIF
CALL LOAD (KLUN, YD%YFRSODS)
NULLIFY (YD%FRSOLU)
READ (KLUN) LF_FRSOLU
IF (LF_FRSOLU) THEN
  CALL LOAD (KLUN, YD%F_FRSOLU)
ELSE
  NULLIFY (YD%F_FRSOLU)
ENDIF
CALL LOAD (KLUN, YD%YFRSOLU)
NULLIFY (YD%FRSOPS)
READ (KLUN) LF_FRSOPS
IF (LF_FRSOPS) THEN
  CALL LOAD (KLUN, YD%F_FRSOPS)
ELSE
  NULLIFY (YD%F_FRSOPS)
ENDIF
CALL LOAD (KLUN, YD%YFRSOPS)
NULLIFY (YD%FRSOPT)
READ (KLUN) LF_FRSOPT
IF (LF_FRSOPT) THEN
  CALL LOAD (KLUN, YD%F_FRSOPT)
ELSE
  NULLIFY (YD%F_FRSOPT)
ENDIF
CALL LOAD (KLUN, YD%YFRSOPT)
NULLIFY (YD%FRSO)
READ (KLUN) LF_FRSO
IF (LF_FRSO) THEN
  CALL LOAD (KLUN, YD%F_FRSO)
ELSE
  NULLIFY (YD%F_FRSO)
ENDIF
CALL LOAD (KLUN, YD%YFRSO)
NULLIFY (YD%FRTHC0)
READ (KLUN) LF_FRTHC0
IF (LF_FRTHC0) THEN
  CALL LOAD (KLUN, YD%F_FRTHC0)
ELSE
  NULLIFY (YD%F_FRTHC0)
ENDIF
CALL LOAD (KLUN, YD%YFRTHC0)
NULLIFY (YD%FRTHC1)
READ (KLUN) LF_FRTHC1
IF (LF_FRTHC1) THEN
  CALL LOAD (KLUN, YD%F_FRTHC1)
ELSE
  NULLIFY (YD%F_FRTHC1)
ENDIF
CALL LOAD (KLUN, YD%YFRTHC1)
NULLIFY (YD%FRTHDS)
READ (KLUN) LF_FRTHDS
IF (LF_FRTHDS) THEN
  CALL LOAD (KLUN, YD%F_FRTHDS)
ELSE
  NULLIFY (YD%F_FRTHDS)
ENDIF
CALL LOAD (KLUN, YD%YFRTHDS)
NULLIFY (YD%FRTH)
READ (KLUN) LF_FRTH
IF (LF_FRTH) THEN
  CALL LOAD (KLUN, YD%F_FRTH)
ELSE
  NULLIFY (YD%F_FRTH)
ENDIF
CALL LOAD (KLUN, YD%YFRTH)
NULLIFY (YD%FTOPH)
READ (KLUN) LF_FTOPH
IF (LF_FTOPH) THEN
  CALL LOAD (KLUN, YD%F_FTOPH)
ELSE
  NULLIFY (YD%F_FTOPH)
ENDIF
CALL LOAD (KLUN, YD%YFTOPH)
NULLIFY (YD%FTR)
READ (KLUN) LF_FTR
IF (LF_FTR) THEN
  CALL LOAD (KLUN, YD%F_FTR)
ELSE
  NULLIFY (YD%F_FTR)
ENDIF
CALL LOAD (KLUN, YD%YFTR)
NULLIFY (YD%NEBBAS)
READ (KLUN) LF_NEBBAS
IF (LF_NEBBAS) THEN
  CALL LOAD (KLUN, YD%F_NEBBAS)
ELSE
  NULLIFY (YD%F_NEBBAS)
ENDIF
CALL LOAD (KLUN, YD%YNEBBAS)
NULLIFY (YD%NEBCON)
READ (KLUN) LF_NEBCON
IF (LF_NEBCON) THEN
  CALL LOAD (KLUN, YD%F_NEBCON)
ELSE
  NULLIFY (YD%F_NEBCON)
ENDIF
CALL LOAD (KLUN, YD%YNEBCON)
NULLIFY (YD%NEBHAU)
READ (KLUN) LF_NEBHAU
IF (LF_NEBHAU) THEN
  CALL LOAD (KLUN, YD%F_NEBHAU)
ELSE
  NULLIFY (YD%F_NEBHAU)
ENDIF
CALL LOAD (KLUN, YD%YNEBHAU)
NULLIFY (YD%NEBMOY)
READ (KLUN) LF_NEBMOY
IF (LF_NEBMOY) THEN
  CALL LOAD (KLUN, YD%F_NEBMOY)
ELSE
  NULLIFY (YD%F_NEBMOY)
ENDIF
CALL LOAD (KLUN, YD%YNEBMOY)
NULLIFY (YD%OZONT)
READ (KLUN) LF_OZONT
IF (LF_OZONT) THEN
  CALL LOAD (KLUN, YD%F_OZONT)
ELSE
  NULLIFY (YD%F_OZONT)
ENDIF
CALL LOAD (KLUN, YD%YOZONT)
NULLIFY (YD%QICE)
READ (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL LOAD (KLUN, YD%F_QICE)
ELSE
  NULLIFY (YD%F_QICE)
ENDIF
CALL LOAD (KLUN, YD%YQICE)
NULLIFY (YD%QLI)
READ (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL LOAD (KLUN, YD%F_QLI)
ELSE
  NULLIFY (YD%F_QLI)
ENDIF
CALL LOAD (KLUN, YD%YQLI)
NULLIFY (YD%QTOT)
READ (KLUN) LF_QTOT
IF (LF_QTOT) THEN
  CALL LOAD (KLUN, YD%F_QTOT)
ELSE
  NULLIFY (YD%F_QTOT)
ENDIF
CALL LOAD (KLUN, YD%YQTOT)
NULLIFY (YD%RUISL)
READ (KLUN) LF_RUISL
IF (LF_RUISL) THEN
  CALL LOAD (KLUN, YD%F_RUISL)
ELSE
  NULLIFY (YD%F_RUISL)
ENDIF
CALL LOAD (KLUN, YD%YRUISL)
NULLIFY (YD%RUISP)
READ (KLUN) LF_RUISP
IF (LF_RUISP) THEN
  CALL LOAD (KLUN, YD%F_RUISP)
ELSE
  NULLIFY (YD%F_RUISP)
ENDIF
CALL LOAD (KLUN, YD%YRUISP)
NULLIFY (YD%RUISS)
READ (KLUN) LF_RUISS
IF (LF_RUISS) THEN
  CALL LOAD (KLUN, YD%F_RUISS)
ELSE
  NULLIFY (YD%F_RUISS)
ENDIF
CALL LOAD (KLUN, YD%YRUISS)
NULLIFY (YD%SNS)
READ (KLUN) LF_SNS
IF (LF_SNS) THEN
  CALL LOAD (KLUN, YD%F_SNS)
ELSE
  NULLIFY (YD%F_SNS)
ENDIF
CALL LOAD (KLUN, YD%YSNS)
NULLIFY (YD%SPRES)
READ (KLUN) LF_SPRES
IF (LF_SPRES) THEN
  CALL LOAD (KLUN, YD%F_SPRES)
ELSE
  NULLIFY (YD%F_SPRES)
ENDIF
CALL LOAD (KLUN, YD%YSPRES)
NULLIFY (YD%STRCU)
READ (KLUN) LF_STRCU
IF (LF_STRCU) THEN
  CALL LOAD (KLUN, YD%F_STRCU)
ELSE
  NULLIFY (YD%F_STRCU)
ENDIF
CALL LOAD (KLUN, YD%YSTRCU)
NULLIFY (YD%STRCV)
READ (KLUN) LF_STRCV
IF (LF_STRCV) THEN
  CALL LOAD (KLUN, YD%F_STRCV)
ELSE
  NULLIFY (YD%F_STRCV)
ENDIF
CALL LOAD (KLUN, YD%YSTRCV)
NULLIFY (YD%STRDU)
READ (KLUN) LF_STRDU
IF (LF_STRDU) THEN
  CALL LOAD (KLUN, YD%F_STRDU)
ELSE
  NULLIFY (YD%F_STRDU)
ENDIF
CALL LOAD (KLUN, YD%YSTRDU)
NULLIFY (YD%STRDV)
READ (KLUN) LF_STRDV
IF (LF_STRDV) THEN
  CALL LOAD (KLUN, YD%F_STRDV)
ELSE
  NULLIFY (YD%F_STRDV)
ENDIF
CALL LOAD (KLUN, YD%YSTRDV)
NULLIFY (YD%STRTU)
READ (KLUN) LF_STRTU
IF (LF_STRTU) THEN
  CALL LOAD (KLUN, YD%F_STRTU)
ELSE
  NULLIFY (YD%F_STRTU)
ENDIF
CALL LOAD (KLUN, YD%YSTRTU)
NULLIFY (YD%STRTV)
READ (KLUN) LF_STRTV
IF (LF_STRTV) THEN
  CALL LOAD (KLUN, YD%F_STRTV)
ELSE
  NULLIFY (YD%F_STRTV)
ENDIF
CALL LOAD (KLUN, YD%YSTRTV)
NULLIFY (YD%WS)
READ (KLUN) LF_WS
IF (LF_WS) THEN
  CALL LOAD (KLUN, YD%F_WS)
ELSE
  NULLIFY (YD%F_WS)
ENDIF
CALL LOAD (KLUN, YD%YWS)
END SUBROUTINE




END MODULE
