MODULE UTIL_TRIP_MOD

USE YOMRIP, ONLY : TRIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRIP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TRIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRIP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NSTART
WRITE (KLUN) YD%NSTOP
WRITE (KLUN) YD%CSTOP
WRITE (KLUN) YD%NSTADD
WRITE (KLUN) YD%NSTASS
WRITE (KLUN) YD%NFOST
WRITE (KLUN) YD%RSTATI
WRITE (KLUN) YD%RTIMTR
WRITE (KLUN) YD%RHGMT
WRITE (KLUN) YD%REQTIM
WRITE (KLUN) YD%RSOVR
WRITE (KLUN) YD%RDEASO
WRITE (KLUN) YD%RDECLI
WRITE (KLUN) YD%RWSOVR
WRITE (KLUN) YD%RIP0
WRITE (KLUN) YD%RCODEC
WRITE (KLUN) YD%RSIDEC
WRITE (KLUN) YD%RCOVSR
WRITE (KLUN) YD%RSIVSR
WRITE (KLUN) YD%RCODECN
WRITE (KLUN) YD%RSIDECN
WRITE (KLUN) YD%RCOVSRN
WRITE (KLUN) YD%RSIVSRN
WRITE (KLUN) YD%RCODECF
WRITE (KLUN) YD%RSIDECF
WRITE (KLUN) YD%RCOVSRF
WRITE (KLUN) YD%RSIVSRF
WRITE (KLUN) YD%TSTEP
WRITE (KLUN) YD%TDT
WRITE (KLUN) YD%RDTSA
WRITE (KLUN) YD%RDTSA2
WRITE (KLUN) YD%RDTS62
WRITE (KLUN) YD%RDTS22
WRITE (KLUN) YD%RTDT
WRITE (KLUN) YD%RDECLU
WRITE (KLUN) YD%RTMOLT
WRITE (KLUN) YD%RIP0LU
WRITE (KLUN) YD%RCODECLU
WRITE (KLUN) YD%RSIDECLU
WRITE (KLUN) YD%RCOVSRLU
WRITE (KLUN) YD%RSIVSRLU
END SUBROUTINE

SUBROUTINE LOAD_TRIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRIP), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NSTART
READ (KLUN) YD%NSTOP
READ (KLUN) YD%CSTOP
READ (KLUN) YD%NSTADD
READ (KLUN) YD%NSTASS
READ (KLUN) YD%NFOST
READ (KLUN) YD%RSTATI
READ (KLUN) YD%RTIMTR
READ (KLUN) YD%RHGMT
READ (KLUN) YD%REQTIM
READ (KLUN) YD%RSOVR
READ (KLUN) YD%RDEASO
READ (KLUN) YD%RDECLI
READ (KLUN) YD%RWSOVR
READ (KLUN) YD%RIP0
READ (KLUN) YD%RCODEC
READ (KLUN) YD%RSIDEC
READ (KLUN) YD%RCOVSR
READ (KLUN) YD%RSIVSR
READ (KLUN) YD%RCODECN
READ (KLUN) YD%RSIDECN
READ (KLUN) YD%RCOVSRN
READ (KLUN) YD%RSIVSRN
READ (KLUN) YD%RCODECF
READ (KLUN) YD%RSIDECF
READ (KLUN) YD%RCOVSRF
READ (KLUN) YD%RSIVSRF
READ (KLUN) YD%TSTEP
READ (KLUN) YD%TDT
READ (KLUN) YD%RDTSA
READ (KLUN) YD%RDTSA2
READ (KLUN) YD%RDTS62
READ (KLUN) YD%RDTS22
READ (KLUN) YD%RTDT
READ (KLUN) YD%RDECLU
READ (KLUN) YD%RTMOLT
READ (KLUN) YD%RIP0LU
READ (KLUN) YD%RCODECLU
READ (KLUN) YD%RSIDECLU
READ (KLUN) YD%RCOVSRLU
READ (KLUN) YD%RSIVSRLU
END SUBROUTINE






END MODULE
