MODULE UTIL_RADIATION_GRID_STRUCT_MOD

USE YOMPRAD, ONLY : RADIATION_GRID_STRUCT

INTERFACE SAVE
MODULE PROCEDURE SAVE_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_RADIATION_GRID_STRUCT
END INTERFACE




CONTAINS

SUBROUTINE SAVE_RADIATION_GRID_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT, LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN) YD%NRESOL_ID
WRITE (KLUN) YD%NGPTOT
WRITE (KLUN) YD%NGPTOTG
WRITE (KLUN) YD%NGPTOTMX
WRITE (KLUN) YD%NSPEC2
WRITE (KLUN) YD%NSMAX
WRITE (KLUN) YD%NPTRFLOFF
WRITE (KLUN) YD%NUMP
WRITE (KLUN) YD%NDLON
WRITE (KLUN) YD%NDGSAL
WRITE (KLUN) YD%NDGENL
WRITE (KLUN) YD%NDGSAH
WRITE (KLUN) YD%NDGENH
WRITE (KLUN) YD%NDGLG
WRITE (KLUN) YD%NDGSAG
WRITE (KLUN) YD%NDGENG
WRITE (KLUN) YD%NDLSUR
WRITE (KLUN) YD%NFRSTLOFF
WRITE (KLUN) YD%NDSUR1
WRITE (KLUN) YD%NDGSUR
WRITE (KLUN) YD%MYFRSTACTLAT
WRITE (KLUN) YD%MYLSTACTLAT
LNRGRI = ALLOCATED (YD%NRGRI)
WRITE (KLUN) LNRGRI
IF (LNRGRI) THEN
  WRITE (KLUN) LBOUND (YD%NRGRI)
  WRITE (KLUN) UBOUND (YD%NRGRI)
  WRITE (KLUN) YD%NRGRI
ENDIF
LNLOENG = ALLOCATED (YD%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (YD%NLOENG)
  WRITE (KLUN) UBOUND (YD%NLOENG)
  WRITE (KLUN) YD%NLOENG
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) YD%NPTRFRSTLAT
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NFRSTLAT)
  WRITE (KLUN) YD%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NLSTLAT)
  WRITE (KLUN) UBOUND (YD%NLSTLAT)
  WRITE (KLUN) YD%NLSTLAT
ENDIF
LMYMS = ALLOCATED (YD%MYMS)
WRITE (KLUN) LMYMS
IF (LMYMS) THEN
  WRITE (KLUN) LBOUND (YD%MYMS)
  WRITE (KLUN) UBOUND (YD%MYMS)
  WRITE (KLUN) YD%MYMS
ENDIF
LNASM0 = ALLOCATED (YD%NASM0)
WRITE (KLUN) LNASM0
IF (LNASM0) THEN
  WRITE (KLUN) LBOUND (YD%NASM0)
  WRITE (KLUN) UBOUND (YD%NASM0)
  WRITE (KLUN) YD%NASM0
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (YD%NSTA)
  WRITE (KLUN) UBOUND (YD%NSTA)
  WRITE (KLUN) YD%NSTA
ENDIF
LNONL = ALLOCATED (YD%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (YD%NONL)
  WRITE (KLUN) UBOUND (YD%NONL)
  WRITE (KLUN) YD%NONL
ENDIF
LGELAM = ALLOCATED (YD%GELAM)
WRITE (KLUN) LGELAM
IF (LGELAM) THEN
  WRITE (KLUN) LBOUND (YD%GELAM)
  WRITE (KLUN) UBOUND (YD%GELAM)
  WRITE (KLUN) YD%GELAM
ENDIF
LGELAT = ALLOCATED (YD%GELAT)
WRITE (KLUN) LGELAT
IF (LGELAT) THEN
  WRITE (KLUN) LBOUND (YD%GELAT)
  WRITE (KLUN) UBOUND (YD%GELAT)
  WRITE (KLUN) YD%GELAT
ENDIF
LGECLO = ALLOCATED (YD%GECLO)
WRITE (KLUN) LGECLO
IF (LGECLO) THEN
  WRITE (KLUN) LBOUND (YD%GECLO)
  WRITE (KLUN) UBOUND (YD%GECLO)
  WRITE (KLUN) YD%GECLO
ENDIF
LGESLO = ALLOCATED (YD%GESLO)
WRITE (KLUN) LGESLO
IF (LGESLO) THEN
  WRITE (KLUN) LBOUND (YD%GESLO)
  WRITE (KLUN) UBOUND (YD%GESLO)
  WRITE (KLUN) YD%GESLO
ENDIF
LRMU = ALLOCATED (YD%RMU)
WRITE (KLUN) LRMU
IF (LRMU) THEN
  WRITE (KLUN) LBOUND (YD%RMU)
  WRITE (KLUN) UBOUND (YD%RMU)
  WRITE (KLUN) YD%RMU
ENDIF
LRSQM2 = ALLOCATED (YD%RSQM2)
WRITE (KLUN) LRSQM2
IF (LRSQM2) THEN
  WRITE (KLUN) LBOUND (YD%RSQM2)
  WRITE (KLUN) UBOUND (YD%RSQM2)
  WRITE (KLUN) YD%RSQM2
ENDIF
LRLATIG = ALLOCATED (YD%RLATIG)
WRITE (KLUN) LRLATIG
IF (LRLATIG) THEN
  WRITE (KLUN) LBOUND (YD%RLATIG)
  WRITE (KLUN) UBOUND (YD%RLATIG)
  WRITE (KLUN) YD%RLATIG
ENDIF
LRLATI = ALLOCATED (YD%RLATI)
WRITE (KLUN) LRLATI
IF (LRLATI) THEN
  WRITE (KLUN) LBOUND (YD%RLATI)
  WRITE (KLUN) UBOUND (YD%RLATI)
  WRITE (KLUN) YD%RLATI
ENDIF
LGEMU = ALLOCATED (YD%GEMU)
WRITE (KLUN) LGEMU
IF (LGEMU) THEN
  WRITE (KLUN) LBOUND (YD%GEMU)
  WRITE (KLUN) UBOUND (YD%GEMU)
  WRITE (KLUN) YD%GEMU
ENDIF
LRIPI = ALLOCATED (YD%RIPI)
WRITE (KLUN) LRIPI
IF (LRIPI) THEN
  WRITE (KLUN) LBOUND (YD%RIPI)
  WRITE (KLUN) UBOUND (YD%RIPI)
  WRITE (KLUN) YD%RIPI
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_RADIATION_GRID_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (RADIATION_GRID_STRUCT), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT, LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
READ (KLUN) YD%NRESOL_ID
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NGPTOTG
READ (KLUN) YD%NGPTOTMX
READ (KLUN) YD%NSPEC2
READ (KLUN) YD%NSMAX
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) YD%NUMP
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) LNRGRI
IF (LNRGRI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NRGRI (IL1(1):IU1(1)))
  READ (KLUN) YD%NRGRI
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRFRSTLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NLSTLAT
ENDIF
READ (KLUN) LMYMS
IF (LMYMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYMS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYMS
ENDIF
READ (KLUN) LNASM0
IF (LNASM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NASM0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NASM0
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NONL
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAM (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAM
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAT (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAT
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GECLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GECLO
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GESLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GESLO
ENDIF
READ (KLUN) LRMU
IF (LRMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMU
ENDIF
READ (KLUN) LRSQM2
IF (LRSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSQM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%RSQM2
ENDIF
READ (KLUN) LRLATIG
IF (LRLATIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATIG (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATIG
ENDIF
READ (KLUN) LRLATI
IF (LRLATI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATI (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATI
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GEMU (IL1(1):IU1(1)))
  READ (KLUN) YD%GEMU
ENDIF
READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RIPI
ENDIF
END SUBROUTINE




END MODULE
