MODULE UTIL_CPG_HWIND_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_HWIND_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_HWIND_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_HWIND_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_CPG_HWIND_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_HWIND_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_UH, LF_VH, LF_WWI
WRITE (KLUN) YD%LOWNED
WRITE (KLUN) YD%IP_UH
LF_UH = ASSOCIATED (YD%F_UH)
WRITE (KLUN) LF_UH
IF (LF_UH) THEN
  CALL SAVE (KLUN, YD%F_UH)
ENDIF
WRITE (KLUN) YD%IP_VH
LF_VH = ASSOCIATED (YD%F_VH)
WRITE (KLUN) LF_VH
IF (LF_VH) THEN
  CALL SAVE (KLUN, YD%F_VH)
ENDIF
WRITE (KLUN) YD%IP_WWI
LF_WWI = ASSOCIATED (YD%F_WWI)
WRITE (KLUN) LF_WWI
IF (LF_WWI) THEN
  CALL SAVE (KLUN, YD%F_WWI)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_HWIND_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_HWIND_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_UH, LF_VH, LF_WWI
READ (KLUN) YD%LOWNED
NULLIFY (YD%ZVIEW)
NULLIFY (YD%ZDATA)
NULLIFY (YD%F_DATA)
READ (KLUN) YD%IP_UH
NULLIFY (YD%UH)
READ (KLUN) LF_UH
IF (LF_UH) THEN
  CALL LOAD (KLUN, YD%F_UH)
ELSE
  NULLIFY (YD%F_UH)
ENDIF
READ (KLUN) YD%IP_VH
NULLIFY (YD%VH)
READ (KLUN) LF_VH
IF (LF_VH) THEN
  CALL LOAD (KLUN, YD%F_VH)
ELSE
  NULLIFY (YD%F_VH)
ENDIF
READ (KLUN) YD%IP_WWI
NULLIFY (YD%WWI)
READ (KLUN) LF_WWI
IF (LF_WWI) THEN
  CALL LOAD (KLUN, YD%F_WWI)
ELSE
  NULLIFY (YD%F_WWI)
ENDIF
END SUBROUTINE






END MODULE
