MODULE UTIL_TDVISI_MOD

USE YOMDVISI, ONLY : TDVISI

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDVISI
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDVISI
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDVISI
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDVISI
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDVISI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDVISI), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%HVISI
WRITE (KLUN) YD%COEF_CM1
WRITE (KLUN) YD%COEF_CM2
WRITE (KLUN) YD%COEF_CM3
WRITE (KLUN) YD%COEF_CM4
WRITE (KLUN) YD%COEF_RM1
WRITE (KLUN) YD%COEF_RM2
WRITE (KLUN) YD%COEF_IM1
WRITE (KLUN) YD%COEF_IM2
WRITE (KLUN) YD%COEF_SM1
WRITE (KLUN) YD%COEF_SM2
WRITE (KLUN) YD%COEF_GM1
WRITE (KLUN) YD%COEF_GM2
END SUBROUTINE

SUBROUTINE LOAD_TDVISI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDVISI), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%HVISI
READ (KLUN) YD%COEF_CM1
READ (KLUN) YD%COEF_CM2
READ (KLUN) YD%COEF_CM3
READ (KLUN) YD%COEF_CM4
READ (KLUN) YD%COEF_RM1
READ (KLUN) YD%COEF_RM2
READ (KLUN) YD%COEF_IM1
READ (KLUN) YD%COEF_IM2
READ (KLUN) YD%COEF_SM1
READ (KLUN) YD%COEF_SM2
READ (KLUN) YD%COEF_GM1
READ (KLUN) YD%COEF_GM2
END SUBROUTINE


SUBROUTINE COPY_TDVISI (YD, LDCREATED)

IMPLICIT NONE
TYPE (TDVISI), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF













END SUBROUTINE

SUBROUTINE WIPE_TDVISI (YD, LDDELETED)

IMPLICIT NONE
TYPE (TDVISI), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED














LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
