MODULE UTIL_MODEL_DIAGNOSTICS_TYPE_MOD

USE MODEL_DIAGNOSTICS_MOD, ONLY : MODEL_DIAGNOSTICS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_DIAGNOSTICS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DIAGNOSTICS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_DIAGNOSTICS_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_DIAGNOSTICS_TYPE (KLUN, YD)
USE UTIL_TCDDH_MOD
USE UTIL_TGPDDH_MOD
USE UTIL_TLDDH_MOD
USE UTIL_TMDDH_MOD
USE UTIL_TPADDH_MOD
USE UTIL_TSDDH_MOD
USE UTIL_TSPDDH_MOD
USE UTIL_TTDDH_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRCDDH)
CALL SAVE (KLUN, YD%YRLDDH)
CALL SAVE (KLUN, YD%YRMDDH)
CALL SAVE (KLUN, YD%YRSDDH)
CALL SAVE (KLUN, YD%YRTDDH)
CALL SAVE (KLUN, YD%YRGPDDH)
CALL SAVE (KLUN, YD%YRPADDH)
CALL SAVE (KLUN, YD%YRSPDDH)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_DIAGNOSTICS_TYPE (KLUN, YD)
USE UTIL_TCDDH_MOD
USE UTIL_TGPDDH_MOD
USE UTIL_TLDDH_MOD
USE UTIL_TMDDH_MOD
USE UTIL_TPADDH_MOD
USE UTIL_TSDDH_MOD
USE UTIL_TSPDDH_MOD
USE UTIL_TTDDH_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRCDDH)
CALL LOAD (KLUN, YD%YRLDDH)
CALL LOAD (KLUN, YD%YRMDDH)
CALL LOAD (KLUN, YD%YRSDDH)
CALL LOAD (KLUN, YD%YRTDDH)
CALL LOAD (KLUN, YD%YRGPDDH)
CALL LOAD (KLUN, YD%YRPADDH)
CALL LOAD (KLUN, YD%YRSPDDH)
END SUBROUTINE


SUBROUTINE COPY_MODEL_DIAGNOSTICS_TYPE (YD, LDCREATED)
USE UTIL_TCDDH_MOD
USE UTIL_TGPDDH_MOD
USE UTIL_TLDDH_MOD
USE UTIL_TMDDH_MOD
USE UTIL_TPADDH_MOD
USE UTIL_TSDDH_MOD
USE UTIL_TSPDDH_MOD
USE UTIL_TTDDH_MOD
IMPLICIT NONE
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRCDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRLDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRMDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRSDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRTDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRGPDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRPADDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRSPDDH, LDCREATED=.TRUE.)

END SUBROUTINE



END MODULE
