MODULE UTIL_TOZO_MOD

USE YOMOZO, ONLY : TOZO

INTERFACE SAVE
MODULE PROCEDURE SAVE_TOZO
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TOZO
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TOZO
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TOZO
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TOZO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOZO), INTENT (IN), TARGET :: YD
LOGICAL :: LTOZ2DG, LTOZ2DL, LTOZ3DBL
LTOZ2DG = ALLOCATED (YD%TOZ2DG)
WRITE (KLUN) LTOZ2DG
IF (LTOZ2DG) THEN
  WRITE (KLUN) LBOUND (YD%TOZ2DG)
  WRITE (KLUN) UBOUND (YD%TOZ2DG)
  WRITE (KLUN) YD%TOZ2DG
ENDIF
LTOZ2DL = ALLOCATED (YD%TOZ2DL)
WRITE (KLUN) LTOZ2DL
IF (LTOZ2DL) THEN
  WRITE (KLUN) LBOUND (YD%TOZ2DL)
  WRITE (KLUN) UBOUND (YD%TOZ2DL)
  WRITE (KLUN) YD%TOZ2DL
ENDIF
LTOZ3DBL = ALLOCATED (YD%TOZ3DBL)
WRITE (KLUN) LTOZ3DBL
IF (LTOZ3DBL) THEN
  WRITE (KLUN) LBOUND (YD%TOZ3DBL)
  WRITE (KLUN) UBOUND (YD%TOZ3DBL)
  WRITE (KLUN) YD%TOZ3DBL
ENDIF
WRITE (KLUN) YD%TEECL2
END SUBROUTINE

SUBROUTINE LOAD_TOZO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOZO), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LTOZ2DG, LTOZ2DL, LTOZ3DBL
READ (KLUN) LTOZ2DG
IF (LTOZ2DG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TOZ2DG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TOZ2DG
ENDIF
READ (KLUN) LTOZ2DL
IF (LTOZ2DL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TOZ2DL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TOZ2DL
ENDIF
READ (KLUN) LTOZ3DBL
IF (LTOZ3DBL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TOZ3DBL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TOZ3DBL
ENDIF
READ (KLUN) YD%TEECL2
END SUBROUTINE


SUBROUTINE COPY_TOZO (YD, LDCREATED)

IMPLICIT NONE
TYPE (TOZO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LTOZ2DG, LTOZ2DL, LTOZ3DBL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LTOZ2DG = ALLOCATED (YD%TOZ2DG)
IF (LTOZ2DG) THEN
  !$acc enter data create (YD%TOZ2DG)
  !$acc update device (YD%TOZ2DG)
  !$acc enter data attach (YD%TOZ2DG)
ENDIF

LTOZ2DL = ALLOCATED (YD%TOZ2DL)
IF (LTOZ2DL) THEN
  !$acc enter data create (YD%TOZ2DL)
  !$acc update device (YD%TOZ2DL)
  !$acc enter data attach (YD%TOZ2DL)
ENDIF

LTOZ3DBL = ALLOCATED (YD%TOZ3DBL)
IF (LTOZ3DBL) THEN
  !$acc enter data create (YD%TOZ3DBL)
  !$acc update device (YD%TOZ3DBL)
  !$acc enter data attach (YD%TOZ3DBL)
ENDIF


END SUBROUTINE

SUBROUTINE WIPE_TOZO (YD, LDDELETED)

IMPLICIT NONE
TYPE (TOZO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LTOZ2DG, LTOZ2DL, LTOZ3DBL

LTOZ2DG = ALLOCATED (YD%TOZ2DG)
IF (LTOZ2DG) THEN
  !$acc exit data detach (YD%TOZ2DG)
  !$acc exit data delete (YD%TOZ2DG)
ENDIF

LTOZ2DL = ALLOCATED (YD%TOZ2DL)
IF (LTOZ2DL) THEN
  !$acc exit data detach (YD%TOZ2DL)
  !$acc exit data delete (YD%TOZ2DL)
ENDIF

LTOZ3DBL = ALLOCATED (YD%TOZ3DBL)
IF (LTOZ3DBL) THEN
  !$acc exit data detach (YD%TOZ3DBL)
  !$acc exit data delete (YD%TOZ3DBL)
ENDIF


LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
