MODULE UTIL_TACVGRIB_MOD

USE TYPE_ACV, ONLY : TACVGRIB

INTERFACE SAVE
MODULE PROCEDURE SAVE_TACVGRIB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TACVGRIB
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TACVGRIB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACVGRIB), INTENT (IN), TARGET :: YD
LOGICAL :: LMACVGRB_1D, LMACVGRB_2D, LMACVGRB_3D, LMACVGRB_ALL
LMACVGRB_1D = ALLOCATED (YD%MACVGRB_1D)
WRITE (KLUN) LMACVGRB_1D
IF (LMACVGRB_1D) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_1D)
  WRITE (KLUN) UBOUND (YD%MACVGRB_1D)
  WRITE (KLUN) YD%MACVGRB_1D
ENDIF
LMACVGRB_2D = ALLOCATED (YD%MACVGRB_2D)
WRITE (KLUN) LMACVGRB_2D
IF (LMACVGRB_2D) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_2D)
  WRITE (KLUN) UBOUND (YD%MACVGRB_2D)
  WRITE (KLUN) YD%MACVGRB_2D
ENDIF
LMACVGRB_3D = ALLOCATED (YD%MACVGRB_3D)
WRITE (KLUN) LMACVGRB_3D
IF (LMACVGRB_3D) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_3D)
  WRITE (KLUN) UBOUND (YD%MACVGRB_3D)
  WRITE (KLUN) YD%MACVGRB_3D
ENDIF
LMACVGRB_ALL = ALLOCATED (YD%MACVGRB_ALL)
WRITE (KLUN) LMACVGRB_ALL
IF (LMACVGRB_ALL) THEN
  WRITE (KLUN) LBOUND (YD%MACVGRB_ALL)
  WRITE (KLUN) UBOUND (YD%MACVGRB_ALL)
  WRITE (KLUN) YD%MACVGRB_ALL
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TACVGRIB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TACVGRIB), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMACVGRB_1D, LMACVGRB_2D, LMACVGRB_3D, LMACVGRB_ALL
READ (KLUN) LMACVGRB_1D
IF (LMACVGRB_1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_1D (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_1D
ENDIF
READ (KLUN) LMACVGRB_2D
IF (LMACVGRB_2D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_2D (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_2D
ENDIF
READ (KLUN) LMACVGRB_3D
IF (LMACVGRB_3D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_3D (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_3D
ENDIF
READ (KLUN) LMACVGRB_ALL
IF (LMACVGRB_ALL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MACVGRB_ALL (IL1(1):IU1(1)))
  READ (KLUN) YD%MACVGRB_ALL
ENDIF
END SUBROUTINE






END MODULE
