MODULE UTIL_TCOU_MOD

USE YOMCOU, ONLY : TCOU

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCOU
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCOU
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCOU
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCOU (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOU), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NCULF
WRITE (KLUN) YD%NPIAT
WRITE (KLUN) YD%NCULMR
WRITE (KLUN) YD%NCULMW
END SUBROUTINE

SUBROUTINE LOAD_TCOU (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOU), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NCULF
READ (KLUN) YD%NPIAT
READ (KLUN) YD%NCULMR
READ (KLUN) YD%NCULMW
END SUBROUTINE


SUBROUTINE COPY_TCOU (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCOU), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




END SUBROUTINE



END MODULE
