MODULE UTIL_CPG_DYN_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_DYN_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_DYN_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_DYN_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_CPG_DYN_TYPE (KLUN, YD)
USE UTIL_CPG_CTY_TYPE_MOD
USE UTIL_CPG_HWIND_TYPE_MOD
USE UTIL_CPG_RCP_TYPE_MOD
USE UTIL_CPG_XYB_TYPE_MOD
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_DYN_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_DBBC, LF_GWFL, LF_GWFM, LF_GWFT, LF_GWS, LF_GWT, LF_KENE, LF_NHPREF, LF_NHPREH, LF_NHX
LOGICAL :: LF_NHY, LF_OROGL, LF_OROGM, LF_PHI, LF_PHIF, LF_PHIFL, LF_PHIFM, LF_PRE, LF_PREF, LF_PREL
LOGICAL :: LF_PREM, LF_QCHAL, LF_QCHAM, LF_RDPHI, LF_RTL, LF_RTM, LF_WRL
LF_OROGL = ASSOCIATED (YD%F_OROGL)
WRITE (KLUN) LF_OROGL
IF (LF_OROGL) THEN
  CALL SAVE (KLUN, YD%F_OROGL)
ENDIF
LF_OROGM = ASSOCIATED (YD%F_OROGM)
WRITE (KLUN) LF_OROGM
IF (LF_OROGM) THEN
  CALL SAVE (KLUN, YD%F_OROGM)
ENDIF
LF_PHI = ASSOCIATED (YD%F_PHI)
WRITE (KLUN) LF_PHI
IF (LF_PHI) THEN
  CALL SAVE (KLUN, YD%F_PHI)
ENDIF
LF_PRE = ASSOCIATED (YD%F_PRE)
WRITE (KLUN) LF_PRE
IF (LF_PRE) THEN
  CALL SAVE (KLUN, YD%F_PRE)
ENDIF
LF_PHIF = ASSOCIATED (YD%F_PHIF)
WRITE (KLUN) LF_PHIF
IF (LF_PHIF) THEN
  CALL SAVE (KLUN, YD%F_PHIF)
ENDIF
LF_PREF = ASSOCIATED (YD%F_PREF)
WRITE (KLUN) LF_PREF
IF (LF_PREF) THEN
  CALL SAVE (KLUN, YD%F_PREF)
ENDIF
LF_WRL = ASSOCIATED (YD%F_WRL)
WRITE (KLUN) LF_WRL
IF (LF_WRL) THEN
  CALL SAVE (KLUN, YD%F_WRL)
ENDIF
LF_PREL = ASSOCIATED (YD%F_PREL)
WRITE (KLUN) LF_PREL
IF (LF_PREL) THEN
  CALL SAVE (KLUN, YD%F_PREL)
ENDIF
LF_PREM = ASSOCIATED (YD%F_PREM)
WRITE (KLUN) LF_PREM
IF (LF_PREM) THEN
  CALL SAVE (KLUN, YD%F_PREM)
ENDIF
LF_NHY = ASSOCIATED (YD%F_NHY)
WRITE (KLUN) LF_NHY
IF (LF_NHY) THEN
  CALL SAVE (KLUN, YD%F_NHY)
ENDIF
LF_GWFT = ASSOCIATED (YD%F_GWFT)
WRITE (KLUN) LF_GWFT
IF (LF_GWFT) THEN
  CALL SAVE (KLUN, YD%F_GWFT)
ENDIF
LF_KENE = ASSOCIATED (YD%F_KENE)
WRITE (KLUN) LF_KENE
IF (LF_KENE) THEN
  CALL SAVE (KLUN, YD%F_KENE)
ENDIF
LF_NHX = ASSOCIATED (YD%F_NHX)
WRITE (KLUN) LF_NHX
IF (LF_NHX) THEN
  CALL SAVE (KLUN, YD%F_NHX)
ENDIF
LF_PHIFL = ASSOCIATED (YD%F_PHIFL)
WRITE (KLUN) LF_PHIFL
IF (LF_PHIFL) THEN
  CALL SAVE (KLUN, YD%F_PHIFL)
ENDIF
LF_PHIFM = ASSOCIATED (YD%F_PHIFM)
WRITE (KLUN) LF_PHIFM
IF (LF_PHIFM) THEN
  CALL SAVE (KLUN, YD%F_PHIFM)
ENDIF
LF_RTL = ASSOCIATED (YD%F_RTL)
WRITE (KLUN) LF_RTL
IF (LF_RTL) THEN
  CALL SAVE (KLUN, YD%F_RTL)
ENDIF
LF_RTM = ASSOCIATED (YD%F_RTM)
WRITE (KLUN) LF_RTM
IF (LF_RTM) THEN
  CALL SAVE (KLUN, YD%F_RTM)
ENDIF
CALL SAVE (KLUN, YD%RCP)
CALL SAVE (KLUN, YD%CTY)
CALL SAVE (KLUN, YD%UVH)
CALL SAVE (KLUN, YD%XYB)
LF_DBBC = ASSOCIATED (YD%F_DBBC)
WRITE (KLUN) LF_DBBC
IF (LF_DBBC) THEN
  CALL SAVE (KLUN, YD%F_DBBC)
ENDIF
LF_GWS = ASSOCIATED (YD%F_GWS)
WRITE (KLUN) LF_GWS
IF (LF_GWS) THEN
  CALL SAVE (KLUN, YD%F_GWS)
ENDIF
LF_GWFL = ASSOCIATED (YD%F_GWFL)
WRITE (KLUN) LF_GWFL
IF (LF_GWFL) THEN
  CALL SAVE (KLUN, YD%F_GWFL)
ENDIF
LF_GWFM = ASSOCIATED (YD%F_GWFM)
WRITE (KLUN) LF_GWFM
IF (LF_GWFM) THEN
  CALL SAVE (KLUN, YD%F_GWFM)
ENDIF
LF_GWT = ASSOCIATED (YD%F_GWT)
WRITE (KLUN) LF_GWT
IF (LF_GWT) THEN
  CALL SAVE (KLUN, YD%F_GWT)
ENDIF
LF_NHPREF = ASSOCIATED (YD%F_NHPREF)
WRITE (KLUN) LF_NHPREF
IF (LF_NHPREF) THEN
  CALL SAVE (KLUN, YD%F_NHPREF)
ENDIF
LF_NHPREH = ASSOCIATED (YD%F_NHPREH)
WRITE (KLUN) LF_NHPREH
IF (LF_NHPREH) THEN
  CALL SAVE (KLUN, YD%F_NHPREH)
ENDIF
LF_QCHAL = ASSOCIATED (YD%F_QCHAL)
WRITE (KLUN) LF_QCHAL
IF (LF_QCHAL) THEN
  CALL SAVE (KLUN, YD%F_QCHAL)
ENDIF
LF_QCHAM = ASSOCIATED (YD%F_QCHAM)
WRITE (KLUN) LF_QCHAM
IF (LF_QCHAM) THEN
  CALL SAVE (KLUN, YD%F_QCHAM)
ENDIF
LF_RDPHI = ASSOCIATED (YD%F_RDPHI)
WRITE (KLUN) LF_RDPHI
IF (LF_RDPHI) THEN
  CALL SAVE (KLUN, YD%F_RDPHI)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_DYN_TYPE (KLUN, YD)
USE UTIL_CPG_CTY_TYPE_MOD
USE UTIL_CPG_HWIND_TYPE_MOD
USE UTIL_CPG_RCP_TYPE_MOD
USE UTIL_CPG_XYB_TYPE_MOD
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_DYN_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_DBBC, LF_GWFL, LF_GWFM, LF_GWFT, LF_GWS, LF_GWT, LF_KENE, LF_NHPREF, LF_NHPREH, LF_NHX
LOGICAL :: LF_NHY, LF_OROGL, LF_OROGM, LF_PHI, LF_PHIF, LF_PHIFL, LF_PHIFM, LF_PRE, LF_PREF, LF_PREL
LOGICAL :: LF_PREM, LF_QCHAL, LF_QCHAM, LF_RDPHI, LF_RTL, LF_RTM, LF_WRL
NULLIFY (YD%OROGL)
READ (KLUN) LF_OROGL
IF (LF_OROGL) THEN
  CALL LOAD (KLUN, YD%F_OROGL)
ELSE
  NULLIFY (YD%F_OROGL)
ENDIF
NULLIFY (YD%OROGM)
READ (KLUN) LF_OROGM
IF (LF_OROGM) THEN
  CALL LOAD (KLUN, YD%F_OROGM)
ELSE
  NULLIFY (YD%F_OROGM)
ENDIF
NULLIFY (YD%PHI)
READ (KLUN) LF_PHI
IF (LF_PHI) THEN
  CALL LOAD (KLUN, YD%F_PHI)
ELSE
  NULLIFY (YD%F_PHI)
ENDIF
NULLIFY (YD%PRE)
READ (KLUN) LF_PRE
IF (LF_PRE) THEN
  CALL LOAD (KLUN, YD%F_PRE)
ELSE
  NULLIFY (YD%F_PRE)
ENDIF
NULLIFY (YD%PHIF)
READ (KLUN) LF_PHIF
IF (LF_PHIF) THEN
  CALL LOAD (KLUN, YD%F_PHIF)
ELSE
  NULLIFY (YD%F_PHIF)
ENDIF
NULLIFY (YD%PREF)
READ (KLUN) LF_PREF
IF (LF_PREF) THEN
  CALL LOAD (KLUN, YD%F_PREF)
ELSE
  NULLIFY (YD%F_PREF)
ENDIF
NULLIFY (YD%WRL)
READ (KLUN) LF_WRL
IF (LF_WRL) THEN
  CALL LOAD (KLUN, YD%F_WRL)
ELSE
  NULLIFY (YD%F_WRL)
ENDIF
NULLIFY (YD%PREL)
READ (KLUN) LF_PREL
IF (LF_PREL) THEN
  CALL LOAD (KLUN, YD%F_PREL)
ELSE
  NULLIFY (YD%F_PREL)
ENDIF
NULLIFY (YD%PREM)
READ (KLUN) LF_PREM
IF (LF_PREM) THEN
  CALL LOAD (KLUN, YD%F_PREM)
ELSE
  NULLIFY (YD%F_PREM)
ENDIF
NULLIFY (YD%NHY)
READ (KLUN) LF_NHY
IF (LF_NHY) THEN
  CALL LOAD (KLUN, YD%F_NHY)
ELSE
  NULLIFY (YD%F_NHY)
ENDIF
NULLIFY (YD%GWFT)
READ (KLUN) LF_GWFT
IF (LF_GWFT) THEN
  CALL LOAD (KLUN, YD%F_GWFT)
ELSE
  NULLIFY (YD%F_GWFT)
ENDIF
NULLIFY (YD%KENE)
READ (KLUN) LF_KENE
IF (LF_KENE) THEN
  CALL LOAD (KLUN, YD%F_KENE)
ELSE
  NULLIFY (YD%F_KENE)
ENDIF
NULLIFY (YD%NHX)
READ (KLUN) LF_NHX
IF (LF_NHX) THEN
  CALL LOAD (KLUN, YD%F_NHX)
ELSE
  NULLIFY (YD%F_NHX)
ENDIF
NULLIFY (YD%PHIFL)
READ (KLUN) LF_PHIFL
IF (LF_PHIFL) THEN
  CALL LOAD (KLUN, YD%F_PHIFL)
ELSE
  NULLIFY (YD%F_PHIFL)
ENDIF
NULLIFY (YD%PHIFM)
READ (KLUN) LF_PHIFM
IF (LF_PHIFM) THEN
  CALL LOAD (KLUN, YD%F_PHIFM)
ELSE
  NULLIFY (YD%F_PHIFM)
ENDIF
NULLIFY (YD%RTL)
READ (KLUN) LF_RTL
IF (LF_RTL) THEN
  CALL LOAD (KLUN, YD%F_RTL)
ELSE
  NULLIFY (YD%F_RTL)
ENDIF
NULLIFY (YD%RTM)
READ (KLUN) LF_RTM
IF (LF_RTM) THEN
  CALL LOAD (KLUN, YD%F_RTM)
ELSE
  NULLIFY (YD%F_RTM)
ENDIF
CALL LOAD (KLUN, YD%RCP)
CALL LOAD (KLUN, YD%CTY)
CALL LOAD (KLUN, YD%UVH)
CALL LOAD (KLUN, YD%XYB)
NULLIFY (YD%DBBC)
READ (KLUN) LF_DBBC
IF (LF_DBBC) THEN
  CALL LOAD (KLUN, YD%F_DBBC)
ELSE
  NULLIFY (YD%F_DBBC)
ENDIF
NULLIFY (YD%GWS)
READ (KLUN) LF_GWS
IF (LF_GWS) THEN
  CALL LOAD (KLUN, YD%F_GWS)
ELSE
  NULLIFY (YD%F_GWS)
ENDIF
NULLIFY (YD%GWFL)
READ (KLUN) LF_GWFL
IF (LF_GWFL) THEN
  CALL LOAD (KLUN, YD%F_GWFL)
ELSE
  NULLIFY (YD%F_GWFL)
ENDIF
NULLIFY (YD%GWFM)
READ (KLUN) LF_GWFM
IF (LF_GWFM) THEN
  CALL LOAD (KLUN, YD%F_GWFM)
ELSE
  NULLIFY (YD%F_GWFM)
ENDIF
NULLIFY (YD%GWT)
READ (KLUN) LF_GWT
IF (LF_GWT) THEN
  CALL LOAD (KLUN, YD%F_GWT)
ELSE
  NULLIFY (YD%F_GWT)
ENDIF
NULLIFY (YD%NHPREF)
READ (KLUN) LF_NHPREF
IF (LF_NHPREF) THEN
  CALL LOAD (KLUN, YD%F_NHPREF)
ELSE
  NULLIFY (YD%F_NHPREF)
ENDIF
NULLIFY (YD%NHPREH)
READ (KLUN) LF_NHPREH
IF (LF_NHPREH) THEN
  CALL LOAD (KLUN, YD%F_NHPREH)
ELSE
  NULLIFY (YD%F_NHPREH)
ENDIF
NULLIFY (YD%QCHAL)
READ (KLUN) LF_QCHAL
IF (LF_QCHAL) THEN
  CALL LOAD (KLUN, YD%F_QCHAL)
ELSE
  NULLIFY (YD%F_QCHAL)
ENDIF
NULLIFY (YD%QCHAM)
READ (KLUN) LF_QCHAM
IF (LF_QCHAM) THEN
  CALL LOAD (KLUN, YD%F_QCHAM)
ELSE
  NULLIFY (YD%F_QCHAM)
ENDIF
NULLIFY (YD%RDPHI)
READ (KLUN) LF_RDPHI
IF (LF_RDPHI) THEN
  CALL LOAD (KLUN, YD%F_RDPHI)
ELSE
  NULLIFY (YD%F_RDPHI)
ENDIF
END SUBROUTINE






END MODULE
