MODULE UTIL_SURFACE_VARIABLE_GROUP_RESVR_MOD

USE SURFACE_VARIABLES_MOD, ONLY : SURFACE_VARIABLE_GROUP_RESVR

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VARIABLE_GROUP_RESVR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VARIABLE_GROUP_RESVR
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VARIABLE_GROUP_RESVR
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VARIABLE_GROUP_RESVR
END INTERFACE



CONTAINS

SUBROUTINE SAVE_SURFACE_VARIABLE_GROUP_RESVR (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VARIABLE_GROUP_RESVR), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%VT)
CALL SAVE (KLUN, YD%VW)
CALL SAVE (KLUN, YD%VFC)
CALL SAVE (KLUN, YD%VIC)
CALL SAVE (KLUN, YD%VFP1)
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VARIABLE_GROUP_RESVR (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VARIABLE_GROUP_RESVR), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%VT)
CALL LOAD (KLUN, YD%VW)
CALL LOAD (KLUN, YD%VFC)
CALL LOAD (KLUN, YD%VIC)
CALL LOAD (KLUN, YD%VFP1)
NULLIFY (YD%F_GROUP)
END SUBROUTINE


SUBROUTINE COPY_SURFACE_VARIABLE_GROUP_RESVR (YD, LDCREATED)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_RESVR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%VT, LDCREATED=.TRUE.)

CALL COPY (YD%VW, LDCREATED=.TRUE.)

CALL COPY (YD%VFC, LDCREATED=.TRUE.)

CALL COPY (YD%VIC, LDCREATED=.TRUE.)

CALL COPY (YD%VFP1, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_SURFACE_VARIABLE_GROUP_RESVR (YD, LDDELETED)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_RESVR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%VT, LDDELETED=.TRUE.)

CALL WIPE (YD%VW, LDDELETED=.TRUE.)

CALL WIPE (YD%VFC, LDDELETED=.TRUE.)

CALL WIPE (YD%VIC, LDDELETED=.TRUE.)

CALL WIPE (YD%VFP1, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
