MODULE UTIL_STACK_MOD

USE STACK_MOD, ONLY : STACK



INTERFACE COPY
MODULE PROCEDURE COPY_STACK
END INTERFACE



CONTAINS





SUBROUTINE COPY_STACK (YD, LDCREATED)
USE UTIL_FIELD_MOD
IMPLICIT NONE
TYPE (STACK), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_P

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LF_P = ASSOCIATED (YD%F_P)
IF (LF_P) THEN
  !$acc enter data create (YD%F_P)
  !$acc update device (YD%F_P)
  CALL COPY (YD%F_P, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_P)
ENDIF



END SUBROUTINE



END MODULE
