MODULE UTIL_CPG_XYB_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_XYB_TYPE
USE UTIL_FIELD_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_XYB_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_XYB_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPG_XYB_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_XYB_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_CPG_XYB_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_XYB_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_ALPH, LF_DELP, LF_LNPR, LF_RDELP, LF_RPP, LF_RPRE, LF_RTGR

WRITE (KLUN) YD%LOWNED
WRITE (KLUN) YD%IP_DELP
LF_DELP = ASSOCIATED (YD%F_DELP)
WRITE (KLUN) LF_DELP
IF (LF_DELP) THEN
  CALL SAVE (KLUN, YD%F_DELP)
ENDIF
WRITE (KLUN) YD%IP_RDELP
LF_RDELP = ASSOCIATED (YD%F_RDELP)
WRITE (KLUN) LF_RDELP
IF (LF_RDELP) THEN
  CALL SAVE (KLUN, YD%F_RDELP)
ENDIF
WRITE (KLUN) YD%IP_LNPR
LF_LNPR = ASSOCIATED (YD%F_LNPR)
WRITE (KLUN) LF_LNPR
IF (LF_LNPR) THEN
  CALL SAVE (KLUN, YD%F_LNPR)
ENDIF
WRITE (KLUN) YD%IP_ALPH
LF_ALPH = ASSOCIATED (YD%F_ALPH)
WRITE (KLUN) LF_ALPH
IF (LF_ALPH) THEN
  CALL SAVE (KLUN, YD%F_ALPH)
ENDIF
WRITE (KLUN) YD%IP_RTGR
LF_RTGR = ASSOCIATED (YD%F_RTGR)
WRITE (KLUN) LF_RTGR
IF (LF_RTGR) THEN
  CALL SAVE (KLUN, YD%F_RTGR)
ENDIF
WRITE (KLUN) YD%IP_RPRE
LF_RPRE = ASSOCIATED (YD%F_RPRE)
WRITE (KLUN) LF_RPRE
IF (LF_RPRE) THEN
  CALL SAVE (KLUN, YD%F_RPRE)
ENDIF
WRITE (KLUN) YD%IP_RPP
LF_RPP = ASSOCIATED (YD%F_RPP)
WRITE (KLUN) LF_RPP
IF (LF_RPP) THEN
  CALL SAVE (KLUN, YD%F_RPP)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_XYB_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_XYB_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_ALPH, LF_DELP, LF_LNPR, LF_RDELP, LF_RPP, LF_RPRE, LF_RTGR

READ (KLUN) YD%LOWNED
NULLIFY (YD%ZVIEW)
NULLIFY (YD%ZDATA)
NULLIFY (YD%F_DATA)
READ (KLUN) YD%IP_DELP
NULLIFY (YD%DELP)
READ (KLUN) LF_DELP
IF (LF_DELP) THEN
  CALL LOAD (KLUN, YD%F_DELP)
ELSE
  NULLIFY (YD%F_DELP)
ENDIF
READ (KLUN) YD%IP_RDELP
NULLIFY (YD%RDELP)
READ (KLUN) LF_RDELP
IF (LF_RDELP) THEN
  CALL LOAD (KLUN, YD%F_RDELP)
ELSE
  NULLIFY (YD%F_RDELP)
ENDIF
READ (KLUN) YD%IP_LNPR
NULLIFY (YD%LNPR)
READ (KLUN) LF_LNPR
IF (LF_LNPR) THEN
  CALL LOAD (KLUN, YD%F_LNPR)
ELSE
  NULLIFY (YD%F_LNPR)
ENDIF
READ (KLUN) YD%IP_ALPH
NULLIFY (YD%ALPH)
READ (KLUN) LF_ALPH
IF (LF_ALPH) THEN
  CALL LOAD (KLUN, YD%F_ALPH)
ELSE
  NULLIFY (YD%F_ALPH)
ENDIF
READ (KLUN) YD%IP_RTGR
NULLIFY (YD%RTGR)
READ (KLUN) LF_RTGR
IF (LF_RTGR) THEN
  CALL LOAD (KLUN, YD%F_RTGR)
ELSE
  NULLIFY (YD%F_RTGR)
ENDIF
READ (KLUN) YD%IP_RPRE
NULLIFY (YD%RPRE)
READ (KLUN) LF_RPRE
IF (LF_RPRE) THEN
  CALL LOAD (KLUN, YD%F_RPRE)
ELSE
  NULLIFY (YD%F_RPRE)
ENDIF
READ (KLUN) YD%IP_RPP
NULLIFY (YD%RPP)
READ (KLUN) LF_RPP
IF (LF_RPP) THEN
  CALL LOAD (KLUN, YD%F_RPP)
ELSE
  NULLIFY (YD%F_RPP)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_CPG_XYB_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (CPG_XYB_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_ALPH, LF_DELP, LF_LNPR, LF_RDELP, LF_RPP, LF_RPRE, LF_RTGR

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF


LF_DELP = ASSOCIATED (YD%F_DELP)
IF (LF_DELP) THEN
  !$acc enter data create (YD%F_DELP)
  !$acc update device (YD%F_DELP)
  CALL COPY (YD%F_DELP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_DELP)
ENDIF


LF_RDELP = ASSOCIATED (YD%F_RDELP)
IF (LF_RDELP) THEN
  !$acc enter data create (YD%F_RDELP)
  !$acc update device (YD%F_RDELP)
  CALL COPY (YD%F_RDELP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RDELP)
ENDIF


LF_LNPR = ASSOCIATED (YD%F_LNPR)
IF (LF_LNPR) THEN
  !$acc enter data create (YD%F_LNPR)
  !$acc update device (YD%F_LNPR)
  CALL COPY (YD%F_LNPR, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_LNPR)
ENDIF


LF_ALPH = ASSOCIATED (YD%F_ALPH)
IF (LF_ALPH) THEN
  !$acc enter data create (YD%F_ALPH)
  !$acc update device (YD%F_ALPH)
  CALL COPY (YD%F_ALPH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_ALPH)
ENDIF


LF_RTGR = ASSOCIATED (YD%F_RTGR)
IF (LF_RTGR) THEN
  !$acc enter data create (YD%F_RTGR)
  !$acc update device (YD%F_RTGR)
  CALL COPY (YD%F_RTGR, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RTGR)
ENDIF


LF_RPRE = ASSOCIATED (YD%F_RPRE)
IF (LF_RPRE) THEN
  !$acc enter data create (YD%F_RPRE)
  !$acc update device (YD%F_RPRE)
  CALL COPY (YD%F_RPRE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RPRE)
ENDIF


LF_RPP = ASSOCIATED (YD%F_RPP)
IF (LF_RPP) THEN
  !$acc enter data create (YD%F_RPP)
  !$acc update device (YD%F_RPP)
  CALL COPY (YD%F_RPP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RPP)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_CPG_XYB_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (CPG_XYB_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LF_ALPH, LF_DELP, LF_LNPR, LF_RDELP, LF_RPP, LF_RPRE, LF_RTGR



LF_DELP = ASSOCIATED (YD%F_DELP)
IF (LF_DELP) THEN
  !$acc exit data detach (YD%F_DELP)
  CALL WIPE (YD%F_DELP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_DELP)
ENDIF


LF_RDELP = ASSOCIATED (YD%F_RDELP)
IF (LF_RDELP) THEN
  !$acc exit data detach (YD%F_RDELP)
  CALL WIPE (YD%F_RDELP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RDELP)
ENDIF


LF_LNPR = ASSOCIATED (YD%F_LNPR)
IF (LF_LNPR) THEN
  !$acc exit data detach (YD%F_LNPR)
  CALL WIPE (YD%F_LNPR, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_LNPR)
ENDIF


LF_ALPH = ASSOCIATED (YD%F_ALPH)
IF (LF_ALPH) THEN
  !$acc exit data detach (YD%F_ALPH)
  CALL WIPE (YD%F_ALPH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_ALPH)
ENDIF


LF_RTGR = ASSOCIATED (YD%F_RTGR)
IF (LF_RTGR) THEN
  !$acc exit data detach (YD%F_RTGR)
  CALL WIPE (YD%F_RTGR, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RTGR)
ENDIF


LF_RPRE = ASSOCIATED (YD%F_RPRE)
IF (LF_RPRE) THEN
  !$acc exit data detach (YD%F_RPRE)
  CALL WIPE (YD%F_RPRE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RPRE)
ENDIF


LF_RPP = ASSOCIATED (YD%F_RPP)
IF (LF_RPP) THEN
  !$acc exit data detach (YD%F_RPP)
  CALL WIPE (YD%F_RPP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RPP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
