MODULE UTIL_TTNH_MOD

USE YOMTNH, ONLY : TTNH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTNH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTNH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TTNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTNH), INTENT (IN), TARGET :: YD
LOGICAL :: LTRAJNH
WRITE (KLUN) YD%NLENNH95B
LTRAJNH = ALLOCATED (YD%TRAJNH)
WRITE (KLUN) LTRAJNH
IF (LTRAJNH) THEN
  WRITE (KLUN) LBOUND (YD%TRAJNH)
  WRITE (KLUN) UBOUND (YD%TRAJNH)
  WRITE (KLUN) YD%TRAJNH
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TTNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTNH), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LTRAJNH
READ (KLUN) YD%NLENNH95B
READ (KLUN) LTRAJNH
IF (LTRAJNH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TRAJNH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TRAJNH
ENDIF
END SUBROUTINE




END MODULE
