MODULE UTIL_MF_PHYS_SURF_TYPE_MOD

USE MF_PHYS_SURFACE_TYPE_MOD, ONLY : MF_PHYS_SURF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MF_PHYS_SURF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MF_PHYS_SURF_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MF_PHYS_SURF_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MF_PHYS_SURF_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MF_PHYS_SURF_TYPE (KLUN, YD)
USE UTIL_SURFACE_VIEW_GROUP_CLS_MOD
USE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD
USE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MF_PHYS_SURF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%GSP_SG)
CALL SAVE (KLUN, YD%GSP_RR)
CALL SAVE (KLUN, YD%GSP_CL)
CALL SAVE (KLUN, YD%GSD_XP)
CALL SAVE (KLUN, YD%GSD_XP2)
END SUBROUTINE

SUBROUTINE LOAD_MF_PHYS_SURF_TYPE (KLUN, YD)
USE UTIL_SURFACE_VIEW_GROUP_CLS_MOD
USE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD
USE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MF_PHYS_SURF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%GSP_SG)
CALL LOAD (KLUN, YD%GSP_RR)
CALL LOAD (KLUN, YD%GSP_CL)
CALL LOAD (KLUN, YD%GSD_XP)
CALL LOAD (KLUN, YD%GSD_XP2)
END SUBROUTINE


SUBROUTINE COPY_MF_PHYS_SURF_TYPE (YD, LDCREATED)
USE UTIL_SURFACE_VIEW_GROUP_CLS_MOD
USE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD
USE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD
IMPLICIT NONE
TYPE (MF_PHYS_SURF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%GSP_SG, LDCREATED=.TRUE.)

CALL COPY (YD%GSP_RR, LDCREATED=.TRUE.)

CALL COPY (YD%GSP_CL, LDCREATED=.TRUE.)

CALL COPY (YD%GSD_XP, LDCREATED=.TRUE.)

CALL COPY (YD%GSD_XP2, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MF_PHYS_SURF_TYPE (YD, LDDELETED)
USE UTIL_SURFACE_VIEW_GROUP_CLS_MOD
USE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD
USE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD
IMPLICIT NONE
TYPE (MF_PHYS_SURF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%GSP_SG, LDDELETED=.TRUE.)

CALL WIPE (YD%GSP_RR, LDDELETED=.TRUE.)

CALL WIPE (YD%GSP_CL, LDDELETED=.TRUE.)

CALL WIPE (YD%GSD_XP, LDDELETED=.TRUE.)

CALL WIPE (YD%GSD_XP2, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
