MODULE UTIL_MODEL_PHYSICS_MF_TYPE_MOD

USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_MF_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_MF_TYPE (KLUN, YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TARPHY_MOD
USE UTIL_TCVMNH_MOD
USE UTIL_TLOUIS_MOD
USE UTIL_TMSE_MOD
USE UTIL_TNORGWD_MOD
USE UTIL_TPARAR_MOD
USE UTIL_TPHY0_MOD
USE UTIL_TPHY1_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY3_MOD
USE UTIL_TPHYDS_MOD
USE UTIL_TPHY_MOD
USE UTIL_TSIMPHL_MOD
USE UTIL_TTOPH_MOD
USE UTIL_TVDOZ_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRPHY)
CALL SAVE (KLUN, YD%YRPHY0)
CALL SAVE (KLUN, YD%YRPHY1)
CALL SAVE (KLUN, YD%YRPHY2)
CALL SAVE (KLUN, YD%YRPHY3)
CALL SAVE (KLUN, YD%YRPHYDS)
CALL SAVE (KLUN, YD%YRCVMNH)
CALL SAVE (KLUN, YD%YRTOPH)
CALL SAVE (KLUN, YD%YRVDOZ)
CALL SAVE (KLUN, YD%YRSIMPHL)
CALL SAVE (KLUN, YD%YRARPHY)
CALL SAVE (KLUN, YD%YRPARAR)
CALL SAVE (KLUN, YD%YRMSE)
CALL SAVE (KLUN, YD%YRLOUIS)
CALL SAVE (KLUN, YD%YRNORGWD)
CALL SAVE (KLUN, YD%YRGR)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_MF_TYPE (KLUN, YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TARPHY_MOD
USE UTIL_TCVMNH_MOD
USE UTIL_TLOUIS_MOD
USE UTIL_TMSE_MOD
USE UTIL_TNORGWD_MOD
USE UTIL_TPARAR_MOD
USE UTIL_TPHY0_MOD
USE UTIL_TPHY1_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY3_MOD
USE UTIL_TPHYDS_MOD
USE UTIL_TPHY_MOD
USE UTIL_TSIMPHL_MOD
USE UTIL_TTOPH_MOD
USE UTIL_TVDOZ_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRPHY)
CALL LOAD (KLUN, YD%YRPHY0)
CALL LOAD (KLUN, YD%YRPHY1)
CALL LOAD (KLUN, YD%YRPHY2)
CALL LOAD (KLUN, YD%YRPHY3)
CALL LOAD (KLUN, YD%YRPHYDS)
CALL LOAD (KLUN, YD%YRCVMNH)
CALL LOAD (KLUN, YD%YRTOPH)
CALL LOAD (KLUN, YD%YRVDOZ)
CALL LOAD (KLUN, YD%YRSIMPHL)
CALL LOAD (KLUN, YD%YRARPHY)
CALL LOAD (KLUN, YD%YRPARAR)
CALL LOAD (KLUN, YD%YRMSE)
CALL LOAD (KLUN, YD%YRLOUIS)
CALL LOAD (KLUN, YD%YRNORGWD)
CALL LOAD (KLUN, YD%YRGR)
END SUBROUTINE






END MODULE
