MODULE UTIL_STACK_MOD

USE STACK_MOD, ONLY : STACK
USE UTIL_FIELD_MOD



INTERFACE COPY
MODULE PROCEDURE COPY_STACK
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_STACK
END INTERFACE



CONTAINS





SUBROUTINE COPY_STACK (YD, LDCREATED)
IMPLICIT NONE
TYPE (STACK), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_P

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LF_P = ASSOCIATED (YD%F_P)
IF (LF_P) THEN
  !$acc enter data create (YD%F_P)
  !$acc update device (YD%F_P)
  CALL COPY (YD%F_P, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_P)
ENDIF



END SUBROUTINE

SUBROUTINE WIPE_STACK (YD, LDDELETED)
IMPLICIT NONE
TYPE (STACK), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LF_P

LF_P = ASSOCIATED (YD%F_P)
IF (LF_P) THEN
  !$acc exit data detach (YD%F_P)
  CALL WIPE (YD%F_P, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_P)
ENDIF



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
