MODULE UTIL_TECLDP_MOD

USE YOECLDP, ONLY : TECLDP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TECLDP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECLDP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TECLDP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECLDP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RAMID
WRITE (KLUN) YD%RCLDIFF
WRITE (KLUN) YD%RCLDIFF_CONVI
WRITE (KLUN) YD%RCLCRIT
WRITE (KLUN) YD%RCLCRIT_SEA
WRITE (KLUN) YD%RCLCRIT_LAND
WRITE (KLUN) YD%RKCONV
WRITE (KLUN) YD%RPRC1
WRITE (KLUN) YD%RPRC2
WRITE (KLUN) YD%RCLDMAX
WRITE (KLUN) YD%RPECONS
WRITE (KLUN) YD%RVRFACTOR
WRITE (KLUN) YD%RPRECRHMAX
WRITE (KLUN) YD%RTAUMEL
WRITE (KLUN) YD%RAMIN
WRITE (KLUN) YD%RLMIN
WRITE (KLUN) YD%RKOOPTAU
WRITE (KLUN) YD%RCLDTOPP
WRITE (KLUN) YD%RLCRITSNOW
WRITE (KLUN) YD%RSNOWLIN1
WRITE (KLUN) YD%RSNOWLIN2
WRITE (KLUN) YD%RICEHI1
WRITE (KLUN) YD%RICEHI2
WRITE (KLUN) YD%RICEINIT
WRITE (KLUN) YD%RVICE
WRITE (KLUN) YD%RVRAIN
WRITE (KLUN) YD%RVSNOW
WRITE (KLUN) YD%RTHOMO
WRITE (KLUN) YD%RCOVPMIN
WRITE (KLUN) YD%RCCN
WRITE (KLUN) YD%RNICE
WRITE (KLUN) YD%RCCNOM
WRITE (KLUN) YD%RCCNSS
WRITE (KLUN) YD%RCCNSU
WRITE (KLUN) YD%RCLDTOPCF
WRITE (KLUN) YD%RDEPLIQREFRATE
WRITE (KLUN) YD%RDEPLIQREFDEPTH
WRITE (KLUN) YD%RCL_OVERLAPLIQICE
WRITE (KLUN) YD%RCL_EFFRIME
WRITE (KLUN) YD%RCL_KKAAC
WRITE (KLUN) YD%RCL_KKBAC
WRITE (KLUN) YD%RCL_KKAAU
WRITE (KLUN) YD%RCL_KKBAUQ
WRITE (KLUN) YD%RCL_KKBAUN
WRITE (KLUN) YD%RCL_KK_CLOUD_NUM_SEA
WRITE (KLUN) YD%RCL_KK_CLOUD_NUM_LAND
WRITE (KLUN) YD%RCL_INHOMOGAUT
WRITE (KLUN) YD%RCL_INHOMOGACC
WRITE (KLUN) YD%LCLOUD_INHOMOG
WRITE (KLUN) YD%RCL_AI
WRITE (KLUN) YD%RCL_BI
WRITE (KLUN) YD%RCL_CI
WRITE (KLUN) YD%RCL_DI
WRITE (KLUN) YD%RCL_X1I
WRITE (KLUN) YD%RCL_X2I
WRITE (KLUN) YD%RCL_X3I
WRITE (KLUN) YD%RCL_X4I
WRITE (KLUN) YD%RCL_CONST1I
WRITE (KLUN) YD%RCL_CONST2I
WRITE (KLUN) YD%RCL_CONST3I
WRITE (KLUN) YD%RCL_CONST4I
WRITE (KLUN) YD%RCL_CONST5I
WRITE (KLUN) YD%RCL_CONST6I
WRITE (KLUN) YD%RCL_APB1
WRITE (KLUN) YD%RCL_APB2
WRITE (KLUN) YD%RCL_APB3
WRITE (KLUN) YD%RCL_AS
WRITE (KLUN) YD%RCL_BS
WRITE (KLUN) YD%RCL_CS
WRITE (KLUN) YD%RCL_DS
WRITE (KLUN) YD%RCL_X1S
WRITE (KLUN) YD%RCL_X2S
WRITE (KLUN) YD%RCL_X3S
WRITE (KLUN) YD%RCL_X4S
WRITE (KLUN) YD%RCL_CONST1S
WRITE (KLUN) YD%RCL_CONST2S
WRITE (KLUN) YD%RCL_CONST3S
WRITE (KLUN) YD%RCL_CONST4S
WRITE (KLUN) YD%RCL_CONST5S
WRITE (KLUN) YD%RCL_CONST6S
WRITE (KLUN) YD%RCL_CONST7S
WRITE (KLUN) YD%RCL_CONST8S
WRITE (KLUN) YD%RDENSWAT
WRITE (KLUN) YD%RDENSREF
WRITE (KLUN) YD%RCL_AR
WRITE (KLUN) YD%RCL_BR
WRITE (KLUN) YD%RCL_CR
WRITE (KLUN) YD%RCL_DR
WRITE (KLUN) YD%RCL_X1R
WRITE (KLUN) YD%RCL_X2R
WRITE (KLUN) YD%RCL_X4R
WRITE (KLUN) YD%RCL_X1R_MP
WRITE (KLUN) YD%RCL_X2R_MP
WRITE (KLUN) YD%RCL_X4R_MP
WRITE (KLUN) YD%RCL_KA273
WRITE (KLUN) YD%RCL_CDENOM1
WRITE (KLUN) YD%RCL_CDENOM2
WRITE (KLUN) YD%RCL_CDENOM3
WRITE (KLUN) YD%RCL_SCHMIDT
WRITE (KLUN) YD%RCL_DYNVISC
WRITE (KLUN) YD%RCL_CONST1R
WRITE (KLUN) YD%RCL_CONST2R
WRITE (KLUN) YD%RCL_CONST3R
WRITE (KLUN) YD%RCL_CONST4R
WRITE (KLUN) YD%RCL_CONST7R
WRITE (KLUN) YD%RCL_CONST8R
WRITE (KLUN) YD%RCL_FAC1
WRITE (KLUN) YD%RCL_FAC2
WRITE (KLUN) YD%RCL_FAC1_MP
WRITE (KLUN) YD%RCL_FAC2_MP
WRITE (KLUN) YD%RCL_CONST5R
WRITE (KLUN) YD%RCL_CONST6R
WRITE (KLUN) YD%RCL_FZRAB
WRITE (KLUN) YD%RCL_FZRBB
WRITE (KLUN) YD%RCL_CONST9R
WRITE (KLUN) YD%RCL_CONST10R
WRITE (KLUN) YD%RCL_EFF_RACW
WRITE (KLUN) YD%LCLDEXTRA
WRITE (KLUN) YD%LCLDBUDGET
WRITE (KLUN) YD%LCLDBUDC
WRITE (KLUN) YD%LCLDBUDL
WRITE (KLUN) YD%LCLDBUDI
WRITE (KLUN) YD%LCLDBUDT
WRITE (KLUN) YD%LCLDBUD_TIMEINT
WRITE (KLUN) YD%LCLDBUD_VERTINT
WRITE (KLUN) YD%NSSOPT
WRITE (KLUN) YD%NCLDTOP
WRITE (KLUN) YD%NAECLBC
WRITE (KLUN) YD%NAECLDU
WRITE (KLUN) YD%NAECLOM
WRITE (KLUN) YD%NAECLSS
WRITE (KLUN) YD%NAECLSU
WRITE (KLUN) YD%NCLDDIAG
WRITE (KLUN) YD%NAERCLD
WRITE (KLUN) YD%LAERLIQAUTOLSP
WRITE (KLUN) YD%LAERLIQAUTOCP
WRITE (KLUN) YD%LAERLIQAUTOCPB
WRITE (KLUN) YD%LAERLIQCOLL
WRITE (KLUN) YD%LAERICESED
WRITE (KLUN) YD%LAERICEAUTO
WRITE (KLUN) YD%NSHAPEP
WRITE (KLUN) YD%NSHAPEQ
WRITE (KLUN) YD%NBETA
WRITE (KLUN) YD%RBETA
WRITE (KLUN) YD%RBETAP1
END SUBROUTINE
SUBROUTINE LOAD_TECLDP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECLDP), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RAMID
READ (KLUN) YD%RCLDIFF
READ (KLUN) YD%RCLDIFF_CONVI
READ (KLUN) YD%RCLCRIT
READ (KLUN) YD%RCLCRIT_SEA
READ (KLUN) YD%RCLCRIT_LAND
READ (KLUN) YD%RKCONV
READ (KLUN) YD%RPRC1
READ (KLUN) YD%RPRC2
READ (KLUN) YD%RCLDMAX
READ (KLUN) YD%RPECONS
READ (KLUN) YD%RVRFACTOR
READ (KLUN) YD%RPRECRHMAX
READ (KLUN) YD%RTAUMEL
READ (KLUN) YD%RAMIN
READ (KLUN) YD%RLMIN
READ (KLUN) YD%RKOOPTAU
READ (KLUN) YD%RCLDTOPP
READ (KLUN) YD%RLCRITSNOW
READ (KLUN) YD%RSNOWLIN1
READ (KLUN) YD%RSNOWLIN2
READ (KLUN) YD%RICEHI1
READ (KLUN) YD%RICEHI2
READ (KLUN) YD%RICEINIT
READ (KLUN) YD%RVICE
READ (KLUN) YD%RVRAIN
READ (KLUN) YD%RVSNOW
READ (KLUN) YD%RTHOMO
READ (KLUN) YD%RCOVPMIN
READ (KLUN) YD%RCCN
READ (KLUN) YD%RNICE
READ (KLUN) YD%RCCNOM
READ (KLUN) YD%RCCNSS
READ (KLUN) YD%RCCNSU
READ (KLUN) YD%RCLDTOPCF
READ (KLUN) YD%RDEPLIQREFRATE
READ (KLUN) YD%RDEPLIQREFDEPTH
READ (KLUN) YD%RCL_OVERLAPLIQICE
READ (KLUN) YD%RCL_EFFRIME
READ (KLUN) YD%RCL_KKAAC
READ (KLUN) YD%RCL_KKBAC
READ (KLUN) YD%RCL_KKAAU
READ (KLUN) YD%RCL_KKBAUQ
READ (KLUN) YD%RCL_KKBAUN
READ (KLUN) YD%RCL_KK_CLOUD_NUM_SEA
READ (KLUN) YD%RCL_KK_CLOUD_NUM_LAND
READ (KLUN) YD%RCL_INHOMOGAUT
READ (KLUN) YD%RCL_INHOMOGACC
READ (KLUN) YD%LCLOUD_INHOMOG
READ (KLUN) YD%RCL_AI
READ (KLUN) YD%RCL_BI
READ (KLUN) YD%RCL_CI
READ (KLUN) YD%RCL_DI
READ (KLUN) YD%RCL_X1I
READ (KLUN) YD%RCL_X2I
READ (KLUN) YD%RCL_X3I
READ (KLUN) YD%RCL_X4I
READ (KLUN) YD%RCL_CONST1I
READ (KLUN) YD%RCL_CONST2I
READ (KLUN) YD%RCL_CONST3I
READ (KLUN) YD%RCL_CONST4I
READ (KLUN) YD%RCL_CONST5I
READ (KLUN) YD%RCL_CONST6I
READ (KLUN) YD%RCL_APB1
READ (KLUN) YD%RCL_APB2
READ (KLUN) YD%RCL_APB3
READ (KLUN) YD%RCL_AS
READ (KLUN) YD%RCL_BS
READ (KLUN) YD%RCL_CS
READ (KLUN) YD%RCL_DS
READ (KLUN) YD%RCL_X1S
READ (KLUN) YD%RCL_X2S
READ (KLUN) YD%RCL_X3S
READ (KLUN) YD%RCL_X4S
READ (KLUN) YD%RCL_CONST1S
READ (KLUN) YD%RCL_CONST2S
READ (KLUN) YD%RCL_CONST3S
READ (KLUN) YD%RCL_CONST4S
READ (KLUN) YD%RCL_CONST5S
READ (KLUN) YD%RCL_CONST6S
READ (KLUN) YD%RCL_CONST7S
READ (KLUN) YD%RCL_CONST8S
READ (KLUN) YD%RDENSWAT
READ (KLUN) YD%RDENSREF
READ (KLUN) YD%RCL_AR
READ (KLUN) YD%RCL_BR
READ (KLUN) YD%RCL_CR
READ (KLUN) YD%RCL_DR
READ (KLUN) YD%RCL_X1R
READ (KLUN) YD%RCL_X2R
READ (KLUN) YD%RCL_X4R
READ (KLUN) YD%RCL_X1R_MP
READ (KLUN) YD%RCL_X2R_MP
READ (KLUN) YD%RCL_X4R_MP
READ (KLUN) YD%RCL_KA273
READ (KLUN) YD%RCL_CDENOM1
READ (KLUN) YD%RCL_CDENOM2
READ (KLUN) YD%RCL_CDENOM3
READ (KLUN) YD%RCL_SCHMIDT
READ (KLUN) YD%RCL_DYNVISC
READ (KLUN) YD%RCL_CONST1R
READ (KLUN) YD%RCL_CONST2R
READ (KLUN) YD%RCL_CONST3R
READ (KLUN) YD%RCL_CONST4R
READ (KLUN) YD%RCL_CONST7R
READ (KLUN) YD%RCL_CONST8R
READ (KLUN) YD%RCL_FAC1
READ (KLUN) YD%RCL_FAC2
READ (KLUN) YD%RCL_FAC1_MP
READ (KLUN) YD%RCL_FAC2_MP
READ (KLUN) YD%RCL_CONST5R
READ (KLUN) YD%RCL_CONST6R
READ (KLUN) YD%RCL_FZRAB
READ (KLUN) YD%RCL_FZRBB
READ (KLUN) YD%RCL_CONST9R
READ (KLUN) YD%RCL_CONST10R
READ (KLUN) YD%RCL_EFF_RACW
READ (KLUN) YD%LCLDEXTRA
READ (KLUN) YD%LCLDBUDGET
READ (KLUN) YD%LCLDBUDC
READ (KLUN) YD%LCLDBUDL
READ (KLUN) YD%LCLDBUDI
READ (KLUN) YD%LCLDBUDT
READ (KLUN) YD%LCLDBUD_TIMEINT
READ (KLUN) YD%LCLDBUD_VERTINT
READ (KLUN) YD%NSSOPT
READ (KLUN) YD%NCLDTOP
READ (KLUN) YD%NAECLBC
READ (KLUN) YD%NAECLDU
READ (KLUN) YD%NAECLOM
READ (KLUN) YD%NAECLSS
READ (KLUN) YD%NAECLSU
READ (KLUN) YD%NCLDDIAG
READ (KLUN) YD%NAERCLD
READ (KLUN) YD%LAERLIQAUTOLSP
READ (KLUN) YD%LAERLIQAUTOCP
READ (KLUN) YD%LAERLIQAUTOCPB
READ (KLUN) YD%LAERLIQCOLL
READ (KLUN) YD%LAERICESED
READ (KLUN) YD%LAERICEAUTO
READ (KLUN) YD%NSHAPEP
READ (KLUN) YD%NSHAPEQ
READ (KLUN) YD%NBETA
READ (KLUN) YD%RBETA
READ (KLUN) YD%RBETAP1
END SUBROUTINE




END MODULE
