MODULE UTIL_FIELD_MOD

USE FIELD_MODULE

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_2D
  MODULE PROCEDURE LOAD_FIELD_3D
  MODULE PROCEDURE LOAD_FIELD_4D
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_2D
  MODULE PROCEDURE SAVE_FIELD_3D
  MODULE PROCEDURE SAVE_FIELD_4D
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_2D
  MODULE PROCEDURE DIFF_FIELD_3D
  MODULE PROCEDURE DIFF_FIELD_4D
END INTERFACE

CONTAINS

SUBROUTINE LOAD_FIELD_2D (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_2D), POINTER :: YD
INTEGER (KIND=JPIM) :: ISIZE (2)

ALLOCATE (YD)
READ (KLUN) YD%LBOUNDS
READ (KLUN) ISIZE
ALLOCATE (YD%DATA (ISIZE (1), ISIZE (2)))
READ (KLUN) YD%DATA
YD%PTR => YD%DATA
YD%ACTIVE = .TRUE.

END SUBROUTINE

SUBROUTINE LOAD_FIELD_3D (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_3D), POINTER :: YD
INTEGER (KIND=JPIM) :: ISIZE (3)

ALLOCATE (YD)
READ (KLUN) YD%LBOUNDS
READ (KLUN) ISIZE
ALLOCATE (YD%DATA (ISIZE (1), ISIZE (2), ISIZE (3)))
READ (KLUN) YD%DATA
YD%PTR => YD%DATA
YD%ACTIVE = .TRUE.

END SUBROUTINE

SUBROUTINE LOAD_FIELD_4D (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_4D), POINTER :: YD
INTEGER (KIND=JPIM) :: ISIZE (4)

ALLOCATE (YD)
READ (KLUN) YD%LBOUNDS
READ (KLUN) ISIZE
ALLOCATE (YD%DATA (ISIZE (1), ISIZE (2), ISIZE (3), ISIZE (4)))
READ (KLUN) YD%DATA
YD%PTR => YD%DATA
YD%ACTIVE = .TRUE.

END SUBROUTINE

SUBROUTINE SAVE_FIELD_2D (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_2D), POINTER :: YD
INTEGER (KIND=JPIM) :: ISIZE (2)

WRITE (KLUN) YD%LBOUNDS
ISIZE = UBOUND (YD%PTR) - LBOUND (YD%PTR) + 1
WRITE (KLUN) ISIZE
WRITE (KLUN) YD%PTR

END SUBROUTINE

SUBROUTINE SAVE_FIELD_3D (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_3D), POINTER :: YD
INTEGER (KIND=JPIM) :: ISIZE (3)

WRITE (KLUN) YD%LBOUNDS
ISIZE = UBOUND (YD%PTR) - LBOUND (YD%PTR) + 1
WRITE (KLUN) ISIZE
WRITE (KLUN) YD%PTR

END SUBROUTINE

SUBROUTINE SAVE_FIELD_4D (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_4D), POINTER :: YD
INTEGER (KIND=JPIM) :: ISIZE (4)

WRITE (KLUN) YD%LBOUNDS
ISIZE = UBOUND (YD%PTR) - LBOUND (YD%PTR) + 1
WRITE (KLUN) ISIZE
WRITE (KLUN) YD%PTR

END SUBROUTINE

SUBROUTINE DIFF_FIELD_2D (CDMESS, YD, YO)
CHARACTER(LEN=*), INTENT(IN) :: CDMESS
TYPE (FIELD_2D), POINTER :: YD, YO

INTEGER (KIND=JPIM) :: I1, I2

IF (ANY (LBOUND (YD%PTR) /= LBOUND (YO%PTR))) CALL ABOR1 ('DIMENSION MISMATCH')
IF (ANY (UBOUND (YD%PTR) /= UBOUND (YO%PTR))) CALL ABOR1 ('DIMENSION MISMATCH')
IF (ANY (YD%LBOUNDS /= YO%LBOUNDS)) CALL ABOR1 ('DIMENSION MISMATCH')

DO I2 = LBOUND (YD%PTR, 2), UBOUND (YD%PTR, 2)
DO I1 = LBOUND (YD%PTR, 1), UBOUND (YD%PTR, 1)
  IF (YD%PTR (I1, I2) /= YO%PTR (I1, I2)) THEN
    WRITE (*, '(A16," ",2I4," ",3E15.4)') CDMESS, I1, I2, YD%PTR (I1, I2), YO%PTR (I1, I2), YD%PTR (I1, I2) - YO%PTR (I1, I2)
  ENDIF
ENDDO
ENDDO

END SUBROUTINE

SUBROUTINE DIFF_FIELD_3D (CDMESS, YD, YO)
CHARACTER(LEN=*), INTENT(IN) :: CDMESS
TYPE (FIELD_3D), POINTER :: YD, YO

INTEGER (KIND=JPIM) :: I1, I2, I3

IF (ANY (LBOUND (YD%PTR) /= LBOUND (YO%PTR))) CALL ABOR1 ('DIMENSION MISMATCH')
IF (ANY (UBOUND (YD%PTR) /= UBOUND (YO%PTR))) CALL ABOR1 ('DIMENSION MISMATCH')
IF (ANY (YD%LBOUNDS /= YO%LBOUNDS)) CALL ABOR1 ('DIMENSION MISMATCH')

DO I3 = LBOUND (YD%PTR, 3), UBOUND (YD%PTR, 3)
DO I2 = LBOUND (YD%PTR, 2), UBOUND (YD%PTR, 2)
DO I1 = LBOUND (YD%PTR, 1), UBOUND (YD%PTR, 1)
  IF (YD%PTR (I1, I2, I3) /= YO%PTR (I1, I2, I3)) THEN
    WRITE (*, '(A16," ",3I4," ",3E15.4)') CDMESS, I1, I2, I3, YD%PTR (I1, I2, I3), YO%PTR (I1, I2, I3), YD%PTR (I1, I2, I3) - YO%PTR (I1, I2, I3)
  ENDIF
ENDDO
ENDDO
ENDDO

END SUBROUTINE

SUBROUTINE DIFF_FIELD_4D (CDMESS, YD, YO)
CHARACTER(LEN=*), INTENT(IN) :: CDMESS
TYPE (FIELD_4D), POINTER :: YD, YO

INTEGER (KIND=JPIM) :: I1, I2, I3, I4

IF (ANY (LBOUND (YD%PTR) /= LBOUND (YO%PTR))) CALL ABOR1 ('DIMENSION MISMATCH')
IF (ANY (UBOUND (YD%PTR) /= UBOUND (YO%PTR))) CALL ABOR1 ('DIMENSION MISMATCH')
IF (ANY (YD%LBOUNDS /= YO%LBOUNDS)) CALL ABOR1 ('DIMENSION MISMATCH')

DO I4 = LBOUND (YD%PTR, 4), UBOUND (YD%PTR, 4)
DO I3 = LBOUND (YD%PTR, 3), UBOUND (YD%PTR, 3)
DO I2 = LBOUND (YD%PTR, 2), UBOUND (YD%PTR, 2)
DO I1 = LBOUND (YD%PTR, 1), UBOUND (YD%PTR, 1)
  IF (YD%PTR (I1, I2, I3, I4) /= YO%PTR (I1, I2, I3, I4)) THEN
    WRITE (*, '(A16," ",4I4," ",3E15.4)') CDMESS, I1, I2, I3, I4, YD%PTR (I1, I2, I3, I4), YO%PTR (I1, I2, I3, I4), YD%PTR (I1, I2, I3, I4) - YO%PTR (I1, I2, I3, I4)
  ENDIF
ENDDO
ENDDO
ENDDO
ENDDO

END SUBROUTINE

END MODULE
