MODULE UTIL_TOROG_BLOCKED_MOD

USE YOMOROG, ONLY : TOROG_BLOCKED

INTERFACE SAVE
MODULE PROCEDURE SAVE_TOROG_BLOCKED
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TOROG_BLOCKED
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TOROG_BLOCKED (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOROG_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM
LOROG = ALLOCATED (YD%OROG)
WRITE (KLUN) LOROG
IF (LOROG) THEN
  WRITE (KLUN) LBOUND (YD%OROG)
  WRITE (KLUN) UBOUND (YD%OROG)
  WRITE (KLUN) YD%OROG
ENDIF
LOROGL = ALLOCATED (YD%OROGL)
WRITE (KLUN) LOROGL
IF (LOROGL) THEN
  WRITE (KLUN) LBOUND (YD%OROGL)
  WRITE (KLUN) UBOUND (YD%OROGL)
  WRITE (KLUN) YD%OROGL
ENDIF
LOROGM = ALLOCATED (YD%OROGM)
WRITE (KLUN) LOROGM
IF (LOROGM) THEN
  WRITE (KLUN) LBOUND (YD%OROGM)
  WRITE (KLUN) UBOUND (YD%OROGM)
  WRITE (KLUN) YD%OROGM
ENDIF
LOROGLL = ALLOCATED (YD%OROGLL)
WRITE (KLUN) LOROGLL
IF (LOROGLL) THEN
  WRITE (KLUN) LBOUND (YD%OROGLL)
  WRITE (KLUN) UBOUND (YD%OROGLL)
  WRITE (KLUN) YD%OROGLL
ENDIF
LOROGMM = ALLOCATED (YD%OROGMM)
WRITE (KLUN) LOROGMM
IF (LOROGMM) THEN
  WRITE (KLUN) LBOUND (YD%OROGMM)
  WRITE (KLUN) UBOUND (YD%OROGMM)
  WRITE (KLUN) YD%OROGMM
ENDIF
LOROGLM = ALLOCATED (YD%OROGLM)
WRITE (KLUN) LOROGLM
IF (LOROGLM) THEN
  WRITE (KLUN) LBOUND (YD%OROGLM)
  WRITE (KLUN) UBOUND (YD%OROGLM)
  WRITE (KLUN) YD%OROGLM
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TOROG_BLOCKED (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOROG_BLOCKED), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM
READ (KLUN) LOROG
IF (LOROG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROG
ENDIF
READ (KLUN) LOROGL
IF (LOROGL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGL
ENDIF
READ (KLUN) LOROGM
IF (LOROGM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGM
ENDIF
READ (KLUN) LOROGLL
IF (LOROGLL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGLL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGLL
ENDIF
READ (KLUN) LOROGMM
IF (LOROGMM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGMM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGMM
ENDIF
READ (KLUN) LOROGLM
IF (LOROGLM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGLM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGLM
ENDIF
END SUBROUTINE




END MODULE
