MODULE UTIL_TEGSL_MOD

USE YEMGSL, ONLY : TEGSL


INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGSL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGSL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEGSL
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEGSL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEGSL (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TEGSL), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RIPORE
WRITE (KLUN) YD%RJPORE
WRITE (KLUN) YD%REGPK
WRITE (KLUN) YD%RNOBILE
WRITE (KLUN) YD%RHSUD
WRITE (KLUN) YD%RMERCAT
WRITE (KLUN) YD%RLON0R
WRITE (KLUN) YD%RELONC
WRITE (KLUN) YD%RELATC
END SUBROUTINE

SUBROUTINE LOAD_TEGSL (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TEGSL), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RIPORE
READ (KLUN) YD%RJPORE
READ (KLUN) YD%REGPK
READ (KLUN) YD%RNOBILE
READ (KLUN) YD%RHSUD
READ (KLUN) YD%RMERCAT
READ (KLUN) YD%RLON0R
READ (KLUN) YD%RELONC
READ (KLUN) YD%RELATC
END SUBROUTINE


SUBROUTINE COPY_TEGSL (YD, LDCREATED)
IMPLICIT NONE
CLASS (TEGSL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









END SUBROUTINE

SUBROUTINE WIPE_TEGSL (YD, LDDELETED)
IMPLICIT NONE
CLASS (TEGSL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED










LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
