MODULE UTIL_TYPE_AERO_WVL_DIAG_MOD

USE YOE_AERODIAG, ONLY : TYPE_AERO_WVL_DIAG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_AERO_WVL_DIAG
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TYPE_AERO_WVL_DIAG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%IWVL
WRITE (KLUN) YD%IGRIBDIAG
END SUBROUTINE

SUBROUTINE LOAD_TYPE_AERO_WVL_DIAG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_AERO_WVL_DIAG), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%IWVL
READ (KLUN) YD%IGRIBDIAG
END SUBROUTINE






END MODULE
