MODULE UTIL_TEDIM_MOD

USE YEMDIM, ONLY : TEDIM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEDIM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEDIM
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEDIM), INTENT (IN), TARGET :: YD
LOGICAL :: LNISMAX, LNISNAX
WRITE (KLUN) YD%NSECPLG
WRITE (KLUN) YD%NBZONG
WRITE (KLUN) YD%NBZONL
WRITE (KLUN) YD%NBZONU
WRITE (KLUN) YD%NNOEXTZG
WRITE (KLUN) YD%NNOEXTZL
LNISMAX = ASSOCIATED (YD%NISMAX)
WRITE (KLUN) LNISMAX
IF (LNISMAX) THEN
  WRITE (KLUN) LBOUND (YD%NISMAX)
  WRITE (KLUN) UBOUND (YD%NISMAX)
  WRITE (KLUN) YD%NISMAX
ENDIF
LNISNAX = ASSOCIATED (YD%NISNAX)
WRITE (KLUN) LNISNAX
IF (LNISNAX) THEN
  WRITE (KLUN) LBOUND (YD%NISNAX)
  WRITE (KLUN) UBOUND (YD%NISNAX)
  WRITE (KLUN) YD%NISNAX
ENDIF
WRITE (KLUN) YD%LBIPINCI
WRITE (KLUN) YD%NBIPINCIX
WRITE (KLUN) YD%NBIPINCIY
WRITE (KLUN) YD%NEDOM
END SUBROUTINE
SUBROUTINE LOAD_TEDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEDIM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LNISMAX, LNISNAX
READ (KLUN) YD%NSECPLG
READ (KLUN) YD%NBZONG
READ (KLUN) YD%NBZONL
READ (KLUN) YD%NBZONU
READ (KLUN) YD%NNOEXTZG
READ (KLUN) YD%NNOEXTZL
READ (KLUN) LNISMAX
IF (LNISMAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NISMAX (IL1(1):IU1(1)))
  READ (KLUN) YD%NISMAX
ELSE
  NULLIFY (YD%NISMAX)
ENDIF
READ (KLUN) LNISNAX
IF (LNISNAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NISNAX (IL1(1):IU1(1)))
  READ (KLUN) YD%NISNAX
ELSE
  NULLIFY (YD%NISNAX)
ENDIF
READ (KLUN) YD%LBIPINCI
READ (KLUN) YD%NBIPINCIX
READ (KLUN) YD%NBIPINCIY
READ (KLUN) YD%NEDOM
END SUBROUTINE




END MODULE
