MODULE UTIL_MODEL_PHYSICS_AEROSOL_TYPE_MOD

USE MODEL_PHYSICS_AEROSOL_MOD, ONLY : MODEL_PHYSICS_AEROSOL_TYPE
USE UTIL_TEAERLID_MOD
USE UTIL_TEAERMAP_MOD
USE UTIL_TEAERSNK_MOD
USE UTIL_TEAERSRC_MOD
USE UTIL_TEAERVOL_MOD
USE UTIL_TEDBUG_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_AEROSOL_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_AEROSOL_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_AEROSOL_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_AEROSOL_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_AEROSOL_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_AEROSOL_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YREAERLID)
CALL SAVE (KLUN, YD%YREAERMAP)
CALL SAVE (KLUN, YD%YREAERSNK)
CALL SAVE (KLUN, YD%YREAERSRC)
CALL SAVE (KLUN, YD%YREAERVOL)
CALL SAVE (KLUN, YD%YREDBUG)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_AEROSOL_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_AEROSOL_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YREAERLID)
CALL LOAD (KLUN, YD%YREAERMAP)
CALL LOAD (KLUN, YD%YREAERSNK)
CALL LOAD (KLUN, YD%YREAERSRC)
CALL LOAD (KLUN, YD%YREAERVOL)
CALL LOAD (KLUN, YD%YREDBUG)
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_AEROSOL_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (MODEL_PHYSICS_AEROSOL_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YREAERLID, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERMAP, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERSNK, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERSRC, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERVOL, LDCREATED=.TRUE.)

CALL COPY (YD%YREDBUG, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_AEROSOL_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (MODEL_PHYSICS_AEROSOL_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YREAERLID, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERMAP, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERSNK, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERSRC, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERVOL, LDDELETED=.TRUE.)

CALL WIPE (YD%YREDBUG, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
