MODULE UTIL_TNCL_MOD

USE YOMNCL, ONLY : TNCL


INTERFACE SAVE
MODULE PROCEDURE SAVE_TNCL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TNCL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TNCL
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TNCL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TNCL (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNCL), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LNCLIN
WRITE (KLUN) YD%LREGCL
END SUBROUTINE

SUBROUTINE LOAD_TNCL (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNCL), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LNCLIN
READ (KLUN) YD%LREGCL
END SUBROUTINE


SUBROUTINE COPY_TNCL (YD, LDCREATED)
IMPLICIT NONE
TYPE (TNCL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF


END SUBROUTINE

SUBROUTINE WIPE_TNCL (YD, LDDELETED)
IMPLICIT NONE
TYPE (TNCL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
