MODULE UTIL_MODEL_PHYSICS_GENERAL_TYPE_MOD

USE MODEL_PHYSICS_GENERAL_MOD, ONLY : MODEL_PHYSICS_GENERAL_TYPE
USE UTIL_TDPHY_MOD
USE UTIL_TSLPHY_MOD
USE UTIL_TVDF_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_GENERAL_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_GENERAL_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_GENERAL_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_GENERAL_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_GENERAL_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_GENERAL_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRDPHY)
CALL SAVE (KLUN, YD%YRSLPHY)
CALL SAVE (KLUN, YD%YRVDF)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_GENERAL_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_GENERAL_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRDPHY)
CALL LOAD (KLUN, YD%YRSLPHY)
CALL LOAD (KLUN, YD%YRVDF)
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_GENERAL_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (MODEL_PHYSICS_GENERAL_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRDPHY, LDCREATED=.TRUE.)

CALL COPY (YD%YRSLPHY, LDCREATED=.TRUE.)

CALL COPY (YD%YRVDF, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_GENERAL_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (MODEL_PHYSICS_GENERAL_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRDPHY, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSLPHY, LDDELETED=.TRUE.)

CALL WIPE (YD%YRVDF, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
