MODULE UTIL_ACV_CONTAINER_MOD

USE TYPE_ACV, ONLY : ACV_CONTAINER

INTERFACE SAVE
MODULE PROCEDURE SAVE_ACV_CONTAINER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_ACV_CONTAINER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_ACV_CONTAINER
END INTERFACE



CONTAINS

SUBROUTINE SAVE_ACV_CONTAINER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (ACV_CONTAINER), INTENT (IN), TARGET :: YD
LOGICAL :: LRACV1D, LRGPACV2D, LRGPACV3D, LRSPACV2D, LRSPACV3D
LRACV1D = ALLOCATED (YD%RACV1D)
WRITE (KLUN) LRACV1D
IF (LRACV1D) THEN
  WRITE (KLUN) LBOUND (YD%RACV1D)
  WRITE (KLUN) UBOUND (YD%RACV1D)
  WRITE (KLUN) YD%RACV1D
ENDIF
LRSPACV2D = ALLOCATED (YD%RSPACV2D)
WRITE (KLUN) LRSPACV2D
IF (LRSPACV2D) THEN
  WRITE (KLUN) LBOUND (YD%RSPACV2D)
  WRITE (KLUN) UBOUND (YD%RSPACV2D)
  WRITE (KLUN) YD%RSPACV2D
ENDIF
LRGPACV2D = ALLOCATED (YD%RGPACV2D)
WRITE (KLUN) LRGPACV2D
IF (LRGPACV2D) THEN
  WRITE (KLUN) LBOUND (YD%RGPACV2D)
  WRITE (KLUN) UBOUND (YD%RGPACV2D)
  WRITE (KLUN) YD%RGPACV2D
ENDIF
LRSPACV3D = ALLOCATED (YD%RSPACV3D)
WRITE (KLUN) LRSPACV3D
IF (LRSPACV3D) THEN
  WRITE (KLUN) LBOUND (YD%RSPACV3D)
  WRITE (KLUN) UBOUND (YD%RSPACV3D)
  WRITE (KLUN) YD%RSPACV3D
ENDIF
LRGPACV3D = ALLOCATED (YD%RGPACV3D)
WRITE (KLUN) LRGPACV3D
IF (LRGPACV3D) THEN
  WRITE (KLUN) LBOUND (YD%RGPACV3D)
  WRITE (KLUN) UBOUND (YD%RGPACV3D)
  WRITE (KLUN) YD%RGPACV3D
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_ACV_CONTAINER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (ACV_CONTAINER), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LRACV1D, LRGPACV2D, LRGPACV3D, LRSPACV2D, LRSPACV3D
READ (KLUN) LRACV1D
IF (LRACV1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RACV1D (IL1(1):IU1(1)))
  READ (KLUN) YD%RACV1D
ENDIF
READ (KLUN) LRSPACV2D
IF (LRSPACV2D) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSPACV2D (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSPACV2D
ENDIF
READ (KLUN) LRGPACV2D
IF (LRGPACV2D) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RGPACV2D (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RGPACV2D
ENDIF
READ (KLUN) LRSPACV3D
IF (LRSPACV3D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSPACV3D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RSPACV3D
ENDIF
READ (KLUN) LRGPACV3D
IF (LRGPACV3D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RGPACV3D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RGPACV3D
ENDIF
END SUBROUTINE


SUBROUTINE COPY_ACV_CONTAINER (YD, LDCREATED)

IMPLICIT NONE
TYPE (ACV_CONTAINER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRACV1D, LRGPACV2D, LRGPACV3D, LRSPACV2D, LRSPACV3D

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRACV1D = ALLOCATED (YD%RACV1D)
IF (LRACV1D) THEN
  !$acc enter data create (YD%RACV1D)
  !$acc update device (YD%RACV1D)
  !$acc enter data attach (YD%RACV1D)
ENDIF

LRSPACV2D = ALLOCATED (YD%RSPACV2D)
IF (LRSPACV2D) THEN
  !$acc enter data create (YD%RSPACV2D)
  !$acc update device (YD%RSPACV2D)
  !$acc enter data attach (YD%RSPACV2D)
ENDIF

LRGPACV2D = ALLOCATED (YD%RGPACV2D)
IF (LRGPACV2D) THEN
  !$acc enter data create (YD%RGPACV2D)
  !$acc update device (YD%RGPACV2D)
  !$acc enter data attach (YD%RGPACV2D)
ENDIF

LRSPACV3D = ALLOCATED (YD%RSPACV3D)
IF (LRSPACV3D) THEN
  !$acc enter data create (YD%RSPACV3D)
  !$acc update device (YD%RSPACV3D)
  !$acc enter data attach (YD%RSPACV3D)
ENDIF

LRGPACV3D = ALLOCATED (YD%RGPACV3D)
IF (LRGPACV3D) THEN
  !$acc enter data create (YD%RGPACV3D)
  !$acc update device (YD%RGPACV3D)
  !$acc enter data attach (YD%RGPACV3D)
ENDIF

END SUBROUTINE



END MODULE
