MODULE UTIL_TYPE_AERO_WVL_DIAG_MOD

USE YOE_AERODIAG, ONLY : TYPE_AERO_WVL_DIAG


INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TYPE_AERO_WVL_DIAG
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_AERO_WVL_DIAG (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%IWVL
WRITE (KLUN) YD%IGRIBDIAG
END SUBROUTINE

SUBROUTINE LOAD_TYPE_AERO_WVL_DIAG (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TYPE_AERO_WVL_DIAG), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%IWVL
READ (KLUN) YD%IGRIBDIAG
END SUBROUTINE


SUBROUTINE COPY_TYPE_AERO_WVL_DIAG (YD, LDCREATED)
IMPLICIT NONE
CLASS (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF


END SUBROUTINE

SUBROUTINE WIPE_TYPE_AERO_WVL_DIAG (YD, LDDELETED)
IMPLICIT NONE
CLASS (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
