MODULE UTIL_CPG_DYN_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_DYN_TYPE
USE UTIL_CPG_CTY_TYPE_MOD
USE UTIL_CPG_HWIND_TYPE_MOD
USE UTIL_CPG_RCP_TYPE_MOD
USE UTIL_CPG_XYB_TYPE_MOD
USE UTIL_FIELD_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_DYN_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_DYN_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPG_DYN_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_DYN_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_CPG_DYN_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_DYN_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_DBBC, LF_GWFL, LF_GWFM, LF_GWFT, LF_GWS, LF_GWT, LF_KENE, LF_NHPREF, LF_NHPREH, LF_NHX
LOGICAL :: LF_NHY, LF_OROGL, LF_OROGM, LF_PHI, LF_PHIF, LF_PHIFL, LF_PHIFM, LF_PRE, LF_PREF, LF_PREL
LOGICAL :: LF_PREM, LF_QCHAL, LF_QCHAM, LF_RDPHI, LF_RTL, LF_RTM, LF_WRL

LF_OROGL = ASSOCIATED (YD%F_OROGL)
WRITE (KLUN) LF_OROGL
IF (LF_OROGL) THEN
  CALL SAVE (KLUN, YD%F_OROGL)
ENDIF
LF_OROGM = ASSOCIATED (YD%F_OROGM)
WRITE (KLUN) LF_OROGM
IF (LF_OROGM) THEN
  CALL SAVE (KLUN, YD%F_OROGM)
ENDIF
LF_PHI = ASSOCIATED (YD%F_PHI)
WRITE (KLUN) LF_PHI
IF (LF_PHI) THEN
  CALL SAVE (KLUN, YD%F_PHI)
ENDIF
LF_PRE = ASSOCIATED (YD%F_PRE)
WRITE (KLUN) LF_PRE
IF (LF_PRE) THEN
  CALL SAVE (KLUN, YD%F_PRE)
ENDIF
LF_PHIF = ASSOCIATED (YD%F_PHIF)
WRITE (KLUN) LF_PHIF
IF (LF_PHIF) THEN
  CALL SAVE (KLUN, YD%F_PHIF)
ENDIF
LF_PREF = ASSOCIATED (YD%F_PREF)
WRITE (KLUN) LF_PREF
IF (LF_PREF) THEN
  CALL SAVE (KLUN, YD%F_PREF)
ENDIF
LF_WRL = ASSOCIATED (YD%F_WRL)
WRITE (KLUN) LF_WRL
IF (LF_WRL) THEN
  CALL SAVE (KLUN, YD%F_WRL)
ENDIF
LF_PREL = ASSOCIATED (YD%F_PREL)
WRITE (KLUN) LF_PREL
IF (LF_PREL) THEN
  CALL SAVE (KLUN, YD%F_PREL)
ENDIF
LF_PREM = ASSOCIATED (YD%F_PREM)
WRITE (KLUN) LF_PREM
IF (LF_PREM) THEN
  CALL SAVE (KLUN, YD%F_PREM)
ENDIF
LF_NHY = ASSOCIATED (YD%F_NHY)
WRITE (KLUN) LF_NHY
IF (LF_NHY) THEN
  CALL SAVE (KLUN, YD%F_NHY)
ENDIF
LF_GWFT = ASSOCIATED (YD%F_GWFT)
WRITE (KLUN) LF_GWFT
IF (LF_GWFT) THEN
  CALL SAVE (KLUN, YD%F_GWFT)
ENDIF
LF_KENE = ASSOCIATED (YD%F_KENE)
WRITE (KLUN) LF_KENE
IF (LF_KENE) THEN
  CALL SAVE (KLUN, YD%F_KENE)
ENDIF
LF_NHX = ASSOCIATED (YD%F_NHX)
WRITE (KLUN) LF_NHX
IF (LF_NHX) THEN
  CALL SAVE (KLUN, YD%F_NHX)
ENDIF
LF_PHIFL = ASSOCIATED (YD%F_PHIFL)
WRITE (KLUN) LF_PHIFL
IF (LF_PHIFL) THEN
  CALL SAVE (KLUN, YD%F_PHIFL)
ENDIF
LF_PHIFM = ASSOCIATED (YD%F_PHIFM)
WRITE (KLUN) LF_PHIFM
IF (LF_PHIFM) THEN
  CALL SAVE (KLUN, YD%F_PHIFM)
ENDIF
LF_RTL = ASSOCIATED (YD%F_RTL)
WRITE (KLUN) LF_RTL
IF (LF_RTL) THEN
  CALL SAVE (KLUN, YD%F_RTL)
ENDIF
LF_RTM = ASSOCIATED (YD%F_RTM)
WRITE (KLUN) LF_RTM
IF (LF_RTM) THEN
  CALL SAVE (KLUN, YD%F_RTM)
ENDIF
CALL SAVE (KLUN, YD%RCP)
CALL SAVE (KLUN, YD%CTY)
CALL SAVE (KLUN, YD%UVH)
CALL SAVE (KLUN, YD%XYB)
LF_DBBC = ASSOCIATED (YD%F_DBBC)
WRITE (KLUN) LF_DBBC
IF (LF_DBBC) THEN
  CALL SAVE (KLUN, YD%F_DBBC)
ENDIF
LF_GWS = ASSOCIATED (YD%F_GWS)
WRITE (KLUN) LF_GWS
IF (LF_GWS) THEN
  CALL SAVE (KLUN, YD%F_GWS)
ENDIF
LF_GWFL = ASSOCIATED (YD%F_GWFL)
WRITE (KLUN) LF_GWFL
IF (LF_GWFL) THEN
  CALL SAVE (KLUN, YD%F_GWFL)
ENDIF
LF_GWFM = ASSOCIATED (YD%F_GWFM)
WRITE (KLUN) LF_GWFM
IF (LF_GWFM) THEN
  CALL SAVE (KLUN, YD%F_GWFM)
ENDIF
LF_GWT = ASSOCIATED (YD%F_GWT)
WRITE (KLUN) LF_GWT
IF (LF_GWT) THEN
  CALL SAVE (KLUN, YD%F_GWT)
ENDIF
LF_NHPREF = ASSOCIATED (YD%F_NHPREF)
WRITE (KLUN) LF_NHPREF
IF (LF_NHPREF) THEN
  CALL SAVE (KLUN, YD%F_NHPREF)
ENDIF
LF_NHPREH = ASSOCIATED (YD%F_NHPREH)
WRITE (KLUN) LF_NHPREH
IF (LF_NHPREH) THEN
  CALL SAVE (KLUN, YD%F_NHPREH)
ENDIF
LF_QCHAL = ASSOCIATED (YD%F_QCHAL)
WRITE (KLUN) LF_QCHAL
IF (LF_QCHAL) THEN
  CALL SAVE (KLUN, YD%F_QCHAL)
ENDIF
LF_QCHAM = ASSOCIATED (YD%F_QCHAM)
WRITE (KLUN) LF_QCHAM
IF (LF_QCHAM) THEN
  CALL SAVE (KLUN, YD%F_QCHAM)
ENDIF
LF_RDPHI = ASSOCIATED (YD%F_RDPHI)
WRITE (KLUN) LF_RDPHI
IF (LF_RDPHI) THEN
  CALL SAVE (KLUN, YD%F_RDPHI)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_DYN_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_DYN_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_DBBC, LF_GWFL, LF_GWFM, LF_GWFT, LF_GWS, LF_GWT, LF_KENE, LF_NHPREF, LF_NHPREH, LF_NHX
LOGICAL :: LF_NHY, LF_OROGL, LF_OROGM, LF_PHI, LF_PHIF, LF_PHIFL, LF_PHIFM, LF_PRE, LF_PREF, LF_PREL
LOGICAL :: LF_PREM, LF_QCHAL, LF_QCHAM, LF_RDPHI, LF_RTL, LF_RTM, LF_WRL

NULLIFY (YD%OROGL)
READ (KLUN) LF_OROGL
IF (LF_OROGL) THEN
  CALL LOAD (KLUN, YD%F_OROGL)
ELSE
  NULLIFY (YD%F_OROGL)
ENDIF
NULLIFY (YD%OROGM)
READ (KLUN) LF_OROGM
IF (LF_OROGM) THEN
  CALL LOAD (KLUN, YD%F_OROGM)
ELSE
  NULLIFY (YD%F_OROGM)
ENDIF
NULLIFY (YD%PHI)
READ (KLUN) LF_PHI
IF (LF_PHI) THEN
  CALL LOAD (KLUN, YD%F_PHI)
ELSE
  NULLIFY (YD%F_PHI)
ENDIF
NULLIFY (YD%PRE)
READ (KLUN) LF_PRE
IF (LF_PRE) THEN
  CALL LOAD (KLUN, YD%F_PRE)
ELSE
  NULLIFY (YD%F_PRE)
ENDIF
NULLIFY (YD%PHIF)
READ (KLUN) LF_PHIF
IF (LF_PHIF) THEN
  CALL LOAD (KLUN, YD%F_PHIF)
ELSE
  NULLIFY (YD%F_PHIF)
ENDIF
NULLIFY (YD%PREF)
READ (KLUN) LF_PREF
IF (LF_PREF) THEN
  CALL LOAD (KLUN, YD%F_PREF)
ELSE
  NULLIFY (YD%F_PREF)
ENDIF
NULLIFY (YD%WRL)
READ (KLUN) LF_WRL
IF (LF_WRL) THEN
  CALL LOAD (KLUN, YD%F_WRL)
ELSE
  NULLIFY (YD%F_WRL)
ENDIF
NULLIFY (YD%PREL)
READ (KLUN) LF_PREL
IF (LF_PREL) THEN
  CALL LOAD (KLUN, YD%F_PREL)
ELSE
  NULLIFY (YD%F_PREL)
ENDIF
NULLIFY (YD%PREM)
READ (KLUN) LF_PREM
IF (LF_PREM) THEN
  CALL LOAD (KLUN, YD%F_PREM)
ELSE
  NULLIFY (YD%F_PREM)
ENDIF
NULLIFY (YD%NHY)
READ (KLUN) LF_NHY
IF (LF_NHY) THEN
  CALL LOAD (KLUN, YD%F_NHY)
ELSE
  NULLIFY (YD%F_NHY)
ENDIF
NULLIFY (YD%GWFT)
READ (KLUN) LF_GWFT
IF (LF_GWFT) THEN
  CALL LOAD (KLUN, YD%F_GWFT)
ELSE
  NULLIFY (YD%F_GWFT)
ENDIF
NULLIFY (YD%KENE)
READ (KLUN) LF_KENE
IF (LF_KENE) THEN
  CALL LOAD (KLUN, YD%F_KENE)
ELSE
  NULLIFY (YD%F_KENE)
ENDIF
NULLIFY (YD%NHX)
READ (KLUN) LF_NHX
IF (LF_NHX) THEN
  CALL LOAD (KLUN, YD%F_NHX)
ELSE
  NULLIFY (YD%F_NHX)
ENDIF
NULLIFY (YD%PHIFL)
READ (KLUN) LF_PHIFL
IF (LF_PHIFL) THEN
  CALL LOAD (KLUN, YD%F_PHIFL)
ELSE
  NULLIFY (YD%F_PHIFL)
ENDIF
NULLIFY (YD%PHIFM)
READ (KLUN) LF_PHIFM
IF (LF_PHIFM) THEN
  CALL LOAD (KLUN, YD%F_PHIFM)
ELSE
  NULLIFY (YD%F_PHIFM)
ENDIF
NULLIFY (YD%RTL)
READ (KLUN) LF_RTL
IF (LF_RTL) THEN
  CALL LOAD (KLUN, YD%F_RTL)
ELSE
  NULLIFY (YD%F_RTL)
ENDIF
NULLIFY (YD%RTM)
READ (KLUN) LF_RTM
IF (LF_RTM) THEN
  CALL LOAD (KLUN, YD%F_RTM)
ELSE
  NULLIFY (YD%F_RTM)
ENDIF
CALL LOAD (KLUN, YD%RCP)
CALL LOAD (KLUN, YD%CTY)
CALL LOAD (KLUN, YD%UVH)
CALL LOAD (KLUN, YD%XYB)
NULLIFY (YD%DBBC)
READ (KLUN) LF_DBBC
IF (LF_DBBC) THEN
  CALL LOAD (KLUN, YD%F_DBBC)
ELSE
  NULLIFY (YD%F_DBBC)
ENDIF
NULLIFY (YD%GWS)
READ (KLUN) LF_GWS
IF (LF_GWS) THEN
  CALL LOAD (KLUN, YD%F_GWS)
ELSE
  NULLIFY (YD%F_GWS)
ENDIF
NULLIFY (YD%GWFL)
READ (KLUN) LF_GWFL
IF (LF_GWFL) THEN
  CALL LOAD (KLUN, YD%F_GWFL)
ELSE
  NULLIFY (YD%F_GWFL)
ENDIF
NULLIFY (YD%GWFM)
READ (KLUN) LF_GWFM
IF (LF_GWFM) THEN
  CALL LOAD (KLUN, YD%F_GWFM)
ELSE
  NULLIFY (YD%F_GWFM)
ENDIF
NULLIFY (YD%GWT)
READ (KLUN) LF_GWT
IF (LF_GWT) THEN
  CALL LOAD (KLUN, YD%F_GWT)
ELSE
  NULLIFY (YD%F_GWT)
ENDIF
NULLIFY (YD%NHPREF)
READ (KLUN) LF_NHPREF
IF (LF_NHPREF) THEN
  CALL LOAD (KLUN, YD%F_NHPREF)
ELSE
  NULLIFY (YD%F_NHPREF)
ENDIF
NULLIFY (YD%NHPREH)
READ (KLUN) LF_NHPREH
IF (LF_NHPREH) THEN
  CALL LOAD (KLUN, YD%F_NHPREH)
ELSE
  NULLIFY (YD%F_NHPREH)
ENDIF
NULLIFY (YD%QCHAL)
READ (KLUN) LF_QCHAL
IF (LF_QCHAL) THEN
  CALL LOAD (KLUN, YD%F_QCHAL)
ELSE
  NULLIFY (YD%F_QCHAL)
ENDIF
NULLIFY (YD%QCHAM)
READ (KLUN) LF_QCHAM
IF (LF_QCHAM) THEN
  CALL LOAD (KLUN, YD%F_QCHAM)
ELSE
  NULLIFY (YD%F_QCHAM)
ENDIF
NULLIFY (YD%RDPHI)
READ (KLUN) LF_RDPHI
IF (LF_RDPHI) THEN
  CALL LOAD (KLUN, YD%F_RDPHI)
ELSE
  NULLIFY (YD%F_RDPHI)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_CPG_DYN_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (CPG_DYN_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_DBBC, LF_GWFL, LF_GWFM, LF_GWFT, LF_GWS, LF_GWT, LF_KENE, LF_NHPREF, LF_NHPREH, LF_NHX
LOGICAL :: LF_NHY, LF_OROGL, LF_OROGM, LF_PHI, LF_PHIF, LF_PHIFL, LF_PHIFM, LF_PRE, LF_PREF, LF_PREL
LOGICAL :: LF_PREM, LF_QCHAL, LF_QCHAM, LF_RDPHI, LF_RTL, LF_RTM, LF_WRL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LF_OROGL = ASSOCIATED (YD%F_OROGL)
IF (LF_OROGL) THEN
  !$acc enter data create (YD%F_OROGL)
  !$acc update device (YD%F_OROGL)
  CALL COPY (YD%F_OROGL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_OROGL)
ENDIF

LF_OROGM = ASSOCIATED (YD%F_OROGM)
IF (LF_OROGM) THEN
  !$acc enter data create (YD%F_OROGM)
  !$acc update device (YD%F_OROGM)
  CALL COPY (YD%F_OROGM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_OROGM)
ENDIF

LF_PHI = ASSOCIATED (YD%F_PHI)
IF (LF_PHI) THEN
  !$acc enter data create (YD%F_PHI)
  !$acc update device (YD%F_PHI)
  CALL COPY (YD%F_PHI, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PHI)
ENDIF

LF_PRE = ASSOCIATED (YD%F_PRE)
IF (LF_PRE) THEN
  !$acc enter data create (YD%F_PRE)
  !$acc update device (YD%F_PRE)
  CALL COPY (YD%F_PRE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PRE)
ENDIF

LF_PHIF = ASSOCIATED (YD%F_PHIF)
IF (LF_PHIF) THEN
  !$acc enter data create (YD%F_PHIF)
  !$acc update device (YD%F_PHIF)
  CALL COPY (YD%F_PHIF, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PHIF)
ENDIF

LF_PREF = ASSOCIATED (YD%F_PREF)
IF (LF_PREF) THEN
  !$acc enter data create (YD%F_PREF)
  !$acc update device (YD%F_PREF)
  CALL COPY (YD%F_PREF, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PREF)
ENDIF

LF_WRL = ASSOCIATED (YD%F_WRL)
IF (LF_WRL) THEN
  !$acc enter data create (YD%F_WRL)
  !$acc update device (YD%F_WRL)
  CALL COPY (YD%F_WRL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_WRL)
ENDIF

LF_PREL = ASSOCIATED (YD%F_PREL)
IF (LF_PREL) THEN
  !$acc enter data create (YD%F_PREL)
  !$acc update device (YD%F_PREL)
  CALL COPY (YD%F_PREL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PREL)
ENDIF

LF_PREM = ASSOCIATED (YD%F_PREM)
IF (LF_PREM) THEN
  !$acc enter data create (YD%F_PREM)
  !$acc update device (YD%F_PREM)
  CALL COPY (YD%F_PREM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PREM)
ENDIF

LF_NHY = ASSOCIATED (YD%F_NHY)
IF (LF_NHY) THEN
  !$acc enter data create (YD%F_NHY)
  !$acc update device (YD%F_NHY)
  CALL COPY (YD%F_NHY, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NHY)
ENDIF

LF_GWFT = ASSOCIATED (YD%F_GWFT)
IF (LF_GWFT) THEN
  !$acc enter data create (YD%F_GWFT)
  !$acc update device (YD%F_GWFT)
  CALL COPY (YD%F_GWFT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_GWFT)
ENDIF

LF_KENE = ASSOCIATED (YD%F_KENE)
IF (LF_KENE) THEN
  !$acc enter data create (YD%F_KENE)
  !$acc update device (YD%F_KENE)
  CALL COPY (YD%F_KENE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_KENE)
ENDIF

LF_NHX = ASSOCIATED (YD%F_NHX)
IF (LF_NHX) THEN
  !$acc enter data create (YD%F_NHX)
  !$acc update device (YD%F_NHX)
  CALL COPY (YD%F_NHX, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NHX)
ENDIF

LF_PHIFL = ASSOCIATED (YD%F_PHIFL)
IF (LF_PHIFL) THEN
  !$acc enter data create (YD%F_PHIFL)
  !$acc update device (YD%F_PHIFL)
  CALL COPY (YD%F_PHIFL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PHIFL)
ENDIF

LF_PHIFM = ASSOCIATED (YD%F_PHIFM)
IF (LF_PHIFM) THEN
  !$acc enter data create (YD%F_PHIFM)
  !$acc update device (YD%F_PHIFM)
  CALL COPY (YD%F_PHIFM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_PHIFM)
ENDIF

LF_RTL = ASSOCIATED (YD%F_RTL)
IF (LF_RTL) THEN
  !$acc enter data create (YD%F_RTL)
  !$acc update device (YD%F_RTL)
  CALL COPY (YD%F_RTL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RTL)
ENDIF

LF_RTM = ASSOCIATED (YD%F_RTM)
IF (LF_RTM) THEN
  !$acc enter data create (YD%F_RTM)
  !$acc update device (YD%F_RTM)
  CALL COPY (YD%F_RTM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RTM)
ENDIF

CALL COPY (YD%RCP, LDCREATED=.TRUE.)

CALL COPY (YD%CTY, LDCREATED=.TRUE.)

CALL COPY (YD%UVH, LDCREATED=.TRUE.)

CALL COPY (YD%XYB, LDCREATED=.TRUE.)

LF_DBBC = ASSOCIATED (YD%F_DBBC)
IF (LF_DBBC) THEN
  !$acc enter data create (YD%F_DBBC)
  !$acc update device (YD%F_DBBC)
  CALL COPY (YD%F_DBBC, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_DBBC)
ENDIF

LF_GWS = ASSOCIATED (YD%F_GWS)
IF (LF_GWS) THEN
  !$acc enter data create (YD%F_GWS)
  !$acc update device (YD%F_GWS)
  CALL COPY (YD%F_GWS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_GWS)
ENDIF

LF_GWFL = ASSOCIATED (YD%F_GWFL)
IF (LF_GWFL) THEN
  !$acc enter data create (YD%F_GWFL)
  !$acc update device (YD%F_GWFL)
  CALL COPY (YD%F_GWFL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_GWFL)
ENDIF

LF_GWFM = ASSOCIATED (YD%F_GWFM)
IF (LF_GWFM) THEN
  !$acc enter data create (YD%F_GWFM)
  !$acc update device (YD%F_GWFM)
  CALL COPY (YD%F_GWFM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_GWFM)
ENDIF

LF_GWT = ASSOCIATED (YD%F_GWT)
IF (LF_GWT) THEN
  !$acc enter data create (YD%F_GWT)
  !$acc update device (YD%F_GWT)
  CALL COPY (YD%F_GWT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_GWT)
ENDIF

LF_NHPREF = ASSOCIATED (YD%F_NHPREF)
IF (LF_NHPREF) THEN
  !$acc enter data create (YD%F_NHPREF)
  !$acc update device (YD%F_NHPREF)
  CALL COPY (YD%F_NHPREF, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NHPREF)
ENDIF

LF_NHPREH = ASSOCIATED (YD%F_NHPREH)
IF (LF_NHPREH) THEN
  !$acc enter data create (YD%F_NHPREH)
  !$acc update device (YD%F_NHPREH)
  CALL COPY (YD%F_NHPREH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NHPREH)
ENDIF

LF_QCHAL = ASSOCIATED (YD%F_QCHAL)
IF (LF_QCHAL) THEN
  !$acc enter data create (YD%F_QCHAL)
  !$acc update device (YD%F_QCHAL)
  CALL COPY (YD%F_QCHAL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QCHAL)
ENDIF

LF_QCHAM = ASSOCIATED (YD%F_QCHAM)
IF (LF_QCHAM) THEN
  !$acc enter data create (YD%F_QCHAM)
  !$acc update device (YD%F_QCHAM)
  CALL COPY (YD%F_QCHAM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QCHAM)
ENDIF

LF_RDPHI = ASSOCIATED (YD%F_RDPHI)
IF (LF_RDPHI) THEN
  !$acc enter data create (YD%F_RDPHI)
  !$acc update device (YD%F_RDPHI)
  CALL COPY (YD%F_RDPHI, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RDPHI)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_CPG_DYN_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (CPG_DYN_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LF_DBBC, LF_GWFL, LF_GWFM, LF_GWFT, LF_GWS, LF_GWT, LF_KENE, LF_NHPREF, LF_NHPREH, LF_NHX
LOGICAL :: LF_NHY, LF_OROGL, LF_OROGM, LF_PHI, LF_PHIF, LF_PHIFL, LF_PHIFM, LF_PRE, LF_PREF, LF_PREL
LOGICAL :: LF_PREM, LF_QCHAL, LF_QCHAM, LF_RDPHI, LF_RTL, LF_RTM, LF_WRL

LF_OROGL = ASSOCIATED (YD%F_OROGL)
IF (LF_OROGL) THEN
  !$acc exit data detach (YD%F_OROGL)
  CALL WIPE (YD%F_OROGL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_OROGL)
ENDIF

LF_OROGM = ASSOCIATED (YD%F_OROGM)
IF (LF_OROGM) THEN
  !$acc exit data detach (YD%F_OROGM)
  CALL WIPE (YD%F_OROGM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_OROGM)
ENDIF

LF_PHI = ASSOCIATED (YD%F_PHI)
IF (LF_PHI) THEN
  !$acc exit data detach (YD%F_PHI)
  CALL WIPE (YD%F_PHI, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PHI)
ENDIF

LF_PRE = ASSOCIATED (YD%F_PRE)
IF (LF_PRE) THEN
  !$acc exit data detach (YD%F_PRE)
  CALL WIPE (YD%F_PRE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PRE)
ENDIF

LF_PHIF = ASSOCIATED (YD%F_PHIF)
IF (LF_PHIF) THEN
  !$acc exit data detach (YD%F_PHIF)
  CALL WIPE (YD%F_PHIF, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PHIF)
ENDIF

LF_PREF = ASSOCIATED (YD%F_PREF)
IF (LF_PREF) THEN
  !$acc exit data detach (YD%F_PREF)
  CALL WIPE (YD%F_PREF, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PREF)
ENDIF

LF_WRL = ASSOCIATED (YD%F_WRL)
IF (LF_WRL) THEN
  !$acc exit data detach (YD%F_WRL)
  CALL WIPE (YD%F_WRL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_WRL)
ENDIF

LF_PREL = ASSOCIATED (YD%F_PREL)
IF (LF_PREL) THEN
  !$acc exit data detach (YD%F_PREL)
  CALL WIPE (YD%F_PREL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PREL)
ENDIF

LF_PREM = ASSOCIATED (YD%F_PREM)
IF (LF_PREM) THEN
  !$acc exit data detach (YD%F_PREM)
  CALL WIPE (YD%F_PREM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PREM)
ENDIF

LF_NHY = ASSOCIATED (YD%F_NHY)
IF (LF_NHY) THEN
  !$acc exit data detach (YD%F_NHY)
  CALL WIPE (YD%F_NHY, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NHY)
ENDIF

LF_GWFT = ASSOCIATED (YD%F_GWFT)
IF (LF_GWFT) THEN
  !$acc exit data detach (YD%F_GWFT)
  CALL WIPE (YD%F_GWFT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_GWFT)
ENDIF

LF_KENE = ASSOCIATED (YD%F_KENE)
IF (LF_KENE) THEN
  !$acc exit data detach (YD%F_KENE)
  CALL WIPE (YD%F_KENE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_KENE)
ENDIF

LF_NHX = ASSOCIATED (YD%F_NHX)
IF (LF_NHX) THEN
  !$acc exit data detach (YD%F_NHX)
  CALL WIPE (YD%F_NHX, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NHX)
ENDIF

LF_PHIFL = ASSOCIATED (YD%F_PHIFL)
IF (LF_PHIFL) THEN
  !$acc exit data detach (YD%F_PHIFL)
  CALL WIPE (YD%F_PHIFL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PHIFL)
ENDIF

LF_PHIFM = ASSOCIATED (YD%F_PHIFM)
IF (LF_PHIFM) THEN
  !$acc exit data detach (YD%F_PHIFM)
  CALL WIPE (YD%F_PHIFM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_PHIFM)
ENDIF

LF_RTL = ASSOCIATED (YD%F_RTL)
IF (LF_RTL) THEN
  !$acc exit data detach (YD%F_RTL)
  CALL WIPE (YD%F_RTL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RTL)
ENDIF

LF_RTM = ASSOCIATED (YD%F_RTM)
IF (LF_RTM) THEN
  !$acc exit data detach (YD%F_RTM)
  CALL WIPE (YD%F_RTM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RTM)
ENDIF

CALL WIPE (YD%RCP, LDDELETED=.TRUE.)

CALL WIPE (YD%CTY, LDDELETED=.TRUE.)

CALL WIPE (YD%UVH, LDDELETED=.TRUE.)

CALL WIPE (YD%XYB, LDDELETED=.TRUE.)

LF_DBBC = ASSOCIATED (YD%F_DBBC)
IF (LF_DBBC) THEN
  !$acc exit data detach (YD%F_DBBC)
  CALL WIPE (YD%F_DBBC, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_DBBC)
ENDIF

LF_GWS = ASSOCIATED (YD%F_GWS)
IF (LF_GWS) THEN
  !$acc exit data detach (YD%F_GWS)
  CALL WIPE (YD%F_GWS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_GWS)
ENDIF

LF_GWFL = ASSOCIATED (YD%F_GWFL)
IF (LF_GWFL) THEN
  !$acc exit data detach (YD%F_GWFL)
  CALL WIPE (YD%F_GWFL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_GWFL)
ENDIF

LF_GWFM = ASSOCIATED (YD%F_GWFM)
IF (LF_GWFM) THEN
  !$acc exit data detach (YD%F_GWFM)
  CALL WIPE (YD%F_GWFM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_GWFM)
ENDIF

LF_GWT = ASSOCIATED (YD%F_GWT)
IF (LF_GWT) THEN
  !$acc exit data detach (YD%F_GWT)
  CALL WIPE (YD%F_GWT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_GWT)
ENDIF

LF_NHPREF = ASSOCIATED (YD%F_NHPREF)
IF (LF_NHPREF) THEN
  !$acc exit data detach (YD%F_NHPREF)
  CALL WIPE (YD%F_NHPREF, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NHPREF)
ENDIF

LF_NHPREH = ASSOCIATED (YD%F_NHPREH)
IF (LF_NHPREH) THEN
  !$acc exit data detach (YD%F_NHPREH)
  CALL WIPE (YD%F_NHPREH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NHPREH)
ENDIF

LF_QCHAL = ASSOCIATED (YD%F_QCHAL)
IF (LF_QCHAL) THEN
  !$acc exit data detach (YD%F_QCHAL)
  CALL WIPE (YD%F_QCHAL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QCHAL)
ENDIF

LF_QCHAM = ASSOCIATED (YD%F_QCHAM)
IF (LF_QCHAM) THEN
  !$acc exit data detach (YD%F_QCHAM)
  CALL WIPE (YD%F_QCHAM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QCHAM)
ENDIF

LF_RDPHI = ASSOCIATED (YD%F_RDPHI)
IF (LF_RDPHI) THEN
  !$acc exit data detach (YD%F_RDPHI)
  CALL WIPE (YD%F_RDPHI, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RDPHI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
