MODULE UTIL_TVDOZ_MOD

USE YOMVDOZ, ONLY : TVDOZ

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVDOZ
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVDOZ
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TVDOZ (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDOZ), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%VDHJS
WRITE (KLUN) YD%VDHJH
WRITE (KLUN) YD%VDHNS
WRITE (KLUN) YD%VDHNH
WRITE (KLUN) YD%VDPJS
WRITE (KLUN) YD%VDPJH
WRITE (KLUN) YD%VDPNS
WRITE (KLUN) YD%VDPNH
WRITE (KLUN) YD%VDEJS
WRITE (KLUN) YD%VDEJH
WRITE (KLUN) YD%VDENS
WRITE (KLUN) YD%VDENH
WRITE (KLUN) YD%VDAJS
WRITE (KLUN) YD%VDAJH
WRITE (KLUN) YD%VDANS
WRITE (KLUN) YD%VDANH
WRITE (KLUN) YD%VDNJS
WRITE (KLUN) YD%VDNJH
WRITE (KLUN) YD%VDNNS
WRITE (KLUN) YD%VDNNH
WRITE (KLUN) YD%VOZNJ
WRITE (KLUN) YD%VOZHS
WRITE (KLUN) YD%LRDIFOZ
WRITE (KLUN) YD%LRDEPOZ
END SUBROUTINE

SUBROUTINE LOAD_TVDOZ (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDOZ), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%VDHJS
READ (KLUN) YD%VDHJH
READ (KLUN) YD%VDHNS
READ (KLUN) YD%VDHNH
READ (KLUN) YD%VDPJS
READ (KLUN) YD%VDPJH
READ (KLUN) YD%VDPNS
READ (KLUN) YD%VDPNH
READ (KLUN) YD%VDEJS
READ (KLUN) YD%VDEJH
READ (KLUN) YD%VDENS
READ (KLUN) YD%VDENH
READ (KLUN) YD%VDAJS
READ (KLUN) YD%VDAJH
READ (KLUN) YD%VDANS
READ (KLUN) YD%VDANH
READ (KLUN) YD%VDNJS
READ (KLUN) YD%VDNJH
READ (KLUN) YD%VDNNS
READ (KLUN) YD%VDNNH
READ (KLUN) YD%VOZNJ
READ (KLUN) YD%VOZHS
READ (KLUN) YD%LRDIFOZ
READ (KLUN) YD%LRDEPOZ
END SUBROUTINE






END MODULE
