MODULE UTIL_TSTA_MOD

USE YOMSTA, ONLY : TSTA


INTERFACE SAVE
MODULE PROCEDURE SAVE_TSTA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSTA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSTA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSTA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSTA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTA), INTENT (IN), TARGET :: YD
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH

LSTPREH = ALLOCATED (YD%STPREH)
WRITE (KLUN) LSTPREH
IF (LSTPREH) THEN
  WRITE (KLUN) LBOUND (YD%STPREH)
  WRITE (KLUN) UBOUND (YD%STPREH)
  WRITE (KLUN) YD%STPREH
ENDIF
LSTPRE = ALLOCATED (YD%STPRE)
WRITE (KLUN) LSTPRE
IF (LSTPRE) THEN
  WRITE (KLUN) LBOUND (YD%STPRE)
  WRITE (KLUN) UBOUND (YD%STPRE)
  WRITE (KLUN) YD%STPRE
ENDIF
LSTPHI = ALLOCATED (YD%STPHI)
WRITE (KLUN) LSTPHI
IF (LSTPHI) THEN
  WRITE (KLUN) LBOUND (YD%STPHI)
  WRITE (KLUN) UBOUND (YD%STPHI)
  WRITE (KLUN) YD%STPHI
ENDIF
LSTTEM = ALLOCATED (YD%STTEM)
WRITE (KLUN) LSTTEM
IF (LSTTEM) THEN
  WRITE (KLUN) LBOUND (YD%STTEM)
  WRITE (KLUN) UBOUND (YD%STTEM)
  WRITE (KLUN) YD%STTEM
ENDIF
LSTDEN = ALLOCATED (YD%STDEN)
WRITE (KLUN) LSTDEN
IF (LSTDEN) THEN
  WRITE (KLUN) LBOUND (YD%STDEN)
  WRITE (KLUN) UBOUND (YD%STDEN)
  WRITE (KLUN) YD%STDEN
ENDIF
LSTZ = ALLOCATED (YD%STZ)
WRITE (KLUN) LSTZ
IF (LSTZ) THEN
  WRITE (KLUN) LBOUND (YD%STZ)
  WRITE (KLUN) UBOUND (YD%STZ)
  WRITE (KLUN) YD%STZ
ENDIF
LSVETAH = ALLOCATED (YD%SVETAH)
WRITE (KLUN) LSVETAH
IF (LSVETAH) THEN
  WRITE (KLUN) LBOUND (YD%SVETAH)
  WRITE (KLUN) UBOUND (YD%SVETAH)
  WRITE (KLUN) YD%SVETAH
ENDIF
LSVETAF = ALLOCATED (YD%SVETAF)
WRITE (KLUN) LSVETAF
IF (LSVETAF) THEN
  WRITE (KLUN) LBOUND (YD%SVETAF)
  WRITE (KLUN) UBOUND (YD%SVETAF)
  WRITE (KLUN) YD%SVETAF
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TSTA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH

READ (KLUN) LSTPREH
IF (LSTPREH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPREH (IL1(1):IU1(1)))
  READ (KLUN) YD%STPREH
ENDIF
READ (KLUN) LSTPRE
IF (LSTPRE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPRE (IL1(1):IU1(1)))
  READ (KLUN) YD%STPRE
ENDIF
READ (KLUN) LSTPHI
IF (LSTPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPHI (IL1(1):IU1(1)))
  READ (KLUN) YD%STPHI
ENDIF
READ (KLUN) LSTTEM
IF (LSTTEM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STTEM (IL1(1):IU1(1)))
  READ (KLUN) YD%STTEM
ENDIF
READ (KLUN) LSTDEN
IF (LSTDEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STDEN (IL1(1):IU1(1)))
  READ (KLUN) YD%STDEN
ENDIF
READ (KLUN) LSTZ
IF (LSTZ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STZ (IL1(1):IU1(1)))
  READ (KLUN) YD%STZ
ENDIF
READ (KLUN) LSVETAH
IF (LSVETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SVETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%SVETAH
ENDIF
READ (KLUN) LSVETAF
IF (LSVETAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SVETAF (IL1(1):IU1(1)))
  READ (KLUN) YD%SVETAF
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TSTA (YD, LDCREATED)
IMPLICIT NONE
TYPE (TSTA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LSTPREH = ALLOCATED (YD%STPREH)
IF (LSTPREH) THEN
  !$acc enter data create (YD%STPREH)
  !$acc update device (YD%STPREH)
  !$acc enter data attach (YD%STPREH)
ENDIF

LSTPRE = ALLOCATED (YD%STPRE)
IF (LSTPRE) THEN
  !$acc enter data create (YD%STPRE)
  !$acc update device (YD%STPRE)
  !$acc enter data attach (YD%STPRE)
ENDIF

LSTPHI = ALLOCATED (YD%STPHI)
IF (LSTPHI) THEN
  !$acc enter data create (YD%STPHI)
  !$acc update device (YD%STPHI)
  !$acc enter data attach (YD%STPHI)
ENDIF

LSTTEM = ALLOCATED (YD%STTEM)
IF (LSTTEM) THEN
  !$acc enter data create (YD%STTEM)
  !$acc update device (YD%STTEM)
  !$acc enter data attach (YD%STTEM)
ENDIF

LSTDEN = ALLOCATED (YD%STDEN)
IF (LSTDEN) THEN
  !$acc enter data create (YD%STDEN)
  !$acc update device (YD%STDEN)
  !$acc enter data attach (YD%STDEN)
ENDIF

LSTZ = ALLOCATED (YD%STZ)
IF (LSTZ) THEN
  !$acc enter data create (YD%STZ)
  !$acc update device (YD%STZ)
  !$acc enter data attach (YD%STZ)
ENDIF

LSVETAH = ALLOCATED (YD%SVETAH)
IF (LSVETAH) THEN
  !$acc enter data create (YD%SVETAH)
  !$acc update device (YD%SVETAH)
  !$acc enter data attach (YD%SVETAH)
ENDIF

LSVETAF = ALLOCATED (YD%SVETAF)
IF (LSVETAF) THEN
  !$acc enter data create (YD%SVETAF)
  !$acc update device (YD%SVETAF)
  !$acc enter data attach (YD%SVETAF)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TSTA (YD, LDDELETED)
IMPLICIT NONE
TYPE (TSTA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH

LSTPREH = ALLOCATED (YD%STPREH)
IF (LSTPREH) THEN
  !$acc exit data detach (YD%STPREH)
  !$acc exit data delete (YD%STPREH)
ENDIF

LSTPRE = ALLOCATED (YD%STPRE)
IF (LSTPRE) THEN
  !$acc exit data detach (YD%STPRE)
  !$acc exit data delete (YD%STPRE)
ENDIF

LSTPHI = ALLOCATED (YD%STPHI)
IF (LSTPHI) THEN
  !$acc exit data detach (YD%STPHI)
  !$acc exit data delete (YD%STPHI)
ENDIF

LSTTEM = ALLOCATED (YD%STTEM)
IF (LSTTEM) THEN
  !$acc exit data detach (YD%STTEM)
  !$acc exit data delete (YD%STTEM)
ENDIF

LSTDEN = ALLOCATED (YD%STDEN)
IF (LSTDEN) THEN
  !$acc exit data detach (YD%STDEN)
  !$acc exit data delete (YD%STDEN)
ENDIF

LSTZ = ALLOCATED (YD%STZ)
IF (LSTZ) THEN
  !$acc exit data detach (YD%STZ)
  !$acc exit data delete (YD%STZ)
ENDIF

LSVETAH = ALLOCATED (YD%SVETAH)
IF (LSVETAH) THEN
  !$acc exit data detach (YD%SVETAH)
  !$acc exit data delete (YD%SVETAH)
ENDIF

LSVETAF = ALLOCATED (YD%SVETAF)
IF (LSVETAF) THEN
  !$acc exit data detach (YD%SVETAF)
  !$acc exit data delete (YD%SVETAF)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
