MODULE UTIL_TCFU_MOD

USE YOMCFU_TYPE, ONLY : TCFU

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCFU
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCFU
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCFU
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCFU
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCFU (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TCFU_KEYS_MOD, ONLY : TCFU_KEYS, SAVE_TCFU_KEYS
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCFU), INTENT (IN), TARGET :: YD
CLASS (TCFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_FCCQL, LF_FCCQN, LF_FCHSP, LF_FCL, LF_FCLL, LF_FCLN, LF_FCS, LF_FCSQL, LF_FCSQN, LF_FDICQ
LOGICAL :: LF_FDICS, LF_FDISH, LF_FDITQ, LF_FDITS, LF_FDUTP, LF_FEVL, LF_FEVN, LF_FEVV, LF_FGEL, LF_FGELS
LOGICAL :: LF_FLASH, LF_FLWSP, LF_FNEB, LF_FNEBT, LF_FONTE, LF_FPLCG, LF_FPLCH, LF_FPLCL, LF_FPLCN, LF_FPLSG
LOGICAL :: LF_FPLSH, LF_FPLSL, LF_FPLSN, LF_FRSDNI, LF_FRSGNI, LF_FRSO, LF_FRSOC0, LF_FRSOC1, LF_FRSODS, LF_FRSOLU
LOGICAL :: LF_FRSOPS, LF_FRSOPT, LF_FRTH, LF_FRTHC0, LF_FRTHC1, LF_FRTHDS, LF_FTOPH, LF_FTR, LF_NEBBAS, LF_NEBCON
LOGICAL :: LF_NEBHAU, LF_NEBMOY, LF_OZONT, LF_QICE, LF_QLI, LF_QTOT, LF_RUISL, LF_RUISP, LF_RUISS, LF_SNS
LOGICAL :: LF_SPRES, LF_STRCU, LF_STRCV, LF_STRDU, LF_STRDV, LF_STRTU, LF_STRTV, LF_WS
YLSUPER => YD
CALL SAVE_TCFU_KEYS (KLUN, YLSUPER)
WRITE (KLUN) YD%NCFUTS
WRITE (KLUN) YD%NFRRC
WRITE (KLUN) YD%NFRCFU
WRITE (KLUN) YD%NFDCFU
WRITE (KLUN) YD%NTYPCFU
WRITE (KLUN) YD%NMTFLASH
WRITE (KLUN) YD%CALFLASH1
WRITE (KLUN) YD%CALFLASH2
WRITE (KLUN) YD%LREACFU
LF_FCCQL = ASSOCIATED (YD%F_FCCQL)
WRITE (KLUN) LF_FCCQL
IF (LF_FCCQL) THEN
  CALL SAVE (KLUN, YD%F_FCCQL)
ENDIF
CALL SAVE (KLUN, YD%YFCCQL)
LF_FCCQN = ASSOCIATED (YD%F_FCCQN)
WRITE (KLUN) LF_FCCQN
IF (LF_FCCQN) THEN
  CALL SAVE (KLUN, YD%F_FCCQN)
ENDIF
CALL SAVE (KLUN, YD%YFCCQN)
LF_FCHSP = ASSOCIATED (YD%F_FCHSP)
WRITE (KLUN) LF_FCHSP
IF (LF_FCHSP) THEN
  CALL SAVE (KLUN, YD%F_FCHSP)
ENDIF
CALL SAVE (KLUN, YD%YFCHSP)
LF_FCL = ASSOCIATED (YD%F_FCL)
WRITE (KLUN) LF_FCL
IF (LF_FCL) THEN
  CALL SAVE (KLUN, YD%F_FCL)
ENDIF
CALL SAVE (KLUN, YD%YFCL)
LF_FCLL = ASSOCIATED (YD%F_FCLL)
WRITE (KLUN) LF_FCLL
IF (LF_FCLL) THEN
  CALL SAVE (KLUN, YD%F_FCLL)
ENDIF
CALL SAVE (KLUN, YD%YFCLL)
LF_FCLN = ASSOCIATED (YD%F_FCLN)
WRITE (KLUN) LF_FCLN
IF (LF_FCLN) THEN
  CALL SAVE (KLUN, YD%F_FCLN)
ENDIF
CALL SAVE (KLUN, YD%YFCLN)
LF_FCSQL = ASSOCIATED (YD%F_FCSQL)
WRITE (KLUN) LF_FCSQL
IF (LF_FCSQL) THEN
  CALL SAVE (KLUN, YD%F_FCSQL)
ENDIF
CALL SAVE (KLUN, YD%YFCSQL)
LF_FCSQN = ASSOCIATED (YD%F_FCSQN)
WRITE (KLUN) LF_FCSQN
IF (LF_FCSQN) THEN
  CALL SAVE (KLUN, YD%F_FCSQN)
ENDIF
CALL SAVE (KLUN, YD%YFCSQN)
LF_FCS = ASSOCIATED (YD%F_FCS)
WRITE (KLUN) LF_FCS
IF (LF_FCS) THEN
  CALL SAVE (KLUN, YD%F_FCS)
ENDIF
CALL SAVE (KLUN, YD%YFCS)
LF_FDICQ = ASSOCIATED (YD%F_FDICQ)
WRITE (KLUN) LF_FDICQ
IF (LF_FDICQ) THEN
  CALL SAVE (KLUN, YD%F_FDICQ)
ENDIF
CALL SAVE (KLUN, YD%YFDICQ)
LF_FDICS = ASSOCIATED (YD%F_FDICS)
WRITE (KLUN) LF_FDICS
IF (LF_FDICS) THEN
  CALL SAVE (KLUN, YD%F_FDICS)
ENDIF
CALL SAVE (KLUN, YD%YFDICS)
LF_FDISH = ASSOCIATED (YD%F_FDISH)
WRITE (KLUN) LF_FDISH
IF (LF_FDISH) THEN
  CALL SAVE (KLUN, YD%F_FDISH)
ENDIF
CALL SAVE (KLUN, YD%YFDISH)
LF_FDITQ = ASSOCIATED (YD%F_FDITQ)
WRITE (KLUN) LF_FDITQ
IF (LF_FDITQ) THEN
  CALL SAVE (KLUN, YD%F_FDITQ)
ENDIF
CALL SAVE (KLUN, YD%YFDITQ)
LF_FDITS = ASSOCIATED (YD%F_FDITS)
WRITE (KLUN) LF_FDITS
IF (LF_FDITS) THEN
  CALL SAVE (KLUN, YD%F_FDITS)
ENDIF
CALL SAVE (KLUN, YD%YFDITS)
LF_FDUTP = ASSOCIATED (YD%F_FDUTP)
WRITE (KLUN) LF_FDUTP
IF (LF_FDUTP) THEN
  CALL SAVE (KLUN, YD%F_FDUTP)
ENDIF
CALL SAVE (KLUN, YD%YFDUTP)
LF_FEVL = ASSOCIATED (YD%F_FEVL)
WRITE (KLUN) LF_FEVL
IF (LF_FEVL) THEN
  CALL SAVE (KLUN, YD%F_FEVL)
ENDIF
CALL SAVE (KLUN, YD%YFEVL)
LF_FEVN = ASSOCIATED (YD%F_FEVN)
WRITE (KLUN) LF_FEVN
IF (LF_FEVN) THEN
  CALL SAVE (KLUN, YD%F_FEVN)
ENDIF
CALL SAVE (KLUN, YD%YFEVN)
LF_FEVV = ASSOCIATED (YD%F_FEVV)
WRITE (KLUN) LF_FEVV
IF (LF_FEVV) THEN
  CALL SAVE (KLUN, YD%F_FEVV)
ENDIF
CALL SAVE (KLUN, YD%YFEVV)
LF_FGEL = ASSOCIATED (YD%F_FGEL)
WRITE (KLUN) LF_FGEL
IF (LF_FGEL) THEN
  CALL SAVE (KLUN, YD%F_FGEL)
ENDIF
CALL SAVE (KLUN, YD%YFGEL)
LF_FGELS = ASSOCIATED (YD%F_FGELS)
WRITE (KLUN) LF_FGELS
IF (LF_FGELS) THEN
  CALL SAVE (KLUN, YD%F_FGELS)
ENDIF
CALL SAVE (KLUN, YD%YFGELS)
LF_FLASH = ASSOCIATED (YD%F_FLASH)
WRITE (KLUN) LF_FLASH
IF (LF_FLASH) THEN
  CALL SAVE (KLUN, YD%F_FLASH)
ENDIF
CALL SAVE (KLUN, YD%YFLASH)
LF_FLWSP = ASSOCIATED (YD%F_FLWSP)
WRITE (KLUN) LF_FLWSP
IF (LF_FLWSP) THEN
  CALL SAVE (KLUN, YD%F_FLWSP)
ENDIF
CALL SAVE (KLUN, YD%YFLWSP)
LF_FNEB = ASSOCIATED (YD%F_FNEB)
WRITE (KLUN) LF_FNEB
IF (LF_FNEB) THEN
  CALL SAVE (KLUN, YD%F_FNEB)
ENDIF
CALL SAVE (KLUN, YD%YFNEB)
LF_FNEBT = ASSOCIATED (YD%F_FNEBT)
WRITE (KLUN) LF_FNEBT
IF (LF_FNEBT) THEN
  CALL SAVE (KLUN, YD%F_FNEBT)
ENDIF
CALL SAVE (KLUN, YD%YFNEBT)
LF_FONTE = ASSOCIATED (YD%F_FONTE)
WRITE (KLUN) LF_FONTE
IF (LF_FONTE) THEN
  CALL SAVE (KLUN, YD%F_FONTE)
ENDIF
CALL SAVE (KLUN, YD%YFONTE)
LF_FPLCG = ASSOCIATED (YD%F_FPLCG)
WRITE (KLUN) LF_FPLCG
IF (LF_FPLCG) THEN
  CALL SAVE (KLUN, YD%F_FPLCG)
ENDIF
CALL SAVE (KLUN, YD%YFPLCG)
LF_FPLCH = ASSOCIATED (YD%F_FPLCH)
WRITE (KLUN) LF_FPLCH
IF (LF_FPLCH) THEN
  CALL SAVE (KLUN, YD%F_FPLCH)
ENDIF
CALL SAVE (KLUN, YD%YFPLCH)
LF_FPLCL = ASSOCIATED (YD%F_FPLCL)
WRITE (KLUN) LF_FPLCL
IF (LF_FPLCL) THEN
  CALL SAVE (KLUN, YD%F_FPLCL)
ENDIF
CALL SAVE (KLUN, YD%YFPLCL)
LF_FPLCN = ASSOCIATED (YD%F_FPLCN)
WRITE (KLUN) LF_FPLCN
IF (LF_FPLCN) THEN
  CALL SAVE (KLUN, YD%F_FPLCN)
ENDIF
CALL SAVE (KLUN, YD%YFPLCN)
LF_FPLSG = ASSOCIATED (YD%F_FPLSG)
WRITE (KLUN) LF_FPLSG
IF (LF_FPLSG) THEN
  CALL SAVE (KLUN, YD%F_FPLSG)
ENDIF
CALL SAVE (KLUN, YD%YFPLSG)
LF_FPLSH = ASSOCIATED (YD%F_FPLSH)
WRITE (KLUN) LF_FPLSH
IF (LF_FPLSH) THEN
  CALL SAVE (KLUN, YD%F_FPLSH)
ENDIF
CALL SAVE (KLUN, YD%YFPLSH)
LF_FPLSL = ASSOCIATED (YD%F_FPLSL)
WRITE (KLUN) LF_FPLSL
IF (LF_FPLSL) THEN
  CALL SAVE (KLUN, YD%F_FPLSL)
ENDIF
CALL SAVE (KLUN, YD%YFPLSL)
LF_FPLSN = ASSOCIATED (YD%F_FPLSN)
WRITE (KLUN) LF_FPLSN
IF (LF_FPLSN) THEN
  CALL SAVE (KLUN, YD%F_FPLSN)
ENDIF
CALL SAVE (KLUN, YD%YFPLSN)
LF_FRSDNI = ASSOCIATED (YD%F_FRSDNI)
WRITE (KLUN) LF_FRSDNI
IF (LF_FRSDNI) THEN
  CALL SAVE (KLUN, YD%F_FRSDNI)
ENDIF
CALL SAVE (KLUN, YD%YFRSDNI)
LF_FRSGNI = ASSOCIATED (YD%F_FRSGNI)
WRITE (KLUN) LF_FRSGNI
IF (LF_FRSGNI) THEN
  CALL SAVE (KLUN, YD%F_FRSGNI)
ENDIF
CALL SAVE (KLUN, YD%YFRSGNI)
LF_FRSOC0 = ASSOCIATED (YD%F_FRSOC0)
WRITE (KLUN) LF_FRSOC0
IF (LF_FRSOC0) THEN
  CALL SAVE (KLUN, YD%F_FRSOC0)
ENDIF
CALL SAVE (KLUN, YD%YFRSOC0)
LF_FRSOC1 = ASSOCIATED (YD%F_FRSOC1)
WRITE (KLUN) LF_FRSOC1
IF (LF_FRSOC1) THEN
  CALL SAVE (KLUN, YD%F_FRSOC1)
ENDIF
CALL SAVE (KLUN, YD%YFRSOC1)
LF_FRSODS = ASSOCIATED (YD%F_FRSODS)
WRITE (KLUN) LF_FRSODS
IF (LF_FRSODS) THEN
  CALL SAVE (KLUN, YD%F_FRSODS)
ENDIF
CALL SAVE (KLUN, YD%YFRSODS)
LF_FRSOLU = ASSOCIATED (YD%F_FRSOLU)
WRITE (KLUN) LF_FRSOLU
IF (LF_FRSOLU) THEN
  CALL SAVE (KLUN, YD%F_FRSOLU)
ENDIF
CALL SAVE (KLUN, YD%YFRSOLU)
LF_FRSOPS = ASSOCIATED (YD%F_FRSOPS)
WRITE (KLUN) LF_FRSOPS
IF (LF_FRSOPS) THEN
  CALL SAVE (KLUN, YD%F_FRSOPS)
ENDIF
CALL SAVE (KLUN, YD%YFRSOPS)
LF_FRSOPT = ASSOCIATED (YD%F_FRSOPT)
WRITE (KLUN) LF_FRSOPT
IF (LF_FRSOPT) THEN
  CALL SAVE (KLUN, YD%F_FRSOPT)
ENDIF
CALL SAVE (KLUN, YD%YFRSOPT)
LF_FRSO = ASSOCIATED (YD%F_FRSO)
WRITE (KLUN) LF_FRSO
IF (LF_FRSO) THEN
  CALL SAVE (KLUN, YD%F_FRSO)
ENDIF
CALL SAVE (KLUN, YD%YFRSO)
LF_FRTHC0 = ASSOCIATED (YD%F_FRTHC0)
WRITE (KLUN) LF_FRTHC0
IF (LF_FRTHC0) THEN
  CALL SAVE (KLUN, YD%F_FRTHC0)
ENDIF
CALL SAVE (KLUN, YD%YFRTHC0)
LF_FRTHC1 = ASSOCIATED (YD%F_FRTHC1)
WRITE (KLUN) LF_FRTHC1
IF (LF_FRTHC1) THEN
  CALL SAVE (KLUN, YD%F_FRTHC1)
ENDIF
CALL SAVE (KLUN, YD%YFRTHC1)
LF_FRTHDS = ASSOCIATED (YD%F_FRTHDS)
WRITE (KLUN) LF_FRTHDS
IF (LF_FRTHDS) THEN
  CALL SAVE (KLUN, YD%F_FRTHDS)
ENDIF
CALL SAVE (KLUN, YD%YFRTHDS)
LF_FRTH = ASSOCIATED (YD%F_FRTH)
WRITE (KLUN) LF_FRTH
IF (LF_FRTH) THEN
  CALL SAVE (KLUN, YD%F_FRTH)
ENDIF
CALL SAVE (KLUN, YD%YFRTH)
LF_FTOPH = ASSOCIATED (YD%F_FTOPH)
WRITE (KLUN) LF_FTOPH
IF (LF_FTOPH) THEN
  CALL SAVE (KLUN, YD%F_FTOPH)
ENDIF
CALL SAVE (KLUN, YD%YFTOPH)
LF_FTR = ASSOCIATED (YD%F_FTR)
WRITE (KLUN) LF_FTR
IF (LF_FTR) THEN
  CALL SAVE (KLUN, YD%F_FTR)
ENDIF
CALL SAVE (KLUN, YD%YFTR)
LF_NEBBAS = ASSOCIATED (YD%F_NEBBAS)
WRITE (KLUN) LF_NEBBAS
IF (LF_NEBBAS) THEN
  CALL SAVE (KLUN, YD%F_NEBBAS)
ENDIF
CALL SAVE (KLUN, YD%YNEBBAS)
LF_NEBCON = ASSOCIATED (YD%F_NEBCON)
WRITE (KLUN) LF_NEBCON
IF (LF_NEBCON) THEN
  CALL SAVE (KLUN, YD%F_NEBCON)
ENDIF
CALL SAVE (KLUN, YD%YNEBCON)
LF_NEBHAU = ASSOCIATED (YD%F_NEBHAU)
WRITE (KLUN) LF_NEBHAU
IF (LF_NEBHAU) THEN
  CALL SAVE (KLUN, YD%F_NEBHAU)
ENDIF
CALL SAVE (KLUN, YD%YNEBHAU)
LF_NEBMOY = ASSOCIATED (YD%F_NEBMOY)
WRITE (KLUN) LF_NEBMOY
IF (LF_NEBMOY) THEN
  CALL SAVE (KLUN, YD%F_NEBMOY)
ENDIF
CALL SAVE (KLUN, YD%YNEBMOY)
LF_OZONT = ASSOCIATED (YD%F_OZONT)
WRITE (KLUN) LF_OZONT
IF (LF_OZONT) THEN
  CALL SAVE (KLUN, YD%F_OZONT)
ENDIF
CALL SAVE (KLUN, YD%YOZONT)
LF_QICE = ASSOCIATED (YD%F_QICE)
WRITE (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL SAVE (KLUN, YD%F_QICE)
ENDIF
CALL SAVE (KLUN, YD%YQICE)
LF_QLI = ASSOCIATED (YD%F_QLI)
WRITE (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL SAVE (KLUN, YD%F_QLI)
ENDIF
CALL SAVE (KLUN, YD%YQLI)
LF_QTOT = ASSOCIATED (YD%F_QTOT)
WRITE (KLUN) LF_QTOT
IF (LF_QTOT) THEN
  CALL SAVE (KLUN, YD%F_QTOT)
ENDIF
CALL SAVE (KLUN, YD%YQTOT)
LF_RUISL = ASSOCIATED (YD%F_RUISL)
WRITE (KLUN) LF_RUISL
IF (LF_RUISL) THEN
  CALL SAVE (KLUN, YD%F_RUISL)
ENDIF
CALL SAVE (KLUN, YD%YRUISL)
LF_RUISP = ASSOCIATED (YD%F_RUISP)
WRITE (KLUN) LF_RUISP
IF (LF_RUISP) THEN
  CALL SAVE (KLUN, YD%F_RUISP)
ENDIF
CALL SAVE (KLUN, YD%YRUISP)
LF_RUISS = ASSOCIATED (YD%F_RUISS)
WRITE (KLUN) LF_RUISS
IF (LF_RUISS) THEN
  CALL SAVE (KLUN, YD%F_RUISS)
ENDIF
CALL SAVE (KLUN, YD%YRUISS)
LF_SNS = ASSOCIATED (YD%F_SNS)
WRITE (KLUN) LF_SNS
IF (LF_SNS) THEN
  CALL SAVE (KLUN, YD%F_SNS)
ENDIF
CALL SAVE (KLUN, YD%YSNS)
LF_SPRES = ASSOCIATED (YD%F_SPRES)
WRITE (KLUN) LF_SPRES
IF (LF_SPRES) THEN
  CALL SAVE (KLUN, YD%F_SPRES)
ENDIF
CALL SAVE (KLUN, YD%YSPRES)
LF_STRCU = ASSOCIATED (YD%F_STRCU)
WRITE (KLUN) LF_STRCU
IF (LF_STRCU) THEN
  CALL SAVE (KLUN, YD%F_STRCU)
ENDIF
CALL SAVE (KLUN, YD%YSTRCU)
LF_STRCV = ASSOCIATED (YD%F_STRCV)
WRITE (KLUN) LF_STRCV
IF (LF_STRCV) THEN
  CALL SAVE (KLUN, YD%F_STRCV)
ENDIF
CALL SAVE (KLUN, YD%YSTRCV)
LF_STRDU = ASSOCIATED (YD%F_STRDU)
WRITE (KLUN) LF_STRDU
IF (LF_STRDU) THEN
  CALL SAVE (KLUN, YD%F_STRDU)
ENDIF
CALL SAVE (KLUN, YD%YSTRDU)
LF_STRDV = ASSOCIATED (YD%F_STRDV)
WRITE (KLUN) LF_STRDV
IF (LF_STRDV) THEN
  CALL SAVE (KLUN, YD%F_STRDV)
ENDIF
CALL SAVE (KLUN, YD%YSTRDV)
LF_STRTU = ASSOCIATED (YD%F_STRTU)
WRITE (KLUN) LF_STRTU
IF (LF_STRTU) THEN
  CALL SAVE (KLUN, YD%F_STRTU)
ENDIF
CALL SAVE (KLUN, YD%YSTRTU)
LF_STRTV = ASSOCIATED (YD%F_STRTV)
WRITE (KLUN) LF_STRTV
IF (LF_STRTV) THEN
  CALL SAVE (KLUN, YD%F_STRTV)
ENDIF
CALL SAVE (KLUN, YD%YSTRTV)
LF_WS = ASSOCIATED (YD%F_WS)
WRITE (KLUN) LF_WS
IF (LF_WS) THEN
  CALL SAVE (KLUN, YD%F_WS)
ENDIF
CALL SAVE (KLUN, YD%YWS)
END SUBROUTINE

SUBROUTINE LOAD_TCFU (KLUN, YD)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TCFU_KEYS_MOD, ONLY : TCFU_KEYS, LOAD_TCFU_KEYS

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCFU), INTENT (OUT), TARGET :: YD
CLASS (TCFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_FCCQL, LF_FCCQN, LF_FCHSP, LF_FCL, LF_FCLL, LF_FCLN, LF_FCS, LF_FCSQL, LF_FCSQN, LF_FDICQ
LOGICAL :: LF_FDICS, LF_FDISH, LF_FDITQ, LF_FDITS, LF_FDUTP, LF_FEVL, LF_FEVN, LF_FEVV, LF_FGEL, LF_FGELS
LOGICAL :: LF_FLASH, LF_FLWSP, LF_FNEB, LF_FNEBT, LF_FONTE, LF_FPLCG, LF_FPLCH, LF_FPLCL, LF_FPLCN, LF_FPLSG
LOGICAL :: LF_FPLSH, LF_FPLSL, LF_FPLSN, LF_FRSDNI, LF_FRSGNI, LF_FRSO, LF_FRSOC0, LF_FRSOC1, LF_FRSODS, LF_FRSOLU
LOGICAL :: LF_FRSOPS, LF_FRSOPT, LF_FRTH, LF_FRTHC0, LF_FRTHC1, LF_FRTHDS, LF_FTOPH, LF_FTR, LF_NEBBAS, LF_NEBCON
LOGICAL :: LF_NEBHAU, LF_NEBMOY, LF_OZONT, LF_QICE, LF_QLI, LF_QTOT, LF_RUISL, LF_RUISP, LF_RUISS, LF_SNS
LOGICAL :: LF_SPRES, LF_STRCU, LF_STRCV, LF_STRDU, LF_STRDV, LF_STRTU, LF_STRTV, LF_WS
YLSUPER => YD
CALL LOAD_TCFU_KEYS (KLUN, YLSUPER)
READ (KLUN) YD%NCFUTS
READ (KLUN) YD%NFRRC
READ (KLUN) YD%NFRCFU
READ (KLUN) YD%NFDCFU
READ (KLUN) YD%NTYPCFU
READ (KLUN) YD%NMTFLASH
READ (KLUN) YD%CALFLASH1
READ (KLUN) YD%CALFLASH2
READ (KLUN) YD%LREACFU
NULLIFY (YD%CFUBUF_B)
NULLIFY (YD%FCCQL)
READ (KLUN) LF_FCCQL
IF (LF_FCCQL) THEN
  CALL LOAD (KLUN, YD%F_FCCQL)
ELSE
  NULLIFY (YD%F_FCCQL)
ENDIF
CALL LOAD (KLUN, YD%YFCCQL)
NULLIFY (YD%FCCQN)
READ (KLUN) LF_FCCQN
IF (LF_FCCQN) THEN
  CALL LOAD (KLUN, YD%F_FCCQN)
ELSE
  NULLIFY (YD%F_FCCQN)
ENDIF
CALL LOAD (KLUN, YD%YFCCQN)
NULLIFY (YD%FCHSP)
READ (KLUN) LF_FCHSP
IF (LF_FCHSP) THEN
  CALL LOAD (KLUN, YD%F_FCHSP)
ELSE
  NULLIFY (YD%F_FCHSP)
ENDIF
CALL LOAD (KLUN, YD%YFCHSP)
NULLIFY (YD%FCL)
READ (KLUN) LF_FCL
IF (LF_FCL) THEN
  CALL LOAD (KLUN, YD%F_FCL)
ELSE
  NULLIFY (YD%F_FCL)
ENDIF
CALL LOAD (KLUN, YD%YFCL)
NULLIFY (YD%FCLL)
READ (KLUN) LF_FCLL
IF (LF_FCLL) THEN
  CALL LOAD (KLUN, YD%F_FCLL)
ELSE
  NULLIFY (YD%F_FCLL)
ENDIF
CALL LOAD (KLUN, YD%YFCLL)
NULLIFY (YD%FCLN)
READ (KLUN) LF_FCLN
IF (LF_FCLN) THEN
  CALL LOAD (KLUN, YD%F_FCLN)
ELSE
  NULLIFY (YD%F_FCLN)
ENDIF
CALL LOAD (KLUN, YD%YFCLN)
NULLIFY (YD%FCSQL)
READ (KLUN) LF_FCSQL
IF (LF_FCSQL) THEN
  CALL LOAD (KLUN, YD%F_FCSQL)
ELSE
  NULLIFY (YD%F_FCSQL)
ENDIF
CALL LOAD (KLUN, YD%YFCSQL)
NULLIFY (YD%FCSQN)
READ (KLUN) LF_FCSQN
IF (LF_FCSQN) THEN
  CALL LOAD (KLUN, YD%F_FCSQN)
ELSE
  NULLIFY (YD%F_FCSQN)
ENDIF
CALL LOAD (KLUN, YD%YFCSQN)
NULLIFY (YD%FCS)
READ (KLUN) LF_FCS
IF (LF_FCS) THEN
  CALL LOAD (KLUN, YD%F_FCS)
ELSE
  NULLIFY (YD%F_FCS)
ENDIF
CALL LOAD (KLUN, YD%YFCS)
NULLIFY (YD%FDICQ)
READ (KLUN) LF_FDICQ
IF (LF_FDICQ) THEN
  CALL LOAD (KLUN, YD%F_FDICQ)
ELSE
  NULLIFY (YD%F_FDICQ)
ENDIF
CALL LOAD (KLUN, YD%YFDICQ)
NULLIFY (YD%FDICS)
READ (KLUN) LF_FDICS
IF (LF_FDICS) THEN
  CALL LOAD (KLUN, YD%F_FDICS)
ELSE
  NULLIFY (YD%F_FDICS)
ENDIF
CALL LOAD (KLUN, YD%YFDICS)
NULLIFY (YD%FDISH)
READ (KLUN) LF_FDISH
IF (LF_FDISH) THEN
  CALL LOAD (KLUN, YD%F_FDISH)
ELSE
  NULLIFY (YD%F_FDISH)
ENDIF
CALL LOAD (KLUN, YD%YFDISH)
NULLIFY (YD%FDITQ)
READ (KLUN) LF_FDITQ
IF (LF_FDITQ) THEN
  CALL LOAD (KLUN, YD%F_FDITQ)
ELSE
  NULLIFY (YD%F_FDITQ)
ENDIF
CALL LOAD (KLUN, YD%YFDITQ)
NULLIFY (YD%FDITS)
READ (KLUN) LF_FDITS
IF (LF_FDITS) THEN
  CALL LOAD (KLUN, YD%F_FDITS)
ELSE
  NULLIFY (YD%F_FDITS)
ENDIF
CALL LOAD (KLUN, YD%YFDITS)
NULLIFY (YD%FDUTP)
READ (KLUN) LF_FDUTP
IF (LF_FDUTP) THEN
  CALL LOAD (KLUN, YD%F_FDUTP)
ELSE
  NULLIFY (YD%F_FDUTP)
ENDIF
CALL LOAD (KLUN, YD%YFDUTP)
NULLIFY (YD%FEVL)
READ (KLUN) LF_FEVL
IF (LF_FEVL) THEN
  CALL LOAD (KLUN, YD%F_FEVL)
ELSE
  NULLIFY (YD%F_FEVL)
ENDIF
CALL LOAD (KLUN, YD%YFEVL)
NULLIFY (YD%FEVN)
READ (KLUN) LF_FEVN
IF (LF_FEVN) THEN
  CALL LOAD (KLUN, YD%F_FEVN)
ELSE
  NULLIFY (YD%F_FEVN)
ENDIF
CALL LOAD (KLUN, YD%YFEVN)
NULLIFY (YD%FEVV)
READ (KLUN) LF_FEVV
IF (LF_FEVV) THEN
  CALL LOAD (KLUN, YD%F_FEVV)
ELSE
  NULLIFY (YD%F_FEVV)
ENDIF
CALL LOAD (KLUN, YD%YFEVV)
NULLIFY (YD%FGEL)
READ (KLUN) LF_FGEL
IF (LF_FGEL) THEN
  CALL LOAD (KLUN, YD%F_FGEL)
ELSE
  NULLIFY (YD%F_FGEL)
ENDIF
CALL LOAD (KLUN, YD%YFGEL)
NULLIFY (YD%FGELS)
READ (KLUN) LF_FGELS
IF (LF_FGELS) THEN
  CALL LOAD (KLUN, YD%F_FGELS)
ELSE
  NULLIFY (YD%F_FGELS)
ENDIF
CALL LOAD (KLUN, YD%YFGELS)
NULLIFY (YD%FLASH)
READ (KLUN) LF_FLASH
IF (LF_FLASH) THEN
  CALL LOAD (KLUN, YD%F_FLASH)
ELSE
  NULLIFY (YD%F_FLASH)
ENDIF
CALL LOAD (KLUN, YD%YFLASH)
NULLIFY (YD%FLWSP)
READ (KLUN) LF_FLWSP
IF (LF_FLWSP) THEN
  CALL LOAD (KLUN, YD%F_FLWSP)
ELSE
  NULLIFY (YD%F_FLWSP)
ENDIF
CALL LOAD (KLUN, YD%YFLWSP)
NULLIFY (YD%FNEB)
READ (KLUN) LF_FNEB
IF (LF_FNEB) THEN
  CALL LOAD (KLUN, YD%F_FNEB)
ELSE
  NULLIFY (YD%F_FNEB)
ENDIF
CALL LOAD (KLUN, YD%YFNEB)
NULLIFY (YD%FNEBT)
READ (KLUN) LF_FNEBT
IF (LF_FNEBT) THEN
  CALL LOAD (KLUN, YD%F_FNEBT)
ELSE
  NULLIFY (YD%F_FNEBT)
ENDIF
CALL LOAD (KLUN, YD%YFNEBT)
NULLIFY (YD%FONTE)
READ (KLUN) LF_FONTE
IF (LF_FONTE) THEN
  CALL LOAD (KLUN, YD%F_FONTE)
ELSE
  NULLIFY (YD%F_FONTE)
ENDIF
CALL LOAD (KLUN, YD%YFONTE)
NULLIFY (YD%FPLCG)
READ (KLUN) LF_FPLCG
IF (LF_FPLCG) THEN
  CALL LOAD (KLUN, YD%F_FPLCG)
ELSE
  NULLIFY (YD%F_FPLCG)
ENDIF
CALL LOAD (KLUN, YD%YFPLCG)
NULLIFY (YD%FPLCH)
READ (KLUN) LF_FPLCH
IF (LF_FPLCH) THEN
  CALL LOAD (KLUN, YD%F_FPLCH)
ELSE
  NULLIFY (YD%F_FPLCH)
ENDIF
CALL LOAD (KLUN, YD%YFPLCH)
NULLIFY (YD%FPLCL)
READ (KLUN) LF_FPLCL
IF (LF_FPLCL) THEN
  CALL LOAD (KLUN, YD%F_FPLCL)
ELSE
  NULLIFY (YD%F_FPLCL)
ENDIF
CALL LOAD (KLUN, YD%YFPLCL)
NULLIFY (YD%FPLCN)
READ (KLUN) LF_FPLCN
IF (LF_FPLCN) THEN
  CALL LOAD (KLUN, YD%F_FPLCN)
ELSE
  NULLIFY (YD%F_FPLCN)
ENDIF
CALL LOAD (KLUN, YD%YFPLCN)
NULLIFY (YD%FPLSG)
READ (KLUN) LF_FPLSG
IF (LF_FPLSG) THEN
  CALL LOAD (KLUN, YD%F_FPLSG)
ELSE
  NULLIFY (YD%F_FPLSG)
ENDIF
CALL LOAD (KLUN, YD%YFPLSG)
NULLIFY (YD%FPLSH)
READ (KLUN) LF_FPLSH
IF (LF_FPLSH) THEN
  CALL LOAD (KLUN, YD%F_FPLSH)
ELSE
  NULLIFY (YD%F_FPLSH)
ENDIF
CALL LOAD (KLUN, YD%YFPLSH)
NULLIFY (YD%FPLSL)
READ (KLUN) LF_FPLSL
IF (LF_FPLSL) THEN
  CALL LOAD (KLUN, YD%F_FPLSL)
ELSE
  NULLIFY (YD%F_FPLSL)
ENDIF
CALL LOAD (KLUN, YD%YFPLSL)
NULLIFY (YD%FPLSN)
READ (KLUN) LF_FPLSN
IF (LF_FPLSN) THEN
  CALL LOAD (KLUN, YD%F_FPLSN)
ELSE
  NULLIFY (YD%F_FPLSN)
ENDIF
CALL LOAD (KLUN, YD%YFPLSN)
NULLIFY (YD%FRSDNI)
READ (KLUN) LF_FRSDNI
IF (LF_FRSDNI) THEN
  CALL LOAD (KLUN, YD%F_FRSDNI)
ELSE
  NULLIFY (YD%F_FRSDNI)
ENDIF
CALL LOAD (KLUN, YD%YFRSDNI)
NULLIFY (YD%FRSGNI)
READ (KLUN) LF_FRSGNI
IF (LF_FRSGNI) THEN
  CALL LOAD (KLUN, YD%F_FRSGNI)
ELSE
  NULLIFY (YD%F_FRSGNI)
ENDIF
CALL LOAD (KLUN, YD%YFRSGNI)
NULLIFY (YD%FRSOC0)
READ (KLUN) LF_FRSOC0
IF (LF_FRSOC0) THEN
  CALL LOAD (KLUN, YD%F_FRSOC0)
ELSE
  NULLIFY (YD%F_FRSOC0)
ENDIF
CALL LOAD (KLUN, YD%YFRSOC0)
NULLIFY (YD%FRSOC1)
READ (KLUN) LF_FRSOC1
IF (LF_FRSOC1) THEN
  CALL LOAD (KLUN, YD%F_FRSOC1)
ELSE
  NULLIFY (YD%F_FRSOC1)
ENDIF
CALL LOAD (KLUN, YD%YFRSOC1)
NULLIFY (YD%FRSODS)
READ (KLUN) LF_FRSODS
IF (LF_FRSODS) THEN
  CALL LOAD (KLUN, YD%F_FRSODS)
ELSE
  NULLIFY (YD%F_FRSODS)
ENDIF
CALL LOAD (KLUN, YD%YFRSODS)
NULLIFY (YD%FRSOLU)
READ (KLUN) LF_FRSOLU
IF (LF_FRSOLU) THEN
  CALL LOAD (KLUN, YD%F_FRSOLU)
ELSE
  NULLIFY (YD%F_FRSOLU)
ENDIF
CALL LOAD (KLUN, YD%YFRSOLU)
NULLIFY (YD%FRSOPS)
READ (KLUN) LF_FRSOPS
IF (LF_FRSOPS) THEN
  CALL LOAD (KLUN, YD%F_FRSOPS)
ELSE
  NULLIFY (YD%F_FRSOPS)
ENDIF
CALL LOAD (KLUN, YD%YFRSOPS)
NULLIFY (YD%FRSOPT)
READ (KLUN) LF_FRSOPT
IF (LF_FRSOPT) THEN
  CALL LOAD (KLUN, YD%F_FRSOPT)
ELSE
  NULLIFY (YD%F_FRSOPT)
ENDIF
CALL LOAD (KLUN, YD%YFRSOPT)
NULLIFY (YD%FRSO)
READ (KLUN) LF_FRSO
IF (LF_FRSO) THEN
  CALL LOAD (KLUN, YD%F_FRSO)
ELSE
  NULLIFY (YD%F_FRSO)
ENDIF
CALL LOAD (KLUN, YD%YFRSO)
NULLIFY (YD%FRTHC0)
READ (KLUN) LF_FRTHC0
IF (LF_FRTHC0) THEN
  CALL LOAD (KLUN, YD%F_FRTHC0)
ELSE
  NULLIFY (YD%F_FRTHC0)
ENDIF
CALL LOAD (KLUN, YD%YFRTHC0)
NULLIFY (YD%FRTHC1)
READ (KLUN) LF_FRTHC1
IF (LF_FRTHC1) THEN
  CALL LOAD (KLUN, YD%F_FRTHC1)
ELSE
  NULLIFY (YD%F_FRTHC1)
ENDIF
CALL LOAD (KLUN, YD%YFRTHC1)
NULLIFY (YD%FRTHDS)
READ (KLUN) LF_FRTHDS
IF (LF_FRTHDS) THEN
  CALL LOAD (KLUN, YD%F_FRTHDS)
ELSE
  NULLIFY (YD%F_FRTHDS)
ENDIF
CALL LOAD (KLUN, YD%YFRTHDS)
NULLIFY (YD%FRTH)
READ (KLUN) LF_FRTH
IF (LF_FRTH) THEN
  CALL LOAD (KLUN, YD%F_FRTH)
ELSE
  NULLIFY (YD%F_FRTH)
ENDIF
CALL LOAD (KLUN, YD%YFRTH)
NULLIFY (YD%FTOPH)
READ (KLUN) LF_FTOPH
IF (LF_FTOPH) THEN
  CALL LOAD (KLUN, YD%F_FTOPH)
ELSE
  NULLIFY (YD%F_FTOPH)
ENDIF
CALL LOAD (KLUN, YD%YFTOPH)
NULLIFY (YD%FTR)
READ (KLUN) LF_FTR
IF (LF_FTR) THEN
  CALL LOAD (KLUN, YD%F_FTR)
ELSE
  NULLIFY (YD%F_FTR)
ENDIF
CALL LOAD (KLUN, YD%YFTR)
NULLIFY (YD%NEBBAS)
READ (KLUN) LF_NEBBAS
IF (LF_NEBBAS) THEN
  CALL LOAD (KLUN, YD%F_NEBBAS)
ELSE
  NULLIFY (YD%F_NEBBAS)
ENDIF
CALL LOAD (KLUN, YD%YNEBBAS)
NULLIFY (YD%NEBCON)
READ (KLUN) LF_NEBCON
IF (LF_NEBCON) THEN
  CALL LOAD (KLUN, YD%F_NEBCON)
ELSE
  NULLIFY (YD%F_NEBCON)
ENDIF
CALL LOAD (KLUN, YD%YNEBCON)
NULLIFY (YD%NEBHAU)
READ (KLUN) LF_NEBHAU
IF (LF_NEBHAU) THEN
  CALL LOAD (KLUN, YD%F_NEBHAU)
ELSE
  NULLIFY (YD%F_NEBHAU)
ENDIF
CALL LOAD (KLUN, YD%YNEBHAU)
NULLIFY (YD%NEBMOY)
READ (KLUN) LF_NEBMOY
IF (LF_NEBMOY) THEN
  CALL LOAD (KLUN, YD%F_NEBMOY)
ELSE
  NULLIFY (YD%F_NEBMOY)
ENDIF
CALL LOAD (KLUN, YD%YNEBMOY)
NULLIFY (YD%OZONT)
READ (KLUN) LF_OZONT
IF (LF_OZONT) THEN
  CALL LOAD (KLUN, YD%F_OZONT)
ELSE
  NULLIFY (YD%F_OZONT)
ENDIF
CALL LOAD (KLUN, YD%YOZONT)
NULLIFY (YD%QICE)
READ (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL LOAD (KLUN, YD%F_QICE)
ELSE
  NULLIFY (YD%F_QICE)
ENDIF
CALL LOAD (KLUN, YD%YQICE)
NULLIFY (YD%QLI)
READ (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL LOAD (KLUN, YD%F_QLI)
ELSE
  NULLIFY (YD%F_QLI)
ENDIF
CALL LOAD (KLUN, YD%YQLI)
NULLIFY (YD%QTOT)
READ (KLUN) LF_QTOT
IF (LF_QTOT) THEN
  CALL LOAD (KLUN, YD%F_QTOT)
ELSE
  NULLIFY (YD%F_QTOT)
ENDIF
CALL LOAD (KLUN, YD%YQTOT)
NULLIFY (YD%RUISL)
READ (KLUN) LF_RUISL
IF (LF_RUISL) THEN
  CALL LOAD (KLUN, YD%F_RUISL)
ELSE
  NULLIFY (YD%F_RUISL)
ENDIF
CALL LOAD (KLUN, YD%YRUISL)
NULLIFY (YD%RUISP)
READ (KLUN) LF_RUISP
IF (LF_RUISP) THEN
  CALL LOAD (KLUN, YD%F_RUISP)
ELSE
  NULLIFY (YD%F_RUISP)
ENDIF
CALL LOAD (KLUN, YD%YRUISP)
NULLIFY (YD%RUISS)
READ (KLUN) LF_RUISS
IF (LF_RUISS) THEN
  CALL LOAD (KLUN, YD%F_RUISS)
ELSE
  NULLIFY (YD%F_RUISS)
ENDIF
CALL LOAD (KLUN, YD%YRUISS)
NULLIFY (YD%SNS)
READ (KLUN) LF_SNS
IF (LF_SNS) THEN
  CALL LOAD (KLUN, YD%F_SNS)
ELSE
  NULLIFY (YD%F_SNS)
ENDIF
CALL LOAD (KLUN, YD%YSNS)
NULLIFY (YD%SPRES)
READ (KLUN) LF_SPRES
IF (LF_SPRES) THEN
  CALL LOAD (KLUN, YD%F_SPRES)
ELSE
  NULLIFY (YD%F_SPRES)
ENDIF
CALL LOAD (KLUN, YD%YSPRES)
NULLIFY (YD%STRCU)
READ (KLUN) LF_STRCU
IF (LF_STRCU) THEN
  CALL LOAD (KLUN, YD%F_STRCU)
ELSE
  NULLIFY (YD%F_STRCU)
ENDIF
CALL LOAD (KLUN, YD%YSTRCU)
NULLIFY (YD%STRCV)
READ (KLUN) LF_STRCV
IF (LF_STRCV) THEN
  CALL LOAD (KLUN, YD%F_STRCV)
ELSE
  NULLIFY (YD%F_STRCV)
ENDIF
CALL LOAD (KLUN, YD%YSTRCV)
NULLIFY (YD%STRDU)
READ (KLUN) LF_STRDU
IF (LF_STRDU) THEN
  CALL LOAD (KLUN, YD%F_STRDU)
ELSE
  NULLIFY (YD%F_STRDU)
ENDIF
CALL LOAD (KLUN, YD%YSTRDU)
NULLIFY (YD%STRDV)
READ (KLUN) LF_STRDV
IF (LF_STRDV) THEN
  CALL LOAD (KLUN, YD%F_STRDV)
ELSE
  NULLIFY (YD%F_STRDV)
ENDIF
CALL LOAD (KLUN, YD%YSTRDV)
NULLIFY (YD%STRTU)
READ (KLUN) LF_STRTU
IF (LF_STRTU) THEN
  CALL LOAD (KLUN, YD%F_STRTU)
ELSE
  NULLIFY (YD%F_STRTU)
ENDIF
CALL LOAD (KLUN, YD%YSTRTU)
NULLIFY (YD%STRTV)
READ (KLUN) LF_STRTV
IF (LF_STRTV) THEN
  CALL LOAD (KLUN, YD%F_STRTV)
ELSE
  NULLIFY (YD%F_STRTV)
ENDIF
CALL LOAD (KLUN, YD%YSTRTV)
NULLIFY (YD%WS)
READ (KLUN) LF_WS
IF (LF_WS) THEN
  CALL LOAD (KLUN, YD%F_WS)
ELSE
  NULLIFY (YD%F_WS)
ENDIF
CALL LOAD (KLUN, YD%YWS)
END SUBROUTINE


SUBROUTINE COPY_TCFU (YD, LDCREATED)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TCFU_KEYS_MOD, ONLY : TCFU_KEYS, COPY_TCFU_KEYS
IMPLICIT NONE
TYPE (TCFU), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
CLASS (TCFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_FCCQL, LF_FCCQN, LF_FCHSP, LF_FCL, LF_FCLL, LF_FCLN, LF_FCS, LF_FCSQL, LF_FCSQN, LF_FDICQ
LOGICAL :: LF_FDICS, LF_FDISH, LF_FDITQ, LF_FDITS, LF_FDUTP, LF_FEVL, LF_FEVN, LF_FEVV, LF_FGEL, LF_FGELS
LOGICAL :: LF_FLASH, LF_FLWSP, LF_FNEB, LF_FNEBT, LF_FONTE, LF_FPLCG, LF_FPLCH, LF_FPLCL, LF_FPLCN, LF_FPLSG
LOGICAL :: LF_FPLSH, LF_FPLSL, LF_FPLSN, LF_FRSDNI, LF_FRSGNI, LF_FRSO, LF_FRSOC0, LF_FRSOC1, LF_FRSODS, LF_FRSOLU
LOGICAL :: LF_FRSOPS, LF_FRSOPT, LF_FRTH, LF_FRTHC0, LF_FRTHC1, LF_FRTHDS, LF_FTOPH, LF_FTR, LF_NEBBAS, LF_NEBCON
LOGICAL :: LF_NEBHAU, LF_NEBMOY, LF_OZONT, LF_QICE, LF_QLI, LF_QTOT, LF_RUISL, LF_RUISP, LF_RUISS, LF_SNS
LOGICAL :: LF_SPRES, LF_STRCU, LF_STRCV, LF_STRDU, LF_STRDV, LF_STRTU, LF_STRTV, LF_WS

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
YLSUPER => YD
CALL COPY_TCFU_KEYS (YLSUPER, LDCREATED=.TRUE.)









LF_FCCQL = ASSOCIATED (YD%F_FCCQL)
IF (LF_FCCQL) THEN
  !$acc enter data create (YD%F_FCCQL)
  !$acc update device (YD%F_FCCQL)
  CALL COPY (YD%F_FCCQL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCCQL)
ENDIF

CALL COPY (YD%YFCCQL, LDCREATED=.TRUE.)

LF_FCCQN = ASSOCIATED (YD%F_FCCQN)
IF (LF_FCCQN) THEN
  !$acc enter data create (YD%F_FCCQN)
  !$acc update device (YD%F_FCCQN)
  CALL COPY (YD%F_FCCQN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCCQN)
ENDIF

CALL COPY (YD%YFCCQN, LDCREATED=.TRUE.)

LF_FCHSP = ASSOCIATED (YD%F_FCHSP)
IF (LF_FCHSP) THEN
  !$acc enter data create (YD%F_FCHSP)
  !$acc update device (YD%F_FCHSP)
  CALL COPY (YD%F_FCHSP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCHSP)
ENDIF

CALL COPY (YD%YFCHSP, LDCREATED=.TRUE.)

LF_FCL = ASSOCIATED (YD%F_FCL)
IF (LF_FCL) THEN
  !$acc enter data create (YD%F_FCL)
  !$acc update device (YD%F_FCL)
  CALL COPY (YD%F_FCL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCL)
ENDIF

CALL COPY (YD%YFCL, LDCREATED=.TRUE.)

LF_FCLL = ASSOCIATED (YD%F_FCLL)
IF (LF_FCLL) THEN
  !$acc enter data create (YD%F_FCLL)
  !$acc update device (YD%F_FCLL)
  CALL COPY (YD%F_FCLL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCLL)
ENDIF

CALL COPY (YD%YFCLL, LDCREATED=.TRUE.)

LF_FCLN = ASSOCIATED (YD%F_FCLN)
IF (LF_FCLN) THEN
  !$acc enter data create (YD%F_FCLN)
  !$acc update device (YD%F_FCLN)
  CALL COPY (YD%F_FCLN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCLN)
ENDIF

CALL COPY (YD%YFCLN, LDCREATED=.TRUE.)

LF_FCSQL = ASSOCIATED (YD%F_FCSQL)
IF (LF_FCSQL) THEN
  !$acc enter data create (YD%F_FCSQL)
  !$acc update device (YD%F_FCSQL)
  CALL COPY (YD%F_FCSQL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCSQL)
ENDIF

CALL COPY (YD%YFCSQL, LDCREATED=.TRUE.)

LF_FCSQN = ASSOCIATED (YD%F_FCSQN)
IF (LF_FCSQN) THEN
  !$acc enter data create (YD%F_FCSQN)
  !$acc update device (YD%F_FCSQN)
  CALL COPY (YD%F_FCSQN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCSQN)
ENDIF

CALL COPY (YD%YFCSQN, LDCREATED=.TRUE.)

LF_FCS = ASSOCIATED (YD%F_FCS)
IF (LF_FCS) THEN
  !$acc enter data create (YD%F_FCS)
  !$acc update device (YD%F_FCS)
  CALL COPY (YD%F_FCS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FCS)
ENDIF

CALL COPY (YD%YFCS, LDCREATED=.TRUE.)

LF_FDICQ = ASSOCIATED (YD%F_FDICQ)
IF (LF_FDICQ) THEN
  !$acc enter data create (YD%F_FDICQ)
  !$acc update device (YD%F_FDICQ)
  CALL COPY (YD%F_FDICQ, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FDICQ)
ENDIF

CALL COPY (YD%YFDICQ, LDCREATED=.TRUE.)

LF_FDICS = ASSOCIATED (YD%F_FDICS)
IF (LF_FDICS) THEN
  !$acc enter data create (YD%F_FDICS)
  !$acc update device (YD%F_FDICS)
  CALL COPY (YD%F_FDICS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FDICS)
ENDIF

CALL COPY (YD%YFDICS, LDCREATED=.TRUE.)

LF_FDISH = ASSOCIATED (YD%F_FDISH)
IF (LF_FDISH) THEN
  !$acc enter data create (YD%F_FDISH)
  !$acc update device (YD%F_FDISH)
  CALL COPY (YD%F_FDISH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FDISH)
ENDIF

CALL COPY (YD%YFDISH, LDCREATED=.TRUE.)

LF_FDITQ = ASSOCIATED (YD%F_FDITQ)
IF (LF_FDITQ) THEN
  !$acc enter data create (YD%F_FDITQ)
  !$acc update device (YD%F_FDITQ)
  CALL COPY (YD%F_FDITQ, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FDITQ)
ENDIF

CALL COPY (YD%YFDITQ, LDCREATED=.TRUE.)

LF_FDITS = ASSOCIATED (YD%F_FDITS)
IF (LF_FDITS) THEN
  !$acc enter data create (YD%F_FDITS)
  !$acc update device (YD%F_FDITS)
  CALL COPY (YD%F_FDITS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FDITS)
ENDIF

CALL COPY (YD%YFDITS, LDCREATED=.TRUE.)

LF_FDUTP = ASSOCIATED (YD%F_FDUTP)
IF (LF_FDUTP) THEN
  !$acc enter data create (YD%F_FDUTP)
  !$acc update device (YD%F_FDUTP)
  CALL COPY (YD%F_FDUTP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FDUTP)
ENDIF

CALL COPY (YD%YFDUTP, LDCREATED=.TRUE.)

LF_FEVL = ASSOCIATED (YD%F_FEVL)
IF (LF_FEVL) THEN
  !$acc enter data create (YD%F_FEVL)
  !$acc update device (YD%F_FEVL)
  CALL COPY (YD%F_FEVL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FEVL)
ENDIF

CALL COPY (YD%YFEVL, LDCREATED=.TRUE.)

LF_FEVN = ASSOCIATED (YD%F_FEVN)
IF (LF_FEVN) THEN
  !$acc enter data create (YD%F_FEVN)
  !$acc update device (YD%F_FEVN)
  CALL COPY (YD%F_FEVN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FEVN)
ENDIF

CALL COPY (YD%YFEVN, LDCREATED=.TRUE.)

LF_FEVV = ASSOCIATED (YD%F_FEVV)
IF (LF_FEVV) THEN
  !$acc enter data create (YD%F_FEVV)
  !$acc update device (YD%F_FEVV)
  CALL COPY (YD%F_FEVV, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FEVV)
ENDIF

CALL COPY (YD%YFEVV, LDCREATED=.TRUE.)

LF_FGEL = ASSOCIATED (YD%F_FGEL)
IF (LF_FGEL) THEN
  !$acc enter data create (YD%F_FGEL)
  !$acc update device (YD%F_FGEL)
  CALL COPY (YD%F_FGEL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FGEL)
ENDIF

CALL COPY (YD%YFGEL, LDCREATED=.TRUE.)

LF_FGELS = ASSOCIATED (YD%F_FGELS)
IF (LF_FGELS) THEN
  !$acc enter data create (YD%F_FGELS)
  !$acc update device (YD%F_FGELS)
  CALL COPY (YD%F_FGELS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FGELS)
ENDIF

CALL COPY (YD%YFGELS, LDCREATED=.TRUE.)

LF_FLASH = ASSOCIATED (YD%F_FLASH)
IF (LF_FLASH) THEN
  !$acc enter data create (YD%F_FLASH)
  !$acc update device (YD%F_FLASH)
  CALL COPY (YD%F_FLASH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FLASH)
ENDIF

CALL COPY (YD%YFLASH, LDCREATED=.TRUE.)

LF_FLWSP = ASSOCIATED (YD%F_FLWSP)
IF (LF_FLWSP) THEN
  !$acc enter data create (YD%F_FLWSP)
  !$acc update device (YD%F_FLWSP)
  CALL COPY (YD%F_FLWSP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FLWSP)
ENDIF

CALL COPY (YD%YFLWSP, LDCREATED=.TRUE.)

LF_FNEB = ASSOCIATED (YD%F_FNEB)
IF (LF_FNEB) THEN
  !$acc enter data create (YD%F_FNEB)
  !$acc update device (YD%F_FNEB)
  CALL COPY (YD%F_FNEB, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FNEB)
ENDIF

CALL COPY (YD%YFNEB, LDCREATED=.TRUE.)

LF_FNEBT = ASSOCIATED (YD%F_FNEBT)
IF (LF_FNEBT) THEN
  !$acc enter data create (YD%F_FNEBT)
  !$acc update device (YD%F_FNEBT)
  CALL COPY (YD%F_FNEBT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FNEBT)
ENDIF

CALL COPY (YD%YFNEBT, LDCREATED=.TRUE.)

LF_FONTE = ASSOCIATED (YD%F_FONTE)
IF (LF_FONTE) THEN
  !$acc enter data create (YD%F_FONTE)
  !$acc update device (YD%F_FONTE)
  CALL COPY (YD%F_FONTE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FONTE)
ENDIF

CALL COPY (YD%YFONTE, LDCREATED=.TRUE.)

LF_FPLCG = ASSOCIATED (YD%F_FPLCG)
IF (LF_FPLCG) THEN
  !$acc enter data create (YD%F_FPLCG)
  !$acc update device (YD%F_FPLCG)
  CALL COPY (YD%F_FPLCG, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLCG)
ENDIF

CALL COPY (YD%YFPLCG, LDCREATED=.TRUE.)

LF_FPLCH = ASSOCIATED (YD%F_FPLCH)
IF (LF_FPLCH) THEN
  !$acc enter data create (YD%F_FPLCH)
  !$acc update device (YD%F_FPLCH)
  CALL COPY (YD%F_FPLCH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLCH)
ENDIF

CALL COPY (YD%YFPLCH, LDCREATED=.TRUE.)

LF_FPLCL = ASSOCIATED (YD%F_FPLCL)
IF (LF_FPLCL) THEN
  !$acc enter data create (YD%F_FPLCL)
  !$acc update device (YD%F_FPLCL)
  CALL COPY (YD%F_FPLCL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLCL)
ENDIF

CALL COPY (YD%YFPLCL, LDCREATED=.TRUE.)

LF_FPLCN = ASSOCIATED (YD%F_FPLCN)
IF (LF_FPLCN) THEN
  !$acc enter data create (YD%F_FPLCN)
  !$acc update device (YD%F_FPLCN)
  CALL COPY (YD%F_FPLCN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLCN)
ENDIF

CALL COPY (YD%YFPLCN, LDCREATED=.TRUE.)

LF_FPLSG = ASSOCIATED (YD%F_FPLSG)
IF (LF_FPLSG) THEN
  !$acc enter data create (YD%F_FPLSG)
  !$acc update device (YD%F_FPLSG)
  CALL COPY (YD%F_FPLSG, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLSG)
ENDIF

CALL COPY (YD%YFPLSG, LDCREATED=.TRUE.)

LF_FPLSH = ASSOCIATED (YD%F_FPLSH)
IF (LF_FPLSH) THEN
  !$acc enter data create (YD%F_FPLSH)
  !$acc update device (YD%F_FPLSH)
  CALL COPY (YD%F_FPLSH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLSH)
ENDIF

CALL COPY (YD%YFPLSH, LDCREATED=.TRUE.)

LF_FPLSL = ASSOCIATED (YD%F_FPLSL)
IF (LF_FPLSL) THEN
  !$acc enter data create (YD%F_FPLSL)
  !$acc update device (YD%F_FPLSL)
  CALL COPY (YD%F_FPLSL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLSL)
ENDIF

CALL COPY (YD%YFPLSL, LDCREATED=.TRUE.)

LF_FPLSN = ASSOCIATED (YD%F_FPLSN)
IF (LF_FPLSN) THEN
  !$acc enter data create (YD%F_FPLSN)
  !$acc update device (YD%F_FPLSN)
  CALL COPY (YD%F_FPLSN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FPLSN)
ENDIF

CALL COPY (YD%YFPLSN, LDCREATED=.TRUE.)

LF_FRSDNI = ASSOCIATED (YD%F_FRSDNI)
IF (LF_FRSDNI) THEN
  !$acc enter data create (YD%F_FRSDNI)
  !$acc update device (YD%F_FRSDNI)
  CALL COPY (YD%F_FRSDNI, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSDNI)
ENDIF

CALL COPY (YD%YFRSDNI, LDCREATED=.TRUE.)

LF_FRSGNI = ASSOCIATED (YD%F_FRSGNI)
IF (LF_FRSGNI) THEN
  !$acc enter data create (YD%F_FRSGNI)
  !$acc update device (YD%F_FRSGNI)
  CALL COPY (YD%F_FRSGNI, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSGNI)
ENDIF

CALL COPY (YD%YFRSGNI, LDCREATED=.TRUE.)

LF_FRSOC0 = ASSOCIATED (YD%F_FRSOC0)
IF (LF_FRSOC0) THEN
  !$acc enter data create (YD%F_FRSOC0)
  !$acc update device (YD%F_FRSOC0)
  CALL COPY (YD%F_FRSOC0, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSOC0)
ENDIF

CALL COPY (YD%YFRSOC0, LDCREATED=.TRUE.)

LF_FRSOC1 = ASSOCIATED (YD%F_FRSOC1)
IF (LF_FRSOC1) THEN
  !$acc enter data create (YD%F_FRSOC1)
  !$acc update device (YD%F_FRSOC1)
  CALL COPY (YD%F_FRSOC1, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSOC1)
ENDIF

CALL COPY (YD%YFRSOC1, LDCREATED=.TRUE.)

LF_FRSODS = ASSOCIATED (YD%F_FRSODS)
IF (LF_FRSODS) THEN
  !$acc enter data create (YD%F_FRSODS)
  !$acc update device (YD%F_FRSODS)
  CALL COPY (YD%F_FRSODS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSODS)
ENDIF

CALL COPY (YD%YFRSODS, LDCREATED=.TRUE.)

LF_FRSOLU = ASSOCIATED (YD%F_FRSOLU)
IF (LF_FRSOLU) THEN
  !$acc enter data create (YD%F_FRSOLU)
  !$acc update device (YD%F_FRSOLU)
  CALL COPY (YD%F_FRSOLU, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSOLU)
ENDIF

CALL COPY (YD%YFRSOLU, LDCREATED=.TRUE.)

LF_FRSOPS = ASSOCIATED (YD%F_FRSOPS)
IF (LF_FRSOPS) THEN
  !$acc enter data create (YD%F_FRSOPS)
  !$acc update device (YD%F_FRSOPS)
  CALL COPY (YD%F_FRSOPS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSOPS)
ENDIF

CALL COPY (YD%YFRSOPS, LDCREATED=.TRUE.)

LF_FRSOPT = ASSOCIATED (YD%F_FRSOPT)
IF (LF_FRSOPT) THEN
  !$acc enter data create (YD%F_FRSOPT)
  !$acc update device (YD%F_FRSOPT)
  CALL COPY (YD%F_FRSOPT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSOPT)
ENDIF

CALL COPY (YD%YFRSOPT, LDCREATED=.TRUE.)

LF_FRSO = ASSOCIATED (YD%F_FRSO)
IF (LF_FRSO) THEN
  !$acc enter data create (YD%F_FRSO)
  !$acc update device (YD%F_FRSO)
  CALL COPY (YD%F_FRSO, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRSO)
ENDIF

CALL COPY (YD%YFRSO, LDCREATED=.TRUE.)

LF_FRTHC0 = ASSOCIATED (YD%F_FRTHC0)
IF (LF_FRTHC0) THEN
  !$acc enter data create (YD%F_FRTHC0)
  !$acc update device (YD%F_FRTHC0)
  CALL COPY (YD%F_FRTHC0, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRTHC0)
ENDIF

CALL COPY (YD%YFRTHC0, LDCREATED=.TRUE.)

LF_FRTHC1 = ASSOCIATED (YD%F_FRTHC1)
IF (LF_FRTHC1) THEN
  !$acc enter data create (YD%F_FRTHC1)
  !$acc update device (YD%F_FRTHC1)
  CALL COPY (YD%F_FRTHC1, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRTHC1)
ENDIF

CALL COPY (YD%YFRTHC1, LDCREATED=.TRUE.)

LF_FRTHDS = ASSOCIATED (YD%F_FRTHDS)
IF (LF_FRTHDS) THEN
  !$acc enter data create (YD%F_FRTHDS)
  !$acc update device (YD%F_FRTHDS)
  CALL COPY (YD%F_FRTHDS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRTHDS)
ENDIF

CALL COPY (YD%YFRTHDS, LDCREATED=.TRUE.)

LF_FRTH = ASSOCIATED (YD%F_FRTH)
IF (LF_FRTH) THEN
  !$acc enter data create (YD%F_FRTH)
  !$acc update device (YD%F_FRTH)
  CALL COPY (YD%F_FRTH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FRTH)
ENDIF

CALL COPY (YD%YFRTH, LDCREATED=.TRUE.)

LF_FTOPH = ASSOCIATED (YD%F_FTOPH)
IF (LF_FTOPH) THEN
  !$acc enter data create (YD%F_FTOPH)
  !$acc update device (YD%F_FTOPH)
  CALL COPY (YD%F_FTOPH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FTOPH)
ENDIF

CALL COPY (YD%YFTOPH, LDCREATED=.TRUE.)

LF_FTR = ASSOCIATED (YD%F_FTR)
IF (LF_FTR) THEN
  !$acc enter data create (YD%F_FTR)
  !$acc update device (YD%F_FTR)
  CALL COPY (YD%F_FTR, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FTR)
ENDIF

CALL COPY (YD%YFTR, LDCREATED=.TRUE.)

LF_NEBBAS = ASSOCIATED (YD%F_NEBBAS)
IF (LF_NEBBAS) THEN
  !$acc enter data create (YD%F_NEBBAS)
  !$acc update device (YD%F_NEBBAS)
  CALL COPY (YD%F_NEBBAS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NEBBAS)
ENDIF

CALL COPY (YD%YNEBBAS, LDCREATED=.TRUE.)

LF_NEBCON = ASSOCIATED (YD%F_NEBCON)
IF (LF_NEBCON) THEN
  !$acc enter data create (YD%F_NEBCON)
  !$acc update device (YD%F_NEBCON)
  CALL COPY (YD%F_NEBCON, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NEBCON)
ENDIF

CALL COPY (YD%YNEBCON, LDCREATED=.TRUE.)

LF_NEBHAU = ASSOCIATED (YD%F_NEBHAU)
IF (LF_NEBHAU) THEN
  !$acc enter data create (YD%F_NEBHAU)
  !$acc update device (YD%F_NEBHAU)
  CALL COPY (YD%F_NEBHAU, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NEBHAU)
ENDIF

CALL COPY (YD%YNEBHAU, LDCREATED=.TRUE.)

LF_NEBMOY = ASSOCIATED (YD%F_NEBMOY)
IF (LF_NEBMOY) THEN
  !$acc enter data create (YD%F_NEBMOY)
  !$acc update device (YD%F_NEBMOY)
  CALL COPY (YD%F_NEBMOY, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NEBMOY)
ENDIF

CALL COPY (YD%YNEBMOY, LDCREATED=.TRUE.)

LF_OZONT = ASSOCIATED (YD%F_OZONT)
IF (LF_OZONT) THEN
  !$acc enter data create (YD%F_OZONT)
  !$acc update device (YD%F_OZONT)
  CALL COPY (YD%F_OZONT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_OZONT)
ENDIF

CALL COPY (YD%YOZONT, LDCREATED=.TRUE.)

LF_QICE = ASSOCIATED (YD%F_QICE)
IF (LF_QICE) THEN
  !$acc enter data create (YD%F_QICE)
  !$acc update device (YD%F_QICE)
  CALL COPY (YD%F_QICE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QICE)
ENDIF

CALL COPY (YD%YQICE, LDCREATED=.TRUE.)

LF_QLI = ASSOCIATED (YD%F_QLI)
IF (LF_QLI) THEN
  !$acc enter data create (YD%F_QLI)
  !$acc update device (YD%F_QLI)
  CALL COPY (YD%F_QLI, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QLI)
ENDIF

CALL COPY (YD%YQLI, LDCREATED=.TRUE.)

LF_QTOT = ASSOCIATED (YD%F_QTOT)
IF (LF_QTOT) THEN
  !$acc enter data create (YD%F_QTOT)
  !$acc update device (YD%F_QTOT)
  CALL COPY (YD%F_QTOT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QTOT)
ENDIF

CALL COPY (YD%YQTOT, LDCREATED=.TRUE.)

LF_RUISL = ASSOCIATED (YD%F_RUISL)
IF (LF_RUISL) THEN
  !$acc enter data create (YD%F_RUISL)
  !$acc update device (YD%F_RUISL)
  CALL COPY (YD%F_RUISL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RUISL)
ENDIF

CALL COPY (YD%YRUISL, LDCREATED=.TRUE.)

LF_RUISP = ASSOCIATED (YD%F_RUISP)
IF (LF_RUISP) THEN
  !$acc enter data create (YD%F_RUISP)
  !$acc update device (YD%F_RUISP)
  CALL COPY (YD%F_RUISP, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RUISP)
ENDIF

CALL COPY (YD%YRUISP, LDCREATED=.TRUE.)

LF_RUISS = ASSOCIATED (YD%F_RUISS)
IF (LF_RUISS) THEN
  !$acc enter data create (YD%F_RUISS)
  !$acc update device (YD%F_RUISS)
  CALL COPY (YD%F_RUISS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RUISS)
ENDIF

CALL COPY (YD%YRUISS, LDCREATED=.TRUE.)

LF_SNS = ASSOCIATED (YD%F_SNS)
IF (LF_SNS) THEN
  !$acc enter data create (YD%F_SNS)
  !$acc update device (YD%F_SNS)
  CALL COPY (YD%F_SNS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_SNS)
ENDIF

CALL COPY (YD%YSNS, LDCREATED=.TRUE.)

LF_SPRES = ASSOCIATED (YD%F_SPRES)
IF (LF_SPRES) THEN
  !$acc enter data create (YD%F_SPRES)
  !$acc update device (YD%F_SPRES)
  CALL COPY (YD%F_SPRES, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_SPRES)
ENDIF

CALL COPY (YD%YSPRES, LDCREATED=.TRUE.)

LF_STRCU = ASSOCIATED (YD%F_STRCU)
IF (LF_STRCU) THEN
  !$acc enter data create (YD%F_STRCU)
  !$acc update device (YD%F_STRCU)
  CALL COPY (YD%F_STRCU, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_STRCU)
ENDIF

CALL COPY (YD%YSTRCU, LDCREATED=.TRUE.)

LF_STRCV = ASSOCIATED (YD%F_STRCV)
IF (LF_STRCV) THEN
  !$acc enter data create (YD%F_STRCV)
  !$acc update device (YD%F_STRCV)
  CALL COPY (YD%F_STRCV, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_STRCV)
ENDIF

CALL COPY (YD%YSTRCV, LDCREATED=.TRUE.)

LF_STRDU = ASSOCIATED (YD%F_STRDU)
IF (LF_STRDU) THEN
  !$acc enter data create (YD%F_STRDU)
  !$acc update device (YD%F_STRDU)
  CALL COPY (YD%F_STRDU, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_STRDU)
ENDIF

CALL COPY (YD%YSTRDU, LDCREATED=.TRUE.)

LF_STRDV = ASSOCIATED (YD%F_STRDV)
IF (LF_STRDV) THEN
  !$acc enter data create (YD%F_STRDV)
  !$acc update device (YD%F_STRDV)
  CALL COPY (YD%F_STRDV, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_STRDV)
ENDIF

CALL COPY (YD%YSTRDV, LDCREATED=.TRUE.)

LF_STRTU = ASSOCIATED (YD%F_STRTU)
IF (LF_STRTU) THEN
  !$acc enter data create (YD%F_STRTU)
  !$acc update device (YD%F_STRTU)
  CALL COPY (YD%F_STRTU, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_STRTU)
ENDIF

CALL COPY (YD%YSTRTU, LDCREATED=.TRUE.)

LF_STRTV = ASSOCIATED (YD%F_STRTV)
IF (LF_STRTV) THEN
  !$acc enter data create (YD%F_STRTV)
  !$acc update device (YD%F_STRTV)
  CALL COPY (YD%F_STRTV, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_STRTV)
ENDIF

CALL COPY (YD%YSTRTV, LDCREATED=.TRUE.)

LF_WS = ASSOCIATED (YD%F_WS)
IF (LF_WS) THEN
  !$acc enter data create (YD%F_WS)
  !$acc update device (YD%F_WS)
  CALL COPY (YD%F_WS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_WS)
ENDIF

CALL COPY (YD%YWS, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_TCFU (YD, LDDELETED)
USE UTIL_FIELD_MOD
USE UTIL_FLUXES_DESCRIPTOR_MOD
USE UTIL_TCFU_KEYS_MOD, ONLY : TCFU_KEYS, WIPE_TCFU_KEYS
IMPLICIT NONE
TYPE (TCFU), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
CLASS (TCFU_KEYS), POINTER :: YLSUPER
LOGICAL :: LF_FCCQL, LF_FCCQN, LF_FCHSP, LF_FCL, LF_FCLL, LF_FCLN, LF_FCS, LF_FCSQL, LF_FCSQN, LF_FDICQ
LOGICAL :: LF_FDICS, LF_FDISH, LF_FDITQ, LF_FDITS, LF_FDUTP, LF_FEVL, LF_FEVN, LF_FEVV, LF_FGEL, LF_FGELS
LOGICAL :: LF_FLASH, LF_FLWSP, LF_FNEB, LF_FNEBT, LF_FONTE, LF_FPLCG, LF_FPLCH, LF_FPLCL, LF_FPLCN, LF_FPLSG
LOGICAL :: LF_FPLSH, LF_FPLSL, LF_FPLSN, LF_FRSDNI, LF_FRSGNI, LF_FRSO, LF_FRSOC0, LF_FRSOC1, LF_FRSODS, LF_FRSOLU
LOGICAL :: LF_FRSOPS, LF_FRSOPT, LF_FRTH, LF_FRTHC0, LF_FRTHC1, LF_FRTHDS, LF_FTOPH, LF_FTR, LF_NEBBAS, LF_NEBCON
LOGICAL :: LF_NEBHAU, LF_NEBMOY, LF_OZONT, LF_QICE, LF_QLI, LF_QTOT, LF_RUISL, LF_RUISP, LF_RUISS, LF_SNS
LOGICAL :: LF_SPRES, LF_STRCU, LF_STRCV, LF_STRDU, LF_STRDV, LF_STRTU, LF_STRTV, LF_WS

YLSUPER => YD
CALL WIPE_TCFU_KEYS (YLSUPER, LDDELETED=.TRUE.)









LF_FCCQL = ASSOCIATED (YD%F_FCCQL)
IF (LF_FCCQL) THEN
  !$acc exit data detach (YD%F_FCCQL)
  CALL WIPE (YD%F_FCCQL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCCQL)
ENDIF

CALL WIPE (YD%YFCCQL, LDDELETED=.TRUE.)

LF_FCCQN = ASSOCIATED (YD%F_FCCQN)
IF (LF_FCCQN) THEN
  !$acc exit data detach (YD%F_FCCQN)
  CALL WIPE (YD%F_FCCQN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCCQN)
ENDIF

CALL WIPE (YD%YFCCQN, LDDELETED=.TRUE.)

LF_FCHSP = ASSOCIATED (YD%F_FCHSP)
IF (LF_FCHSP) THEN
  !$acc exit data detach (YD%F_FCHSP)
  CALL WIPE (YD%F_FCHSP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCHSP)
ENDIF

CALL WIPE (YD%YFCHSP, LDDELETED=.TRUE.)

LF_FCL = ASSOCIATED (YD%F_FCL)
IF (LF_FCL) THEN
  !$acc exit data detach (YD%F_FCL)
  CALL WIPE (YD%F_FCL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCL)
ENDIF

CALL WIPE (YD%YFCL, LDDELETED=.TRUE.)

LF_FCLL = ASSOCIATED (YD%F_FCLL)
IF (LF_FCLL) THEN
  !$acc exit data detach (YD%F_FCLL)
  CALL WIPE (YD%F_FCLL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCLL)
ENDIF

CALL WIPE (YD%YFCLL, LDDELETED=.TRUE.)

LF_FCLN = ASSOCIATED (YD%F_FCLN)
IF (LF_FCLN) THEN
  !$acc exit data detach (YD%F_FCLN)
  CALL WIPE (YD%F_FCLN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCLN)
ENDIF

CALL WIPE (YD%YFCLN, LDDELETED=.TRUE.)

LF_FCSQL = ASSOCIATED (YD%F_FCSQL)
IF (LF_FCSQL) THEN
  !$acc exit data detach (YD%F_FCSQL)
  CALL WIPE (YD%F_FCSQL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCSQL)
ENDIF

CALL WIPE (YD%YFCSQL, LDDELETED=.TRUE.)

LF_FCSQN = ASSOCIATED (YD%F_FCSQN)
IF (LF_FCSQN) THEN
  !$acc exit data detach (YD%F_FCSQN)
  CALL WIPE (YD%F_FCSQN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCSQN)
ENDIF

CALL WIPE (YD%YFCSQN, LDDELETED=.TRUE.)

LF_FCS = ASSOCIATED (YD%F_FCS)
IF (LF_FCS) THEN
  !$acc exit data detach (YD%F_FCS)
  CALL WIPE (YD%F_FCS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FCS)
ENDIF

CALL WIPE (YD%YFCS, LDDELETED=.TRUE.)

LF_FDICQ = ASSOCIATED (YD%F_FDICQ)
IF (LF_FDICQ) THEN
  !$acc exit data detach (YD%F_FDICQ)
  CALL WIPE (YD%F_FDICQ, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FDICQ)
ENDIF

CALL WIPE (YD%YFDICQ, LDDELETED=.TRUE.)

LF_FDICS = ASSOCIATED (YD%F_FDICS)
IF (LF_FDICS) THEN
  !$acc exit data detach (YD%F_FDICS)
  CALL WIPE (YD%F_FDICS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FDICS)
ENDIF

CALL WIPE (YD%YFDICS, LDDELETED=.TRUE.)

LF_FDISH = ASSOCIATED (YD%F_FDISH)
IF (LF_FDISH) THEN
  !$acc exit data detach (YD%F_FDISH)
  CALL WIPE (YD%F_FDISH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FDISH)
ENDIF

CALL WIPE (YD%YFDISH, LDDELETED=.TRUE.)

LF_FDITQ = ASSOCIATED (YD%F_FDITQ)
IF (LF_FDITQ) THEN
  !$acc exit data detach (YD%F_FDITQ)
  CALL WIPE (YD%F_FDITQ, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FDITQ)
ENDIF

CALL WIPE (YD%YFDITQ, LDDELETED=.TRUE.)

LF_FDITS = ASSOCIATED (YD%F_FDITS)
IF (LF_FDITS) THEN
  !$acc exit data detach (YD%F_FDITS)
  CALL WIPE (YD%F_FDITS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FDITS)
ENDIF

CALL WIPE (YD%YFDITS, LDDELETED=.TRUE.)

LF_FDUTP = ASSOCIATED (YD%F_FDUTP)
IF (LF_FDUTP) THEN
  !$acc exit data detach (YD%F_FDUTP)
  CALL WIPE (YD%F_FDUTP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FDUTP)
ENDIF

CALL WIPE (YD%YFDUTP, LDDELETED=.TRUE.)

LF_FEVL = ASSOCIATED (YD%F_FEVL)
IF (LF_FEVL) THEN
  !$acc exit data detach (YD%F_FEVL)
  CALL WIPE (YD%F_FEVL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FEVL)
ENDIF

CALL WIPE (YD%YFEVL, LDDELETED=.TRUE.)

LF_FEVN = ASSOCIATED (YD%F_FEVN)
IF (LF_FEVN) THEN
  !$acc exit data detach (YD%F_FEVN)
  CALL WIPE (YD%F_FEVN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FEVN)
ENDIF

CALL WIPE (YD%YFEVN, LDDELETED=.TRUE.)

LF_FEVV = ASSOCIATED (YD%F_FEVV)
IF (LF_FEVV) THEN
  !$acc exit data detach (YD%F_FEVV)
  CALL WIPE (YD%F_FEVV, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FEVV)
ENDIF

CALL WIPE (YD%YFEVV, LDDELETED=.TRUE.)

LF_FGEL = ASSOCIATED (YD%F_FGEL)
IF (LF_FGEL) THEN
  !$acc exit data detach (YD%F_FGEL)
  CALL WIPE (YD%F_FGEL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FGEL)
ENDIF

CALL WIPE (YD%YFGEL, LDDELETED=.TRUE.)

LF_FGELS = ASSOCIATED (YD%F_FGELS)
IF (LF_FGELS) THEN
  !$acc exit data detach (YD%F_FGELS)
  CALL WIPE (YD%F_FGELS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FGELS)
ENDIF

CALL WIPE (YD%YFGELS, LDDELETED=.TRUE.)

LF_FLASH = ASSOCIATED (YD%F_FLASH)
IF (LF_FLASH) THEN
  !$acc exit data detach (YD%F_FLASH)
  CALL WIPE (YD%F_FLASH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FLASH)
ENDIF

CALL WIPE (YD%YFLASH, LDDELETED=.TRUE.)

LF_FLWSP = ASSOCIATED (YD%F_FLWSP)
IF (LF_FLWSP) THEN
  !$acc exit data detach (YD%F_FLWSP)
  CALL WIPE (YD%F_FLWSP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FLWSP)
ENDIF

CALL WIPE (YD%YFLWSP, LDDELETED=.TRUE.)

LF_FNEB = ASSOCIATED (YD%F_FNEB)
IF (LF_FNEB) THEN
  !$acc exit data detach (YD%F_FNEB)
  CALL WIPE (YD%F_FNEB, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FNEB)
ENDIF

CALL WIPE (YD%YFNEB, LDDELETED=.TRUE.)

LF_FNEBT = ASSOCIATED (YD%F_FNEBT)
IF (LF_FNEBT) THEN
  !$acc exit data detach (YD%F_FNEBT)
  CALL WIPE (YD%F_FNEBT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FNEBT)
ENDIF

CALL WIPE (YD%YFNEBT, LDDELETED=.TRUE.)

LF_FONTE = ASSOCIATED (YD%F_FONTE)
IF (LF_FONTE) THEN
  !$acc exit data detach (YD%F_FONTE)
  CALL WIPE (YD%F_FONTE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FONTE)
ENDIF

CALL WIPE (YD%YFONTE, LDDELETED=.TRUE.)

LF_FPLCG = ASSOCIATED (YD%F_FPLCG)
IF (LF_FPLCG) THEN
  !$acc exit data detach (YD%F_FPLCG)
  CALL WIPE (YD%F_FPLCG, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLCG)
ENDIF

CALL WIPE (YD%YFPLCG, LDDELETED=.TRUE.)

LF_FPLCH = ASSOCIATED (YD%F_FPLCH)
IF (LF_FPLCH) THEN
  !$acc exit data detach (YD%F_FPLCH)
  CALL WIPE (YD%F_FPLCH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLCH)
ENDIF

CALL WIPE (YD%YFPLCH, LDDELETED=.TRUE.)

LF_FPLCL = ASSOCIATED (YD%F_FPLCL)
IF (LF_FPLCL) THEN
  !$acc exit data detach (YD%F_FPLCL)
  CALL WIPE (YD%F_FPLCL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLCL)
ENDIF

CALL WIPE (YD%YFPLCL, LDDELETED=.TRUE.)

LF_FPLCN = ASSOCIATED (YD%F_FPLCN)
IF (LF_FPLCN) THEN
  !$acc exit data detach (YD%F_FPLCN)
  CALL WIPE (YD%F_FPLCN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLCN)
ENDIF

CALL WIPE (YD%YFPLCN, LDDELETED=.TRUE.)

LF_FPLSG = ASSOCIATED (YD%F_FPLSG)
IF (LF_FPLSG) THEN
  !$acc exit data detach (YD%F_FPLSG)
  CALL WIPE (YD%F_FPLSG, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLSG)
ENDIF

CALL WIPE (YD%YFPLSG, LDDELETED=.TRUE.)

LF_FPLSH = ASSOCIATED (YD%F_FPLSH)
IF (LF_FPLSH) THEN
  !$acc exit data detach (YD%F_FPLSH)
  CALL WIPE (YD%F_FPLSH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLSH)
ENDIF

CALL WIPE (YD%YFPLSH, LDDELETED=.TRUE.)

LF_FPLSL = ASSOCIATED (YD%F_FPLSL)
IF (LF_FPLSL) THEN
  !$acc exit data detach (YD%F_FPLSL)
  CALL WIPE (YD%F_FPLSL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLSL)
ENDIF

CALL WIPE (YD%YFPLSL, LDDELETED=.TRUE.)

LF_FPLSN = ASSOCIATED (YD%F_FPLSN)
IF (LF_FPLSN) THEN
  !$acc exit data detach (YD%F_FPLSN)
  CALL WIPE (YD%F_FPLSN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FPLSN)
ENDIF

CALL WIPE (YD%YFPLSN, LDDELETED=.TRUE.)

LF_FRSDNI = ASSOCIATED (YD%F_FRSDNI)
IF (LF_FRSDNI) THEN
  !$acc exit data detach (YD%F_FRSDNI)
  CALL WIPE (YD%F_FRSDNI, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSDNI)
ENDIF

CALL WIPE (YD%YFRSDNI, LDDELETED=.TRUE.)

LF_FRSGNI = ASSOCIATED (YD%F_FRSGNI)
IF (LF_FRSGNI) THEN
  !$acc exit data detach (YD%F_FRSGNI)
  CALL WIPE (YD%F_FRSGNI, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSGNI)
ENDIF

CALL WIPE (YD%YFRSGNI, LDDELETED=.TRUE.)

LF_FRSOC0 = ASSOCIATED (YD%F_FRSOC0)
IF (LF_FRSOC0) THEN
  !$acc exit data detach (YD%F_FRSOC0)
  CALL WIPE (YD%F_FRSOC0, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSOC0)
ENDIF

CALL WIPE (YD%YFRSOC0, LDDELETED=.TRUE.)

LF_FRSOC1 = ASSOCIATED (YD%F_FRSOC1)
IF (LF_FRSOC1) THEN
  !$acc exit data detach (YD%F_FRSOC1)
  CALL WIPE (YD%F_FRSOC1, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSOC1)
ENDIF

CALL WIPE (YD%YFRSOC1, LDDELETED=.TRUE.)

LF_FRSODS = ASSOCIATED (YD%F_FRSODS)
IF (LF_FRSODS) THEN
  !$acc exit data detach (YD%F_FRSODS)
  CALL WIPE (YD%F_FRSODS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSODS)
ENDIF

CALL WIPE (YD%YFRSODS, LDDELETED=.TRUE.)

LF_FRSOLU = ASSOCIATED (YD%F_FRSOLU)
IF (LF_FRSOLU) THEN
  !$acc exit data detach (YD%F_FRSOLU)
  CALL WIPE (YD%F_FRSOLU, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSOLU)
ENDIF

CALL WIPE (YD%YFRSOLU, LDDELETED=.TRUE.)

LF_FRSOPS = ASSOCIATED (YD%F_FRSOPS)
IF (LF_FRSOPS) THEN
  !$acc exit data detach (YD%F_FRSOPS)
  CALL WIPE (YD%F_FRSOPS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSOPS)
ENDIF

CALL WIPE (YD%YFRSOPS, LDDELETED=.TRUE.)

LF_FRSOPT = ASSOCIATED (YD%F_FRSOPT)
IF (LF_FRSOPT) THEN
  !$acc exit data detach (YD%F_FRSOPT)
  CALL WIPE (YD%F_FRSOPT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSOPT)
ENDIF

CALL WIPE (YD%YFRSOPT, LDDELETED=.TRUE.)

LF_FRSO = ASSOCIATED (YD%F_FRSO)
IF (LF_FRSO) THEN
  !$acc exit data detach (YD%F_FRSO)
  CALL WIPE (YD%F_FRSO, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRSO)
ENDIF

CALL WIPE (YD%YFRSO, LDDELETED=.TRUE.)

LF_FRTHC0 = ASSOCIATED (YD%F_FRTHC0)
IF (LF_FRTHC0) THEN
  !$acc exit data detach (YD%F_FRTHC0)
  CALL WIPE (YD%F_FRTHC0, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRTHC0)
ENDIF

CALL WIPE (YD%YFRTHC0, LDDELETED=.TRUE.)

LF_FRTHC1 = ASSOCIATED (YD%F_FRTHC1)
IF (LF_FRTHC1) THEN
  !$acc exit data detach (YD%F_FRTHC1)
  CALL WIPE (YD%F_FRTHC1, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRTHC1)
ENDIF

CALL WIPE (YD%YFRTHC1, LDDELETED=.TRUE.)

LF_FRTHDS = ASSOCIATED (YD%F_FRTHDS)
IF (LF_FRTHDS) THEN
  !$acc exit data detach (YD%F_FRTHDS)
  CALL WIPE (YD%F_FRTHDS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRTHDS)
ENDIF

CALL WIPE (YD%YFRTHDS, LDDELETED=.TRUE.)

LF_FRTH = ASSOCIATED (YD%F_FRTH)
IF (LF_FRTH) THEN
  !$acc exit data detach (YD%F_FRTH)
  CALL WIPE (YD%F_FRTH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FRTH)
ENDIF

CALL WIPE (YD%YFRTH, LDDELETED=.TRUE.)

LF_FTOPH = ASSOCIATED (YD%F_FTOPH)
IF (LF_FTOPH) THEN
  !$acc exit data detach (YD%F_FTOPH)
  CALL WIPE (YD%F_FTOPH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FTOPH)
ENDIF

CALL WIPE (YD%YFTOPH, LDDELETED=.TRUE.)

LF_FTR = ASSOCIATED (YD%F_FTR)
IF (LF_FTR) THEN
  !$acc exit data detach (YD%F_FTR)
  CALL WIPE (YD%F_FTR, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FTR)
ENDIF

CALL WIPE (YD%YFTR, LDDELETED=.TRUE.)

LF_NEBBAS = ASSOCIATED (YD%F_NEBBAS)
IF (LF_NEBBAS) THEN
  !$acc exit data detach (YD%F_NEBBAS)
  CALL WIPE (YD%F_NEBBAS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NEBBAS)
ENDIF

CALL WIPE (YD%YNEBBAS, LDDELETED=.TRUE.)

LF_NEBCON = ASSOCIATED (YD%F_NEBCON)
IF (LF_NEBCON) THEN
  !$acc exit data detach (YD%F_NEBCON)
  CALL WIPE (YD%F_NEBCON, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NEBCON)
ENDIF

CALL WIPE (YD%YNEBCON, LDDELETED=.TRUE.)

LF_NEBHAU = ASSOCIATED (YD%F_NEBHAU)
IF (LF_NEBHAU) THEN
  !$acc exit data detach (YD%F_NEBHAU)
  CALL WIPE (YD%F_NEBHAU, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NEBHAU)
ENDIF

CALL WIPE (YD%YNEBHAU, LDDELETED=.TRUE.)

LF_NEBMOY = ASSOCIATED (YD%F_NEBMOY)
IF (LF_NEBMOY) THEN
  !$acc exit data detach (YD%F_NEBMOY)
  CALL WIPE (YD%F_NEBMOY, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NEBMOY)
ENDIF

CALL WIPE (YD%YNEBMOY, LDDELETED=.TRUE.)

LF_OZONT = ASSOCIATED (YD%F_OZONT)
IF (LF_OZONT) THEN
  !$acc exit data detach (YD%F_OZONT)
  CALL WIPE (YD%F_OZONT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_OZONT)
ENDIF

CALL WIPE (YD%YOZONT, LDDELETED=.TRUE.)

LF_QICE = ASSOCIATED (YD%F_QICE)
IF (LF_QICE) THEN
  !$acc exit data detach (YD%F_QICE)
  CALL WIPE (YD%F_QICE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QICE)
ENDIF

CALL WIPE (YD%YQICE, LDDELETED=.TRUE.)

LF_QLI = ASSOCIATED (YD%F_QLI)
IF (LF_QLI) THEN
  !$acc exit data detach (YD%F_QLI)
  CALL WIPE (YD%F_QLI, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QLI)
ENDIF

CALL WIPE (YD%YQLI, LDDELETED=.TRUE.)

LF_QTOT = ASSOCIATED (YD%F_QTOT)
IF (LF_QTOT) THEN
  !$acc exit data detach (YD%F_QTOT)
  CALL WIPE (YD%F_QTOT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QTOT)
ENDIF

CALL WIPE (YD%YQTOT, LDDELETED=.TRUE.)

LF_RUISL = ASSOCIATED (YD%F_RUISL)
IF (LF_RUISL) THEN
  !$acc exit data detach (YD%F_RUISL)
  CALL WIPE (YD%F_RUISL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RUISL)
ENDIF

CALL WIPE (YD%YRUISL, LDDELETED=.TRUE.)

LF_RUISP = ASSOCIATED (YD%F_RUISP)
IF (LF_RUISP) THEN
  !$acc exit data detach (YD%F_RUISP)
  CALL WIPE (YD%F_RUISP, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RUISP)
ENDIF

CALL WIPE (YD%YRUISP, LDDELETED=.TRUE.)

LF_RUISS = ASSOCIATED (YD%F_RUISS)
IF (LF_RUISS) THEN
  !$acc exit data detach (YD%F_RUISS)
  CALL WIPE (YD%F_RUISS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RUISS)
ENDIF

CALL WIPE (YD%YRUISS, LDDELETED=.TRUE.)

LF_SNS = ASSOCIATED (YD%F_SNS)
IF (LF_SNS) THEN
  !$acc exit data detach (YD%F_SNS)
  CALL WIPE (YD%F_SNS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_SNS)
ENDIF

CALL WIPE (YD%YSNS, LDDELETED=.TRUE.)

LF_SPRES = ASSOCIATED (YD%F_SPRES)
IF (LF_SPRES) THEN
  !$acc exit data detach (YD%F_SPRES)
  CALL WIPE (YD%F_SPRES, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_SPRES)
ENDIF

CALL WIPE (YD%YSPRES, LDDELETED=.TRUE.)

LF_STRCU = ASSOCIATED (YD%F_STRCU)
IF (LF_STRCU) THEN
  !$acc exit data detach (YD%F_STRCU)
  CALL WIPE (YD%F_STRCU, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_STRCU)
ENDIF

CALL WIPE (YD%YSTRCU, LDDELETED=.TRUE.)

LF_STRCV = ASSOCIATED (YD%F_STRCV)
IF (LF_STRCV) THEN
  !$acc exit data detach (YD%F_STRCV)
  CALL WIPE (YD%F_STRCV, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_STRCV)
ENDIF

CALL WIPE (YD%YSTRCV, LDDELETED=.TRUE.)

LF_STRDU = ASSOCIATED (YD%F_STRDU)
IF (LF_STRDU) THEN
  !$acc exit data detach (YD%F_STRDU)
  CALL WIPE (YD%F_STRDU, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_STRDU)
ENDIF

CALL WIPE (YD%YSTRDU, LDDELETED=.TRUE.)

LF_STRDV = ASSOCIATED (YD%F_STRDV)
IF (LF_STRDV) THEN
  !$acc exit data detach (YD%F_STRDV)
  CALL WIPE (YD%F_STRDV, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_STRDV)
ENDIF

CALL WIPE (YD%YSTRDV, LDDELETED=.TRUE.)

LF_STRTU = ASSOCIATED (YD%F_STRTU)
IF (LF_STRTU) THEN
  !$acc exit data detach (YD%F_STRTU)
  CALL WIPE (YD%F_STRTU, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_STRTU)
ENDIF

CALL WIPE (YD%YSTRTU, LDDELETED=.TRUE.)

LF_STRTV = ASSOCIATED (YD%F_STRTV)
IF (LF_STRTV) THEN
  !$acc exit data detach (YD%F_STRTV)
  CALL WIPE (YD%F_STRTV, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_STRTV)
ENDIF

CALL WIPE (YD%YSTRTV, LDDELETED=.TRUE.)

LF_WS = ASSOCIATED (YD%F_WS)
IF (LF_WS) THEN
  !$acc exit data detach (YD%F_WS)
  CALL WIPE (YD%F_WS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_WS)
ENDIF

CALL WIPE (YD%YWS, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
