MODULE UTIL_TMP_MOD

USE YOMMP, ONLY : TMP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TMP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMP
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMP), INTENT (IN), TARGET :: YD
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
LNUMPP = ALLOCATED (YD%NUMPP)
WRITE (KLUN) LNUMPP
IF (LNUMPP) THEN
  WRITE (KLUN) LBOUND (YD%NUMPP)
  WRITE (KLUN) UBOUND (YD%NUMPP)
  WRITE (KLUN) YD%NUMPP
ENDIF
LNPROCM = ALLOCATED (YD%NPROCM)
WRITE (KLUN) LNPROCM
IF (LNPROCM) THEN
  WRITE (KLUN) LBOUND (YD%NPROCM)
  WRITE (KLUN) UBOUND (YD%NPROCM)
  WRITE (KLUN) YD%NPROCM
ENDIF
LNPTRMS = ALLOCATED (YD%NPTRMS)
WRITE (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  WRITE (KLUN) LBOUND (YD%NPTRMS)
  WRITE (KLUN) UBOUND (YD%NPTRMS)
  WRITE (KLUN) YD%NPTRMS
ENDIF
LNALLMS = ALLOCATED (YD%NALLMS)
WRITE (KLUN) LNALLMS
IF (LNALLMS) THEN
  WRITE (KLUN) LBOUND (YD%NALLMS)
  WRITE (KLUN) UBOUND (YD%NALLMS)
  WRITE (KLUN) YD%NALLMS
ENDIF
LNPTRLS = ALLOCATED (YD%NPTRLS)
WRITE (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLS)
  WRITE (KLUN) UBOUND (YD%NPTRLS)
  WRITE (KLUN) YD%NPTRLS
ENDIF
LNPTRSV = ALLOCATED (YD%NPTRSV)
WRITE (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  WRITE (KLUN) LBOUND (YD%NPTRSV)
  WRITE (KLUN) UBOUND (YD%NPTRSV)
  WRITE (KLUN) YD%NPTRSV
ENDIF
LNPTRSVF = ALLOCATED (YD%NPTRSVF)
WRITE (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  WRITE (KLUN) LBOUND (YD%NPTRSVF)
  WRITE (KLUN) UBOUND (YD%NPTRSVF)
  WRITE (KLUN) YD%NPTRSVF
ENDIF
LNPTRMF = ALLOCATED (YD%NPTRMF)
WRITE (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  WRITE (KLUN) LBOUND (YD%NPTRMF)
  WRITE (KLUN) UBOUND (YD%NPTRMF)
  WRITE (KLUN) YD%NPTRMF
ENDIF
LNSPSTAF = ALLOCATED (YD%NSPSTAF)
WRITE (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  WRITE (KLUN) LBOUND (YD%NSPSTAF)
  WRITE (KLUN) UBOUND (YD%NSPSTAF)
  WRITE (KLUN) YD%NSPSTAF
ENDIF
LNUMLL = ALLOCATED (YD%NUMLL)
WRITE (KLUN) LNUMLL
IF (LNUMLL) THEN
  WRITE (KLUN) LBOUND (YD%NUMLL)
  WRITE (KLUN) UBOUND (YD%NUMLL)
  WRITE (KLUN) YD%NUMLL
ENDIF
LNPTRLL = ALLOCATED (YD%NPTRLL)
WRITE (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLL)
  WRITE (KLUN) UBOUND (YD%NPTRLL)
  WRITE (KLUN) YD%NPTRLL
ENDIF
LMYLEVS = ALLOCATED (YD%MYLEVS)
WRITE (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  WRITE (KLUN) LBOUND (YD%MYLEVS)
  WRITE (KLUN) UBOUND (YD%MYLEVS)
  WRITE (KLUN) YD%MYLEVS
ENDIF
LNPSURF = ALLOCATED (YD%NPSURF)
WRITE (KLUN) LNPSURF
IF (LNPSURF) THEN
  WRITE (KLUN) LBOUND (YD%NPSURF)
  WRITE (KLUN) UBOUND (YD%NPSURF)
  WRITE (KLUN) YD%NPSURF
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (YD%NSTA)
  WRITE (KLUN) UBOUND (YD%NSTA)
  WRITE (KLUN) YD%NSTA
ENDIF
LNONL = ALLOCATED (YD%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (YD%NONL)
  WRITE (KLUN) UBOUND (YD%NONL)
  WRITE (KLUN) YD%NONL
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) YD%NPTRFRSTLAT
ENDIF
LNPTRLSTLAT = ALLOCATED (YD%NPTRLSTLAT)
WRITE (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRLSTLAT)
  WRITE (KLUN) YD%NPTRLSTLAT
ENDIF
LNPTRLAT = ALLOCATED (YD%NPTRLAT)
WRITE (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLAT)
  WRITE (KLUN) UBOUND (YD%NPTRLAT)
  WRITE (KLUN) YD%NPTRLAT
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NFRSTLAT)
  WRITE (KLUN) YD%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NLSTLAT)
  WRITE (KLUN) UBOUND (YD%NLSTLAT)
  WRITE (KLUN) YD%NLSTLAT
ENDIF
LNBSETLEV = ALLOCATED (YD%NBSETLEV)
WRITE (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  WRITE (KLUN) LBOUND (YD%NBSETLEV)
  WRITE (KLUN) UBOUND (YD%NBSETLEV)
  WRITE (KLUN) YD%NBSETLEV
ENDIF
LNGLOBALINDEX = ALLOCATED (YD%NGLOBALINDEX)
WRITE (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  WRITE (KLUN) LBOUND (YD%NGLOBALINDEX)
  WRITE (KLUN) UBOUND (YD%NGLOBALINDEX)
  WRITE (KLUN) YD%NGLOBALINDEX
ENDIF
LNGLOBALAT = ALLOCATED (YD%NGLOBALAT)
WRITE (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  WRITE (KLUN) LBOUND (YD%NGLOBALAT)
  WRITE (KLUN) UBOUND (YD%NGLOBALAT)
  WRITE (KLUN) YD%NGLOBALAT
ENDIF
LNGLOBALPROC = ALLOCATED (YD%NGLOBALPROC)
WRITE (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  WRITE (KLUN) LBOUND (YD%NGLOBALPROC)
  WRITE (KLUN) UBOUND (YD%NGLOBALPROC)
  WRITE (KLUN) YD%NGLOBALPROC
ENDIF
LNLOCALINDEX = ALLOCATED (YD%NLOCALINDEX)
WRITE (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  WRITE (KLUN) LBOUND (YD%NLOCALINDEX)
  WRITE (KLUN) UBOUND (YD%NLOCALINDEX)
  WRITE (KLUN) YD%NLOCALINDEX
ENDIF
LNLATGPP = ALLOCATED (YD%NLATGPP)
WRITE (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  WRITE (KLUN) LBOUND (YD%NLATGPP)
  WRITE (KLUN) UBOUND (YD%NLATGPP)
  WRITE (KLUN) YD%NLATGPP
ENDIF
LNLONGPP = ALLOCATED (YD%NLONGPP)
WRITE (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  WRITE (KLUN) LBOUND (YD%NLONGPP)
  WRITE (KLUN) UBOUND (YD%NLONGPP)
  WRITE (KLUN) YD%NLONGPP
ENDIF
LLSPLITLAT = ALLOCATED (YD%LSPLITLAT)
WRITE (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  WRITE (KLUN) LBOUND (YD%LSPLITLAT)
  WRITE (KLUN) UBOUND (YD%LSPLITLAT)
  WRITE (KLUN) YD%LSPLITLAT
ENDIF
LMYLATS = ALLOCATED (YD%MYLATS)
WRITE (KLUN) LMYLATS
IF (LMYLATS) THEN
  WRITE (KLUN) LBOUND (YD%MYLATS)
  WRITE (KLUN) UBOUND (YD%MYLATS)
  WRITE (KLUN) YD%MYLATS
ENDIF
WRITE (KLUN) YD%NPSP
WRITE (KLUN) YD%NSPEC2V
WRITE (KLUN) YD%NSPEC2VF
WRITE (KLUN) YD%NSPEC2VDDH
WRITE (KLUN) YD%NSPEC2V_NH
WRITE (KLUN) YD%NSPEC2V_NHX
WRITE (KLUN) YD%NBSETSP
WRITE (KLUN) YD%NFRSTLOFF
WRITE (KLUN) YD%MYFRSTACTLAT
WRITE (KLUN) YD%MYLSTACTLAT
WRITE (KLUN) YD%NPTRFLOFF
LNPOSSP = ALLOCATED (YD%NPOSSP)
WRITE (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  WRITE (KLUN) LBOUND (YD%NPOSSP)
  WRITE (KLUN) UBOUND (YD%NPOSSP)
  WRITE (KLUN) YD%NPOSSP
ENDIF
LNDIM0G = ALLOCATED (YD%NDIM0G)
WRITE (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  WRITE (KLUN) LBOUND (YD%NDIM0G)
  WRITE (KLUN) UBOUND (YD%NDIM0G)
  WRITE (KLUN) YD%NDIM0G
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
READ (KLUN) LNUMPP
IF (LNUMPP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUMPP (IL1(1):IU1(1)))
  READ (KLUN) YD%NUMPP
ENDIF
READ (KLUN) LNPROCM
IF (LNPROCM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPROCM (IL1(1):IU1(1)))
  READ (KLUN) YD%NPROCM
ENDIF
READ (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRMS (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRMS
ENDIF
READ (KLUN) LNALLMS
IF (LNALLMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NALLMS (IL1(1):IU1(1)))
  READ (KLUN) YD%NALLMS
ENDIF
READ (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLS (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLS
ENDIF
READ (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRSV (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRSV
ENDIF
READ (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRSVF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRSVF
ENDIF
READ (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRMF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRMF
ENDIF
READ (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSPSTAF (IL1(1):IU1(1)))
  READ (KLUN) YD%NSPSTAF
ENDIF
READ (KLUN) LNUMLL
IF (LNUMLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUMLL (IL1(1):IU1(1)))
  READ (KLUN) YD%NUMLL
ENDIF
READ (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLL (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLL
ENDIF
READ (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYLEVS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYLEVS
ENDIF
READ (KLUN) LNPSURF
IF (LNPSURF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPSURF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPSURF
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NONL
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRFRSTLAT
ENDIF
READ (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLSTLAT
ENDIF
READ (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NLSTLAT
ENDIF
READ (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NBSETLEV (IL1(1):IU1(1)))
  READ (KLUN) YD%NBSETLEV
ENDIF
READ (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALINDEX (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALINDEX
ENDIF
READ (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALAT
ENDIF
READ (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALPROC (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALPROC
ENDIF
READ (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOCALINDEX (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOCALINDEX
ENDIF
READ (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLATGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLATGPP
ENDIF
READ (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLONGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLONGPP
ENDIF
READ (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LSPLITLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%LSPLITLAT
ENDIF
READ (KLUN) LMYLATS
IF (LMYLATS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYLATS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYLATS
ENDIF
READ (KLUN) YD%NPSP
READ (KLUN) YD%NSPEC2V
READ (KLUN) YD%NSPEC2VF
READ (KLUN) YD%NSPEC2VDDH
READ (KLUN) YD%NSPEC2V_NH
READ (KLUN) YD%NSPEC2V_NHX
READ (KLUN) YD%NBSETSP
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPOSSP (IL1(1):IU1(1)))
  READ (KLUN) YD%NPOSSP
ENDIF
READ (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDIM0G (IL1(1):IU1(1)))
  READ (KLUN) YD%NDIM0G
ENDIF
END SUBROUTINE






END MODULE
