MODULE UTIL_MODEL_PHYSICS_STOCHAST_TYPE_MOD

USE MODEL_PHYSICS_STOCHAST_MOD, ONLY : MODEL_PHYSICS_STOCHAST_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_STOCHAST_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_STOCHAST_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_STOCHAST_TYPE (KLUN, YD)
USE UTIL_TSTOPH_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_STOCHAST_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRSTOPH)
END SUBROUTINE
SUBROUTINE LOAD_MODEL_PHYSICS_STOCHAST_TYPE (KLUN, YD)
USE UTIL_TSTOPH_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_STOCHAST_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRSTOPH)
END SUBROUTINE




END MODULE
