MODULE UTIL_TVFE_MOD

USE YOMVERT, ONLY : TVFE

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVFE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVFE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVFE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVFE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVFE), INTENT (IN), TARGET :: YD
LOGICAL :: LD_RINTBF11, LD_RINTE, LRDDERBF01, LRDDERI, LRDERB, LRDERBF00, LRDERBF01, LRDERBF10, LRDERBF11, LRDERBH00
LOGICAL :: LRDERBH01, LRDERGW, LRDERI, LRINTBF00, LRINTBF11, LRINTE, LRINTGW, LVFE_KNOT
LVFE_KNOT = ALLOCATED (YD%VFE_KNOT)
WRITE (KLUN) LVFE_KNOT
IF (LVFE_KNOT) THEN
  WRITE (KLUN) LBOUND (YD%VFE_KNOT)
  WRITE (KLUN) UBOUND (YD%VFE_KNOT)
  WRITE (KLUN) YD%VFE_KNOT
ENDIF
LRINTE = ALLOCATED (YD%RINTE)
WRITE (KLUN) LRINTE
IF (LRINTE) THEN
  WRITE (KLUN) LBOUND (YD%RINTE)
  WRITE (KLUN) UBOUND (YD%RINTE)
  WRITE (KLUN) YD%RINTE
ENDIF
LRINTBF00 = ALLOCATED (YD%RINTBF00)
WRITE (KLUN) LRINTBF00
IF (LRINTBF00) THEN
  WRITE (KLUN) LBOUND (YD%RINTBF00)
  WRITE (KLUN) UBOUND (YD%RINTBF00)
  WRITE (KLUN) YD%RINTBF00
ENDIF
LRINTBF11 = ALLOCATED (YD%RINTBF11)
WRITE (KLUN) LRINTBF11
IF (LRINTBF11) THEN
  WRITE (KLUN) LBOUND (YD%RINTBF11)
  WRITE (KLUN) UBOUND (YD%RINTBF11)
  WRITE (KLUN) YD%RINTBF11
ENDIF
LD_RINTE = ALLOCATED (YD%D_RINTE)
WRITE (KLUN) LD_RINTE
IF (LD_RINTE) THEN
  WRITE (KLUN) LBOUND (YD%D_RINTE)
  WRITE (KLUN) UBOUND (YD%D_RINTE)
  WRITE (KLUN) YD%D_RINTE
ENDIF
LD_RINTBF11 = ALLOCATED (YD%D_RINTBF11)
WRITE (KLUN) LD_RINTBF11
IF (LD_RINTBF11) THEN
  WRITE (KLUN) LBOUND (YD%D_RINTBF11)
  WRITE (KLUN) UBOUND (YD%D_RINTBF11)
  WRITE (KLUN) YD%D_RINTBF11
ENDIF
LRDERI = ALLOCATED (YD%RDERI)
WRITE (KLUN) LRDERI
IF (LRDERI) THEN
  WRITE (KLUN) LBOUND (YD%RDERI)
  WRITE (KLUN) UBOUND (YD%RDERI)
  WRITE (KLUN) YD%RDERI
ENDIF
LRDERB = ALLOCATED (YD%RDERB)
WRITE (KLUN) LRDERB
IF (LRDERB) THEN
  WRITE (KLUN) LBOUND (YD%RDERB)
  WRITE (KLUN) UBOUND (YD%RDERB)
  WRITE (KLUN) YD%RDERB
ENDIF
LRDERBF00 = ALLOCATED (YD%RDERBF00)
WRITE (KLUN) LRDERBF00
IF (LRDERBF00) THEN
  WRITE (KLUN) LBOUND (YD%RDERBF00)
  WRITE (KLUN) UBOUND (YD%RDERBF00)
  WRITE (KLUN) YD%RDERBF00
ENDIF
LRDERBF01 = ALLOCATED (YD%RDERBF01)
WRITE (KLUN) LRDERBF01
IF (LRDERBF01) THEN
  WRITE (KLUN) LBOUND (YD%RDERBF01)
  WRITE (KLUN) UBOUND (YD%RDERBF01)
  WRITE (KLUN) YD%RDERBF01
ENDIF
LRDERBF10 = ALLOCATED (YD%RDERBF10)
WRITE (KLUN) LRDERBF10
IF (LRDERBF10) THEN
  WRITE (KLUN) LBOUND (YD%RDERBF10)
  WRITE (KLUN) UBOUND (YD%RDERBF10)
  WRITE (KLUN) YD%RDERBF10
ENDIF
LRDERBF11 = ALLOCATED (YD%RDERBF11)
WRITE (KLUN) LRDERBF11
IF (LRDERBF11) THEN
  WRITE (KLUN) LBOUND (YD%RDERBF11)
  WRITE (KLUN) UBOUND (YD%RDERBF11)
  WRITE (KLUN) YD%RDERBF11
ENDIF
LRDERBH00 = ALLOCATED (YD%RDERBH00)
WRITE (KLUN) LRDERBH00
IF (LRDERBH00) THEN
  WRITE (KLUN) LBOUND (YD%RDERBH00)
  WRITE (KLUN) UBOUND (YD%RDERBH00)
  WRITE (KLUN) YD%RDERBH00
ENDIF
LRDERBH01 = ALLOCATED (YD%RDERBH01)
WRITE (KLUN) LRDERBH01
IF (LRDERBH01) THEN
  WRITE (KLUN) LBOUND (YD%RDERBH01)
  WRITE (KLUN) UBOUND (YD%RDERBH01)
  WRITE (KLUN) YD%RDERBH01
ENDIF
LRDDERI = ALLOCATED (YD%RDDERI)
WRITE (KLUN) LRDDERI
IF (LRDDERI) THEN
  WRITE (KLUN) LBOUND (YD%RDDERI)
  WRITE (KLUN) UBOUND (YD%RDDERI)
  WRITE (KLUN) YD%RDDERI
ENDIF
LRDDERBF01 = ALLOCATED (YD%RDDERBF01)
WRITE (KLUN) LRDDERBF01
IF (LRDDERBF01) THEN
  WRITE (KLUN) LBOUND (YD%RDDERBF01)
  WRITE (KLUN) UBOUND (YD%RDDERBF01)
  WRITE (KLUN) YD%RDDERBF01
ENDIF
LRINTGW = ALLOCATED (YD%RINTGW)
WRITE (KLUN) LRINTGW
IF (LRINTGW) THEN
  WRITE (KLUN) LBOUND (YD%RINTGW)
  WRITE (KLUN) UBOUND (YD%RINTGW)
  WRITE (KLUN) YD%RINTGW
ENDIF
LRDERGW = ALLOCATED (YD%RDERGW)
WRITE (KLUN) LRDERGW
IF (LRDERGW) THEN
  WRITE (KLUN) LBOUND (YD%RDERGW)
  WRITE (KLUN) UBOUND (YD%RDERGW)
  WRITE (KLUN) YD%RDERGW
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVFE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVFE), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LD_RINTBF11, LD_RINTE, LRDDERBF01, LRDDERI, LRDERB, LRDERBF00, LRDERBF01, LRDERBF10, LRDERBF11, LRDERBH00
LOGICAL :: LRDERBH01, LRDERGW, LRDERI, LRINTBF00, LRINTBF11, LRINTE, LRINTGW, LVFE_KNOT
READ (KLUN) LVFE_KNOT
IF (LVFE_KNOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_KNOT (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_KNOT
ENDIF
READ (KLUN) LRINTE
IF (LRINTE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTE
ENDIF
READ (KLUN) LRINTBF00
IF (LRINTBF00) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTBF00 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTBF00
ENDIF
READ (KLUN) LRINTBF11
IF (LRINTBF11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTBF11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTBF11
ENDIF
READ (KLUN) LD_RINTE
IF (LD_RINTE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%D_RINTE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%D_RINTE
ENDIF
READ (KLUN) LD_RINTBF11
IF (LD_RINTBF11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%D_RINTBF11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%D_RINTBF11
ENDIF
READ (KLUN) LRDERI
IF (LRDERI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERI
ENDIF
READ (KLUN) LRDERB
IF (LRDERB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERB (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERB
ENDIF
READ (KLUN) LRDERBF00
IF (LRDERBF00) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF00 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF00
ENDIF
READ (KLUN) LRDERBF01
IF (LRDERBF01) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF01 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF01
ENDIF
READ (KLUN) LRDERBF10
IF (LRDERBF10) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF10 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF10
ENDIF
READ (KLUN) LRDERBF11
IF (LRDERBF11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF11
ENDIF
READ (KLUN) LRDERBH00
IF (LRDERBH00) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBH00 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBH00
ENDIF
READ (KLUN) LRDERBH01
IF (LRDERBH01) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBH01 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBH01
ENDIF
READ (KLUN) LRDDERI
IF (LRDDERI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERI
ENDIF
READ (KLUN) LRDDERBF01
IF (LRDDERBF01) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERBF01 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERBF01
ENDIF
READ (KLUN) LRINTGW
IF (LRINTGW) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTGW (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTGW
ENDIF
READ (KLUN) LRDERGW
IF (LRDERGW) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERGW (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERGW
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVFE (YD, LDCREATED)

IMPLICIT NONE
TYPE (TVFE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LD_RINTBF11, LD_RINTE, LRDDERBF01, LRDDERI, LRDERB, LRDERBF00, LRDERBF01, LRDERBF10, LRDERBF11, LRDERBH00
LOGICAL :: LRDERBH01, LRDERGW, LRDERI, LRINTBF00, LRINTBF11, LRINTE, LRINTGW, LVFE_KNOT

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LVFE_KNOT = ALLOCATED (YD%VFE_KNOT)
IF (LVFE_KNOT) THEN
  !$acc enter data create (YD%VFE_KNOT)
  !$acc update device (YD%VFE_KNOT)
  !$acc enter data attach (YD%VFE_KNOT)
ENDIF

LRINTE = ALLOCATED (YD%RINTE)
IF (LRINTE) THEN
  !$acc enter data create (YD%RINTE)
  !$acc update device (YD%RINTE)
  !$acc enter data attach (YD%RINTE)
ENDIF

LRINTBF00 = ALLOCATED (YD%RINTBF00)
IF (LRINTBF00) THEN
  !$acc enter data create (YD%RINTBF00)
  !$acc update device (YD%RINTBF00)
  !$acc enter data attach (YD%RINTBF00)
ENDIF

LRINTBF11 = ALLOCATED (YD%RINTBF11)
IF (LRINTBF11) THEN
  !$acc enter data create (YD%RINTBF11)
  !$acc update device (YD%RINTBF11)
  !$acc enter data attach (YD%RINTBF11)
ENDIF

LD_RINTE = ALLOCATED (YD%D_RINTE)
IF (LD_RINTE) THEN
  !$acc enter data create (YD%D_RINTE)
  !$acc update device (YD%D_RINTE)
  !$acc enter data attach (YD%D_RINTE)
ENDIF

LD_RINTBF11 = ALLOCATED (YD%D_RINTBF11)
IF (LD_RINTBF11) THEN
  !$acc enter data create (YD%D_RINTBF11)
  !$acc update device (YD%D_RINTBF11)
  !$acc enter data attach (YD%D_RINTBF11)
ENDIF

LRDERI = ALLOCATED (YD%RDERI)
IF (LRDERI) THEN
  !$acc enter data create (YD%RDERI)
  !$acc update device (YD%RDERI)
  !$acc enter data attach (YD%RDERI)
ENDIF

LRDERB = ALLOCATED (YD%RDERB)
IF (LRDERB) THEN
  !$acc enter data create (YD%RDERB)
  !$acc update device (YD%RDERB)
  !$acc enter data attach (YD%RDERB)
ENDIF

LRDERBF00 = ALLOCATED (YD%RDERBF00)
IF (LRDERBF00) THEN
  !$acc enter data create (YD%RDERBF00)
  !$acc update device (YD%RDERBF00)
  !$acc enter data attach (YD%RDERBF00)
ENDIF

LRDERBF01 = ALLOCATED (YD%RDERBF01)
IF (LRDERBF01) THEN
  !$acc enter data create (YD%RDERBF01)
  !$acc update device (YD%RDERBF01)
  !$acc enter data attach (YD%RDERBF01)
ENDIF

LRDERBF10 = ALLOCATED (YD%RDERBF10)
IF (LRDERBF10) THEN
  !$acc enter data create (YD%RDERBF10)
  !$acc update device (YD%RDERBF10)
  !$acc enter data attach (YD%RDERBF10)
ENDIF

LRDERBF11 = ALLOCATED (YD%RDERBF11)
IF (LRDERBF11) THEN
  !$acc enter data create (YD%RDERBF11)
  !$acc update device (YD%RDERBF11)
  !$acc enter data attach (YD%RDERBF11)
ENDIF

LRDERBH00 = ALLOCATED (YD%RDERBH00)
IF (LRDERBH00) THEN
  !$acc enter data create (YD%RDERBH00)
  !$acc update device (YD%RDERBH00)
  !$acc enter data attach (YD%RDERBH00)
ENDIF

LRDERBH01 = ALLOCATED (YD%RDERBH01)
IF (LRDERBH01) THEN
  !$acc enter data create (YD%RDERBH01)
  !$acc update device (YD%RDERBH01)
  !$acc enter data attach (YD%RDERBH01)
ENDIF

LRDDERI = ALLOCATED (YD%RDDERI)
IF (LRDDERI) THEN
  !$acc enter data create (YD%RDDERI)
  !$acc update device (YD%RDDERI)
  !$acc enter data attach (YD%RDDERI)
ENDIF

LRDDERBF01 = ALLOCATED (YD%RDDERBF01)
IF (LRDDERBF01) THEN
  !$acc enter data create (YD%RDDERBF01)
  !$acc update device (YD%RDDERBF01)
  !$acc enter data attach (YD%RDDERBF01)
ENDIF

LRINTGW = ALLOCATED (YD%RINTGW)
IF (LRINTGW) THEN
  !$acc enter data create (YD%RINTGW)
  !$acc update device (YD%RINTGW)
  !$acc enter data attach (YD%RINTGW)
ENDIF

LRDERGW = ALLOCATED (YD%RDERGW)
IF (LRDERGW) THEN
  !$acc enter data create (YD%RDERGW)
  !$acc update device (YD%RDERGW)
  !$acc enter data attach (YD%RDERGW)
ENDIF

END SUBROUTINE



END MODULE
