MODULE UTIL_TCSGEOM_BLOCKED_MOD

USE YOMCSGEOM, ONLY : TCSGEOM_BLOCKED

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCSGEOM_BLOCKED
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCSGEOM_BLOCKED
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TCSGEOM_BLOCKED (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGEOM_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LRCOLON = ASSOCIATED (YD%RCOLON)
WRITE (KLUN) LRCOLON
IF (LRCOLON) THEN
  WRITE (KLUN) LBOUND (YD%RCOLON)
  WRITE (KLUN) UBOUND (YD%RCOLON)
  WRITE (KLUN) YD%RCOLON
ENDIF
LRSILON = ASSOCIATED (YD%RSILON)
WRITE (KLUN) LRSILON
IF (LRSILON) THEN
  WRITE (KLUN) LBOUND (YD%RSILON)
  WRITE (KLUN) UBOUND (YD%RSILON)
  WRITE (KLUN) YD%RSILON
ENDIF
LRINDX = ASSOCIATED (YD%RINDX)
WRITE (KLUN) LRINDX
IF (LRINDX) THEN
  WRITE (KLUN) LBOUND (YD%RINDX)
  WRITE (KLUN) UBOUND (YD%RINDX)
  WRITE (KLUN) YD%RINDX
ENDIF
LRINDY = ASSOCIATED (YD%RINDY)
WRITE (KLUN) LRINDY
IF (LRINDY) THEN
  WRITE (KLUN) LBOUND (YD%RINDY)
  WRITE (KLUN) UBOUND (YD%RINDY)
  WRITE (KLUN) YD%RINDY
ENDIF
LRATATH = ASSOCIATED (YD%RATATH)
WRITE (KLUN) LRATATH
IF (LRATATH) THEN
  WRITE (KLUN) LBOUND (YD%RATATH)
  WRITE (KLUN) UBOUND (YD%RATATH)
  WRITE (KLUN) YD%RATATH
ENDIF
LRATATX = ASSOCIATED (YD%RATATX)
WRITE (KLUN) LRATATX
IF (LRATATX) THEN
  WRITE (KLUN) LBOUND (YD%RATATX)
  WRITE (KLUN) UBOUND (YD%RATATX)
  WRITE (KLUN) YD%RATATX
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TCSGEOM_BLOCKED (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGEOM_BLOCKED), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
READ (KLUN) LRCOLON
IF (LRCOLON) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RCOLON (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RCOLON
ELSE
  NULLIFY (YD%RCOLON)
ENDIF
READ (KLUN) LRSILON
IF (LRSILON) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSILON (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSILON
ELSE
  NULLIFY (YD%RSILON)
ENDIF
READ (KLUN) LRINDX
IF (LRINDX) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINDX (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINDX
ELSE
  NULLIFY (YD%RINDX)
ENDIF
READ (KLUN) LRINDY
IF (LRINDY) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINDY (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINDY
ELSE
  NULLIFY (YD%RINDY)
ENDIF
READ (KLUN) LRATATH
IF (LRATATH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RATATH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RATATH
ELSE
  NULLIFY (YD%RATATH)
ENDIF
READ (KLUN) LRATATX
IF (LRATATX) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RATATX (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RATATX
ELSE
  NULLIFY (YD%RATATX)
ENDIF
END SUBROUTINE






END MODULE
