MODULE UTIL_TYPE_GFL_NAML_MOD

USE YOM_YGFL, ONLY : TYPE_GFL_NAML

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_GFL_NAML
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_GFL_NAML
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TYPE_GFL_NAML (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFL_NAML), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%CNAME
WRITE (KLUN) YD%IGRBCODE
WRITE (KLUN) YD%NREQIN
WRITE (KLUN) YD%REFVALI
WRITE (KLUN) YD%LREQOUT
WRITE (KLUN) YD%LGPINGP
WRITE (KLUN) YD%LMGRID
WRITE (KLUN) YD%LGP
WRITE (KLUN) YD%LSP
WRITE (KLUN) YD%LCDERS
WRITE (KLUN) YD%LT9
WRITE (KLUN) YD%LT1
WRITE (KLUN) YD%LT5
WRITE (KLUN) YD%LPHY
WRITE (KLUN) YD%LPT
WRITE (KLUN) YD%LTRAJIO
WRITE (KLUN) YD%LDIAG
WRITE (KLUN) YD%LPC
WRITE (KLUN) YD%LADV
WRITE (KLUN) YD%LADV5
WRITE (KLUN) YD%LINTLIN
WRITE (KLUN) YD%LTDIABLIN
WRITE (KLUN) YD%LHORTURB
WRITE (KLUN) YD%LQM
WRITE (KLUN) YD%LQMH
WRITE (KLUN) YD%LQM3D
WRITE (KLUN) YD%LQML3D
WRITE (KLUN) YD%LVWENO
WRITE (KLUN) YD%WENO_ALPHA
WRITE (KLUN) YD%LSLHD
WRITE (KLUN) YD%LCOMAD
WRITE (KLUN) YD%LHV
WRITE (KLUN) YD%LVSPLIP
WRITE (KLUN) YD%NCOUPLING
WRITE (KLUN) YD%REFVALC
WRITE (KLUN) YD%NCOUPLO4
WRITE (KLUN) YD%LASSIM
WRITE (KLUN) YD%IGRIBDV
WRITE (KLUN) YD%IGRIBTC
WRITE (KLUN) YD%IGRIBSFC
WRITE (KLUN) YD%IGRBFLXO
WRITE (KLUN) YD%LDIFF
WRITE (KLUN) YD%LCONV
WRITE (KLUN) YD%LNEGFIX
WRITE (KLUN) YD%LMASSFIX
WRITE (KLUN) YD%BETAMFBC
WRITE (KLUN) YD%RMOLMASS
WRITE (KLUN) YD%REFOLD
WRITE (KLUN) YD%HENRYA
WRITE (KLUN) YD%HENRYB
END SUBROUTINE

SUBROUTINE LOAD_TYPE_GFL_NAML (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFL_NAML), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%CNAME
READ (KLUN) YD%IGRBCODE
READ (KLUN) YD%NREQIN
READ (KLUN) YD%REFVALI
READ (KLUN) YD%LREQOUT
READ (KLUN) YD%LGPINGP
READ (KLUN) YD%LMGRID
READ (KLUN) YD%LGP
READ (KLUN) YD%LSP
READ (KLUN) YD%LCDERS
READ (KLUN) YD%LT9
READ (KLUN) YD%LT1
READ (KLUN) YD%LT5
READ (KLUN) YD%LPHY
READ (KLUN) YD%LPT
READ (KLUN) YD%LTRAJIO
READ (KLUN) YD%LDIAG
READ (KLUN) YD%LPC
READ (KLUN) YD%LADV
READ (KLUN) YD%LADV5
READ (KLUN) YD%LINTLIN
READ (KLUN) YD%LTDIABLIN
READ (KLUN) YD%LHORTURB
READ (KLUN) YD%LQM
READ (KLUN) YD%LQMH
READ (KLUN) YD%LQM3D
READ (KLUN) YD%LQML3D
READ (KLUN) YD%LVWENO
READ (KLUN) YD%WENO_ALPHA
READ (KLUN) YD%LSLHD
READ (KLUN) YD%LCOMAD
READ (KLUN) YD%LHV
READ (KLUN) YD%LVSPLIP
READ (KLUN) YD%NCOUPLING
READ (KLUN) YD%REFVALC
READ (KLUN) YD%NCOUPLO4
READ (KLUN) YD%LASSIM
READ (KLUN) YD%IGRIBDV
READ (KLUN) YD%IGRIBTC
READ (KLUN) YD%IGRIBSFC
READ (KLUN) YD%IGRBFLXO
READ (KLUN) YD%LDIFF
READ (KLUN) YD%LCONV
READ (KLUN) YD%LNEGFIX
READ (KLUN) YD%LMASSFIX
READ (KLUN) YD%BETAMFBC
READ (KLUN) YD%RMOLMASS
READ (KLUN) YD%REFOLD
READ (KLUN) YD%HENRYA
READ (KLUN) YD%HENRYB
END SUBROUTINE






END MODULE
