MODULE UTIL_TSDDH_MOD

USE YOMSDDH, ONLY : TSDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSDDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSDDH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSDDH), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NHDQLNVA
WRITE (KLUN) YD%NHDQLNTD
WRITE (KLUN) YD%NHDQLNFD
WRITE (KLUN) YD%NHDQLNFP
WRITE (KLUN) YD%NHDQLNTP
WRITE (KLUN) YD%NHDPASVA
WRITE (KLUN) YD%NHDPASTD
WRITE (KLUN) YD%NHDPASFD
WRITE (KLUN) YD%NHDPASFP
WRITE (KLUN) YD%NHDPASTP
WRITE (KLUN) YD%LHDQLN
WRITE (KLUN) YD%LHDPAS
END SUBROUTINE

SUBROUTINE LOAD_TSDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSDDH), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NHDQLNVA
READ (KLUN) YD%NHDQLNTD
READ (KLUN) YD%NHDQLNFD
READ (KLUN) YD%NHDQLNFP
READ (KLUN) YD%NHDQLNTP
READ (KLUN) YD%NHDPASVA
READ (KLUN) YD%NHDPASTD
READ (KLUN) YD%NHDPASFD
READ (KLUN) YD%NHDPASFP
READ (KLUN) YD%NHDPASTP
READ (KLUN) YD%LHDQLN
READ (KLUN) YD%LHDPAS
END SUBROUTINE


SUBROUTINE COPY_TSDDH (YD, LDCREATED)

IMPLICIT NONE
TYPE (TSDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF












END SUBROUTINE



END MODULE
