MODULE UTIL_TPHYDS_MOD

USE YOMPHYDS, ONLY : TPHYDS


INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHYDS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHYDS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHYDS
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPHYDS
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TPHYDS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHYDS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%JPVXP
WRITE (KLUN) YD%JPVXP2
WRITE (KLUN) YD%JPCXP
WRITE (KLUN) YD%JPVEXTR
WRITE (KLUN) YD%JPVEXTRDI
WRITE (KLUN) YD%JPVXTR2
WRITE (KLUN) YD%JPVPRECIP
WRITE (KLUN) YD%JPVPRECIP2
WRITE (KLUN) YD%CEXTRP
WRITE (KLUN) YD%CXTRP2
WRITE (KLUN) YD%CVEXTRA
WRITE (KLUN) YD%CVEXRAD
WRITE (KLUN) YD%CVEXTRDI
WRITE (KLUN) YD%CVEXTR2
WRITE (KLUN) YD%CVPRECIP
WRITE (KLUN) YD%CVPRECIP2
WRITE (KLUN) YD%NEXTRPGB
WRITE (KLUN) YD%NXTRP2GB
WRITE (KLUN) YD%NVEXTRAGB
WRITE (KLUN) YD%NVEXRADGB
WRITE (KLUN) YD%NVEXTR2GB
WRITE (KLUN) YD%NVEXTRDIGB
WRITE (KLUN) YD%NVPRECIPGB
WRITE (KLUN) YD%NVPRECIPGB2
WRITE (KLUN) YD%NSFLUX
WRITE (KLUN) YD%NSFORC
WRITE (KLUN) YD%NPPVCLIX
WRITE (KLUN) YD%EXTRPDF
WRITE (KLUN) YD%XTRP2DF
WRITE (KLUN) YD%VEXTRADF
WRITE (KLUN) YD%VEXRADDF
WRITE (KLUN) YD%VEXTR2DF
WRITE (KLUN) YD%VEXTRDI
WRITE (KLUN) YD%VPRECIP
WRITE (KLUN) YD%VPRECIP2
WRITE (KLUN) YD%LREQIN_VEXTRDI
WRITE (KLUN) YD%LREQOUT_VEXTRDI
END SUBROUTINE

SUBROUTINE LOAD_TPHYDS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHYDS), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%JPVXP
READ (KLUN) YD%JPVXP2
READ (KLUN) YD%JPCXP
READ (KLUN) YD%JPVEXTR
READ (KLUN) YD%JPVEXTRDI
READ (KLUN) YD%JPVXTR2
READ (KLUN) YD%JPVPRECIP
READ (KLUN) YD%JPVPRECIP2
READ (KLUN) YD%CEXTRP
READ (KLUN) YD%CXTRP2
READ (KLUN) YD%CVEXTRA
READ (KLUN) YD%CVEXRAD
READ (KLUN) YD%CVEXTRDI
READ (KLUN) YD%CVEXTR2
READ (KLUN) YD%CVPRECIP
READ (KLUN) YD%CVPRECIP2
READ (KLUN) YD%NEXTRPGB
READ (KLUN) YD%NXTRP2GB
READ (KLUN) YD%NVEXTRAGB
READ (KLUN) YD%NVEXRADGB
READ (KLUN) YD%NVEXTR2GB
READ (KLUN) YD%NVEXTRDIGB
READ (KLUN) YD%NVPRECIPGB
READ (KLUN) YD%NVPRECIPGB2
READ (KLUN) YD%NSFLUX
READ (KLUN) YD%NSFORC
READ (KLUN) YD%NPPVCLIX
READ (KLUN) YD%EXTRPDF
READ (KLUN) YD%XTRP2DF
READ (KLUN) YD%VEXTRADF
READ (KLUN) YD%VEXRADDF
READ (KLUN) YD%VEXTR2DF
READ (KLUN) YD%VEXTRDI
READ (KLUN) YD%VPRECIP
READ (KLUN) YD%VPRECIP2
READ (KLUN) YD%LREQIN_VEXTRDI
READ (KLUN) YD%LREQOUT_VEXTRDI
END SUBROUTINE


SUBROUTINE COPY_TPHYDS (YD, LDCREATED)
IMPLICIT NONE
TYPE (TPHYDS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





































END SUBROUTINE

SUBROUTINE WIPE_TPHYDS (YD, LDDELETED)
IMPLICIT NONE
TYPE (TPHYDS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED






































LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
