MODULE UTIL_TSTA_MOD

USE YOMSTA, ONLY : TSTA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSTA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSTA
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TSTA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTA), INTENT (IN), TARGET :: YD
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH
LSTPREH = ALLOCATED (YD%STPREH)
WRITE (KLUN) LSTPREH
IF (LSTPREH) THEN
  WRITE (KLUN) LBOUND (YD%STPREH)
  WRITE (KLUN) UBOUND (YD%STPREH)
  WRITE (KLUN) YD%STPREH
ENDIF
LSTPRE = ALLOCATED (YD%STPRE)
WRITE (KLUN) LSTPRE
IF (LSTPRE) THEN
  WRITE (KLUN) LBOUND (YD%STPRE)
  WRITE (KLUN) UBOUND (YD%STPRE)
  WRITE (KLUN) YD%STPRE
ENDIF
LSTPHI = ALLOCATED (YD%STPHI)
WRITE (KLUN) LSTPHI
IF (LSTPHI) THEN
  WRITE (KLUN) LBOUND (YD%STPHI)
  WRITE (KLUN) UBOUND (YD%STPHI)
  WRITE (KLUN) YD%STPHI
ENDIF
LSTTEM = ALLOCATED (YD%STTEM)
WRITE (KLUN) LSTTEM
IF (LSTTEM) THEN
  WRITE (KLUN) LBOUND (YD%STTEM)
  WRITE (KLUN) UBOUND (YD%STTEM)
  WRITE (KLUN) YD%STTEM
ENDIF
LSTDEN = ALLOCATED (YD%STDEN)
WRITE (KLUN) LSTDEN
IF (LSTDEN) THEN
  WRITE (KLUN) LBOUND (YD%STDEN)
  WRITE (KLUN) UBOUND (YD%STDEN)
  WRITE (KLUN) YD%STDEN
ENDIF
LSTZ = ALLOCATED (YD%STZ)
WRITE (KLUN) LSTZ
IF (LSTZ) THEN
  WRITE (KLUN) LBOUND (YD%STZ)
  WRITE (KLUN) UBOUND (YD%STZ)
  WRITE (KLUN) YD%STZ
ENDIF
LSVETAH = ALLOCATED (YD%SVETAH)
WRITE (KLUN) LSVETAH
IF (LSVETAH) THEN
  WRITE (KLUN) LBOUND (YD%SVETAH)
  WRITE (KLUN) UBOUND (YD%SVETAH)
  WRITE (KLUN) YD%SVETAH
ENDIF
LSVETAF = ALLOCATED (YD%SVETAF)
WRITE (KLUN) LSVETAF
IF (LSVETAF) THEN
  WRITE (KLUN) LBOUND (YD%SVETAF)
  WRITE (KLUN) UBOUND (YD%SVETAF)
  WRITE (KLUN) YD%SVETAF
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TSTA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH
READ (KLUN) LSTPREH
IF (LSTPREH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPREH (IL1(1):IU1(1)))
  READ (KLUN) YD%STPREH
ENDIF
READ (KLUN) LSTPRE
IF (LSTPRE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPRE (IL1(1):IU1(1)))
  READ (KLUN) YD%STPRE
ENDIF
READ (KLUN) LSTPHI
IF (LSTPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPHI (IL1(1):IU1(1)))
  READ (KLUN) YD%STPHI
ENDIF
READ (KLUN) LSTTEM
IF (LSTTEM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STTEM (IL1(1):IU1(1)))
  READ (KLUN) YD%STTEM
ENDIF
READ (KLUN) LSTDEN
IF (LSTDEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STDEN (IL1(1):IU1(1)))
  READ (KLUN) YD%STDEN
ENDIF
READ (KLUN) LSTZ
IF (LSTZ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STZ (IL1(1):IU1(1)))
  READ (KLUN) YD%STZ
ENDIF
READ (KLUN) LSVETAH
IF (LSVETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SVETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%SVETAH
ENDIF
READ (KLUN) LSVETAF
IF (LSVETAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SVETAF (IL1(1):IU1(1)))
  READ (KLUN) YD%SVETAF
ENDIF
END SUBROUTINE




END MODULE
