MODULE UTIL_TVETA_MOD

USE YOMVERT, ONLY : TVETA


INTERFACE SAVE
MODULE PROCEDURE SAVE_TVETA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVETA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVETA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVETA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVETA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVETA), INTENT (IN), TARGET :: YD
LOGICAL :: LVETAF, LVETAH, LVFE_ETAF, LVFE_ETAH, LVFE_RDETAH

LVETAH = ALLOCATED (YD%VETAH)
WRITE (KLUN) LVETAH
IF (LVETAH) THEN
  WRITE (KLUN) LBOUND (YD%VETAH)
  WRITE (KLUN) UBOUND (YD%VETAH)
  WRITE (KLUN) YD%VETAH
ENDIF
LVFE_ETAH = ALLOCATED (YD%VFE_ETAH)
WRITE (KLUN) LVFE_ETAH
IF (LVFE_ETAH) THEN
  WRITE (KLUN) LBOUND (YD%VFE_ETAH)
  WRITE (KLUN) UBOUND (YD%VFE_ETAH)
  WRITE (KLUN) YD%VFE_ETAH
ENDIF
LVETAF = ALLOCATED (YD%VETAF)
WRITE (KLUN) LVETAF
IF (LVETAF) THEN
  WRITE (KLUN) LBOUND (YD%VETAF)
  WRITE (KLUN) UBOUND (YD%VETAF)
  WRITE (KLUN) YD%VETAF
ENDIF
LVFE_ETAF = ALLOCATED (YD%VFE_ETAF)
WRITE (KLUN) LVFE_ETAF
IF (LVFE_ETAF) THEN
  WRITE (KLUN) LBOUND (YD%VFE_ETAF)
  WRITE (KLUN) UBOUND (YD%VFE_ETAF)
  WRITE (KLUN) YD%VFE_ETAF
ENDIF
LVFE_RDETAH = ALLOCATED (YD%VFE_RDETAH)
WRITE (KLUN) LVFE_RDETAH
IF (LVFE_RDETAH) THEN
  WRITE (KLUN) LBOUND (YD%VFE_RDETAH)
  WRITE (KLUN) UBOUND (YD%VFE_RDETAH)
  WRITE (KLUN) YD%VFE_RDETAH
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVETA (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVETA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LVETAF, LVETAH, LVFE_ETAF, LVFE_ETAH, LVFE_RDETAH

READ (KLUN) LVETAH
IF (LVETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VETAH
ENDIF
READ (KLUN) LVFE_ETAH
IF (LVFE_ETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_ETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_ETAH
ENDIF
READ (KLUN) LVETAF
IF (LVETAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VETAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VETAF
ENDIF
READ (KLUN) LVFE_ETAF
IF (LVFE_ETAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_ETAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_ETAF
ENDIF
READ (KLUN) LVFE_RDETAH
IF (LVFE_RDETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_RDETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_RDETAH
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVETA (YD, LDCREATED)
IMPLICIT NONE
TYPE (TVETA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LVETAF, LVETAH, LVFE_ETAF, LVFE_ETAH, LVFE_RDETAH

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LVETAH = ALLOCATED (YD%VETAH)
IF (LVETAH) THEN
  !$acc enter data create (YD%VETAH)
  !$acc update device (YD%VETAH)
  !$acc enter data attach (YD%VETAH)
ENDIF

LVFE_ETAH = ALLOCATED (YD%VFE_ETAH)
IF (LVFE_ETAH) THEN
  !$acc enter data create (YD%VFE_ETAH)
  !$acc update device (YD%VFE_ETAH)
  !$acc enter data attach (YD%VFE_ETAH)
ENDIF

LVETAF = ALLOCATED (YD%VETAF)
IF (LVETAF) THEN
  !$acc enter data create (YD%VETAF)
  !$acc update device (YD%VETAF)
  !$acc enter data attach (YD%VETAF)
ENDIF

LVFE_ETAF = ALLOCATED (YD%VFE_ETAF)
IF (LVFE_ETAF) THEN
  !$acc enter data create (YD%VFE_ETAF)
  !$acc update device (YD%VFE_ETAF)
  !$acc enter data attach (YD%VFE_ETAF)
ENDIF

LVFE_RDETAH = ALLOCATED (YD%VFE_RDETAH)
IF (LVFE_RDETAH) THEN
  !$acc enter data create (YD%VFE_RDETAH)
  !$acc update device (YD%VFE_RDETAH)
  !$acc enter data attach (YD%VFE_RDETAH)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TVETA (YD, LDDELETED)
IMPLICIT NONE
TYPE (TVETA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LVETAF, LVETAH, LVFE_ETAF, LVFE_ETAH, LVFE_RDETAH

LVETAH = ALLOCATED (YD%VETAH)
IF (LVETAH) THEN
  !$acc exit data detach (YD%VETAH)
  !$acc exit data delete (YD%VETAH)
ENDIF

LVFE_ETAH = ALLOCATED (YD%VFE_ETAH)
IF (LVFE_ETAH) THEN
  !$acc exit data detach (YD%VFE_ETAH)
  !$acc exit data delete (YD%VFE_ETAH)
ENDIF

LVETAF = ALLOCATED (YD%VETAF)
IF (LVETAF) THEN
  !$acc exit data detach (YD%VETAF)
  !$acc exit data delete (YD%VETAF)
ENDIF

LVFE_ETAF = ALLOCATED (YD%VFE_ETAF)
IF (LVFE_ETAF) THEN
  !$acc exit data detach (YD%VFE_ETAF)
  !$acc exit data delete (YD%VFE_ETAF)
ENDIF

LVFE_RDETAH = ALLOCATED (YD%VFE_RDETAH)
IF (LVFE_RDETAH) THEN
  !$acc exit data detach (YD%VFE_RDETAH)
  !$acc exit data delete (YD%VFE_RDETAH)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
