MODULE UTIL_TEAERVOL_MOD

USE YOEAERVOL, ONLY : TEAERVOL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERVOL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERVOL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERVOL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEAERVOL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERVOL), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NAERVOLC
WRITE (KLUN) YD%NAERVOLE
WRITE (KLUN) YD%NINTERPT
WRITE (KLUN) YD%NTVOLC
WRITE (KLUN) YD%NVOLERUP
WRITE (KLUN) YD%NVOLHOMO
WRITE (KLUN) YD%NVOLOPTP
WRITE (KLUN) YD%NVOLERUZ
WRITE (KLUN) YD%NVOLDATS
WRITE (KLUN) YD%NVOLDATE
WRITE (KLUN) YD%RAERVOLC
WRITE (KLUN) YD%RAERVOLE
WRITE (KLUN) YD%RVOLERUZ
WRITE (KLUN) YD%RVSEDVOL
WRITE (KLUN) YD%RVDEPVOL
WRITE (KLUN) YD%RWDEPVOL
END SUBROUTINE

SUBROUTINE LOAD_TEAERVOL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERVOL), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NAERVOLC
READ (KLUN) YD%NAERVOLE
READ (KLUN) YD%NINTERPT
READ (KLUN) YD%NTVOLC
READ (KLUN) YD%NVOLERUP
READ (KLUN) YD%NVOLHOMO
READ (KLUN) YD%NVOLOPTP
READ (KLUN) YD%NVOLERUZ
READ (KLUN) YD%NVOLDATS
READ (KLUN) YD%NVOLDATE
READ (KLUN) YD%RAERVOLC
READ (KLUN) YD%RAERVOLE
READ (KLUN) YD%RVOLERUZ
READ (KLUN) YD%RVSEDVOL
READ (KLUN) YD%RVDEPVOL
READ (KLUN) YD%RWDEPVOL
END SUBROUTINE


SUBROUTINE COPY_TEAERVOL (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEAERVOL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
















END SUBROUTINE



END MODULE
