MODULE UTIL_CPG_MISC_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_MISC_TYPE
USE UTIL_FIELD_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_MISC_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_MISC_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPG_MISC_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_MISC_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_CPG_MISC_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_MISC_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN
LOGICAL :: LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL

LF_NEB = ASSOCIATED (YD%F_NEB)
WRITE (KLUN) LF_NEB
IF (LF_NEB) THEN
  CALL SAVE (KLUN, YD%F_NEB)
ENDIF
LF_QLI = ASSOCIATED (YD%F_QLI)
WRITE (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL SAVE (KLUN, YD%F_QLI)
ENDIF
LF_QICE = ASSOCIATED (YD%F_QICE)
WRITE (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL SAVE (KLUN, YD%F_QICE)
ENDIF
LF_QRAIN = ASSOCIATED (YD%F_QRAIN)
WRITE (KLUN) LF_QRAIN
IF (LF_QRAIN) THEN
  CALL SAVE (KLUN, YD%F_QRAIN)
ENDIF
LF_QSNOW = ASSOCIATED (YD%F_QSNOW)
WRITE (KLUN) LF_QSNOW
IF (LF_QSNOW) THEN
  CALL SAVE (KLUN, YD%F_QSNOW)
ENDIF
LF_QGRAUPEL = ASSOCIATED (YD%F_QGRAUPEL)
WRITE (KLUN) LF_QGRAUPEL
IF (LF_QGRAUPEL) THEN
  CALL SAVE (KLUN, YD%F_QGRAUPEL)
ENDIF
LF_RH = ASSOCIATED (YD%F_RH)
WRITE (KLUN) LF_RH
IF (LF_RH) THEN
  CALL SAVE (KLUN, YD%F_RH)
ENDIF
LF_QS = ASSOCIATED (YD%F_QS)
WRITE (KLUN) LF_QS
IF (LF_QS) THEN
  CALL SAVE (KLUN, YD%F_QS)
ENDIF
LF_QSOL = ASSOCIATED (YD%F_QSOL)
WRITE (KLUN) LF_QSOL
IF (LF_QSOL) THEN
  CALL SAVE (KLUN, YD%F_QSOL)
ENDIF
LF_DHSF = ASSOCIATED (YD%F_DHSF)
WRITE (KLUN) LF_DHSF
IF (LF_DHSF) THEN
  CALL SAVE (KLUN, YD%F_DHSF)
ENDIF
LF_CLCT = ASSOCIATED (YD%F_CLCT)
WRITE (KLUN) LF_CLCT
IF (LF_CLCT) THEN
  CALL SAVE (KLUN, YD%F_CLCT)
ENDIF
LF_LSM = ASSOCIATED (YD%F_LSM)
WRITE (KLUN) LF_LSM
IF (LF_LSM) THEN
  CALL SAVE (KLUN, YD%F_LSM)
ENDIF
LF_TSOL = ASSOCIATED (YD%F_TSOL)
WRITE (KLUN) LF_TSOL
IF (LF_TSOL) THEN
  CALL SAVE (KLUN, YD%F_TSOL)
ENDIF
LF_FTCNS = ASSOCIATED (YD%F_FTCNS)
WRITE (KLUN) LF_FTCNS
IF (LF_FTCNS) THEN
  CALL SAVE (KLUN, YD%F_FTCNS)
ENDIF
LF_KOZO = ASSOCIATED (YD%F_KOZO)
WRITE (KLUN) LF_KOZO
IF (LF_KOZO) THEN
  CALL SAVE (KLUN, YD%F_KOZO)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_MISC_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_MISC_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN
LOGICAL :: LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL

NULLIFY (YD%NEB)
READ (KLUN) LF_NEB
IF (LF_NEB) THEN
  CALL LOAD (KLUN, YD%F_NEB)
ELSE
  NULLIFY (YD%F_NEB)
ENDIF
NULLIFY (YD%QLI)
READ (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL LOAD (KLUN, YD%F_QLI)
ELSE
  NULLIFY (YD%F_QLI)
ENDIF
NULLIFY (YD%QICE)
READ (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL LOAD (KLUN, YD%F_QICE)
ELSE
  NULLIFY (YD%F_QICE)
ENDIF
NULLIFY (YD%QRAIN)
READ (KLUN) LF_QRAIN
IF (LF_QRAIN) THEN
  CALL LOAD (KLUN, YD%F_QRAIN)
ELSE
  NULLIFY (YD%F_QRAIN)
ENDIF
NULLIFY (YD%QSNOW)
READ (KLUN) LF_QSNOW
IF (LF_QSNOW) THEN
  CALL LOAD (KLUN, YD%F_QSNOW)
ELSE
  NULLIFY (YD%F_QSNOW)
ENDIF
NULLIFY (YD%QGRAUPEL)
READ (KLUN) LF_QGRAUPEL
IF (LF_QGRAUPEL) THEN
  CALL LOAD (KLUN, YD%F_QGRAUPEL)
ELSE
  NULLIFY (YD%F_QGRAUPEL)
ENDIF
NULLIFY (YD%RH)
READ (KLUN) LF_RH
IF (LF_RH) THEN
  CALL LOAD (KLUN, YD%F_RH)
ELSE
  NULLIFY (YD%F_RH)
ENDIF
NULLIFY (YD%QS)
READ (KLUN) LF_QS
IF (LF_QS) THEN
  CALL LOAD (KLUN, YD%F_QS)
ELSE
  NULLIFY (YD%F_QS)
ENDIF
NULLIFY (YD%QSOL)
READ (KLUN) LF_QSOL
IF (LF_QSOL) THEN
  CALL LOAD (KLUN, YD%F_QSOL)
ELSE
  NULLIFY (YD%F_QSOL)
ENDIF
NULLIFY (YD%DHSF)
READ (KLUN) LF_DHSF
IF (LF_DHSF) THEN
  CALL LOAD (KLUN, YD%F_DHSF)
ELSE
  NULLIFY (YD%F_DHSF)
ENDIF
NULLIFY (YD%CLCT)
READ (KLUN) LF_CLCT
IF (LF_CLCT) THEN
  CALL LOAD (KLUN, YD%F_CLCT)
ELSE
  NULLIFY (YD%F_CLCT)
ENDIF
NULLIFY (YD%LSM)
READ (KLUN) LF_LSM
IF (LF_LSM) THEN
  CALL LOAD (KLUN, YD%F_LSM)
ELSE
  NULLIFY (YD%F_LSM)
ENDIF
NULLIFY (YD%TSOL)
READ (KLUN) LF_TSOL
IF (LF_TSOL) THEN
  CALL LOAD (KLUN, YD%F_TSOL)
ELSE
  NULLIFY (YD%F_TSOL)
ENDIF
NULLIFY (YD%FTCNS)
READ (KLUN) LF_FTCNS
IF (LF_FTCNS) THEN
  CALL LOAD (KLUN, YD%F_FTCNS)
ELSE
  NULLIFY (YD%F_FTCNS)
ENDIF
NULLIFY (YD%KOZO)
READ (KLUN) LF_KOZO
IF (LF_KOZO) THEN
  CALL LOAD (KLUN, YD%F_KOZO)
ELSE
  NULLIFY (YD%F_KOZO)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_CPG_MISC_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (CPG_MISC_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN
LOGICAL :: LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LF_NEB = ASSOCIATED (YD%F_NEB)
IF (LF_NEB) THEN
  !$acc enter data create (YD%F_NEB)
  !$acc update device (YD%F_NEB)
  CALL COPY (YD%F_NEB, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_NEB)
ENDIF

LF_QLI = ASSOCIATED (YD%F_QLI)
IF (LF_QLI) THEN
  !$acc enter data create (YD%F_QLI)
  !$acc update device (YD%F_QLI)
  CALL COPY (YD%F_QLI, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QLI)
ENDIF

LF_QICE = ASSOCIATED (YD%F_QICE)
IF (LF_QICE) THEN
  !$acc enter data create (YD%F_QICE)
  !$acc update device (YD%F_QICE)
  CALL COPY (YD%F_QICE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QICE)
ENDIF

LF_QRAIN = ASSOCIATED (YD%F_QRAIN)
IF (LF_QRAIN) THEN
  !$acc enter data create (YD%F_QRAIN)
  !$acc update device (YD%F_QRAIN)
  CALL COPY (YD%F_QRAIN, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QRAIN)
ENDIF

LF_QSNOW = ASSOCIATED (YD%F_QSNOW)
IF (LF_QSNOW) THEN
  !$acc enter data create (YD%F_QSNOW)
  !$acc update device (YD%F_QSNOW)
  CALL COPY (YD%F_QSNOW, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QSNOW)
ENDIF

LF_QGRAUPEL = ASSOCIATED (YD%F_QGRAUPEL)
IF (LF_QGRAUPEL) THEN
  !$acc enter data create (YD%F_QGRAUPEL)
  !$acc update device (YD%F_QGRAUPEL)
  CALL COPY (YD%F_QGRAUPEL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QGRAUPEL)
ENDIF

LF_RH = ASSOCIATED (YD%F_RH)
IF (LF_RH) THEN
  !$acc enter data create (YD%F_RH)
  !$acc update device (YD%F_RH)
  CALL COPY (YD%F_RH, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_RH)
ENDIF

LF_QS = ASSOCIATED (YD%F_QS)
IF (LF_QS) THEN
  !$acc enter data create (YD%F_QS)
  !$acc update device (YD%F_QS)
  CALL COPY (YD%F_QS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QS)
ENDIF

LF_QSOL = ASSOCIATED (YD%F_QSOL)
IF (LF_QSOL) THEN
  !$acc enter data create (YD%F_QSOL)
  !$acc update device (YD%F_QSOL)
  CALL COPY (YD%F_QSOL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_QSOL)
ENDIF

LF_DHSF = ASSOCIATED (YD%F_DHSF)
IF (LF_DHSF) THEN
  !$acc enter data create (YD%F_DHSF)
  !$acc update device (YD%F_DHSF)
  CALL COPY (YD%F_DHSF, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_DHSF)
ENDIF

LF_CLCT = ASSOCIATED (YD%F_CLCT)
IF (LF_CLCT) THEN
  !$acc enter data create (YD%F_CLCT)
  !$acc update device (YD%F_CLCT)
  CALL COPY (YD%F_CLCT, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_CLCT)
ENDIF

LF_LSM = ASSOCIATED (YD%F_LSM)
IF (LF_LSM) THEN
  !$acc enter data create (YD%F_LSM)
  !$acc update device (YD%F_LSM)
  CALL COPY (YD%F_LSM, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_LSM)
ENDIF

LF_TSOL = ASSOCIATED (YD%F_TSOL)
IF (LF_TSOL) THEN
  !$acc enter data create (YD%F_TSOL)
  !$acc update device (YD%F_TSOL)
  CALL COPY (YD%F_TSOL, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_TSOL)
ENDIF

LF_FTCNS = ASSOCIATED (YD%F_FTCNS)
IF (LF_FTCNS) THEN
  !$acc enter data create (YD%F_FTCNS)
  !$acc update device (YD%F_FTCNS)
  CALL COPY (YD%F_FTCNS, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_FTCNS)
ENDIF

LF_KOZO = ASSOCIATED (YD%F_KOZO)
IF (LF_KOZO) THEN
  !$acc enter data create (YD%F_KOZO)
  !$acc update device (YD%F_KOZO)
  CALL COPY (YD%F_KOZO, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%F_KOZO)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_CPG_MISC_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (CPG_MISC_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN
LOGICAL :: LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL

LF_NEB = ASSOCIATED (YD%F_NEB)
IF (LF_NEB) THEN
  !$acc exit data detach (YD%F_NEB)
  CALL WIPE (YD%F_NEB, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_NEB)
ENDIF

LF_QLI = ASSOCIATED (YD%F_QLI)
IF (LF_QLI) THEN
  !$acc exit data detach (YD%F_QLI)
  CALL WIPE (YD%F_QLI, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QLI)
ENDIF

LF_QICE = ASSOCIATED (YD%F_QICE)
IF (LF_QICE) THEN
  !$acc exit data detach (YD%F_QICE)
  CALL WIPE (YD%F_QICE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QICE)
ENDIF

LF_QRAIN = ASSOCIATED (YD%F_QRAIN)
IF (LF_QRAIN) THEN
  !$acc exit data detach (YD%F_QRAIN)
  CALL WIPE (YD%F_QRAIN, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QRAIN)
ENDIF

LF_QSNOW = ASSOCIATED (YD%F_QSNOW)
IF (LF_QSNOW) THEN
  !$acc exit data detach (YD%F_QSNOW)
  CALL WIPE (YD%F_QSNOW, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QSNOW)
ENDIF

LF_QGRAUPEL = ASSOCIATED (YD%F_QGRAUPEL)
IF (LF_QGRAUPEL) THEN
  !$acc exit data detach (YD%F_QGRAUPEL)
  CALL WIPE (YD%F_QGRAUPEL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QGRAUPEL)
ENDIF

LF_RH = ASSOCIATED (YD%F_RH)
IF (LF_RH) THEN
  !$acc exit data detach (YD%F_RH)
  CALL WIPE (YD%F_RH, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_RH)
ENDIF

LF_QS = ASSOCIATED (YD%F_QS)
IF (LF_QS) THEN
  !$acc exit data detach (YD%F_QS)
  CALL WIPE (YD%F_QS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QS)
ENDIF

LF_QSOL = ASSOCIATED (YD%F_QSOL)
IF (LF_QSOL) THEN
  !$acc exit data detach (YD%F_QSOL)
  CALL WIPE (YD%F_QSOL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_QSOL)
ENDIF

LF_DHSF = ASSOCIATED (YD%F_DHSF)
IF (LF_DHSF) THEN
  !$acc exit data detach (YD%F_DHSF)
  CALL WIPE (YD%F_DHSF, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_DHSF)
ENDIF

LF_CLCT = ASSOCIATED (YD%F_CLCT)
IF (LF_CLCT) THEN
  !$acc exit data detach (YD%F_CLCT)
  CALL WIPE (YD%F_CLCT, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_CLCT)
ENDIF

LF_LSM = ASSOCIATED (YD%F_LSM)
IF (LF_LSM) THEN
  !$acc exit data detach (YD%F_LSM)
  CALL WIPE (YD%F_LSM, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_LSM)
ENDIF

LF_TSOL = ASSOCIATED (YD%F_TSOL)
IF (LF_TSOL) THEN
  !$acc exit data detach (YD%F_TSOL)
  CALL WIPE (YD%F_TSOL, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_TSOL)
ENDIF

LF_FTCNS = ASSOCIATED (YD%F_FTCNS)
IF (LF_FTCNS) THEN
  !$acc exit data detach (YD%F_FTCNS)
  CALL WIPE (YD%F_FTCNS, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_FTCNS)
ENDIF

LF_KOZO = ASSOCIATED (YD%F_KOZO)
IF (LF_KOZO) THEN
  !$acc exit data detach (YD%F_KOZO)
  CALL WIPE (YD%F_KOZO, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%F_KOZO)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
