MODULE UTIL_TSIMPHL_MOD

USE YOMSIMPHL, ONLY : TSIMPHL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSIMPHL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSIMPHL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSIMPHL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSIMPHL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSIMPHL), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LSIMPH
WRITE (KLUN) YD%LTRAJPS
WRITE (KLUN) YD%LTRAJPST
WRITE (KLUN) YD%LSMOOTHD
WRITE (KLUN) YD%LSMOOTHA
WRITE (KLUN) YD%LSMOOTHB
WRITE (KLUN) YD%LCVRASP
WRITE (KLUN) YD%LGWDSP
WRITE (KLUN) YD%LRAYSP
WRITE (KLUN) YD%LSTRASP
WRITE (KLUN) YD%LVDIFSP
WRITE (KLUN) YD%LVDIFSPNL
WRITE (KLUN) YD%LRRMESSP
WRITE (KLUN) YD%LCLOUDS
WRITE (KLUN) YD%LGWDSPNL
WRITE (KLUN) YD%LSTRASPN
WRITE (KLUN) YD%LPROCLDTL
WRITE (KLUN) YD%LMELTTL
WRITE (KLUN) YD%LMELTNL
WRITE (KLUN) YD%LMICROTL
WRITE (KLUN) YD%LTRAJRAIN
WRITE (KLUN) YD%LTRAJCOND
WRITE (KLUN) YD%LNEBCVPPKF
WRITE (KLUN) YD%LCOLLECTL
WRITE (KLUN) YD%LEVAPTL
WRITE (KLUN) YD%LSMOOTHEVP
WRITE (KLUN) YD%LIGELREPRO
WRITE (KLUN) YD%LCVRASBM
WRITE (KLUN) YD%LCONSENTH
WRITE (KLUN) YD%LAPPROXCONV
WRITE (KLUN) YD%RHCRIT1S
WRITE (KLUN) YD%RHCRIT2S
WRITE (KLUN) YD%TADJ
WRITE (KLUN) YD%RMINEVP
WRITE (KLUN) YD%DELTAH
WRITE (KLUN) YD%RMODULQCPROG
END SUBROUTINE

SUBROUTINE LOAD_TSIMPHL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSIMPHL), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LSIMPH
READ (KLUN) YD%LTRAJPS
READ (KLUN) YD%LTRAJPST
READ (KLUN) YD%LSMOOTHD
READ (KLUN) YD%LSMOOTHA
READ (KLUN) YD%LSMOOTHB
READ (KLUN) YD%LCVRASP
READ (KLUN) YD%LGWDSP
READ (KLUN) YD%LRAYSP
READ (KLUN) YD%LSTRASP
READ (KLUN) YD%LVDIFSP
READ (KLUN) YD%LVDIFSPNL
READ (KLUN) YD%LRRMESSP
READ (KLUN) YD%LCLOUDS
READ (KLUN) YD%LGWDSPNL
READ (KLUN) YD%LSTRASPN
READ (KLUN) YD%LPROCLDTL
READ (KLUN) YD%LMELTTL
READ (KLUN) YD%LMELTNL
READ (KLUN) YD%LMICROTL
READ (KLUN) YD%LTRAJRAIN
READ (KLUN) YD%LTRAJCOND
READ (KLUN) YD%LNEBCVPPKF
READ (KLUN) YD%LCOLLECTL
READ (KLUN) YD%LEVAPTL
READ (KLUN) YD%LSMOOTHEVP
READ (KLUN) YD%LIGELREPRO
READ (KLUN) YD%LCVRASBM
READ (KLUN) YD%LCONSENTH
READ (KLUN) YD%LAPPROXCONV
READ (KLUN) YD%RHCRIT1S
READ (KLUN) YD%RHCRIT2S
READ (KLUN) YD%TADJ
READ (KLUN) YD%RMINEVP
READ (KLUN) YD%DELTAH
READ (KLUN) YD%RMODULQCPROG
END SUBROUTINE


SUBROUTINE COPY_TSIMPHL (YD, LDCREATED)

IMPLICIT NONE
TYPE (TSIMPHL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




































END SUBROUTINE



END MODULE
