MODULE UTIL_TLDDH_MOD

USE YOMLDDH, ONLY : TLDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLDDH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TLDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLDDH), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LSDDH
WRITE (KLUN) YD%LHDGLB
WRITE (KLUN) YD%LHDZON
WRITE (KLUN) YD%LHDDOP
WRITE (KLUN) YD%LHDLFA
WRITE (KLUN) YD%LHDHKS
WRITE (KLUN) YD%LHDMCI
WRITE (KLUN) YD%LHDENT
WRITE (KLUN) YD%LHDPRG
WRITE (KLUN) YD%LHDPRZ
WRITE (KLUN) YD%LHDPRD
WRITE (KLUN) YD%LHDPR
WRITE (KLUN) YD%LHDEFG
WRITE (KLUN) YD%LHDEFZ
WRITE (KLUN) YD%LHDEFD
WRITE (KLUN) YD%LHDLIST
WRITE (KLUN) YD%LHDOUFG
WRITE (KLUN) YD%LHDOUFZ
WRITE (KLUN) YD%LHDOUFD
WRITE (KLUN) YD%LHDOUP
WRITE (KLUN) YD%LHDFIL
WRITE (KLUN) YD%LONLYVAR
WRITE (KLUN) YD%LHDORIGP
WRITE (KLUN) YD%LHDCDPI
WRITE (KLUN) YD%LFLEXDIA
WRITE (KLUN) YD%LRDDHDYN
WRITE (KLUN) YD%LRSLDDH
WRITE (KLUN) YD%LRSIDDH
WRITE (KLUN) YD%LRHDDDH
WRITE (KLUN) YD%LDDH_OMP
END SUBROUTINE
SUBROUTINE LOAD_TLDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLDDH), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LSDDH
READ (KLUN) YD%LHDGLB
READ (KLUN) YD%LHDZON
READ (KLUN) YD%LHDDOP
READ (KLUN) YD%LHDLFA
READ (KLUN) YD%LHDHKS
READ (KLUN) YD%LHDMCI
READ (KLUN) YD%LHDENT
READ (KLUN) YD%LHDPRG
READ (KLUN) YD%LHDPRZ
READ (KLUN) YD%LHDPRD
READ (KLUN) YD%LHDPR
READ (KLUN) YD%LHDEFG
READ (KLUN) YD%LHDEFZ
READ (KLUN) YD%LHDEFD
READ (KLUN) YD%LHDLIST
READ (KLUN) YD%LHDOUFG
READ (KLUN) YD%LHDOUFZ
READ (KLUN) YD%LHDOUFD
READ (KLUN) YD%LHDOUP
READ (KLUN) YD%LHDFIL
READ (KLUN) YD%LONLYVAR
READ (KLUN) YD%LHDORIGP
READ (KLUN) YD%LHDCDPI
READ (KLUN) YD%LFLEXDIA
READ (KLUN) YD%LRDDHDYN
READ (KLUN) YD%LRSLDDH
READ (KLUN) YD%LRSIDDH
READ (KLUN) YD%LRHDDDH
READ (KLUN) YD%LDDH_OMP
END SUBROUTINE




END MODULE
