MODULE UTIL_TTDDH_MOD

USE YOMTDDH, ONLY : TTDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTDDH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TTDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LCFLDNAMES2D, LCFLDNAMES3D, LCFLDTYPES2D, LCFLDTYPES3D, LHDCS0, LHDCS1, LHDCVB0, LHDCVB1, LPDDHFSVI
LHDCVB0 = ALLOCATED (YD%HDCVB0)
WRITE (KLUN) LHDCVB0
IF (LHDCVB0) THEN
  WRITE (KLUN) LBOUND (YD%HDCVB0)
  WRITE (KLUN) UBOUND (YD%HDCVB0)
  WRITE (KLUN) YD%HDCVB0
ENDIF
LHDCVB1 = ALLOCATED (YD%HDCVB1)
WRITE (KLUN) LHDCVB1
IF (LHDCVB1) THEN
  WRITE (KLUN) LBOUND (YD%HDCVB1)
  WRITE (KLUN) UBOUND (YD%HDCVB1)
  WRITE (KLUN) YD%HDCVB1
ENDIF
LHDCS0 = ALLOCATED (YD%HDCS0)
WRITE (KLUN) LHDCS0
IF (LHDCS0) THEN
  WRITE (KLUN) LBOUND (YD%HDCS0)
  WRITE (KLUN) UBOUND (YD%HDCS0)
  WRITE (KLUN) YD%HDCS0
ENDIF
LHDCS1 = ALLOCATED (YD%HDCS1)
WRITE (KLUN) LHDCS1
IF (LHDCS1) THEN
  WRITE (KLUN) LBOUND (YD%HDCS1)
  WRITE (KLUN) UBOUND (YD%HDCS1)
  WRITE (KLUN) YD%HDCS1
ENDIF
LPDDHFSVI = ALLOCATED (YD%PDDHFSVI)
WRITE (KLUN) LPDDHFSVI
IF (LPDDHFSVI) THEN
  WRITE (KLUN) LBOUND (YD%PDDHFSVI)
  WRITE (KLUN) UBOUND (YD%PDDHFSVI)
  WRITE (KLUN) YD%PDDHFSVI
ENDIF
LCFLDNAMES3D = ALLOCATED (YD%CFLDNAMES3D)
WRITE (KLUN) LCFLDNAMES3D
IF (LCFLDNAMES3D) THEN
  WRITE (KLUN) LBOUND (YD%CFLDNAMES3D)
  WRITE (KLUN) UBOUND (YD%CFLDNAMES3D)
  WRITE (KLUN) YD%CFLDNAMES3D
ENDIF
LCFLDTYPES3D = ALLOCATED (YD%CFLDTYPES3D)
WRITE (KLUN) LCFLDTYPES3D
IF (LCFLDTYPES3D) THEN
  WRITE (KLUN) LBOUND (YD%CFLDTYPES3D)
  WRITE (KLUN) UBOUND (YD%CFLDTYPES3D)
  WRITE (KLUN) YD%CFLDTYPES3D
ENDIF
LCFLDNAMES2D = ALLOCATED (YD%CFLDNAMES2D)
WRITE (KLUN) LCFLDNAMES2D
IF (LCFLDNAMES2D) THEN
  WRITE (KLUN) LBOUND (YD%CFLDNAMES2D)
  WRITE (KLUN) UBOUND (YD%CFLDNAMES2D)
  WRITE (KLUN) YD%CFLDNAMES2D
ENDIF
LCFLDTYPES2D = ALLOCATED (YD%CFLDTYPES2D)
WRITE (KLUN) LCFLDTYPES2D
IF (LCFLDTYPES2D) THEN
  WRITE (KLUN) LBOUND (YD%CFLDTYPES2D)
  WRITE (KLUN) UBOUND (YD%CFLDTYPES2D)
  WRITE (KLUN) YD%CFLDTYPES2D
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TTDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3)
LOGICAL :: LCFLDNAMES2D, LCFLDNAMES3D, LCFLDTYPES2D, LCFLDTYPES3D, LHDCS0, LHDCS1, LHDCVB0, LHDCVB1, LPDDHFSVI
READ (KLUN) LHDCVB0
IF (LHDCVB0) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%HDCVB0 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%HDCVB0
ENDIF
READ (KLUN) LHDCVB1
IF (LHDCVB1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%HDCVB1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%HDCVB1
ENDIF
READ (KLUN) LHDCS0
IF (LHDCS0) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%HDCS0 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%HDCS0
ENDIF
READ (KLUN) LHDCS1
IF (LHDCS1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%HDCS1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%HDCS1
ENDIF
READ (KLUN) LPDDHFSVI
IF (LPDDHFSVI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PDDHFSVI (IL1(1):IU1(1)))
  READ (KLUN) YD%PDDHFSVI
ENDIF
READ (KLUN) LCFLDNAMES3D
IF (LCFLDNAMES3D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CFLDNAMES3D (IL1(1):IU1(1)))
  READ (KLUN) YD%CFLDNAMES3D
ENDIF
READ (KLUN) LCFLDTYPES3D
IF (LCFLDTYPES3D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CFLDTYPES3D (IL1(1):IU1(1)))
  READ (KLUN) YD%CFLDTYPES3D
ENDIF
READ (KLUN) LCFLDNAMES2D
IF (LCFLDNAMES2D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CFLDNAMES2D (IL1(1):IU1(1)))
  READ (KLUN) YD%CFLDNAMES2D
ENDIF
READ (KLUN) LCFLDTYPES2D
IF (LCFLDTYPES2D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CFLDTYPES2D (IL1(1):IU1(1)))
  READ (KLUN) YD%CFLDTYPES2D
ENDIF
END SUBROUTINE




END MODULE
