MODULE UTIL_TTOPH_MOD

USE YOMTOPH, ONLY : TTOPH


INTERFACE SAVE
MODULE PROCEDURE SAVE_TTOPH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTOPH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TTOPH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TTOPH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TTOPH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TTOPH), INTENT (IN), TARGET :: YD
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL

LRMESOU = ALLOCATED (YD%RMESOU)
WRITE (KLUN) LRMESOU
IF (LRMESOU) THEN
  WRITE (KLUN) LBOUND (YD%RMESOU)
  WRITE (KLUN) UBOUND (YD%RMESOU)
  WRITE (KLUN) YD%RMESOU
ENDIF
LRMESOT = ALLOCATED (YD%RMESOT)
WRITE (KLUN) LRMESOT
IF (LRMESOT) THEN
  WRITE (KLUN) LBOUND (YD%RMESOT)
  WRITE (KLUN) UBOUND (YD%RMESOT)
  WRITE (KLUN) YD%RMESOT
ENDIF
LRMESOQ = ALLOCATED (YD%RMESOQ)
WRITE (KLUN) LRMESOQ
IF (LRMESOQ) THEN
  WRITE (KLUN) LBOUND (YD%RMESOQ)
  WRITE (KLUN) UBOUND (YD%RMESOQ)
  WRITE (KLUN) YD%RMESOQ
ENDIF
LRUREL = ALLOCATED (YD%RUREL)
WRITE (KLUN) LRUREL
IF (LRUREL) THEN
  WRITE (KLUN) LBOUND (YD%RUREL)
  WRITE (KLUN) UBOUND (YD%RUREL)
  WRITE (KLUN) YD%RUREL
ENDIF
LRVREL = ALLOCATED (YD%RVREL)
WRITE (KLUN) LRVREL
IF (LRVREL) THEN
  WRITE (KLUN) LBOUND (YD%RVREL)
  WRITE (KLUN) UBOUND (YD%RVREL)
  WRITE (KLUN) YD%RVREL
ENDIF
LRTREL = ALLOCATED (YD%RTREL)
WRITE (KLUN) LRTREL
IF (LRTREL) THEN
  WRITE (KLUN) LBOUND (YD%RTREL)
  WRITE (KLUN) UBOUND (YD%RTREL)
  WRITE (KLUN) YD%RTREL
ENDIF
LRQREL = ALLOCATED (YD%RQREL)
WRITE (KLUN) LRQREL
IF (LRQREL) THEN
  WRITE (KLUN) LBOUND (YD%RQREL)
  WRITE (KLUN) UBOUND (YD%RQREL)
  WRITE (KLUN) YD%RQREL
ENDIF
WRITE (KLUN) YD%RFMESOQ
WRITE (KLUN) YD%NTQSAT
WRITE (KLUN) YD%NTDIFU
WRITE (KLUN) YD%NTCOEF
WRITE (KLUN) YD%NTDRAG
WRITE (KLUN) YD%NTCVIM
WRITE (KLUN) YD%NT850
WRITE (KLUN) YD%NT950
WRITE (KLUN) YD%NTPLUI
WRITE (KLUN) YD%NTRADI
WRITE (KLUN) YD%NTNEBU
WRITE (KLUN) YD%NTOZON
WRITE (KLUN) YD%NTDRME
WRITE (KLUN) YD%NTCOET
WRITE (KLUN) YD%NTAJUC
WRITE (KLUN) YD%NTRELAXT
WRITE (KLUN) YD%NTRELAXQ
WRITE (KLUN) YD%NTRELAXU
WRITE (KLUN) YD%ETQSAT
WRITE (KLUN) YD%ETDIFU
WRITE (KLUN) YD%ETCOEF
WRITE (KLUN) YD%ETDRAG
WRITE (KLUN) YD%ETCVIM
WRITE (KLUN) YD%ET850
WRITE (KLUN) YD%ET950
WRITE (KLUN) YD%ETPLUI
WRITE (KLUN) YD%ETRADI
WRITE (KLUN) YD%ETNEBU
WRITE (KLUN) YD%ETOZON
WRITE (KLUN) YD%ETDRME
WRITE (KLUN) YD%ETCOET
WRITE (KLUN) YD%ETAJUC
WRITE (KLUN) YD%ETRELAXT
WRITE (KLUN) YD%ETRELAXQ
WRITE (KLUN) YD%ETRELAXU
WRITE (KLUN) YD%XDRMUK
WRITE (KLUN) YD%XDRMUX
WRITE (KLUN) YD%XDRMUP
WRITE (KLUN) YD%XDRMTK
WRITE (KLUN) YD%XDRMTX
WRITE (KLUN) YD%XDRMTP
WRITE (KLUN) YD%XDRMQK
WRITE (KLUN) YD%XDRMQP
WRITE (KLUN) YD%XDRMQX
WRITE (KLUN) YD%RCLX
WRITE (KLUN) YD%TPSCLIM
END SUBROUTINE

SUBROUTINE LOAD_TTOPH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TTOPH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL

READ (KLUN) LRMESOU
IF (LRMESOU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOU
ENDIF
READ (KLUN) LRMESOT
IF (LRMESOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOT (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOT
ENDIF
READ (KLUN) LRMESOQ
IF (LRMESOQ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOQ (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOQ
ENDIF
READ (KLUN) LRUREL
IF (LRUREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RUREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RUREL
ENDIF
READ (KLUN) LRVREL
IF (LRVREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RVREL
ENDIF
READ (KLUN) LRTREL
IF (LRTREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RTREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RTREL
ENDIF
READ (KLUN) LRQREL
IF (LRQREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RQREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RQREL
ENDIF
READ (KLUN) YD%RFMESOQ
READ (KLUN) YD%NTQSAT
READ (KLUN) YD%NTDIFU
READ (KLUN) YD%NTCOEF
READ (KLUN) YD%NTDRAG
READ (KLUN) YD%NTCVIM
READ (KLUN) YD%NT850
READ (KLUN) YD%NT950
READ (KLUN) YD%NTPLUI
READ (KLUN) YD%NTRADI
READ (KLUN) YD%NTNEBU
READ (KLUN) YD%NTOZON
READ (KLUN) YD%NTDRME
READ (KLUN) YD%NTCOET
READ (KLUN) YD%NTAJUC
READ (KLUN) YD%NTRELAXT
READ (KLUN) YD%NTRELAXQ
READ (KLUN) YD%NTRELAXU
READ (KLUN) YD%ETQSAT
READ (KLUN) YD%ETDIFU
READ (KLUN) YD%ETCOEF
READ (KLUN) YD%ETDRAG
READ (KLUN) YD%ETCVIM
READ (KLUN) YD%ET850
READ (KLUN) YD%ET950
READ (KLUN) YD%ETPLUI
READ (KLUN) YD%ETRADI
READ (KLUN) YD%ETNEBU
READ (KLUN) YD%ETOZON
READ (KLUN) YD%ETDRME
READ (KLUN) YD%ETCOET
READ (KLUN) YD%ETAJUC
READ (KLUN) YD%ETRELAXT
READ (KLUN) YD%ETRELAXQ
READ (KLUN) YD%ETRELAXU
READ (KLUN) YD%XDRMUK
READ (KLUN) YD%XDRMUX
READ (KLUN) YD%XDRMUP
READ (KLUN) YD%XDRMTK
READ (KLUN) YD%XDRMTX
READ (KLUN) YD%XDRMTP
READ (KLUN) YD%XDRMQK
READ (KLUN) YD%XDRMQP
READ (KLUN) YD%XDRMQX
READ (KLUN) YD%RCLX
READ (KLUN) YD%TPSCLIM
END SUBROUTINE


SUBROUTINE COPY_TTOPH (YD, LDCREATED)
IMPLICIT NONE
CLASS (TTOPH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRMESOU = ALLOCATED (YD%RMESOU)
IF (LRMESOU) THEN
  !$acc enter data create (YD%RMESOU)
  !$acc update device (YD%RMESOU)
  !$acc enter data attach (YD%RMESOU)
ENDIF

LRMESOT = ALLOCATED (YD%RMESOT)
IF (LRMESOT) THEN
  !$acc enter data create (YD%RMESOT)
  !$acc update device (YD%RMESOT)
  !$acc enter data attach (YD%RMESOT)
ENDIF

LRMESOQ = ALLOCATED (YD%RMESOQ)
IF (LRMESOQ) THEN
  !$acc enter data create (YD%RMESOQ)
  !$acc update device (YD%RMESOQ)
  !$acc enter data attach (YD%RMESOQ)
ENDIF

LRUREL = ALLOCATED (YD%RUREL)
IF (LRUREL) THEN
  !$acc enter data create (YD%RUREL)
  !$acc update device (YD%RUREL)
  !$acc enter data attach (YD%RUREL)
ENDIF

LRVREL = ALLOCATED (YD%RVREL)
IF (LRVREL) THEN
  !$acc enter data create (YD%RVREL)
  !$acc update device (YD%RVREL)
  !$acc enter data attach (YD%RVREL)
ENDIF

LRTREL = ALLOCATED (YD%RTREL)
IF (LRTREL) THEN
  !$acc enter data create (YD%RTREL)
  !$acc update device (YD%RTREL)
  !$acc enter data attach (YD%RTREL)
ENDIF

LRQREL = ALLOCATED (YD%RQREL)
IF (LRQREL) THEN
  !$acc enter data create (YD%RQREL)
  !$acc update device (YD%RQREL)
  !$acc enter data attach (YD%RQREL)
ENDIF















































END SUBROUTINE

SUBROUTINE WIPE_TTOPH (YD, LDDELETED)
IMPLICIT NONE
CLASS (TTOPH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL

LRMESOU = ALLOCATED (YD%RMESOU)
IF (LRMESOU) THEN
  !$acc exit data detach (YD%RMESOU)
  !$acc exit data delete (YD%RMESOU)
ENDIF

LRMESOT = ALLOCATED (YD%RMESOT)
IF (LRMESOT) THEN
  !$acc exit data detach (YD%RMESOT)
  !$acc exit data delete (YD%RMESOT)
ENDIF

LRMESOQ = ALLOCATED (YD%RMESOQ)
IF (LRMESOQ) THEN
  !$acc exit data detach (YD%RMESOQ)
  !$acc exit data delete (YD%RMESOQ)
ENDIF

LRUREL = ALLOCATED (YD%RUREL)
IF (LRUREL) THEN
  !$acc exit data detach (YD%RUREL)
  !$acc exit data delete (YD%RUREL)
ENDIF

LRVREL = ALLOCATED (YD%RVREL)
IF (LRVREL) THEN
  !$acc exit data detach (YD%RVREL)
  !$acc exit data delete (YD%RVREL)
ENDIF

LRTREL = ALLOCATED (YD%RTREL)
IF (LRTREL) THEN
  !$acc exit data detach (YD%RTREL)
  !$acc exit data delete (YD%RTREL)
ENDIF

LRQREL = ALLOCATED (YD%RQREL)
IF (LRQREL) THEN
  !$acc exit data detach (YD%RQREL)
  !$acc exit data delete (YD%RQREL)
ENDIF















































LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
