MODULE UTIL_TSPGEOM_MOD

USE TYPE_SPGEOM, ONLY : TSPGEOM


INTERFACE SAVE
MODULE PROCEDURE SAVE_TSPGEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSPGEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSPGEOM
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSPGEOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSPGEOM (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPGEOM), INTENT (IN), TARGET :: YD
LOGICAL :: LGMR, LSCGMAP

LGMR = ALLOCATED (YD%GMR)
WRITE (KLUN) LGMR
IF (LGMR) THEN
  WRITE (KLUN) LBOUND (YD%GMR)
  WRITE (KLUN) UBOUND (YD%GMR)
  WRITE (KLUN) YD%GMR
ENDIF
LSCGMAP = ALLOCATED (YD%SCGMAP)
WRITE (KLUN) LSCGMAP
IF (LSCGMAP) THEN
  WRITE (KLUN) LBOUND (YD%SCGMAP)
  WRITE (KLUN) UBOUND (YD%SCGMAP)
  WRITE (KLUN) YD%SCGMAP
ENDIF
WRITE (KLUN) YD%ESCGMAP
END SUBROUTINE

SUBROUTINE LOAD_TSPGEOM (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPGEOM), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LGMR, LSCGMAP

READ (KLUN) LGMR
IF (LGMR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GMR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GMR
ENDIF
READ (KLUN) LSCGMAP
IF (LSCGMAP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SCGMAP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SCGMAP
ENDIF
READ (KLUN) YD%ESCGMAP
END SUBROUTINE


SUBROUTINE COPY_TSPGEOM (YD, LDCREATED)
IMPLICIT NONE
TYPE (TSPGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LGMR, LSCGMAP

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LGMR = ALLOCATED (YD%GMR)
IF (LGMR) THEN
  !$acc enter data create (YD%GMR)
  !$acc update device (YD%GMR)
  !$acc enter data attach (YD%GMR)
ENDIF

LSCGMAP = ALLOCATED (YD%SCGMAP)
IF (LSCGMAP) THEN
  !$acc enter data create (YD%SCGMAP)
  !$acc update device (YD%SCGMAP)
  !$acc enter data attach (YD%SCGMAP)
ENDIF


END SUBROUTINE

SUBROUTINE WIPE_TSPGEOM (YD, LDDELETED)
IMPLICIT NONE
TYPE (TSPGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LGMR, LSCGMAP

LGMR = ALLOCATED (YD%GMR)
IF (LGMR) THEN
  !$acc exit data detach (YD%GMR)
  !$acc exit data delete (YD%GMR)
ENDIF

LSCGMAP = ALLOCATED (YD%SCGMAP)
IF (LSCGMAP) THEN
  !$acc exit data detach (YD%SCGMAP)
  !$acc exit data delete (YD%SCGMAP)
ENDIF


LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
