MODULE UTIL_TENEUR_MOD

USE YOENEUR, ONLY : TENEUR

INTERFACE SAVE
MODULE PROCEDURE SAVE_TENEUR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TENEUR
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TENEUR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TENEUR), INTENT (IN), TARGET :: YD
LOGICAL :: LAAM_NN, LBBM_NN, LENTREEMOY, LNBNEUR, LPDFSDX, LRAPIN, LRAPOUT, LSORTIEMOY, LWNELN
WRITE (KLUN) YD%NCOU
WRITE (KLUN) YD%NBR
WRITE (KLUN) YD%NBNEURMAX
WRITE (KLUN) YD%KLEV_NN
LNBNEUR = ALLOCATED (YD%NBNEUR)
WRITE (KLUN) LNBNEUR
IF (LNBNEUR) THEN
  WRITE (KLUN) LBOUND (YD%NBNEUR)
  WRITE (KLUN) UBOUND (YD%NBNEUR)
  WRITE (KLUN) YD%NBNEUR
ENDIF
LWNELN = ALLOCATED (YD%WNELN)
WRITE (KLUN) LWNELN
IF (LWNELN) THEN
  WRITE (KLUN) LBOUND (YD%WNELN)
  WRITE (KLUN) UBOUND (YD%WNELN)
  WRITE (KLUN) YD%WNELN
ENDIF
LENTREEMOY = ALLOCATED (YD%ENTREEMOY)
WRITE (KLUN) LENTREEMOY
IF (LENTREEMOY) THEN
  WRITE (KLUN) LBOUND (YD%ENTREEMOY)
  WRITE (KLUN) UBOUND (YD%ENTREEMOY)
  WRITE (KLUN) YD%ENTREEMOY
ENDIF
LRAPIN = ALLOCATED (YD%RAPIN)
WRITE (KLUN) LRAPIN
IF (LRAPIN) THEN
  WRITE (KLUN) LBOUND (YD%RAPIN)
  WRITE (KLUN) UBOUND (YD%RAPIN)
  WRITE (KLUN) YD%RAPIN
ENDIF
LSORTIEMOY = ALLOCATED (YD%SORTIEMOY)
WRITE (KLUN) LSORTIEMOY
IF (LSORTIEMOY) THEN
  WRITE (KLUN) LBOUND (YD%SORTIEMOY)
  WRITE (KLUN) UBOUND (YD%SORTIEMOY)
  WRITE (KLUN) YD%SORTIEMOY
ENDIF
LRAPOUT = ALLOCATED (YD%RAPOUT)
WRITE (KLUN) LRAPOUT
IF (LRAPOUT) THEN
  WRITE (KLUN) LBOUND (YD%RAPOUT)
  WRITE (KLUN) UBOUND (YD%RAPOUT)
  WRITE (KLUN) YD%RAPOUT
ENDIF
LPDFSDX = ALLOCATED (YD%PDFSDX)
WRITE (KLUN) LPDFSDX
IF (LPDFSDX) THEN
  WRITE (KLUN) LBOUND (YD%PDFSDX)
  WRITE (KLUN) UBOUND (YD%PDFSDX)
  WRITE (KLUN) YD%PDFSDX
ENDIF
LAAM_NN = ALLOCATED (YD%AAM_NN)
WRITE (KLUN) LAAM_NN
IF (LAAM_NN) THEN
  WRITE (KLUN) LBOUND (YD%AAM_NN)
  WRITE (KLUN) UBOUND (YD%AAM_NN)
  WRITE (KLUN) YD%AAM_NN
ENDIF
LBBM_NN = ALLOCATED (YD%BBM_NN)
WRITE (KLUN) LBBM_NN
IF (LBBM_NN) THEN
  WRITE (KLUN) LBOUND (YD%BBM_NN)
  WRITE (KLUN) UBOUND (YD%BBM_NN)
  WRITE (KLUN) YD%BBM_NN
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TENEUR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TENEUR), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL4(4), IU4(4)
LOGICAL :: LAAM_NN, LBBM_NN, LENTREEMOY, LNBNEUR, LPDFSDX, LRAPIN, LRAPOUT, LSORTIEMOY, LWNELN
READ (KLUN) YD%NCOU
READ (KLUN) YD%NBR
READ (KLUN) YD%NBNEURMAX
READ (KLUN) YD%KLEV_NN
READ (KLUN) LNBNEUR
IF (LNBNEUR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NBNEUR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NBNEUR
ENDIF
READ (KLUN) LWNELN
IF (LWNELN) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%WNELN (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%WNELN
ENDIF
READ (KLUN) LENTREEMOY
IF (LENTREEMOY) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%ENTREEMOY (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%ENTREEMOY
ENDIF
READ (KLUN) LRAPIN
IF (LRAPIN) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RAPIN (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RAPIN
ENDIF
READ (KLUN) LSORTIEMOY
IF (LSORTIEMOY) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SORTIEMOY (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SORTIEMOY
ENDIF
READ (KLUN) LRAPOUT
IF (LRAPOUT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RAPOUT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RAPOUT
ENDIF
READ (KLUN) LPDFSDX
IF (LPDFSDX) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%PDFSDX (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%PDFSDX
ENDIF
READ (KLUN) LAAM_NN
IF (LAAM_NN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%AAM_NN (IL1(1):IU1(1)))
  READ (KLUN) YD%AAM_NN
ENDIF
READ (KLUN) LBBM_NN
IF (LBBM_NN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%BBM_NN (IL1(1):IU1(1)))
  READ (KLUN) YD%BBM_NN
ENDIF
END SUBROUTINE






END MODULE
