MODULE UTIL_TELBC_MODEL_MOD

USE YEMLBC_MODEL, ONLY : TELBC_MODEL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TELBC_MODEL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TELBC_MODEL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TELBC_MODEL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TELBC_MODEL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TELBC_MODEL), INTENT (IN), TARGET :: YD
LOGICAL :: LEALFAGT3GFL, LEALFAGT3GMV, LEALFAGT3GMVS, LEALFAU_GFL, LEALFAU_GMV, LEALFA_GFL, LEALFA_GMV, LEALFA_GMVS, LEALFA_TENC, LEWB
LOGICAL :: LEWBDFIBW, LEWBDFIFW, LGMGT3, LGMGT4, LLNUDSPGFL
WRITE (KLUN) YD%NEFRCL
WRITE (KLUN) YD%NETLS1
WRITE (KLUN) YD%TEFRCL
WRITE (KLUN) YD%LECOBI
WRITE (KLUN) YD%EPA_GMV
WRITE (KLUN) YD%EPA_GMVS
WRITE (KLUN) YD%EPA_GFL
LEALFA_GMV = ALLOCATED (YD%EALFA_GMV)
WRITE (KLUN) LEALFA_GMV
IF (LEALFA_GMV) THEN
  WRITE (KLUN) LBOUND (YD%EALFA_GMV)
  WRITE (KLUN) UBOUND (YD%EALFA_GMV)
  WRITE (KLUN) YD%EALFA_GMV
ENDIF
LEALFA_GMVS = ALLOCATED (YD%EALFA_GMVS)
WRITE (KLUN) LEALFA_GMVS
IF (LEALFA_GMVS) THEN
  WRITE (KLUN) LBOUND (YD%EALFA_GMVS)
  WRITE (KLUN) UBOUND (YD%EALFA_GMVS)
  WRITE (KLUN) YD%EALFA_GMVS
ENDIF
LEALFA_GFL = ALLOCATED (YD%EALFA_GFL)
WRITE (KLUN) LEALFA_GFL
IF (LEALFA_GFL) THEN
  WRITE (KLUN) LBOUND (YD%EALFA_GFL)
  WRITE (KLUN) UBOUND (YD%EALFA_GFL)
  WRITE (KLUN) YD%EALFA_GFL
ENDIF
LEALFA_TENC = ALLOCATED (YD%EALFA_TENC)
WRITE (KLUN) LEALFA_TENC
IF (LEALFA_TENC) THEN
  WRITE (KLUN) LBOUND (YD%EALFA_TENC)
  WRITE (KLUN) UBOUND (YD%EALFA_TENC)
  WRITE (KLUN) YD%EALFA_TENC
ENDIF
LEALFAGT3GMV = ALLOCATED (YD%EALFAGT3GMV)
WRITE (KLUN) LEALFAGT3GMV
IF (LEALFAGT3GMV) THEN
  WRITE (KLUN) LBOUND (YD%EALFAGT3GMV)
  WRITE (KLUN) UBOUND (YD%EALFAGT3GMV)
  WRITE (KLUN) YD%EALFAGT3GMV
ENDIF
LEALFAGT3GMVS = ALLOCATED (YD%EALFAGT3GMVS)
WRITE (KLUN) LEALFAGT3GMVS
IF (LEALFAGT3GMVS) THEN
  WRITE (KLUN) LBOUND (YD%EALFAGT3GMVS)
  WRITE (KLUN) UBOUND (YD%EALFAGT3GMVS)
  WRITE (KLUN) YD%EALFAGT3GMVS
ENDIF
LEALFAGT3GFL = ALLOCATED (YD%EALFAGT3GFL)
WRITE (KLUN) LEALFAGT3GFL
IF (LEALFAGT3GFL) THEN
  WRITE (KLUN) LBOUND (YD%EALFAGT3GFL)
  WRITE (KLUN) UBOUND (YD%EALFAGT3GFL)
  WRITE (KLUN) YD%EALFAGT3GFL
ENDIF
LEALFAU_GMV = ALLOCATED (YD%EALFAU_GMV)
WRITE (KLUN) LEALFAU_GMV
IF (LEALFAU_GMV) THEN
  WRITE (KLUN) LBOUND (YD%EALFAU_GMV)
  WRITE (KLUN) UBOUND (YD%EALFAU_GMV)
  WRITE (KLUN) YD%EALFAU_GMV
ENDIF
LEALFAU_GFL = ALLOCATED (YD%EALFAU_GFL)
WRITE (KLUN) LEALFAU_GFL
IF (LEALFAU_GFL) THEN
  WRITE (KLUN) LBOUND (YD%EALFAU_GFL)
  WRITE (KLUN) UBOUND (YD%EALFAU_GFL)
  WRITE (KLUN) YD%EALFAU_GFL
ENDIF
LGMGT3 = ALLOCATED (YD%GMGT3)
WRITE (KLUN) LGMGT3
IF (LGMGT3) THEN
  WRITE (KLUN) LBOUND (YD%GMGT3)
  WRITE (KLUN) UBOUND (YD%GMGT3)
  WRITE (KLUN) YD%GMGT3
ENDIF
LGMGT4 = ALLOCATED (YD%GMGT4)
WRITE (KLUN) LGMGT4
IF (LGMGT4) THEN
  WRITE (KLUN) LBOUND (YD%GMGT4)
  WRITE (KLUN) UBOUND (YD%GMGT4)
  WRITE (KLUN) YD%GMGT4
ENDIF
LEWB = ALLOCATED (YD%EWB)
WRITE (KLUN) LEWB
IF (LEWB) THEN
  WRITE (KLUN) LBOUND (YD%EWB)
  WRITE (KLUN) UBOUND (YD%EWB)
  WRITE (KLUN) YD%EWB
ENDIF
LEWBDFIFW = ALLOCATED (YD%EWBDFIFW)
WRITE (KLUN) LEWBDFIFW
IF (LEWBDFIFW) THEN
  WRITE (KLUN) LBOUND (YD%EWBDFIFW)
  WRITE (KLUN) UBOUND (YD%EWBDFIFW)
  WRITE (KLUN) YD%EWBDFIFW
ENDIF
LEWBDFIBW = ALLOCATED (YD%EWBDFIBW)
WRITE (KLUN) LEWBDFIBW
IF (LEWBDFIBW) THEN
  WRITE (KLUN) LBOUND (YD%EWBDFIBW)
  WRITE (KLUN) UBOUND (YD%EWBDFIBW)
  WRITE (KLUN) YD%EWBDFIBW
ENDIF
WRITE (KLUN) YD%RTENC
LLNUDSPGFL = ALLOCATED (YD%LNUDSPGFL)
WRITE (KLUN) LLNUDSPGFL
IF (LLNUDSPGFL) THEN
  WRITE (KLUN) LBOUND (YD%LNUDSPGFL)
  WRITE (KLUN) UBOUND (YD%LNUDSPGFL)
  WRITE (KLUN) YD%LNUDSPGFL
ENDIF
WRITE (KLUN) YD%LSPNUSPDL
WRITE (KLUN) YD%RNUDTFRAC
WRITE (KLUN) YD%NEFRSPCPL
WRITE (KLUN) YD%NEK0
WRITE (KLUN) YD%NEK1
WRITE (KLUN) YD%NEN1
WRITE (KLUN) YD%NEN2
WRITE (KLUN) YD%SPNUDVOR
WRITE (KLUN) YD%SPNUDDIV
WRITE (KLUN) YD%SPNUDT
WRITE (KLUN) YD%SPNUDQ
WRITE (KLUN) YD%SPNUDSP
WRITE (KLUN) YD%RNUTENC
END SUBROUTINE

SUBROUTINE LOAD_TELBC_MODEL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TELBC_MODEL), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LEALFAGT3GFL, LEALFAGT3GMV, LEALFAGT3GMVS, LEALFAU_GFL, LEALFAU_GMV, LEALFA_GFL, LEALFA_GMV, LEALFA_GMVS, LEALFA_TENC, LEWB
LOGICAL :: LEWBDFIBW, LEWBDFIFW, LGMGT3, LGMGT4, LLNUDSPGFL
READ (KLUN) YD%NEFRCL
READ (KLUN) YD%NETLS1
READ (KLUN) YD%TEFRCL
READ (KLUN) YD%LECOBI
READ (KLUN) YD%EPA_GMV
READ (KLUN) YD%EPA_GMVS
READ (KLUN) YD%EPA_GFL
READ (KLUN) LEALFA_GMV
IF (LEALFA_GMV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EALFA_GMV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EALFA_GMV
ENDIF
READ (KLUN) LEALFA_GMVS
IF (LEALFA_GMVS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EALFA_GMVS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EALFA_GMVS
ENDIF
READ (KLUN) LEALFA_GFL
IF (LEALFA_GFL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EALFA_GFL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EALFA_GFL
ENDIF
READ (KLUN) LEALFA_TENC
IF (LEALFA_TENC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EALFA_TENC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EALFA_TENC
ENDIF
READ (KLUN) LEALFAGT3GMV
IF (LEALFAGT3GMV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EALFAGT3GMV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EALFAGT3GMV
ENDIF
READ (KLUN) LEALFAGT3GMVS
IF (LEALFAGT3GMVS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EALFAGT3GMVS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EALFAGT3GMVS
ENDIF
READ (KLUN) LEALFAGT3GFL
IF (LEALFAGT3GFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EALFAGT3GFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EALFAGT3GFL
ENDIF
READ (KLUN) LEALFAU_GMV
IF (LEALFAU_GMV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EALFAU_GMV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EALFAU_GMV
ENDIF
READ (KLUN) LEALFAU_GFL
IF (LEALFAU_GFL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%EALFAU_GFL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%EALFAU_GFL
ENDIF
READ (KLUN) LGMGT3
IF (LGMGT3) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GMGT3 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GMGT3
ENDIF
READ (KLUN) LGMGT4
IF (LGMGT4) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GMGT4 (IL1(1):IU1(1)))
  READ (KLUN) YD%GMGT4
ENDIF
READ (KLUN) LEWB
IF (LEWB) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%EWB (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%EWB
ENDIF
READ (KLUN) LEWBDFIFW
IF (LEWBDFIFW) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%EWBDFIFW (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%EWBDFIFW
ENDIF
READ (KLUN) LEWBDFIBW
IF (LEWBDFIBW) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%EWBDFIBW (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%EWBDFIBW
ENDIF
READ (KLUN) YD%RTENC
READ (KLUN) LLNUDSPGFL
IF (LLNUDSPGFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LNUDSPGFL (IL1(1):IU1(1)))
  READ (KLUN) YD%LNUDSPGFL
ENDIF
READ (KLUN) YD%LSPNUSPDL
READ (KLUN) YD%RNUDTFRAC
READ (KLUN) YD%NEFRSPCPL
READ (KLUN) YD%NEK0
READ (KLUN) YD%NEK1
READ (KLUN) YD%NEN1
READ (KLUN) YD%NEN2
READ (KLUN) YD%SPNUDVOR
READ (KLUN) YD%SPNUDDIV
READ (KLUN) YD%SPNUDT
READ (KLUN) YD%SPNUDQ
READ (KLUN) YD%SPNUDSP
READ (KLUN) YD%RNUTENC
END SUBROUTINE


SUBROUTINE COPY_TELBC_MODEL (YD, LDCREATED)

IMPLICIT NONE
TYPE (TELBC_MODEL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LEALFAGT3GFL, LEALFAGT3GMV, LEALFAGT3GMVS, LEALFAU_GFL, LEALFAU_GMV, LEALFA_GFL, LEALFA_GMV, LEALFA_GMVS, LEALFA_TENC, LEWB
LOGICAL :: LEWBDFIBW, LEWBDFIFW, LGMGT3, LGMGT4, LLNUDSPGFL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF







LEALFA_GMV = ALLOCATED (YD%EALFA_GMV)
IF (LEALFA_GMV) THEN
  !$acc enter data create (YD%EALFA_GMV)
  !$acc update device (YD%EALFA_GMV)
  !$acc enter data attach (YD%EALFA_GMV)
ENDIF

LEALFA_GMVS = ALLOCATED (YD%EALFA_GMVS)
IF (LEALFA_GMVS) THEN
  !$acc enter data create (YD%EALFA_GMVS)
  !$acc update device (YD%EALFA_GMVS)
  !$acc enter data attach (YD%EALFA_GMVS)
ENDIF

LEALFA_GFL = ALLOCATED (YD%EALFA_GFL)
IF (LEALFA_GFL) THEN
  !$acc enter data create (YD%EALFA_GFL)
  !$acc update device (YD%EALFA_GFL)
  !$acc enter data attach (YD%EALFA_GFL)
ENDIF

LEALFA_TENC = ALLOCATED (YD%EALFA_TENC)
IF (LEALFA_TENC) THEN
  !$acc enter data create (YD%EALFA_TENC)
  !$acc update device (YD%EALFA_TENC)
  !$acc enter data attach (YD%EALFA_TENC)
ENDIF

LEALFAGT3GMV = ALLOCATED (YD%EALFAGT3GMV)
IF (LEALFAGT3GMV) THEN
  !$acc enter data create (YD%EALFAGT3GMV)
  !$acc update device (YD%EALFAGT3GMV)
  !$acc enter data attach (YD%EALFAGT3GMV)
ENDIF

LEALFAGT3GMVS = ALLOCATED (YD%EALFAGT3GMVS)
IF (LEALFAGT3GMVS) THEN
  !$acc enter data create (YD%EALFAGT3GMVS)
  !$acc update device (YD%EALFAGT3GMVS)
  !$acc enter data attach (YD%EALFAGT3GMVS)
ENDIF

LEALFAGT3GFL = ALLOCATED (YD%EALFAGT3GFL)
IF (LEALFAGT3GFL) THEN
  !$acc enter data create (YD%EALFAGT3GFL)
  !$acc update device (YD%EALFAGT3GFL)
  !$acc enter data attach (YD%EALFAGT3GFL)
ENDIF

LEALFAU_GMV = ALLOCATED (YD%EALFAU_GMV)
IF (LEALFAU_GMV) THEN
  !$acc enter data create (YD%EALFAU_GMV)
  !$acc update device (YD%EALFAU_GMV)
  !$acc enter data attach (YD%EALFAU_GMV)
ENDIF

LEALFAU_GFL = ALLOCATED (YD%EALFAU_GFL)
IF (LEALFAU_GFL) THEN
  !$acc enter data create (YD%EALFAU_GFL)
  !$acc update device (YD%EALFAU_GFL)
  !$acc enter data attach (YD%EALFAU_GFL)
ENDIF

LGMGT3 = ALLOCATED (YD%GMGT3)
IF (LGMGT3) THEN
  !$acc enter data create (YD%GMGT3)
  !$acc update device (YD%GMGT3)
  !$acc enter data attach (YD%GMGT3)
ENDIF

LGMGT4 = ALLOCATED (YD%GMGT4)
IF (LGMGT4) THEN
  !$acc enter data create (YD%GMGT4)
  !$acc update device (YD%GMGT4)
  !$acc enter data attach (YD%GMGT4)
ENDIF

LEWB = ALLOCATED (YD%EWB)
IF (LEWB) THEN
  !$acc enter data create (YD%EWB)
  !$acc update device (YD%EWB)
  !$acc enter data attach (YD%EWB)
ENDIF

LEWBDFIFW = ALLOCATED (YD%EWBDFIFW)
IF (LEWBDFIFW) THEN
  !$acc enter data create (YD%EWBDFIFW)
  !$acc update device (YD%EWBDFIFW)
  !$acc enter data attach (YD%EWBDFIFW)
ENDIF

LEWBDFIBW = ALLOCATED (YD%EWBDFIBW)
IF (LEWBDFIBW) THEN
  !$acc enter data create (YD%EWBDFIBW)
  !$acc update device (YD%EWBDFIBW)
  !$acc enter data attach (YD%EWBDFIBW)
ENDIF


LLNUDSPGFL = ALLOCATED (YD%LNUDSPGFL)
IF (LLNUDSPGFL) THEN
  !$acc enter data create (YD%LNUDSPGFL)
  !$acc update device (YD%LNUDSPGFL)
  !$acc enter data attach (YD%LNUDSPGFL)
ENDIF














END SUBROUTINE



END MODULE
