MODULE UTIL_TVAB_MOD

USE YOMVERT, ONLY : TVAB

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVAB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVAB
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TVAB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVAB), INTENT (IN), TARGET :: YD
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH
LVALH = ALLOCATED (YD%VALH)
WRITE (KLUN) LVALH
IF (LVALH) THEN
  WRITE (KLUN) LBOUND (YD%VALH)
  WRITE (KLUN) UBOUND (YD%VALH)
  WRITE (KLUN) YD%VALH
ENDIF
LVBH = ALLOCATED (YD%VBH)
WRITE (KLUN) LVBH
IF (LVBH) THEN
  WRITE (KLUN) LBOUND (YD%VBH)
  WRITE (KLUN) UBOUND (YD%VBH)
  WRITE (KLUN) YD%VBH
ENDIF
LVAH = ALLOCATED (YD%VAH)
WRITE (KLUN) LVAH
IF (LVAH) THEN
  WRITE (KLUN) LBOUND (YD%VAH)
  WRITE (KLUN) UBOUND (YD%VAH)
  WRITE (KLUN) YD%VAH
ENDIF
LVC = ALLOCATED (YD%VC)
WRITE (KLUN) LVC
IF (LVC) THEN
  WRITE (KLUN) LBOUND (YD%VC)
  WRITE (KLUN) UBOUND (YD%VC)
  WRITE (KLUN) YD%VC
ENDIF
LVAF = ALLOCATED (YD%VAF)
WRITE (KLUN) LVAF
IF (LVAF) THEN
  WRITE (KLUN) LBOUND (YD%VAF)
  WRITE (KLUN) UBOUND (YD%VAF)
  WRITE (KLUN) YD%VAF
ENDIF
LVBF = ALLOCATED (YD%VBF)
WRITE (KLUN) LVBF
IF (LVBF) THEN
  WRITE (KLUN) LBOUND (YD%VBF)
  WRITE (KLUN) UBOUND (YD%VBF)
  WRITE (KLUN) YD%VBF
ENDIF
LVDELA = ALLOCATED (YD%VDELA)
WRITE (KLUN) LVDELA
IF (LVDELA) THEN
  WRITE (KLUN) LBOUND (YD%VDELA)
  WRITE (KLUN) UBOUND (YD%VDELA)
  WRITE (KLUN) YD%VDELA
ENDIF
LVDELB = ALLOCATED (YD%VDELB)
WRITE (KLUN) LVDELB
IF (LVDELB) THEN
  WRITE (KLUN) LBOUND (YD%VDELB)
  WRITE (KLUN) UBOUND (YD%VDELB)
  WRITE (KLUN) YD%VDELB
ENDIF
LVRATH = ALLOCATED (YD%VRATH)
WRITE (KLUN) LVRATH
IF (LVRATH) THEN
  WRITE (KLUN) LBOUND (YD%VRATH)
  WRITE (KLUN) UBOUND (YD%VRATH)
  WRITE (KLUN) YD%VRATH
ENDIF
LVRATF = ALLOCATED (YD%VRATF)
WRITE (KLUN) LVRATF
IF (LVRATF) THEN
  WRITE (KLUN) LBOUND (YD%VRATF)
  WRITE (KLUN) UBOUND (YD%VRATF)
  WRITE (KLUN) YD%VRATF
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVAB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVAB), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH
READ (KLUN) LVALH
IF (LVALH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VALH (IL1(1):IU1(1)))
  READ (KLUN) YD%VALH
ENDIF
READ (KLUN) LVBH
IF (LVBH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VBH (IL1(1):IU1(1)))
  READ (KLUN) YD%VBH
ENDIF
READ (KLUN) LVAH
IF (LVAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VAH
ENDIF
READ (KLUN) LVC
IF (LVC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VC (IL1(1):IU1(1)))
  READ (KLUN) YD%VC
ENDIF
READ (KLUN) LVAF
IF (LVAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VAF
ENDIF
READ (KLUN) LVBF
IF (LVBF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VBF (IL1(1):IU1(1)))
  READ (KLUN) YD%VBF
ENDIF
READ (KLUN) LVDELA
IF (LVDELA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VDELA (IL1(1):IU1(1)))
  READ (KLUN) YD%VDELA
ENDIF
READ (KLUN) LVDELB
IF (LVDELB) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VDELB (IL1(1):IU1(1)))
  READ (KLUN) YD%VDELB
ENDIF
READ (KLUN) LVRATH
IF (LVRATH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRATH (IL1(1):IU1(1)))
  READ (KLUN) YD%VRATH
ENDIF
READ (KLUN) LVRATF
IF (LVRATF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRATF (IL1(1):IU1(1)))
  READ (KLUN) YD%VRATF
ENDIF
END SUBROUTINE






END MODULE
