MODULE UTIL_TVAB_MOD

USE YOMVERT, ONLY : TVAB


INTERFACE SAVE
MODULE PROCEDURE SAVE_TVAB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVAB
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVAB
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVAB
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVAB (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TVAB), INTENT (IN), TARGET :: YD
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH

LVALH = ALLOCATED (YD%VALH)
WRITE (KLUN) LVALH
IF (LVALH) THEN
  WRITE (KLUN) LBOUND (YD%VALH)
  WRITE (KLUN) UBOUND (YD%VALH)
  WRITE (KLUN) YD%VALH
ENDIF
LVBH = ALLOCATED (YD%VBH)
WRITE (KLUN) LVBH
IF (LVBH) THEN
  WRITE (KLUN) LBOUND (YD%VBH)
  WRITE (KLUN) UBOUND (YD%VBH)
  WRITE (KLUN) YD%VBH
ENDIF
LVAH = ALLOCATED (YD%VAH)
WRITE (KLUN) LVAH
IF (LVAH) THEN
  WRITE (KLUN) LBOUND (YD%VAH)
  WRITE (KLUN) UBOUND (YD%VAH)
  WRITE (KLUN) YD%VAH
ENDIF
LVC = ALLOCATED (YD%VC)
WRITE (KLUN) LVC
IF (LVC) THEN
  WRITE (KLUN) LBOUND (YD%VC)
  WRITE (KLUN) UBOUND (YD%VC)
  WRITE (KLUN) YD%VC
ENDIF
LVAF = ALLOCATED (YD%VAF)
WRITE (KLUN) LVAF
IF (LVAF) THEN
  WRITE (KLUN) LBOUND (YD%VAF)
  WRITE (KLUN) UBOUND (YD%VAF)
  WRITE (KLUN) YD%VAF
ENDIF
LVBF = ALLOCATED (YD%VBF)
WRITE (KLUN) LVBF
IF (LVBF) THEN
  WRITE (KLUN) LBOUND (YD%VBF)
  WRITE (KLUN) UBOUND (YD%VBF)
  WRITE (KLUN) YD%VBF
ENDIF
LVDELA = ALLOCATED (YD%VDELA)
WRITE (KLUN) LVDELA
IF (LVDELA) THEN
  WRITE (KLUN) LBOUND (YD%VDELA)
  WRITE (KLUN) UBOUND (YD%VDELA)
  WRITE (KLUN) YD%VDELA
ENDIF
LVDELB = ALLOCATED (YD%VDELB)
WRITE (KLUN) LVDELB
IF (LVDELB) THEN
  WRITE (KLUN) LBOUND (YD%VDELB)
  WRITE (KLUN) UBOUND (YD%VDELB)
  WRITE (KLUN) YD%VDELB
ENDIF
LVRATH = ALLOCATED (YD%VRATH)
WRITE (KLUN) LVRATH
IF (LVRATH) THEN
  WRITE (KLUN) LBOUND (YD%VRATH)
  WRITE (KLUN) UBOUND (YD%VRATH)
  WRITE (KLUN) YD%VRATH
ENDIF
LVRATF = ALLOCATED (YD%VRATF)
WRITE (KLUN) LVRATF
IF (LVRATF) THEN
  WRITE (KLUN) LBOUND (YD%VRATF)
  WRITE (KLUN) UBOUND (YD%VRATF)
  WRITE (KLUN) YD%VRATF
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVAB (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TVAB), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH

READ (KLUN) LVALH
IF (LVALH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VALH (IL1(1):IU1(1)))
  READ (KLUN) YD%VALH
ENDIF
READ (KLUN) LVBH
IF (LVBH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VBH (IL1(1):IU1(1)))
  READ (KLUN) YD%VBH
ENDIF
READ (KLUN) LVAH
IF (LVAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VAH
ENDIF
READ (KLUN) LVC
IF (LVC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VC (IL1(1):IU1(1)))
  READ (KLUN) YD%VC
ENDIF
READ (KLUN) LVAF
IF (LVAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VAF
ENDIF
READ (KLUN) LVBF
IF (LVBF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VBF (IL1(1):IU1(1)))
  READ (KLUN) YD%VBF
ENDIF
READ (KLUN) LVDELA
IF (LVDELA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VDELA (IL1(1):IU1(1)))
  READ (KLUN) YD%VDELA
ENDIF
READ (KLUN) LVDELB
IF (LVDELB) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VDELB (IL1(1):IU1(1)))
  READ (KLUN) YD%VDELB
ENDIF
READ (KLUN) LVRATH
IF (LVRATH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRATH (IL1(1):IU1(1)))
  READ (KLUN) YD%VRATH
ENDIF
READ (KLUN) LVRATF
IF (LVRATF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRATF (IL1(1):IU1(1)))
  READ (KLUN) YD%VRATF
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVAB (YD, LDCREATED)
IMPLICIT NONE
CLASS (TVAB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LVALH = ALLOCATED (YD%VALH)
IF (LVALH) THEN
  !$acc enter data create (YD%VALH)
  !$acc update device (YD%VALH)
  !$acc enter data attach (YD%VALH)
ENDIF

LVBH = ALLOCATED (YD%VBH)
IF (LVBH) THEN
  !$acc enter data create (YD%VBH)
  !$acc update device (YD%VBH)
  !$acc enter data attach (YD%VBH)
ENDIF

LVAH = ALLOCATED (YD%VAH)
IF (LVAH) THEN
  !$acc enter data create (YD%VAH)
  !$acc update device (YD%VAH)
  !$acc enter data attach (YD%VAH)
ENDIF

LVC = ALLOCATED (YD%VC)
IF (LVC) THEN
  !$acc enter data create (YD%VC)
  !$acc update device (YD%VC)
  !$acc enter data attach (YD%VC)
ENDIF

LVAF = ALLOCATED (YD%VAF)
IF (LVAF) THEN
  !$acc enter data create (YD%VAF)
  !$acc update device (YD%VAF)
  !$acc enter data attach (YD%VAF)
ENDIF

LVBF = ALLOCATED (YD%VBF)
IF (LVBF) THEN
  !$acc enter data create (YD%VBF)
  !$acc update device (YD%VBF)
  !$acc enter data attach (YD%VBF)
ENDIF

LVDELA = ALLOCATED (YD%VDELA)
IF (LVDELA) THEN
  !$acc enter data create (YD%VDELA)
  !$acc update device (YD%VDELA)
  !$acc enter data attach (YD%VDELA)
ENDIF

LVDELB = ALLOCATED (YD%VDELB)
IF (LVDELB) THEN
  !$acc enter data create (YD%VDELB)
  !$acc update device (YD%VDELB)
  !$acc enter data attach (YD%VDELB)
ENDIF

LVRATH = ALLOCATED (YD%VRATH)
IF (LVRATH) THEN
  !$acc enter data create (YD%VRATH)
  !$acc update device (YD%VRATH)
  !$acc enter data attach (YD%VRATH)
ENDIF

LVRATF = ALLOCATED (YD%VRATF)
IF (LVRATF) THEN
  !$acc enter data create (YD%VRATF)
  !$acc update device (YD%VRATF)
  !$acc enter data attach (YD%VRATF)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TVAB (YD, LDDELETED)
IMPLICIT NONE
CLASS (TVAB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH

LVALH = ALLOCATED (YD%VALH)
IF (LVALH) THEN
  !$acc exit data detach (YD%VALH)
  !$acc exit data delete (YD%VALH)
ENDIF

LVBH = ALLOCATED (YD%VBH)
IF (LVBH) THEN
  !$acc exit data detach (YD%VBH)
  !$acc exit data delete (YD%VBH)
ENDIF

LVAH = ALLOCATED (YD%VAH)
IF (LVAH) THEN
  !$acc exit data detach (YD%VAH)
  !$acc exit data delete (YD%VAH)
ENDIF

LVC = ALLOCATED (YD%VC)
IF (LVC) THEN
  !$acc exit data detach (YD%VC)
  !$acc exit data delete (YD%VC)
ENDIF

LVAF = ALLOCATED (YD%VAF)
IF (LVAF) THEN
  !$acc exit data detach (YD%VAF)
  !$acc exit data delete (YD%VAF)
ENDIF

LVBF = ALLOCATED (YD%VBF)
IF (LVBF) THEN
  !$acc exit data detach (YD%VBF)
  !$acc exit data delete (YD%VBF)
ENDIF

LVDELA = ALLOCATED (YD%VDELA)
IF (LVDELA) THEN
  !$acc exit data detach (YD%VDELA)
  !$acc exit data delete (YD%VDELA)
ENDIF

LVDELB = ALLOCATED (YD%VDELB)
IF (LVDELB) THEN
  !$acc exit data detach (YD%VDELB)
  !$acc exit data delete (YD%VDELB)
ENDIF

LVRATH = ALLOCATED (YD%VRATH)
IF (LVRATH) THEN
  !$acc exit data detach (YD%VRATH)
  !$acc exit data delete (YD%VRATH)
ENDIF

LVRATF = ALLOCATED (YD%VRATF)
IF (LVRATF) THEN
  !$acc exit data detach (YD%VRATF)
  !$acc exit data delete (YD%VRATF)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
