MODULE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD

USE MODEL_PHYSICS_SIMPLINEAR_MOD, ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE UTIL_SPHYS_HIST_TYPE_MOD
USE UTIL_TCUMFS_MOD
USE UTIL_TECUMF2_MOD
USE UTIL_TEGWDWMS_MOD
USE UTIL_TEPHLI_MOD
USE UTIL_TNCL_MOD
USE UTIL_TPHLC_MOD
USE UTIL_TPHNC_MOD
USE UTIL_TSRFTLAD_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_SIMPLINEAR_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_SIMPLINEAR_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_SIMPLINEAR_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_SIMPLINEAR_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_SIMPLINEAR_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LGPHIST

CALL SAVE (KLUN, YD%YREPHLI)
CALL SAVE (KLUN, YD%YRCUMFS)
CALL SAVE (KLUN, YD%YREGWDWMS)
CALL SAVE (KLUN, YD%YRECUMF2)
CALL SAVE (KLUN, YD%YRPHLC)
CALL SAVE (KLUN, YD%YRPHNC)
CALL SAVE (KLUN, YD%YRNCL)
CALL SAVE (KLUN, YD%YRSRFTLAD)
LGPHIST = ASSOCIATED (YD%GPHIST)
WRITE (KLUN) LGPHIST
IF (LGPHIST) THEN
  WRITE (KLUN) LBOUND (YD%GPHIST)
  WRITE (KLUN) UBOUND (YD%GPHIST)
  DO J1 = LBOUND (YD%GPHIST, 1), UBOUND (YD%GPHIST, 1)
    CALL SAVE (KLUN, YD%GPHIST (J1))
  ENDDO
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_SIMPLINEAR_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LGPHIST

CALL LOAD (KLUN, YD%YREPHLI)
CALL LOAD (KLUN, YD%YRCUMFS)
CALL LOAD (KLUN, YD%YREGWDWMS)
CALL LOAD (KLUN, YD%YRECUMF2)
CALL LOAD (KLUN, YD%YRPHLC)
CALL LOAD (KLUN, YD%YRPHNC)
CALL LOAD (KLUN, YD%YRNCL)
CALL LOAD (KLUN, YD%YRSRFTLAD)
READ (KLUN) LGPHIST
IF (LGPHIST) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GPHIST (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%GPHIST, 1), UBOUND (YD%GPHIST, 1)
    CALL LOAD (KLUN, YD%GPHIST (J1))
  ENDDO
ELSE
  NULLIFY (YD%GPHIST)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_SIMPLINEAR_TYPE (YD, LDCREATED)
IMPLICIT NONE
CLASS (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
INTEGER :: J1
LOGICAL :: LGPHIST

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YREPHLI, LDCREATED=.TRUE.)

CALL COPY (YD%YRCUMFS, LDCREATED=.TRUE.)

CALL COPY (YD%YREGWDWMS, LDCREATED=.TRUE.)

CALL COPY (YD%YRECUMF2, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHLC, LDCREATED=.TRUE.)

CALL COPY (YD%YRPHNC, LDCREATED=.TRUE.)

CALL COPY (YD%YRNCL, LDCREATED=.TRUE.)

CALL COPY (YD%YRSRFTLAD, LDCREATED=.TRUE.)

LGPHIST = ASSOCIATED (YD%GPHIST)
IF (LGPHIST) THEN
  !$acc enter data create (YD%GPHIST)
  !$acc update device (YD%GPHIST)
  DO J1 = LBOUND (YD%GPHIST, 1), UBOUND (YD%GPHIST, 1)
    CALL COPY (YD%GPHIST (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%GPHIST)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_SIMPLINEAR_TYPE (YD, LDDELETED)
IMPLICIT NONE
CLASS (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
INTEGER :: J1
LOGICAL :: LGPHIST

CALL WIPE (YD%YREPHLI, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCUMFS, LDDELETED=.TRUE.)

CALL WIPE (YD%YREGWDWMS, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECUMF2, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHLC, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPHNC, LDDELETED=.TRUE.)

CALL WIPE (YD%YRNCL, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSRFTLAD, LDDELETED=.TRUE.)

LGPHIST = ASSOCIATED (YD%GPHIST)
IF (LGPHIST) THEN
  !$acc exit data detach (YD%GPHIST)
  DO J1 = LBOUND (YD%GPHIST, 1), UBOUND (YD%GPHIST, 1)
    CALL WIPE (YD%GPHIST (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%GPHIST)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
