MODULE UTIL_TECND_MOD

USE YOECND, ONLY : TECND


INTERFACE SAVE
MODULE PROCEDURE SAVE_TECND
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECND
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TECND
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TECND
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TECND (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECND), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%REPFLM
WRITE (KLUN) YD%REPQMI
END SUBROUTINE

SUBROUTINE LOAD_TECND (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECND), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%REPFLM
READ (KLUN) YD%REPQMI
END SUBROUTINE


SUBROUTINE COPY_TECND (YD, LDCREATED)
IMPLICIT NONE
TYPE (TECND), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF


END SUBROUTINE

SUBROUTINE WIPE_TECND (YD, LDDELETED)
IMPLICIT NONE
TYPE (TECND), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
