MODULE UTIL_RADIATION_GRID_STRUCT_MOD

USE YOMPRAD, ONLY : RADIATION_GRID_STRUCT

INTERFACE SAVE
MODULE PROCEDURE SAVE_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_RADIATION_GRID_STRUCT
END INTERFACE



CONTAINS

SUBROUTINE SAVE_RADIATION_GRID_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN) YD%NRESOL_ID
WRITE (KLUN) YD%NGPTOT
WRITE (KLUN) YD%NGPTOTG
WRITE (KLUN) YD%NGPTOTMX
WRITE (KLUN) YD%NSPEC2
WRITE (KLUN) YD%NSMAX
WRITE (KLUN) YD%NPTRFLOFF
WRITE (KLUN) YD%NUMP
WRITE (KLUN) YD%NDLON
WRITE (KLUN) YD%NDGSAL
WRITE (KLUN) YD%NDGENL
WRITE (KLUN) YD%NDGSAH
WRITE (KLUN) YD%NDGENH
WRITE (KLUN) YD%NDGLG
WRITE (KLUN) YD%NDGSAG
WRITE (KLUN) YD%NDGENG
WRITE (KLUN) YD%NDLSUR
WRITE (KLUN) YD%NFRSTLOFF
WRITE (KLUN) YD%NDSUR1
WRITE (KLUN) YD%NDGSUR
WRITE (KLUN) YD%MYFRSTACTLAT
WRITE (KLUN) YD%MYLSTACTLAT
LNRGRI = ALLOCATED (YD%NRGRI)
WRITE (KLUN) LNRGRI
IF (LNRGRI) THEN
  WRITE (KLUN) LBOUND (YD%NRGRI)
  WRITE (KLUN) UBOUND (YD%NRGRI)
  WRITE (KLUN) YD%NRGRI
ENDIF
LNLOENG = ALLOCATED (YD%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (YD%NLOENG)
  WRITE (KLUN) UBOUND (YD%NLOENG)
  WRITE (KLUN) YD%NLOENG
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) YD%NPTRFRSTLAT
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NFRSTLAT)
  WRITE (KLUN) YD%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NLSTLAT)
  WRITE (KLUN) UBOUND (YD%NLSTLAT)
  WRITE (KLUN) YD%NLSTLAT
ENDIF
LMYMS = ALLOCATED (YD%MYMS)
WRITE (KLUN) LMYMS
IF (LMYMS) THEN
  WRITE (KLUN) LBOUND (YD%MYMS)
  WRITE (KLUN) UBOUND (YD%MYMS)
  WRITE (KLUN) YD%MYMS
ENDIF
LNASM0 = ALLOCATED (YD%NASM0)
WRITE (KLUN) LNASM0
IF (LNASM0) THEN
  WRITE (KLUN) LBOUND (YD%NASM0)
  WRITE (KLUN) UBOUND (YD%NASM0)
  WRITE (KLUN) YD%NASM0
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (YD%NSTA)
  WRITE (KLUN) UBOUND (YD%NSTA)
  WRITE (KLUN) YD%NSTA
ENDIF
LNONL = ALLOCATED (YD%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (YD%NONL)
  WRITE (KLUN) UBOUND (YD%NONL)
  WRITE (KLUN) YD%NONL
ENDIF
LGELAM = ALLOCATED (YD%GELAM)
WRITE (KLUN) LGELAM
IF (LGELAM) THEN
  WRITE (KLUN) LBOUND (YD%GELAM)
  WRITE (KLUN) UBOUND (YD%GELAM)
  WRITE (KLUN) YD%GELAM
ENDIF
LGELAT = ALLOCATED (YD%GELAT)
WRITE (KLUN) LGELAT
IF (LGELAT) THEN
  WRITE (KLUN) LBOUND (YD%GELAT)
  WRITE (KLUN) UBOUND (YD%GELAT)
  WRITE (KLUN) YD%GELAT
ENDIF
LGECLO = ALLOCATED (YD%GECLO)
WRITE (KLUN) LGECLO
IF (LGECLO) THEN
  WRITE (KLUN) LBOUND (YD%GECLO)
  WRITE (KLUN) UBOUND (YD%GECLO)
  WRITE (KLUN) YD%GECLO
ENDIF
LGESLO = ALLOCATED (YD%GESLO)
WRITE (KLUN) LGESLO
IF (LGESLO) THEN
  WRITE (KLUN) LBOUND (YD%GESLO)
  WRITE (KLUN) UBOUND (YD%GESLO)
  WRITE (KLUN) YD%GESLO
ENDIF
LRMU = ALLOCATED (YD%RMU)
WRITE (KLUN) LRMU
IF (LRMU) THEN
  WRITE (KLUN) LBOUND (YD%RMU)
  WRITE (KLUN) UBOUND (YD%RMU)
  WRITE (KLUN) YD%RMU
ENDIF
LRSQM2 = ALLOCATED (YD%RSQM2)
WRITE (KLUN) LRSQM2
IF (LRSQM2) THEN
  WRITE (KLUN) LBOUND (YD%RSQM2)
  WRITE (KLUN) UBOUND (YD%RSQM2)
  WRITE (KLUN) YD%RSQM2
ENDIF
LRLATIG = ALLOCATED (YD%RLATIG)
WRITE (KLUN) LRLATIG
IF (LRLATIG) THEN
  WRITE (KLUN) LBOUND (YD%RLATIG)
  WRITE (KLUN) UBOUND (YD%RLATIG)
  WRITE (KLUN) YD%RLATIG
ENDIF
LRLATI = ALLOCATED (YD%RLATI)
WRITE (KLUN) LRLATI
IF (LRLATI) THEN
  WRITE (KLUN) LBOUND (YD%RLATI)
  WRITE (KLUN) UBOUND (YD%RLATI)
  WRITE (KLUN) YD%RLATI
ENDIF
LGEMU = ALLOCATED (YD%GEMU)
WRITE (KLUN) LGEMU
IF (LGEMU) THEN
  WRITE (KLUN) LBOUND (YD%GEMU)
  WRITE (KLUN) UBOUND (YD%GEMU)
  WRITE (KLUN) YD%GEMU
ENDIF
LRIPI = ALLOCATED (YD%RIPI)
WRITE (KLUN) LRIPI
IF (LRIPI) THEN
  WRITE (KLUN) LBOUND (YD%RIPI)
  WRITE (KLUN) UBOUND (YD%RIPI)
  WRITE (KLUN) YD%RIPI
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_RADIATION_GRID_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (RADIATION_GRID_STRUCT), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
READ (KLUN) YD%NRESOL_ID
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NGPTOTG
READ (KLUN) YD%NGPTOTMX
READ (KLUN) YD%NSPEC2
READ (KLUN) YD%NSMAX
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) YD%NUMP
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) LNRGRI
IF (LNRGRI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NRGRI (IL1(1):IU1(1)))
  READ (KLUN) YD%NRGRI
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRFRSTLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NLSTLAT
ENDIF
READ (KLUN) LMYMS
IF (LMYMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYMS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYMS
ENDIF
READ (KLUN) LNASM0
IF (LNASM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NASM0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NASM0
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NONL
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAM (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAM
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAT (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAT
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GECLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GECLO
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GESLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GESLO
ENDIF
READ (KLUN) LRMU
IF (LRMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMU
ENDIF
READ (KLUN) LRSQM2
IF (LRSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSQM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%RSQM2
ENDIF
READ (KLUN) LRLATIG
IF (LRLATIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATIG (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATIG
ENDIF
READ (KLUN) LRLATI
IF (LRLATI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATI (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATI
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GEMU (IL1(1):IU1(1)))
  READ (KLUN) YD%GEMU
ENDIF
READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RIPI
ENDIF
END SUBROUTINE


SUBROUTINE COPY_RADIATION_GRID_STRUCT (YD, LDCREATED)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF






















LNRGRI = ALLOCATED (YD%NRGRI)
IF (LNRGRI) THEN
  !$acc enter data create (YD%NRGRI)
  !$acc update device (YD%NRGRI)
  !$acc enter data attach (YD%NRGRI)
ENDIF

LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  !$acc enter data create (YD%NLOENG)
  !$acc update device (YD%NLOENG)
  !$acc enter data attach (YD%NLOENG)
ENDIF

LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$acc enter data create (YD%NPTRFRSTLAT)
  !$acc update device (YD%NPTRFRSTLAT)
  !$acc enter data attach (YD%NPTRFRSTLAT)
ENDIF

LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$acc enter data create (YD%NFRSTLAT)
  !$acc update device (YD%NFRSTLAT)
  !$acc enter data attach (YD%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  !$acc enter data create (YD%NLSTLAT)
  !$acc update device (YD%NLSTLAT)
  !$acc enter data attach (YD%NLSTLAT)
ENDIF

LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  !$acc enter data create (YD%MYMS)
  !$acc update device (YD%MYMS)
  !$acc enter data attach (YD%MYMS)
ENDIF

LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  !$acc enter data create (YD%NASM0)
  !$acc update device (YD%NASM0)
  !$acc enter data attach (YD%NASM0)
ENDIF

LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  !$acc enter data create (YD%NSTA)
  !$acc update device (YD%NSTA)
  !$acc enter data attach (YD%NSTA)
ENDIF

LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  !$acc enter data create (YD%NONL)
  !$acc update device (YD%NONL)
  !$acc enter data attach (YD%NONL)
ENDIF

LGELAM = ALLOCATED (YD%GELAM)
IF (LGELAM) THEN
  !$acc enter data create (YD%GELAM)
  !$acc update device (YD%GELAM)
  !$acc enter data attach (YD%GELAM)
ENDIF

LGELAT = ALLOCATED (YD%GELAT)
IF (LGELAT) THEN
  !$acc enter data create (YD%GELAT)
  !$acc update device (YD%GELAT)
  !$acc enter data attach (YD%GELAT)
ENDIF

LGECLO = ALLOCATED (YD%GECLO)
IF (LGECLO) THEN
  !$acc enter data create (YD%GECLO)
  !$acc update device (YD%GECLO)
  !$acc enter data attach (YD%GECLO)
ENDIF

LGESLO = ALLOCATED (YD%GESLO)
IF (LGESLO) THEN
  !$acc enter data create (YD%GESLO)
  !$acc update device (YD%GESLO)
  !$acc enter data attach (YD%GESLO)
ENDIF

LRMU = ALLOCATED (YD%RMU)
IF (LRMU) THEN
  !$acc enter data create (YD%RMU)
  !$acc update device (YD%RMU)
  !$acc enter data attach (YD%RMU)
ENDIF

LRSQM2 = ALLOCATED (YD%RSQM2)
IF (LRSQM2) THEN
  !$acc enter data create (YD%RSQM2)
  !$acc update device (YD%RSQM2)
  !$acc enter data attach (YD%RSQM2)
ENDIF

LRLATIG = ALLOCATED (YD%RLATIG)
IF (LRLATIG) THEN
  !$acc enter data create (YD%RLATIG)
  !$acc update device (YD%RLATIG)
  !$acc enter data attach (YD%RLATIG)
ENDIF

LRLATI = ALLOCATED (YD%RLATI)
IF (LRLATI) THEN
  !$acc enter data create (YD%RLATI)
  !$acc update device (YD%RLATI)
  !$acc enter data attach (YD%RLATI)
ENDIF

LGEMU = ALLOCATED (YD%GEMU)
IF (LGEMU) THEN
  !$acc enter data create (YD%GEMU)
  !$acc update device (YD%GEMU)
  !$acc enter data attach (YD%GEMU)
ENDIF

LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  !$acc enter data create (YD%RIPI)
  !$acc update device (YD%RIPI)
  !$acc enter data attach (YD%RIPI)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_RADIATION_GRID_STRUCT (YD, LDDELETED)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2























LNRGRI = ALLOCATED (YD%NRGRI)
IF (LNRGRI) THEN
  !$acc exit data detach (YD%NRGRI)
  !$acc exit data delete (YD%NRGRI)
ENDIF

LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  !$acc exit data detach (YD%NLOENG)
  !$acc exit data delete (YD%NLOENG)
ENDIF

LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$acc exit data detach (YD%NPTRFRSTLAT)
  !$acc exit data delete (YD%NPTRFRSTLAT)
ENDIF

LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$acc exit data detach (YD%NFRSTLAT)
  !$acc exit data delete (YD%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  !$acc exit data detach (YD%NLSTLAT)
  !$acc exit data delete (YD%NLSTLAT)
ENDIF

LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  !$acc exit data detach (YD%MYMS)
  !$acc exit data delete (YD%MYMS)
ENDIF

LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  !$acc exit data detach (YD%NASM0)
  !$acc exit data delete (YD%NASM0)
ENDIF

LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  !$acc exit data detach (YD%NSTA)
  !$acc exit data delete (YD%NSTA)
ENDIF

LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  !$acc exit data detach (YD%NONL)
  !$acc exit data delete (YD%NONL)
ENDIF

LGELAM = ALLOCATED (YD%GELAM)
IF (LGELAM) THEN
  !$acc exit data detach (YD%GELAM)
  !$acc exit data delete (YD%GELAM)
ENDIF

LGELAT = ALLOCATED (YD%GELAT)
IF (LGELAT) THEN
  !$acc exit data detach (YD%GELAT)
  !$acc exit data delete (YD%GELAT)
ENDIF

LGECLO = ALLOCATED (YD%GECLO)
IF (LGECLO) THEN
  !$acc exit data detach (YD%GECLO)
  !$acc exit data delete (YD%GECLO)
ENDIF

LGESLO = ALLOCATED (YD%GESLO)
IF (LGESLO) THEN
  !$acc exit data detach (YD%GESLO)
  !$acc exit data delete (YD%GESLO)
ENDIF

LRMU = ALLOCATED (YD%RMU)
IF (LRMU) THEN
  !$acc exit data detach (YD%RMU)
  !$acc exit data delete (YD%RMU)
ENDIF

LRSQM2 = ALLOCATED (YD%RSQM2)
IF (LRSQM2) THEN
  !$acc exit data detach (YD%RSQM2)
  !$acc exit data delete (YD%RSQM2)
ENDIF

LRLATIG = ALLOCATED (YD%RLATIG)
IF (LRLATIG) THEN
  !$acc exit data detach (YD%RLATIG)
  !$acc exit data delete (YD%RLATIG)
ENDIF

LRLATI = ALLOCATED (YD%RLATI)
IF (LRLATI) THEN
  !$acc exit data detach (YD%RLATI)
  !$acc exit data delete (YD%RLATI)
ENDIF

LGEMU = ALLOCATED (YD%GEMU)
IF (LGEMU) THEN
  !$acc exit data detach (YD%GEMU)
  !$acc exit data delete (YD%GEMU)
ENDIF

LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  !$acc exit data detach (YD%RIPI)
  !$acc exit data delete (YD%RIPI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
