MODULE UTIL_TRCOEF_MOD

USE YOMRCOEF, ONLY : TRCOEF

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRCOEF
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRCOEF
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRCOEF
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRCOEF
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRCOEF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRCOEF), INTENT (IN), TARGET :: YD
LOGICAL :: LSOLRAD, LTHERRAD, LTRMATSUM, LTRWEIGHT
WRITE (KLUN) YD%LRCOEF
WRITE (KLUN) YD%LTLADDIA
WRITE (KLUN) YD%LGLOBRAD
WRITE (KLUN) YD%NG3SR
WRITE (KLUN) YD%NGMTR
WRITE (KLUN) YD%NLATWR
WRITE (KLUN) YD%NLATRD
WRITE (KLUN) YD%NLENGSRB
WRITE (KLUN) YD%NLENGTRB
LSOLRAD = ALLOCATED (YD%SOLRAD)
WRITE (KLUN) LSOLRAD
IF (LSOLRAD) THEN
  WRITE (KLUN) LBOUND (YD%SOLRAD)
  WRITE (KLUN) UBOUND (YD%SOLRAD)
  WRITE (KLUN) YD%SOLRAD
ENDIF
LTHERRAD = ALLOCATED (YD%THERRAD)
WRITE (KLUN) LTHERRAD
IF (LTHERRAD) THEN
  WRITE (KLUN) LBOUND (YD%THERRAD)
  WRITE (KLUN) UBOUND (YD%THERRAD)
  WRITE (KLUN) YD%THERRAD
ENDIF
LTRWEIGHT = ALLOCATED (YD%TRWEIGHT)
WRITE (KLUN) LTRWEIGHT
IF (LTRWEIGHT) THEN
  WRITE (KLUN) LBOUND (YD%TRWEIGHT)
  WRITE (KLUN) UBOUND (YD%TRWEIGHT)
  WRITE (KLUN) YD%TRWEIGHT
ENDIF
LTRMATSUM = ALLOCATED (YD%TRMATSUM)
WRITE (KLUN) LTRMATSUM
IF (LTRMATSUM) THEN
  WRITE (KLUN) LBOUND (YD%TRMATSUM)
  WRITE (KLUN) UBOUND (YD%TRMATSUM)
  WRITE (KLUN) YD%TRMATSUM
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TRCOEF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRCOEF), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LSOLRAD, LTHERRAD, LTRMATSUM, LTRWEIGHT
READ (KLUN) YD%LRCOEF
READ (KLUN) YD%LTLADDIA
READ (KLUN) YD%LGLOBRAD
READ (KLUN) YD%NG3SR
READ (KLUN) YD%NGMTR
READ (KLUN) YD%NLATWR
READ (KLUN) YD%NLATRD
READ (KLUN) YD%NLENGSRB
READ (KLUN) YD%NLENGTRB
READ (KLUN) LSOLRAD
IF (LSOLRAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SOLRAD (IL1(1):IU1(1)))
  READ (KLUN) YD%SOLRAD
ENDIF
READ (KLUN) LTHERRAD
IF (LTHERRAD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%THERRAD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%THERRAD
ENDIF
READ (KLUN) LTRWEIGHT
IF (LTRWEIGHT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TRWEIGHT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TRWEIGHT
ENDIF
READ (KLUN) LTRMATSUM
IF (LTRMATSUM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TRMATSUM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TRMATSUM
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TRCOEF (YD, LDCREATED)

IMPLICIT NONE
TYPE (TRCOEF), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LSOLRAD, LTHERRAD, LTRMATSUM, LTRWEIGHT

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









LSOLRAD = ALLOCATED (YD%SOLRAD)
IF (LSOLRAD) THEN
  !$acc enter data create (YD%SOLRAD)
  !$acc update device (YD%SOLRAD)
  !$acc enter data attach (YD%SOLRAD)
ENDIF

LTHERRAD = ALLOCATED (YD%THERRAD)
IF (LTHERRAD) THEN
  !$acc enter data create (YD%THERRAD)
  !$acc update device (YD%THERRAD)
  !$acc enter data attach (YD%THERRAD)
ENDIF

LTRWEIGHT = ALLOCATED (YD%TRWEIGHT)
IF (LTRWEIGHT) THEN
  !$acc enter data create (YD%TRWEIGHT)
  !$acc update device (YD%TRWEIGHT)
  !$acc enter data attach (YD%TRWEIGHT)
ENDIF

LTRMATSUM = ALLOCATED (YD%TRMATSUM)
IF (LTRMATSUM) THEN
  !$acc enter data create (YD%TRMATSUM)
  !$acc update device (YD%TRMATSUM)
  !$acc enter data attach (YD%TRMATSUM)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TRCOEF (YD, LDDELETED)

IMPLICIT NONE
TYPE (TRCOEF), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LSOLRAD, LTHERRAD, LTRMATSUM, LTRWEIGHT










LSOLRAD = ALLOCATED (YD%SOLRAD)
IF (LSOLRAD) THEN
  !$acc exit data detach (YD%SOLRAD)
  !$acc exit data delete (YD%SOLRAD)
ENDIF

LTHERRAD = ALLOCATED (YD%THERRAD)
IF (LTHERRAD) THEN
  !$acc exit data detach (YD%THERRAD)
  !$acc exit data delete (YD%THERRAD)
ENDIF

LTRWEIGHT = ALLOCATED (YD%TRWEIGHT)
IF (LTRWEIGHT) THEN
  !$acc exit data detach (YD%TRWEIGHT)
  !$acc exit data delete (YD%TRWEIGHT)
ENDIF

LTRMATSUM = ALLOCATED (YD%TRMATSUM)
IF (LTRMATSUM) THEN
  !$acc exit data detach (YD%TRMATSUM)
  !$acc exit data delete (YD%TRMATSUM)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
