MODULE UTIL_GEOMETRY_MOD

USE TYPE_GEOMETRY, ONLY : GEOMETRY

INTERFACE SAVE
MODULE PROCEDURE SAVE_GEOMETRY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_GEOMETRY
END INTERFACE




CONTAINS

SUBROUTINE SAVE_GEOMETRY (KLUN, YD)
USE UTIL_TCSGEOM_BLOCKED_MOD
USE UTIL_TCSGEOM_MOD
USE UTIL_TCSGLEG_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TELBC_GEO_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TGSGEOM_BLOCKED_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_THSLMER_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TOROG_BLOCKED_MOD
USE UTIL_TOROG_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
USE UTIL_TVSLETA_MOD
USE UTIL_TVSPLIP_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYRCSGEOM, LYRCSGEOMAD, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA, LYRVFE
CALL SAVE (KLUN, YD%YRVERT_GEOM)
LYRVAB = ASSOCIATED (YD%YRVAB)
WRITE (KLUN) LYRVAB
IF (LYRVAB) THEN
  CALL SAVE (KLUN, YD%YRVAB)
ENDIF
LYRVETA = ASSOCIATED (YD%YRVETA)
WRITE (KLUN) LYRVETA
IF (LYRVETA) THEN
  CALL SAVE (KLUN, YD%YRVETA)
ENDIF
LYRVFE = ASSOCIATED (YD%YRVFE)
WRITE (KLUN) LYRVFE
IF (LYRVFE) THEN
  CALL SAVE (KLUN, YD%YRVFE)
ENDIF
CALL SAVE (KLUN, YD%YRSTA)
CALL SAVE (KLUN, YD%YRLAP)
CALL SAVE (KLUN, YD%YRCSGLEG)
CALL SAVE (KLUN, YD%YRDIM)
CALL SAVE (KLUN, YD%YRDIMV)
CALL SAVE (KLUN, YD%YRMP)
CALL SAVE (KLUN, YD%YRGEM)
CALL SAVE (KLUN, YD%YRVSPLIP)
CALL SAVE (KLUN, YD%YRVSLETA)
CALL SAVE (KLUN, YD%YRHSLMER)
CALL SAVE (KLUN, YD%YRCSGEOM_NB)
LYRCSGEOM = ASSOCIATED (YD%YRCSGEOM)
WRITE (KLUN) LYRCSGEOM
IF (LYRCSGEOM) THEN
  WRITE (KLUN) LBOUND (YD%YRCSGEOM)
  WRITE (KLUN) UBOUND (YD%YRCSGEOM)
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL SAVE (KLUN, YD%YRCSGEOM (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRCSGEOM_B)
CALL SAVE (KLUN, YD%YRGSGEOM_NB)
LYRGSGEOM = ASSOCIATED (YD%YRGSGEOM)
WRITE (KLUN) LYRGSGEOM
IF (LYRGSGEOM) THEN
  WRITE (KLUN) LBOUND (YD%YRGSGEOM)
  WRITE (KLUN) UBOUND (YD%YRGSGEOM)
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL SAVE (KLUN, YD%YRGSGEOM (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRGSGEOM_B)
WRITE (KLUN) YD%AD_GEOM
LYRCSGEOMAD = ASSOCIATED (YD%YRCSGEOMAD)
WRITE (KLUN) LYRCSGEOMAD
IF (LYRCSGEOMAD) THEN
  WRITE (KLUN) LBOUND (YD%YRCSGEOMAD)
  WRITE (KLUN) UBOUND (YD%YRCSGEOMAD)
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL SAVE (KLUN, YD%YRCSGEOMAD (J1))
  ENDDO
ENDIF
LYRGSGEOMAD = ASSOCIATED (YD%YRGSGEOMAD)
WRITE (KLUN) LYRGSGEOMAD
IF (LYRGSGEOMAD) THEN
  WRITE (KLUN) LBOUND (YD%YRGSGEOMAD)
  WRITE (KLUN) UBOUND (YD%YRGSGEOMAD)
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL SAVE (KLUN, YD%YRGSGEOMAD (J1))
  ENDDO
ENDIF
LYROROG = ALLOCATED (YD%YROROG)
WRITE (KLUN) LYROROG
IF (LYROROG) THEN
  WRITE (KLUN) LBOUND (YD%YROROG)
  WRITE (KLUN) UBOUND (YD%YROROG)
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL SAVE (KLUN, YD%YROROG (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YROROG_B)
CALL SAVE (KLUN, YD%YSPGEOM)
CALL SAVE (KLUN, YD%YVABIO)
CALL SAVE (KLUN, YD%YREDIM)
CALL SAVE (KLUN, YD%YREGEO)
CALL SAVE (KLUN, YD%YREMP)
CALL SAVE (KLUN, YD%YRELAP)
CALL SAVE (KLUN, YD%YREGSL)
LYRELBC_GEO = ASSOCIATED (YD%YRELBC_GEO)
WRITE (KLUN) LYRELBC_GEO
IF (LYRELBC_GEO) THEN
  CALL SAVE (KLUN, YD%YRELBC_GEO)
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_GEOMETRY (KLUN, YD)
USE UTIL_TCSGEOM_BLOCKED_MOD
USE UTIL_TCSGEOM_MOD
USE UTIL_TCSGLEG_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TELBC_GEO_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TGSGEOM_BLOCKED_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_THSLMER_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TOROG_BLOCKED_MOD
USE UTIL_TOROG_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
USE UTIL_TVSLETA_MOD
USE UTIL_TVSPLIP_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYRCSGEOM, LYRCSGEOMAD, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA, LYRVFE
CALL LOAD (KLUN, YD%YRVERT_GEOM)
READ (KLUN) LYRVAB
IF (LYRVAB) THEN
  ALLOCATE (YD%YRVAB)
  CALL LOAD (KLUN, YD%YRVAB)
ELSE
  NULLIFY (YD%YRVAB)
ENDIF
READ (KLUN) LYRVETA
IF (LYRVETA) THEN
  ALLOCATE (YD%YRVETA)
  CALL LOAD (KLUN, YD%YRVETA)
ELSE
  NULLIFY (YD%YRVETA)
ENDIF
READ (KLUN) LYRVFE
IF (LYRVFE) THEN
  ALLOCATE (YD%YRVFE)
  CALL LOAD (KLUN, YD%YRVFE)
ELSE
  NULLIFY (YD%YRVFE)
ENDIF
CALL LOAD (KLUN, YD%YRSTA)
CALL LOAD (KLUN, YD%YRLAP)
CALL LOAD (KLUN, YD%YRCSGLEG)
CALL LOAD (KLUN, YD%YRDIM)
CALL LOAD (KLUN, YD%YRDIMV)
CALL LOAD (KLUN, YD%YRMP)
CALL LOAD (KLUN, YD%YRGEM)
CALL LOAD (KLUN, YD%YRVSPLIP)
CALL LOAD (KLUN, YD%YRVSLETA)
CALL LOAD (KLUN, YD%YRHSLMER)
CALL LOAD (KLUN, YD%YRCSGEOM_NB)
READ (KLUN) LYRCSGEOM
IF (LYRCSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL LOAD (KLUN, YD%YRCSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRCSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRCSGEOM_B)
CALL LOAD (KLUN, YD%YRGSGEOM_NB)
READ (KLUN) LYRGSGEOM
IF (LYRGSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRGSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL LOAD (KLUN, YD%YRGSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRGSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRGSGEOM_B)
READ (KLUN) YD%AD_GEOM
READ (KLUN) LYRCSGEOMAD
IF (LYRCSGEOMAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCSGEOMAD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL LOAD (KLUN, YD%YRCSGEOMAD (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRCSGEOMAD)
ENDIF
READ (KLUN) LYRGSGEOMAD
IF (LYRGSGEOMAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRGSGEOMAD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL LOAD (KLUN, YD%YRGSGEOMAD (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRGSGEOMAD)
ENDIF
READ (KLUN) LYROROG
IF (LYROROG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YROROG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL LOAD (KLUN, YD%YROROG (J1))
  ENDDO
ENDIF
CALL LOAD (KLUN, YD%YROROG_B)
CALL LOAD (KLUN, YD%YSPGEOM)
CALL LOAD (KLUN, YD%YVABIO)
CALL LOAD (KLUN, YD%YREDIM)
CALL LOAD (KLUN, YD%YREGEO)
CALL LOAD (KLUN, YD%YREMP)
CALL LOAD (KLUN, YD%YRELAP)
CALL LOAD (KLUN, YD%YREGSL)
READ (KLUN) LYRELBC_GEO
IF (LYRELBC_GEO) THEN
  ALLOCATE (YD%YRELBC_GEO)
  CALL LOAD (KLUN, YD%YRELBC_GEO)
ELSE
  NULLIFY (YD%YRELBC_GEO)
ENDIF
END SUBROUTINE




END MODULE
