MODULE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD

USE SURFACE_VIEWS_PROGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_SNOWG

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_SNOWG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_SNOWG
END INTERFACE




CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_SNOWG (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_SNOWG), INTENT (IN), TARGET :: YD
LOGICAL :: LF_A_T0, LF_A_T1, LF_A_T9, LF_F_T0, LF_F_T1, LF_F_T9, LF_R_T0, LF_R_T1, LF_R_T9, LF_T_T0
LOGICAL :: LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9
LF_F_T0 = ASSOCIATED (YD%F_F_T0)
WRITE (KLUN) LF_F_T0
IF (LF_F_T0) THEN
  CALL SAVE (KLUN, YD%F_F_T0)
ENDIF
LF_F_T1 = ASSOCIATED (YD%F_F_T1)
WRITE (KLUN) LF_F_T1
IF (LF_F_T1) THEN
  CALL SAVE (KLUN, YD%F_F_T1)
ENDIF
LF_F_T9 = ASSOCIATED (YD%F_F_T9)
WRITE (KLUN) LF_F_T9
IF (LF_F_T9) THEN
  CALL SAVE (KLUN, YD%F_F_T9)
ENDIF
LF_A_T0 = ASSOCIATED (YD%F_A_T0)
WRITE (KLUN) LF_A_T0
IF (LF_A_T0) THEN
  CALL SAVE (KLUN, YD%F_A_T0)
ENDIF
LF_A_T1 = ASSOCIATED (YD%F_A_T1)
WRITE (KLUN) LF_A_T1
IF (LF_A_T1) THEN
  CALL SAVE (KLUN, YD%F_A_T1)
ENDIF
LF_A_T9 = ASSOCIATED (YD%F_A_T9)
WRITE (KLUN) LF_A_T9
IF (LF_A_T9) THEN
  CALL SAVE (KLUN, YD%F_A_T9)
ENDIF
LF_R_T0 = ASSOCIATED (YD%F_R_T0)
WRITE (KLUN) LF_R_T0
IF (LF_R_T0) THEN
  CALL SAVE (KLUN, YD%F_R_T0)
ENDIF
LF_R_T1 = ASSOCIATED (YD%F_R_T1)
WRITE (KLUN) LF_R_T1
IF (LF_R_T1) THEN
  CALL SAVE (KLUN, YD%F_R_T1)
ENDIF
LF_R_T9 = ASSOCIATED (YD%F_R_T9)
WRITE (KLUN) LF_R_T9
IF (LF_R_T9) THEN
  CALL SAVE (KLUN, YD%F_R_T9)
ENDIF
LF_T_T0 = ASSOCIATED (YD%F_T_T0)
WRITE (KLUN) LF_T_T0
IF (LF_T_T0) THEN
  CALL SAVE (KLUN, YD%F_T_T0)
ENDIF
LF_T_T1 = ASSOCIATED (YD%F_T_T1)
WRITE (KLUN) LF_T_T1
IF (LF_T_T1) THEN
  CALL SAVE (KLUN, YD%F_T_T1)
ENDIF
LF_T_T9 = ASSOCIATED (YD%F_T_T9)
WRITE (KLUN) LF_T_T9
IF (LF_T_T9) THEN
  CALL SAVE (KLUN, YD%F_T_T9)
ENDIF
LF_W_T0 = ASSOCIATED (YD%F_W_T0)
WRITE (KLUN) LF_W_T0
IF (LF_W_T0) THEN
  CALL SAVE (KLUN, YD%F_W_T0)
ENDIF
LF_W_T1 = ASSOCIATED (YD%F_W_T1)
WRITE (KLUN) LF_W_T1
IF (LF_W_T1) THEN
  CALL SAVE (KLUN, YD%F_W_T1)
ENDIF
LF_W_T9 = ASSOCIATED (YD%F_W_T9)
WRITE (KLUN) LF_W_T9
IF (LF_W_T9) THEN
  CALL SAVE (KLUN, YD%F_W_T9)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_SNOWG (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_SNOWG), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_A_T0, LF_A_T1, LF_A_T9, LF_F_T0, LF_F_T1, LF_F_T9, LF_R_T0, LF_R_T1, LF_R_T9, LF_T_T0
LOGICAL :: LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9
NULLIFY (YD%PF_T0)
NULLIFY (YD%PF_T1)
NULLIFY (YD%PF_T9)
NULLIFY (YD%PA_T0)
NULLIFY (YD%PA_T1)
NULLIFY (YD%PA_T9)
NULLIFY (YD%PR_T0)
NULLIFY (YD%PR_T1)
NULLIFY (YD%PR_T9)
NULLIFY (YD%PT_T0)
NULLIFY (YD%PT_T1)
NULLIFY (YD%PT_T9)
NULLIFY (YD%PW_T0)
NULLIFY (YD%PW_T1)
NULLIFY (YD%PW_T9)
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_F_T0
IF (LF_F_T0) THEN
  CALL LOAD (KLUN, YD%F_F_T0)
ELSE
  NULLIFY (YD%F_F_T0)
ENDIF
READ (KLUN) LF_F_T1
IF (LF_F_T1) THEN
  CALL LOAD (KLUN, YD%F_F_T1)
ELSE
  NULLIFY (YD%F_F_T1)
ENDIF
READ (KLUN) LF_F_T9
IF (LF_F_T9) THEN
  CALL LOAD (KLUN, YD%F_F_T9)
ELSE
  NULLIFY (YD%F_F_T9)
ENDIF
READ (KLUN) LF_A_T0
IF (LF_A_T0) THEN
  CALL LOAD (KLUN, YD%F_A_T0)
ELSE
  NULLIFY (YD%F_A_T0)
ENDIF
READ (KLUN) LF_A_T1
IF (LF_A_T1) THEN
  CALL LOAD (KLUN, YD%F_A_T1)
ELSE
  NULLIFY (YD%F_A_T1)
ENDIF
READ (KLUN) LF_A_T9
IF (LF_A_T9) THEN
  CALL LOAD (KLUN, YD%F_A_T9)
ELSE
  NULLIFY (YD%F_A_T9)
ENDIF
READ (KLUN) LF_R_T0
IF (LF_R_T0) THEN
  CALL LOAD (KLUN, YD%F_R_T0)
ELSE
  NULLIFY (YD%F_R_T0)
ENDIF
READ (KLUN) LF_R_T1
IF (LF_R_T1) THEN
  CALL LOAD (KLUN, YD%F_R_T1)
ELSE
  NULLIFY (YD%F_R_T1)
ENDIF
READ (KLUN) LF_R_T9
IF (LF_R_T9) THEN
  CALL LOAD (KLUN, YD%F_R_T9)
ELSE
  NULLIFY (YD%F_R_T9)
ENDIF
READ (KLUN) LF_T_T0
IF (LF_T_T0) THEN
  CALL LOAD (KLUN, YD%F_T_T0)
ELSE
  NULLIFY (YD%F_T_T0)
ENDIF
READ (KLUN) LF_T_T1
IF (LF_T_T1) THEN
  CALL LOAD (KLUN, YD%F_T_T1)
ELSE
  NULLIFY (YD%F_T_T1)
ENDIF
READ (KLUN) LF_T_T9
IF (LF_T_T9) THEN
  CALL LOAD (KLUN, YD%F_T_T9)
ELSE
  NULLIFY (YD%F_T_T9)
ENDIF
READ (KLUN) LF_W_T0
IF (LF_W_T0) THEN
  CALL LOAD (KLUN, YD%F_W_T0)
ELSE
  NULLIFY (YD%F_W_T0)
ENDIF
READ (KLUN) LF_W_T1
IF (LF_W_T1) THEN
  CALL LOAD (KLUN, YD%F_W_T1)
ELSE
  NULLIFY (YD%F_W_T1)
ENDIF
READ (KLUN) LF_W_T9
IF (LF_W_T9) THEN
  CALL LOAD (KLUN, YD%F_W_T9)
ELSE
  NULLIFY (YD%F_W_T9)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE






END MODULE
MODULE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD

USE SURFACE_VIEWS_PROGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_RESVR

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_RESVR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_RESVR
END INTERFACE




CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_RESVR (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_RESVR), INTENT (IN), TARGET :: YD
LOGICAL :: LF_FC_T0, LF_FC_T1, LF_FC_T9, LF_FP1_T0, LF_FP1_T1, LF_FP1_T9, LF_IC_T0, LF_IC_T1, LF_IC_T9, LF_T_T0
LOGICAL :: LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9
LF_T_T0 = ASSOCIATED (YD%F_T_T0)
WRITE (KLUN) LF_T_T0
IF (LF_T_T0) THEN
  CALL SAVE (KLUN, YD%F_T_T0)
ENDIF
LF_T_T1 = ASSOCIATED (YD%F_T_T1)
WRITE (KLUN) LF_T_T1
IF (LF_T_T1) THEN
  CALL SAVE (KLUN, YD%F_T_T1)
ENDIF
LF_T_T9 = ASSOCIATED (YD%F_T_T9)
WRITE (KLUN) LF_T_T9
IF (LF_T_T9) THEN
  CALL SAVE (KLUN, YD%F_T_T9)
ENDIF
LF_W_T0 = ASSOCIATED (YD%F_W_T0)
WRITE (KLUN) LF_W_T0
IF (LF_W_T0) THEN
  CALL SAVE (KLUN, YD%F_W_T0)
ENDIF
LF_W_T1 = ASSOCIATED (YD%F_W_T1)
WRITE (KLUN) LF_W_T1
IF (LF_W_T1) THEN
  CALL SAVE (KLUN, YD%F_W_T1)
ENDIF
LF_W_T9 = ASSOCIATED (YD%F_W_T9)
WRITE (KLUN) LF_W_T9
IF (LF_W_T9) THEN
  CALL SAVE (KLUN, YD%F_W_T9)
ENDIF
LF_FC_T0 = ASSOCIATED (YD%F_FC_T0)
WRITE (KLUN) LF_FC_T0
IF (LF_FC_T0) THEN
  CALL SAVE (KLUN, YD%F_FC_T0)
ENDIF
LF_FC_T1 = ASSOCIATED (YD%F_FC_T1)
WRITE (KLUN) LF_FC_T1
IF (LF_FC_T1) THEN
  CALL SAVE (KLUN, YD%F_FC_T1)
ENDIF
LF_FC_T9 = ASSOCIATED (YD%F_FC_T9)
WRITE (KLUN) LF_FC_T9
IF (LF_FC_T9) THEN
  CALL SAVE (KLUN, YD%F_FC_T9)
ENDIF
LF_IC_T0 = ASSOCIATED (YD%F_IC_T0)
WRITE (KLUN) LF_IC_T0
IF (LF_IC_T0) THEN
  CALL SAVE (KLUN, YD%F_IC_T0)
ENDIF
LF_IC_T1 = ASSOCIATED (YD%F_IC_T1)
WRITE (KLUN) LF_IC_T1
IF (LF_IC_T1) THEN
  CALL SAVE (KLUN, YD%F_IC_T1)
ENDIF
LF_IC_T9 = ASSOCIATED (YD%F_IC_T9)
WRITE (KLUN) LF_IC_T9
IF (LF_IC_T9) THEN
  CALL SAVE (KLUN, YD%F_IC_T9)
ENDIF
LF_FP1_T0 = ASSOCIATED (YD%F_FP1_T0)
WRITE (KLUN) LF_FP1_T0
IF (LF_FP1_T0) THEN
  CALL SAVE (KLUN, YD%F_FP1_T0)
ENDIF
LF_FP1_T1 = ASSOCIATED (YD%F_FP1_T1)
WRITE (KLUN) LF_FP1_T1
IF (LF_FP1_T1) THEN
  CALL SAVE (KLUN, YD%F_FP1_T1)
ENDIF
LF_FP1_T9 = ASSOCIATED (YD%F_FP1_T9)
WRITE (KLUN) LF_FP1_T9
IF (LF_FP1_T9) THEN
  CALL SAVE (KLUN, YD%F_FP1_T9)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_RESVR (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_RESVR), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_FC_T0, LF_FC_T1, LF_FC_T9, LF_FP1_T0, LF_FP1_T1, LF_FP1_T9, LF_IC_T0, LF_IC_T1, LF_IC_T9, LF_T_T0
LOGICAL :: LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9
NULLIFY (YD%PT_T0)
NULLIFY (YD%PT_T1)
NULLIFY (YD%PT_T9)
NULLIFY (YD%PW_T0)
NULLIFY (YD%PW_T1)
NULLIFY (YD%PW_T9)
NULLIFY (YD%PFC_T0)
NULLIFY (YD%PFC_T1)
NULLIFY (YD%PFC_T9)
NULLIFY (YD%PIC_T0)
NULLIFY (YD%PIC_T1)
NULLIFY (YD%PIC_T9)
NULLIFY (YD%PFP1_T0)
NULLIFY (YD%PFP1_T1)
NULLIFY (YD%PFP1_T9)
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_T_T0
IF (LF_T_T0) THEN
  CALL LOAD (KLUN, YD%F_T_T0)
ELSE
  NULLIFY (YD%F_T_T0)
ENDIF
READ (KLUN) LF_T_T1
IF (LF_T_T1) THEN
  CALL LOAD (KLUN, YD%F_T_T1)
ELSE
  NULLIFY (YD%F_T_T1)
ENDIF
READ (KLUN) LF_T_T9
IF (LF_T_T9) THEN
  CALL LOAD (KLUN, YD%F_T_T9)
ELSE
  NULLIFY (YD%F_T_T9)
ENDIF
READ (KLUN) LF_W_T0
IF (LF_W_T0) THEN
  CALL LOAD (KLUN, YD%F_W_T0)
ELSE
  NULLIFY (YD%F_W_T0)
ENDIF
READ (KLUN) LF_W_T1
IF (LF_W_T1) THEN
  CALL LOAD (KLUN, YD%F_W_T1)
ELSE
  NULLIFY (YD%F_W_T1)
ENDIF
READ (KLUN) LF_W_T9
IF (LF_W_T9) THEN
  CALL LOAD (KLUN, YD%F_W_T9)
ELSE
  NULLIFY (YD%F_W_T9)
ENDIF
READ (KLUN) LF_FC_T0
IF (LF_FC_T0) THEN
  CALL LOAD (KLUN, YD%F_FC_T0)
ELSE
  NULLIFY (YD%F_FC_T0)
ENDIF
READ (KLUN) LF_FC_T1
IF (LF_FC_T1) THEN
  CALL LOAD (KLUN, YD%F_FC_T1)
ELSE
  NULLIFY (YD%F_FC_T1)
ENDIF
READ (KLUN) LF_FC_T9
IF (LF_FC_T9) THEN
  CALL LOAD (KLUN, YD%F_FC_T9)
ELSE
  NULLIFY (YD%F_FC_T9)
ENDIF
READ (KLUN) LF_IC_T0
IF (LF_IC_T0) THEN
  CALL LOAD (KLUN, YD%F_IC_T0)
ELSE
  NULLIFY (YD%F_IC_T0)
ENDIF
READ (KLUN) LF_IC_T1
IF (LF_IC_T1) THEN
  CALL LOAD (KLUN, YD%F_IC_T1)
ELSE
  NULLIFY (YD%F_IC_T1)
ENDIF
READ (KLUN) LF_IC_T9
IF (LF_IC_T9) THEN
  CALL LOAD (KLUN, YD%F_IC_T9)
ELSE
  NULLIFY (YD%F_IC_T9)
ENDIF
READ (KLUN) LF_FP1_T0
IF (LF_FP1_T0) THEN
  CALL LOAD (KLUN, YD%F_FP1_T0)
ELSE
  NULLIFY (YD%F_FP1_T0)
ENDIF
READ (KLUN) LF_FP1_T1
IF (LF_FP1_T1) THEN
  CALL LOAD (KLUN, YD%F_FP1_T1)
ELSE
  NULLIFY (YD%F_FP1_T1)
ENDIF
READ (KLUN) LF_FP1_T9
IF (LF_FP1_T9) THEN
  CALL LOAD (KLUN, YD%F_FP1_T9)
ELSE
  NULLIFY (YD%F_FP1_T9)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE






END MODULE
MODULE UTIL_SURFACE_VIEW_GROUP_CLS_MOD

USE SURFACE_VIEWS_PROGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_CLS

INTERFACE SAVE
MODULE PROCEDURE SAVE_SURFACE_VIEW_GROUP_CLS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SURFACE_VIEW_GROUP_CLS
END INTERFACE




CONTAINS

SUBROUTINE SAVE_SURFACE_VIEW_GROUP_CLS (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_CLS), INTENT (IN), TARGET :: YD
LOGICAL :: LF_HUCLS_T0, LF_HUCLS_T1, LF_HUCLS_T9, LF_NUCLS_T0, LF_NUCLS_T1, LF_NUCLS_T9, LF_NVCLS_T0, LF_NVCLS_T1, LF_NVCLS_T9, LF_TCLS_T0
LOGICAL :: LF_TCLS_T1, LF_TCLS_T9, LF_UCLS_T0, LF_UCLS_T1, LF_UCLS_T9, LF_VCLS_T0, LF_VCLS_T1, LF_VCLS_T9
LF_TCLS_T0 = ASSOCIATED (YD%F_TCLS_T0)
WRITE (KLUN) LF_TCLS_T0
IF (LF_TCLS_T0) THEN
  CALL SAVE (KLUN, YD%F_TCLS_T0)
ENDIF
LF_TCLS_T1 = ASSOCIATED (YD%F_TCLS_T1)
WRITE (KLUN) LF_TCLS_T1
IF (LF_TCLS_T1) THEN
  CALL SAVE (KLUN, YD%F_TCLS_T1)
ENDIF
LF_TCLS_T9 = ASSOCIATED (YD%F_TCLS_T9)
WRITE (KLUN) LF_TCLS_T9
IF (LF_TCLS_T9) THEN
  CALL SAVE (KLUN, YD%F_TCLS_T9)
ENDIF
LF_HUCLS_T0 = ASSOCIATED (YD%F_HUCLS_T0)
WRITE (KLUN) LF_HUCLS_T0
IF (LF_HUCLS_T0) THEN
  CALL SAVE (KLUN, YD%F_HUCLS_T0)
ENDIF
LF_HUCLS_T1 = ASSOCIATED (YD%F_HUCLS_T1)
WRITE (KLUN) LF_HUCLS_T1
IF (LF_HUCLS_T1) THEN
  CALL SAVE (KLUN, YD%F_HUCLS_T1)
ENDIF
LF_HUCLS_T9 = ASSOCIATED (YD%F_HUCLS_T9)
WRITE (KLUN) LF_HUCLS_T9
IF (LF_HUCLS_T9) THEN
  CALL SAVE (KLUN, YD%F_HUCLS_T9)
ENDIF
LF_UCLS_T0 = ASSOCIATED (YD%F_UCLS_T0)
WRITE (KLUN) LF_UCLS_T0
IF (LF_UCLS_T0) THEN
  CALL SAVE (KLUN, YD%F_UCLS_T0)
ENDIF
LF_UCLS_T1 = ASSOCIATED (YD%F_UCLS_T1)
WRITE (KLUN) LF_UCLS_T1
IF (LF_UCLS_T1) THEN
  CALL SAVE (KLUN, YD%F_UCLS_T1)
ENDIF
LF_UCLS_T9 = ASSOCIATED (YD%F_UCLS_T9)
WRITE (KLUN) LF_UCLS_T9
IF (LF_UCLS_T9) THEN
  CALL SAVE (KLUN, YD%F_UCLS_T9)
ENDIF
LF_VCLS_T0 = ASSOCIATED (YD%F_VCLS_T0)
WRITE (KLUN) LF_VCLS_T0
IF (LF_VCLS_T0) THEN
  CALL SAVE (KLUN, YD%F_VCLS_T0)
ENDIF
LF_VCLS_T1 = ASSOCIATED (YD%F_VCLS_T1)
WRITE (KLUN) LF_VCLS_T1
IF (LF_VCLS_T1) THEN
  CALL SAVE (KLUN, YD%F_VCLS_T1)
ENDIF
LF_VCLS_T9 = ASSOCIATED (YD%F_VCLS_T9)
WRITE (KLUN) LF_VCLS_T9
IF (LF_VCLS_T9) THEN
  CALL SAVE (KLUN, YD%F_VCLS_T9)
ENDIF
LF_NUCLS_T0 = ASSOCIATED (YD%F_NUCLS_T0)
WRITE (KLUN) LF_NUCLS_T0
IF (LF_NUCLS_T0) THEN
  CALL SAVE (KLUN, YD%F_NUCLS_T0)
ENDIF
LF_NUCLS_T1 = ASSOCIATED (YD%F_NUCLS_T1)
WRITE (KLUN) LF_NUCLS_T1
IF (LF_NUCLS_T1) THEN
  CALL SAVE (KLUN, YD%F_NUCLS_T1)
ENDIF
LF_NUCLS_T9 = ASSOCIATED (YD%F_NUCLS_T9)
WRITE (KLUN) LF_NUCLS_T9
IF (LF_NUCLS_T9) THEN
  CALL SAVE (KLUN, YD%F_NUCLS_T9)
ENDIF
LF_NVCLS_T0 = ASSOCIATED (YD%F_NVCLS_T0)
WRITE (KLUN) LF_NVCLS_T0
IF (LF_NVCLS_T0) THEN
  CALL SAVE (KLUN, YD%F_NVCLS_T0)
ENDIF
LF_NVCLS_T1 = ASSOCIATED (YD%F_NVCLS_T1)
WRITE (KLUN) LF_NVCLS_T1
IF (LF_NVCLS_T1) THEN
  CALL SAVE (KLUN, YD%F_NVCLS_T1)
ENDIF
LF_NVCLS_T9 = ASSOCIATED (YD%F_NVCLS_T9)
WRITE (KLUN) LF_NVCLS_T9
IF (LF_NVCLS_T9) THEN
  CALL SAVE (KLUN, YD%F_NVCLS_T9)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SURFACE_VIEW_GROUP_CLS (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SURFACE_VIEW_GROUP_CLS), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_HUCLS_T0, LF_HUCLS_T1, LF_HUCLS_T9, LF_NUCLS_T0, LF_NUCLS_T1, LF_NUCLS_T9, LF_NVCLS_T0, LF_NVCLS_T1, LF_NVCLS_T9, LF_TCLS_T0
LOGICAL :: LF_TCLS_T1, LF_TCLS_T9, LF_UCLS_T0, LF_UCLS_T1, LF_UCLS_T9, LF_VCLS_T0, LF_VCLS_T1, LF_VCLS_T9
NULLIFY (YD%PTCLS_T0)
NULLIFY (YD%PTCLS_T1)
NULLIFY (YD%PTCLS_T9)
NULLIFY (YD%PHUCLS_T0)
NULLIFY (YD%PHUCLS_T1)
NULLIFY (YD%PHUCLS_T9)
NULLIFY (YD%PUCLS_T0)
NULLIFY (YD%PUCLS_T1)
NULLIFY (YD%PUCLS_T9)
NULLIFY (YD%PVCLS_T0)
NULLIFY (YD%PVCLS_T1)
NULLIFY (YD%PVCLS_T9)
NULLIFY (YD%PNUCLS_T0)
NULLIFY (YD%PNUCLS_T1)
NULLIFY (YD%PNUCLS_T9)
NULLIFY (YD%PNVCLS_T0)
NULLIFY (YD%PNVCLS_T1)
NULLIFY (YD%PNVCLS_T9)
NULLIFY (YD%PGROUP)
NULLIFY (YD%VARIABLE_GROUP)
READ (KLUN) LF_TCLS_T0
IF (LF_TCLS_T0) THEN
  CALL LOAD (KLUN, YD%F_TCLS_T0)
ELSE
  NULLIFY (YD%F_TCLS_T0)
ENDIF
READ (KLUN) LF_TCLS_T1
IF (LF_TCLS_T1) THEN
  CALL LOAD (KLUN, YD%F_TCLS_T1)
ELSE
  NULLIFY (YD%F_TCLS_T1)
ENDIF
READ (KLUN) LF_TCLS_T9
IF (LF_TCLS_T9) THEN
  CALL LOAD (KLUN, YD%F_TCLS_T9)
ELSE
  NULLIFY (YD%F_TCLS_T9)
ENDIF
READ (KLUN) LF_HUCLS_T0
IF (LF_HUCLS_T0) THEN
  CALL LOAD (KLUN, YD%F_HUCLS_T0)
ELSE
  NULLIFY (YD%F_HUCLS_T0)
ENDIF
READ (KLUN) LF_HUCLS_T1
IF (LF_HUCLS_T1) THEN
  CALL LOAD (KLUN, YD%F_HUCLS_T1)
ELSE
  NULLIFY (YD%F_HUCLS_T1)
ENDIF
READ (KLUN) LF_HUCLS_T9
IF (LF_HUCLS_T9) THEN
  CALL LOAD (KLUN, YD%F_HUCLS_T9)
ELSE
  NULLIFY (YD%F_HUCLS_T9)
ENDIF
READ (KLUN) LF_UCLS_T0
IF (LF_UCLS_T0) THEN
  CALL LOAD (KLUN, YD%F_UCLS_T0)
ELSE
  NULLIFY (YD%F_UCLS_T0)
ENDIF
READ (KLUN) LF_UCLS_T1
IF (LF_UCLS_T1) THEN
  CALL LOAD (KLUN, YD%F_UCLS_T1)
ELSE
  NULLIFY (YD%F_UCLS_T1)
ENDIF
READ (KLUN) LF_UCLS_T9
IF (LF_UCLS_T9) THEN
  CALL LOAD (KLUN, YD%F_UCLS_T9)
ELSE
  NULLIFY (YD%F_UCLS_T9)
ENDIF
READ (KLUN) LF_VCLS_T0
IF (LF_VCLS_T0) THEN
  CALL LOAD (KLUN, YD%F_VCLS_T0)
ELSE
  NULLIFY (YD%F_VCLS_T0)
ENDIF
READ (KLUN) LF_VCLS_T1
IF (LF_VCLS_T1) THEN
  CALL LOAD (KLUN, YD%F_VCLS_T1)
ELSE
  NULLIFY (YD%F_VCLS_T1)
ENDIF
READ (KLUN) LF_VCLS_T9
IF (LF_VCLS_T9) THEN
  CALL LOAD (KLUN, YD%F_VCLS_T9)
ELSE
  NULLIFY (YD%F_VCLS_T9)
ENDIF
READ (KLUN) LF_NUCLS_T0
IF (LF_NUCLS_T0) THEN
  CALL LOAD (KLUN, YD%F_NUCLS_T0)
ELSE
  NULLIFY (YD%F_NUCLS_T0)
ENDIF
READ (KLUN) LF_NUCLS_T1
IF (LF_NUCLS_T1) THEN
  CALL LOAD (KLUN, YD%F_NUCLS_T1)
ELSE
  NULLIFY (YD%F_NUCLS_T1)
ENDIF
READ (KLUN) LF_NUCLS_T9
IF (LF_NUCLS_T9) THEN
  CALL LOAD (KLUN, YD%F_NUCLS_T9)
ELSE
  NULLIFY (YD%F_NUCLS_T9)
ENDIF
READ (KLUN) LF_NVCLS_T0
IF (LF_NVCLS_T0) THEN
  CALL LOAD (KLUN, YD%F_NVCLS_T0)
ELSE
  NULLIFY (YD%F_NVCLS_T0)
ENDIF
READ (KLUN) LF_NVCLS_T1
IF (LF_NVCLS_T1) THEN
  CALL LOAD (KLUN, YD%F_NVCLS_T1)
ELSE
  NULLIFY (YD%F_NVCLS_T1)
ENDIF
READ (KLUN) LF_NVCLS_T9
IF (LF_NVCLS_T9) THEN
  CALL LOAD (KLUN, YD%F_NVCLS_T9)
ELSE
  NULLIFY (YD%F_NVCLS_T9)
ENDIF
NULLIFY (YD%F_GROUP)
END SUBROUTINE






END MODULE
