MODULE UTIL_TMDDH_MOD

USE YOMMDDH, ONLY : TMDDH


INTERFACE SAVE
MODULE PROCEDURE SAVE_TMDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMDDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TMDDH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TMDDH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TMDDH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LHDSF, LHDSFDU, LHDSFLA, LNDDHI, LNDDHLA, LNDDHPU, LNLRDDH, LNLXDDH, LNURDDH, LNUXDDH

WRITE (KLUN) YD%NDHKD
WRITE (KLUN) YD%NDHNPU
WRITE (KLUN) YD%NDHBPU
WRITE (KLUN) YD%NDHBPX
WRITE (KLUN) YD%NDHNOM
WRITE (KLUN) YD%NDHDDX
WRITE (KLUN) YD%NDHIDH
WRITE (KLUN) YD%NDHCS
WRITE (KLUN) YD%NDHCV
WRITE (KLUN) YD%NDHCVSU
WRITE (KLUN) YD%NDHCSSU
WRITE (KLUN) YD%NDHCVSUN
WRITE (KLUN) YD%NDHCVSUL
WRITE (KLUN) YD%NDHVV
WRITE (KLUN) YD%NDHFVD
WRITE (KLUN) YD%NDHFVP
WRITE (KLUN) YD%NDHVS
WRITE (KLUN) YD%NDHFSD
WRITE (KLUN) YD%NDHFSP
WRITE (KLUN) YD%NDHFFS
WRITE (KLUN) YD%NDHVFS
WRITE (KLUN) YD%NFSVAR_AERO
WRITE (KLUN) YD%NFSFLX_AERO
WRITE (KLUN) YD%NDHVTLS
WRITE (KLUN) YD%NDHFTLS
WRITE (KLUN) YD%NDHVTSS
WRITE (KLUN) YD%NDHFTSS
WRITE (KLUN) YD%NDHVTTS
WRITE (KLUN) YD%NDHFTTS
WRITE (KLUN) YD%NDHVTIS
WRITE (KLUN) YD%NDHFTIS
WRITE (KLUN) YD%NDHVSSS
WRITE (KLUN) YD%NDHFSSS
WRITE (KLUN) YD%NDHVIIS
WRITE (KLUN) YD%NDHFIIS
WRITE (KLUN) YD%NDHVWLS
WRITE (KLUN) YD%NDHFWLS
WRITE (KLUN) YD%NDHTHK
WRITE (KLUN) YD%NDHVHK
WRITE (KLUN) YD%NDHFHKD
WRITE (KLUN) YD%NDHFHKP
WRITE (KLUN) YD%NDHTMC
WRITE (KLUN) YD%NDHVMC
WRITE (KLUN) YD%NDHFMCD
WRITE (KLUN) YD%NDHFMCP
WRITE (KLUN) YD%NDHTEN
WRITE (KLUN) YD%NDHVEN
WRITE (KLUN) YD%NDHFEND
WRITE (KLUN) YD%NDHFENP
WRITE (KLUN) YD%NDHAVD
WRITE (KLUN) YD%NDHBVD
WRITE (KLUN) YD%NDHAVP
WRITE (KLUN) YD%NDHBVP
WRITE (KLUN) YD%NDHAHKD
WRITE (KLUN) YD%NDHBHKD
WRITE (KLUN) YD%NDHAHKP
WRITE (KLUN) YD%NDHBHKP
WRITE (KLUN) YD%NDHAMCD
WRITE (KLUN) YD%NDHBMCD
WRITE (KLUN) YD%NDHAMCP
WRITE (KLUN) YD%NDHBMCP
WRITE (KLUN) YD%NDHAEND
WRITE (KLUN) YD%NDHBEND
WRITE (KLUN) YD%NDHAENP
WRITE (KLUN) YD%NDHBENP
WRITE (KLUN) YD%NDHZPR
WRITE (KLUN) YD%FNODDH
WRITE (KLUN) YD%BDEDDH
WRITE (KLUN) YD%HDSFGL
LNDDHLA = ALLOCATED (YD%NDDHLA)
WRITE (KLUN) LNDDHLA
IF (LNDDHLA) THEN
  WRITE (KLUN) LBOUND (YD%NDDHLA)
  WRITE (KLUN) UBOUND (YD%NDDHLA)
  WRITE (KLUN) YD%NDDHLA
ENDIF
LNDDHPU = ALLOCATED (YD%NDDHPU)
WRITE (KLUN) LNDDHPU
IF (LNDDHPU) THEN
  WRITE (KLUN) LBOUND (YD%NDDHPU)
  WRITE (KLUN) UBOUND (YD%NDDHPU)
  WRITE (KLUN) YD%NDDHPU
ENDIF
LNDDHI = ALLOCATED (YD%NDDHI)
WRITE (KLUN) LNDDHI
IF (LNDDHI) THEN
  WRITE (KLUN) LBOUND (YD%NDDHI)
  WRITE (KLUN) UBOUND (YD%NDDHI)
  WRITE (KLUN) YD%NDDHI
ENDIF
LNLRDDH = ALLOCATED (YD%NLRDDH)
WRITE (KLUN) LNLRDDH
IF (LNLRDDH) THEN
  WRITE (KLUN) LBOUND (YD%NLRDDH)
  WRITE (KLUN) UBOUND (YD%NLRDDH)
  WRITE (KLUN) YD%NLRDDH
ENDIF
LNURDDH = ALLOCATED (YD%NURDDH)
WRITE (KLUN) LNURDDH
IF (LNURDDH) THEN
  WRITE (KLUN) LBOUND (YD%NURDDH)
  WRITE (KLUN) UBOUND (YD%NURDDH)
  WRITE (KLUN) YD%NURDDH
ENDIF
LNLXDDH = ALLOCATED (YD%NLXDDH)
WRITE (KLUN) LNLXDDH
IF (LNLXDDH) THEN
  WRITE (KLUN) LBOUND (YD%NLXDDH)
  WRITE (KLUN) UBOUND (YD%NLXDDH)
  WRITE (KLUN) YD%NLXDDH
ENDIF
LNUXDDH = ALLOCATED (YD%NUXDDH)
WRITE (KLUN) LNUXDDH
IF (LNUXDDH) THEN
  WRITE (KLUN) LBOUND (YD%NUXDDH)
  WRITE (KLUN) UBOUND (YD%NUXDDH)
  WRITE (KLUN) YD%NUXDDH
ENDIF
LHDSFLA = ALLOCATED (YD%HDSFLA)
WRITE (KLUN) LHDSFLA
IF (LHDSFLA) THEN
  WRITE (KLUN) LBOUND (YD%HDSFLA)
  WRITE (KLUN) UBOUND (YD%HDSFLA)
  WRITE (KLUN) YD%HDSFLA
ENDIF
LHDSFDU = ALLOCATED (YD%HDSFDU)
WRITE (KLUN) LHDSFDU
IF (LHDSFDU) THEN
  WRITE (KLUN) LBOUND (YD%HDSFDU)
  WRITE (KLUN) UBOUND (YD%HDSFDU)
  WRITE (KLUN) YD%HDSFDU
ENDIF
LHDSF = ALLOCATED (YD%HDSF)
WRITE (KLUN) LHDSF
IF (LHDSF) THEN
  WRITE (KLUN) LBOUND (YD%HDSF)
  WRITE (KLUN) UBOUND (YD%HDSF)
  WRITE (KLUN) YD%HDSF
ENDIF
WRITE (KLUN) YD%NDIMHDGFL
WRITE (KLUN) YD%NDIMSIGMV
WRITE (KLUN) YD%MSIDDH_U1
WRITE (KLUN) YD%MSIDDH_V1
WRITE (KLUN) YD%MSIDDH_T1
WRITE (KLUN) YD%MSIDDH_PD1
WRITE (KLUN) YD%MSIDDH_VD1
WRITE (KLUN) YD%MSIDDH_U0
WRITE (KLUN) YD%MSIDDH_V0
WRITE (KLUN) YD%MSIDDH_T0
WRITE (KLUN) YD%MSIDDH_PD0
WRITE (KLUN) YD%MSIDDH_VD0
WRITE (KLUN) YD%MSIDDH_U9
WRITE (KLUN) YD%MSIDDH_V9
WRITE (KLUN) YD%MSIDDH_T9
WRITE (KLUN) YD%MSIDDH_PD9
WRITE (KLUN) YD%MSIDDH_VD9
WRITE (KLUN) YD%MHDDDH_U
WRITE (KLUN) YD%MHDDDH_V
WRITE (KLUN) YD%MHDDDH_T
WRITE (KLUN) YD%MHDDDH_Q
WRITE (KLUN) YD%MHDDDH_PD
WRITE (KLUN) YD%MHDDDH_VD
WRITE (KLUN) YD%MHDDDH_NHX
WRITE (KLUN) YD%MSLDDH_U
WRITE (KLUN) YD%MSLDDH_V
WRITE (KLUN) YD%MSLDDH_T
WRITE (KLUN) YD%MSLDDH_PD
WRITE (KLUN) YD%MSLDDH_VD
WRITE (KLUN) YD%MSLDDH_NHX
WRITE (KLUN) YD%CFPATHDDH
WRITE (KLUN) YD%NFIELDS3D_AUTO
WRITE (KLUN) YD%NFIELDS3D_OFFSET
WRITE (KLUN) YD%NFIELDSMAX
WRITE (KLUN) YD%NFIELDS2D_AUTO
WRITE (KLUN) YD%NFIELDS2D_OFFSET
END SUBROUTINE

SUBROUTINE LOAD_TMDDH (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LHDSF, LHDSFDU, LHDSFLA, LNDDHI, LNDDHLA, LNDDHPU, LNLRDDH, LNLXDDH, LNURDDH, LNUXDDH

READ (KLUN) YD%NDHKD
READ (KLUN) YD%NDHNPU
READ (KLUN) YD%NDHBPU
READ (KLUN) YD%NDHBPX
READ (KLUN) YD%NDHNOM
READ (KLUN) YD%NDHDDX
READ (KLUN) YD%NDHIDH
READ (KLUN) YD%NDHCS
READ (KLUN) YD%NDHCV
READ (KLUN) YD%NDHCVSU
READ (KLUN) YD%NDHCSSU
READ (KLUN) YD%NDHCVSUN
READ (KLUN) YD%NDHCVSUL
READ (KLUN) YD%NDHVV
READ (KLUN) YD%NDHFVD
READ (KLUN) YD%NDHFVP
READ (KLUN) YD%NDHVS
READ (KLUN) YD%NDHFSD
READ (KLUN) YD%NDHFSP
READ (KLUN) YD%NDHFFS
READ (KLUN) YD%NDHVFS
READ (KLUN) YD%NFSVAR_AERO
READ (KLUN) YD%NFSFLX_AERO
READ (KLUN) YD%NDHVTLS
READ (KLUN) YD%NDHFTLS
READ (KLUN) YD%NDHVTSS
READ (KLUN) YD%NDHFTSS
READ (KLUN) YD%NDHVTTS
READ (KLUN) YD%NDHFTTS
READ (KLUN) YD%NDHVTIS
READ (KLUN) YD%NDHFTIS
READ (KLUN) YD%NDHVSSS
READ (KLUN) YD%NDHFSSS
READ (KLUN) YD%NDHVIIS
READ (KLUN) YD%NDHFIIS
READ (KLUN) YD%NDHVWLS
READ (KLUN) YD%NDHFWLS
READ (KLUN) YD%NDHTHK
READ (KLUN) YD%NDHVHK
READ (KLUN) YD%NDHFHKD
READ (KLUN) YD%NDHFHKP
READ (KLUN) YD%NDHTMC
READ (KLUN) YD%NDHVMC
READ (KLUN) YD%NDHFMCD
READ (KLUN) YD%NDHFMCP
READ (KLUN) YD%NDHTEN
READ (KLUN) YD%NDHVEN
READ (KLUN) YD%NDHFEND
READ (KLUN) YD%NDHFENP
READ (KLUN) YD%NDHAVD
READ (KLUN) YD%NDHBVD
READ (KLUN) YD%NDHAVP
READ (KLUN) YD%NDHBVP
READ (KLUN) YD%NDHAHKD
READ (KLUN) YD%NDHBHKD
READ (KLUN) YD%NDHAHKP
READ (KLUN) YD%NDHBHKP
READ (KLUN) YD%NDHAMCD
READ (KLUN) YD%NDHBMCD
READ (KLUN) YD%NDHAMCP
READ (KLUN) YD%NDHBMCP
READ (KLUN) YD%NDHAEND
READ (KLUN) YD%NDHBEND
READ (KLUN) YD%NDHAENP
READ (KLUN) YD%NDHBENP
READ (KLUN) YD%NDHZPR
READ (KLUN) YD%FNODDH
READ (KLUN) YD%BDEDDH
READ (KLUN) YD%HDSFGL
READ (KLUN) LNDDHLA
IF (LNDDHLA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDDHLA (IL1(1):IU1(1)))
  READ (KLUN) YD%NDDHLA
ENDIF
READ (KLUN) LNDDHPU
IF (LNDDHPU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NDDHPU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NDDHPU
ENDIF
READ (KLUN) LNDDHI
IF (LNDDHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDDHI (IL1(1):IU1(1)))
  READ (KLUN) YD%NDDHI
ENDIF
READ (KLUN) LNLRDDH
IF (LNLRDDH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLRDDH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLRDDH
ENDIF
READ (KLUN) LNURDDH
IF (LNURDDH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%NURDDH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%NURDDH
ENDIF
READ (KLUN) LNLXDDH
IF (LNLXDDH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLXDDH (IL1(1):IU1(1)))
  READ (KLUN) YD%NLXDDH
ENDIF
READ (KLUN) LNUXDDH
IF (LNUXDDH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NUXDDH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NUXDDH
ENDIF
READ (KLUN) LHDSFLA
IF (LHDSFLA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%HDSFLA (IL1(1):IU1(1)))
  READ (KLUN) YD%HDSFLA
ENDIF
READ (KLUN) LHDSFDU
IF (LHDSFDU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%HDSFDU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%HDSFDU
ENDIF
READ (KLUN) LHDSF
IF (LHDSF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%HDSF (IL1(1):IU1(1)))
  READ (KLUN) YD%HDSF
ENDIF
READ (KLUN) YD%NDIMHDGFL
READ (KLUN) YD%NDIMSIGMV
READ (KLUN) YD%MSIDDH_U1
READ (KLUN) YD%MSIDDH_V1
READ (KLUN) YD%MSIDDH_T1
READ (KLUN) YD%MSIDDH_PD1
READ (KLUN) YD%MSIDDH_VD1
READ (KLUN) YD%MSIDDH_U0
READ (KLUN) YD%MSIDDH_V0
READ (KLUN) YD%MSIDDH_T0
READ (KLUN) YD%MSIDDH_PD0
READ (KLUN) YD%MSIDDH_VD0
READ (KLUN) YD%MSIDDH_U9
READ (KLUN) YD%MSIDDH_V9
READ (KLUN) YD%MSIDDH_T9
READ (KLUN) YD%MSIDDH_PD9
READ (KLUN) YD%MSIDDH_VD9
READ (KLUN) YD%MHDDDH_U
READ (KLUN) YD%MHDDDH_V
READ (KLUN) YD%MHDDDH_T
READ (KLUN) YD%MHDDDH_Q
READ (KLUN) YD%MHDDDH_PD
READ (KLUN) YD%MHDDDH_VD
READ (KLUN) YD%MHDDDH_NHX
READ (KLUN) YD%MSLDDH_U
READ (KLUN) YD%MSLDDH_V
READ (KLUN) YD%MSLDDH_T
READ (KLUN) YD%MSLDDH_PD
READ (KLUN) YD%MSLDDH_VD
READ (KLUN) YD%MSLDDH_NHX
READ (KLUN) YD%CFPATHDDH
READ (KLUN) YD%NFIELDS3D_AUTO
READ (KLUN) YD%NFIELDS3D_OFFSET
READ (KLUN) YD%NFIELDSMAX
READ (KLUN) YD%NFIELDS2D_AUTO
READ (KLUN) YD%NFIELDS2D_OFFSET
END SUBROUTINE


SUBROUTINE COPY_TMDDH (YD, LDCREATED)
IMPLICIT NONE
TYPE (TMDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LHDSF, LHDSFDU, LHDSFLA, LNDDHI, LNDDHLA, LNDDHPU, LNLRDDH, LNLXDDH, LNURDDH, LNUXDDH

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





































































LNDDHLA = ALLOCATED (YD%NDDHLA)
IF (LNDDHLA) THEN
  !$acc enter data create (YD%NDDHLA)
  !$acc update device (YD%NDDHLA)
  !$acc enter data attach (YD%NDDHLA)
ENDIF

LNDDHPU = ALLOCATED (YD%NDDHPU)
IF (LNDDHPU) THEN
  !$acc enter data create (YD%NDDHPU)
  !$acc update device (YD%NDDHPU)
  !$acc enter data attach (YD%NDDHPU)
ENDIF

LNDDHI = ALLOCATED (YD%NDDHI)
IF (LNDDHI) THEN
  !$acc enter data create (YD%NDDHI)
  !$acc update device (YD%NDDHI)
  !$acc enter data attach (YD%NDDHI)
ENDIF

LNLRDDH = ALLOCATED (YD%NLRDDH)
IF (LNLRDDH) THEN
  !$acc enter data create (YD%NLRDDH)
  !$acc update device (YD%NLRDDH)
  !$acc enter data attach (YD%NLRDDH)
ENDIF

LNURDDH = ALLOCATED (YD%NURDDH)
IF (LNURDDH) THEN
  !$acc enter data create (YD%NURDDH)
  !$acc update device (YD%NURDDH)
  !$acc enter data attach (YD%NURDDH)
ENDIF

LNLXDDH = ALLOCATED (YD%NLXDDH)
IF (LNLXDDH) THEN
  !$acc enter data create (YD%NLXDDH)
  !$acc update device (YD%NLXDDH)
  !$acc enter data attach (YD%NLXDDH)
ENDIF

LNUXDDH = ALLOCATED (YD%NUXDDH)
IF (LNUXDDH) THEN
  !$acc enter data create (YD%NUXDDH)
  !$acc update device (YD%NUXDDH)
  !$acc enter data attach (YD%NUXDDH)
ENDIF

LHDSFLA = ALLOCATED (YD%HDSFLA)
IF (LHDSFLA) THEN
  !$acc enter data create (YD%HDSFLA)
  !$acc update device (YD%HDSFLA)
  !$acc enter data attach (YD%HDSFLA)
ENDIF

LHDSFDU = ALLOCATED (YD%HDSFDU)
IF (LHDSFDU) THEN
  !$acc enter data create (YD%HDSFDU)
  !$acc update device (YD%HDSFDU)
  !$acc enter data attach (YD%HDSFDU)
ENDIF

LHDSF = ALLOCATED (YD%HDSF)
IF (LHDSF) THEN
  !$acc enter data create (YD%HDSF)
  !$acc update device (YD%HDSF)
  !$acc enter data attach (YD%HDSF)
ENDIF





































END SUBROUTINE

SUBROUTINE WIPE_TMDDH (YD, LDDELETED)
IMPLICIT NONE
TYPE (TMDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LHDSF, LHDSFDU, LHDSFLA, LNDDHI, LNDDHLA, LNDDHPU, LNLRDDH, LNLXDDH, LNURDDH, LNUXDDH






































































LNDDHLA = ALLOCATED (YD%NDDHLA)
IF (LNDDHLA) THEN
  !$acc exit data detach (YD%NDDHLA)
  !$acc exit data delete (YD%NDDHLA)
ENDIF

LNDDHPU = ALLOCATED (YD%NDDHPU)
IF (LNDDHPU) THEN
  !$acc exit data detach (YD%NDDHPU)
  !$acc exit data delete (YD%NDDHPU)
ENDIF

LNDDHI = ALLOCATED (YD%NDDHI)
IF (LNDDHI) THEN
  !$acc exit data detach (YD%NDDHI)
  !$acc exit data delete (YD%NDDHI)
ENDIF

LNLRDDH = ALLOCATED (YD%NLRDDH)
IF (LNLRDDH) THEN
  !$acc exit data detach (YD%NLRDDH)
  !$acc exit data delete (YD%NLRDDH)
ENDIF

LNURDDH = ALLOCATED (YD%NURDDH)
IF (LNURDDH) THEN
  !$acc exit data detach (YD%NURDDH)
  !$acc exit data delete (YD%NURDDH)
ENDIF

LNLXDDH = ALLOCATED (YD%NLXDDH)
IF (LNLXDDH) THEN
  !$acc exit data detach (YD%NLXDDH)
  !$acc exit data delete (YD%NLXDDH)
ENDIF

LNUXDDH = ALLOCATED (YD%NUXDDH)
IF (LNUXDDH) THEN
  !$acc exit data detach (YD%NUXDDH)
  !$acc exit data delete (YD%NUXDDH)
ENDIF

LHDSFLA = ALLOCATED (YD%HDSFLA)
IF (LHDSFLA) THEN
  !$acc exit data detach (YD%HDSFLA)
  !$acc exit data delete (YD%HDSFLA)
ENDIF

LHDSFDU = ALLOCATED (YD%HDSFDU)
IF (LHDSFDU) THEN
  !$acc exit data detach (YD%HDSFDU)
  !$acc exit data delete (YD%HDSFDU)
ENDIF

LHDSF = ALLOCATED (YD%HDSF)
IF (LHDSF) THEN
  !$acc exit data detach (YD%HDSF)
  !$acc exit data delete (YD%HDSF)
ENDIF





































LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
