MODULE UTIL_TRADIATION_MOD

USE RADIATION_SETUP, ONLY : TRADIATION

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRADIATION
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRADIATION
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRADIATION
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRADIATION
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRADIATION (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADIATION), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NWEIGHT_UV
WRITE (KLUN) YD%IBAND_UV
WRITE (KLUN) YD%WEIGHT_UV
WRITE (KLUN) YD%NWEIGHT_PAR
WRITE (KLUN) YD%IBAND_PAR
WRITE (KLUN) YD%WEIGHT_PAR
WRITE (KLUN) YD%TROP_BG_AER_MASS_EXT
WRITE (KLUN) YD%STRAT_BG_AER_MASS_EXT
END SUBROUTINE

SUBROUTINE LOAD_TRADIATION (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADIATION), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NWEIGHT_UV
READ (KLUN) YD%IBAND_UV
READ (KLUN) YD%WEIGHT_UV
READ (KLUN) YD%NWEIGHT_PAR
READ (KLUN) YD%IBAND_PAR
READ (KLUN) YD%WEIGHT_PAR
READ (KLUN) YD%TROP_BG_AER_MASS_EXT
READ (KLUN) YD%STRAT_BG_AER_MASS_EXT
END SUBROUTINE


SUBROUTINE COPY_TRADIATION (YD, LDCREATED)

IMPLICIT NONE
TYPE (TRADIATION), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF








END SUBROUTINE

SUBROUTINE WIPE_TRADIATION (YD, LDDELETED)

IMPLICIT NONE
TYPE (TRADIATION), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED









LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
