MODULE UTIL_CPG_MISC_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_MISC_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_MISC_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_MISC_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_CPG_MISC_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_MISC_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN, LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL
LF_NEB = ASSOCIATED (YD%F_NEB)
WRITE (KLUN) LF_NEB
IF (LF_NEB) THEN
  CALL SAVE (KLUN, YD%F_NEB)
ENDIF
LF_QLI = ASSOCIATED (YD%F_QLI)
WRITE (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL SAVE (KLUN, YD%F_QLI)
ENDIF
LF_QICE = ASSOCIATED (YD%F_QICE)
WRITE (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL SAVE (KLUN, YD%F_QICE)
ENDIF
LF_QRAIN = ASSOCIATED (YD%F_QRAIN)
WRITE (KLUN) LF_QRAIN
IF (LF_QRAIN) THEN
  CALL SAVE (KLUN, YD%F_QRAIN)
ENDIF
LF_QSNOW = ASSOCIATED (YD%F_QSNOW)
WRITE (KLUN) LF_QSNOW
IF (LF_QSNOW) THEN
  CALL SAVE (KLUN, YD%F_QSNOW)
ENDIF
LF_QGRAUPEL = ASSOCIATED (YD%F_QGRAUPEL)
WRITE (KLUN) LF_QGRAUPEL
IF (LF_QGRAUPEL) THEN
  CALL SAVE (KLUN, YD%F_QGRAUPEL)
ENDIF
LF_RH = ASSOCIATED (YD%F_RH)
WRITE (KLUN) LF_RH
IF (LF_RH) THEN
  CALL SAVE (KLUN, YD%F_RH)
ENDIF
LF_QS = ASSOCIATED (YD%F_QS)
WRITE (KLUN) LF_QS
IF (LF_QS) THEN
  CALL SAVE (KLUN, YD%F_QS)
ENDIF
LF_QSOL = ASSOCIATED (YD%F_QSOL)
WRITE (KLUN) LF_QSOL
IF (LF_QSOL) THEN
  CALL SAVE (KLUN, YD%F_QSOL)
ENDIF
LF_DHSF = ASSOCIATED (YD%F_DHSF)
WRITE (KLUN) LF_DHSF
IF (LF_DHSF) THEN
  CALL SAVE (KLUN, YD%F_DHSF)
ENDIF
LF_CLCT = ASSOCIATED (YD%F_CLCT)
WRITE (KLUN) LF_CLCT
IF (LF_CLCT) THEN
  CALL SAVE (KLUN, YD%F_CLCT)
ENDIF
LF_LSM = ASSOCIATED (YD%F_LSM)
WRITE (KLUN) LF_LSM
IF (LF_LSM) THEN
  CALL SAVE (KLUN, YD%F_LSM)
ENDIF
LF_TSOL = ASSOCIATED (YD%F_TSOL)
WRITE (KLUN) LF_TSOL
IF (LF_TSOL) THEN
  CALL SAVE (KLUN, YD%F_TSOL)
ENDIF
LF_FTCNS = ASSOCIATED (YD%F_FTCNS)
WRITE (KLUN) LF_FTCNS
IF (LF_FTCNS) THEN
  CALL SAVE (KLUN, YD%F_FTCNS)
ENDIF
LF_KOZO = ASSOCIATED (YD%F_KOZO)
WRITE (KLUN) LF_KOZO
IF (LF_KOZO) THEN
  CALL SAVE (KLUN, YD%F_KOZO)
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_CPG_MISC_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_MISC_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN, LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL
NULLIFY (YD%NEB)
READ (KLUN) LF_NEB
IF (LF_NEB) THEN
  CALL LOAD (KLUN, YD%F_NEB)
ELSE
  NULLIFY (YD%F_NEB)
ENDIF
NULLIFY (YD%QLI)
READ (KLUN) LF_QLI
IF (LF_QLI) THEN
  CALL LOAD (KLUN, YD%F_QLI)
ELSE
  NULLIFY (YD%F_QLI)
ENDIF
NULLIFY (YD%QICE)
READ (KLUN) LF_QICE
IF (LF_QICE) THEN
  CALL LOAD (KLUN, YD%F_QICE)
ELSE
  NULLIFY (YD%F_QICE)
ENDIF
NULLIFY (YD%QRAIN)
READ (KLUN) LF_QRAIN
IF (LF_QRAIN) THEN
  CALL LOAD (KLUN, YD%F_QRAIN)
ELSE
  NULLIFY (YD%F_QRAIN)
ENDIF
NULLIFY (YD%QSNOW)
READ (KLUN) LF_QSNOW
IF (LF_QSNOW) THEN
  CALL LOAD (KLUN, YD%F_QSNOW)
ELSE
  NULLIFY (YD%F_QSNOW)
ENDIF
NULLIFY (YD%QGRAUPEL)
READ (KLUN) LF_QGRAUPEL
IF (LF_QGRAUPEL) THEN
  CALL LOAD (KLUN, YD%F_QGRAUPEL)
ELSE
  NULLIFY (YD%F_QGRAUPEL)
ENDIF
NULLIFY (YD%RH)
READ (KLUN) LF_RH
IF (LF_RH) THEN
  CALL LOAD (KLUN, YD%F_RH)
ELSE
  NULLIFY (YD%F_RH)
ENDIF
NULLIFY (YD%QS)
READ (KLUN) LF_QS
IF (LF_QS) THEN
  CALL LOAD (KLUN, YD%F_QS)
ELSE
  NULLIFY (YD%F_QS)
ENDIF
NULLIFY (YD%QSOL)
READ (KLUN) LF_QSOL
IF (LF_QSOL) THEN
  CALL LOAD (KLUN, YD%F_QSOL)
ELSE
  NULLIFY (YD%F_QSOL)
ENDIF
NULLIFY (YD%DHSF)
READ (KLUN) LF_DHSF
IF (LF_DHSF) THEN
  CALL LOAD (KLUN, YD%F_DHSF)
ELSE
  NULLIFY (YD%F_DHSF)
ENDIF
NULLIFY (YD%CLCT)
READ (KLUN) LF_CLCT
IF (LF_CLCT) THEN
  CALL LOAD (KLUN, YD%F_CLCT)
ELSE
  NULLIFY (YD%F_CLCT)
ENDIF
NULLIFY (YD%LSM)
READ (KLUN) LF_LSM
IF (LF_LSM) THEN
  CALL LOAD (KLUN, YD%F_LSM)
ELSE
  NULLIFY (YD%F_LSM)
ENDIF
NULLIFY (YD%TSOL)
READ (KLUN) LF_TSOL
IF (LF_TSOL) THEN
  CALL LOAD (KLUN, YD%F_TSOL)
ELSE
  NULLIFY (YD%F_TSOL)
ENDIF
NULLIFY (YD%FTCNS)
READ (KLUN) LF_FTCNS
IF (LF_FTCNS) THEN
  CALL LOAD (KLUN, YD%F_FTCNS)
ELSE
  NULLIFY (YD%F_FTCNS)
ENDIF
NULLIFY (YD%KOZO)
READ (KLUN) LF_KOZO
IF (LF_KOZO) THEN
  CALL LOAD (KLUN, YD%F_KOZO)
ELSE
  NULLIFY (YD%F_KOZO)
ENDIF
END SUBROUTINE




END MODULE
