MODULE UTIL_SPHYS_HIST_TYPE_MOD

USE YOMSPHYHIST, ONLY : SPHYS_HIST_TYPE


INTERFACE SAVE
MODULE PROCEDURE SAVE_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_SPHYS_HIST_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_SPHYS_HIST_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5

LYA5 = ASSOCIATED (YD%YA5)
WRITE (KLUN) LYA5
IF (LYA5) THEN
  WRITE (KLUN) LBOUND (YD%YA5)
  WRITE (KLUN) UBOUND (YD%YA5)
  WRITE (KLUN) YD%YA5
ENDIF
LYL5 = ASSOCIATED (YD%YL5)
WRITE (KLUN) LYL5
IF (LYL5) THEN
  WRITE (KLUN) LBOUND (YD%YL5)
  WRITE (KLUN) UBOUND (YD%YL5)
  WRITE (KLUN) YD%YL5
ENDIF
LYI5 = ASSOCIATED (YD%YI5)
WRITE (KLUN) LYI5
IF (LYI5) THEN
  WRITE (KLUN) LBOUND (YD%YI5)
  WRITE (KLUN) UBOUND (YD%YI5)
  WRITE (KLUN) YD%YI5
ENDIF
LRADLWM = ASSOCIATED (YD%RADLWM)
WRITE (KLUN) LRADLWM
IF (LRADLWM) THEN
  WRITE (KLUN) LBOUND (YD%RADLWM)
  WRITE (KLUN) UBOUND (YD%RADLWM)
  WRITE (KLUN) YD%RADLWM
ENDIF
LRADLWM5 = ASSOCIATED (YD%RADLWM5)
WRITE (KLUN) LRADLWM5
IF (LRADLWM5) THEN
  WRITE (KLUN) LBOUND (YD%RADLWM5)
  WRITE (KLUN) UBOUND (YD%RADLWM5)
  WRITE (KLUN) YD%RADLWM5
ENDIF
LTGWDWMSU = ASSOCIATED (YD%TGWDWMSU)
WRITE (KLUN) LTGWDWMSU
IF (LTGWDWMSU) THEN
  WRITE (KLUN) LBOUND (YD%TGWDWMSU)
  WRITE (KLUN) UBOUND (YD%TGWDWMSU)
  WRITE (KLUN) YD%TGWDWMSU
ENDIF
LTGWDWMSU5 = ASSOCIATED (YD%TGWDWMSU5)
WRITE (KLUN) LTGWDWMSU5
IF (LTGWDWMSU5) THEN
  WRITE (KLUN) LBOUND (YD%TGWDWMSU5)
  WRITE (KLUN) UBOUND (YD%TGWDWMSU5)
  WRITE (KLUN) YD%TGWDWMSU5
ENDIF
LTGWDWMSV = ASSOCIATED (YD%TGWDWMSV)
WRITE (KLUN) LTGWDWMSV
IF (LTGWDWMSV) THEN
  WRITE (KLUN) LBOUND (YD%TGWDWMSV)
  WRITE (KLUN) UBOUND (YD%TGWDWMSV)
  WRITE (KLUN) YD%TGWDWMSV
ENDIF
LTGWDWMSV5 = ASSOCIATED (YD%TGWDWMSV5)
WRITE (KLUN) LTGWDWMSV5
IF (LTGWDWMSV5) THEN
  WRITE (KLUN) LBOUND (YD%TGWDWMSV5)
  WRITE (KLUN) UBOUND (YD%TGWDWMSV5)
  WRITE (KLUN) YD%TGWDWMSV5
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_SPHYS_HIST_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (SPHYS_HIST_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5

READ (KLUN) LYA5
IF (LYA5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%YA5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%YA5
ELSE
  NULLIFY (YD%YA5)
ENDIF
READ (KLUN) LYL5
IF (LYL5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%YL5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%YL5
ELSE
  NULLIFY (YD%YL5)
ENDIF
READ (KLUN) LYI5
IF (LYI5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%YI5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%YI5
ELSE
  NULLIFY (YD%YI5)
ENDIF
READ (KLUN) LRADLWM
IF (LRADLWM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RADLWM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RADLWM
ELSE
  NULLIFY (YD%RADLWM)
ENDIF
READ (KLUN) LRADLWM5
IF (LRADLWM5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RADLWM5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RADLWM5
ELSE
  NULLIFY (YD%RADLWM5)
ENDIF
READ (KLUN) LTGWDWMSU
IF (LTGWDWMSU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TGWDWMSU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TGWDWMSU
ELSE
  NULLIFY (YD%TGWDWMSU)
ENDIF
READ (KLUN) LTGWDWMSU5
IF (LTGWDWMSU5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TGWDWMSU5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TGWDWMSU5
ELSE
  NULLIFY (YD%TGWDWMSU5)
ENDIF
READ (KLUN) LTGWDWMSV
IF (LTGWDWMSV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TGWDWMSV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TGWDWMSV
ELSE
  NULLIFY (YD%TGWDWMSV)
ENDIF
READ (KLUN) LTGWDWMSV5
IF (LTGWDWMSV5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%TGWDWMSV5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%TGWDWMSV5
ELSE
  NULLIFY (YD%TGWDWMSV5)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_SPHYS_HIST_TYPE (YD, LDCREATED)
IMPLICIT NONE
CLASS (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LYA5 = ASSOCIATED (YD%YA5)
IF (LYA5) THEN
  !$acc enter data create (YD%YA5)
  !$acc update device (YD%YA5)
  !$acc enter data attach (YD%YA5)
ENDIF

LYL5 = ASSOCIATED (YD%YL5)
IF (LYL5) THEN
  !$acc enter data create (YD%YL5)
  !$acc update device (YD%YL5)
  !$acc enter data attach (YD%YL5)
ENDIF

LYI5 = ASSOCIATED (YD%YI5)
IF (LYI5) THEN
  !$acc enter data create (YD%YI5)
  !$acc update device (YD%YI5)
  !$acc enter data attach (YD%YI5)
ENDIF

LRADLWM = ASSOCIATED (YD%RADLWM)
IF (LRADLWM) THEN
  !$acc enter data create (YD%RADLWM)
  !$acc update device (YD%RADLWM)
  !$acc enter data attach (YD%RADLWM)
ENDIF

LRADLWM5 = ASSOCIATED (YD%RADLWM5)
IF (LRADLWM5) THEN
  !$acc enter data create (YD%RADLWM5)
  !$acc update device (YD%RADLWM5)
  !$acc enter data attach (YD%RADLWM5)
ENDIF

LTGWDWMSU = ASSOCIATED (YD%TGWDWMSU)
IF (LTGWDWMSU) THEN
  !$acc enter data create (YD%TGWDWMSU)
  !$acc update device (YD%TGWDWMSU)
  !$acc enter data attach (YD%TGWDWMSU)
ENDIF

LTGWDWMSU5 = ASSOCIATED (YD%TGWDWMSU5)
IF (LTGWDWMSU5) THEN
  !$acc enter data create (YD%TGWDWMSU5)
  !$acc update device (YD%TGWDWMSU5)
  !$acc enter data attach (YD%TGWDWMSU5)
ENDIF

LTGWDWMSV = ASSOCIATED (YD%TGWDWMSV)
IF (LTGWDWMSV) THEN
  !$acc enter data create (YD%TGWDWMSV)
  !$acc update device (YD%TGWDWMSV)
  !$acc enter data attach (YD%TGWDWMSV)
ENDIF

LTGWDWMSV5 = ASSOCIATED (YD%TGWDWMSV5)
IF (LTGWDWMSV5) THEN
  !$acc enter data create (YD%TGWDWMSV5)
  !$acc update device (YD%TGWDWMSV5)
  !$acc enter data attach (YD%TGWDWMSV5)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_SPHYS_HIST_TYPE (YD, LDDELETED)
IMPLICIT NONE
CLASS (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5

LYA5 = ASSOCIATED (YD%YA5)
IF (LYA5) THEN
  !$acc exit data detach (YD%YA5)
  !$acc exit data delete (YD%YA5)
ENDIF

LYL5 = ASSOCIATED (YD%YL5)
IF (LYL5) THEN
  !$acc exit data detach (YD%YL5)
  !$acc exit data delete (YD%YL5)
ENDIF

LYI5 = ASSOCIATED (YD%YI5)
IF (LYI5) THEN
  !$acc exit data detach (YD%YI5)
  !$acc exit data delete (YD%YI5)
ENDIF

LRADLWM = ASSOCIATED (YD%RADLWM)
IF (LRADLWM) THEN
  !$acc exit data detach (YD%RADLWM)
  !$acc exit data delete (YD%RADLWM)
ENDIF

LRADLWM5 = ASSOCIATED (YD%RADLWM5)
IF (LRADLWM5) THEN
  !$acc exit data detach (YD%RADLWM5)
  !$acc exit data delete (YD%RADLWM5)
ENDIF

LTGWDWMSU = ASSOCIATED (YD%TGWDWMSU)
IF (LTGWDWMSU) THEN
  !$acc exit data detach (YD%TGWDWMSU)
  !$acc exit data delete (YD%TGWDWMSU)
ENDIF

LTGWDWMSU5 = ASSOCIATED (YD%TGWDWMSU5)
IF (LTGWDWMSU5) THEN
  !$acc exit data detach (YD%TGWDWMSU5)
  !$acc exit data delete (YD%TGWDWMSU5)
ENDIF

LTGWDWMSV = ASSOCIATED (YD%TGWDWMSV)
IF (LTGWDWMSV) THEN
  !$acc exit data detach (YD%TGWDWMSV)
  !$acc exit data delete (YD%TGWDWMSV)
ENDIF

LTGWDWMSV5 = ASSOCIATED (YD%TGWDWMSV5)
IF (LTGWDWMSV5) THEN
  !$acc exit data detach (YD%TGWDWMSV5)
  !$acc exit data delete (YD%TGWDWMSV5)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
