MODULE UTIL_TMSE_MOD

USE YOMMSE, ONLY : TMSE

INTERFACE SAVE
MODULE PROCEDURE SAVE_TMSE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMSE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TMSE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMSE), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LPGDFWR
WRITE (KLUN) YD%LHISFWR
WRITE (KLUN) YD%LFTZERO
WRITE (KLUN) YD%NSURFEXCTLMAX
WRITE (KLUN) YD%NSURFEXCTL
WRITE (KLUN) YD%CPREFIX_SFX1
WRITE (KLUN) YD%CPREFIX_SFX2
WRITE (KLUN) YD%XZSEPS
END SUBROUTINE

SUBROUTINE LOAD_TMSE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMSE), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LPGDFWR
READ (KLUN) YD%LHISFWR
READ (KLUN) YD%LFTZERO
READ (KLUN) YD%NSURFEXCTLMAX
READ (KLUN) YD%NSURFEXCTL
READ (KLUN) YD%CPREFIX_SFX1
READ (KLUN) YD%CPREFIX_SFX2
READ (KLUN) YD%XZSEPS
END SUBROUTINE






END MODULE
