MODULE UTIL_TPHLC_MOD

USE YOPHLC, ONLY : TPHLC


INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHLC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHLC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHLC
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPHLC
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TPHLC (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPHLC), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%ALPHA
WRITE (KLUN) YD%AH0
WRITE (KLUN) YD%USTARL
WRITE (KLUN) YD%USTARS
WRITE (KLUN) YD%ALANDZ0
WRITE (KLUN) YD%ASEAZ0
WRITE (KLUN) YD%LSPHLC
WRITE (KLUN) YD%LVDFLC
WRITE (KLUN) YD%LSDRLC
WRITE (KLUN) YD%LZMCON
WRITE (KLUN) YD%LKEXP
WRITE (KLUN) YD%LVDFDS
WRITE (KLUN) YD%LSDRDS
END SUBROUTINE

SUBROUTINE LOAD_TPHLC (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (TPHLC), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%ALPHA
READ (KLUN) YD%AH0
READ (KLUN) YD%USTARL
READ (KLUN) YD%USTARS
READ (KLUN) YD%ALANDZ0
READ (KLUN) YD%ASEAZ0
READ (KLUN) YD%LSPHLC
READ (KLUN) YD%LVDFLC
READ (KLUN) YD%LSDRLC
READ (KLUN) YD%LZMCON
READ (KLUN) YD%LKEXP
READ (KLUN) YD%LVDFDS
READ (KLUN) YD%LSDRDS
END SUBROUTINE


SUBROUTINE COPY_TPHLC (YD, LDCREATED)
IMPLICIT NONE
CLASS (TPHLC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF













END SUBROUTINE

SUBROUTINE WIPE_TPHLC (YD, LDDELETED)
IMPLICIT NONE
CLASS (TPHLC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED














LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
