MODULE UTIL_TVDF_MOD

USE YOEVDF, ONLY : TVDF

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVDF
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVDF
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TVDF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDF), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RLAM
WRITE (KLUN) YD%RVDIFTS
WRITE (KLUN) YD%LWDS
WRITE (KLUN) YD%REPS1WDS
WRITE (KLUN) YD%REPS2WDS
WRITE (KLUN) YD%RETAWDS
WRITE (KLUN) YD%RTOFDALPHA
WRITE (KLUN) YD%NSUBST
WRITE (KLUN) YD%RFAC_TWO_COEF
WRITE (KLUN) YD%RZC_H
WRITE (KLUN) YD%RZL_INF
END SUBROUTINE
SUBROUTINE LOAD_TVDF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDF), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%RLAM
READ (KLUN) YD%RVDIFTS
READ (KLUN) YD%LWDS
READ (KLUN) YD%REPS1WDS
READ (KLUN) YD%REPS2WDS
READ (KLUN) YD%RETAWDS
READ (KLUN) YD%RTOFDALPHA
READ (KLUN) YD%NSUBST
READ (KLUN) YD%RFAC_TWO_COEF
READ (KLUN) YD%RZC_H
READ (KLUN) YD%RZL_INF
END SUBROUTINE




END MODULE
