MODULE UTIL_TSTOPH_MOD

USE STOPH_MIX, ONLY : TSTOPH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSTOPH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSTOPH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TSTOPH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTOPH), INTENT (IN), TARGET :: YD
LOGICAL :: LALPHA_STO, LALPHA_STO_T, LGPSTREAM, LGPTEMP, LGPTOTDISS, LGPTOTDISS_SMOOTH, LGPVELPOT, LGPVORTGRAD, LMCELL, LNIMRAN
LOGICAL :: LONEMINALPHA_NFRSPBS, LONEMINALPHA_NFRSPBS_T, LRSMOOTH, LRSTOPHCA, LRVP_MUL, LRVP_MULFACT, LRVP_MULFACT_T, LRVP_MUL_T, LRWGHT, LSPDP
LOGICAL :: LSPG_AMP, LSPG_AMP_T, LSPSTREAM, LSPSTREAM_FORC, LSPTEMP, LSPTEMP_FORC, LSPVELPOT, LSPVELPOT_FORC, LSQRTCORR, LTAPER_FACT
LRSTOPHCA = ALLOCATED (YD%RSTOPHCA)
WRITE (KLUN) LRSTOPHCA
IF (LRSTOPHCA) THEN
  WRITE (KLUN) LBOUND (YD%RSTOPHCA)
  WRITE (KLUN) UBOUND (YD%RSTOPHCA)
  WRITE (KLUN) YD%RSTOPHCA
ENDIF
LSQRTCORR = ALLOCATED (YD%SQRTCORR)
WRITE (KLUN) LSQRTCORR
IF (LSQRTCORR) THEN
  WRITE (KLUN) LBOUND (YD%SQRTCORR)
  WRITE (KLUN) UBOUND (YD%SQRTCORR)
  WRITE (KLUN) YD%SQRTCORR
ENDIF
LSPSTREAM = ALLOCATED (YD%SPSTREAM)
WRITE (KLUN) LSPSTREAM
IF (LSPSTREAM) THEN
  WRITE (KLUN) LBOUND (YD%SPSTREAM)
  WRITE (KLUN) UBOUND (YD%SPSTREAM)
  WRITE (KLUN) YD%SPSTREAM
ENDIF
LSPVELPOT = ALLOCATED (YD%SPVELPOT)
WRITE (KLUN) LSPVELPOT
IF (LSPVELPOT) THEN
  WRITE (KLUN) LBOUND (YD%SPVELPOT)
  WRITE (KLUN) UBOUND (YD%SPVELPOT)
  WRITE (KLUN) YD%SPVELPOT
ENDIF
LSPSTREAM_FORC = ALLOCATED (YD%SPSTREAM_FORC)
WRITE (KLUN) LSPSTREAM_FORC
IF (LSPSTREAM_FORC) THEN
  WRITE (KLUN) LBOUND (YD%SPSTREAM_FORC)
  WRITE (KLUN) UBOUND (YD%SPSTREAM_FORC)
  WRITE (KLUN) YD%SPSTREAM_FORC
ENDIF
LSPVELPOT_FORC = ALLOCATED (YD%SPVELPOT_FORC)
WRITE (KLUN) LSPVELPOT_FORC
IF (LSPVELPOT_FORC) THEN
  WRITE (KLUN) LBOUND (YD%SPVELPOT_FORC)
  WRITE (KLUN) UBOUND (YD%SPVELPOT_FORC)
  WRITE (KLUN) YD%SPVELPOT_FORC
ENDIF
LSPG_AMP = ALLOCATED (YD%SPG_AMP)
WRITE (KLUN) LSPG_AMP
IF (LSPG_AMP) THEN
  WRITE (KLUN) LBOUND (YD%SPG_AMP)
  WRITE (KLUN) UBOUND (YD%SPG_AMP)
  WRITE (KLUN) YD%SPG_AMP
ENDIF
LALPHA_STO = ALLOCATED (YD%ALPHA_STO)
WRITE (KLUN) LALPHA_STO
IF (LALPHA_STO) THEN
  WRITE (KLUN) LBOUND (YD%ALPHA_STO)
  WRITE (KLUN) UBOUND (YD%ALPHA_STO)
  WRITE (KLUN) YD%ALPHA_STO
ENDIF
LONEMINALPHA_NFRSPBS = ALLOCATED (YD%ONEMINALPHA_NFRSPBS)
WRITE (KLUN) LONEMINALPHA_NFRSPBS
IF (LONEMINALPHA_NFRSPBS) THEN
  WRITE (KLUN) LBOUND (YD%ONEMINALPHA_NFRSPBS)
  WRITE (KLUN) UBOUND (YD%ONEMINALPHA_NFRSPBS)
  WRITE (KLUN) YD%ONEMINALPHA_NFRSPBS
ENDIF
LRSMOOTH = ALLOCATED (YD%RSMOOTH)
WRITE (KLUN) LRSMOOTH
IF (LRSMOOTH) THEN
  WRITE (KLUN) LBOUND (YD%RSMOOTH)
  WRITE (KLUN) UBOUND (YD%RSMOOTH)
  WRITE (KLUN) YD%RSMOOTH
ENDIF
LGPSTREAM = ALLOCATED (YD%GPSTREAM)
WRITE (KLUN) LGPSTREAM
IF (LGPSTREAM) THEN
  WRITE (KLUN) LBOUND (YD%GPSTREAM)
  WRITE (KLUN) UBOUND (YD%GPSTREAM)
  WRITE (KLUN) YD%GPSTREAM
ENDIF
LGPVELPOT = ALLOCATED (YD%GPVELPOT)
WRITE (KLUN) LGPVELPOT
IF (LGPVELPOT) THEN
  WRITE (KLUN) LBOUND (YD%GPVELPOT)
  WRITE (KLUN) UBOUND (YD%GPVELPOT)
  WRITE (KLUN) YD%GPVELPOT
ENDIF
LGPTOTDISS = ALLOCATED (YD%GPTOTDISS)
WRITE (KLUN) LGPTOTDISS
IF (LGPTOTDISS) THEN
  WRITE (KLUN) LBOUND (YD%GPTOTDISS)
  WRITE (KLUN) UBOUND (YD%GPTOTDISS)
  WRITE (KLUN) YD%GPTOTDISS
ENDIF
LGPTOTDISS_SMOOTH = ALLOCATED (YD%GPTOTDISS_SMOOTH)
WRITE (KLUN) LGPTOTDISS_SMOOTH
IF (LGPTOTDISS_SMOOTH) THEN
  WRITE (KLUN) LBOUND (YD%GPTOTDISS_SMOOTH)
  WRITE (KLUN) UBOUND (YD%GPTOTDISS_SMOOTH)
  WRITE (KLUN) YD%GPTOTDISS_SMOOTH
ENDIF
LGPVORTGRAD = ALLOCATED (YD%GPVORTGRAD)
WRITE (KLUN) LGPVORTGRAD
IF (LGPVORTGRAD) THEN
  WRITE (KLUN) LBOUND (YD%GPVORTGRAD)
  WRITE (KLUN) UBOUND (YD%GPVORTGRAD)
  WRITE (KLUN) YD%GPVORTGRAD
ENDIF
LMCELL = ALLOCATED (YD%MCELL)
WRITE (KLUN) LMCELL
IF (LMCELL) THEN
  WRITE (KLUN) LBOUND (YD%MCELL)
  WRITE (KLUN) UBOUND (YD%MCELL)
  WRITE (KLUN) YD%MCELL
ENDIF
LRWGHT = ALLOCATED (YD%RWGHT)
WRITE (KLUN) LRWGHT
IF (LRWGHT) THEN
  WRITE (KLUN) LBOUND (YD%RWGHT)
  WRITE (KLUN) UBOUND (YD%RWGHT)
  WRITE (KLUN) YD%RWGHT
ENDIF
WRITE (KLUN) YD%NFRSTOPH_SPBS
WRITE (KLUN) YD%NFRSTOPH_SPBS_PAT
WRITE (KLUN) YD%NFRSTOPH_VC
WRITE (KLUN) YD%NFORCESTART
WRITE (KLUN) YD%NFORCEEND
WRITE (KLUN) YD%NSTOCHOPT
WRITE (KLUN) YD%ALPHA_DEEP_CONV
WRITE (KLUN) YD%ALPHA_SHAL_CONV
WRITE (KLUN) YD%SLDISSFAC
WRITE (KLUN) YD%RATIO_BACKSCAT
WRITE (KLUN) YD%RSPBS_TAU
WRITE (KLUN) YD%RATIO_BACKSCAT_CON2NUM
WRITE (KLUN) YD%REXPONENT
WRITE (KLUN) YD%VC_CON
WRITE (KLUN) YD%RFLUX_DET_CLIP
WRITE (KLUN) YD%BIHARM
WRITE (KLUN) YD%RSMOOTHSCALE
WRITE (KLUN) YD%RSIGMA2_EPS
WRITE (KLUN) YD%INCUT
WRITE (KLUN) YD%AMAGSTOPH_CASBS
WRITE (KLUN) YD%ADLATSTOPH_CA
WRITE (KLUN) YD%ADLONSTOPH_CA
WRITE (KLUN) YD%LSTOPH_SPBS
WRITE (KLUN) YD%LSTOPH_SPBS_FAST
WRITE (KLUN) YD%LEXTRAFIELDS
WRITE (KLUN) YD%LSTOPH_JBCOR
WRITE (KLUN) YD%LSTOPH_UNCORR
WRITE (KLUN) YD%LSTOPH_UNIFORM
WRITE (KLUN) YD%LSTOPH_SPBS_VORT
WRITE (KLUN) YD%LSTOPH_RVP
WRITE (KLUN) YD%LSTOPH_RVPOLD
WRITE (KLUN) YD%LSTOPH_TAPER
WRITE (KLUN) YD%LSTOPH_INI
WRITE (KLUN) YD%LSTOPH_CASBS
WRITE (KLUN) YD%LVORTCON
WRITE (KLUN) YD%LFORCENL
WRITE (KLUN) YD%LSTOPH_VARALPHA
WRITE (KLUN) YD%LSTOPH_GAUSS
WRITE (KLUN) YD%LSPBS_DISSGW
WRITE (KLUN) YD%LSPBS_DISSNUM
WRITE (KLUN) YD%LSPBS_DISSCU
WRITE (KLUN) YD%LSPBS_DISSNUM_CT
WRITE (KLUN) YD%LSPBSNORM
WRITE (KLUN) YD%LSPBSDISS
LSPDP = ALLOCATED (YD%SPDP)
WRITE (KLUN) LSPDP
IF (LSPDP) THEN
  WRITE (KLUN) LBOUND (YD%SPDP)
  WRITE (KLUN) UBOUND (YD%SPDP)
  WRITE (KLUN) YD%SPDP
ENDIF
LNIMRAN = ALLOCATED (YD%NIMRAN)
WRITE (KLUN) LNIMRAN
IF (LNIMRAN) THEN
  WRITE (KLUN) LBOUND (YD%NIMRAN)
  WRITE (KLUN) UBOUND (YD%NIMRAN)
  WRITE (KLUN) YD%NIMRAN
ENDIF
WRITE (KLUN) YD%NSMAXSPBS
WRITE (KLUN) YD%RVP_MULMIN
WRITE (KLUN) YD%RVP_MULMAX
WRITE (KLUN) YD%RVP_MULEXP
WRITE (KLUN) YD%RVP_MULNSMAX
LRVP_MULFACT = ALLOCATED (YD%RVP_MULFACT)
WRITE (KLUN) LRVP_MULFACT
IF (LRVP_MULFACT) THEN
  WRITE (KLUN) LBOUND (YD%RVP_MULFACT)
  WRITE (KLUN) UBOUND (YD%RVP_MULFACT)
  WRITE (KLUN) YD%RVP_MULFACT
ENDIF
WRITE (KLUN) YD%RVP_MUL_A
WRITE (KLUN) YD%RVP_MUL_B
WRITE (KLUN) YD%RVP_MUL_C
WRITE (KLUN) YD%RVP_MUL_D
WRITE (KLUN) YD%RVP_MUL_1
WRITE (KLUN) YD%RVP_MUL_2
LRVP_MUL = ALLOCATED (YD%RVP_MUL)
WRITE (KLUN) LRVP_MUL
IF (LRVP_MUL) THEN
  WRITE (KLUN) LBOUND (YD%RVP_MUL)
  WRITE (KLUN) UBOUND (YD%RVP_MUL)
  WRITE (KLUN) YD%RVP_MUL
ENDIF
WRITE (KLUN) YD%TAPER_SIGMATOP
WRITE (KLUN) YD%TAPER_SIGMABOT
WRITE (KLUN) YD%TAPER0
WRITE (KLUN) YD%TAPER1
WRITE (KLUN) YD%TAPER2
WRITE (KLUN) YD%TAPER3
LTAPER_FACT = ALLOCATED (YD%TAPER_FACT)
WRITE (KLUN) LTAPER_FACT
IF (LTAPER_FACT) THEN
  WRITE (KLUN) LBOUND (YD%TAPER_FACT)
  WRITE (KLUN) UBOUND (YD%TAPER_FACT)
  WRITE (KLUN) YD%TAPER_FACT
ENDIF
WRITE (KLUN) YD%LSTOPH_SPBS_T
WRITE (KLUN) YD%REXPONENT_T
WRITE (KLUN) YD%RATIO_APE2KE
LSPTEMP = ALLOCATED (YD%SPTEMP)
WRITE (KLUN) LSPTEMP
IF (LSPTEMP) THEN
  WRITE (KLUN) LBOUND (YD%SPTEMP)
  WRITE (KLUN) UBOUND (YD%SPTEMP)
  WRITE (KLUN) YD%SPTEMP
ENDIF
LSPTEMP_FORC = ALLOCATED (YD%SPTEMP_FORC)
WRITE (KLUN) LSPTEMP_FORC
IF (LSPTEMP_FORC) THEN
  WRITE (KLUN) LBOUND (YD%SPTEMP_FORC)
  WRITE (KLUN) UBOUND (YD%SPTEMP_FORC)
  WRITE (KLUN) YD%SPTEMP_FORC
ENDIF
LSPG_AMP_T = ALLOCATED (YD%SPG_AMP_T)
WRITE (KLUN) LSPG_AMP_T
IF (LSPG_AMP_T) THEN
  WRITE (KLUN) LBOUND (YD%SPG_AMP_T)
  WRITE (KLUN) UBOUND (YD%SPG_AMP_T)
  WRITE (KLUN) YD%SPG_AMP_T
ENDIF
LALPHA_STO_T = ALLOCATED (YD%ALPHA_STO_T)
WRITE (KLUN) LALPHA_STO_T
IF (LALPHA_STO_T) THEN
  WRITE (KLUN) LBOUND (YD%ALPHA_STO_T)
  WRITE (KLUN) UBOUND (YD%ALPHA_STO_T)
  WRITE (KLUN) YD%ALPHA_STO_T
ENDIF
LONEMINALPHA_NFRSPBS_T = ALLOCATED (YD%ONEMINALPHA_NFRSPBS_T)
WRITE (KLUN) LONEMINALPHA_NFRSPBS_T
IF (LONEMINALPHA_NFRSPBS_T) THEN
  WRITE (KLUN) LBOUND (YD%ONEMINALPHA_NFRSPBS_T)
  WRITE (KLUN) UBOUND (YD%ONEMINALPHA_NFRSPBS_T)
  WRITE (KLUN) YD%ONEMINALPHA_NFRSPBS_T
ENDIF
LGPTEMP = ALLOCATED (YD%GPTEMP)
WRITE (KLUN) LGPTEMP
IF (LGPTEMP) THEN
  WRITE (KLUN) LBOUND (YD%GPTEMP)
  WRITE (KLUN) UBOUND (YD%GPTEMP)
  WRITE (KLUN) YD%GPTEMP
ENDIF
WRITE (KLUN) YD%RVP_MULMIN_T
WRITE (KLUN) YD%RVP_MULMAX_T
WRITE (KLUN) YD%RVP_MULEXP_T
WRITE (KLUN) YD%RVP_MULNSMAX_T
LRVP_MULFACT_T = ALLOCATED (YD%RVP_MULFACT_T)
WRITE (KLUN) LRVP_MULFACT_T
IF (LRVP_MULFACT_T) THEN
  WRITE (KLUN) LBOUND (YD%RVP_MULFACT_T)
  WRITE (KLUN) UBOUND (YD%RVP_MULFACT_T)
  WRITE (KLUN) YD%RVP_MULFACT_T
ENDIF
WRITE (KLUN) YD%RVP_MUL_A_T
WRITE (KLUN) YD%RVP_MUL_B_T
WRITE (KLUN) YD%RVP_MUL_C_T
WRITE (KLUN) YD%RVP_MUL_D_T
WRITE (KLUN) YD%RVP_MUL_1_T
WRITE (KLUN) YD%RVP_MUL_2_T
LRVP_MUL_T = ALLOCATED (YD%RVP_MUL_T)
WRITE (KLUN) LRVP_MUL_T
IF (LRVP_MUL_T) THEN
  WRITE (KLUN) LBOUND (YD%RVP_MUL_T)
  WRITE (KLUN) UBOUND (YD%RVP_MUL_T)
  WRITE (KLUN) YD%RVP_MUL_T
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TSTOPH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTOPH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LALPHA_STO, LALPHA_STO_T, LGPSTREAM, LGPTEMP, LGPTOTDISS, LGPTOTDISS_SMOOTH, LGPVELPOT, LGPVORTGRAD, LMCELL, LNIMRAN
LOGICAL :: LONEMINALPHA_NFRSPBS, LONEMINALPHA_NFRSPBS_T, LRSMOOTH, LRSTOPHCA, LRVP_MUL, LRVP_MULFACT, LRVP_MULFACT_T, LRVP_MUL_T, LRWGHT, LSPDP
LOGICAL :: LSPG_AMP, LSPG_AMP_T, LSPSTREAM, LSPSTREAM_FORC, LSPTEMP, LSPTEMP_FORC, LSPVELPOT, LSPVELPOT_FORC, LSQRTCORR, LTAPER_FACT
READ (KLUN) LRSTOPHCA
IF (LRSTOPHCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSTOPHCA (IL1(1):IU1(1)))
  READ (KLUN) YD%RSTOPHCA
ENDIF
READ (KLUN) LSQRTCORR
IF (LSQRTCORR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SQRTCORR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SQRTCORR
ENDIF
READ (KLUN) LSPSTREAM
IF (LSPSTREAM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPSTREAM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPSTREAM
ENDIF
READ (KLUN) LSPVELPOT
IF (LSPVELPOT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPVELPOT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPVELPOT
ENDIF
READ (KLUN) LSPSTREAM_FORC
IF (LSPSTREAM_FORC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPSTREAM_FORC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPSTREAM_FORC
ENDIF
READ (KLUN) LSPVELPOT_FORC
IF (LSPVELPOT_FORC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPVELPOT_FORC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPVELPOT_FORC
ENDIF
READ (KLUN) LSPG_AMP
IF (LSPG_AMP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SPG_AMP (IL1(1):IU1(1)))
  READ (KLUN) YD%SPG_AMP
ENDIF
READ (KLUN) LALPHA_STO
IF (LALPHA_STO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%ALPHA_STO (IL1(1):IU1(1)))
  READ (KLUN) YD%ALPHA_STO
ENDIF
READ (KLUN) LONEMINALPHA_NFRSPBS
IF (LONEMINALPHA_NFRSPBS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%ONEMINALPHA_NFRSPBS (IL1(1):IU1(1)))
  READ (KLUN) YD%ONEMINALPHA_NFRSPBS
ENDIF
READ (KLUN) LRSMOOTH
IF (LRSMOOTH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSMOOTH (IL1(1):IU1(1)))
  READ (KLUN) YD%RSMOOTH
ENDIF
READ (KLUN) LGPSTREAM
IF (LGPSTREAM) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GPSTREAM (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GPSTREAM
ENDIF
READ (KLUN) LGPVELPOT
IF (LGPVELPOT) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GPVELPOT (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GPVELPOT
ENDIF
READ (KLUN) LGPTOTDISS
IF (LGPTOTDISS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GPTOTDISS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GPTOTDISS
ENDIF
READ (KLUN) LGPTOTDISS_SMOOTH
IF (LGPTOTDISS_SMOOTH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GPTOTDISS_SMOOTH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GPTOTDISS_SMOOTH
ENDIF
READ (KLUN) LGPVORTGRAD
IF (LGPVORTGRAD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GPVORTGRAD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GPVORTGRAD
ENDIF
READ (KLUN) LMCELL
IF (LMCELL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MCELL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%MCELL
ENDIF
READ (KLUN) LRWGHT
IF (LRWGHT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RWGHT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RWGHT
ENDIF
READ (KLUN) YD%NFRSTOPH_SPBS
READ (KLUN) YD%NFRSTOPH_SPBS_PAT
READ (KLUN) YD%NFRSTOPH_VC
READ (KLUN) YD%NFORCESTART
READ (KLUN) YD%NFORCEEND
READ (KLUN) YD%NSTOCHOPT
READ (KLUN) YD%ALPHA_DEEP_CONV
READ (KLUN) YD%ALPHA_SHAL_CONV
READ (KLUN) YD%SLDISSFAC
READ (KLUN) YD%RATIO_BACKSCAT
READ (KLUN) YD%RSPBS_TAU
READ (KLUN) YD%RATIO_BACKSCAT_CON2NUM
READ (KLUN) YD%REXPONENT
READ (KLUN) YD%VC_CON
READ (KLUN) YD%RFLUX_DET_CLIP
READ (KLUN) YD%BIHARM
READ (KLUN) YD%RSMOOTHSCALE
READ (KLUN) YD%RSIGMA2_EPS
READ (KLUN) YD%INCUT
READ (KLUN) YD%AMAGSTOPH_CASBS
READ (KLUN) YD%ADLATSTOPH_CA
READ (KLUN) YD%ADLONSTOPH_CA
READ (KLUN) YD%LSTOPH_SPBS
READ (KLUN) YD%LSTOPH_SPBS_FAST
READ (KLUN) YD%LEXTRAFIELDS
READ (KLUN) YD%LSTOPH_JBCOR
READ (KLUN) YD%LSTOPH_UNCORR
READ (KLUN) YD%LSTOPH_UNIFORM
READ (KLUN) YD%LSTOPH_SPBS_VORT
READ (KLUN) YD%LSTOPH_RVP
READ (KLUN) YD%LSTOPH_RVPOLD
READ (KLUN) YD%LSTOPH_TAPER
READ (KLUN) YD%LSTOPH_INI
READ (KLUN) YD%LSTOPH_CASBS
READ (KLUN) YD%LVORTCON
READ (KLUN) YD%LFORCENL
READ (KLUN) YD%LSTOPH_VARALPHA
READ (KLUN) YD%LSTOPH_GAUSS
READ (KLUN) YD%LSPBS_DISSGW
READ (KLUN) YD%LSPBS_DISSNUM
READ (KLUN) YD%LSPBS_DISSCU
READ (KLUN) YD%LSPBS_DISSNUM_CT
READ (KLUN) YD%LSPBSNORM
READ (KLUN) YD%LSPBSDISS
READ (KLUN) LSPDP
IF (LSPDP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SPDP (IL1(1):IU1(1)))
  READ (KLUN) YD%SPDP
ENDIF
READ (KLUN) LNIMRAN
IF (LNIMRAN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NIMRAN (IL1(1):IU1(1)))
  READ (KLUN) YD%NIMRAN
ENDIF
READ (KLUN) YD%NSMAXSPBS
READ (KLUN) YD%RVP_MULMIN
READ (KLUN) YD%RVP_MULMAX
READ (KLUN) YD%RVP_MULEXP
READ (KLUN) YD%RVP_MULNSMAX
READ (KLUN) LRVP_MULFACT
IF (LRVP_MULFACT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVP_MULFACT (IL1(1):IU1(1)))
  READ (KLUN) YD%RVP_MULFACT
ENDIF
READ (KLUN) YD%RVP_MUL_A
READ (KLUN) YD%RVP_MUL_B
READ (KLUN) YD%RVP_MUL_C
READ (KLUN) YD%RVP_MUL_D
READ (KLUN) YD%RVP_MUL_1
READ (KLUN) YD%RVP_MUL_2
READ (KLUN) LRVP_MUL
IF (LRVP_MUL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVP_MUL (IL1(1):IU1(1)))
  READ (KLUN) YD%RVP_MUL
ENDIF
READ (KLUN) YD%TAPER_SIGMATOP
READ (KLUN) YD%TAPER_SIGMABOT
READ (KLUN) YD%TAPER0
READ (KLUN) YD%TAPER1
READ (KLUN) YD%TAPER2
READ (KLUN) YD%TAPER3
READ (KLUN) LTAPER_FACT
IF (LTAPER_FACT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%TAPER_FACT (IL1(1):IU1(1)))
  READ (KLUN) YD%TAPER_FACT
ENDIF
READ (KLUN) YD%LSTOPH_SPBS_T
READ (KLUN) YD%REXPONENT_T
READ (KLUN) YD%RATIO_APE2KE
READ (KLUN) LSPTEMP
IF (LSPTEMP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTEMP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTEMP
ENDIF
READ (KLUN) LSPTEMP_FORC
IF (LSPTEMP_FORC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SPTEMP_FORC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SPTEMP_FORC
ENDIF
READ (KLUN) LSPG_AMP_T
IF (LSPG_AMP_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SPG_AMP_T (IL1(1):IU1(1)))
  READ (KLUN) YD%SPG_AMP_T
ENDIF
READ (KLUN) LALPHA_STO_T
IF (LALPHA_STO_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%ALPHA_STO_T (IL1(1):IU1(1)))
  READ (KLUN) YD%ALPHA_STO_T
ENDIF
READ (KLUN) LONEMINALPHA_NFRSPBS_T
IF (LONEMINALPHA_NFRSPBS_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%ONEMINALPHA_NFRSPBS_T (IL1(1):IU1(1)))
  READ (KLUN) YD%ONEMINALPHA_NFRSPBS_T
ENDIF
READ (KLUN) LGPTEMP
IF (LGPTEMP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GPTEMP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GPTEMP
ENDIF
READ (KLUN) YD%RVP_MULMIN_T
READ (KLUN) YD%RVP_MULMAX_T
READ (KLUN) YD%RVP_MULEXP_T
READ (KLUN) YD%RVP_MULNSMAX_T
READ (KLUN) LRVP_MULFACT_T
IF (LRVP_MULFACT_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVP_MULFACT_T (IL1(1):IU1(1)))
  READ (KLUN) YD%RVP_MULFACT_T
ENDIF
READ (KLUN) YD%RVP_MUL_A_T
READ (KLUN) YD%RVP_MUL_B_T
READ (KLUN) YD%RVP_MUL_C_T
READ (KLUN) YD%RVP_MUL_D_T
READ (KLUN) YD%RVP_MUL_1_T
READ (KLUN) YD%RVP_MUL_2_T
READ (KLUN) LRVP_MUL_T
IF (LRVP_MUL_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVP_MUL_T (IL1(1):IU1(1)))
  READ (KLUN) YD%RVP_MUL_T
ENDIF
END SUBROUTINE






END MODULE
