MODULE UTIL_TCSGLEG_MOD

USE YOMLEG, ONLY : TCSGLEG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCSGLEG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCSGLEG
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TCSGLEG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGLEG), INTENT (IN), TARGET :: YD
LOGICAL :: LR1MU2, LR1MUA, LR1MUI, LR1QM2, LRACTHE, LRLATI, LRLATIG, LRMU, LRSQM2, LRW
LRW = ALLOCATED (YD%RW)
WRITE (KLUN) LRW
IF (LRW) THEN
  WRITE (KLUN) LBOUND (YD%RW)
  WRITE (KLUN) UBOUND (YD%RW)
  WRITE (KLUN) YD%RW
ENDIF
LRMU = ALLOCATED (YD%RMU)
WRITE (KLUN) LRMU
IF (LRMU) THEN
  WRITE (KLUN) LBOUND (YD%RMU)
  WRITE (KLUN) UBOUND (YD%RMU)
  WRITE (KLUN) YD%RMU
ENDIF
LR1MU2 = ALLOCATED (YD%R1MU2)
WRITE (KLUN) LR1MU2
IF (LR1MU2) THEN
  WRITE (KLUN) LBOUND (YD%R1MU2)
  WRITE (KLUN) UBOUND (YD%R1MU2)
  WRITE (KLUN) YD%R1MU2
ENDIF
LR1MUI = ALLOCATED (YD%R1MUI)
WRITE (KLUN) LR1MUI
IF (LR1MUI) THEN
  WRITE (KLUN) LBOUND (YD%R1MUI)
  WRITE (KLUN) UBOUND (YD%R1MUI)
  WRITE (KLUN) YD%R1MUI
ENDIF
LR1MUA = ALLOCATED (YD%R1MUA)
WRITE (KLUN) LR1MUA
IF (LR1MUA) THEN
  WRITE (KLUN) LBOUND (YD%R1MUA)
  WRITE (KLUN) UBOUND (YD%R1MUA)
  WRITE (KLUN) YD%R1MUA
ENDIF
LRSQM2 = ALLOCATED (YD%RSQM2)
WRITE (KLUN) LRSQM2
IF (LRSQM2) THEN
  WRITE (KLUN) LBOUND (YD%RSQM2)
  WRITE (KLUN) UBOUND (YD%RSQM2)
  WRITE (KLUN) YD%RSQM2
ENDIF
LR1QM2 = ALLOCATED (YD%R1QM2)
WRITE (KLUN) LR1QM2
IF (LR1QM2) THEN
  WRITE (KLUN) LBOUND (YD%R1QM2)
  WRITE (KLUN) UBOUND (YD%R1QM2)
  WRITE (KLUN) YD%R1QM2
ENDIF
LRACTHE = ALLOCATED (YD%RACTHE)
WRITE (KLUN) LRACTHE
IF (LRACTHE) THEN
  WRITE (KLUN) LBOUND (YD%RACTHE)
  WRITE (KLUN) UBOUND (YD%RACTHE)
  WRITE (KLUN) YD%RACTHE
ENDIF
LRLATIG = ALLOCATED (YD%RLATIG)
WRITE (KLUN) LRLATIG
IF (LRLATIG) THEN
  WRITE (KLUN) LBOUND (YD%RLATIG)
  WRITE (KLUN) UBOUND (YD%RLATIG)
  WRITE (KLUN) YD%RLATIG
ENDIF
LRLATI = ALLOCATED (YD%RLATI)
WRITE (KLUN) LRLATI
IF (LRLATI) THEN
  WRITE (KLUN) LBOUND (YD%RLATI)
  WRITE (KLUN) UBOUND (YD%RLATI)
  WRITE (KLUN) YD%RLATI
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TCSGLEG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGLEG), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LR1MU2, LR1MUA, LR1MUI, LR1QM2, LRACTHE, LRLATI, LRLATIG, LRMU, LRSQM2, LRW
READ (KLUN) LRW
IF (LRW) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RW (IL1(1):IU1(1)))
  READ (KLUN) YD%RW
ENDIF
READ (KLUN) LRMU
IF (LRMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMU
ENDIF
READ (KLUN) LR1MU2
IF (LR1MU2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1MU2 (IL1(1):IU1(1)))
  READ (KLUN) YD%R1MU2
ENDIF
READ (KLUN) LR1MUI
IF (LR1MUI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1MUI (IL1(1):IU1(1)))
  READ (KLUN) YD%R1MUI
ENDIF
READ (KLUN) LR1MUA
IF (LR1MUA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1MUA (IL1(1):IU1(1)))
  READ (KLUN) YD%R1MUA
ENDIF
READ (KLUN) LRSQM2
IF (LRSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSQM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%RSQM2
ENDIF
READ (KLUN) LR1QM2
IF (LR1QM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1QM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%R1QM2
ENDIF
READ (KLUN) LRACTHE
IF (LRACTHE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RACTHE (IL1(1):IU1(1)))
  READ (KLUN) YD%RACTHE
ENDIF
READ (KLUN) LRLATIG
IF (LRLATIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATIG (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATIG
ENDIF
READ (KLUN) LRLATI
IF (LRLATI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATI (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATI
ENDIF
END SUBROUTINE




END MODULE
