MODULE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD

USE MODEL_PHYSICS_ECMWF_MOD, ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE UTIL_TECLDP_MOD
USE UTIL_TECLD_MOD
USE UTIL_TECND_MOD
USE UTIL_TECUCONVCA_MOD
USE UTIL_TECUMF_MOD
USE UTIL_TEGWD_MOD
USE UTIL_TEGWWMS_MOD
USE UTIL_TEPHY_MOD
USE UTIL_TTHF_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_ECMWF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_ECMWF_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_ECMWF_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_ECMWF_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_ECMWF_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YREPHY)
CALL SAVE (KLUN, YD%YRECLD)
CALL SAVE (KLUN, YD%YRECLDP)
CALL SAVE (KLUN, YD%YRECND)
CALL SAVE (KLUN, YD%YRECUMF)
CALL SAVE (KLUN, YD%YRECUCONVCA)
CALL SAVE (KLUN, YD%YREGWD)
CALL SAVE (KLUN, YD%YREGWWMS)
CALL SAVE (KLUN, YD%YRTHF)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_ECMWF_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YREPHY)
CALL LOAD (KLUN, YD%YRECLD)
CALL LOAD (KLUN, YD%YRECLDP)
CALL LOAD (KLUN, YD%YRECND)
CALL LOAD (KLUN, YD%YRECUMF)
CALL LOAD (KLUN, YD%YRECUCONVCA)
CALL LOAD (KLUN, YD%YREGWD)
CALL LOAD (KLUN, YD%YREGWWMS)
CALL LOAD (KLUN, YD%YRTHF)
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_ECMWF_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YREPHY, LDCREATED=.TRUE.)

CALL COPY (YD%YRECLD, LDCREATED=.TRUE.)

CALL COPY (YD%YRECLDP, LDCREATED=.TRUE.)

CALL COPY (YD%YRECND, LDCREATED=.TRUE.)

CALL COPY (YD%YRECUMF, LDCREATED=.TRUE.)

CALL COPY (YD%YRECUCONVCA, LDCREATED=.TRUE.)

CALL COPY (YD%YREGWD, LDCREATED=.TRUE.)

CALL COPY (YD%YREGWWMS, LDCREATED=.TRUE.)

CALL COPY (YD%YRTHF, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_ECMWF_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YREPHY, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECLD, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECLDP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECND, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECUMF, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECUCONVCA, LDDELETED=.TRUE.)

CALL WIPE (YD%YREGWD, LDDELETED=.TRUE.)

CALL WIPE (YD%YREGWWMS, LDDELETED=.TRUE.)

CALL WIPE (YD%YRTHF, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
