MODULE UTIL_TPHNC_MOD

USE YOPHNC, ONLY : TPHNC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHNC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHNC
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TPHNC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHNC), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LETRAJP
WRITE (KLUN) YD%LETRAJPT
WRITE (KLUN) YD%LERADI2
WRITE (KLUN) YD%LERADS2
WRITE (KLUN) YD%LERADSW2
WRITE (KLUN) YD%LERADN2
WRITE (KLUN) YD%LERADFL2
WRITE (KLUN) YD%LERADLW2
WRITE (KLUN) YD%LH2OCO2
WRITE (KLUN) YD%LWLOPT
WRITE (KLUN) YD%LWSOPT
WRITE (KLUN) YD%LEDCLD2
WRITE (KLUN) YD%LENCLD2
WRITE (KLUN) YD%LEVAPLS2
WRITE (KLUN) YD%LEVDIF2
WRITE (KLUN) YD%LEGWDG2
WRITE (KLUN) YD%LECUMF2
WRITE (KLUN) YD%LECOND2
WRITE (KLUN) YD%LEGWWMS2
WRITE (KLUN) YD%LEQNGT2
WRITE (KLUN) YD%LESURF2
WRITE (KLUN) YD%LEKPERT
WRITE (KLUN) YD%LEKPERTS
WRITE (KLUN) YD%LTRACLNPH
END SUBROUTINE
SUBROUTINE LOAD_TPHNC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHNC), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LETRAJP
READ (KLUN) YD%LETRAJPT
READ (KLUN) YD%LERADI2
READ (KLUN) YD%LERADS2
READ (KLUN) YD%LERADSW2
READ (KLUN) YD%LERADN2
READ (KLUN) YD%LERADFL2
READ (KLUN) YD%LERADLW2
READ (KLUN) YD%LH2OCO2
READ (KLUN) YD%LWLOPT
READ (KLUN) YD%LWSOPT
READ (KLUN) YD%LEDCLD2
READ (KLUN) YD%LENCLD2
READ (KLUN) YD%LEVAPLS2
READ (KLUN) YD%LEVDIF2
READ (KLUN) YD%LEGWDG2
READ (KLUN) YD%LECUMF2
READ (KLUN) YD%LECOND2
READ (KLUN) YD%LEGWWMS2
READ (KLUN) YD%LEQNGT2
READ (KLUN) YD%LESURF2
READ (KLUN) YD%LEKPERT
READ (KLUN) YD%LEKPERTS
READ (KLUN) YD%LTRACLNPH
END SUBROUTINE




END MODULE
