MODULE UTIL_TNORGWD_MOD

USE YOMNORGWD, ONLY : TNORGWD

INTERFACE SAVE
MODULE PROCEDURE SAVE_TNORGWD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TNORGWD
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TNORGWD
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TNORGWD
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TNORGWD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNORGWD), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NORGWD_SCHEME
WRITE (KLUN) YD%NORGWD_PRMAX
WRITE (KLUN) YD%NORGWD_DZ
WRITE (KLUN) YD%NORGWD_PTROPO
WRITE (KLUN) YD%NORGWD_NTROPO
WRITE (KLUN) YD%NORGWD_RUWMAX
WRITE (KLUN) YD%NORGWD_SAT
WRITE (KLUN) YD%NORGWD_RDISS
WRITE (KLUN) YD%NORGWD_DELTAT
WRITE (KLUN) YD%NORGWD_KMIN
WRITE (KLUN) YD%NORGWD_KMAX
WRITE (KLUN) YD%NORGWD_CMIN
WRITE (KLUN) YD%NORGWD_CMAX
WRITE (KLUN) YD%NORGWD_PLAUNCH
WRITE (KLUN) YD%NORGWD_NLAUNCH
WRITE (KLUN) YD%NORGWD_PNOVERDIF
WRITE (KLUN) YD%NORGWD_NNOVERDIF
WRITE (KLUN) YD%NORGWD_DZFRON
WRITE (KLUN) YD%NORGWD_GFRON
WRITE (KLUN) YD%NORGWD_GB
END SUBROUTINE

SUBROUTINE LOAD_TNORGWD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNORGWD), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NORGWD_SCHEME
READ (KLUN) YD%NORGWD_PRMAX
READ (KLUN) YD%NORGWD_DZ
READ (KLUN) YD%NORGWD_PTROPO
READ (KLUN) YD%NORGWD_NTROPO
READ (KLUN) YD%NORGWD_RUWMAX
READ (KLUN) YD%NORGWD_SAT
READ (KLUN) YD%NORGWD_RDISS
READ (KLUN) YD%NORGWD_DELTAT
READ (KLUN) YD%NORGWD_KMIN
READ (KLUN) YD%NORGWD_KMAX
READ (KLUN) YD%NORGWD_CMIN
READ (KLUN) YD%NORGWD_CMAX
READ (KLUN) YD%NORGWD_PLAUNCH
READ (KLUN) YD%NORGWD_NLAUNCH
READ (KLUN) YD%NORGWD_PNOVERDIF
READ (KLUN) YD%NORGWD_NNOVERDIF
READ (KLUN) YD%NORGWD_DZFRON
READ (KLUN) YD%NORGWD_GFRON
READ (KLUN) YD%NORGWD_GB
END SUBROUTINE


SUBROUTINE COPY_TNORGWD (YD, LDCREATED)

IMPLICIT NONE
TYPE (TNORGWD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




















END SUBROUTINE

SUBROUTINE WIPE_TNORGWD (YD, LDDELETED)

IMPLICIT NONE
TYPE (TNORGWD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED





















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
