MODULE UTIL_TOROG_BLOCKED_MOD

USE YOMOROG, ONLY : TOROG_BLOCKED


INTERFACE SAVE
MODULE PROCEDURE SAVE_TOROG_BLOCKED
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TOROG_BLOCKED
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TOROG_BLOCKED
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TOROG_BLOCKED
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TOROG_BLOCKED (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOROG_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM

LOROG = ALLOCATED (YD%OROG)
WRITE (KLUN) LOROG
IF (LOROG) THEN
  WRITE (KLUN) LBOUND (YD%OROG)
  WRITE (KLUN) UBOUND (YD%OROG)
  WRITE (KLUN) YD%OROG
ENDIF
LOROGL = ALLOCATED (YD%OROGL)
WRITE (KLUN) LOROGL
IF (LOROGL) THEN
  WRITE (KLUN) LBOUND (YD%OROGL)
  WRITE (KLUN) UBOUND (YD%OROGL)
  WRITE (KLUN) YD%OROGL
ENDIF
LOROGM = ALLOCATED (YD%OROGM)
WRITE (KLUN) LOROGM
IF (LOROGM) THEN
  WRITE (KLUN) LBOUND (YD%OROGM)
  WRITE (KLUN) UBOUND (YD%OROGM)
  WRITE (KLUN) YD%OROGM
ENDIF
LOROGLL = ALLOCATED (YD%OROGLL)
WRITE (KLUN) LOROGLL
IF (LOROGLL) THEN
  WRITE (KLUN) LBOUND (YD%OROGLL)
  WRITE (KLUN) UBOUND (YD%OROGLL)
  WRITE (KLUN) YD%OROGLL
ENDIF
LOROGMM = ALLOCATED (YD%OROGMM)
WRITE (KLUN) LOROGMM
IF (LOROGMM) THEN
  WRITE (KLUN) LBOUND (YD%OROGMM)
  WRITE (KLUN) UBOUND (YD%OROGMM)
  WRITE (KLUN) YD%OROGMM
ENDIF
LOROGLM = ALLOCATED (YD%OROGLM)
WRITE (KLUN) LOROGLM
IF (LOROGLM) THEN
  WRITE (KLUN) LBOUND (YD%OROGLM)
  WRITE (KLUN) UBOUND (YD%OROGLM)
  WRITE (KLUN) YD%OROGLM
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TOROG_BLOCKED (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOROG_BLOCKED), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM

READ (KLUN) LOROG
IF (LOROG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROG
ENDIF
READ (KLUN) LOROGL
IF (LOROGL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGL
ENDIF
READ (KLUN) LOROGM
IF (LOROGM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGM
ENDIF
READ (KLUN) LOROGLL
IF (LOROGLL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGLL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGLL
ENDIF
READ (KLUN) LOROGMM
IF (LOROGMM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGMM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGMM
ENDIF
READ (KLUN) LOROGLM
IF (LOROGLM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OROGLM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OROGLM
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TOROG_BLOCKED (YD, LDCREATED)
IMPLICIT NONE
TYPE (TOROG_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LOROG = ALLOCATED (YD%OROG)
IF (LOROG) THEN
  !$acc enter data create (YD%OROG)
  !$acc update device (YD%OROG)
  !$acc enter data attach (YD%OROG)
ENDIF

LOROGL = ALLOCATED (YD%OROGL)
IF (LOROGL) THEN
  !$acc enter data create (YD%OROGL)
  !$acc update device (YD%OROGL)
  !$acc enter data attach (YD%OROGL)
ENDIF

LOROGM = ALLOCATED (YD%OROGM)
IF (LOROGM) THEN
  !$acc enter data create (YD%OROGM)
  !$acc update device (YD%OROGM)
  !$acc enter data attach (YD%OROGM)
ENDIF

LOROGLL = ALLOCATED (YD%OROGLL)
IF (LOROGLL) THEN
  !$acc enter data create (YD%OROGLL)
  !$acc update device (YD%OROGLL)
  !$acc enter data attach (YD%OROGLL)
ENDIF

LOROGMM = ALLOCATED (YD%OROGMM)
IF (LOROGMM) THEN
  !$acc enter data create (YD%OROGMM)
  !$acc update device (YD%OROGMM)
  !$acc enter data attach (YD%OROGMM)
ENDIF

LOROGLM = ALLOCATED (YD%OROGLM)
IF (LOROGLM) THEN
  !$acc enter data create (YD%OROGLM)
  !$acc update device (YD%OROGLM)
  !$acc enter data attach (YD%OROGLM)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TOROG_BLOCKED (YD, LDDELETED)
IMPLICIT NONE
TYPE (TOROG_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM

LOROG = ALLOCATED (YD%OROG)
IF (LOROG) THEN
  !$acc exit data detach (YD%OROG)
  !$acc exit data delete (YD%OROG)
ENDIF

LOROGL = ALLOCATED (YD%OROGL)
IF (LOROGL) THEN
  !$acc exit data detach (YD%OROGL)
  !$acc exit data delete (YD%OROGL)
ENDIF

LOROGM = ALLOCATED (YD%OROGM)
IF (LOROGM) THEN
  !$acc exit data detach (YD%OROGM)
  !$acc exit data delete (YD%OROGM)
ENDIF

LOROGLL = ALLOCATED (YD%OROGLL)
IF (LOROGLL) THEN
  !$acc exit data detach (YD%OROGLL)
  !$acc exit data delete (YD%OROGLL)
ENDIF

LOROGMM = ALLOCATED (YD%OROGMM)
IF (LOROGMM) THEN
  !$acc exit data detach (YD%OROGMM)
  !$acc exit data delete (YD%OROGMM)
ENDIF

LOROGLM = ALLOCATED (YD%OROGLM)
IF (LOROGLM) THEN
  !$acc exit data detach (YD%OROGLM)
  !$acc exit data delete (YD%OROGLM)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
