MODULE UTIL_TMCC_MOD

USE YOMMCC, ONLY : TMCC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TMCC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMCC
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TMCC (KLUN, YD)
USE UTIL_CPLNG_FLD_TYPE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMCC), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
WRITE (KLUN) YD%N923
WRITE (KLUN) YD%NCLIMTOT
WRITE (KLUN) YD%NCLIMR
WRITE (KLUN) YD%NCLIGC
WRITE (KLUN) YD%NCLIGC_COMPO
WRITE (KLUN) YD%NYSDMP_COMPO
WRITE (KLUN) YD%NCLIMR_COMPO
WRITE (KLUN) YD%NCLIAER
WRITE (KLUN) YD%NDIFC
WRITE (KLUN) YD%NJDCR
WRITE (KLUN) YD%NJDCR1
WRITE (KLUN) YD%NDIFC_COMPO
WRITE (KLUN) YD%NJDCR_COMPO
WRITE (KLUN) YD%NJDCR1_COMPO
WRITE (KLUN) YD%NP1
WRITE (KLUN) YD%NP2
WRITE (KLUN) YD%NPCO2_1
WRITE (KLUN) YD%NPCO2_2
WRITE (KLUN) YD%NPAER_1
WRITE (KLUN) YD%NPAER_2
WRITE (KLUN) YD%NPCOMPO_1
WRITE (KLUN) YD%NPCOMPO_2
WRITE (KLUN) YD%NUNITC
WRITE (KLUN) YD%NUNITC1
WRITE (KLUN) YD%NUNITCM
WRITE (KLUN) YD%NOACOMM
WRITE (KLUN) YD%NSSTICEOP
LCLIMRCO2 = ALLOCATED (YD%CLIMRCO2)
WRITE (KLUN) LCLIMRCO2
IF (LCLIMRCO2) THEN
  WRITE (KLUN) LBOUND (YD%CLIMRCO2)
  WRITE (KLUN) UBOUND (YD%CLIMRCO2)
  WRITE (KLUN) YD%CLIMRCO2
ENDIF
LCLIMRAER = ALLOCATED (YD%CLIMRAER)
WRITE (KLUN) LCLIMRAER
IF (LCLIMRAER) THEN
  WRITE (KLUN) LBOUND (YD%CLIMRAER)
  WRITE (KLUN) UBOUND (YD%CLIMRAER)
  WRITE (KLUN) YD%CLIMRAER
ENDIF
LCLIMRCOMPO = ALLOCATED (YD%CLIMRCOMPO)
WRITE (KLUN) LCLIMRCOMPO
IF (LCLIMRCOMPO) THEN
  WRITE (KLUN) LBOUND (YD%CLIMRCOMPO)
  WRITE (KLUN) UBOUND (YD%CLIMRCOMPO)
  WRITE (KLUN) YD%CLIMRCOMPO
ENDIF
LZLAKE = ALLOCATED (YD%ZLAKE)
WRITE (KLUN) LZLAKE
IF (LZLAKE) THEN
  WRITE (KLUN) LBOUND (YD%ZLAKE)
  WRITE (KLUN) UBOUND (YD%ZLAKE)
  WRITE (KLUN) YD%ZLAKE
ENDIF
LOCEANBC = ALLOCATED (YD%OCEANBC)
WRITE (KLUN) LOCEANBC
IF (LOCEANBC) THEN
  WRITE (KLUN) LBOUND (YD%OCEANBC)
  WRITE (KLUN) UBOUND (YD%OCEANBC)
  WRITE (KLUN) YD%OCEANBC
ENDIF
LCLIMR = ALLOCATED (YD%CLIMR)
WRITE (KLUN) LCLIMR
IF (LCLIMR) THEN
  WRITE (KLUN) LBOUND (YD%CLIMR)
  WRITE (KLUN) UBOUND (YD%CLIMR)
  WRITE (KLUN) YD%CLIMR
ENDIF
WRITE (KLUN) YD%LCURR
WRITE (KLUN) YD%LGELATO
WRITE (KLUN) YD%LMCC01_MSE
WRITE (KLUN) YD%LMCC01
WRITE (KLUN) YD%LMCC02
WRITE (KLUN) YD%LMCC03
WRITE (KLUN) YD%LMCC04
WRITE (KLUN) YD%LMCC05
WRITE (KLUN) YD%LMCC06
WRITE (KLUN) YD%LMCCEC
WRITE (KLUN) YD%LMCCIEC
WRITE (KLUN) YD%LMCCIEC_COMPO
WRITE (KLUN) YD%LMCCICEIC
WRITE (KLUN) YD%LMCCDYNSEAICE
WRITE (KLUN) YD%LNEMOCOUP
WRITE (KLUN) YD%LNEMOFLUXNC
WRITE (KLUN) YD%LNEMO1WAY
WRITE (KLUN) YD%LNEMOIFSLOG
WRITE (KLUN) YD%LNEMOSSTFREEZ
WRITE (KLUN) YD%LNEMOGRIBFLDS
WRITE (KLUN) YD%LNEMOGRIBMASK
WRITE (KLUN) YD%LMULTIYR
WRITE (KLUN) YD%LMCC_COMPO
WRITE (KLUN) YD%NFRCPL
WRITE (KLUN) YD%LNEMOLIMGET
WRITE (KLUN) YD%LNEMOLIMPUT
WRITE (KLUN) YD%LNEMOLIMALB
WRITE (KLUN) YD%LNEMOLIMTEMP
WRITE (KLUN) YD%LNEMOLIMTLVL
WRITE (KLUN) YD%LNEMOLIMTHK
WRITE (KLUN) YD%LNEMOSICOUP
WRITE (KLUN) YD%LNEMOATMFLDS
WRITE (KLUN) YD%LNEMOOCEICEMIX
WRITE (KLUN) YD%LNEMOQNSICEFILT
WRITE (KLUN) YD%LNEMOACCUMFLUX
WRITE (KLUN) YD%LNEMOGRIB3D
WRITE (KLUN) YD%NNEMO3DLEVS
LRNEMOLVLS = ALLOCATED (YD%RNEMOLVLS)
WRITE (KLUN) LRNEMOLVLS
IF (LRNEMOLVLS) THEN
  WRITE (KLUN) LBOUND (YD%RNEMOLVLS)
  WRITE (KLUN) UBOUND (YD%RNEMOLVLS)
  WRITE (KLUN) YD%RNEMOLVLS
ENDIF
LRNEMOMASK = ALLOCATED (YD%RNEMOMASK)
WRITE (KLUN) LRNEMOMASK
IF (LRNEMOMASK) THEN
  WRITE (KLUN) LBOUND (YD%RNEMOMASK)
  WRITE (KLUN) UBOUND (YD%RNEMOMASK)
  WRITE (KLUN) YD%RNEMOMASK
ENDIF
WRITE (KLUN) YD%LNEMOPARTCOUP
WRITE (KLUN) YD%LNEMOPARTMASK
WRITE (KLUN) YD%LNEMOPARTMASKFILE
WRITE (KLUN) YD%RNPARTRAMPSTART
WRITE (KLUN) YD%RNPARTRAMPLEN
WRITE (KLUN) YD%RNPARTLAT
WRITE (KLUN) YD%RNPARTLATSPREAD
LPARTSST0 = ALLOCATED (YD%PARTSST0)
WRITE (KLUN) LPARTSST0
IF (LPARTSST0) THEN
  WRITE (KLUN) LBOUND (YD%PARTSST0)
  WRITE (KLUN) UBOUND (YD%PARTSST0)
  WRITE (KLUN) YD%PARTSST0
ENDIF
LPARTMASK = ALLOCATED (YD%PARTMASK)
WRITE (KLUN) LPARTMASK
IF (LPARTMASK) THEN
  WRITE (KLUN) LBOUND (YD%PARTMASK)
  WRITE (KLUN) UBOUND (YD%PARTMASK)
  WRITE (KLUN) YD%PARTMASK
ENDIF
WRITE (KLUN) YD%CDNPARTMASKFILE
LCPLNG_FLD = ALLOCATED (YD%CPLNG_FLD)
WRITE (KLUN) LCPLNG_FLD
IF (LCPLNG_FLD) THEN
  WRITE (KLUN) LBOUND (YD%CPLNG_FLD)
  WRITE (KLUN) UBOUND (YD%CPLNG_FLD)
  DO J1 = LBOUND (YD%CPLNG_FLD, 1), UBOUND (YD%CPLNG_FLD, 1)
    CALL SAVE (KLUN, YD%CPLNG_FLD (J1))
  ENDDO
ENDIF
WRITE (KLUN) YD%CPLNG_ACTIVE
WRITE (KLUN) YD%CPLNG_NUM_FIELDS
WRITE (KLUN) YD%IP_A_SST
WRITE (KLUN) YD%IP_A_ICE_FRAC
WRITE (KLUN) YD%IP_A_CURR_U
WRITE (KLUN) YD%IP_A_CURR_V
WRITE (KLUN) YD%IP_A_TAUX_OCE
WRITE (KLUN) YD%IP_A_TAUY_OCE
WRITE (KLUN) YD%IP_A_TAUX_ICE
WRITE (KLUN) YD%IP_A_TAUY_ICE
WRITE (KLUN) YD%IP_A_QS_MIX
WRITE (KLUN) YD%IP_A_QNS_MIX
WRITE (KLUN) YD%IP_A_QS_OCE
WRITE (KLUN) YD%IP_A_QNS_OCE
WRITE (KLUN) YD%IP_A_QS_ICE
WRITE (KLUN) YD%IP_A_QNS_ICE
WRITE (KLUN) YD%IP_A_PRECIP_LIQUID
WRITE (KLUN) YD%IP_A_PRECIP_SOLID
WRITE (KLUN) YD%IP_A_EVAP_TOTAL
WRITE (KLUN) YD%IP_A_EVAP_ICE
WRITE (KLUN) YD%IP_A_DQNS_DT
WRITE (KLUN) YD%IP_A_RUNOFF
WRITE (KLUN) YD%IP_A_TOTAL_CC
WRITE (KLUN) YD%IP_A_LOW_CC
WRITE (KLUN) YD%IP_A_ICE_TEMP
WRITE (KLUN) YD%IP_A_ICE_ALBEDO
WRITE (KLUN) YD%IP_A_ICE_THICKNESS
WRITE (KLUN) YD%IP_A_SNOW_THICKNESS
WRITE (KLUN) YD%IP_A_ICE_TEMP_LVLS
WRITE (KLUN) YD%IP_A_TAUX
WRITE (KLUN) YD%IP_A_TAUY
WRITE (KLUN) YD%IP_A_QS
WRITE (KLUN) YD%IP_A_QNS
WRITE (KLUN) YD%IP_A_WATER
WRITE (KLUN) YD%IP_A_SST_ATM
WRITE (KLUN) YD%IP_A_TSK_ATM
WRITE (KLUN) YD%IP_A_IST_ATM
WRITE (KLUN) YD%LCOUPSIM
END SUBROUTINE

SUBROUTINE LOAD_TMCC (KLUN, YD)
USE UTIL_CPLNG_FLD_TYPE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMCC), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
READ (KLUN) YD%N923
READ (KLUN) YD%NCLIMTOT
READ (KLUN) YD%NCLIMR
READ (KLUN) YD%NCLIGC
READ (KLUN) YD%NCLIGC_COMPO
READ (KLUN) YD%NYSDMP_COMPO
READ (KLUN) YD%NCLIMR_COMPO
READ (KLUN) YD%NCLIAER
READ (KLUN) YD%NDIFC
READ (KLUN) YD%NJDCR
READ (KLUN) YD%NJDCR1
READ (KLUN) YD%NDIFC_COMPO
READ (KLUN) YD%NJDCR_COMPO
READ (KLUN) YD%NJDCR1_COMPO
READ (KLUN) YD%NP1
READ (KLUN) YD%NP2
READ (KLUN) YD%NPCO2_1
READ (KLUN) YD%NPCO2_2
READ (KLUN) YD%NPAER_1
READ (KLUN) YD%NPAER_2
READ (KLUN) YD%NPCOMPO_1
READ (KLUN) YD%NPCOMPO_2
READ (KLUN) YD%NUNITC
READ (KLUN) YD%NUNITC1
READ (KLUN) YD%NUNITCM
READ (KLUN) YD%NOACOMM
READ (KLUN) YD%NSSTICEOP
READ (KLUN) LCLIMRCO2
IF (LCLIMRCO2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%CLIMRCO2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%CLIMRCO2
ENDIF
READ (KLUN) LCLIMRAER
IF (LCLIMRAER) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%CLIMRAER (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%CLIMRAER
ENDIF
READ (KLUN) LCLIMRCOMPO
IF (LCLIMRCOMPO) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%CLIMRCOMPO (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%CLIMRCOMPO
ENDIF
READ (KLUN) LZLAKE
IF (LZLAKE) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%ZLAKE (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%ZLAKE
ENDIF
READ (KLUN) LOCEANBC
IF (LOCEANBC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%OCEANBC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%OCEANBC
ENDIF
READ (KLUN) LCLIMR
IF (LCLIMR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%CLIMR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%CLIMR
ENDIF
READ (KLUN) YD%LCURR
READ (KLUN) YD%LGELATO
READ (KLUN) YD%LMCC01_MSE
READ (KLUN) YD%LMCC01
READ (KLUN) YD%LMCC02
READ (KLUN) YD%LMCC03
READ (KLUN) YD%LMCC04
READ (KLUN) YD%LMCC05
READ (KLUN) YD%LMCC06
READ (KLUN) YD%LMCCEC
READ (KLUN) YD%LMCCIEC
READ (KLUN) YD%LMCCIEC_COMPO
READ (KLUN) YD%LMCCICEIC
READ (KLUN) YD%LMCCDYNSEAICE
READ (KLUN) YD%LNEMOCOUP
READ (KLUN) YD%LNEMOFLUXNC
READ (KLUN) YD%LNEMO1WAY
READ (KLUN) YD%LNEMOIFSLOG
READ (KLUN) YD%LNEMOSSTFREEZ
READ (KLUN) YD%LNEMOGRIBFLDS
READ (KLUN) YD%LNEMOGRIBMASK
READ (KLUN) YD%LMULTIYR
READ (KLUN) YD%LMCC_COMPO
READ (KLUN) YD%NFRCPL
READ (KLUN) YD%LNEMOLIMGET
READ (KLUN) YD%LNEMOLIMPUT
READ (KLUN) YD%LNEMOLIMALB
READ (KLUN) YD%LNEMOLIMTEMP
READ (KLUN) YD%LNEMOLIMTLVL
READ (KLUN) YD%LNEMOLIMTHK
READ (KLUN) YD%LNEMOSICOUP
READ (KLUN) YD%LNEMOATMFLDS
READ (KLUN) YD%LNEMOOCEICEMIX
READ (KLUN) YD%LNEMOQNSICEFILT
READ (KLUN) YD%LNEMOACCUMFLUX
READ (KLUN) YD%LNEMOGRIB3D
READ (KLUN) YD%NNEMO3DLEVS
READ (KLUN) LRNEMOLVLS
IF (LRNEMOLVLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RNEMOLVLS (IL1(1):IU1(1)))
  READ (KLUN) YD%RNEMOLVLS
ENDIF
READ (KLUN) LRNEMOMASK
IF (LRNEMOMASK) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RNEMOMASK (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RNEMOMASK
ENDIF
READ (KLUN) YD%LNEMOPARTCOUP
READ (KLUN) YD%LNEMOPARTMASK
READ (KLUN) YD%LNEMOPARTMASKFILE
READ (KLUN) YD%RNPARTRAMPSTART
READ (KLUN) YD%RNPARTRAMPLEN
READ (KLUN) YD%RNPARTLAT
READ (KLUN) YD%RNPARTLATSPREAD
READ (KLUN) LPARTSST0
IF (LPARTSST0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PARTSST0 (IL1(1):IU1(1)))
  READ (KLUN) YD%PARTSST0
ENDIF
READ (KLUN) LPARTMASK
IF (LPARTMASK) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PARTMASK (IL1(1):IU1(1)))
  READ (KLUN) YD%PARTMASK
ENDIF
READ (KLUN) YD%CDNPARTMASKFILE
READ (KLUN) LCPLNG_FLD
IF (LCPLNG_FLD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CPLNG_FLD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%CPLNG_FLD, 1), UBOUND (YD%CPLNG_FLD, 1)
    CALL LOAD (KLUN, YD%CPLNG_FLD (J1))
  ENDDO
ENDIF
READ (KLUN) YD%CPLNG_ACTIVE
READ (KLUN) YD%CPLNG_NUM_FIELDS
READ (KLUN) YD%IP_A_SST
READ (KLUN) YD%IP_A_ICE_FRAC
READ (KLUN) YD%IP_A_CURR_U
READ (KLUN) YD%IP_A_CURR_V
READ (KLUN) YD%IP_A_TAUX_OCE
READ (KLUN) YD%IP_A_TAUY_OCE
READ (KLUN) YD%IP_A_TAUX_ICE
READ (KLUN) YD%IP_A_TAUY_ICE
READ (KLUN) YD%IP_A_QS_MIX
READ (KLUN) YD%IP_A_QNS_MIX
READ (KLUN) YD%IP_A_QS_OCE
READ (KLUN) YD%IP_A_QNS_OCE
READ (KLUN) YD%IP_A_QS_ICE
READ (KLUN) YD%IP_A_QNS_ICE
READ (KLUN) YD%IP_A_PRECIP_LIQUID
READ (KLUN) YD%IP_A_PRECIP_SOLID
READ (KLUN) YD%IP_A_EVAP_TOTAL
READ (KLUN) YD%IP_A_EVAP_ICE
READ (KLUN) YD%IP_A_DQNS_DT
READ (KLUN) YD%IP_A_RUNOFF
READ (KLUN) YD%IP_A_TOTAL_CC
READ (KLUN) YD%IP_A_LOW_CC
READ (KLUN) YD%IP_A_ICE_TEMP
READ (KLUN) YD%IP_A_ICE_ALBEDO
READ (KLUN) YD%IP_A_ICE_THICKNESS
READ (KLUN) YD%IP_A_SNOW_THICKNESS
READ (KLUN) YD%IP_A_ICE_TEMP_LVLS
READ (KLUN) YD%IP_A_TAUX
READ (KLUN) YD%IP_A_TAUY
READ (KLUN) YD%IP_A_QS
READ (KLUN) YD%IP_A_QNS
READ (KLUN) YD%IP_A_WATER
READ (KLUN) YD%IP_A_SST_ATM
READ (KLUN) YD%IP_A_TSK_ATM
READ (KLUN) YD%IP_A_IST_ATM
READ (KLUN) YD%LCOUPSIM
END SUBROUTINE






END MODULE
