MODULE UTIL_MODEL_DYNAMICS_TYPE_MOD

USE MODEL_DYNAMICS_MOD, ONLY : MODEL_DYNAMICS_TYPE
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_DYNAMICS_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_DYNAMICS_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRDYNA)
CALL SAVE (KLUN, YD%YRDYN)
CALL SAVE (KLUN, YD%YREDYN)
CALL SAVE (KLUN, YD%YRSPNG)
CALL SAVE (KLUN, YD%YRPTRGPPC)
CALL SAVE (KLUN, YD%YYTLSCAW)
CALL SAVE (KLUN, YD%YYTLSCAWH)
CALL SAVE (KLUN, YD%YYTRSCAW)
CALL SAVE (KLUN, YD%YYTRSCAWH)
CALL SAVE (KLUN, YD%YYTSCO)
CALL SAVE (KLUN, YD%YYTCCO)
CALL SAVE (KLUN, YD%YRSLREP)
CALL SAVE (KLUN, YD%YRPTRSLB1)
CALL SAVE (KLUN, YD%YRPTRSLB2)
CALL SAVE (KLUN, YD%YRPTRSLB15)
CALL SAVE (KLUN, YD%YRTNH)
CALL SAVE (KLUN, YD%YRSL)
CALL SAVE (KLUN, YD%YRAD)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_DYNAMICS_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRDYNA)
CALL LOAD (KLUN, YD%YRDYN)
CALL LOAD (KLUN, YD%YREDYN)
CALL LOAD (KLUN, YD%YRSPNG)
CALL LOAD (KLUN, YD%YRPTRGPPC)
CALL LOAD (KLUN, YD%YYTLSCAW)
CALL LOAD (KLUN, YD%YYTLSCAWH)
CALL LOAD (KLUN, YD%YYTRSCAW)
CALL LOAD (KLUN, YD%YYTRSCAWH)
CALL LOAD (KLUN, YD%YYTSCO)
CALL LOAD (KLUN, YD%YYTCCO)
CALL LOAD (KLUN, YD%YRSLREP)
CALL LOAD (KLUN, YD%YRPTRSLB1)
CALL LOAD (KLUN, YD%YRPTRSLB2)
CALL LOAD (KLUN, YD%YRPTRSLB15)
CALL LOAD (KLUN, YD%YRTNH)
CALL LOAD (KLUN, YD%YRSL)
CALL LOAD (KLUN, YD%YRAD)
END SUBROUTINE


SUBROUTINE COPY_MODEL_DYNAMICS_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRDYNA, LDCREATED=.TRUE.)

CALL COPY (YD%YRDYN, LDCREATED=.TRUE.)

CALL COPY (YD%YREDYN, LDCREATED=.TRUE.)

CALL COPY (YD%YRSPNG, LDCREATED=.TRUE.)

CALL COPY (YD%YRPTRGPPC, LDCREATED=.TRUE.)

CALL COPY (YD%YYTLSCAW, LDCREATED=.TRUE.)

CALL COPY (YD%YYTLSCAWH, LDCREATED=.TRUE.)

CALL COPY (YD%YYTRSCAW, LDCREATED=.TRUE.)

CALL COPY (YD%YYTRSCAWH, LDCREATED=.TRUE.)

CALL COPY (YD%YYTSCO, LDCREATED=.TRUE.)

CALL COPY (YD%YYTCCO, LDCREATED=.TRUE.)

CALL COPY (YD%YRSLREP, LDCREATED=.TRUE.)

CALL COPY (YD%YRPTRSLB1, LDCREATED=.TRUE.)

CALL COPY (YD%YRPTRSLB2, LDCREATED=.TRUE.)

CALL COPY (YD%YRPTRSLB15, LDCREATED=.TRUE.)

CALL COPY (YD%YRTNH, LDCREATED=.TRUE.)

CALL COPY (YD%YRSL, LDCREATED=.TRUE.)

CALL COPY (YD%YRAD, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_DYNAMICS_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRDYNA, LDDELETED=.TRUE.)

CALL WIPE (YD%YRDYN, LDDELETED=.TRUE.)

CALL WIPE (YD%YREDYN, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSPNG, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPTRGPPC, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTLSCAW, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTLSCAWH, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTRSCAW, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTRSCAWH, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTSCO, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTCCO, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSLREP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPTRSLB1, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPTRSLB2, LDDELETED=.TRUE.)

CALL WIPE (YD%YRPTRSLB15, LDDELETED=.TRUE.)

CALL WIPE (YD%YRTNH, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSL, LDDELETED=.TRUE.)

CALL WIPE (YD%YRAD, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
