MODULE UTIL_TCDDH_MOD

USE YOMCDDH, ONLY : TCDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCDDH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TCDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
LCADHTLS = ALLOCATED (YD%CADHTLS)
WRITE (KLUN) LCADHTLS
IF (LCADHTLS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTLS)
  WRITE (KLUN) UBOUND (YD%CADHTLS)
  WRITE (KLUN) YD%CADHTLS
ENDIF
LCADHTSS = ALLOCATED (YD%CADHTSS)
WRITE (KLUN) LCADHTSS
IF (LCADHTSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTSS)
  WRITE (KLUN) UBOUND (YD%CADHTSS)
  WRITE (KLUN) YD%CADHTSS
ENDIF
LCADHTTS = ALLOCATED (YD%CADHTTS)
WRITE (KLUN) LCADHTTS
IF (LCADHTTS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTTS)
  WRITE (KLUN) UBOUND (YD%CADHTTS)
  WRITE (KLUN) YD%CADHTTS
ENDIF
LCADHTIS = ALLOCATED (YD%CADHTIS)
WRITE (KLUN) LCADHTIS
IF (LCADHTIS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTIS)
  WRITE (KLUN) UBOUND (YD%CADHTIS)
  WRITE (KLUN) YD%CADHTIS
ENDIF
LCADHSSS = ALLOCATED (YD%CADHSSS)
WRITE (KLUN) LCADHSSS
IF (LCADHSSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHSSS)
  WRITE (KLUN) UBOUND (YD%CADHSSS)
  WRITE (KLUN) YD%CADHSSS
ENDIF
LCADHIIS = ALLOCATED (YD%CADHIIS)
WRITE (KLUN) LCADHIIS
IF (LCADHIIS) THEN
  WRITE (KLUN) LBOUND (YD%CADHIIS)
  WRITE (KLUN) UBOUND (YD%CADHIIS)
  WRITE (KLUN) YD%CADHIIS
ENDIF
LCADHWLS = ALLOCATED (YD%CADHWLS)
WRITE (KLUN) LCADHWLS
IF (LCADHWLS) THEN
  WRITE (KLUN) LBOUND (YD%CADHWLS)
  WRITE (KLUN) UBOUND (YD%CADHWLS)
  WRITE (KLUN) YD%CADHWLS
ENDIF
LCADHFSS = ALLOCATED (YD%CADHFSS)
WRITE (KLUN) LCADHFSS
IF (LCADHFSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHFSS)
  WRITE (KLUN) UBOUND (YD%CADHFSS)
  WRITE (KLUN) YD%CADHFSS
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TCDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
READ (KLUN) LCADHTLS
IF (LCADHTLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTLS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTLS
ENDIF
READ (KLUN) LCADHTSS
IF (LCADHTSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTSS
ENDIF
READ (KLUN) LCADHTTS
IF (LCADHTTS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTTS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTTS
ENDIF
READ (KLUN) LCADHTIS
IF (LCADHTIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTIS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTIS
ENDIF
READ (KLUN) LCADHSSS
IF (LCADHSSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHSSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHSSS
ENDIF
READ (KLUN) LCADHIIS
IF (LCADHIIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHIIS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHIIS
ENDIF
READ (KLUN) LCADHWLS
IF (LCADHWLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHWLS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHWLS
ENDIF
READ (KLUN) LCADHFSS
IF (LCADHFSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHFSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHFSS
ENDIF
END SUBROUTINE




END MODULE
