MODULE UTIL_TEOVLP_MOD

USE YOEOVLP, ONLY : TEOVLP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEOVLP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEOVLP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEOVLP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEOVLP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOVLP), INTENT (IN), TARGET :: YD
LOGICAL :: LRA1OVLP
LRA1OVLP = ALLOCATED (YD%RA1OVLP)
WRITE (KLUN) LRA1OVLP
IF (LRA1OVLP) THEN
  WRITE (KLUN) LBOUND (YD%RA1OVLP)
  WRITE (KLUN) UBOUND (YD%RA1OVLP)
  WRITE (KLUN) YD%RA1OVLP
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TEOVLP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOVLP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRA1OVLP
READ (KLUN) LRA1OVLP
IF (LRA1OVLP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RA1OVLP (IL1(1):IU1(1)))
  READ (KLUN) YD%RA1OVLP
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TEOVLP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEOVLP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRA1OVLP

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRA1OVLP = ALLOCATED (YD%RA1OVLP)
IF (LRA1OVLP) THEN
  !$acc enter data create (YD%RA1OVLP)
  !$acc update device (YD%RA1OVLP)
  !$acc enter data attach (YD%RA1OVLP)
ENDIF

END SUBROUTINE



END MODULE
