MODULE UTIL_TDPRECIPS_MOD

USE YOMDPRECIPS, ONLY : TDPRECIPS


INTERFACE SAVE
MODULE PROCEDURE SAVE_TDPRECIPS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDPRECIPS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDPRECIPS
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDPRECIPS
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDPRECIPS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPRECIPS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%HDPRECIPS
WRITE (KLUN) YD%HDCLWC
WRITE (KLUN) YD%RDHAIL1
WRITE (KLUN) YD%RDHAIL2
WRITE (KLUN) YD%RDSEUIL1
WRITE (KLUN) YD%RDSEUIL2
WRITE (KLUN) YD%RDSEUIL3
WRITE (KLUN) YD%RDSEUIL4
WRITE (KLUN) YD%RDSEUIL5
WRITE (KLUN) YD%RDCLWC
WRITE (KLUN) YD%RPRECSEUIL
WRITE (KLUN) YD%RHTOP
WRITE (KLUN) YD%RTPW
WRITE (KLUN) YD%RAWARM
WRITE (KLUN) YD%RACOLD
WRITE (KLUN) YD%NDTPREC
WRITE (KLUN) YD%NDTPREC2
END SUBROUTINE

SUBROUTINE LOAD_TDPRECIPS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPRECIPS), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%HDPRECIPS
READ (KLUN) YD%HDCLWC
READ (KLUN) YD%RDHAIL1
READ (KLUN) YD%RDHAIL2
READ (KLUN) YD%RDSEUIL1
READ (KLUN) YD%RDSEUIL2
READ (KLUN) YD%RDSEUIL3
READ (KLUN) YD%RDSEUIL4
READ (KLUN) YD%RDSEUIL5
READ (KLUN) YD%RDCLWC
READ (KLUN) YD%RPRECSEUIL
READ (KLUN) YD%RHTOP
READ (KLUN) YD%RTPW
READ (KLUN) YD%RAWARM
READ (KLUN) YD%RACOLD
READ (KLUN) YD%NDTPREC
READ (KLUN) YD%NDTPREC2
END SUBROUTINE


SUBROUTINE COPY_TDPRECIPS (YD, LDCREATED)
IMPLICIT NONE
TYPE (TDPRECIPS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

















END SUBROUTINE

SUBROUTINE WIPE_TDPRECIPS (YD, LDDELETED)
IMPLICIT NONE
TYPE (TDPRECIPS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED


















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
