MODULE UTIL_TTRC_MOD

USE YOMTRC, ONLY : TTRC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTRC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTRC
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TTRC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTRC), INTENT (IN), TARGET :: YD
LOGICAL :: LGDEOSI, LGDEOTI, LGDEOTI2, LGEOLT, LGEOXT, LGFLUXC, LGMIXP, LGMU0, LGMU0_MAX, LGMU0_MIN, LGRPROX, LGRSURF, LGUEOSI, LGUEOTI, LGUEOTI2
LGRSURF = ALLOCATED (YD%GRSURF)
WRITE (KLUN) LGRSURF
IF (LGRSURF) THEN
  WRITE (KLUN) LBOUND (YD%GRSURF)
  WRITE (KLUN) UBOUND (YD%GRSURF)
  WRITE (KLUN) YD%GRSURF
ENDIF
LGDEOTI = ALLOCATED (YD%GDEOTI)
WRITE (KLUN) LGDEOTI
IF (LGDEOTI) THEN
  WRITE (KLUN) LBOUND (YD%GDEOTI)
  WRITE (KLUN) UBOUND (YD%GDEOTI)
  WRITE (KLUN) YD%GDEOTI
ENDIF
LGDEOTI2 = ALLOCATED (YD%GDEOTI2)
WRITE (KLUN) LGDEOTI2
IF (LGDEOTI2) THEN
  WRITE (KLUN) LBOUND (YD%GDEOTI2)
  WRITE (KLUN) UBOUND (YD%GDEOTI2)
  WRITE (KLUN) YD%GDEOTI2
ENDIF
LGUEOTI = ALLOCATED (YD%GUEOTI)
WRITE (KLUN) LGUEOTI
IF (LGUEOTI) THEN
  WRITE (KLUN) LBOUND (YD%GUEOTI)
  WRITE (KLUN) UBOUND (YD%GUEOTI)
  WRITE (KLUN) YD%GUEOTI
ENDIF
LGUEOTI2 = ALLOCATED (YD%GUEOTI2)
WRITE (KLUN) LGUEOTI2
IF (LGUEOTI2) THEN
  WRITE (KLUN) LBOUND (YD%GUEOTI2)
  WRITE (KLUN) UBOUND (YD%GUEOTI2)
  WRITE (KLUN) YD%GUEOTI2
ENDIF
LGEOLT = ALLOCATED (YD%GEOLT)
WRITE (KLUN) LGEOLT
IF (LGEOLT) THEN
  WRITE (KLUN) LBOUND (YD%GEOLT)
  WRITE (KLUN) UBOUND (YD%GEOLT)
  WRITE (KLUN) YD%GEOLT
ENDIF
LGEOXT = ALLOCATED (YD%GEOXT)
WRITE (KLUN) LGEOXT
IF (LGEOXT) THEN
  WRITE (KLUN) LBOUND (YD%GEOXT)
  WRITE (KLUN) UBOUND (YD%GEOXT)
  WRITE (KLUN) YD%GEOXT
ENDIF
LGRPROX = ALLOCATED (YD%GRPROX)
WRITE (KLUN) LGRPROX
IF (LGRPROX) THEN
  WRITE (KLUN) LBOUND (YD%GRPROX)
  WRITE (KLUN) UBOUND (YD%GRPROX)
  WRITE (KLUN) YD%GRPROX
ENDIF
LGMIXP = ALLOCATED (YD%GMIXP)
WRITE (KLUN) LGMIXP
IF (LGMIXP) THEN
  WRITE (KLUN) LBOUND (YD%GMIXP)
  WRITE (KLUN) UBOUND (YD%GMIXP)
  WRITE (KLUN) YD%GMIXP
ENDIF
LGFLUXC = ALLOCATED (YD%GFLUXC)
WRITE (KLUN) LGFLUXC
IF (LGFLUXC) THEN
  WRITE (KLUN) LBOUND (YD%GFLUXC)
  WRITE (KLUN) UBOUND (YD%GFLUXC)
  WRITE (KLUN) YD%GFLUXC
ENDIF
LGDEOSI = ALLOCATED (YD%GDEOSI)
WRITE (KLUN) LGDEOSI
IF (LGDEOSI) THEN
  WRITE (KLUN) LBOUND (YD%GDEOSI)
  WRITE (KLUN) UBOUND (YD%GDEOSI)
  WRITE (KLUN) YD%GDEOSI
ENDIF
LGUEOSI = ALLOCATED (YD%GUEOSI)
WRITE (KLUN) LGUEOSI
IF (LGUEOSI) THEN
  WRITE (KLUN) LBOUND (YD%GUEOSI)
  WRITE (KLUN) UBOUND (YD%GUEOSI)
  WRITE (KLUN) YD%GUEOSI
ENDIF
LGMU0 = ALLOCATED (YD%GMU0)
WRITE (KLUN) LGMU0
IF (LGMU0) THEN
  WRITE (KLUN) LBOUND (YD%GMU0)
  WRITE (KLUN) UBOUND (YD%GMU0)
  WRITE (KLUN) YD%GMU0
ENDIF
LGMU0_MIN = ALLOCATED (YD%GMU0_MIN)
WRITE (KLUN) LGMU0_MIN
IF (LGMU0_MIN) THEN
  WRITE (KLUN) LBOUND (YD%GMU0_MIN)
  WRITE (KLUN) UBOUND (YD%GMU0_MIN)
  WRITE (KLUN) YD%GMU0_MIN
ENDIF
LGMU0_MAX = ALLOCATED (YD%GMU0_MAX)
WRITE (KLUN) LGMU0_MAX
IF (LGMU0_MAX) THEN
  WRITE (KLUN) LBOUND (YD%GMU0_MAX)
  WRITE (KLUN) UBOUND (YD%GMU0_MAX)
  WRITE (KLUN) YD%GMU0_MAX
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TTRC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTRC), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LGDEOSI, LGDEOTI, LGDEOTI2, LGEOLT, LGEOXT, LGFLUXC, LGMIXP, LGMU0, LGMU0_MAX, LGMU0_MIN, LGRPROX, LGRSURF, LGUEOSI, LGUEOTI, LGUEOTI2
READ (KLUN) LGRSURF
IF (LGRSURF) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GRSURF (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GRSURF
ENDIF
READ (KLUN) LGDEOTI
IF (LGDEOTI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GDEOTI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GDEOTI
ENDIF
READ (KLUN) LGDEOTI2
IF (LGDEOTI2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GDEOTI2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GDEOTI2
ENDIF
READ (KLUN) LGUEOTI
IF (LGUEOTI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GUEOTI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GUEOTI
ENDIF
READ (KLUN) LGUEOTI2
IF (LGUEOTI2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GUEOTI2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GUEOTI2
ENDIF
READ (KLUN) LGEOLT
IF (LGEOLT) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GEOLT (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GEOLT
ENDIF
READ (KLUN) LGEOXT
IF (LGEOXT) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GEOXT (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GEOXT
ENDIF
READ (KLUN) LGRPROX
IF (LGRPROX) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GRPROX (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GRPROX
ENDIF
READ (KLUN) LGMIXP
IF (LGMIXP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GMIXP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GMIXP
ENDIF
READ (KLUN) LGFLUXC
IF (LGFLUXC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GFLUXC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GFLUXC
ENDIF
READ (KLUN) LGDEOSI
IF (LGDEOSI) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GDEOSI (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GDEOSI
ENDIF
READ (KLUN) LGUEOSI
IF (LGUEOSI) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%GUEOSI (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%GUEOSI
ENDIF
READ (KLUN) LGMU0
IF (LGMU0) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%GMU0 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%GMU0
ENDIF
READ (KLUN) LGMU0_MIN
IF (LGMU0_MIN) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GMU0_MIN (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GMU0_MIN
ENDIF
READ (KLUN) LGMU0_MAX
IF (LGMU0_MAX) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GMU0_MAX (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GMU0_MAX
ENDIF
END SUBROUTINE




END MODULE
