MODULE UTIL_TSCO_MOD

USE INTDYNSL_MOD, ONLY : TSCO


INTERFACE SAVE
MODULE PROCEDURE SAVE_TSCO
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSCO
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSCO
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSCO
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSCO (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSCO), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_COSCO
WRITE (KLUN) YD%M_SINCO
WRITE (KLUN) YD%M_SINLA
WRITE (KLUN) YD%M_COPHI
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TSCO (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSCO), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_COSCO
READ (KLUN) YD%M_SINCO
READ (KLUN) YD%M_SINLA
READ (KLUN) YD%M_COPHI
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TSCO (YD, LDCREATED)
IMPLICIT NONE
TYPE (TSCO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





END SUBROUTINE

SUBROUTINE WIPE_TSCO (YD, LDDELETED)
IMPLICIT NONE
TYPE (TSCO), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED






LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
