MODULE UTIL_FIELD_VARIABLES_MOD

USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

INTERFACE SAVE
MODULE PROCEDURE SAVE_FIELD_VARIABLES
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_FIELD_VARIABLES
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_FIELD_VARIABLES
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_FIELD_VARIABLES
END INTERFACE



CONTAINS

SUBROUTINE SAVE_FIELD_VARIABLES (KLUN, YD)
USE UTIL_GEOMETRY_VARIABLES_MOD
USE UTIL_VARIABLE_3D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (FIELD_VARIABLES), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%Q)
CALL SAVE (KLUN, YD%O3)
CALL SAVE (KLUN, YD%GEOMETRY)
END SUBROUTINE

SUBROUTINE LOAD_FIELD_VARIABLES (KLUN, YD)
USE UTIL_GEOMETRY_VARIABLES_MOD
USE UTIL_VARIABLE_3D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (FIELD_VARIABLES), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%Q)
CALL LOAD (KLUN, YD%O3)
NULLIFY (YD%GHG)
NULLIFY (YD%CHEM)
NULLIFY (YD%AERO)
NULLIFY (YD%FORC)
NULLIFY (YD%EZDIAG)
NULLIFY (YD%ERA40)
NULLIFY (YD%NOGW)
NULLIFY (YD%EDRP)
NULLIFY (YD%SLDIA)
NULLIFY (YD%AERAOT)
NULLIFY (YD%AERLISI)
NULLIFY (YD%AEROUT)
NULLIFY (YD%AEROCLIM)
NULLIFY (YD%UVP)
NULLIFY (YD%PHYS)
NULLIFY (YD%CRM)
NULLIFY (YD%LIMA)
NULLIFY (YD%EXT)
CALL LOAD (KLUN, YD%GEOMETRY)
END SUBROUTINE


SUBROUTINE COPY_FIELD_VARIABLES (YD, LDCREATED)
USE UTIL_GEOMETRY_VARIABLES_MOD
USE UTIL_VARIABLE_3D_MOD
IMPLICIT NONE
TYPE (FIELD_VARIABLES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%Q, LDCREATED=.TRUE.)

CALL COPY (YD%O3, LDCREATED=.TRUE.)

CALL COPY (YD%GEOMETRY, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_FIELD_VARIABLES (YD, LDDELETED)
USE UTIL_GEOMETRY_VARIABLES_MOD
USE UTIL_VARIABLE_3D_MOD
IMPLICIT NONE
TYPE (FIELD_VARIABLES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%Q, LDDELETED=.TRUE.)

CALL WIPE (YD%O3, LDDELETED=.TRUE.)

CALL WIPE (YD%GEOMETRY, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
