MODULE UTIL_MODEL_PHYSICS_GENERAL_TYPE_MOD

USE MODEL_PHYSICS_GENERAL_MOD, ONLY : MODEL_PHYSICS_GENERAL_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_GENERAL_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_GENERAL_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_GENERAL_TYPE (KLUN, YD)
USE UTIL_TDPHY_MOD
USE UTIL_TSLPHY_MOD
USE UTIL_TVDF_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_GENERAL_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRDPHY)
CALL SAVE (KLUN, YD%YRSLPHY)
CALL SAVE (KLUN, YD%YRVDF)
END SUBROUTINE
SUBROUTINE LOAD_MODEL_PHYSICS_GENERAL_TYPE (KLUN, YD)
USE UTIL_TDPHY_MOD
USE UTIL_TSLPHY_MOD
USE UTIL_TVDF_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_GENERAL_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRDPHY)
CALL LOAD (KLUN, YD%YRSLPHY)
CALL LOAD (KLUN, YD%YRVDF)
END SUBROUTINE




END MODULE
