MODULE UTIL_TDYN_MOD

USE YOMDYN, ONLY : TDYN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDYN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDYN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDYN
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDYN
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDYN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYN), INTENT (IN), TARGET :: YD
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRKRF, LSIALPH, LSIB, LSIBI, LSIDELP
LOGICAL :: LSIDPHI, LSIFAC, LSIFACI, LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSIMI, LSIMO
LOGICAL :: LSIRDEL, LSITLAF, LSITLAH, LSITRAM, LSIVP, LSIWEIG, LSI_ILAPKSSI, LSLHDA, LSLHDD0, LSLHD_MASK_T
LOGICAL :: LSLHD_MASK_U
WRITE (KLUN) YD%REPS1
WRITE (KLUN) YD%REPS2
WRITE (KLUN) YD%REPSM1
WRITE (KLUN) YD%REPSM2
WRITE (KLUN) YD%REPSP1
WRITE (KLUN) YD%HDIRVOR
WRITE (KLUN) YD%HDIRDIV
WRITE (KLUN) YD%HDIRT
WRITE (KLUN) YD%HDIRQ
WRITE (KLUN) YD%HDIRO3
WRITE (KLUN) YD%HDIRPD
WRITE (KLUN) YD%HDIRVD
WRITE (KLUN) YD%HDIRSP
WRITE (KLUN) YD%HRDIRVOR
WRITE (KLUN) YD%HRDIRDIV
WRITE (KLUN) YD%HRDIRT
WRITE (KLUN) YD%HRDIRQ
WRITE (KLUN) YD%HRDIRO3
WRITE (KLUN) YD%HRDIRPD
WRITE (KLUN) YD%HRDIRVD
WRITE (KLUN) YD%HRDIRSP
WRITE (KLUN) YD%RRDXTAU
WRITE (KLUN) YD%RDAMPVOR
WRITE (KLUN) YD%RDAMPDIV
WRITE (KLUN) YD%RDAMPT
WRITE (KLUN) YD%RDAMPQ
WRITE (KLUN) YD%RDAMPO3
WRITE (KLUN) YD%RDAMPPD
WRITE (KLUN) YD%RDAMPVD
WRITE (KLUN) YD%RDAMPSP
WRITE (KLUN) YD%LNEWHD
WRITE (KLUN) YD%REXPDH
WRITE (KLUN) YD%FRANDH
WRITE (KLUN) YD%SLEVDH
WRITE (KLUN) YD%SLEVDH1
WRITE (KLUN) YD%SLEVDH2
WRITE (KLUN) YD%SLEVDH3
WRITE (KLUN) YD%NSREFDH
WRITE (KLUN) YD%RATIO_HDI_TOP
WRITE (KLUN) YD%NPROFILEHD
WRITE (KLUN) YD%RPROFHDBT
WRITE (KLUN) YD%RPROFHDTP
WRITE (KLUN) YD%RPROFHDMX
WRITE (KLUN) YD%RPROFHDEX
WRITE (KLUN) YD%LRDISPE_EC
LRDIVOR = ALLOCATED (YD%RDIVOR)
WRITE (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  WRITE (KLUN) LBOUND (YD%RDIVOR)
  WRITE (KLUN) UBOUND (YD%RDIVOR)
  WRITE (KLUN) YD%RDIVOR
ENDIF
LRDIDIV = ALLOCATED (YD%RDIDIV)
WRITE (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  WRITE (KLUN) LBOUND (YD%RDIDIV)
  WRITE (KLUN) UBOUND (YD%RDIDIV)
  WRITE (KLUN) YD%RDIDIV
ENDIF
LRDITG = ALLOCATED (YD%RDITG)
WRITE (KLUN) LRDITG
IF (LRDITG) THEN
  WRITE (KLUN) LBOUND (YD%RDITG)
  WRITE (KLUN) UBOUND (YD%RDITG)
  WRITE (KLUN) YD%RDITG
ENDIF
LRDIGFL = ALLOCATED (YD%RDIGFL)
WRITE (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  WRITE (KLUN) LBOUND (YD%RDIGFL)
  WRITE (KLUN) UBOUND (YD%RDIGFL)
  WRITE (KLUN) YD%RDIGFL
ENDIF
LRDIPD = ALLOCATED (YD%RDIPD)
WRITE (KLUN) LRDIPD
IF (LRDIPD) THEN
  WRITE (KLUN) LBOUND (YD%RDIPD)
  WRITE (KLUN) UBOUND (YD%RDIPD)
  WRITE (KLUN) YD%RDIPD
ENDIF
LRDIVD = ALLOCATED (YD%RDIVD)
WRITE (KLUN) LRDIVD
IF (LRDIVD) THEN
  WRITE (KLUN) LBOUND (YD%RDIVD)
  WRITE (KLUN) UBOUND (YD%RDIVD)
  WRITE (KLUN) YD%RDIVD
ENDIF
LRDISP = ALLOCATED (YD%RDISP)
WRITE (KLUN) LRDISP
IF (LRDISP) THEN
  WRITE (KLUN) LBOUND (YD%RDISP)
  WRITE (KLUN) UBOUND (YD%RDISP)
  WRITE (KLUN) YD%RDISP
ENDIF
LRDHI = ALLOCATED (YD%RDHI)
WRITE (KLUN) LRDHI
IF (LRDHI) THEN
  WRITE (KLUN) LBOUND (YD%RDHI)
  WRITE (KLUN) UBOUND (YD%RDHI)
  WRITE (KLUN) YD%RDHI
ENDIF
WRITE (KLUN) YD%LSTRHD
WRITE (KLUN) YD%HDTIME_STRHD
WRITE (KLUN) YD%LTOP_VOR
WRITE (KLUN) YD%NTOP_VOR_TRUNC
WRITE (KLUN) YD%NTOP_VOR_BOT
LSLHDA = ALLOCATED (YD%SLHDA)
WRITE (KLUN) LSLHDA
IF (LSLHDA) THEN
  WRITE (KLUN) LBOUND (YD%SLHDA)
  WRITE (KLUN) UBOUND (YD%SLHDA)
  WRITE (KLUN) YD%SLHDA
ENDIF
WRITE (KLUN) YD%SLHDA0
WRITE (KLUN) YD%SLHDA0T
WRITE (KLUN) YD%SLHDB
WRITE (KLUN) YD%SLHDBT
LSLHDD0 = ALLOCATED (YD%SLHDD0)
WRITE (KLUN) LSLHDD0
IF (LSLHDD0) THEN
  WRITE (KLUN) LBOUND (YD%SLHDD0)
  WRITE (KLUN) UBOUND (YD%SLHDD0)
  WRITE (KLUN) YD%SLHDD0
ENDIF
WRITE (KLUN) YD%SLHDD00
WRITE (KLUN) YD%SLHDD00T
WRITE (KLUN) YD%SLHDDIV
WRITE (KLUN) YD%SLHDRATDDIV
WRITE (KLUN) YD%SLHDHOR
WRITE (KLUN) YD%LSLHDHEAT
WRITE (KLUN) YD%LSLHDSPONGE
WRITE (KLUN) YD%HDSRVOR
WRITE (KLUN) YD%HDSRDIV
WRITE (KLUN) YD%HDSRVD
WRITE (KLUN) YD%HRDSRVOR
WRITE (KLUN) YD%HRDSRDIV
WRITE (KLUN) YD%HRDSRVD
WRITE (KLUN) YD%RDAMPVORS
WRITE (KLUN) YD%RDAMPDIVS
WRITE (KLUN) YD%RDAMPVDS
WRITE (KLUN) YD%RDAMPHDS
WRITE (KLUN) YD%REXPDHS
WRITE (KLUN) YD%SLEVDHS
WRITE (KLUN) YD%SLEVDHS1
WRITE (KLUN) YD%SLEVDHS2
WRITE (KLUN) YD%SDRED
LRDSVOR = ALLOCATED (YD%RDSVOR)
WRITE (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  WRITE (KLUN) LBOUND (YD%RDSVOR)
  WRITE (KLUN) UBOUND (YD%RDSVOR)
  WRITE (KLUN) YD%RDSVOR
ENDIF
LRDSDIV = ALLOCATED (YD%RDSDIV)
WRITE (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  WRITE (KLUN) LBOUND (YD%RDSDIV)
  WRITE (KLUN) UBOUND (YD%RDSDIV)
  WRITE (KLUN) YD%RDSDIV
ENDIF
LRDSVD = ALLOCATED (YD%RDSVD)
WRITE (KLUN) LRDSVD
IF (LRDSVD) THEN
  WRITE (KLUN) LBOUND (YD%RDSVD)
  WRITE (KLUN) UBOUND (YD%RDSVD)
  WRITE (KLUN) YD%RDSVD
ENDIF
LRDHS = ALLOCATED (YD%RDHS)
WRITE (KLUN) LRDHS
IF (LRDHS) THEN
  WRITE (KLUN) LBOUND (YD%RDHS)
  WRITE (KLUN) UBOUND (YD%RDHS)
  WRITE (KLUN) YD%RDHS
ENDIF
LSLHD_MASK_U = ALLOCATED (YD%SLHD_MASK_U)
WRITE (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  WRITE (KLUN) LBOUND (YD%SLHD_MASK_U)
  WRITE (KLUN) UBOUND (YD%SLHD_MASK_U)
  WRITE (KLUN) YD%SLHD_MASK_U
ENDIF
LSLHD_MASK_T = ALLOCATED (YD%SLHD_MASK_T)
WRITE (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  WRITE (KLUN) LBOUND (YD%SLHD_MASK_T)
  WRITE (KLUN) UBOUND (YD%SLHD_MASK_T)
  WRITE (KLUN) YD%SLHD_MASK_T
ENDIF
WRITE (KLUN) YD%NLEV_SPONGE
WRITE (KLUN) YD%LRFRIC
WRITE (KLUN) YD%LRFRICISOTR
LRCORDIT = ALLOCATED (YD%RCORDIT)
WRITE (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  WRITE (KLUN) LBOUND (YD%RCORDIT)
  WRITE (KLUN) UBOUND (YD%RCORDIT)
  WRITE (KLUN) YD%RCORDIT
ENDIF
LRCORDIH = ALLOCATED (YD%RCORDIH)
WRITE (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  WRITE (KLUN) LBOUND (YD%RCORDIH)
  WRITE (KLUN) UBOUND (YD%RCORDIH)
  WRITE (KLUN) YD%RCORDIH
ENDIF
LRCORDIF = ALLOCATED (YD%RCORDIF)
WRITE (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  WRITE (KLUN) LBOUND (YD%RCORDIF)
  WRITE (KLUN) UBOUND (YD%RCORDIF)
  WRITE (KLUN) YD%RCORDIF
ENDIF
WRITE (KLUN) YD%VMAX1
WRITE (KLUN) YD%VMAX2
WRITE (KLUN) YD%RMAX_D3
WRITE (KLUN) YD%LBOUND_D3
LRKRF = ALLOCATED (YD%RKRF)
WRITE (KLUN) LRKRF
IF (LRKRF) THEN
  WRITE (KLUN) LBOUND (YD%RKRF)
  WRITE (KLUN) UBOUND (YD%RKRF)
  WRITE (KLUN) YD%RKRF
ENDIF
WRITE (KLUN) YD%NMAXLEVRF
WRITE (KLUN) YD%RRFZ1
WRITE (KLUN) YD%RRFPLM
WRITE (KLUN) YD%RRFTAU
WRITE (KLUN) YD%RTEMRB
WRITE (KLUN) YD%NRUBC
WRITE (KLUN) YD%LSIDG
WRITE (KLUN) YD%LDYN_STABAN
WRITE (KLUN) YD%BETADT
WRITE (KLUN) YD%RBT
WRITE (KLUN) YD%RBTS2
WRITE (KLUN) YD%REFGEO
WRITE (KLUN) YD%SIPR
WRITE (KLUN) YD%SITR
WRITE (KLUN) YD%SITRA
WRITE (KLUN) YD%SITRUB
WRITE (KLUN) YD%SIPRUB
WRITE (KLUN) YD%SITIME
WRITE (KLUN) YD%SIRPRG
WRITE (KLUN) YD%SIRPRN
WRITE (KLUN) YD%SIRSLP
WRITE (KLUN) YD%RSLOPE_MAX
WRITE (KLUN) YD%NSITER
WRITE (KLUN) YD%NCURRENT_ITER
WRITE (KLUN) YD%LRHDI_LASTITERPC
WRITE (KLUN) YD%NITERHELM
WRITE (KLUN) YD%NOPT_SITRA
LSIALPH = ALLOCATED (YD%SIALPH)
WRITE (KLUN) LSIALPH
IF (LSIALPH) THEN
  WRITE (KLUN) LBOUND (YD%SIALPH)
  WRITE (KLUN) UBOUND (YD%SIALPH)
  WRITE (KLUN) YD%SIALPH
ENDIF
LSILNPR = ALLOCATED (YD%SILNPR)
WRITE (KLUN) LSILNPR
IF (LSILNPR) THEN
  WRITE (KLUN) LBOUND (YD%SILNPR)
  WRITE (KLUN) UBOUND (YD%SILNPR)
  WRITE (KLUN) YD%SILNPR
ENDIF
LSIDELP = ALLOCATED (YD%SIDELP)
WRITE (KLUN) LSIDELP
IF (LSIDELP) THEN
  WRITE (KLUN) LBOUND (YD%SIDELP)
  WRITE (KLUN) UBOUND (YD%SIDELP)
  WRITE (KLUN) YD%SIDELP
ENDIF
LSIRDEL = ALLOCATED (YD%SIRDEL)
WRITE (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  WRITE (KLUN) LBOUND (YD%SIRDEL)
  WRITE (KLUN) UBOUND (YD%SIRDEL)
  WRITE (KLUN) YD%SIRDEL
ENDIF
LSITLAH = ALLOCATED (YD%SITLAH)
WRITE (KLUN) LSITLAH
IF (LSITLAH) THEN
  WRITE (KLUN) LBOUND (YD%SITLAH)
  WRITE (KLUN) UBOUND (YD%SITLAH)
  WRITE (KLUN) YD%SITLAH
ENDIF
LSITLAF = ALLOCATED (YD%SITLAF)
WRITE (KLUN) LSITLAF
IF (LSITLAF) THEN
  WRITE (KLUN) LBOUND (YD%SITLAF)
  WRITE (KLUN) UBOUND (YD%SITLAF)
  WRITE (KLUN) YD%SITLAF
ENDIF
LSIDPHI = ALLOCATED (YD%SIDPHI)
WRITE (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  WRITE (KLUN) LBOUND (YD%SIDPHI)
  WRITE (KLUN) UBOUND (YD%SIDPHI)
  WRITE (KLUN) YD%SIDPHI
ENDIF
LSIWEIG = ALLOCATED (YD%SIWEIG)
WRITE (KLUN) LSIWEIG
IF (LSIWEIG) THEN
  WRITE (KLUN) LBOUND (YD%SIWEIG)
  WRITE (KLUN) UBOUND (YD%SIWEIG)
  WRITE (KLUN) YD%SIWEIG
ENDIF
LSIB = ALLOCATED (YD%SIB)
WRITE (KLUN) LSIB
IF (LSIB) THEN
  WRITE (KLUN) LBOUND (YD%SIB)
  WRITE (KLUN) UBOUND (YD%SIB)
  WRITE (KLUN) YD%SIB
ENDIF
LSIMO = ALLOCATED (YD%SIMO)
WRITE (KLUN) LSIMO
IF (LSIMO) THEN
  WRITE (KLUN) LBOUND (YD%SIMO)
  WRITE (KLUN) UBOUND (YD%SIMO)
  WRITE (KLUN) YD%SIMO
ENDIF
LSIMI = ALLOCATED (YD%SIMI)
WRITE (KLUN) LSIMI
IF (LSIMI) THEN
  WRITE (KLUN) LBOUND (YD%SIMI)
  WRITE (KLUN) UBOUND (YD%SIMI)
  WRITE (KLUN) YD%SIMI
ENDIF
LSIVP = ALLOCATED (YD%SIVP)
WRITE (KLUN) LSIVP
IF (LSIVP) THEN
  WRITE (KLUN) LBOUND (YD%SIVP)
  WRITE (KLUN) UBOUND (YD%SIVP)
  WRITE (KLUN) YD%SIVP
ENDIF
LSIHEG = ALLOCATED (YD%SIHEG)
WRITE (KLUN) LSIHEG
IF (LSIHEG) THEN
  WRITE (KLUN) LBOUND (YD%SIHEG)
  WRITE (KLUN) UBOUND (YD%SIHEG)
  WRITE (KLUN) YD%SIHEG
ENDIF
LSIHEG2 = ALLOCATED (YD%SIHEG2)
WRITE (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  WRITE (KLUN) LBOUND (YD%SIHEG2)
  WRITE (KLUN) UBOUND (YD%SIHEG2)
  WRITE (KLUN) YD%SIHEG2
ENDIF
LSIHEGB = ALLOCATED (YD%SIHEGB)
WRITE (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  WRITE (KLUN) LBOUND (YD%SIHEGB)
  WRITE (KLUN) UBOUND (YD%SIHEGB)
  WRITE (KLUN) YD%SIHEGB
ENDIF
LSIHEGB2 = ALLOCATED (YD%SIHEGB2)
WRITE (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  WRITE (KLUN) LBOUND (YD%SIHEGB2)
  WRITE (KLUN) UBOUND (YD%SIHEGB2)
  WRITE (KLUN) YD%SIHEGB2
ENDIF
LSIFAC = ALLOCATED (YD%SIFAC)
WRITE (KLUN) LSIFAC
IF (LSIFAC) THEN
  WRITE (KLUN) LBOUND (YD%SIFAC)
  WRITE (KLUN) UBOUND (YD%SIFAC)
  WRITE (KLUN) YD%SIFAC
ENDIF
LSIFACI = ALLOCATED (YD%SIFACI)
WRITE (KLUN) LSIFACI
IF (LSIFACI) THEN
  WRITE (KLUN) LBOUND (YD%SIFACI)
  WRITE (KLUN) UBOUND (YD%SIFACI)
  WRITE (KLUN) YD%SIFACI
ENDIF
LSI_ILAPKSSI = ALLOCATED (YD%SI_ILAPKSSI)
WRITE (KLUN) LSI_ILAPKSSI
IF (LSI_ILAPKSSI) THEN
  WRITE (KLUN) LBOUND (YD%SI_ILAPKSSI)
  WRITE (KLUN) UBOUND (YD%SI_ILAPKSSI)
  WRITE (KLUN) YD%SI_ILAPKSSI
ENDIF
LSITRAM = ALLOCATED (YD%SITRAM)
WRITE (KLUN) LSITRAM
IF (LSITRAM) THEN
  WRITE (KLUN) LBOUND (YD%SITRAM)
  WRITE (KLUN) UBOUND (YD%SITRAM)
  WRITE (KLUN) YD%SITRAM
ENDIF
WRITE (KLUN) YD%VNORM
WRITE (KLUN) YD%NVLAG
WRITE (KLUN) YD%NWLAG
WRITE (KLUN) YD%NTLAG
WRITE (KLUN) YD%NSPDLAG
WRITE (KLUN) YD%NSVDLAG
WRITE (KLUN) YD%NSPLTHOI
WRITE (KLUN) YD%LSPLTHOIGFL
WRITE (KLUN) YD%NSLDIMK
WRITE (KLUN) YD%NITMP
WRITE (KLUN) YD%VETAON
WRITE (KLUN) YD%VETAOX
WRITE (KLUN) YD%LSETTLSVF
WRITE (KLUN) YD%LSETFSTAT
WRITE (KLUN) YD%RW2TLFF
WRITE (KLUN) YD%RALPHA
WRITE (KLUN) YD%RALPHA_TOP
WRITE (KLUN) YD%NLEV_ZALPHA
WRITE (KLUN) YD%NEDER
WRITE (KLUN) YD%LWENOBC
WRITE (KLUN) YD%LSLDP_RK
WRITE (KLUN) YD%LSLDP_CURV
WRITE (KLUN) YD%VESL
WRITE (KLUN) YD%XIDT
WRITE (KLUN) YD%LQMW
WRITE (KLUN) YD%LQMHW
WRITE (KLUN) YD%LQMT
WRITE (KLUN) YD%LQMHT
WRITE (KLUN) YD%LQMP
WRITE (KLUN) YD%LQMHP
WRITE (KLUN) YD%LQMPD
WRITE (KLUN) YD%LQMHPD
WRITE (KLUN) YD%LQMVD
WRITE (KLUN) YD%LQMHVD
WRITE (KLUN) YD%LVWENO_W
WRITE (KLUN) YD%LVWENO_T
WRITE (KLUN) YD%LVWENO_SP
WRITE (KLUN) YD%LVWENO_SPD
WRITE (KLUN) YD%LVWENO_SVD
WRITE (KLUN) YD%WENO_ALPHA_W
WRITE (KLUN) YD%WENO_ALPHA_T
WRITE (KLUN) YD%WENO_ALPHA_SP
WRITE (KLUN) YD%WENO_ALPHA_SPD
WRITE (KLUN) YD%WENO_ALPHA_SVD
WRITE (KLUN) YD%LADVF
WRITE (KLUN) YD%LIMPF
WRITE (KLUN) YD%L2TLFF
WRITE (KLUN) YD%RCMSLP0
WRITE (KLUN) YD%NCOMP_CVGQ
WRITE (KLUN) YD%LSVTSM
WRITE (KLUN) YD%RPRES_SVTSM
WRITE (KLUN) YD%RPRES_SETTLSVF
WRITE (KLUN) YD%NFLEVSF
WRITE (KLUN) YD%RSCALE
WRITE (KLUN) YD%RSCALEOFF
WRITE (KLUN) YD%LHDIFFM
WRITE (KLUN) YD%LSPECVIS
WRITE (KLUN) YD%NDIFFACT
WRITE (KLUN) YD%LGPSTRESS
WRITE (KLUN) YD%RCLSTRESS
WRITE (KLUN) YD%RCLPOLE
WRITE (KLUN) YD%NVSEPC
WRITE (KLUN) YD%NVSEPL
WRITE (KLUN) YD%LFINDVSEP
WRITE (KLUN) YD%LMASCOR
WRITE (KLUN) YD%LMASDRY
WRITE (KLUN) YD%LGPMASCOR
WRITE (KLUN) YD%NGPMASCOR
WRITE (KLUN) YD%GPMASSI
WRITE (KLUN) YD%GMASSI
WRITE (KLUN) YD%GMASS0
WRITE (KLUN) YD%GMASSINC
WRITE (KLUN) YD%LNODRYFLX
LSIBI = ALLOCATED (YD%SIBI)
WRITE (KLUN) LSIBI
IF (LSIBI) THEN
  WRITE (KLUN) LBOUND (YD%SIBI)
  WRITE (KLUN) UBOUND (YD%SIBI)
  WRITE (KLUN) YD%SIBI
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TDYN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYN), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRKRF, LSIALPH, LSIB, LSIBI, LSIDELP
LOGICAL :: LSIDPHI, LSIFAC, LSIFACI, LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSIMI, LSIMO
LOGICAL :: LSIRDEL, LSITLAF, LSITLAH, LSITRAM, LSIVP, LSIWEIG, LSI_ILAPKSSI, LSLHDA, LSLHDD0, LSLHD_MASK_T
LOGICAL :: LSLHD_MASK_U
READ (KLUN) YD%REPS1
READ (KLUN) YD%REPS2
READ (KLUN) YD%REPSM1
READ (KLUN) YD%REPSM2
READ (KLUN) YD%REPSP1
READ (KLUN) YD%HDIRVOR
READ (KLUN) YD%HDIRDIV
READ (KLUN) YD%HDIRT
READ (KLUN) YD%HDIRQ
READ (KLUN) YD%HDIRO3
READ (KLUN) YD%HDIRPD
READ (KLUN) YD%HDIRVD
READ (KLUN) YD%HDIRSP
READ (KLUN) YD%HRDIRVOR
READ (KLUN) YD%HRDIRDIV
READ (KLUN) YD%HRDIRT
READ (KLUN) YD%HRDIRQ
READ (KLUN) YD%HRDIRO3
READ (KLUN) YD%HRDIRPD
READ (KLUN) YD%HRDIRVD
READ (KLUN) YD%HRDIRSP
READ (KLUN) YD%RRDXTAU
READ (KLUN) YD%RDAMPVOR
READ (KLUN) YD%RDAMPDIV
READ (KLUN) YD%RDAMPT
READ (KLUN) YD%RDAMPQ
READ (KLUN) YD%RDAMPO3
READ (KLUN) YD%RDAMPPD
READ (KLUN) YD%RDAMPVD
READ (KLUN) YD%RDAMPSP
READ (KLUN) YD%LNEWHD
READ (KLUN) YD%REXPDH
READ (KLUN) YD%FRANDH
READ (KLUN) YD%SLEVDH
READ (KLUN) YD%SLEVDH1
READ (KLUN) YD%SLEVDH2
READ (KLUN) YD%SLEVDH3
READ (KLUN) YD%NSREFDH
READ (KLUN) YD%RATIO_HDI_TOP
READ (KLUN) YD%NPROFILEHD
READ (KLUN) YD%RPROFHDBT
READ (KLUN) YD%RPROFHDTP
READ (KLUN) YD%RPROFHDMX
READ (KLUN) YD%RPROFHDEX
READ (KLUN) YD%LRDISPE_EC
READ (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIVOR
ENDIF
READ (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIDIV
ENDIF
READ (KLUN) LRDITG
IF (LRDITG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDITG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDITG
ENDIF
READ (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDIGFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDIGFL
ENDIF
READ (KLUN) LRDIPD
IF (LRDIPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIPD
ENDIF
READ (KLUN) LRDIVD
IF (LRDIVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIVD
ENDIF
READ (KLUN) LRDISP
IF (LRDISP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RDISP (IL1(1):IU1(1)))
  READ (KLUN) YD%RDISP
ENDIF
READ (KLUN) LRDHI
IF (LRDHI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDHI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDHI
ENDIF
READ (KLUN) YD%LSTRHD
READ (KLUN) YD%HDTIME_STRHD
READ (KLUN) YD%LTOP_VOR
READ (KLUN) YD%NTOP_VOR_TRUNC
READ (KLUN) YD%NTOP_VOR_BOT
READ (KLUN) LSLHDA
IF (LSLHDA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SLHDA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SLHDA
ENDIF
READ (KLUN) YD%SLHDA0
READ (KLUN) YD%SLHDA0T
READ (KLUN) YD%SLHDB
READ (KLUN) YD%SLHDBT
READ (KLUN) LSLHDD0
IF (LSLHDD0) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SLHDD0 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SLHDD0
ENDIF
READ (KLUN) YD%SLHDD00
READ (KLUN) YD%SLHDD00T
READ (KLUN) YD%SLHDDIV
READ (KLUN) YD%SLHDRATDDIV
READ (KLUN) YD%SLHDHOR
READ (KLUN) YD%LSLHDHEAT
READ (KLUN) YD%LSLHDSPONGE
READ (KLUN) YD%HDSRVOR
READ (KLUN) YD%HDSRDIV
READ (KLUN) YD%HDSRVD
READ (KLUN) YD%HRDSRVOR
READ (KLUN) YD%HRDSRDIV
READ (KLUN) YD%HRDSRVD
READ (KLUN) YD%RDAMPVORS
READ (KLUN) YD%RDAMPDIVS
READ (KLUN) YD%RDAMPVDS
READ (KLUN) YD%RDAMPHDS
READ (KLUN) YD%REXPDHS
READ (KLUN) YD%SLEVDHS
READ (KLUN) YD%SLEVDHS1
READ (KLUN) YD%SLEVDHS2
READ (KLUN) YD%SDRED
READ (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSVOR
ENDIF
READ (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSDIV
ENDIF
READ (KLUN) LRDSVD
IF (LRDSVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSVD
ENDIF
READ (KLUN) LRDHS
IF (LRDHS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDHS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDHS
ENDIF
READ (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHD_MASK_U (IL1(1):IU1(1)))
  READ (KLUN) YD%SLHD_MASK_U
ENDIF
READ (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHD_MASK_T (IL1(1):IU1(1)))
  READ (KLUN) YD%SLHD_MASK_T
ENDIF
READ (KLUN) YD%NLEV_SPONGE
READ (KLUN) YD%LRFRIC
READ (KLUN) YD%LRFRICISOTR
READ (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIT (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORDIT
ENDIF
READ (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIH (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORDIH
ENDIF
READ (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIF (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORDIF
ENDIF
READ (KLUN) YD%VMAX1
READ (KLUN) YD%VMAX2
READ (KLUN) YD%RMAX_D3
READ (KLUN) YD%LBOUND_D3
READ (KLUN) LRKRF
IF (LRKRF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RKRF (IL1(1):IU1(1)))
  READ (KLUN) YD%RKRF
ENDIF
READ (KLUN) YD%NMAXLEVRF
READ (KLUN) YD%RRFZ1
READ (KLUN) YD%RRFPLM
READ (KLUN) YD%RRFTAU
READ (KLUN) YD%RTEMRB
READ (KLUN) YD%NRUBC
READ (KLUN) YD%LSIDG
READ (KLUN) YD%LDYN_STABAN
READ (KLUN) YD%BETADT
READ (KLUN) YD%RBT
READ (KLUN) YD%RBTS2
READ (KLUN) YD%REFGEO
READ (KLUN) YD%SIPR
READ (KLUN) YD%SITR
READ (KLUN) YD%SITRA
READ (KLUN) YD%SITRUB
READ (KLUN) YD%SIPRUB
READ (KLUN) YD%SITIME
READ (KLUN) YD%SIRPRG
READ (KLUN) YD%SIRPRN
READ (KLUN) YD%SIRSLP
READ (KLUN) YD%RSLOPE_MAX
READ (KLUN) YD%NSITER
READ (KLUN) YD%NCURRENT_ITER
READ (KLUN) YD%LRHDI_LASTITERPC
READ (KLUN) YD%NITERHELM
READ (KLUN) YD%NOPT_SITRA
READ (KLUN) LSIALPH
IF (LSIALPH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIALPH (IL1(1):IU1(1)))
  READ (KLUN) YD%SIALPH
ENDIF
READ (KLUN) LSILNPR
IF (LSILNPR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SILNPR (IL1(1):IU1(1)))
  READ (KLUN) YD%SILNPR
ENDIF
READ (KLUN) LSIDELP
IF (LSIDELP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDELP (IL1(1):IU1(1)))
  READ (KLUN) YD%SIDELP
ENDIF
READ (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIRDEL (IL1(1):IU1(1)))
  READ (KLUN) YD%SIRDEL
ENDIF
READ (KLUN) LSITLAH
IF (LSITLAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAH (IL1(1):IU1(1)))
  READ (KLUN) YD%SITLAH
ENDIF
READ (KLUN) LSITLAF
IF (LSITLAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAF (IL1(1):IU1(1)))
  READ (KLUN) YD%SITLAF
ENDIF
READ (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDPHI (IL1(1):IU1(1)))
  READ (KLUN) YD%SIDPHI
ENDIF
READ (KLUN) LSIWEIG
IF (LSIWEIG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIWEIG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIWEIG
ENDIF
READ (KLUN) LSIB
IF (LSIB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIB (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIB
ENDIF
READ (KLUN) LSIMO
IF (LSIMO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIMO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIMO
ENDIF
READ (KLUN) LSIMI
IF (LSIMI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIMI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIMI
ENDIF
READ (KLUN) LSIVP
IF (LSIVP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIVP (IL1(1):IU1(1)))
  READ (KLUN) YD%SIVP
ENDIF
READ (KLUN) LSIHEG
IF (LSIHEG) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEG (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEG
ENDIF
READ (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEG2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEG2
ENDIF
READ (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEGB (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEGB
ENDIF
READ (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEGB2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEGB2
ENDIF
READ (KLUN) LSIFAC
IF (LSIFAC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIFAC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIFAC
ENDIF
READ (KLUN) LSIFACI
IF (LSIFACI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIFACI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIFACI
ENDIF
READ (KLUN) LSI_ILAPKSSI
IF (LSI_ILAPKSSI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SI_ILAPKSSI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SI_ILAPKSSI
ENDIF
READ (KLUN) LSITRAM
IF (LSITRAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITRAM (IL1(1):IU1(1)))
  READ (KLUN) YD%SITRAM
ENDIF
READ (KLUN) YD%VNORM
READ (KLUN) YD%NVLAG
READ (KLUN) YD%NWLAG
READ (KLUN) YD%NTLAG
READ (KLUN) YD%NSPDLAG
READ (KLUN) YD%NSVDLAG
READ (KLUN) YD%NSPLTHOI
READ (KLUN) YD%LSPLTHOIGFL
READ (KLUN) YD%NSLDIMK
READ (KLUN) YD%NITMP
READ (KLUN) YD%VETAON
READ (KLUN) YD%VETAOX
READ (KLUN) YD%LSETTLSVF
READ (KLUN) YD%LSETFSTAT
READ (KLUN) YD%RW2TLFF
READ (KLUN) YD%RALPHA
READ (KLUN) YD%RALPHA_TOP
READ (KLUN) YD%NLEV_ZALPHA
READ (KLUN) YD%NEDER
READ (KLUN) YD%LWENOBC
READ (KLUN) YD%LSLDP_RK
READ (KLUN) YD%LSLDP_CURV
READ (KLUN) YD%VESL
READ (KLUN) YD%XIDT
READ (KLUN) YD%LQMW
READ (KLUN) YD%LQMHW
READ (KLUN) YD%LQMT
READ (KLUN) YD%LQMHT
READ (KLUN) YD%LQMP
READ (KLUN) YD%LQMHP
READ (KLUN) YD%LQMPD
READ (KLUN) YD%LQMHPD
READ (KLUN) YD%LQMVD
READ (KLUN) YD%LQMHVD
READ (KLUN) YD%LVWENO_W
READ (KLUN) YD%LVWENO_T
READ (KLUN) YD%LVWENO_SP
READ (KLUN) YD%LVWENO_SPD
READ (KLUN) YD%LVWENO_SVD
READ (KLUN) YD%WENO_ALPHA_W
READ (KLUN) YD%WENO_ALPHA_T
READ (KLUN) YD%WENO_ALPHA_SP
READ (KLUN) YD%WENO_ALPHA_SPD
READ (KLUN) YD%WENO_ALPHA_SVD
READ (KLUN) YD%LADVF
READ (KLUN) YD%LIMPF
READ (KLUN) YD%L2TLFF
READ (KLUN) YD%RCMSLP0
READ (KLUN) YD%NCOMP_CVGQ
READ (KLUN) YD%LSVTSM
READ (KLUN) YD%RPRES_SVTSM
READ (KLUN) YD%RPRES_SETTLSVF
READ (KLUN) YD%NFLEVSF
READ (KLUN) YD%RSCALE
READ (KLUN) YD%RSCALEOFF
READ (KLUN) YD%LHDIFFM
READ (KLUN) YD%LSPECVIS
READ (KLUN) YD%NDIFFACT
READ (KLUN) YD%LGPSTRESS
READ (KLUN) YD%RCLSTRESS
READ (KLUN) YD%RCLPOLE
READ (KLUN) YD%NVSEPC
READ (KLUN) YD%NVSEPL
READ (KLUN) YD%LFINDVSEP
READ (KLUN) YD%LMASCOR
READ (KLUN) YD%LMASDRY
READ (KLUN) YD%LGPMASCOR
READ (KLUN) YD%NGPMASCOR
READ (KLUN) YD%GPMASSI
READ (KLUN) YD%GMASSI
READ (KLUN) YD%GMASS0
READ (KLUN) YD%GMASSINC
READ (KLUN) YD%LNODRYFLX
READ (KLUN) LSIBI
IF (LSIBI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIBI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIBI
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TDYN (YD, LDCREATED)

IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRKRF, LSIALPH, LSIB, LSIBI, LSIDELP
LOGICAL :: LSIDPHI, LSIFAC, LSIFACI, LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSIMI, LSIMO
LOGICAL :: LSIRDEL, LSITLAF, LSITLAH, LSITRAM, LSIVP, LSIWEIG, LSI_ILAPKSSI, LSLHDA, LSLHDD0, LSLHD_MASK_T
LOGICAL :: LSLHD_MASK_U

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF













































LRDIVOR = ALLOCATED (YD%RDIVOR)
IF (LRDIVOR) THEN
  !$acc enter data create (YD%RDIVOR)
  !$acc update device (YD%RDIVOR)
  !$acc enter data attach (YD%RDIVOR)
ENDIF

LRDIDIV = ALLOCATED (YD%RDIDIV)
IF (LRDIDIV) THEN
  !$acc enter data create (YD%RDIDIV)
  !$acc update device (YD%RDIDIV)
  !$acc enter data attach (YD%RDIDIV)
ENDIF

LRDITG = ALLOCATED (YD%RDITG)
IF (LRDITG) THEN
  !$acc enter data create (YD%RDITG)
  !$acc update device (YD%RDITG)
  !$acc enter data attach (YD%RDITG)
ENDIF

LRDIGFL = ALLOCATED (YD%RDIGFL)
IF (LRDIGFL) THEN
  !$acc enter data create (YD%RDIGFL)
  !$acc update device (YD%RDIGFL)
  !$acc enter data attach (YD%RDIGFL)
ENDIF

LRDIPD = ALLOCATED (YD%RDIPD)
IF (LRDIPD) THEN
  !$acc enter data create (YD%RDIPD)
  !$acc update device (YD%RDIPD)
  !$acc enter data attach (YD%RDIPD)
ENDIF

LRDIVD = ALLOCATED (YD%RDIVD)
IF (LRDIVD) THEN
  !$acc enter data create (YD%RDIVD)
  !$acc update device (YD%RDIVD)
  !$acc enter data attach (YD%RDIVD)
ENDIF

LRDISP = ALLOCATED (YD%RDISP)
IF (LRDISP) THEN
  !$acc enter data create (YD%RDISP)
  !$acc update device (YD%RDISP)
  !$acc enter data attach (YD%RDISP)
ENDIF

LRDHI = ALLOCATED (YD%RDHI)
IF (LRDHI) THEN
  !$acc enter data create (YD%RDHI)
  !$acc update device (YD%RDHI)
  !$acc enter data attach (YD%RDHI)
ENDIF






LSLHDA = ALLOCATED (YD%SLHDA)
IF (LSLHDA) THEN
  !$acc enter data create (YD%SLHDA)
  !$acc update device (YD%SLHDA)
  !$acc enter data attach (YD%SLHDA)
ENDIF





LSLHDD0 = ALLOCATED (YD%SLHDD0)
IF (LSLHDD0) THEN
  !$acc enter data create (YD%SLHDD0)
  !$acc update device (YD%SLHDD0)
  !$acc enter data attach (YD%SLHDD0)
ENDIF























LRDSVOR = ALLOCATED (YD%RDSVOR)
IF (LRDSVOR) THEN
  !$acc enter data create (YD%RDSVOR)
  !$acc update device (YD%RDSVOR)
  !$acc enter data attach (YD%RDSVOR)
ENDIF

LRDSDIV = ALLOCATED (YD%RDSDIV)
IF (LRDSDIV) THEN
  !$acc enter data create (YD%RDSDIV)
  !$acc update device (YD%RDSDIV)
  !$acc enter data attach (YD%RDSDIV)
ENDIF

LRDSVD = ALLOCATED (YD%RDSVD)
IF (LRDSVD) THEN
  !$acc enter data create (YD%RDSVD)
  !$acc update device (YD%RDSVD)
  !$acc enter data attach (YD%RDSVD)
ENDIF

LRDHS = ALLOCATED (YD%RDHS)
IF (LRDHS) THEN
  !$acc enter data create (YD%RDHS)
  !$acc update device (YD%RDHS)
  !$acc enter data attach (YD%RDHS)
ENDIF

LSLHD_MASK_U = ALLOCATED (YD%SLHD_MASK_U)
IF (LSLHD_MASK_U) THEN
  !$acc enter data create (YD%SLHD_MASK_U)
  !$acc update device (YD%SLHD_MASK_U)
  !$acc enter data attach (YD%SLHD_MASK_U)
ENDIF

LSLHD_MASK_T = ALLOCATED (YD%SLHD_MASK_T)
IF (LSLHD_MASK_T) THEN
  !$acc enter data create (YD%SLHD_MASK_T)
  !$acc update device (YD%SLHD_MASK_T)
  !$acc enter data attach (YD%SLHD_MASK_T)
ENDIF




LRCORDIT = ALLOCATED (YD%RCORDIT)
IF (LRCORDIT) THEN
  !$acc enter data create (YD%RCORDIT)
  !$acc update device (YD%RCORDIT)
  !$acc enter data attach (YD%RCORDIT)
ENDIF

LRCORDIH = ALLOCATED (YD%RCORDIH)
IF (LRCORDIH) THEN
  !$acc enter data create (YD%RCORDIH)
  !$acc update device (YD%RCORDIH)
  !$acc enter data attach (YD%RCORDIH)
ENDIF

LRCORDIF = ALLOCATED (YD%RCORDIF)
IF (LRCORDIF) THEN
  !$acc enter data create (YD%RCORDIF)
  !$acc update device (YD%RCORDIF)
  !$acc enter data attach (YD%RCORDIF)
ENDIF





LRKRF = ALLOCATED (YD%RKRF)
IF (LRKRF) THEN
  !$acc enter data create (YD%RKRF)
  !$acc update device (YD%RKRF)
  !$acc enter data attach (YD%RKRF)
ENDIF




























LSIALPH = ALLOCATED (YD%SIALPH)
IF (LSIALPH) THEN
  !$acc enter data create (YD%SIALPH)
  !$acc update device (YD%SIALPH)
  !$acc enter data attach (YD%SIALPH)
ENDIF

LSILNPR = ALLOCATED (YD%SILNPR)
IF (LSILNPR) THEN
  !$acc enter data create (YD%SILNPR)
  !$acc update device (YD%SILNPR)
  !$acc enter data attach (YD%SILNPR)
ENDIF

LSIDELP = ALLOCATED (YD%SIDELP)
IF (LSIDELP) THEN
  !$acc enter data create (YD%SIDELP)
  !$acc update device (YD%SIDELP)
  !$acc enter data attach (YD%SIDELP)
ENDIF

LSIRDEL = ALLOCATED (YD%SIRDEL)
IF (LSIRDEL) THEN
  !$acc enter data create (YD%SIRDEL)
  !$acc update device (YD%SIRDEL)
  !$acc enter data attach (YD%SIRDEL)
ENDIF

LSITLAH = ALLOCATED (YD%SITLAH)
IF (LSITLAH) THEN
  !$acc enter data create (YD%SITLAH)
  !$acc update device (YD%SITLAH)
  !$acc enter data attach (YD%SITLAH)
ENDIF

LSITLAF = ALLOCATED (YD%SITLAF)
IF (LSITLAF) THEN
  !$acc enter data create (YD%SITLAF)
  !$acc update device (YD%SITLAF)
  !$acc enter data attach (YD%SITLAF)
ENDIF

LSIDPHI = ALLOCATED (YD%SIDPHI)
IF (LSIDPHI) THEN
  !$acc enter data create (YD%SIDPHI)
  !$acc update device (YD%SIDPHI)
  !$acc enter data attach (YD%SIDPHI)
ENDIF

LSIWEIG = ALLOCATED (YD%SIWEIG)
IF (LSIWEIG) THEN
  !$acc enter data create (YD%SIWEIG)
  !$acc update device (YD%SIWEIG)
  !$acc enter data attach (YD%SIWEIG)
ENDIF

LSIB = ALLOCATED (YD%SIB)
IF (LSIB) THEN
  !$acc enter data create (YD%SIB)
  !$acc update device (YD%SIB)
  !$acc enter data attach (YD%SIB)
ENDIF

LSIMO = ALLOCATED (YD%SIMO)
IF (LSIMO) THEN
  !$acc enter data create (YD%SIMO)
  !$acc update device (YD%SIMO)
  !$acc enter data attach (YD%SIMO)
ENDIF

LSIMI = ALLOCATED (YD%SIMI)
IF (LSIMI) THEN
  !$acc enter data create (YD%SIMI)
  !$acc update device (YD%SIMI)
  !$acc enter data attach (YD%SIMI)
ENDIF

LSIVP = ALLOCATED (YD%SIVP)
IF (LSIVP) THEN
  !$acc enter data create (YD%SIVP)
  !$acc update device (YD%SIVP)
  !$acc enter data attach (YD%SIVP)
ENDIF

LSIHEG = ALLOCATED (YD%SIHEG)
IF (LSIHEG) THEN
  !$acc enter data create (YD%SIHEG)
  !$acc update device (YD%SIHEG)
  !$acc enter data attach (YD%SIHEG)
ENDIF

LSIHEG2 = ALLOCATED (YD%SIHEG2)
IF (LSIHEG2) THEN
  !$acc enter data create (YD%SIHEG2)
  !$acc update device (YD%SIHEG2)
  !$acc enter data attach (YD%SIHEG2)
ENDIF

LSIHEGB = ALLOCATED (YD%SIHEGB)
IF (LSIHEGB) THEN
  !$acc enter data create (YD%SIHEGB)
  !$acc update device (YD%SIHEGB)
  !$acc enter data attach (YD%SIHEGB)
ENDIF

LSIHEGB2 = ALLOCATED (YD%SIHEGB2)
IF (LSIHEGB2) THEN
  !$acc enter data create (YD%SIHEGB2)
  !$acc update device (YD%SIHEGB2)
  !$acc enter data attach (YD%SIHEGB2)
ENDIF

LSIFAC = ALLOCATED (YD%SIFAC)
IF (LSIFAC) THEN
  !$acc enter data create (YD%SIFAC)
  !$acc update device (YD%SIFAC)
  !$acc enter data attach (YD%SIFAC)
ENDIF

LSIFACI = ALLOCATED (YD%SIFACI)
IF (LSIFACI) THEN
  !$acc enter data create (YD%SIFACI)
  !$acc update device (YD%SIFACI)
  !$acc enter data attach (YD%SIFACI)
ENDIF

LSI_ILAPKSSI = ALLOCATED (YD%SI_ILAPKSSI)
IF (LSI_ILAPKSSI) THEN
  !$acc enter data create (YD%SI_ILAPKSSI)
  !$acc update device (YD%SI_ILAPKSSI)
  !$acc enter data attach (YD%SI_ILAPKSSI)
ENDIF

LSITRAM = ALLOCATED (YD%SITRAM)
IF (LSITRAM) THEN
  !$acc enter data create (YD%SITRAM)
  !$acc update device (YD%SITRAM)
  !$acc enter data attach (YD%SITRAM)
ENDIF










































































LSIBI = ALLOCATED (YD%SIBI)
IF (LSIBI) THEN
  !$acc enter data create (YD%SIBI)
  !$acc update device (YD%SIBI)
  !$acc enter data attach (YD%SIBI)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TDYN (YD, LDDELETED)

IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRKRF, LSIALPH, LSIB, LSIBI, LSIDELP
LOGICAL :: LSIDPHI, LSIFAC, LSIFACI, LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSIMI, LSIMO
LOGICAL :: LSIRDEL, LSITLAF, LSITLAH, LSITRAM, LSIVP, LSIWEIG, LSI_ILAPKSSI, LSLHDA, LSLHDD0, LSLHD_MASK_T
LOGICAL :: LSLHD_MASK_U














































LRDIVOR = ALLOCATED (YD%RDIVOR)
IF (LRDIVOR) THEN
  !$acc exit data detach (YD%RDIVOR)
  !$acc exit data delete (YD%RDIVOR)
ENDIF

LRDIDIV = ALLOCATED (YD%RDIDIV)
IF (LRDIDIV) THEN
  !$acc exit data detach (YD%RDIDIV)
  !$acc exit data delete (YD%RDIDIV)
ENDIF

LRDITG = ALLOCATED (YD%RDITG)
IF (LRDITG) THEN
  !$acc exit data detach (YD%RDITG)
  !$acc exit data delete (YD%RDITG)
ENDIF

LRDIGFL = ALLOCATED (YD%RDIGFL)
IF (LRDIGFL) THEN
  !$acc exit data detach (YD%RDIGFL)
  !$acc exit data delete (YD%RDIGFL)
ENDIF

LRDIPD = ALLOCATED (YD%RDIPD)
IF (LRDIPD) THEN
  !$acc exit data detach (YD%RDIPD)
  !$acc exit data delete (YD%RDIPD)
ENDIF

LRDIVD = ALLOCATED (YD%RDIVD)
IF (LRDIVD) THEN
  !$acc exit data detach (YD%RDIVD)
  !$acc exit data delete (YD%RDIVD)
ENDIF

LRDISP = ALLOCATED (YD%RDISP)
IF (LRDISP) THEN
  !$acc exit data detach (YD%RDISP)
  !$acc exit data delete (YD%RDISP)
ENDIF

LRDHI = ALLOCATED (YD%RDHI)
IF (LRDHI) THEN
  !$acc exit data detach (YD%RDHI)
  !$acc exit data delete (YD%RDHI)
ENDIF






LSLHDA = ALLOCATED (YD%SLHDA)
IF (LSLHDA) THEN
  !$acc exit data detach (YD%SLHDA)
  !$acc exit data delete (YD%SLHDA)
ENDIF





LSLHDD0 = ALLOCATED (YD%SLHDD0)
IF (LSLHDD0) THEN
  !$acc exit data detach (YD%SLHDD0)
  !$acc exit data delete (YD%SLHDD0)
ENDIF























LRDSVOR = ALLOCATED (YD%RDSVOR)
IF (LRDSVOR) THEN
  !$acc exit data detach (YD%RDSVOR)
  !$acc exit data delete (YD%RDSVOR)
ENDIF

LRDSDIV = ALLOCATED (YD%RDSDIV)
IF (LRDSDIV) THEN
  !$acc exit data detach (YD%RDSDIV)
  !$acc exit data delete (YD%RDSDIV)
ENDIF

LRDSVD = ALLOCATED (YD%RDSVD)
IF (LRDSVD) THEN
  !$acc exit data detach (YD%RDSVD)
  !$acc exit data delete (YD%RDSVD)
ENDIF

LRDHS = ALLOCATED (YD%RDHS)
IF (LRDHS) THEN
  !$acc exit data detach (YD%RDHS)
  !$acc exit data delete (YD%RDHS)
ENDIF

LSLHD_MASK_U = ALLOCATED (YD%SLHD_MASK_U)
IF (LSLHD_MASK_U) THEN
  !$acc exit data detach (YD%SLHD_MASK_U)
  !$acc exit data delete (YD%SLHD_MASK_U)
ENDIF

LSLHD_MASK_T = ALLOCATED (YD%SLHD_MASK_T)
IF (LSLHD_MASK_T) THEN
  !$acc exit data detach (YD%SLHD_MASK_T)
  !$acc exit data delete (YD%SLHD_MASK_T)
ENDIF




LRCORDIT = ALLOCATED (YD%RCORDIT)
IF (LRCORDIT) THEN
  !$acc exit data detach (YD%RCORDIT)
  !$acc exit data delete (YD%RCORDIT)
ENDIF

LRCORDIH = ALLOCATED (YD%RCORDIH)
IF (LRCORDIH) THEN
  !$acc exit data detach (YD%RCORDIH)
  !$acc exit data delete (YD%RCORDIH)
ENDIF

LRCORDIF = ALLOCATED (YD%RCORDIF)
IF (LRCORDIF) THEN
  !$acc exit data detach (YD%RCORDIF)
  !$acc exit data delete (YD%RCORDIF)
ENDIF





LRKRF = ALLOCATED (YD%RKRF)
IF (LRKRF) THEN
  !$acc exit data detach (YD%RKRF)
  !$acc exit data delete (YD%RKRF)
ENDIF




























LSIALPH = ALLOCATED (YD%SIALPH)
IF (LSIALPH) THEN
  !$acc exit data detach (YD%SIALPH)
  !$acc exit data delete (YD%SIALPH)
ENDIF

LSILNPR = ALLOCATED (YD%SILNPR)
IF (LSILNPR) THEN
  !$acc exit data detach (YD%SILNPR)
  !$acc exit data delete (YD%SILNPR)
ENDIF

LSIDELP = ALLOCATED (YD%SIDELP)
IF (LSIDELP) THEN
  !$acc exit data detach (YD%SIDELP)
  !$acc exit data delete (YD%SIDELP)
ENDIF

LSIRDEL = ALLOCATED (YD%SIRDEL)
IF (LSIRDEL) THEN
  !$acc exit data detach (YD%SIRDEL)
  !$acc exit data delete (YD%SIRDEL)
ENDIF

LSITLAH = ALLOCATED (YD%SITLAH)
IF (LSITLAH) THEN
  !$acc exit data detach (YD%SITLAH)
  !$acc exit data delete (YD%SITLAH)
ENDIF

LSITLAF = ALLOCATED (YD%SITLAF)
IF (LSITLAF) THEN
  !$acc exit data detach (YD%SITLAF)
  !$acc exit data delete (YD%SITLAF)
ENDIF

LSIDPHI = ALLOCATED (YD%SIDPHI)
IF (LSIDPHI) THEN
  !$acc exit data detach (YD%SIDPHI)
  !$acc exit data delete (YD%SIDPHI)
ENDIF

LSIWEIG = ALLOCATED (YD%SIWEIG)
IF (LSIWEIG) THEN
  !$acc exit data detach (YD%SIWEIG)
  !$acc exit data delete (YD%SIWEIG)
ENDIF

LSIB = ALLOCATED (YD%SIB)
IF (LSIB) THEN
  !$acc exit data detach (YD%SIB)
  !$acc exit data delete (YD%SIB)
ENDIF

LSIMO = ALLOCATED (YD%SIMO)
IF (LSIMO) THEN
  !$acc exit data detach (YD%SIMO)
  !$acc exit data delete (YD%SIMO)
ENDIF

LSIMI = ALLOCATED (YD%SIMI)
IF (LSIMI) THEN
  !$acc exit data detach (YD%SIMI)
  !$acc exit data delete (YD%SIMI)
ENDIF

LSIVP = ALLOCATED (YD%SIVP)
IF (LSIVP) THEN
  !$acc exit data detach (YD%SIVP)
  !$acc exit data delete (YD%SIVP)
ENDIF

LSIHEG = ALLOCATED (YD%SIHEG)
IF (LSIHEG) THEN
  !$acc exit data detach (YD%SIHEG)
  !$acc exit data delete (YD%SIHEG)
ENDIF

LSIHEG2 = ALLOCATED (YD%SIHEG2)
IF (LSIHEG2) THEN
  !$acc exit data detach (YD%SIHEG2)
  !$acc exit data delete (YD%SIHEG2)
ENDIF

LSIHEGB = ALLOCATED (YD%SIHEGB)
IF (LSIHEGB) THEN
  !$acc exit data detach (YD%SIHEGB)
  !$acc exit data delete (YD%SIHEGB)
ENDIF

LSIHEGB2 = ALLOCATED (YD%SIHEGB2)
IF (LSIHEGB2) THEN
  !$acc exit data detach (YD%SIHEGB2)
  !$acc exit data delete (YD%SIHEGB2)
ENDIF

LSIFAC = ALLOCATED (YD%SIFAC)
IF (LSIFAC) THEN
  !$acc exit data detach (YD%SIFAC)
  !$acc exit data delete (YD%SIFAC)
ENDIF

LSIFACI = ALLOCATED (YD%SIFACI)
IF (LSIFACI) THEN
  !$acc exit data detach (YD%SIFACI)
  !$acc exit data delete (YD%SIFACI)
ENDIF

LSI_ILAPKSSI = ALLOCATED (YD%SI_ILAPKSSI)
IF (LSI_ILAPKSSI) THEN
  !$acc exit data detach (YD%SI_ILAPKSSI)
  !$acc exit data delete (YD%SI_ILAPKSSI)
ENDIF

LSITRAM = ALLOCATED (YD%SITRAM)
IF (LSITRAM) THEN
  !$acc exit data detach (YD%SITRAM)
  !$acc exit data delete (YD%SITRAM)
ENDIF










































































LSIBI = ALLOCATED (YD%SIBI)
IF (LSIBI) THEN
  !$acc exit data detach (YD%SIBI)
  !$acc exit data delete (YD%SIBI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
