MODULE UTIL_MF_PHYS_SURF_TYPE_MOD

USE MF_PHYS_SURFACE_TYPE_MOD, ONLY : MF_PHYS_SURF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MF_PHYS_SURF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MF_PHYS_SURF_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MF_PHYS_SURF_TYPE (KLUN, YD)
USE UTIL_SURFACE_VIEW_GROUP_CLS_MOD
USE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD
USE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MF_PHYS_SURF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%GSP_SG)
CALL SAVE (KLUN, YD%GSP_RR)
CALL SAVE (KLUN, YD%GSP_CL)
CALL SAVE (KLUN, YD%GSD_XP)
CALL SAVE (KLUN, YD%GSD_XP2)
END SUBROUTINE

SUBROUTINE LOAD_MF_PHYS_SURF_TYPE (KLUN, YD)
USE UTIL_SURFACE_VIEW_GROUP_CLS_MOD
USE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD
USE UTIL_SURFACE_VIEW_GROUP_SNOWG_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP2_MOD
USE UTIL_SURFACE_VIEW_GROUP_VPRECIP_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MF_PHYS_SURF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%GSP_SG)
CALL LOAD (KLUN, YD%GSP_RR)
CALL LOAD (KLUN, YD%GSP_CL)
CALL LOAD (KLUN, YD%GSD_XP)
CALL LOAD (KLUN, YD%GSD_XP2)
END SUBROUTINE






END MODULE
