MODULE UTIL_TEGWDWMS_MOD

USE YOEGWDWMS, ONLY : TEGWDWMS


INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGWDWMS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGWDWMS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEGWDWMS
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEGWDWMS
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEGWDWMS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGWDWMS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LREGWWMS
END SUBROUTINE

SUBROUTINE LOAD_TEGWDWMS (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGWDWMS), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LREGWWMS
END SUBROUTINE


SUBROUTINE COPY_TEGWDWMS (YD, LDCREATED)
IMPLICIT NONE
TYPE (TEGWDWMS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TEGWDWMS (YD, LDDELETED)
IMPLICIT NONE
TYPE (TEGWDWMS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED


LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
