MODULE UTIL_CPLNG_FLD_TYPE_MOD

USE CPLNG_TYPES_MOD, ONLY : CPLNG_FLD_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPLNG_FLD_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_CPLNG_FLD_TYPE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LD, LID
LID = ALLOCATED (YD%ID)
WRITE (KLUN) LID
IF (LID) THEN
  WRITE (KLUN) LBOUND (YD%ID)
  WRITE (KLUN) UBOUND (YD%ID)
  WRITE (KLUN) YD%ID
ENDIF
WRITE (KLUN) YD%NAME
WRITE (KLUN) YD%TYPE
WRITE (KLUN) YD%INOUT
WRITE (KLUN) YD%STAGE
WRITE (KLUN) YD%NUM_LVL
WRITE (KLUN) YD%NUM_CAT
LD = ALLOCATED (YD%D)
WRITE (KLUN) LD
IF (LD) THEN
  WRITE (KLUN) LBOUND (YD%D)
  WRITE (KLUN) UBOUND (YD%D)
  WRITE (KLUN) YD%D
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPLNG_FLD_TYPE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPLNG_FLD_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LD, LID
READ (KLUN) LID
IF (LID) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%ID (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%ID
ENDIF
READ (KLUN) YD%NAME
READ (KLUN) YD%TYPE
READ (KLUN) YD%INOUT
READ (KLUN) YD%STAGE
READ (KLUN) YD%NUM_LVL
READ (KLUN) YD%NUM_CAT
READ (KLUN) LD
IF (LD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%D
ENDIF
END SUBROUTINE


SUBROUTINE COPY_CPLNG_FLD_TYPE (YD, LDCREATED)

IMPLICIT NONE
TYPE (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LD, LID

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LID = ALLOCATED (YD%ID)
IF (LID) THEN
  !$acc enter data create (YD%ID)
  !$acc update device (YD%ID)
  !$acc enter data attach (YD%ID)
ENDIF







LD = ALLOCATED (YD%D)
IF (LD) THEN
  !$acc enter data create (YD%D)
  !$acc update device (YD%D)
  !$acc enter data attach (YD%D)
ENDIF

END SUBROUTINE



END MODULE
