MODULE UTIL_TDIMV_MOD

USE YOMDIMV, ONLY : TDIMV

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDIMV
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIMV
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TDIMV (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIMV), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NFLEVG
WRITE (KLUN) YD%NFLEVL
WRITE (KLUN) YD%NFLEVLMX
WRITE (KLUN) YD%NFLSUR
WRITE (KLUN) YD%NFLSUL
WRITE (KLUN) YD%NFLSA
WRITE (KLUN) YD%NFLEN
WRITE (KLUN) YD%NIOLEVG
END SUBROUTINE

SUBROUTINE LOAD_TDIMV (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIMV), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NFLEVG
READ (KLUN) YD%NFLEVL
READ (KLUN) YD%NFLEVLMX
READ (KLUN) YD%NFLSUR
READ (KLUN) YD%NFLSUL
READ (KLUN) YD%NFLSA
READ (KLUN) YD%NFLEN
READ (KLUN) YD%NIOLEVG
END SUBROUTINE






END MODULE
