MODULE UTIL_MODEL_ATMOS_OCEAN_COUPLING_TYPE_MOD

USE MODEL_ATMOS_OCEAN_COUPLING_MOD, ONLY : MODEL_ATMOS_OCEAN_COUPLING_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_ATMOS_OCEAN_COUPLING_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_ATMOS_OCEAN_COUPLING_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_MODEL_ATMOS_OCEAN_COUPLING_TYPE (KLUN, YD)
USE UTIL_TCOM_MOD
USE UTIL_TCOU_MOD
USE UTIL_TMCC_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRMCC)
CALL SAVE (KLUN, YD%YRCOM)
CALL SAVE (KLUN, YD%YRCOU)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_ATMOS_OCEAN_COUPLING_TYPE (KLUN, YD)
USE UTIL_TCOM_MOD
USE UTIL_TCOU_MOD
USE UTIL_TMCC_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRMCC)
CALL LOAD (KLUN, YD%YRCOM)
CALL LOAD (KLUN, YD%YRCOU)
END SUBROUTINE






END MODULE
