MODULE UTIL_TPTRSLB1_MOD

USE PTRSLB1, ONLY : TPTRSLB1

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPTRSLB1
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPTRSLB1
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TPTRSLB1 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPTRSLB1), INTENT (IN), TARGET :: YD
LOGICAL :: LRPARSL1
WRITE (KLUN) YD%NFLDSLB1
LRPARSL1 = ALLOCATED (YD%RPARSL1)
WRITE (KLUN) LRPARSL1
IF (LRPARSL1) THEN
  WRITE (KLUN) LBOUND (YD%RPARSL1)
  WRITE (KLUN) UBOUND (YD%RPARSL1)
  WRITE (KLUN) YD%RPARSL1
ENDIF
WRITE (KLUN) YD%MSLBUF1
WRITE (KLUN) YD%MSLB1U9
WRITE (KLUN) YD%MSLB1V9
WRITE (KLUN) YD%MSLB1T9
WRITE (KLUN) YD%MSLB1GFL9
WRITE (KLUN) YD%MSLB1GFLSP9
WRITE (KLUN) YD%MSLB1PD9
WRITE (KLUN) YD%MSLB1VD9
WRITE (KLUN) YD%MSLB1NHX9
WRITE (KLUN) YD%MSLB1UR0
WRITE (KLUN) YD%MSLB1VR0
WRITE (KLUN) YD%MSLB1ZR0
WRITE (KLUN) YD%MSLB1WR0
WRITE (KLUN) YD%MSLB1UR00
WRITE (KLUN) YD%MSLB1VR00
WRITE (KLUN) YD%MSLB1ZR00
WRITE (KLUN) YD%MSLB1WR00
WRITE (KLUN) YD%MSLB1WRA
WRITE (KLUN) YD%MSLB1UR9
WRITE (KLUN) YD%MSLB1VR9
WRITE (KLUN) YD%MSLB1DBBC9
WRITE (KLUN) YD%MSLB1DPHI9
WRITE (KLUN) YD%MSLB1GWS9
WRITE (KLUN) YD%MSLB1U0
WRITE (KLUN) YD%MSLB1V0
WRITE (KLUN) YD%MSLB1T0
WRITE (KLUN) YD%MSLB1PD0
WRITE (KLUN) YD%MSLB1VD0
WRITE (KLUN) YD%MSLB1C9
WRITE (KLUN) YD%MSLB1SP9
WRITE (KLUN) YD%MSLB1SP0
WRITE (KLUN) YD%MSLB1C0
WRITE (KLUN) YD%MSLB1UP9
WRITE (KLUN) YD%MSLB1VP9
WRITE (KLUN) YD%MSLB1TP9
WRITE (KLUN) YD%MSLB1GFLP9
WRITE (KLUN) YD%MSLB1U9_SI
WRITE (KLUN) YD%MSLB1V9_SI
WRITE (KLUN) YD%MSLB1T9_SI
WRITE (KLUN) YD%MSLB1PD9_SI
WRITE (KLUN) YD%MSLB1VD9_SI
WRITE (KLUN) YD%MSLB1C9_SI
WRITE (KLUN) YD%MSLB1UF9
WRITE (KLUN) YD%MSLB1VF9
WRITE (KLUN) YD%MSLB1TF9
WRITE (KLUN) YD%MSLB1GFLF9
WRITE (KLUN) YD%MSLB1VDF9
WRITE (KLUN) YD%MSLB1GFLSPF9
WRITE (KLUN) YD%MSLB1U9_NL
WRITE (KLUN) YD%MSLB1V9_NL
WRITE (KLUN) YD%MSLB1T9_NL
WRITE (KLUN) YD%MSLB1PD9_NL
WRITE (KLUN) YD%MSLB1VD9_NL
WRITE (KLUN) YD%MSLB1C9_NL
END SUBROUTINE

SUBROUTINE LOAD_TPTRSLB1 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPTRSLB1), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRPARSL1
READ (KLUN) YD%NFLDSLB1
READ (KLUN) LRPARSL1
IF (LRPARSL1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RPARSL1 (IL1(1):IU1(1)))
  READ (KLUN) YD%RPARSL1
ENDIF
READ (KLUN) YD%MSLBUF1
READ (KLUN) YD%MSLB1U9
READ (KLUN) YD%MSLB1V9
READ (KLUN) YD%MSLB1T9
READ (KLUN) YD%MSLB1GFL9
READ (KLUN) YD%MSLB1GFLSP9
READ (KLUN) YD%MSLB1PD9
READ (KLUN) YD%MSLB1VD9
READ (KLUN) YD%MSLB1NHX9
READ (KLUN) YD%MSLB1UR0
READ (KLUN) YD%MSLB1VR0
READ (KLUN) YD%MSLB1ZR0
READ (KLUN) YD%MSLB1WR0
READ (KLUN) YD%MSLB1UR00
READ (KLUN) YD%MSLB1VR00
READ (KLUN) YD%MSLB1ZR00
READ (KLUN) YD%MSLB1WR00
READ (KLUN) YD%MSLB1WRA
READ (KLUN) YD%MSLB1UR9
READ (KLUN) YD%MSLB1VR9
READ (KLUN) YD%MSLB1DBBC9
READ (KLUN) YD%MSLB1DPHI9
READ (KLUN) YD%MSLB1GWS9
READ (KLUN) YD%MSLB1U0
READ (KLUN) YD%MSLB1V0
READ (KLUN) YD%MSLB1T0
READ (KLUN) YD%MSLB1PD0
READ (KLUN) YD%MSLB1VD0
READ (KLUN) YD%MSLB1C9
READ (KLUN) YD%MSLB1SP9
READ (KLUN) YD%MSLB1SP0
READ (KLUN) YD%MSLB1C0
READ (KLUN) YD%MSLB1UP9
READ (KLUN) YD%MSLB1VP9
READ (KLUN) YD%MSLB1TP9
READ (KLUN) YD%MSLB1GFLP9
READ (KLUN) YD%MSLB1U9_SI
READ (KLUN) YD%MSLB1V9_SI
READ (KLUN) YD%MSLB1T9_SI
READ (KLUN) YD%MSLB1PD9_SI
READ (KLUN) YD%MSLB1VD9_SI
READ (KLUN) YD%MSLB1C9_SI
READ (KLUN) YD%MSLB1UF9
READ (KLUN) YD%MSLB1VF9
READ (KLUN) YD%MSLB1TF9
READ (KLUN) YD%MSLB1GFLF9
READ (KLUN) YD%MSLB1VDF9
READ (KLUN) YD%MSLB1GFLSPF9
READ (KLUN) YD%MSLB1U9_NL
READ (KLUN) YD%MSLB1V9_NL
READ (KLUN) YD%MSLB1T9_NL
READ (KLUN) YD%MSLB1PD9_NL
READ (KLUN) YD%MSLB1VD9_NL
READ (KLUN) YD%MSLB1C9_NL
END SUBROUTINE






END MODULE
