MODULE UTIL_MODEL_ATMOS_OCEAN_COUPLING_TYPE_MOD

USE MODEL_ATMOS_OCEAN_COUPLING_MOD, ONLY : MODEL_ATMOS_OCEAN_COUPLING_TYPE
USE UTIL_TCOM_MOD
USE UTIL_TCOU_MOD
USE UTIL_TMCC_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_ATMOS_OCEAN_COUPLING_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_ATMOS_OCEAN_COUPLING_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_ATMOS_OCEAN_COUPLING_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_ATMOS_OCEAN_COUPLING_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_ATMOS_OCEAN_COUPLING_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRMCC)
CALL SAVE (KLUN, YD%YRCOM)
CALL SAVE (KLUN, YD%YRCOU)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_ATMOS_OCEAN_COUPLING_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRMCC)
CALL LOAD (KLUN, YD%YRCOM)
CALL LOAD (KLUN, YD%YRCOU)
END SUBROUTINE


SUBROUTINE COPY_MODEL_ATMOS_OCEAN_COUPLING_TYPE (YD, LDCREATED)
IMPLICIT NONE
TYPE (MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRMCC, LDCREATED=.TRUE.)

CALL COPY (YD%YRCOM, LDCREATED=.TRUE.)

CALL COPY (YD%YRCOU, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_ATMOS_OCEAN_COUPLING_TYPE (YD, LDDELETED)
IMPLICIT NONE
TYPE (MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRMCC, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCOM, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCOU, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
