MODULE UTIL_TPTRSLB15_MOD

USE PTRSLB15, ONLY : TPTRSLB15

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPTRSLB15
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPTRSLB15
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TPTRSLB15 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPTRSLB15), INTENT (IN), TARGET :: YD
LOGICAL :: LRPARSL15
WRITE (KLUN) YD%NFLDSLB15
LRPARSL15 = ALLOCATED (YD%RPARSL15)
WRITE (KLUN) LRPARSL15
IF (LRPARSL15) THEN
  WRITE (KLUN) LBOUND (YD%RPARSL15)
  WRITE (KLUN) UBOUND (YD%RPARSL15)
  WRITE (KLUN) YD%RPARSL15
ENDIF
WRITE (KLUN) YD%MSLBUF15
WRITE (KLUN) YD%MSLB1UR05
WRITE (KLUN) YD%MSLB1VR05
WRITE (KLUN) YD%MSLB1ZR05
WRITE (KLUN) YD%MSLB1WR05
WRITE (KLUN) YD%MSLB1UR005
WRITE (KLUN) YD%MSLB1VR005
WRITE (KLUN) YD%MSLB1ZR005
WRITE (KLUN) YD%MSLB1WR005
WRITE (KLUN) YD%MSLB1UR95
WRITE (KLUN) YD%MSLB1VR95
WRITE (KLUN) YD%MSLB1U05
WRITE (KLUN) YD%MSLB1V05
WRITE (KLUN) YD%MSLB1T05
WRITE (KLUN) YD%MSLB1C05
WRITE (KLUN) YD%MSLB1SP05
WRITE (KLUN) YD%MSLB1U95
WRITE (KLUN) YD%MSLB1V95
WRITE (KLUN) YD%MSLB1T95
WRITE (KLUN) YD%MSLB1GFL95
WRITE (KLUN) YD%MSLB1C95
WRITE (KLUN) YD%MSLB1SP95
END SUBROUTINE

SUBROUTINE LOAD_TPTRSLB15 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPTRSLB15), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRPARSL15
READ (KLUN) YD%NFLDSLB15
READ (KLUN) LRPARSL15
IF (LRPARSL15) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RPARSL15 (IL1(1):IU1(1)))
  READ (KLUN) YD%RPARSL15
ENDIF
READ (KLUN) YD%MSLBUF15
READ (KLUN) YD%MSLB1UR05
READ (KLUN) YD%MSLB1VR05
READ (KLUN) YD%MSLB1ZR05
READ (KLUN) YD%MSLB1WR05
READ (KLUN) YD%MSLB1UR005
READ (KLUN) YD%MSLB1VR005
READ (KLUN) YD%MSLB1ZR005
READ (KLUN) YD%MSLB1WR005
READ (KLUN) YD%MSLB1UR95
READ (KLUN) YD%MSLB1VR95
READ (KLUN) YD%MSLB1U05
READ (KLUN) YD%MSLB1V05
READ (KLUN) YD%MSLB1T05
READ (KLUN) YD%MSLB1C05
READ (KLUN) YD%MSLB1SP05
READ (KLUN) YD%MSLB1U95
READ (KLUN) YD%MSLB1V95
READ (KLUN) YD%MSLB1T95
READ (KLUN) YD%MSLB1GFL95
READ (KLUN) YD%MSLB1C95
READ (KLUN) YD%MSLB1SP95
END SUBROUTINE






END MODULE
