MODULE UTIL_CPG_RCP_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_RCP_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_RCP_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_RCP_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_CPG_RCP_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_RCP_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_CP, LF_KAP, LF_R
WRITE (KLUN) YD%LOWNED
WRITE (KLUN) YD%IP_CP
LF_CP = ASSOCIATED (YD%F_CP)
WRITE (KLUN) LF_CP
IF (LF_CP) THEN
  CALL SAVE (KLUN, YD%F_CP)
ENDIF
WRITE (KLUN) YD%IP_R
LF_R = ASSOCIATED (YD%F_R)
WRITE (KLUN) LF_R
IF (LF_R) THEN
  CALL SAVE (KLUN, YD%F_R)
ENDIF
WRITE (KLUN) YD%IP_KAP
LF_KAP = ASSOCIATED (YD%F_KAP)
WRITE (KLUN) LF_KAP
IF (LF_KAP) THEN
  CALL SAVE (KLUN, YD%F_KAP)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_RCP_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_RCP_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_CP, LF_KAP, LF_R
READ (KLUN) YD%LOWNED
NULLIFY (YD%ZVIEW)
NULLIFY (YD%ZDATA)
NULLIFY (YD%F_DATA)
READ (KLUN) YD%IP_CP
NULLIFY (YD%CP)
READ (KLUN) LF_CP
IF (LF_CP) THEN
  CALL LOAD (KLUN, YD%F_CP)
ELSE
  NULLIFY (YD%F_CP)
ENDIF
READ (KLUN) YD%IP_R
NULLIFY (YD%R)
READ (KLUN) LF_R
IF (LF_R) THEN
  CALL LOAD (KLUN, YD%F_R)
ELSE
  NULLIFY (YD%F_R)
ENDIF
READ (KLUN) YD%IP_KAP
NULLIFY (YD%KAP)
READ (KLUN) LF_KAP
IF (LF_KAP) THEN
  CALL LOAD (KLUN, YD%F_KAP)
ELSE
  NULLIFY (YD%F_KAP)
ENDIF
END SUBROUTINE






END MODULE
