MODULE UTIL_FLUXES_DESCRIPTOR_MOD

USE TYPE_FLUXES, ONLY : FLUXES_DESCRIPTOR

INTERFACE SAVE
MODULE PROCEDURE SAVE_FLUXES_DESCRIPTOR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_FLUXES_DESCRIPTOR
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_FLUXES_DESCRIPTOR
END INTERFACE



CONTAINS

SUBROUTINE SAVE_FLUXES_DESCRIPTOR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (FLUXES_DESCRIPTOR), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%CLPREF
WRITE (KLUN) YD%CLSUFF
WRITE (KLUN) YD%INUMLEV
WRITE (KLUN) YD%ILEV
WRITE (KLUN) YD%IPARITY
WRITE (KLUN) YD%LACTIVE
WRITE (KLUN) YD%ILEVBOT
WRITE (KLUN) YD%IOFFSET
END SUBROUTINE

SUBROUTINE LOAD_FLUXES_DESCRIPTOR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (FLUXES_DESCRIPTOR), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%CLPREF
READ (KLUN) YD%CLSUFF
READ (KLUN) YD%INUMLEV
READ (KLUN) YD%ILEV
READ (KLUN) YD%IPARITY
READ (KLUN) YD%LACTIVE
READ (KLUN) YD%ILEVBOT
READ (KLUN) YD%IOFFSET
END SUBROUTINE


SUBROUTINE COPY_FLUXES_DESCRIPTOR (YD, LDCREATED)

IMPLICIT NONE
TYPE (FLUXES_DESCRIPTOR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF








END SUBROUTINE



END MODULE
