MODULE UTIL_TPADDH_MOD

USE YOMPADDH, ONLY : TPADDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPADDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPADDH
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TPADDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPADDH), INTENT (IN), TARGET :: YD
LOGICAL :: LNGLALIST, LNGPUMASK
LNGLALIST = ALLOCATED (YD%NGLALIST)
WRITE (KLUN) LNGLALIST
IF (LNGLALIST) THEN
  WRITE (KLUN) LBOUND (YD%NGLALIST)
  WRITE (KLUN) UBOUND (YD%NGLALIST)
  WRITE (KLUN) YD%NGLALIST
ENDIF
LNGPUMASK = ALLOCATED (YD%NGPUMASK)
WRITE (KLUN) LNGPUMASK
IF (LNGPUMASK) THEN
  WRITE (KLUN) LBOUND (YD%NGPUMASK)
  WRITE (KLUN) UBOUND (YD%NGPUMASK)
  WRITE (KLUN) YD%NGPUMASK
ENDIF
END SUBROUTINE
SUBROUTINE LOAD_TPADDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPADDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LNGLALIST, LNGPUMASK
READ (KLUN) LNGLALIST
IF (LNGLALIST) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGLALIST (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGLALIST
ENDIF
READ (KLUN) LNGPUMASK
IF (LNGPUMASK) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGPUMASK (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGPUMASK
ENDIF
END SUBROUTINE




END MODULE
