MODULE UTIL_GEOMETRY_VARIABLES_MOD

USE FIELD_VARIABLES_MOD, ONLY : GEOMETRY_VARIABLES

INTERFACE SAVE
MODULE PROCEDURE SAVE_GEOMETRY_VARIABLES
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_GEOMETRY_VARIABLES
END INTERFACE




CONTAINS

SUBROUTINE SAVE_GEOMETRY_VARIABLES (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY_VARIABLES), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%GM)
END SUBROUTINE
SUBROUTINE LOAD_GEOMETRY_VARIABLES (KLUN, YD)
USE UTIL_VARIABLE_2D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY_VARIABLES), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%GM)
END SUBROUTINE




END MODULE
