MODULE UTIL_TEGWWMS_MOD

USE YOEGWWMS, ONLY : TEGWWMS

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGWWMS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGWWMS
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TEGWWMS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGWWMS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LOZPR
WRITE (KLUN) YD%LGACALC
WRITE (KLUN) YD%LGSATL
WRITE (KLUN) YD%LGINDL
WRITE (KLUN) YD%NLAUNCHL
WRITE (KLUN) YD%NLAUNCHLEV
WRITE (KLUN) YD%NLAUNCH
WRITE (KLUN) YD%NSLOPE
WRITE (KLUN) YD%NGAUSS
WRITE (KLUN) YD%GFLUXLAUNL
WRITE (KLUN) YD%GFLUXLAUN
WRITE (KLUN) YD%GMSTAR_L
WRITE (KLUN) YD%GCSTAR
WRITE (KLUN) YD%GPTWO
WRITE (KLUN) YD%GTPHYGWWMS
WRITE (KLUN) YD%GGAUSSA
WRITE (KLUN) YD%GGAUSSB
WRITE (KLUN) YD%GCOEFF
END SUBROUTINE
SUBROUTINE LOAD_TEGWWMS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGWWMS), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LOZPR
READ (KLUN) YD%LGACALC
READ (KLUN) YD%LGSATL
READ (KLUN) YD%LGINDL
READ (KLUN) YD%NLAUNCHL
READ (KLUN) YD%NLAUNCHLEV
READ (KLUN) YD%NLAUNCH
READ (KLUN) YD%NSLOPE
READ (KLUN) YD%NGAUSS
READ (KLUN) YD%GFLUXLAUNL
READ (KLUN) YD%GFLUXLAUN
READ (KLUN) YD%GMSTAR_L
READ (KLUN) YD%GCSTAR
READ (KLUN) YD%GPTWO
READ (KLUN) YD%GTPHYGWWMS
READ (KLUN) YD%GGAUSSA
READ (KLUN) YD%GGAUSSB
READ (KLUN) YD%GCOEFF
END SUBROUTINE




END MODULE
