MODULE UTIL_TTHF_MOD

USE YOETHF, ONLY : TTHF

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTHF
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTHF
END INTERFACE




CONTAINS

SUBROUTINE SAVE_TTHF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTHF), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%R2ES
WRITE (KLUN) YD%R3LES
WRITE (KLUN) YD%R3IES
WRITE (KLUN) YD%R4LES
WRITE (KLUN) YD%R4IES
WRITE (KLUN) YD%R5LES
WRITE (KLUN) YD%R5IES
WRITE (KLUN) YD%RVTMP2
WRITE (KLUN) YD%RHOH2O
WRITE (KLUN) YD%R5ALVCP
WRITE (KLUN) YD%R5ALSCP
WRITE (KLUN) YD%RALVDCP
WRITE (KLUN) YD%RALSDCP
WRITE (KLUN) YD%RALFDCP
WRITE (KLUN) YD%RTWAT
WRITE (KLUN) YD%RTBER
WRITE (KLUN) YD%RTBERCU
WRITE (KLUN) YD%RTICE
WRITE (KLUN) YD%RTICECU
WRITE (KLUN) YD%RTWAT_RTICE_R
WRITE (KLUN) YD%RTWAT_RTICECU_R
WRITE (KLUN) YD%RKOOP1
WRITE (KLUN) YD%RKOOP2
END SUBROUTINE

SUBROUTINE LOAD_TTHF (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTHF), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%R2ES
READ (KLUN) YD%R3LES
READ (KLUN) YD%R3IES
READ (KLUN) YD%R4LES
READ (KLUN) YD%R4IES
READ (KLUN) YD%R5LES
READ (KLUN) YD%R5IES
READ (KLUN) YD%RVTMP2
READ (KLUN) YD%RHOH2O
READ (KLUN) YD%R5ALVCP
READ (KLUN) YD%R5ALSCP
READ (KLUN) YD%RALVDCP
READ (KLUN) YD%RALSDCP
READ (KLUN) YD%RALFDCP
READ (KLUN) YD%RTWAT
READ (KLUN) YD%RTBER
READ (KLUN) YD%RTBERCU
READ (KLUN) YD%RTICE
READ (KLUN) YD%RTICECU
READ (KLUN) YD%RTWAT_RTICE_R
READ (KLUN) YD%RTWAT_RTICECU_R
READ (KLUN) YD%RKOOP1
READ (KLUN) YD%RKOOP2
END SUBROUTINE






END MODULE
