MODULE UTIL_CPG_CTY_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_CTY_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_CTY_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_CTY_TYPE
END INTERFACE




CONTAINS

SUBROUTINE SAVE_CPG_CTY_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_CTY_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LF_DIVDP, LF_EVEL, LF_PSDIV, LF_PSDVBC, LF_VVEL
WRITE (KLUN) YD%LOWNED
WRITE (KLUN) YD%IP_EVEL
LF_EVEL = ASSOCIATED (YD%F_EVEL)
WRITE (KLUN) LF_EVEL
IF (LF_EVEL) THEN
  CALL SAVE (KLUN, YD%F_EVEL)
ENDIF
WRITE (KLUN) YD%IP_VVEL
LF_VVEL = ASSOCIATED (YD%F_VVEL)
WRITE (KLUN) LF_VVEL
IF (LF_VVEL) THEN
  CALL SAVE (KLUN, YD%F_VVEL)
ENDIF
WRITE (KLUN) YD%IP_PSDIV
LF_PSDIV = ASSOCIATED (YD%F_PSDIV)
WRITE (KLUN) LF_PSDIV
IF (LF_PSDIV) THEN
  CALL SAVE (KLUN, YD%F_PSDIV)
ENDIF
WRITE (KLUN) YD%IP_PSDVBC
LF_PSDVBC = ASSOCIATED (YD%F_PSDVBC)
WRITE (KLUN) LF_PSDVBC
IF (LF_PSDVBC) THEN
  CALL SAVE (KLUN, YD%F_PSDVBC)
ENDIF
WRITE (KLUN) YD%IP_DIVDP
LF_DIVDP = ASSOCIATED (YD%F_DIVDP)
WRITE (KLUN) LF_DIVDP
IF (LF_DIVDP) THEN
  CALL SAVE (KLUN, YD%F_DIVDP)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPG_CTY_TYPE (KLUN, YD)
USE UTIL_FIELD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_CTY_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LF_DIVDP, LF_EVEL, LF_PSDIV, LF_PSDVBC, LF_VVEL
READ (KLUN) YD%LOWNED
NULLIFY (YD%ZVIEW)
NULLIFY (YD%ZDATA)
NULLIFY (YD%F_DATA)
READ (KLUN) YD%IP_EVEL
NULLIFY (YD%EVEL)
READ (KLUN) LF_EVEL
IF (LF_EVEL) THEN
  CALL LOAD (KLUN, YD%F_EVEL)
ELSE
  NULLIFY (YD%F_EVEL)
ENDIF
READ (KLUN) YD%IP_VVEL
NULLIFY (YD%VVEL)
READ (KLUN) LF_VVEL
IF (LF_VVEL) THEN
  CALL LOAD (KLUN, YD%F_VVEL)
ELSE
  NULLIFY (YD%F_VVEL)
ENDIF
READ (KLUN) YD%IP_PSDIV
NULLIFY (YD%PSDIV)
READ (KLUN) LF_PSDIV
IF (LF_PSDIV) THEN
  CALL LOAD (KLUN, YD%F_PSDIV)
ELSE
  NULLIFY (YD%F_PSDIV)
ENDIF
READ (KLUN) YD%IP_PSDVBC
NULLIFY (YD%PSDVBC)
READ (KLUN) LF_PSDVBC
IF (LF_PSDVBC) THEN
  CALL LOAD (KLUN, YD%F_PSDVBC)
ELSE
  NULLIFY (YD%F_PSDVBC)
ENDIF
READ (KLUN) YD%IP_DIVDP
NULLIFY (YD%DIVDP)
READ (KLUN) LF_DIVDP
IF (LF_DIVDP) THEN
  CALL LOAD (KLUN, YD%F_DIVDP)
ELSE
  NULLIFY (YD%F_DIVDP)
ENDIF
END SUBROUTINE






END MODULE
