MODULE UTIL_TSLPHY_MOD

USE YOMSLPHY, ONLY : TSLPHY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSLPHY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSLPHY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSLPHY
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSLPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLPHY), INTENT (IN), TARGET :: YD
LOGICAL :: LSAVTEND
WRITE (KLUN) YD%NVTEND
LSAVTEND = ALLOCATED (YD%SAVTEND)
WRITE (KLUN) LSAVTEND
IF (LSAVTEND) THEN
  WRITE (KLUN) LBOUND (YD%SAVTEND)
  WRITE (KLUN) UBOUND (YD%SAVTEND)
  WRITE (KLUN) YD%SAVTEND
ENDIF
WRITE (KLUN) YD%MU_SAVTEND
WRITE (KLUN) YD%MV_SAVTEND
WRITE (KLUN) YD%MT_SAVTEND
WRITE (KLUN) YD%MSAT_SAVTEND
END SUBROUTINE

SUBROUTINE LOAD_TSLPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLPHY), INTENT (OUT), TARGET :: YD
INTEGER :: IL4(4), IU4(4)
LOGICAL :: LSAVTEND
READ (KLUN) YD%NVTEND
READ (KLUN) LSAVTEND
IF (LSAVTEND) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%SAVTEND (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%SAVTEND
ENDIF
READ (KLUN) YD%MU_SAVTEND
READ (KLUN) YD%MV_SAVTEND
READ (KLUN) YD%MT_SAVTEND
READ (KLUN) YD%MSAT_SAVTEND
END SUBROUTINE


SUBROUTINE COPY_TSLPHY (YD, LDCREATED)

IMPLICIT NONE
TYPE (TSLPHY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LSAVTEND

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

LSAVTEND = ALLOCATED (YD%SAVTEND)
IF (LSAVTEND) THEN
  !$acc enter data create (YD%SAVTEND)
  !$acc update device (YD%SAVTEND)
  !$acc enter data attach (YD%SAVTEND)
ENDIF





END SUBROUTINE



END MODULE
