MODULE UTIL_MODEL_PHYSICS_RADIATION_TYPE_MOD

USE MODEL_PHYSICS_RADIATION_MOD, ONLY : MODEL_PHYSICS_RADIATION_TYPE
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADF_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_RADIATION_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM

CALL SAVE (KLUN, YD%YRRADF)
CALL SAVE (KLUN, YD%YRERAD)
CALL SAVE (KLUN, YD%YREOVLP)
CALL SAVE (KLUN, YD%YRENEUR)
CALL SAVE (KLUN, YD%YRELWRAD)
CALL SAVE (KLUN, YD%YREAERD)
CALL SAVE (KLUN, YD%YREAERATM)
CALL SAVE (KLUN, YD%YREUVRAD)
CALL SAVE (KLUN, YD%YRERDI)
CALL SAVE (KLUN, YD%YREMCICA)
CALL SAVE (KLUN, YD%YRRCOEF)
CALL SAVE (KLUN, YD%YRTRC)
CALL SAVE (KLUN, YD%RADGRID)
LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
WRITE (KLUN) LYRAD_GSGEOM
IF (LYRAD_GSGEOM) THEN
  WRITE (KLUN) LBOUND (YD%YRAD_GSGEOM)
  WRITE (KLUN) UBOUND (YD%YRAD_GSGEOM)
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL SAVE (KLUN, YD%YRAD_GSGEOM (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRERIP)
CALL SAVE (KLUN, YD%YRADIATION)
CALL SAVE (KLUN, YD%YRRI)
CALL SAVE (KLUN, YD%YRRO)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_RADIATION_TYPE (KLUN, YD)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
CLASS (MODEL_PHYSICS_RADIATION_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYRAD_GSGEOM

CALL LOAD (KLUN, YD%YRRADF)
CALL LOAD (KLUN, YD%YRERAD)
CALL LOAD (KLUN, YD%YREOVLP)
CALL LOAD (KLUN, YD%YRENEUR)
CALL LOAD (KLUN, YD%YRELWRAD)
CALL LOAD (KLUN, YD%YREAERD)
CALL LOAD (KLUN, YD%YREAERATM)
CALL LOAD (KLUN, YD%YREUVRAD)
CALL LOAD (KLUN, YD%YRERDI)
CALL LOAD (KLUN, YD%YREMCICA)
CALL LOAD (KLUN, YD%YRRCOEF)
CALL LOAD (KLUN, YD%YRTRC)
CALL LOAD (KLUN, YD%RADGRID)
READ (KLUN) LYRAD_GSGEOM
IF (LYRAD_GSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRAD_GSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL LOAD (KLUN, YD%YRAD_GSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRAD_GSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRERIP)
CALL LOAD (KLUN, YD%YRADIATION)
CALL LOAD (KLUN, YD%YRRI)
CALL LOAD (KLUN, YD%YRRO)
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_RADIATION_TYPE (YD, LDCREATED)
IMPLICIT NONE
CLASS (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRRADF, LDCREATED=.TRUE.)

CALL COPY (YD%YRERAD, LDCREATED=.TRUE.)

CALL COPY (YD%YREOVLP, LDCREATED=.TRUE.)

CALL COPY (YD%YRENEUR, LDCREATED=.TRUE.)

CALL COPY (YD%YRELWRAD, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERD, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERATM, LDCREATED=.TRUE.)

CALL COPY (YD%YREUVRAD, LDCREATED=.TRUE.)

CALL COPY (YD%YRERDI, LDCREATED=.TRUE.)

CALL COPY (YD%YREMCICA, LDCREATED=.TRUE.)

CALL COPY (YD%YRRCOEF, LDCREATED=.TRUE.)

CALL COPY (YD%YRTRC, LDCREATED=.TRUE.)

CALL COPY (YD%RADGRID, LDCREATED=.TRUE.)

LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  !$acc enter data create (YD%YRAD_GSGEOM)
  !$acc update device (YD%YRAD_GSGEOM)
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL COPY (YD%YRAD_GSGEOM (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YRAD_GSGEOM)
ENDIF

CALL COPY (YD%YRERIP, LDCREATED=.TRUE.)

CALL COPY (YD%YRADIATION, LDCREATED=.TRUE.)

CALL COPY (YD%YRRI, LDCREATED=.TRUE.)

CALL COPY (YD%YRRO, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_RADIATION_TYPE (YD, LDDELETED)
IMPLICIT NONE
CLASS (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM

CALL WIPE (YD%YRRADF, LDDELETED=.TRUE.)

CALL WIPE (YD%YRERAD, LDDELETED=.TRUE.)

CALL WIPE (YD%YREOVLP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRENEUR, LDDELETED=.TRUE.)

CALL WIPE (YD%YRELWRAD, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERD, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERATM, LDDELETED=.TRUE.)

CALL WIPE (YD%YREUVRAD, LDDELETED=.TRUE.)

CALL WIPE (YD%YRERDI, LDDELETED=.TRUE.)

CALL WIPE (YD%YREMCICA, LDDELETED=.TRUE.)

CALL WIPE (YD%YRRCOEF, LDDELETED=.TRUE.)

CALL WIPE (YD%YRTRC, LDDELETED=.TRUE.)

CALL WIPE (YD%RADGRID, LDDELETED=.TRUE.)

LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  !$acc exit data detach (YD%YRAD_GSGEOM)
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL WIPE (YD%YRAD_GSGEOM (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YRAD_GSGEOM)
ENDIF

CALL WIPE (YD%YRERIP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRADIATION, LDDELETED=.TRUE.)

CALL WIPE (YD%YRRI, LDDELETED=.TRUE.)

CALL WIPE (YD%YRRO, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
