MODULE UTIL_TLAP_MOD

USE YOMLAP, ONLY : TLAP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLAP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLAP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLAP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TLAP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TLAP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLAP), INTENT (IN), TARGET :: YD
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN
LNASN0 = ALLOCATED (YD%NASN0)
WRITE (KLUN) LNASN0
IF (LNASN0) THEN
  WRITE (KLUN) LBOUND (YD%NASN0)
  WRITE (KLUN) UBOUND (YD%NASN0)
  WRITE (KLUN) YD%NASN0
ENDIF
LNASM0 = ALLOCATED (YD%NASM0)
WRITE (KLUN) LNASM0
IF (LNASM0) THEN
  WRITE (KLUN) LBOUND (YD%NASM0)
  WRITE (KLUN) UBOUND (YD%NASM0)
  WRITE (KLUN) YD%NASM0
ENDIF
LNASM0G = ALLOCATED (YD%NASM0G)
WRITE (KLUN) LNASM0G
IF (LNASM0G) THEN
  WRITE (KLUN) LBOUND (YD%NASM0G)
  WRITE (KLUN) UBOUND (YD%NASM0G)
  WRITE (KLUN) YD%NASM0G
ENDIF
LNVALUE = ALLOCATED (YD%NVALUE)
WRITE (KLUN) LNVALUE
IF (LNVALUE) THEN
  WRITE (KLUN) LBOUND (YD%NVALUE)
  WRITE (KLUN) UBOUND (YD%NVALUE)
  WRITE (KLUN) YD%NVALUE
ENDIF
LMYMS = ALLOCATED (YD%MYMS)
WRITE (KLUN) LMYMS
IF (LMYMS) THEN
  WRITE (KLUN) LBOUND (YD%MYMS)
  WRITE (KLUN) UBOUND (YD%MYMS)
  WRITE (KLUN) YD%MYMS
ENDIF
LNSPZERO = ALLOCATED (YD%NSPZERO)
WRITE (KLUN) LNSPZERO
IF (LNSPZERO) THEN
  WRITE (KLUN) LBOUND (YD%NSPZERO)
  WRITE (KLUN) UBOUND (YD%NSPZERO)
  WRITE (KLUN) YD%NSPZERO
ENDIF
LNSE0L = ALLOCATED (YD%NSE0L)
WRITE (KLUN) LNSE0L
IF (LNSE0L) THEN
  WRITE (KLUN) LBOUND (YD%NSE0L)
  WRITE (KLUN) UBOUND (YD%NSE0L)
  WRITE (KLUN) YD%NSE0L
ENDIF
LRLAPDI = ALLOCATED (YD%RLAPDI)
WRITE (KLUN) LRLAPDI
IF (LRLAPDI) THEN
  WRITE (KLUN) LBOUND (YD%RLAPDI)
  WRITE (KLUN) UBOUND (YD%RLAPDI)
  WRITE (KLUN) YD%RLAPDI
ENDIF
LRLAPIN = ALLOCATED (YD%RLAPIN)
WRITE (KLUN) LRLAPIN
IF (LRLAPIN) THEN
  WRITE (KLUN) LBOUND (YD%RLAPIN)
  WRITE (KLUN) UBOUND (YD%RLAPIN)
  WRITE (KLUN) YD%RLAPIN
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TLAP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLAP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN
READ (KLUN) LNASN0
IF (LNASN0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NASN0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NASN0
ENDIF
READ (KLUN) LNASM0
IF (LNASM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NASM0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NASM0
ENDIF
READ (KLUN) LNASM0G
IF (LNASM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NASM0G (IL1(1):IU1(1)))
  READ (KLUN) YD%NASM0G
ENDIF
READ (KLUN) LNVALUE
IF (LNVALUE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVALUE (IL1(1):IU1(1)))
  READ (KLUN) YD%NVALUE
ENDIF
READ (KLUN) LMYMS
IF (LMYMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYMS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYMS
ENDIF
READ (KLUN) LNSPZERO
IF (LNSPZERO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSPZERO (IL1(1):IU1(1)))
  READ (KLUN) YD%NSPZERO
ENDIF
READ (KLUN) LNSE0L
IF (LNSE0L) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSE0L (IL1(1):IU1(1)))
  READ (KLUN) YD%NSE0L
ENDIF
READ (KLUN) LRLAPDI
IF (LRLAPDI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLAPDI (IL1(1):IU1(1)))
  READ (KLUN) YD%RLAPDI
ENDIF
READ (KLUN) LRLAPIN
IF (LRLAPIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLAPIN (IL1(1):IU1(1)))
  READ (KLUN) YD%RLAPIN
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TLAP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TLAP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LNASN0 = ALLOCATED (YD%NASN0)
IF (LNASN0) THEN
  !$acc enter data create (YD%NASN0)
  !$acc update device (YD%NASN0)
  !$acc enter data attach (YD%NASN0)
ENDIF

LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  !$acc enter data create (YD%NASM0)
  !$acc update device (YD%NASM0)
  !$acc enter data attach (YD%NASM0)
ENDIF

LNASM0G = ALLOCATED (YD%NASM0G)
IF (LNASM0G) THEN
  !$acc enter data create (YD%NASM0G)
  !$acc update device (YD%NASM0G)
  !$acc enter data attach (YD%NASM0G)
ENDIF

LNVALUE = ALLOCATED (YD%NVALUE)
IF (LNVALUE) THEN
  !$acc enter data create (YD%NVALUE)
  !$acc update device (YD%NVALUE)
  !$acc enter data attach (YD%NVALUE)
ENDIF

LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  !$acc enter data create (YD%MYMS)
  !$acc update device (YD%MYMS)
  !$acc enter data attach (YD%MYMS)
ENDIF

LNSPZERO = ALLOCATED (YD%NSPZERO)
IF (LNSPZERO) THEN
  !$acc enter data create (YD%NSPZERO)
  !$acc update device (YD%NSPZERO)
  !$acc enter data attach (YD%NSPZERO)
ENDIF

LNSE0L = ALLOCATED (YD%NSE0L)
IF (LNSE0L) THEN
  !$acc enter data create (YD%NSE0L)
  !$acc update device (YD%NSE0L)
  !$acc enter data attach (YD%NSE0L)
ENDIF

LRLAPDI = ALLOCATED (YD%RLAPDI)
IF (LRLAPDI) THEN
  !$acc enter data create (YD%RLAPDI)
  !$acc update device (YD%RLAPDI)
  !$acc enter data attach (YD%RLAPDI)
ENDIF

LRLAPIN = ALLOCATED (YD%RLAPIN)
IF (LRLAPIN) THEN
  !$acc enter data create (YD%RLAPIN)
  !$acc update device (YD%RLAPIN)
  !$acc enter data attach (YD%RLAPIN)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TLAP (YD, LDDELETED)

IMPLICIT NONE
TYPE (TLAP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN

LNASN0 = ALLOCATED (YD%NASN0)
IF (LNASN0) THEN
  !$acc exit data detach (YD%NASN0)
  !$acc exit data delete (YD%NASN0)
ENDIF

LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  !$acc exit data detach (YD%NASM0)
  !$acc exit data delete (YD%NASM0)
ENDIF

LNASM0G = ALLOCATED (YD%NASM0G)
IF (LNASM0G) THEN
  !$acc exit data detach (YD%NASM0G)
  !$acc exit data delete (YD%NASM0G)
ENDIF

LNVALUE = ALLOCATED (YD%NVALUE)
IF (LNVALUE) THEN
  !$acc exit data detach (YD%NVALUE)
  !$acc exit data delete (YD%NVALUE)
ENDIF

LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  !$acc exit data detach (YD%MYMS)
  !$acc exit data delete (YD%MYMS)
ENDIF

LNSPZERO = ALLOCATED (YD%NSPZERO)
IF (LNSPZERO) THEN
  !$acc exit data detach (YD%NSPZERO)
  !$acc exit data delete (YD%NSPZERO)
ENDIF

LNSE0L = ALLOCATED (YD%NSE0L)
IF (LNSE0L) THEN
  !$acc exit data detach (YD%NSE0L)
  !$acc exit data delete (YD%NSE0L)
ENDIF

LRLAPDI = ALLOCATED (YD%RLAPDI)
IF (LRLAPDI) THEN
  !$acc exit data detach (YD%RLAPDI)
  !$acc exit data delete (YD%RLAPDI)
ENDIF

LRLAPIN = ALLOCATED (YD%RLAPIN)
IF (LRLAPIN) THEN
  !$acc exit data detach (YD%RLAPIN)
  !$acc exit data delete (YD%RLAPIN)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
