MODULE UTIL_TCOM_MOD

USE YOMCOM, ONLY : TCOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCOM
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOM), INTENT (IN), TARGET :: YD
LOGICAL :: LGTTLIN, LOMLDTH, LSSTMSK, LSSTPRE, LTRAFLX
WRITE (KLUN) YD%NVCOM
LOMLDTH = ALLOCATED (YD%OMLDTH)
WRITE (KLUN) LOMLDTH
IF (LOMLDTH) THEN
  WRITE (KLUN) LBOUND (YD%OMLDTH)
  WRITE (KLUN) UBOUND (YD%OMLDTH)
  WRITE (KLUN) YD%OMLDTH
ENDIF
LGTTLIN = ALLOCATED (YD%GTTLIN)
WRITE (KLUN) LGTTLIN
IF (LGTTLIN) THEN
  WRITE (KLUN) LBOUND (YD%GTTLIN)
  WRITE (KLUN) UBOUND (YD%GTTLIN)
  WRITE (KLUN) YD%GTTLIN
ENDIF
LSSTPRE = ALLOCATED (YD%SSTPRE)
WRITE (KLUN) LSSTPRE
IF (LSSTPRE) THEN
  WRITE (KLUN) LBOUND (YD%SSTPRE)
  WRITE (KLUN) UBOUND (YD%SSTPRE)
  WRITE (KLUN) YD%SSTPRE
ENDIF
LSSTMSK = ALLOCATED (YD%SSTMSK)
WRITE (KLUN) LSSTMSK
IF (LSSTMSK) THEN
  WRITE (KLUN) LBOUND (YD%SSTMSK)
  WRITE (KLUN) UBOUND (YD%SSTMSK)
  WRITE (KLUN) YD%SSTMSK
ENDIF
WRITE (KLUN) YD%LOMLDTH
LTRAFLX = ALLOCATED (YD%TRAFLX)
WRITE (KLUN) LTRAFLX
IF (LTRAFLX) THEN
  WRITE (KLUN) LBOUND (YD%TRAFLX)
  WRITE (KLUN) UBOUND (YD%TRAFLX)
  WRITE (KLUN) YD%TRAFLX
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TCOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LGTTLIN, LOMLDTH, LSSTMSK, LSSTPRE, LTRAFLX
READ (KLUN) YD%NVCOM
READ (KLUN) LOMLDTH
IF (LOMLDTH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OMLDTH (IL1(1):IU1(1)))
  READ (KLUN) YD%OMLDTH
ENDIF
READ (KLUN) LGTTLIN
IF (LGTTLIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GTTLIN (IL1(1):IU1(1)))
  READ (KLUN) YD%GTTLIN
ENDIF
READ (KLUN) LSSTPRE
IF (LSSTPRE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SSTPRE (IL1(1):IU1(1)))
  READ (KLUN) YD%SSTPRE
ENDIF
READ (KLUN) LSSTMSK
IF (LSSTMSK) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SSTMSK (IL1(1):IU1(1)))
  READ (KLUN) YD%SSTMSK
ENDIF
READ (KLUN) YD%LOMLDTH
READ (KLUN) LTRAFLX
IF (LTRAFLX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%TRAFLX (IL1(1):IU1(1)))
  READ (KLUN) YD%TRAFLX
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TCOM (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LGTTLIN, LOMLDTH, LSSTMSK, LSSTPRE, LTRAFLX

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

LOMLDTH = ALLOCATED (YD%OMLDTH)
IF (LOMLDTH) THEN
  !$acc enter data create (YD%OMLDTH)
  !$acc update device (YD%OMLDTH)
  !$acc enter data attach (YD%OMLDTH)
ENDIF

LGTTLIN = ALLOCATED (YD%GTTLIN)
IF (LGTTLIN) THEN
  !$acc enter data create (YD%GTTLIN)
  !$acc update device (YD%GTTLIN)
  !$acc enter data attach (YD%GTTLIN)
ENDIF

LSSTPRE = ALLOCATED (YD%SSTPRE)
IF (LSSTPRE) THEN
  !$acc enter data create (YD%SSTPRE)
  !$acc update device (YD%SSTPRE)
  !$acc enter data attach (YD%SSTPRE)
ENDIF

LSSTMSK = ALLOCATED (YD%SSTMSK)
IF (LSSTMSK) THEN
  !$acc enter data create (YD%SSTMSK)
  !$acc update device (YD%SSTMSK)
  !$acc enter data attach (YD%SSTMSK)
ENDIF


LTRAFLX = ALLOCATED (YD%TRAFLX)
IF (LTRAFLX) THEN
  !$acc enter data create (YD%TRAFLX)
  !$acc update device (YD%TRAFLX)
  !$acc enter data attach (YD%TRAFLX)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TCOM (YD, LDDELETED)

IMPLICIT NONE
TYPE (TCOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LGTTLIN, LOMLDTH, LSSTMSK, LSSTPRE, LTRAFLX


LOMLDTH = ALLOCATED (YD%OMLDTH)
IF (LOMLDTH) THEN
  !$acc exit data detach (YD%OMLDTH)
  !$acc exit data delete (YD%OMLDTH)
ENDIF

LGTTLIN = ALLOCATED (YD%GTTLIN)
IF (LGTTLIN) THEN
  !$acc exit data detach (YD%GTTLIN)
  !$acc exit data delete (YD%GTTLIN)
ENDIF

LSSTPRE = ALLOCATED (YD%SSTPRE)
IF (LSSTPRE) THEN
  !$acc exit data detach (YD%SSTPRE)
  !$acc exit data delete (YD%SSTPRE)
ENDIF

LSSTMSK = ALLOCATED (YD%SSTMSK)
IF (LSSTMSK) THEN
  !$acc exit data detach (YD%SSTMSK)
  !$acc exit data delete (YD%SSTMSK)
ENDIF


LTRAFLX = ALLOCATED (YD%TRAFLX)
IF (LTRAFLX) THEN
  !$acc exit data detach (YD%TRAFLX)
  !$acc exit data delete (YD%TRAFLX)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
