MODULE UTIL_TGSGEOM_MOD

USE YOMGSGEOM, ONLY : TGSGEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGSGEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGSGEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGSGEOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGSGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGSGEOM), INTENT (IN), TARGET :: YD
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LGM, LGMAPPA, LGNORDL, LGNORDLCL
LOGICAL :: LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL, LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC
LRCORI = ASSOCIATED (YD%RCORI)
WRITE (KLUN) LRCORI
IF (LRCORI) THEN
  WRITE (KLUN) LBOUND (YD%RCORI)
  WRITE (KLUN) UBOUND (YD%RCORI)
  WRITE (KLUN) YD%RCORI
ENDIF
LRCORIC = ASSOCIATED (YD%RCORIC)
WRITE (KLUN) LRCORIC
IF (LRCORIC) THEN
  WRITE (KLUN) LBOUND (YD%RCORIC)
  WRITE (KLUN) UBOUND (YD%RCORIC)
  WRITE (KLUN) YD%RCORIC
ENDIF
LGEMU = ASSOCIATED (YD%GEMU)
WRITE (KLUN) LGEMU
IF (LGEMU) THEN
  WRITE (KLUN) LBOUND (YD%GEMU)
  WRITE (KLUN) UBOUND (YD%GEMU)
  WRITE (KLUN) YD%GEMU
ENDIF
LGSQM2 = ASSOCIATED (YD%GSQM2)
WRITE (KLUN) LGSQM2
IF (LGSQM2) THEN
  WRITE (KLUN) LBOUND (YD%GSQM2)
  WRITE (KLUN) UBOUND (YD%GSQM2)
  WRITE (KLUN) YD%GSQM2
ENDIF
LGELAM = ASSOCIATED (YD%GELAM)
WRITE (KLUN) LGELAM
IF (LGELAM) THEN
  WRITE (KLUN) LBOUND (YD%GELAM)
  WRITE (KLUN) UBOUND (YD%GELAM)
  WRITE (KLUN) YD%GELAM
ENDIF
LGELAT = ASSOCIATED (YD%GELAT)
WRITE (KLUN) LGELAT
IF (LGELAT) THEN
  WRITE (KLUN) LBOUND (YD%GELAT)
  WRITE (KLUN) UBOUND (YD%GELAT)
  WRITE (KLUN) YD%GELAT
ENDIF
LGECLO = ASSOCIATED (YD%GECLO)
WRITE (KLUN) LGECLO
IF (LGECLO) THEN
  WRITE (KLUN) LBOUND (YD%GECLO)
  WRITE (KLUN) UBOUND (YD%GECLO)
  WRITE (KLUN) YD%GECLO
ENDIF
LGESLO = ASSOCIATED (YD%GESLO)
WRITE (KLUN) LGESLO
IF (LGESLO) THEN
  WRITE (KLUN) LBOUND (YD%GESLO)
  WRITE (KLUN) UBOUND (YD%GESLO)
  WRITE (KLUN) YD%GESLO
ENDIF
LGM = ASSOCIATED (YD%GM)
WRITE (KLUN) LGM
IF (LGM) THEN
  WRITE (KLUN) LBOUND (YD%GM)
  WRITE (KLUN) UBOUND (YD%GM)
  WRITE (KLUN) YD%GM
ENDIF
LGMAPPA = ASSOCIATED (YD%GMAPPA)
WRITE (KLUN) LGMAPPA
IF (LGMAPPA) THEN
  WRITE (KLUN) LBOUND (YD%GMAPPA)
  WRITE (KLUN) UBOUND (YD%GMAPPA)
  WRITE (KLUN) YD%GMAPPA
ENDIF
LGOMVRL = ASSOCIATED (YD%GOMVRL)
WRITE (KLUN) LGOMVRL
IF (LGOMVRL) THEN
  WRITE (KLUN) LBOUND (YD%GOMVRL)
  WRITE (KLUN) UBOUND (YD%GOMVRL)
  WRITE (KLUN) YD%GOMVRL
ENDIF
LGOMVRM = ASSOCIATED (YD%GOMVRM)
WRITE (KLUN) LGOMVRM
IF (LGOMVRM) THEN
  WRITE (KLUN) LBOUND (YD%GOMVRM)
  WRITE (KLUN) UBOUND (YD%GOMVRM)
  WRITE (KLUN) YD%GOMVRM
ENDIF
LGNORDL = ASSOCIATED (YD%GNORDL)
WRITE (KLUN) LGNORDL
IF (LGNORDL) THEN
  WRITE (KLUN) LBOUND (YD%GNORDL)
  WRITE (KLUN) UBOUND (YD%GNORDL)
  WRITE (KLUN) YD%GNORDL
ENDIF
LGNORDM = ASSOCIATED (YD%GNORDM)
WRITE (KLUN) LGNORDM
IF (LGNORDM) THEN
  WRITE (KLUN) LBOUND (YD%GNORDM)
  WRITE (KLUN) UBOUND (YD%GNORDM)
  WRITE (KLUN) YD%GNORDM
ENDIF
LGNORDLCL = ASSOCIATED (YD%GNORDLCL)
WRITE (KLUN) LGNORDLCL
IF (LGNORDLCL) THEN
  WRITE (KLUN) LBOUND (YD%GNORDLCL)
  WRITE (KLUN) UBOUND (YD%GNORDLCL)
  WRITE (KLUN) YD%GNORDLCL
ENDIF
LGNORDMCL = ASSOCIATED (YD%GNORDMCL)
WRITE (KLUN) LGNORDMCL
IF (LGNORDMCL) THEN
  WRITE (KLUN) LBOUND (YD%GNORDMCL)
  WRITE (KLUN) UBOUND (YD%GNORDMCL)
  WRITE (KLUN) YD%GNORDMCL
ENDIF
LGNORDMCM = ASSOCIATED (YD%GNORDMCM)
WRITE (KLUN) LGNORDMCM
IF (LGNORDMCM) THEN
  WRITE (KLUN) LBOUND (YD%GNORDMCM)
  WRITE (KLUN) UBOUND (YD%GNORDMCM)
  WRITE (KLUN) YD%GNORDMCM
ENDIF
LGAW = ASSOCIATED (YD%GAW)
WRITE (KLUN) LGAW
IF (LGAW) THEN
  WRITE (KLUN) LBOUND (YD%GAW)
  WRITE (KLUN) UBOUND (YD%GAW)
  WRITE (KLUN) YD%GAW
ENDIF
LNGPLAT = ASSOCIATED (YD%NGPLAT)
WRITE (KLUN) LNGPLAT
IF (LNGPLAT) THEN
  WRITE (KLUN) LBOUND (YD%NGPLAT)
  WRITE (KLUN) UBOUND (YD%NGPLAT)
  WRITE (KLUN) YD%NGPLAT
ENDIF
LNUNIQUEGP = ASSOCIATED (YD%NUNIQUEGP)
WRITE (KLUN) LNUNIQUEGP
IF (LNUNIQUEGP) THEN
  WRITE (KLUN) LBOUND (YD%NUNIQUEGP)
  WRITE (KLUN) UBOUND (YD%NUNIQUEGP)
  WRITE (KLUN) YD%NUNIQUEGP
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TGSGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGSGEOM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LGM, LGMAPPA, LGNORDL, LGNORDLCL
LOGICAL :: LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL, LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC
READ (KLUN) LRCORI
IF (LRCORI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORI (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORI
ELSE
  NULLIFY (YD%RCORI)
ENDIF
READ (KLUN) LRCORIC
IF (LRCORIC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORIC (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORIC
ELSE
  NULLIFY (YD%RCORIC)
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GEMU (IL1(1):IU1(1)))
  READ (KLUN) YD%GEMU
ELSE
  NULLIFY (YD%GEMU)
ENDIF
READ (KLUN) LGSQM2
IF (LGSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GSQM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%GSQM2
ELSE
  NULLIFY (YD%GSQM2)
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAM (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAM
ELSE
  NULLIFY (YD%GELAM)
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAT (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAT
ELSE
  NULLIFY (YD%GELAT)
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GECLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GECLO
ELSE
  NULLIFY (YD%GECLO)
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GESLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GESLO
ELSE
  NULLIFY (YD%GESLO)
ENDIF
READ (KLUN) LGM
IF (LGM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GM (IL1(1):IU1(1)))
  READ (KLUN) YD%GM
ELSE
  NULLIFY (YD%GM)
ENDIF
READ (KLUN) LGMAPPA
IF (LGMAPPA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GMAPPA (IL1(1):IU1(1)))
  READ (KLUN) YD%GMAPPA
ELSE
  NULLIFY (YD%GMAPPA)
ENDIF
READ (KLUN) LGOMVRL
IF (LGOMVRL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GOMVRL (IL1(1):IU1(1)))
  READ (KLUN) YD%GOMVRL
ELSE
  NULLIFY (YD%GOMVRL)
ENDIF
READ (KLUN) LGOMVRM
IF (LGOMVRM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GOMVRM (IL1(1):IU1(1)))
  READ (KLUN) YD%GOMVRM
ELSE
  NULLIFY (YD%GOMVRM)
ENDIF
READ (KLUN) LGNORDL
IF (LGNORDL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDL (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDL
ELSE
  NULLIFY (YD%GNORDL)
ENDIF
READ (KLUN) LGNORDM
IF (LGNORDM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDM (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDM
ELSE
  NULLIFY (YD%GNORDM)
ENDIF
READ (KLUN) LGNORDLCL
IF (LGNORDLCL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDLCL (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDLCL
ELSE
  NULLIFY (YD%GNORDLCL)
ENDIF
READ (KLUN) LGNORDMCL
IF (LGNORDMCL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDMCL (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDMCL
ELSE
  NULLIFY (YD%GNORDMCL)
ENDIF
READ (KLUN) LGNORDMCM
IF (LGNORDMCM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDMCM (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDMCM
ELSE
  NULLIFY (YD%GNORDMCM)
ENDIF
READ (KLUN) LGAW
IF (LGAW) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GAW (IL1(1):IU1(1)))
  READ (KLUN) YD%GAW
ELSE
  NULLIFY (YD%GAW)
ENDIF
READ (KLUN) LNGPLAT
IF (LNGPLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGPLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NGPLAT
ELSE
  NULLIFY (YD%NGPLAT)
ENDIF
READ (KLUN) LNUNIQUEGP
IF (LNUNIQUEGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUNIQUEGP (IL1(1):IU1(1)))
  READ (KLUN) YD%NUNIQUEGP
ELSE
  NULLIFY (YD%NUNIQUEGP)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TGSGEOM (YD, LDCREATED)

IMPLICIT NONE
TYPE (TGSGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LGM, LGMAPPA, LGNORDL, LGNORDLCL
LOGICAL :: LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL, LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRCORI = ASSOCIATED (YD%RCORI)
IF (LRCORI) THEN
  !$acc enter data create (YD%RCORI)
  !$acc update device (YD%RCORI)
  !$acc enter data attach (YD%RCORI)
ENDIF

LRCORIC = ASSOCIATED (YD%RCORIC)
IF (LRCORIC) THEN
  !$acc enter data create (YD%RCORIC)
  !$acc update device (YD%RCORIC)
  !$acc enter data attach (YD%RCORIC)
ENDIF

LGEMU = ASSOCIATED (YD%GEMU)
IF (LGEMU) THEN
  !$acc enter data create (YD%GEMU)
  !$acc update device (YD%GEMU)
  !$acc enter data attach (YD%GEMU)
ENDIF

LGSQM2 = ASSOCIATED (YD%GSQM2)
IF (LGSQM2) THEN
  !$acc enter data create (YD%GSQM2)
  !$acc update device (YD%GSQM2)
  !$acc enter data attach (YD%GSQM2)
ENDIF

LGELAM = ASSOCIATED (YD%GELAM)
IF (LGELAM) THEN
  !$acc enter data create (YD%GELAM)
  !$acc update device (YD%GELAM)
  !$acc enter data attach (YD%GELAM)
ENDIF

LGELAT = ASSOCIATED (YD%GELAT)
IF (LGELAT) THEN
  !$acc enter data create (YD%GELAT)
  !$acc update device (YD%GELAT)
  !$acc enter data attach (YD%GELAT)
ENDIF

LGECLO = ASSOCIATED (YD%GECLO)
IF (LGECLO) THEN
  !$acc enter data create (YD%GECLO)
  !$acc update device (YD%GECLO)
  !$acc enter data attach (YD%GECLO)
ENDIF

LGESLO = ASSOCIATED (YD%GESLO)
IF (LGESLO) THEN
  !$acc enter data create (YD%GESLO)
  !$acc update device (YD%GESLO)
  !$acc enter data attach (YD%GESLO)
ENDIF

LGM = ASSOCIATED (YD%GM)
IF (LGM) THEN
  !$acc enter data create (YD%GM)
  !$acc update device (YD%GM)
  !$acc enter data attach (YD%GM)
ENDIF

LGMAPPA = ASSOCIATED (YD%GMAPPA)
IF (LGMAPPA) THEN
  !$acc enter data create (YD%GMAPPA)
  !$acc update device (YD%GMAPPA)
  !$acc enter data attach (YD%GMAPPA)
ENDIF

LGOMVRL = ASSOCIATED (YD%GOMVRL)
IF (LGOMVRL) THEN
  !$acc enter data create (YD%GOMVRL)
  !$acc update device (YD%GOMVRL)
  !$acc enter data attach (YD%GOMVRL)
ENDIF

LGOMVRM = ASSOCIATED (YD%GOMVRM)
IF (LGOMVRM) THEN
  !$acc enter data create (YD%GOMVRM)
  !$acc update device (YD%GOMVRM)
  !$acc enter data attach (YD%GOMVRM)
ENDIF

LGNORDL = ASSOCIATED (YD%GNORDL)
IF (LGNORDL) THEN
  !$acc enter data create (YD%GNORDL)
  !$acc update device (YD%GNORDL)
  !$acc enter data attach (YD%GNORDL)
ENDIF

LGNORDM = ASSOCIATED (YD%GNORDM)
IF (LGNORDM) THEN
  !$acc enter data create (YD%GNORDM)
  !$acc update device (YD%GNORDM)
  !$acc enter data attach (YD%GNORDM)
ENDIF

LGNORDLCL = ASSOCIATED (YD%GNORDLCL)
IF (LGNORDLCL) THEN
  !$acc enter data create (YD%GNORDLCL)
  !$acc update device (YD%GNORDLCL)
  !$acc enter data attach (YD%GNORDLCL)
ENDIF

LGNORDMCL = ASSOCIATED (YD%GNORDMCL)
IF (LGNORDMCL) THEN
  !$acc enter data create (YD%GNORDMCL)
  !$acc update device (YD%GNORDMCL)
  !$acc enter data attach (YD%GNORDMCL)
ENDIF

LGNORDMCM = ASSOCIATED (YD%GNORDMCM)
IF (LGNORDMCM) THEN
  !$acc enter data create (YD%GNORDMCM)
  !$acc update device (YD%GNORDMCM)
  !$acc enter data attach (YD%GNORDMCM)
ENDIF

LGAW = ASSOCIATED (YD%GAW)
IF (LGAW) THEN
  !$acc enter data create (YD%GAW)
  !$acc update device (YD%GAW)
  !$acc enter data attach (YD%GAW)
ENDIF

LNGPLAT = ASSOCIATED (YD%NGPLAT)
IF (LNGPLAT) THEN
  !$acc enter data create (YD%NGPLAT)
  !$acc update device (YD%NGPLAT)
  !$acc enter data attach (YD%NGPLAT)
ENDIF

LNUNIQUEGP = ASSOCIATED (YD%NUNIQUEGP)
IF (LNUNIQUEGP) THEN
  !$acc enter data create (YD%NUNIQUEGP)
  !$acc update device (YD%NUNIQUEGP)
  !$acc enter data attach (YD%NUNIQUEGP)
ENDIF

END SUBROUTINE



END MODULE
