MODULE UTIL_TGEM_MOD

USE YOMGEM, ONLY : TGEM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGEM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGEM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGEM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGEM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGEM), INTENT (IN), TARGET :: YD
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP
WRITE (KLUN) YD%NGPTOT
WRITE (KLUN) YD%NGPTOT_CAP
WRITE (KLUN) YD%NGPTOTMX
WRITE (KLUN) YD%NGPTOTG
LNGPTOTL = ALLOCATED (YD%NGPTOTL)
WRITE (KLUN) LNGPTOTL
IF (LNGPTOTL) THEN
  WRITE (KLUN) LBOUND (YD%NGPTOTL)
  WRITE (KLUN) UBOUND (YD%NGPTOTL)
  WRITE (KLUN) YD%NGPTOTL
ENDIF
WRITE (KLUN) YD%RDELXN
WRITE (KLUN) YD%SLHDP
WRITE (KLUN) YD%RMUCEN
WRITE (KLUN) YD%RLOCEN
WRITE (KLUN) YD%RSTRET
WRITE (KLUN) YD%NSTTYP
WRITE (KLUN) YD%NHTYP
WRITE (KLUN) YD%RNLGINC
WRITE (KLUN) YD%R4JP
WRITE (KLUN) YD%RC2P1
WRITE (KLUN) YD%RC2M1
WRITE (KLUN) YD%RCOR0
WRITE (KLUN) YD%RCOR1
LNLOEN = ALLOCATED (YD%NLOEN)
WRITE (KLUN) LNLOEN
IF (LNLOEN) THEN
  WRITE (KLUN) LBOUND (YD%NLOEN)
  WRITE (KLUN) UBOUND (YD%NLOEN)
  WRITE (KLUN) YD%NLOEN
ENDIF
LNLOENG = ALLOCATED (YD%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (YD%NLOENG)
  WRITE (KLUN) UBOUND (YD%NLOENG)
  WRITE (KLUN) YD%NLOENG
ENDIF
LNMEN = ALLOCATED (YD%NMEN)
WRITE (KLUN) LNMEN
IF (LNMEN) THEN
  WRITE (KLUN) LBOUND (YD%NMEN)
  WRITE (KLUN) UBOUND (YD%NMEN)
  WRITE (KLUN) YD%NMEN
ENDIF
LNMENG = ALLOCATED (YD%NMENG)
WRITE (KLUN) LNMENG
IF (LNMENG) THEN
  WRITE (KLUN) LBOUND (YD%NMENG)
  WRITE (KLUN) UBOUND (YD%NMENG)
  WRITE (KLUN) YD%NMENG
ENDIF
LNDGLU = ALLOCATED (YD%NDGLU)
WRITE (KLUN) LNDGLU
IF (LNDGLU) THEN
  WRITE (KLUN) LBOUND (YD%NDGLU)
  WRITE (KLUN) UBOUND (YD%NDGLU)
  WRITE (KLUN) YD%NDGLU
ENDIF
LNSTAGP = ALLOCATED (YD%NSTAGP)
WRITE (KLUN) LNSTAGP
IF (LNSTAGP) THEN
  WRITE (KLUN) LBOUND (YD%NSTAGP)
  WRITE (KLUN) UBOUND (YD%NSTAGP)
  WRITE (KLUN) YD%NSTAGP
ENDIF
LNTSTAGP = ALLOCATED (YD%NTSTAGP)
WRITE (KLUN) LNTSTAGP
IF (LNTSTAGP) THEN
  WRITE (KLUN) LBOUND (YD%NTSTAGP)
  WRITE (KLUN) UBOUND (YD%NTSTAGP)
  WRITE (KLUN) YD%NTSTAGP
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TGEM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGEM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NGPTOT_CAP
READ (KLUN) YD%NGPTOTMX
READ (KLUN) YD%NGPTOTG
READ (KLUN) LNGPTOTL
IF (LNGPTOTL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGPTOTL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGPTOTL
ENDIF
READ (KLUN) YD%RDELXN
READ (KLUN) YD%SLHDP
READ (KLUN) YD%RMUCEN
READ (KLUN) YD%RLOCEN
READ (KLUN) YD%RSTRET
READ (KLUN) YD%NSTTYP
READ (KLUN) YD%NHTYP
READ (KLUN) YD%RNLGINC
READ (KLUN) YD%R4JP
READ (KLUN) YD%RC2P1
READ (KLUN) YD%RC2M1
READ (KLUN) YD%RCOR0
READ (KLUN) YD%RCOR1
READ (KLUN) LNLOEN
IF (LNLOEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOEN (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOEN
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
READ (KLUN) LNMEN
IF (LNMEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NMEN (IL1(1):IU1(1)))
  READ (KLUN) YD%NMEN
ENDIF
READ (KLUN) LNMENG
IF (LNMENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NMENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NMENG
ENDIF
READ (KLUN) LNDGLU
IF (LNDGLU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDGLU (IL1(1):IU1(1)))
  READ (KLUN) YD%NDGLU
ENDIF
READ (KLUN) LNSTAGP
IF (LNSTAGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSTAGP (IL1(1):IU1(1)))
  READ (KLUN) YD%NSTAGP
ENDIF
READ (KLUN) LNTSTAGP
IF (LNTSTAGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NTSTAGP (IL1(1):IU1(1)))
  READ (KLUN) YD%NTSTAGP
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TGEM (YD, LDCREATED)

IMPLICIT NONE
TYPE (TGEM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




LNGPTOTL = ALLOCATED (YD%NGPTOTL)
IF (LNGPTOTL) THEN
  !$acc enter data create (YD%NGPTOTL)
  !$acc update device (YD%NGPTOTL)
  !$acc enter data attach (YD%NGPTOTL)
ENDIF














LNLOEN = ALLOCATED (YD%NLOEN)
IF (LNLOEN) THEN
  !$acc enter data create (YD%NLOEN)
  !$acc update device (YD%NLOEN)
  !$acc enter data attach (YD%NLOEN)
ENDIF

LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  !$acc enter data create (YD%NLOENG)
  !$acc update device (YD%NLOENG)
  !$acc enter data attach (YD%NLOENG)
ENDIF

LNMEN = ALLOCATED (YD%NMEN)
IF (LNMEN) THEN
  !$acc enter data create (YD%NMEN)
  !$acc update device (YD%NMEN)
  !$acc enter data attach (YD%NMEN)
ENDIF

LNMENG = ALLOCATED (YD%NMENG)
IF (LNMENG) THEN
  !$acc enter data create (YD%NMENG)
  !$acc update device (YD%NMENG)
  !$acc enter data attach (YD%NMENG)
ENDIF

LNDGLU = ALLOCATED (YD%NDGLU)
IF (LNDGLU) THEN
  !$acc enter data create (YD%NDGLU)
  !$acc update device (YD%NDGLU)
  !$acc enter data attach (YD%NDGLU)
ENDIF

LNSTAGP = ALLOCATED (YD%NSTAGP)
IF (LNSTAGP) THEN
  !$acc enter data create (YD%NSTAGP)
  !$acc update device (YD%NSTAGP)
  !$acc enter data attach (YD%NSTAGP)
ENDIF

LNTSTAGP = ALLOCATED (YD%NTSTAGP)
IF (LNTSTAGP) THEN
  !$acc enter data create (YD%NTSTAGP)
  !$acc update device (YD%NTSTAGP)
  !$acc enter data attach (YD%NTSTAGP)
ENDIF

END SUBROUTINE



END MODULE
