PROGRAM WRAP_CPG_DIA_FLU

USE PARKIND1                , ONLY : JPIM, JPRB
USE YOMHOOK                 , ONLY : LHOOK, DR_HOOK
USE XRD_GETOPTIONS          

USE CPG_OPTS_TYPE_MOD       , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD            , ONLY : CPG_DYN_TYPE, CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD        , ONLY : MF_PHYS_OUT_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD, ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD     , ONLY : FIELD_VARIABLES
USE YOMCFU                  , ONLY : TCFU
USE YOMXFU                  , ONLY : TXFU
USE TYPE_MODEL              , ONLY : MODEL

USE UTIL_FIELD_VARIABLES_MOD
USE UTIL_CPG_OPTS_TYPE_MOD
USE UTIL_CPG_BNDS_TYPE_MOD
USE UTIL_CPG_MISC_TYPE_MOD
USE UTIL_CPG_DYN_TYPE_MOD
USE UTIL_TCFU_MOD
USE UTIL_TXFU_MOD
USE UTIL_MF_PHYS_OUT_TYPE_MOD
USE UTIL_MF_PHYS_SURF_TYPE_MOD
USE UTIL_MODEL_MOD

USE STACK_MOD

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(CPG_BNDS_TYPE)       :: YLCPG_BNDS
TYPE(CPG_OPTS_TYPE)       :: YLCPG_OPTS
TYPE(CPG_MISC_TYPE)       :: YLCPG_MISC
TYPE(MF_PHYS_OUT_TYPE)    :: YLMF_PHYS_OUT
TYPE(CPG_DYN_TYPE)        :: YLCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE)   :: YLMF_PHYS_SURF
TYPE(FIELD_VARIABLES)     :: YLVARS
TYPE(TCFU)                :: YLCFU, YLCFU_REF
TYPE(TXFU)                :: YLXFU, YLXFU_REF
TYPE(MODEL)               :: YLMODEL
TYPE(STACK)               :: YLSTACK
TYPE(FIELD_2D_OWNER), POINTER :: YLFO ! For the stack

#include "cpg_dia_flu.intfb.h"
#include "cpg_dia_flu_parallel.intfb.h"

TYPE(CPG_BNDS_TYPE)       :: YLCPG_BNDS1

CHARACTER*32 :: CLPROC
CHARACTER*256 :: CLFILE, CLCASE, CLOUT, CLCASEREF
INTEGER (KIND=JPIM) :: JLON, IBL, NGPBLKS, NPROMA
INTEGER (KIND=JPIM) :: NTIME, ITIME
INTEGER (KIND=JPIM) :: NSTACKSIZE
LOGICAL :: LLDIFF, LLSYNCHOST, LLPARALLEL

REAL (KIND=JPRB) :: ZHOOK_HANDLE, ZHOOK_HANDLE_1

IF (LHOOK) CALL DR_HOOK('WRAP_CPG_DIA_FLU',0,ZHOOK_HANDLE)

CALL INITOPTIONS 
NTIME = 1
CALL GETOPTION ("--times", NTIME)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--parallel", LLPARALLEL)
CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CLCASEREF = CLCASE
CALL GETOPTION ("--case-ref", CLCASEREF)
CLOUT = ''
CALL GETOPTION ("--out", CLOUT)
NGPBLKS = 999999999
CALL GETOPTION ("--ngpblks", NGPBLKS)
NSTACKSIZE = 100000
CALL GETOPTION ("--stack-size", NSTACKSIZE)
CALL CHECKOPTIONS

WRITE (CLPROC, '(".",I4.4,".",I4.4)') 1, 3

CLFILE = TRIM (CLCASE)//"/YDMODEL.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLMODEL)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDVARS.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLVARS)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDCPG_OPTS.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLCPG_OPTS)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDCPG_BNDS.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLCPG_BNDS)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDCPG_MISC.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLCPG_MISC)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDCPG_DYN0.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLCPG_DYN0)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDXFU.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLXFU)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDCFU.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLCFU)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDMF_PHYS_OUT.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLMF_PHYS_OUT)
CLOSE (77)

CLFILE = TRIM (CLCASE)//"/YDMF_PHYS_SURF.IN"//TRIM (CLPROC)
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
CALL LOAD (77, YLMF_PHYS_SURF)
CLOSE (77)

NPROMA = SIZE (YLCPG_DYN0%F_PHI%PTR, 1)
NGPBLKS = MIN (NGPBLKS, SIZE (YLCPG_DYN0%F_PHI%PTR, 3))

PRINT *, " NPROMA, NGPBLKS = ", NPROMA, NGPBLKS

YLCPG_OPTS%KGPBLKS = NGPBLKS

IF (LLSYNCHOST) THEN
  CALL CPG_DIA_FLU_SYNC_HOST (YLCPG_BNDS, YLCPG_OPTS, YLCPG_MISC, YLMF_PHYS_OUT, YLCPG_DYN0, &
                            & YLMF_PHYS_SURF, YLVARS, YLCFU, YLXFU, YLMODEL)
ENDIF


ALLOCATE (YLFO)
CALL YLFO%INIT (PERSISTENT=.TRUE., UBOUNDS=[NSTACKSIZE,NGPBLKS], LBOUNDS=[1,1])
YLSTACK%F_P => YLFO


DO ITIME = 1, NTIME

  IF (LHOOK) CALL DR_HOOK('WRAP_CPG_DIA_FLU:PARALLEL',0,ZHOOK_HANDLE_1)

  IF (LLPARALLEL) THEN
    CALL CPG_DIA_FLU_PARALLEL &
              & (YLCPG_BNDS, YLCPG_OPTS, YLCPG_MISC, YLMF_PHYS_OUT, &
              & YLCPG_DYN0, YLMF_PHYS_SURF, YLVARS, YLCFU, YLXFU, YLMODEL, YLSTACK)
  ELSE

!$OMP PARALLEL PRIVATE (IBL) &
!$OMP FIRSTPRIVATE (YLVARS, YLMF_PHYS_SURF, YLCPG_DYN0, YLCPG_MISC, YLMF_PHYS_OUT, &
!$OMP             & YLCPG_BNDS, YLCPG_BNDS1, YLXFU, YLCFU, YLSTACK)
  
!$OMP DO SCHEDULE(DYNAMIC,1)
  
  DO IBL = 1, NGPBLKS
  
    CALL YLVARS%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLMF_PHYS_SURF%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLCPG_DYN0%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLMF_PHYS_OUT%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLXFU%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLCFU%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLCPG_MISC%UPDATE_VIEW (BLOCK_INDEX=IBL)
    CALL YLCPG_BNDS%UPDATE (IBL)
  
    CALL CPG_DIA_FLU (YLCPG_BNDS, YLCPG_OPTS, YLCPG_MISC, YLMF_PHYS_OUT, YLCPG_DYN0, &
                    & YLMF_PHYS_SURF, YLVARS, YLCFU, YLXFU, YLMODEL)
  
  ENDDO
  
!$OMP END DO
  
!$OMP END PARALLEL
  
  ENDIF

  IF (LHOOK) CALL DR_HOOK('WRAP_CPG_DIA_FLU:PARALLEL',1,ZHOOK_HANDLE_1)

ENDDO

IF (LLDIFF) THEN
  CLFILE = TRIM (CLCASEREF)//"/YDXFU.OUT"//TRIM (CLPROC)
  OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
  CALL LOAD (77, YLXFU_REF)
  CLOSE (77)
  
  CALL YLXFU_REF%DIFF (YLXFU)
  
  CLFILE = TRIM (CLCASEREF)//"/YDCFU.OUT"//TRIM (CLPROC)
  OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='OLD')
  CALL LOAD (77, YLCFU_REF)
  CLOSE (77)
  
  CALL YLCFU_REF%DIFF (YLCFU)
ENDIF

IF (TRIM (CLOUT) /= '') THEN
  CLFILE = TRIM (CLOUT)//"/YDXFU.OUT"//TRIM (CLPROC)
  OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='NEW')
  CALL SAVE (77, YLXFU_REF)
  CLOSE (77)
  
  CLFILE = TRIM (CLOUT)//"/YDCFU.OUT"//TRIM (CLPROC)
  OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED', STATUS='NEW')
  CALL SAVE (77, YLCFU_REF)
  CLOSE (77)
ENDIF

IF (LHOOK) CALL DR_HOOK('WRAP_CPG_DIA_FLU',1,ZHOOK_HANDLE)

END PROGRAM

