MODULE YOECUMF2

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

!     ----------------------------------------------------------------------
!*    ** *YOECUMF2* - PARAMETERS FOR NEW LINEARIZED CUMULUS MASS-FLUX SCHEME
!     ----------------------------------------------------------------------

TYPE :: TECUMF2
REAL(KIND=JPRB) :: ENTRORG2
REAL(KIND=JPRB) :: DETRPEN2
REAL(KIND=JPRB) :: ENTSHALP2
REAL(KIND=JPRB) :: ENTSTPC12
REAL(KIND=JPRB) :: ENTSTPC22
REAL(KIND=JPRB) :: ENTRDD2
REAL(KIND=JPRB) :: RMFCMIN2
REAL(KIND=JPRB) :: RMFDEPS2
REAL(KIND=JPRB) :: RDEPTHS2
REAL(KIND=JPRB) :: RPRCON2
REAL(KIND=JPRB) :: RTAU2
REAL(KIND=JPRB) :: RCPECONS2
REAL(KIND=JPRB) :: RCUCOV2
REAL(KIND=JPRB) :: RTAUMEL2
REAL(KIND=JPRB) :: RUVPER2
REAL(KIND=JPRB) :: RMFSOLCT2
REAL(KIND=JPRB) :: RMFSOLTQ2
REAL(KIND=JPRB) :: RMFSOLUV2
REAL(KIND=JPRB) :: RMFSOLRHS2
REAL(KIND=JPRB) :: RMFCFL2
REAL(KIND=JPRB) :: RMFLIA2
REAL(KIND=JPRB) :: RCAPDCYCL2
REAL(KIND=JPRB) :: RTAU02

LOGICAL :: LMFMID2
LOGICAL :: LMFDD2
LOGICAL :: LMFDUDV2
LOGICAL :: LMFUVDIS2
LOGICAL :: LMFWETB2
LOGICAL :: LMFGLAC2

INTEGER(KIND=JPIM) :: NJKT12, NJKT22, NJKT32
!----------------------------------------------------------------------------
CONTAINS
   
END TYPE TECUMF2
!============================================================================

!! TYPE(TECUMF2), POINTER :: YRECUMF2 => NULL()

!*    ** *YOECUMF2* - PARAMETERS FOR NEW LINEARIZED CUMULUS MASS-FLUX SCHEME

!     P.LOPEZ                       E. C. M. W. F.      21/8/2006
!     Inspired from M.TIEDTKE       E. C. M. W. F.      18/1/89

!     NAME      TYPE      PURPOSE
!     ----      ----      -------

!     LMFMID2    LOGICAL  TRUE IF MIDLEVEL    CONVECTION IS SWITCHED ON
!     LMFDD2     LOGICAL  TRUE IF CUMULUS DOWNDRAFT      IS SWITCHED ON
!     LMFDUDV2   LOGICAL  TRUE IF CUMULUS FRICTION       IS SWITCHED ON
!     LMFUVDIS2  LOGICAL  TRUE IF KIN.ENERGY DISSIPATION BY CUMULUS FRICTION IS SWITCHED ON
!     LMFWETB2   LOGICAL  TRUE IF WET BULB TEMPERATURE USED IN SNOW MELTING
!     LMFGLAC2   LOGICAL  TRUE IF RAIN GLACIATION CONTRIBUTION INCLUDED
!     DETRPEN2   REAL     DETRAINMENT RATE FOR PENETRATIVE CONVECTION
!     ENTSHALP2  REAL     SCALING FACTOR FOR SHALLOW CONVECTION ENTRAINMENT RATE
!     ENTRORG2   REAL     COEFFICIENT FOR ORGANIZED ENTRAINMENT DEEP CONVECTION
!     ENTSTPC12  REAL     SHALLOW ENTRAINMENT TEST PARCEL ENTRAINMENTcst 1
!     ENTSTPC22  REAL     SHALLOW ENTRAINMENT TEST PARCEL ENTRAINMENTcst 2
!     ENTRDD2    REAL     ENTRAINMENT RATE FOR CUMULUS DOWNDRAFTS
!     RMFCMIN2   REAL     MINIMUM MASSFLUX VALUE (FOR SAFETY)
!     RMFDEPS2   REAL     FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
!     RDEPTHS2   REAL     MAXIMUM ALLOWED CLOUD THICKNESS FOR SHALLOW
!     RPRCON2    REAL     COEFFICIENTS FOR DETERMINING CONVERSION
!                         FROM CLOUD WATER TO RAIN
!     RCPECONS2  REAL     COEFFICIENT FOR RAIN EVAPORATION BELOW CLOUD
!     RCUCOV2    REAL     CONVECTIVE CLOUD COVER FOR RAIN EVPORATION
!     RTAUMEL2   REAL     TIME CONSTANT FOR MELTING
!     RTAU2      REAL     ADJUSTMENT TIME SCALE IN CAPE CLOSURE
!     RMFCFL2    REAL     MULTIPLE OF CFL STABILITY CRITERIUM 
!     RMFLIA2    REAL     VALUE OF ABSOLUTE MASS FLUX LIMIT
!     RMFSOLCT2  REAL     SOLVER FOR MASSFLUX ADVECTION EQUATION FOR TRACERS
!                         0 : EXPLICIT,  0-1 : SEMI-IMPLICIT, >=1 : FULLY IMPLICIT.
!     RMFSOLUV2  REAL     SOLVER FOR MASSFLUX ADVECTION EQUATION FOR MOMENTUM
!     RMFSOLTQ2  REAL     SOLVER FOR MASSFLUX ADVECTION EQUATION FOR T AND Q
!     RMFSOLRHS2 REAL     SOLVER FOR MODEL TENDENCY IN RHS OF IMPLICIT SOLVER
!     RUVPER2    REAL     UPDRAIGHT VELOCITY PERTURBATION AT KLEV FOR IMPLICIT

!     NJKT12, NJKT22, NJKT32  INTEGER LEVEL LIMITS FOR CUBASEN2, CUDDRAFN2
!     ---------------------------------------------------------------------

CONTAINS



END MODULE YOECUMF2
