MODULE YOECUMF

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

!     ----------------------------------------------------------------
!*    ** *YOECUMF* - PARAMETERS FOR CUMULUS MASSFLUX SCHEME
!     ----------------------------------------------------------------

TYPE TECUMF
REAL(KIND=JPRB) :: ENTRORG
REAL(KIND=JPRB) :: ENTR_RH
REAL(KIND=JPRB) :: ENTSHALP
REAL(KIND=JPRB) :: ENTSTPC1
REAL(KIND=JPRB) :: ENTSTPC2
REAL(KIND=JPRB) :: ENTRDD
REAL(KIND=JPRB) :: DETRPEN
REAL(KIND=JPRB) :: RMFCFL
REAL(KIND=JPRB) :: RMFLIA
REAL(KIND=JPRB) :: RMFSOLUV
REAL(KIND=JPRB) :: RMFSOLTQ
REAL(KIND=JPRB) :: RMFSOLCT
REAL(KIND=JPRB) :: RMFSOLRHS
REAL(KIND=JPRB) :: RMFADVW
REAL(KIND=JPRB) :: RMFADVWDD
REAL(KIND=JPRB) :: RMFCMIN
REAL(KIND=JPRB) :: RMFDEPS
REAL(KIND=JPRB) :: RDEPTHS
REAL(KIND=JPRB) :: RPRCON
REAL(KIND=JPRB) :: RTAUA
REAL(KIND=JPRB) :: RCAPDCYCL
REAL(KIND=JPRB) :: RMINCAPE
REAL(KIND=JPRB) :: RCPECONS
REAL(KIND=JPRB) :: RCVRFACTOR
REAL(KIND=JPRB) :: RCUCOV
REAL(KIND=JPRB) :: RTAUMEL
REAL(KIND=JPRB) :: RHEBC
REAL(KIND=JPRB) :: RUVPER
REAL(KIND=JPRB) :: RBASE0
REAL(KIND=JPRB) :: RMINCIN

REAL(KIND=JPRB) :: RXMIN
REAL(KIND=JPRB) :: RTAULIM
REAL(KIND=JPRB) :: RTAUFAC


LOGICAL :: LMFPEN
LOGICAL :: LMFSCV
LOGICAL :: LMFMID
LOGICAL :: LMFDD
LOGICAL :: LMFDUDV
LOGICAL :: LMFDSNOW
LOGICAL :: LMFWETB
LOGICAL :: LMFGLAC
LOGICAL :: LSCVLIQ
LOGICAL :: LNEWTAU

LOGICAL :: LMFUVDIS
LOGICAL :: LMFSMOOTH
LOGICAL :: LMFWSTAR
LOGICAL :: LMFCUCA
LOGICAL :: LMFPROFP
INTEGER(KIND=JPIM) :: NJKT1, NJKT2, NJKT3, NJKT4, NJKT5, NJKT6, NJKT7, NJKT8
!----------------------------------------------------------------------------
CONTAINS
   
END TYPE TECUMF
!============================================================================

!!TYPE(TECUMF), POINTER :: YRECUMF => NULL()

!*    ** *YOECUMF* - PARAMETERS FOR CUMULUS MASSFLUX SCHEME

!     M.TIEDTKE       E. C. M. W. F.      18/1/89
!     modified: P. Bechtold 2003-2016

!     NAME      TYPE      PURPOSE
!     ----      ----      -------

!     LMFPEN    LOGICAL  TRUE IF PENETRATIVE CONVECTION IS SWITCHED ON
!     LMFSCV    LOGICAL  TRUE IF SHALLOW     CONVECTION IS SWITCHED ON
!     LMFMID    LOGICAL  TRUE IF MIDLEVEL    CONVECTION IS SWITCHED ON
!     LMFDD     LOGICAL  TRUE IF CUMULUS DOWNDRAFT      IS SWITCHED ON
!     LMFDUDV   LOGICAL  TRUE IF CUMULUS FRICTION       IS SWITCHED ON
!     LMFDSNOW  LOGICAL  TRUE IF SNOW DETRAINMENT       IS SWITCHED ON
!     LMFWETB   LOGICAL  TRUE IF WET-BULB T FOR MELTING IS SWITCHED ON
!     LMFGLAC   LOGICAL  TRUE IF GLACIATION OF RAIN IN UPDRAUGHT IS SWITCHED ON
!     LSCVLIQ   LOGICAL  TRUE IF CONDENSATION FOR SHALLOW WITH RESPECT TO LIQUID ONLY
!     LMFUVDIS  LOGICAL  TRUE IF KIN.ENERGY DISSIPATION BY CUMULUS FRICTION IS SWITCHED ON
!     LMFSMOOTH LOGICAL  TRUE IF MASS FLUXES TOP/BOTTOM SMOOTHED FOR TRACER TRANSPORT
!     LMFWSTAR  LOGICAL  TRUE IF GRANT W* CLOSURE USED FOR SHALLOW
!     LMFCUCA   LOGICAL  TRUE IF BASE MASSFLUX MODULATED BY CA OR 2D ADVECT FIELD
!     LMFPROFP  LOGICAL  TRUE IF INPUT T,Q PROFILES ARE PERTURBED
!     LNEWTAU   LOGICAL  TRUE NEW FORMULATION OF DEPENDANCE TO RESOLUTION
!     RXMIN     REAL     TUNING OF LNEWTAU FORMULATION
!     RTAULIM   REAL     TUNING OF LNEWTAU FORMULATION
!     RTAUFAC   REAL     TUNING OF LNEWTAU FORMULATION
!     ENTRORG   REAL     ENTRAINMENT RATE (POSITIVE BUOYANT CONVECTION)
!     ENTR_RH   REAL     DEPENDENCE OF THE ENTRAINMENT TO HUMIDITY
!     ENTSHALP  REAL     SHALLOW ENTRAINMENT DEFINED AS ENTSHALP*ENTRORG
!     ENTSTPC1  REAL     SHALLOW ENTRAINMENT TEST PARCEL ENTRAINMENTcst 1
!     ENTSTPC2  REAL     SHALLOW ENTRAINMENT TEST PARCEL ENTRAINMENTcst 2
!     ENTRDD    REAL     ENTRAINMENT RATE FOR CUMULUS DOWNDRAFTS
!     DETRPEN   REAL     DETRAINMENT RATE FOR PENETRATIVE CONVECTION
!     RMFCMIN   REAL     MINIMUM MASSFLUX VALUE (FOR SAFETY)
!     RMFDEPS   REAL     FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
!     RDEPTHS   REAL     MAXIMUM ALLOWED CLOUD THICKNESS FOR SHALLOW
!     RPRCON    REAL     COEFFICIENTS FOR DETERMINING CONVERSION
!                        FROM CLOUD WATER TO RAIN
!     RCPECONS  REAL     COEFFICIENT FOR RAIN EVAPORATION BELOW CLOUD
!     RCUCOV    REAL     CONVECTIVE CLOUD COVER FOR RAIN EVPORATION
!     RTAUMEL   REAL     TIME CONSTANT FOR MELTING
!     RHEBC     REAL     REL. HUMIDITY BELOW CLOUD FOR WHICH EVAPORATION STARTS
!     RTAUA     REAL     OPTIMISATION FACTOR FOR ADJUSTMENT TIME SCALE
!     RCAPDCYCL REAL     DIURNAL CYCLE MODULATION FOR CAPE
!                        0:NO  1:SURFACE SENS HEAT FLUX 2: SUBCLOUD CAPE
!     RMINCAPE  REAL     FRACTION OF CAPE THAT IS ALWAYS ADJUSTED
!     RMFCFL    REAL     MULTIPLE OF CFL STABILITY CRITERIUM 
!     RMFLIA    REAL     VALUE OF ABSOLUT MASS FLUX LIMIT
!     RMFSOLCT  REAL     SOLVER FOR MASSFLUX ADVECTION EQUATION FOR TRACERS
!                        0 : EXPLICIT  0-1 : SEMI-IMPLICIT >=1 : FULLY IMPLICIT
!     RMFSOLUV  REAL     SOLVER FOR MASSFLUX ADVECTION EQUATION FOR MOMENTUM
!     RMFSOLTQ  REAL     SOLVER FOR MASSFLUX ADVECTION EQUATION FOR T AND Q
!     RMFSOLRHS REAL     INCLUDE (1) OR NOT (0) MODEL TENDENCY AT RHS OF IMPLICIT SOLVER
!     RMFADVW   REAL     FRACTION OF SUBSIDENCE FROM CUMULUS TO BE DONE BY DYNAMICS
!     RMFADVWDD REAL     FRACTION OF DDMASS FLUX USED IN DYNAMICS/DIVERGENCE IF RMFADVW>0
!     RUVPER    REAL     UPDRAIGHT VELOCITY PERTURBATION AT KLEV FOR IMPLICIT
!     NJKT1, NJKT2, NJKT3-6 INTEGER  LEVEL LIMITS FOR CUBASEN/CUDDR, DIAGNOSTICS
!     RCVRFACTOR REAL    KESSLER FACTOR=5.09E-3 FOR EVAPORATION OF CONVECTIVE RAIN  (KESSLER,1969)
!     RBASE0    REAL     CLOUD BASE HEIGHT LIMIT FOR WHEN TO USE BITMAP IN POST PROCESSING
!     RMINCIN   REAL     MINIMUMB CONVECTIVE INHIBITION VALULE FOR BITMAP IN POST PROCESSING
!     ----------------------------------------------------------------

CONTAINS



END MODULE YOECUMF
