MODULE YOEGWD

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!*    ** *YOEGWD* - PARAMETERS FOR GRAVITY WAVE DRAG CALCULATIONS
!     -----------------------------------------------------------------

TYPE :: TEGWD
INTEGER(KIND=JPIM) :: NKTOPG
INTEGER(KIND=JPIM) :: NGWDLIM
INTEGER(KIND=JPIM) :: NGWDTOP
INTEGER(KIND=JPIM) :: NDIFF_STRATO
REAL(KIND=JPRB) :: GFRCRIT
REAL(KIND=JPRB) :: GRCRIT
REAL(KIND=JPRB) :: GKDRAG
REAL(KIND=JPRB) :: GKWAKE
REAL(KIND=JPRB) :: GSSEC
REAL(KIND=JPRB) :: GTSEC
REAL(KIND=JPRB) :: GVSEC
REAL(KIND=JPRB) :: GTENLIM
REAL(KIND=JPRB) :: GRFPLM
LOGICAL         :: LRDIFF_STRATO
LOGICAL         :: LDIAG_STRATO
!---------------------------------------------------------------------
CONTAINS
   
END TYPE TEGWD
!=====================================================================

!!TYPE(TEGWD), POINTER :: YREGWD => NULL()

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     M. J. MILLER          E.C.M.W.F.      89/12/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : ---------------------------------------------------

! GFRCRIT: CRITICAL FROUDE NUMBER
! GRCRIT : CRITICAL RICHARDSON NUMBER FOR ONSET OF WAVE TURBULENCE.
! GKDRAG : DRAG CONSTANT (PROPORTIONAL TO WAVENUMBER)
! GKWAKE : DRAG COEFFICIENT FOR LOWLEVEL WAKE DRAG
! NKTOPG : NUMBER OF TOPMOST LAYER USED TO DEFINE LOW-LEVEL FLOW
! NGWDLIM: VERTICAL LEVEL ABOVE WHICH THE WIND TENDENCIES WILL BE LIMITED 
!          TO GTENLIM
! GTENLIM: LIMITER FOR WIND TENDENCIES IN THE STRATOSPHERE AND MESOSPHERE
! GRFPLM : PRESUURE LIMIT FOR RAYLEIGH FRICTION
! NGWDTOP: INDEX FOR GRFPLM
! LRDIFF_STRATO: IF TRUE REDUCED VERTICAL DIFFUSION IN STRATOSPHERE
! NDIFF_STRATO: TYPE OF REDUCED VERTICAL DIFFUSION IN STRATOSPHERE
! LDIAG_STRATO:  IF TRUE STORE GRAVITY-WAVE MOMENTUM FLUXES


!*    SECURITY PARAMETERS.
!     --------------------

! GSSEC  : TO SECURE STABILITY.
! GTSEC  : TO SECURE THE STRESS CALCULATION.
! GVSEC  : TO SECURE THE PROJECTION CALCULATION.
!     -----------------------------------------------------------------
 
!---------------------------------------------------------------------

CONTAINS 
  


END MODULE YOEGWD
