MODULE YOMHOOK

USE PARKIND1, ONLY : JPRB, JPIM
IMPLICIT NONE

LOGICAL :: LHOOK = .FALSE.

CONTAINS

SUBROUTINE DR_HOOK (CDNAME, KPART, PHOOK_HANDLE)

CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM) :: KPART
REAL (KIND=JPRB) :: PHOOK_HANDLE

END SUBROUTINE

END MODULE
