MODULE YOMMCC

USE PARKIND1  ,ONLY : JPRD, JPIM     ,JPRB
USE CPLNG_TYPES_MOD , ONLY : CPLNG_FLD_TYPE

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------

!*    KEYS FOR CLIMATE VERSION

! Coupling

! LCURR  = .T.   ===> OCEAN CURRENTS IN THE COMPUTATION OF WIND STRESS
!        = .F.   ===> NO OCEAN CURRENTS IN THE COMPUTATION OF WIND STRESS
! LGELATO= .T.   ===> NECESSARY FLUXES SENT TO GELATO
!          .F.   ===> NO FLUXES SENT TO GELATO
! LMCC01_MSE = .T.   ===> THE CLIM.FIELD(S) ARE READ IN LBC FILE AND USED IN SURFEX
! LMCC01 = .T.   ===> THE BOUNDARY CONDITIONS ARE READ IN CLIMATOLOGY FILES
!        = .F.   ===> THEY ARE READ IN THE HISTORY FILE
! LMCC02 = .T.   ===> THE SEA-ICE IS CONSIDERED AS LAND
!        = .F.   ===> THE SEA-ICE IS CONSIDERED AS OCEAN
! LMCC03 = .T.   ===> THE SST IS GIVEN BY THE COUPLER (ARPEGE VERSION)
!        = .F.   ===> THE SST IS GIVEN BY THE HIST. /BY THE CLIM. (LMCC01)
! LMCC04 = .T.   ===> OCEAN COUPLING ACTIVE IN ECMWF ROUTINES
!        = .F.   ===> NO ECMWF OCEAN COUPLING
! LMCC05 = .T.   ===> IFS VERSION OF SST COUPLING (COM SCHEME)
!        = .F.   ===> NO IFS COUPLING
! LMCC06 = .T.   ===> IFS VERSION OF SST COUPLING (TKE SCHEME)
!        = .F.   ===> NO IFS COUPLING
! LNEMOCOUP= .T. ===> SINGLE EXECUTABLE COUPLING TO NEMO
!          = .F. ===> NO SINGLE EXECUTABLE COUPLING TO NEMO
! LNEMOSSTFREEZ = .T. ===> SET SST TO FREEZING IF CI<=RCIMIN
!               = .F. ===> KEEP NEMO SST IF CI<=RCIMIN 
! LNEMOGRIBFLDS = .T. ===> GET DATA FROM NEMO TO WRITE IN GRIB
!               = .F. ===> DONT GET DATA FROM NEMO TO WRITE IN GRIB
! LNEMOFLUXNC = .T. ===> OUTPUT FLUXES FOR NEMO COUPLING IN NETCDF
!             = .F. ===> DO NOT OUTPUT FLUXES FOR NEMO COUPLING IN NETCDF
! LNEMO1WAY = .T. ===> 1WAY (IFS TO NEMO) COUPLING 
!           = .F. ===> 2WAY IFS TO NEMO AND NEMO TO IFS COUPLING
! LNEMOIFSLOG = .T. ===> NEMO LOG OUTPUT IN IFS NODE.???_?? FILES
!             = .F. ===> NORMAL NEMO LOG OUTPUT
! LNEMOLIMGET  = .T. ! Get new fields LIM
! LNEMOLIMPUT  = .T. ! Put new fields LIM
! LNEMOLIMALB  = .T. ! Use albedo from LIM
! LNEMOLIMTEMP = .F. ! Use ice temp from LIM
! LNEMOLIMTLVL = .F. ! Receive temp levels from LIM
! LNEMOLIMTHK  = .T. ! Use ice and snow thickness
! LMULTIYR     = .T. ! Using multiyear set up - switch needed for pp of chunks
!
! NOACOMM        ===> METHOD OF OASIS COMMUNICATION (1=FORTRAN PIPES, 2=C PIPES, 3=SVIPC)
! LMCCEC = .T.   ===> BOUNDARY CONDITIONS UPDATED BY ECMWF ROUTINES
!        = .F.   ===> THEY ARE NOT UPDATED
! LMCCIEC= .T.   ===> THE BOUNDARY CONDITIONS (SST) ARE INTERPOLATED IN TIME (DEFAULT) CLIMATOLOGY FILES
!        = .F.   ===> THEY ARE NOT INTERPOLATED
! LMCC_COMPO= .T.   ===> THE BOUNDARY CONDITIONS FOR COMPOSITION FLUXES ARE UPDATED (24h) DURING MODEL RUN  CLIMATOLOGY FILES
!        = .F.   ===> ARE NOT UPDATED
! LMCCIEC_COMPO= .T.   ===> THE BOUNDARY CONDITIONS FOR COMPOSITION FLUXES ARE INTERPOLATED IN TIME ( NOT DEFAULT) 
!                            CLIMATOLOGY FILES
!        = .F.   ===> THEY ARE NOT INTERPOLATED
! LMCCICEIC= .T. ===> ICE INITIAL CONDITIONS SENT TO COUPLER AT STARTUP
!           =.F  ===> NO OUTPUT OF ICE
! NCLIMTOT       ===> TOTAL NUMBER OF FIELDS TO BE UPDATED IN TIME
! NCLIMR         ===> NUMBER OF UPDATING FIELDS TO BE READ FROM FILE (OTHERS COME FROM OASIS COUPLER)
! NCLIGC         ===> GRIB CODES OF THE FIELDS TO BE TIME UPDATED
! NCLIAER        ===> GRIB CODES OF CLIM.AEROSOL FIELDS TO BE TIME UPDATED
! NDIFC          ===> DIFFERENCE, IN DAYS, BETWEEN CONSECUTIVE TIMES
!                     IN THE CLIMATE FILE (ONLY USED FOR LMCCIEC_COMPO=.FALSE.)
! NJDCR          ===> JULIAN DAY OF THE NEXT FIELD TO BE READ
!                     IN THE CLIMATE FILE (ONLY USED FOR LMCCIEC_COMPO=.FALSE.)
! NJDCR1         ===> JULIAN DAY OF THE NEXT FIELD TO BE READ
!                     IN THE ICMBC FILE (ONLY USED FOR LMCCIEC_COMPO=.FALSE.)
! NDIFC_COMPO          ===> DIFFERENCE, IN DAYS, BETWEEN CONSECUTIVE TIMES
!                     IN THE CLIMATE FILE (ONLY USED FOR LMCCIEC=.FALSE.)
! NJDCR_COMPO          ===> JULIAN DAY OF THE NEXT FIELD TO BE READ
!                     IN THE CLIMATE FILE (ONLY USED FOR LMCCIEC=.FALSE.)
! NJDCR1_COMPO         ===> JULIAN DAY OF THE NEXT FIELD TO BE READ
!                     IN THE ICMBC FILE (ONLY USED FOR LMCCIEC=.FALSE.)
! NP1            ===> INDEX FOR THE FIRST FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LMCCIEC=.TRUE.)
! NP2            ===> INDEX FOR THE SECOND FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LMCCIEC=.TRUE.)
! NPAER_1        ===> INDEX FOR THE FIRST FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LEAERDIU=.TRUE.)
! NPAER_2        ===> INDEX FOR THE SECOND FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LEAERDIU=.TRUE.)
! NPCOMPO_1        ===> INDEX FOR THE SECOND FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LMCC_COMPO =.TRUE.) ! naj 
! NPCOMPO_2        ===> INDEX FOR THE FIRST FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LECO2DIU=.TRUE.)
! NPCO2_1        ===> INDEX FOR THE FIRST FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LECO2DIU=.TRUE.)
! NPCO2_2        ===> INDEX FOR THE SECOND FILE IN TIME INTERPOLATION
!                     (ONLY USED FOR LECO2DIU=.TRUE.)
! NUNITC         ===> PBOPEN UNIT FOR CLIMATE FILE
! NUNITCM        ===> PBOPEN UNIT FOR CLIMATE FILE FOR COMPO
! NUNITC1        ===> PBOPEN UNIT FOR OCEAN BIAS CORRECTION FILE
! CLIMR          ===> HOLDS THE LAST CLIMATE FILES READ (ONLY USED FOR
!                     LMCCEC=.TRUE. .AND. LMCC04=.FALSE.)
! ZLAKE          ===> HOLDS THE LAST LAKE FILES READ (
!                     (ONLY USED FOR LEOCLAKE=.TRUE. )
! OCEANBC        ===> HOLDS THE LAST OCEAN BC FILES READ 
!                     (ONLY USED FOR LMCCEC=.TRUE. .AND. LMCC04=.FALSE.)
! CLIMRAER       ===> HOLDS THE LAST NBF AER FILES READ 
!                     (ONLY USED FOR LEAERDIU=.TRUE.)
! CLIMRCOMPO       ===> HOLDS THE LAST NBF COMPO FILES READ 
!                     (ONLY USED FOR LMCC_COMPO =.TRUE.) ! naj 
! CLIMRCO2       ===> HOLDS THE LAST NBF CO2 FILES READ 
!                     (ONLY USED FOR LECO2DIU=.TRUE.)
! NFRCPL         ===> COUPLING FREQUENCY
! NSSTICEOP      ===> INDEX FOR SST TREATMENT IN POINTS CONTAINING SEA ICE
!
! LNEMOPARTCOUP  ===> NEMO PARTIAL COUPLING
! LNEMOPARTMASK  ===> NEMO PARTIAL COUPLING MASK
! RNPARTRAMPSTART===> START DAY FOR TRANSITION TO FULL COUPLING
! RNPARTRAMPLEN  ===> LENGTH OF TRANSTION TO FULL COUPLING
! RNPARTLAT      ===> TROPICAL LATITUDE BAND WITH FULL COUPLING IF MASK ACTIVE
! RNPARTLATSPREAD===> MASK TRANSITION ZONE IN DEGREES FOR MASK
! PARTSST0       ===> INITIAL DIFFENCE IN SST
! PARTMASK       ===> MASK TO APPLY THE PARTIAL COUPLING (0 TO 1)
!
! LNEMOGRIB3D    ===> ACTIVATE INTERPOLATION OF 3D OCEAN FIELDS TO ATM GRID
! NNEMO3DLEVS    ===> NUMBER OF NEMO LEVELS

 TYPE :: TMCC
 INTEGER(KIND=JPIM) :: N923
 INTEGER(KIND=JPIM) :: NCLIMTOT
 INTEGER(KIND=JPIM) :: NCLIMR
 INTEGER(KIND=JPIM) :: NCLIGC(19)
 INTEGER(KIND=JPIM) :: NCLIGC_COMPO(150)
 ! pointer to YSD SD_VF array for input field 
 INTEGER(KIND=JPIM) :: NYSDMP_COMPO(150)
 INTEGER(KIND=JPIM) :: NCLIMR_COMPO
 INTEGER(KIND=JPIM) :: NCLIAER(16)
 INTEGER(KIND=JPIM) :: NDIFC
 INTEGER(KIND=JPIM) :: NJDCR
 INTEGER(KIND=JPIM) :: NJDCR1
 INTEGER(KIND=JPIM) :: NDIFC_COMPO
 INTEGER(KIND=JPIM) :: NJDCR_COMPO
 INTEGER(KIND=JPIM) :: NJDCR1_COMPO
 INTEGER(KIND=JPIM) :: NP1
 INTEGER(KIND=JPIM) :: NP2
 INTEGER(KIND=JPIM) :: NPCO2_1, NPCO2_2
 INTEGER(KIND=JPIM) :: NPAER_1, NPAER_2
 INTEGER(KIND=JPIM) :: NPCOMPO_1, NPCOMPO_2
 INTEGER(KIND=JPIM) :: NUNITC
 INTEGER(KIND=JPIM) :: NUNITC1
 INTEGER(KIND=JPIM) :: NUNITCM
 INTEGER(KIND=JPIM) :: NOACOMM
 INTEGER(KIND=JPIM) :: NSSTICEOP
 REAL(KIND=JPRB),ALLOCATABLE:: CLIMRCO2(:,:,:),CLIMRAER(:,:,:),CLIMRCOMPO(:,:,:),ZLAKE(:,:,:),OCEANBC(:,:)

 REAL(KIND=JPRD), ALLOCATABLE :: CLIMR(:,:,:)

 LOGICAL :: LCURR
 LOGICAL :: LGELATO
 LOGICAL :: LMCC01_MSE
 LOGICAL :: LMCC01
 LOGICAL :: LMCC02
 LOGICAL :: LMCC03
 LOGICAL :: LMCC04
 LOGICAL :: LMCC05
 LOGICAL :: LMCC06
 LOGICAL :: LMCCEC
 LOGICAL :: LMCCIEC
 LOGICAL :: LMCCIEC_COMPO
 LOGICAL :: LMCCICEIC
 LOGICAL :: LMCCDYNSEAICE
 LOGICAL :: LNEMOCOUP
 LOGICAL :: LNEMOFLUXNC
 LOGICAL :: LNEMO1WAY
 LOGICAL :: LNEMOIFSLOG
 LOGICAL :: LNEMOSSTFREEZ
 LOGICAL :: LNEMOGRIBFLDS
 LOGICAL :: LNEMOGRIBMASK
 LOGICAL :: LMULTIYR
 LOGICAL :: LMCC_COMPO
 INTEGER(KIND=JPIM) :: NFRCPL

 !Logical switches for NEMO-LIM
 LOGICAL :: LNEMOLIMGET = .TRUE.   ! Get new fields
 LOGICAL :: LNEMOLIMPUT = .TRUE.   ! Put new fields
 LOGICAL :: LNEMOLIMALB = .FALSE.  ! Use albedo from LIM
 LOGICAL :: LNEMOLIMTEMP = .FALSE. ! Use ice temp from LIM
 LOGICAL :: LNEMOLIMTLVL = .FALSE. ! Receive ice temp levels from LIM
 LOGICAL :: LNEMOLIMTHK = .FALSE.  ! Use ice and snow thickness
 LOGICAL :: LNEMOSICOUP = .FALSE.  ! Strongly couple LIM surface temperature
 !
 LOGICAL :: LNEMOATMFLDS = .TRUE.  ! Pass additional atmospheric fields to nemo
 LOGICAL :: LNEMOOCEICEMIX = .FALSE. ! Use Mixture of ice and oce for qns and qs.
 LOGICAL :: LNEMOQNSICEFILT = .FALSE.! Apply temporal filter on dqns_ice in NEMO
 LOGICAL :: LNEMOACCUMFLUX = .TRUE. ! Accumulate fluxes

 ! Ocean 3D output on atmosphere grid variables
 LOGICAL :: LNEMOGRIB3D
 INTEGER :: NNEMO3DLEVS
 REAL(KIND=JPRB), ALLOCATABLE :: RNEMOLVLS(:)
 REAL(KIND=JPRD), ALLOCATABLE :: RNEMOMASK(:,:)

 ! Partial coupling switches
 LOGICAL :: LNEMOPARTCOUP=.FALSE.
 LOGICAL :: LNEMOPARTMASK=.FALSE.
 LOGICAL :: LNEMOPARTMASKFILE=.FALSE.
 REAL(KIND=JPRB) :: RNPARTRAMPSTART=5.0_JPRB
 REAL(KIND=JPRB) :: RNPARTRAMPLEN=4.0_JPRB
 REAL(KIND=JPRB) :: RNPARTLAT=20.0_JPRB
 REAL(KIND=JPRB) :: RNPARTLATSPREAD=5.0_JPRB
 REAL(KIND=JPRB), ALLOCATABLE :: PARTSST0(:)
 REAL(KIND=JPRB), ALLOCATABLE :: PARTMASK(:)
 CHARACTER(LEN=128) :: CDNPARTMASKFILE='partialmask.grib'

! CPLNG data for coupling.
TYPE(CPLNG_FLD_TYPE), ALLOCATABLE, DIMENSION(:) :: CPLNG_FLD
LOGICAL :: CPLNG_ACTIVE = .FALSE.
INTEGER(KIND=JPIM) :: CPLNG_NUM_FIELDS = 0
INTEGER(KIND=JPIM) :: IP_A_SST = -1
INTEGER(KIND=JPIM) :: IP_A_ICE_FRAC = -1
INTEGER(KIND=JPIM) :: IP_A_CURR_U = -1
INTEGER(KIND=JPIM) :: IP_A_CURR_V = -1
INTEGER(KIND=JPIM) :: IP_A_TAUX_OCE = -1
INTEGER(KIND=JPIM) :: IP_A_TAUY_OCE = -1
INTEGER(KIND=JPIM) :: IP_A_TAUX_ICE = -1
INTEGER(KIND=JPIM) :: IP_A_TAUY_ICE = -1
INTEGER(KIND=JPIM) :: IP_A_QS_MIX = -1
INTEGER(KIND=JPIM) :: IP_A_QNS_MIX = -1
INTEGER(KIND=JPIM) :: IP_A_QS_OCE = -1
INTEGER(KIND=JPIM) :: IP_A_QNS_OCE = -1
INTEGER(KIND=JPIM) :: IP_A_QS_ICE = -1
INTEGER(KIND=JPIM) :: IP_A_QNS_ICE = -1
INTEGER(KIND=JPIM) :: IP_A_PRECIP_LIQUID = -1
INTEGER(KIND=JPIM) :: IP_A_PRECIP_SOLID = -1
INTEGER(KIND=JPIM) :: IP_A_EVAP_TOTAL = -1
INTEGER(KIND=JPIM) :: IP_A_EVAP_ICE = -1
INTEGER(KIND=JPIM) :: IP_A_DQNS_DT = -1
INTEGER(KIND=JPIM) :: IP_A_RUNOFF = -1
INTEGER(KIND=JPIM) :: IP_A_TOTAL_CC = -1
INTEGER(KIND=JPIM) :: IP_A_LOW_CC = -1
INTEGER(KIND=JPIM) :: IP_A_ICE_TEMP = -1
INTEGER(KIND=JPIM) :: IP_A_ICE_ALBEDO = -1
INTEGER(KIND=JPIM) :: IP_A_ICE_THICKNESS = -1
INTEGER(KIND=JPIM) :: IP_A_SNOW_THICKNESS = -1
INTEGER(KIND=JPIM) :: IP_A_ICE_TEMP_LVLS = -1
INTEGER(KIND=JPIM) :: IP_A_TAUX = -1
INTEGER(KIND=JPIM) :: IP_A_TAUY = -1
INTEGER(KIND=JPIM) :: IP_A_QS = -1
INTEGER(KIND=JPIM) :: IP_A_QNS = -1
INTEGER(KIND=JPIM) :: IP_A_WATER = -1
INTEGER(KIND=JPIM) :: IP_A_SST_ATM = -1
INTEGER(KIND=JPIM) :: IP_A_TSK_ATM = -1
INTEGER(KIND=JPIM) :: IP_A_IST_ATM = -1

LOGICAL :: LCOUPSIM = .FALSE.
 !---------------------------------------------------------------------
CONTAINS
  
   
  
END TYPE TMCC
!======================================================================
!!TYPE(TMCC), POINTER :: YRMCC => NULL()

CONTAINS 
  


END MODULE YOMMCC
