MODULE YOMPADDH

USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

TYPE :: TPADDH
INTEGER(KIND=JPIM),ALLOCATABLE:: NGLALIST(:,:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NGPUMASK(:,:)
END TYPE TPADDH

!!TYPE(TPADDH), POINTER :: YRPADDH => NULL()

END MODULE YOMPADDH
