MODULE YOMPHYDS

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

INTEGER(KIND=JPIM) ,PARAMETER :: JPVXPL=20
INTEGER(KIND=JPIM) ,PARAMETER :: JPVXP2L=50
INTEGER(KIND=JPIM) ,PARAMETER :: JPCXPL=50
INTEGER(KIND=JPIM) ,PARAMETER :: JPVEXTRL=99
INTEGER(KIND=JPIM) ,PARAMETER :: JPVEXTRDIL=99
INTEGER(KIND=JPIM) ,PARAMETER :: JPVXTR2L=99
INTEGER(KIND=JPIM) ,PARAMETER :: JPVPRECIPL=99
INTEGER(KIND=JPIM) ,PARAMETER :: JPVPRECIPL2=99

TYPE TPHYDS
!     ------------------------------------------------------------------

!     DESCRIPTION OF PHYSICS FIELDS

!     For description of the different extra groups 

!    C.....    - ARPEGE field name for .....
!    N.....GB  - GRIB code for .....
!    .....DF   - default value for .....

! NPPVCLIX : indicator to describe which extra model climatology fields should be set in the fields object
!            (Meteo-France and partners only)
!            0 : no extra fields
!            3 : surface geopotential, surface temperature ; and also all the fields needed to compute 
!                anomalies against climatology in the context of ISBA.
!            4 : same as (3) but with additional ISBA fields in order to enable the computation of soil wetness index.

INTEGER(KIND=JPIM) :: JPVXP=JPVXPL
INTEGER(KIND=JPIM) :: JPVXP2=JPVXP2L
INTEGER(KIND=JPIM) :: JPCXP=JPCXPL
INTEGER(KIND=JPIM) :: JPVEXTR=JPVEXTRL
INTEGER(KIND=JPIM) :: JPVEXTRDI=JPVEXTRDIL
INTEGER(KIND=JPIM) :: JPVXTR2=JPVXTR2L
INTEGER(KIND=JPIM) :: JPVPRECIP=JPVPRECIPL
INTEGER(KIND=JPIM) :: JPVPRECIP2=JPVPRECIPL2

CHARACTER (LEN = 16) ::  CEXTRP(JPCXPL,JPVXPL)
CHARACTER (LEN = 16) ::  CXTRP2(JPVXP2L)
CHARACTER (LEN = 16) ::  CVEXTRA(JPVEXTRL)
CHARACTER (LEN = 16) ::  CVEXRAD(JPVEXTRL)
CHARACTER (LEN = 16) ::  CVEXTRDI(JPVEXTRDIL)
CHARACTER (LEN = 16) ::  CVEXTR2(JPVXTR2L)
CHARACTER (LEN = 16) ::  CVPRECIP(JPVPRECIPL)
CHARACTER (LEN = 16) ::  CVPRECIP2(JPVPRECIPL2)

INTEGER(KIND=JPIM) :: NEXTRPGB(JPCXPL,JPVXPL)
INTEGER(KIND=JPIM) :: NXTRP2GB(JPVXP2L)
INTEGER(KIND=JPIM) :: NVEXTRAGB(JPVEXTRL)
INTEGER(KIND=JPIM) :: NVEXRADGB(JPVEXTRL)
INTEGER(KIND=JPIM) :: NVEXTR2GB(JPVXTR2L)
INTEGER(KIND=JPIM) :: NVEXTRDIGB(JPVEXTRDIL)
INTEGER(KIND=JPIM) :: NVPRECIPGB(JPVPRECIPL)
INTEGER(KIND=JPIM) :: NVPRECIPGB2(JPVPRECIPL2)
INTEGER(KIND=JPIM) :: NSFLUX
INTEGER(KIND=JPIM) :: NSFORC
INTEGER(KIND=JPIM) :: NPPVCLIX = 0

REAL(KIND=JPRB) :: EXTRPDF(JPCXPL,JPVXPL)
REAL(KIND=JPRB) :: XTRP2DF(JPVXP2L)
REAL(KIND=JPRB) :: VEXTRADF(JPVEXTRL)
REAL(KIND=JPRB) :: VEXRADDF(JPVEXTRL)
REAL(KIND=JPRB) :: VEXTR2DF(JPVXTR2L)
REAL(KIND=JPRB) :: VEXTRDI(JPVEXTRDIL)
REAL(KIND=JPRB) :: VPRECIP(JPVPRECIPL)
REAL(KIND=JPRB) :: VPRECIP2(JPVPRECIPL2)

LOGICAL :: LREQIN_VEXTRDI
LOGICAL :: LREQOUT_VEXTRDI

END TYPE TPHYDS

!! TYPE(TPHYDS), POINTER :: YRPHYDS => NULL()

END MODULE YOMPHYDS
