MODULE YOMPHY0

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE TPHY0
!*
!     ------------------------------------------------------------------
!     CONSTANTES PHYSIQUES REGLABLES PROPRES A L'ATMOSPHERE :
!     ------------------------------------------------------------------
!       A0ML_AU : CONSTANTE POUR LE CALCUL DE LA LONGUEUR DE MELANGE.
!               : PARAMETER FOR THE INTERACTIVE MIXING LENGTH.
!       A0ML_AT : CONSTANTE POUR LE CALCUL DE LA LONGUEUR DE MELANGE.
!               : PARAMETER FOR THE INTERACTIVE MIXING LENGTH.
!       A0ML_BU : CONSTANTE POUR LE CALCUL DE LA LONGUEUR DE MELANGE.
!               : PARAMETER FOR THE INTERACTIVE MIXING LENGTH.
!       A0ML_BT : CONSTANTE POUR LE CALCUL DE LA LONGUEUR DE MELANGE.
!               : PARAMETER FOR THE INTERACTIVE MIXING LENGTH.
!       ADISE   : CONSTANTE DE DISSIPATION PARTIE EXPLICITE (ECT).
!               : DISSIPATIVE PARAMETER FOR EXPLICIT PART.
!       ADISI   : CONSTANTE DE DISSIPATION PARTIE IMPLICITE (ECT).
!               : DISSIPATIVE PARAMETER FOR IMPLICIT PART.
!       ADJTAU  : RELAXATION TIME USED IN ADJUSTEMENT (XR scheme).
!                 TEMPS DE RELAXATION POUR AJUSTEMENT (schema XR).
!       AECLS3  : CONSTANTE POUR LE CALCUL DE ECT DANS LA CLS.
!               : PARAMETER FOR THE TKE CALCULATION IN TH PBL.
!       AECLS4  : CONSTANTE POUR LE CALCUL DE ECT DANS LA CLS.
!               : PARAMETER FOR THE TKE CALCULATION IN TH PBL.
!       AERCS1  : PREMIER COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PDAER(KLEV).
!               : FIRST COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PDAER(KLEV).
!       AERCS3  : DEUXIEME COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PDAER(KLEV).
!               : SECOND COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PDAER(KLEV).
!       AERCS5  : TROISIEME COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PDAER(KLEV).
!               : THIRD COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PDAER(KLEV).
!       AHCLPV  : HAUTEUR DE LA COUCHE LIMITE POUR LONGUEUR DE MELANGE
!                 PBL HEIGHT FOR MIXING LENGTH PROFILE COMPUTATION
!       AKN     : CONSTANTE POUR LE CALCUL DES COEFF. D'ECHANGE (ECT)
!               : PARAMETER FOR THE EXCHANGE COEFF. CALCULATION.
!       ALD     : CONSTANTE POUR LE CALCUL DE LA LONGUEUR DE DISSIPATION (ECT)
!               : PARAMETER FOR THE DISSIPATION LENGTH CALCULATION.
!       ALMAV   : LONGUEUR DE MELANGE ASYMPTOTIQUE POUR LE VENT.
!               : MOMENTUM EXCHANGE ASYMPTOTIC MIXING LENGTH.
!       ALMAVE  : MINIMUM BL89 MIXING LENGTH IN THE FREE ATMOSPHERE.
!       ALPHAE  : CONSTANTE POUR LE CALCUL DES COEFF. D'ECHANGE (ECT).
!               : PARAMETER FOR THE EXCHANGE COEFF. CALCULATION.
!       ALPHAT  : CONSTANTE POUR LE CALCUL DES COEFF. D'ECHANGE (ECT).
!               : PARAMETER FOR THE EXCHANGE COEFF. CALCULATION.
!       BEDIFV  : COEFFICIENT DE FORME POUR LE PROFIL DE DIF. VERTICALE.
!               : FORM COEFFICIENT FOR THE VERTICAL DIFFUSION PROFILE.
!       ECMNP   : EPAISSEUR CRITIQUE MINIMUM DU NUAGE PRECIPITANT.
!               : MINIMUM CRITICAL THICKNESS FOR PRECIPITATING CLOUDS.
!       ECTMIN  : VALEUR MINIMALE POUR ECT
!               : MINIMUM VALUE FOR TKE
!       ECTMAX  : VALEUR MAXIMALE POUR ECT
!               : MAXIMUM VALUE FOR TKE
!       EDB     : DETERMINE CD ET CH AU VOISINAGE DE LA NEUTRALITE.
!               : DETERMINES CD AND CH NEAR THE NEUTRAL REGIME.
!       EDC     : DETERMINE CD ET CH EN REGIME ASYMPTOTIQUE INSTABLE.
!               : DETERMINES CD AND CH IN THE ASYMPTOTIC UNST. REGIME.
!       EDD     : DETERMINE CD ET CH EN REGIME ASYMPTOTIQUE STABLE.
!               : DETERMINES CD AND CH IN THE ASYMPTOTIC STABLE REGIME.
!       EDK     : DETERMINE CD ET CH EN REGIME STABLE.
!               : DETERMINES CD AND CH IN THE STABLE REGIME.
!       EPS     : DISSIPATION PARTIE IMPLICITE PARTIE EXPLICITE (ECT).
!               : DISSIPATIVE PARAMETER
!       ETACUT  : PARAMETRE DU SCHEMA DE CONVECTION EN PENTE
!               : LIMITATION OF VORTICITY IN SHEAR-LINKED CONVECTION SCHEME
!       EVAP    : CONSTANTE D'EVAPORATION DES PRECIPITATIONS.
!               : PARAMETER FOR THE EVAPORATION OF PRECIPITATIONS.
!       FONT    : CONSTANTE DE FONTE DES PRECIPITATIONS.
!               : PARAMETER FOR THE MELTING OF PRECIPITATIONS.
!       GALP    : COEFFICIENT DE GALPERING (SCHEMA STAT. DE NUAGE).
!               : GALPERING COEFFICIENT (STATISTICAL CLOUD SCHEME).
!       GCISMIN : CISAILLEMENT MINIMAL UTILISE DANS LES CALCULS TURBULENTS.
!               : MINIMUM VALUE OF SHEAR USED IN TURBULENT COMPUTATIONS.
!       GEVAVF  : CISAILLEMENT MINIMAL UTILISE DANS LES CALCULS D'EVAPORATION (EVAporation par Vent Faible).
!       GCVHMIN : MINIMUM HEIGHT FOR THE DEEP CONVECTION CLOUD.
!               : HAUTEUR MINIMALE DU NUAGE DE CONVECTION PROFONDE.
!       GCVIMPT : IMPLICITATION FACTOR FOR CONVECTIVE TRANSPORT IN COMBINED (CV-TURB) COMPUTATION.
!                 EXPLICIT IF 0, AND FULL IMPLICIT IF 1
!               : FACTEUR D'IMPLICITATION POUR LE TRANSPORT CONVECTIF DANS LE CALCUL COMBINE (CV-TURB).
!                 EXPLICITE SI 0, ET ENTIEREMENT IMPLICITE SI 1
!       GCVOMGE : COEF FOR MODULATING ENTRAINMENT ACCORDING OMEGA.
!               : COEF DE MODULATION DE L'ENTRAINMENT SELON OMEGA.
!       GCVOMGQ : OMEGA MINIMUM VALUE FOR PDIFTQ MODIFICATION IN ACCVIMP.
!               : VALEUR MINIMALE OMEGA POUR MODIFIER PDIFTQ DANS ACCVIMP
!       GCVOMGS : OMEGA MINIMUM VALUE FOR PDIFTS MODIFICATION IN ACCVIMP.
!               : VALEUR MINIMALE OMEGA POUR MODIFIER PDIFTS DANS ACCVIMP.
!       GCVTURB : MINIMUM TURBULENCE FOR STATISTICAL CLOUD SCHEME
!                 TURBULENCE MINIMALE POUR SCHEMA STATISTIQUE DE NUAGE 
!       GCCSV   : CHOIX DU CRITERE DE STABILITE VERTICALE.
!               : VERTICAL STABILITY CRITERIA CHOICE.
!       GCVALFA : COEFFICIENT RELIANT LA FLOTTABILITE NUAGEUSE
!                 AU TAUX D'ENTRAINEMENT.
!               : COEFFICIENT TO COMPUTE ENTRAINMENT RATE FROM CLOUD BUOYANCY.
!       GCVADS  : COEFFICIENT PERMETTANT DE PASSER D'UN CALCUL D'ADIABATIQUE
!                 SATUREE EN EQUIPRESSION A UN CALCUL EN EQUIGEOPOTENTIEL.
!               : COEFFICIENT TO SWITCH FROM AN EQUIPRESSURE ADIABAT COMPUTATION
!                 TO AN EQUIGEOPOTENTIAL ONE.
!       GCVBETA : FRACTION DE LA DIVERGENCE DU FLUX DE MASSE CONVECTIF
!                 ENTRANT DANS LE DETRAINEMENT.
!               : FRACTION OF CONVECTIVE MASS FLUX DIVERGENCY
!                 USED IN DETRAINMENT COMPUTATIONS.
!       GCVMLT  : COEFFICIENT D'HYSTERESIS DE FONTE/GEL DES PRECIPITATIONS CONVECTIVES.
!               : PARAMETER FOR THE HYSTERESIS OF CONVECTIVE PRECIPITATIONS MELTING/FREEZING.
!       GCVNU   : ENTRAINEMENT UTILISE POUR LE CALCUL DE LA FRACTION DE FLOTTABILITE.
!               : ENTRAINMENT RATE TO COMPUTE DILUTE PLUME BUOYANCY.
!       GCVPSI  : COEFFICIENT ADIMENSIONNEL FAISANT
!                 PASSER D'UNE PRISE EN COMPTE LOCALE DES FLUX TURBULENTS (SI 1)
!                 A UNE PRISE EN COMPTE INTEGRALE (SI 0).
!               : ADIMENSIONAL COEFFICIENT TO GO FROM
!                 A LOCAL USE OF TURBULENT FLUXES (IF 1)
!                 TO AN INTEGRAL ONE (IF 0).
!       GCVPSIE : PRESSURE EXPONENT IN THE MULTIPLICATION FACTOR OF PQSAT IN
!                 THE NORMALIZATION INTEGRAL OF TURBULENT FLUXES, UNDER LCVLIS
!                 SWITCH (IF 0 => PQSAT IS USED, IF 1 => PQSAT*P**GCVPSIE)
!       GDDEVA  : DOWNDRAFTS: FRACTION DES PRECIPITATIONS EVAPOREES.
!               : DOWNDRAFTS: PRECIPITATIONS EVAPORATION FRACTION.
!       GDDSDE  : DOWNDRAFTS: EXPOSANT CONTROLANT LES COURANTS DESCENDANTS EN SURFACE.
!               : DOWNDRAFTS: SURFACE DESCENDING FLOW EXPONENT.
!       GPBLHK0 : COEFFICIENT KHI0 UTILISE DANS LE CALCUL DE HAUTEUR DE CLA.
!               : KHI0 COEFFICIENT FOR USE IN THE PBL HEIGHT COMPUTATION.
!       GPBLHRA : RAPPORT KHI0/KHI1 UTILISE DANS LE CALCUL DE HAUTEUR DE CLA.
!               : RATIO KHI0/KHI1 FOR USE IN THE PBL HEIGHT COMPUTATION.
!       GRCVPP  : COEFFICIENT DE REDUCTION DE CVPP (ACCOEFK).
!               : REDUCTION COEFFICIENT FOR SHALLOW-CONVECTION (ACCOEFK).
!       GRCVPP  : COEFFICIENT DE REDUCTION DE CVPP (ACCOEFK).
!               : REDUCTION COEFFICIENT FOR SHALLOW-CONVECTION (ACCOEFK).
!       GWDAMP  : COEFFICIENT DE RESONANCE POUR LE G.W.D..
!               : RESONNANCE COEFFICIENT FOR THE G.W.D..
!       GWDBC   : INVERSE DE LA HAUTEUR CRITIQUE POUR LE G.W.D..
!               : INVERSE CRITICAL HEIGHT FOR THE G.W.D..
!       GWDCCO  : COEFFICIENT DU G.W.D CONVECTIF..
!               : COEFFICIENT FOR THE CONVECTIVE G.W.D..
!       GWDCD   : COEFFICIENT DE FROTTEMENT POUR LE G.W.D. DE SURFACE.
!               : DRAG COEFFICIENT FOR FOR THE LOW LEVEL G.W.D..
!       GWDLT   : COEFFICIENT DE SOULEVEMENT AU SOL POUR LE G.W.D..
!               : SURFACE LIFT COEFF. FOR THE G.W.D..
!       GWDSE   : COEFFICIENT DE FORME DU SOL POUR LE G.W.D..
!               : ASPECT RATIO TYPE COEFF. AT THE SURF. FOR THE G.W.D..
!       GWDPROF : COEFF DEFINISSANT LA FORME DE LA MONTAGNE POUR LE G.W.D..
!               : MOUNTAIN SHAPE COEFF. FOR THE G.W.D..
!       GWDVALI : COEFF DEFINISSANT L'ISOLEMENT DES VALLEES POUR LE G.W.D..
!               : VALLEYS DECOUPLING COEFF. FOR THE G.W.D..
!       HOBST   : MULTIPLICATEUR DE L'E. T. REL. POUR OBSTACLE G.W.D..
!               : FACTOR FOR THE ST. DEV. OF OROG. FOR G.W.D. "WALL".
!       HUCOE   : PREMIER COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PHUC(KLEV).
!               : FIRST COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PHUC(KLEV).
!       HUTIL   : DEUXIEME COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PHUC(KLEV).
!               : SECOND COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PHUC(KLEV).
!       HUTIL1  : DEUXIEME COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT NOUVEAU PHUC(KLEV).
!               : SECOND COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING NEW PHUC(KLEV).
!       HUTIL2  : TROISIEME COEFF. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT NOUVEAU PHUC(KLEV).
!               : THIRD COEFFICIENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING NEW PHUC(KLEV).
!       NPCLO1  : PREMIER EXPOST. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PHUC(KLEV).
!               : FIRST EXPONENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PHUC(KLEV).
!       NPCLO2  : DEUXIEME EXPOST. DE LA FONCTION DE LA COORD. SIGMA
!                 DEFINISSANT PHUC(KLEV).
!               : SECOND EXPONENT IN THE SIGMA COORD.'S FUNCTION
!                 DEFINING PHUC(KLEV).
!       QSSC    : ECART D'ENERGIE STATIQUE SECHE AUTORISE LORS DU CALCUL
!                 DE LA NEBULOSITE PEU PROFONDE.
!                 DRY STATIC ENERGY THRESHOLD FOR SHALLOW CONVECTION COMPUTATIONS.
!       QSMIN   : RAPPORT DE MELANGE MINIMUM POUR LE SCHEMA DE NEBULOSITE STAT.
!               : MINIMUM MIXING RATIO FOR THE STATISTICAL CLOUD SCHEME
!       QSNEBC  : FACTEUR RELIANT L'EAU CONDENSEE A LA NEBULOSITE CONVECTIVE.
!               : DEFINING CONVECTIVE CLOUDINESS FROM CONDENSATED WATER.
!       QSNEBS  : FACTEUR RELIANT L'EAU CONDENSEE A LA NEBULOSITE STRATIFORME.
!               : DEFINING STRATIFORM CLOUDINESS FROM CONDENSATED WATER.
!       QSSUSC  : FACTEUR RELIANT L'EAU CONDENSEE AUX PRECIPITATIONS CONVECTIVES.
!               : DEFINING CONDENSATED WATER FROM CONVECTIVE PRECIPITATION.
!       QSSUSS  : FACTEUR RELIANT L'EAU CONDENSEE A LA SURSATURATION.
!               : DEFINING CONDENSATED WATER FROM SUPERSATURATION.
!       QSSUSV  : FACTEUR RELIANT L'EAU CONDENSEE A LA SURSATURATION.
!               : DEFINING CONDENSATED WATER FROM SUPERSATURATION.
!       QSUSXC  : QL+QI MAXIMUM A L'ECHELLE DU POINT DE GRILLE MODELE,
!                 PARTIE CONVECTION PROFONDE.
!               : MAXIMUM QL+QI AT THE GRID-POINT SCALE,
!                 DEEP CONVECTION PART.
!       QSUSXS  : QL+QI MAXIMUM A L'ECHELLE DU POINT DE GRILLE MODELE,
!                 PARTIES RESOLUE ET DE CONVECTION PEU PROFONDE.
!               : MAXIMUM QL+QI AT THE GRID-POINT SCALE,
!                 RESOLVED AND SHALLOW CONVECTION PART.
!       QSMODC  : FACTEUR DE MODULATION D'EAU CONDENSEE STRATIFORME AVEC ALTITUDE.
!                 MODULATION FACTOR FOR STRATIFORM CONDENSATED WATER WITH HEIGHT.
!       RPHI0   : REGLAGE DE REFROIDISSEMENT DANS L'INVERSION POUR LE
!                 CALCUL DE STRATUS BAS
!                 TUNING OF THE COOLING INSIDE AN INVERSION FOR COMPUTATION
!                 OF LOW-LEVEL STRATUS CLOUDINESS
!       RPHIR   : REGLAGE DE LA PROFONDEUR D'INVERSION THERMIQUE POUR LE
!                 CALCUL DE STRATUS
!                 TUNING OF THE INVERSION THICKNESS FOR COMPUTATION
!                 OF LOW-LEVEL STRATUS CLOUDINESS
!               : XU ET RANDALL CLOUDINESS COMPUTATION (ACNEBXR).
!       RKFBTAU : PARAMETER FOR THE COMPUTATION OF QC IN ACVPPKF (LCVPPKF).
!               : PARAMETRE POUR LE CALCUL DE QC DANS ACVPPKF (LCVPPKF).
!       RKFBNBX : MAXIMUM CLOUDINESS IN ACVPPKF (LCVPPKF).
!               : NEBULOSITE MAXIMALE DANS ACVPPKF (LCVPPKF).
!       QXRAL   : CALCUL DE LA NEBULOSITE XU ET RANDALL (ACNEBXR).
!               : XU ET RANDALL CLOUDINESS COMPUTATION (ACNEBXR).
!       QXRAL_ADJ : VALUE OF QXRAL TO BE USED IN ADJUSTMENT (ACNEBCOND).
!       QXRDEL  : CALCUL DE LA NEBULOSITE XU ET RANDALL (ACNEBXR).
!               : XU ET RANDALL CLOUDINESS COMPUTATION (ACNEBXR).
!       QXRHX   : CALCUL DE LA NEBULOSITE XU ET RANDALL (ACNEBXR).
!               : XU ET RANDALL CLOUDINESS COMPUTATION (ACNEBXR).
!       QXRR    : CALCUL DE LA NEBULOSITE XU ET RANDALL (ACNEBXR).
!               : XU ET RANDALL CLOUDINESS COMPUTATION (ACNEBXR).
!       QXRTGH  : CALCUL DE LA NEBULOSITE XU ET RANDALL (ACNEBXR).
!               : XU ET RANDALL CLOUDINESS COMPUTATION (ACNEBXR).
!       QXRCDIL : RELATIVE DILUTION OF STRATIFORM VS CONVECTIVE CONDENSATES
!                 (XU-RANDALL WITH LCVCSD/LREDPR)
!       TENTRX  : TAUX D'ENTRAINEMENT MAXIMUM DU NUAGE CONVECTIF.
!               : MAXIMUM CONVECTIVE UPDRAFT'S ENTRAINMENT RATE.
!       RDECRD  : DEPTH FOR COMPUTING RANDOMNESS COEFFICIENT IN OVERLAP (SHONK).
!               : PROFONDEUR POUR ETABLIRE LE COEFFICIENT DE RANDOMNESS POUR
!                 RECOUVREMENT DE NUAGES ET PLUIE (APLMPHYS).
!                 RDECRD >  0 IMPLIES USE OF THIS FIXED VALUE IN APLMPHYS,
!                             IT IS KEPT FOR BACKWARD COMPATIBILITY.
!                 RDECRD <= 0 IMPLIES USE OF VALUE DEPENDENT ON LATITUDE
!                             AND SUN DECLINATION IN APLMPHYS. ACRANEB2
!                             ALWAYS USES THIS LATTER OPTION.
!                 SHAPE OF RDECRD INSPIRED BY OREOPOULOS ET AL. 2012:
!       RDECRD1 : MINIMUM VALUE OF RDECRD                                [Pa]
!       RDECRD2 : AMPLITUDE OF RDECRD                                    [Pa]
!       RDECRD3 : RDECRD PEAKING AT LATITUDE RDECRD1 x SOLAR DECLINATION [1]
!       RDECRD4 : CHARACTERISTIC WIDTH OF RDECRD                         [rad]
!       RDECRDRED : REDUCTION FACTOR FOR DECORRELATION DEPTH IN
!                   DIAGNOSTIC CLOUD COVER                               [1]
!       REVAPN  : RATIO OF SNOW EVAPORATION WITH RESPECT TO EVAP (APLMPHYS).
!                 RAPPORT DE EVAP POUR LA NEIGE (APLMPHYS).
!       RGELSFON: COEFFICIENT POUR LE GEL/FONTE (ACEVMEL).
!                 COEFFICIENT FOR FREEZING/MELTING (ACEVMEL).
!       RCIN    : MODULATION DANS LE CALCUL DU PROFIL NUAGEUX CONVECTIF
!               : MODULATION IN THE CONVECTIVE CLOUD PROFILE COMPUTATION
!       RCVEVAP : FACTEUR DE MODULATION DE L'EVAPORATION CONVECTIVE SOUS-NUAGEUSE
!               : MODULATION FACTOR FOR CONVECTIVE EVAPORATION
!       RDTFAC  : FACTEUR MULTIPLICATIF DE "RDT" DANS LA FONCTION "FONICE".
!               : MODULATION FACTOR OF "RDT" IN "FONICE" FUNCTION.
!       REVGSL  : RAPPORT DES VITESSES D'EVAP. DES PRECIP. "GLACE/LIQ.".
!               : RATIO OF THE SPEED OF EVAP. OF PRECIP. "ICE/WATER".
!       RFLCHCE : COEFFICIENT DE PONDERATION DE "CE" PAR "CH" DANS "ECUME".
!               : WEIGHTING COEFFICIENT OF "CE" BY "CH" IN "ECUME".
!       RICRLM  : NOMBRE DE RICHARDSON CRITIQUE POUR LONGUEUR DE MELANGE.
!               : CRITICAL RICHARDSON NUMBER FOR MIXING LENGTH.
!       RMULACVG: MODULATION DE LA FERMETURE EN CVGQ.
!               : MODULATION OF THE CVGQ CLOSURE.
!       RRGAMMA : EXPOSANT DANS LE CALCUL DE "RAFALE HUMIDE".
!                 EXPONENT IN "MOIST GUSTINESS" COMPUTATION.
!       RRSCALE : TAUX DE PRECIPITATION CARACTERISTIQUE DANS LE CALCUL DE "RAFALE HUMIDE".
!                 SCALING RAINFALL RATE IN "MOIST GUSTINESS" COMPUTATION.
!       RTCAPE  : TEMPS CARACTERISTIQUE POUR "CONSOMMER" LA CAPE.
!                 CHARACTERISTICS TIME TO DECREASE THE CAPE CLOSURE.
!       SCO     : SEUIL EN DESSOUS DUQUEL LES PRECIPITATIONS CONVECTIVES
!                 NE SONT PAS PRISES EN COMPTE (SCHEMA STATISTIQUE DE NUAGES)
!               : THRESHOLD FOR THE CONVECTIVE PRECIPITATION (STATISTICAL
!                 CLOUD SCHEME)
!       SENSL   : COEFFICIENT DE SENSIBILITE DE LA LONGUEUR DE MELANGE.
!               : SENSITIVITY TO MIXING LENGTH (STAT. CLOUD SCHEME).
!       SNNBCO  : VALEUR MINIMALE DE LA NEBULOSITE CONVECTIVE.
!               : MINIMUM VALUE OF CONVECTIVE CLOUDINESS.
!       SPNBCO  : PENTE "NEBULOSITE CONV./PRECIPITATION CONV.".
!               : SLOPE "CONV. CLOUDINESS/CONV. PRECIPITATION".
!       SXNBCO  : VALEUR MAXIMALE DE LA NEBULOSITE CONVECTIVE
!               : MAXIMUM VALUE OF CONVECTIVE CLOUDINESS.
!       TCA     : CONSTANTE D'ACCRETION.
!               : ACCRETION CONSTANT (STAT. CLOUD SCHEME).
!       TCT     : AUTOCONV. DES GOUTTELETTES NUAGEUSES EN PRECIP..
!               : DROPLET SELFCONVERSION (STAT. CLOUD SCHEME).
!       TCW     : CONSTANTE DE LIMITATION DE LA CONVERSION DE L'EAU
!                 LIQUIDE NUAGEUSE EN PRECIPITATIONS.
!               : LIMITATION OF LIQUID WATER CONVERSION (STAT. CLOUD
!                 SCHEME).
!       TENTR   : TAUX D'ENTRAINEMENT DU NUAGE CONVECTIF.
!               : CONVECTIVE UPDRAFT'S ENTRAINMENT RATE.
!       TENTRX  : TAUX D'ENTRAINEMENT MAXIMUM DU NUAGE CONVECTIF.
!               : MAXIMUM CONVECTIVE UPDRAFT'S ENTRAINMENT RATE.
!       TDDGP   : Parametrisation grad p horizontal dans le downdraught
!                 (Kershaw & Gregory)
!                 Downdraught Horizontal Grad p  effect coefficient
!       TUDGP   : Parametrisation du grad p horizontal dans l'updraught
!                 (Kershaw & Gregory)
!                 Updraught Horizontal Grad p  effect coefficient
!       TURB    : TURBULENCE RESIDUELLE.
!               : RESIDUAL TURBULENCE (STAT. CLOUD SCHEME).
!       TVF     : VITESSE DE PRECIPITATION DE L'EAU SOLIDE NUAGEUSE.
!               : SOLID PRECIPITATION SPEED (STAT. CLOUD SCHEME).
!       TYM(5)  : TABLEAU DES COEFFICIENTS DU MODELE DE NIVEAU 2.5
!                 DE YAMADA ET MELLOR (SCHEMA STATISTIQUE DE NUAGES).
!               : YAMADA AND MELLOR COEFFICIENTS FOR THE LEVEL 2.5
!                 SCHEME (STAT. CLOUD SCHEME).
!       UHDIFV  : INVERSE DE L'ECHELLE DE DECROISSANCE VERTIC. DE ALMAV.
!               : INVERSE SCALE HEIGHT FOR THE DECREASE OF ALMAV.
!       USDMLT  : INVERSE DE L'ECHELLE DE FUSION DES PRECIP. CONVEC..
!               : INVERSE SCALE OF THE MELTING DEPTH OF CONVEC. PRECIP..
!       USUPRC  : INVERSE DES PRECIPITATIONS CRITIQUES POUR L'INTERCETION
!               : INVERSE CRITICAL RAINFALL FOR VEGETATION INTERCEPTION
!       USURIC  : INVERSE DU NOMBRE DE RICHARDSON CRITIQUE
!               : INVERSE CRITICAL RICHARDSON NUMBER
!       USURID  : INVERSE DU NOMBRE DE RICHARDSON DE TRANSITION POUR LE CALCUL DE L'ORDRE DE CONVERGENCE
!                 DU NOMBRE DE RICHARDSON VERS LE NOMBRE DE RICHARDSON CRITIQUE.
!               : INVERSE TRANSITION RICHARDSON NUMBER TO COMPUTE THE CONVERGENCE ORDER
!                 OF THE RICHARDSON NUMBER TO THE CRITICAL RICHARDSON NUMBER.
!       USURICE : EXPOSANT DE L'ALTITUDE INTERVENANT DANS LE CALCUL
!                 DU NOMBRE DE RICHARDSON CRITIQUE.
!               : HEIGHT EXPONENT IN RICHARDSON NUMBER COMPUTATION.
!       USURICL : COEFFICIENT MULTIPLICATEUR INTERVENANT DANS LE CALCUL
!                 DU NOMBRE DE RICHARDSON CRITIQUE EN FONCTION DE L'ALTITUDE.
!               : COEFFICIENT RELATING RICHARDSON NUMBER COMPUTATION TO HEIGHT.
!       USURID  : INVERSE DU NOMBRE DE RICHARDSON DE TRANSITION POUR LE CALCUL DE L'ORDRE DE CONVERGENCE
!                 DU NOMBRE DE RICHARDSON VERS LE NOMBRE DE RICHARDSON CRITIQUE.
!               : INVERSE TRANSITION RICHARDSON NUMBER TO COMPUTE THE CONVERGENCE ORDER
!                 OF THE RICHARDSON NUMBER TO THE CRITICAL RICHARDSON NUMBER.
!       USURIDE : EXPOSANT DANS LE CALCUL DU NOMBRE DE RICHARDSON CRITIQUE LOCAL.
!                 EXPONENT IN THE COMPUTATION OF THE LOCAL CRITICAL RICHARDSON NUMBER.
!       UTILGUST: VITESSE CARACTERISTIQUE DANS LE CALCUL DE "RAFALE HUMIDE".
!                 CHARACTERISTIC SPEED IN "MOIST GUSTINESS" COMPUTATION.
!       VCHRNK  : CONSTANTE DE CHARNOCK.
!               : CHARNOCK'S CONSTANT.
!       VKARMN  : CONSTANTE DE KARMAN.
!               : KARMAN'S CONSTANT.
!       VZ0CM   : LONGUEUR DE RUGOSITE (NEUTRE) MINIMALE SUR MER.
!               : (NEUTRAL) MINIMUM ROUGHNESS LENGTH OVER THE OCEAN.
!       VZIUSTAR0 : VITESSE DE RUGOSITE INVERSE DE NORMALISATION.
!                 : SCALING INVERSE ROUGHNESS VELOCITY.
!       XBLM    : COEFFICIENT POUR LONGUEUR DE MELANGE.
!               : COEFFICIENT FOR MIXING LENGTH.
!       XKLM    : COEFFICIENT POUR LONGUEUR DE MELANGE (0<XKLM<1).
!               : COEFFICIENT FOR MIXING LENGTH (0<XKLM<1).
!       XMAXLM  : HAUTEUR MAXI DE LA CLP (POUR LONGUEUR DE MELANGE).
!               : MAX HEIGHT OF THE PBL (FOR MIXING LENGTH).
!       XMINLM  : HAUTEUR MINI DE LA CLP (POUR LONGUEUR DE MELANGE).
!               : MIN HEIGHT OF THE PBL (FOR MIXING LENGTH).
!       XNBMAX  : NEBULOSITE MAXIMUM PAR COUCHE.
!               : MAXIMUM CLOUDINESS IN A LAYER.
!       XWSALM  : CONSTANTE 1 DU SCHEMA TROEN-MAHRT (POUR LONGUEUR DE MELANGE).
!               : CONSTANT 1 FOR TROEN-MAHRT SCHEME (FOR MIXING LENGTH).
!       XWSBLM  : CONSTANTE 2 DU SCHEMA TROEN-MAHRT (POUR LONGUEUR DE MELANGE).
!               : CONSTANT 2 FOR TROEN-MAHRT SCHEME (FOR MIXING LENGTH).
!       WMXOV   : POID DANS LE CALCUL DU RECOUVREMENT NUAGEUX ACNPART.
!               : WEIGHT OF MAXIMUM CLOUD OVERLAP COMPUTATION IN ACNPART.

!*   Variables pour la microphysique dite de Lopez
! ------------------------------------------------------------------
!    RAUTEFR  : EFFICIENCY FOR AUTOCONVERSION OF WATER->RAIN.
!    RRAUTCS  : RATIO (CONV/STRAT) OF EFFICIENCY FOR AUTOCONVERSION OF W->R
!    RAUTEFS  : EFFICIENCY FOR AUTOCONVERSION OF ICE->SNOW.
!    RAUTSBET : "BETA" EFFICIENCY PARAMETER FOR AUTOCONV ICE->SNOW.
!    RAUTEFG  : EFFICIENCY FOR AUTOCONVERSION OF WATER->GRAUPEL.
!    REVASX   : MAXIMUM EVAPORATION RATE FOR STRATIFORM PRECIPITATION.
!    RNINTR   : INTERCEPT PARAMETER FOR RAIN.
!    RNINTS   : INTERCEPT PARAMETER FOR ICE.
!    RQLCR    : CRITICAL LIQUID WATER CONTENT FOR AUTOCONVERSION OF
!               STRATIFORM CLOUD WATER.
!    RSPCRR   : SUPERCOOLED RAIN SWITCH (1.=YES, 0.=NO)
!    RQICRMAX : MAXIMUM CRITICAL ICE CONTENT FOR AUTOCONVERSION OF
!               STRATIFORM ICE.
!    RQICRMIN : MINIMUM CRITICAL ICE CONTENT FOR AUTOCONVERSION OF
!               STRATIFORM ICE.
!    RQLCV    : CRITICAL LIQUID WATER CONTENT FOR AUTOCONVERSION OF
!               CONVECTIVE CLOUD WATER.
!    RQICVMAX : MAXIMUM CRITICAL ICE CONTENT FOR AUTOCONVERSION OF
!               CONVECTIVE CLOUD ICE.
!    RQICVMIN : MINIMUM CRITICAL ICE CONTENT FOR AUTOCONVERSION OF
!               CONVECTIVE CLOUD ICE.
!    RQICRT1  : TUNING COEFF FOR AUTOCONVERSION OF STRATIFORM ICE.
!    RQICRT2  : TUNING COEFF FOR AUTOCONVERSION OF STRATIFORM ICE.
!    RQICRSN  : MULTIPLICATIVE FACTOR OF CRITICAL ICE CONTENT FOR
!               AUTOCONVERSION OF STRATIFORM ICE OVER SNOW AND SEA ICE.
!    RQCRNS   : TUNING COEFF FOR AUTOCONVERSION NEAR THE SURFACE.
!    RACCEF   : ACCRETION EFFICIENCY.
!    RAGGEF   : AGGREGATION EFFICIENCY.
!    RRIMEF   : RIMING AND AGGREGATION EFFICIENCY.
!    RHCRIT1  : CRITICAL RELATIVE HUMIDITY FOR SMITH SCHEME (UPPER LEVELS).
!    RHCRIT2  : CRITICAL RELATIVE HUMIDITY FOR SMITH SCHEME (SURFACE).
!    RETAMIN  : MODEL ETA LEVEL WHERE CRITICAL RELATIVE HUMIDITY IS MINIMUM.
!    RFACNSM  : MULTIPLICATVE FACTOR OF SMITH CLOUDINESS COMPUTATION.
!    TFVL     : SEDIMENTATION SPEED OF CLOUD LIQUID WATER.
!    TFVI     : SEDIMENTATION SPEED OF CLOUD ICE WATER.
!    TFVR     : SEDIMENTATION SPEED OF RAIN.
!    TFVS     : SEDIMENTATION SPEED OF SNOW.
!    GRHCMOD  : MODULATION IN CRITICAL RELATIVE HUMIDITY COMPUTATION.
!    RHCEXPDX : DX-MODULATION OF CRITICAL RELATIVE HUMIDITY COMPUTATION - XU-RANDALL.

! TOUCANS / (eventually pTKE)
!    NUPTKE   : TUNABLE VALUE FOR PSEUDO TKE SCHEME FOLLOWING
!               REDELSBERGER, MAHE & CARLOTTI (2001) EQUAL TO
!               ( C_k * C_{epsilon} )^{1/4}
!    TKEMULT  : TKE enhancing factor for (TKE) mixing length computation
!    C_EPSILON: C_EPSILON COEFFICIENT IN FULL TKE FORMALISM
!    ETKE_CTHETA:C_THETA COEFFICIENT IN FULL TKE FORMALISM
!    C3TKEFREE: C_3 COEFFICIENT IN FULL TKE FORMALISM
!    ETKE_RIFC_MAF: tuning parameter for moist AF scheme
!    ETKE_RIFC: RIFC  in modified CCH02 system
!    ETKE_R   : R in modified CCH02 system
!    ETKE_OLAM: O_LAMBDA in modified CCH02 system
!    ETKE_LAM0: LAMBDA_0 in modified CCH02 system
!    ETKE_LAM1: LAMBDA_1 in modified CCH02 system
!    ETKE_LAM2: LAMBDA_2 in modified CCH02 system
!    ETKE_LAM3: LAMBDA_3 in modified CCH02 system
!    ETKE_LAM4: LAMBDA_4 in modified CCH02 system
!    ETKE_CG01: CG01-A1 term -TUNING CONSTANT FOR TOM's
!    ETKE_CG02: CG01-A2 term -TUNING CONSTANT FOR TOM's
!    ETKE_CG03: CG03-A3 term -TUNING CONSTANT FOR TOM's
!    ETKE_KA1:K^(A1) - coefficient for TOMs in TOUCANS
!    ETKE_KA2:K^(A2) - coefficient for TOMs in TOUCANS
!    ETKE_KA3:K^(A3) - coefficient for TOMs in TOUCANS
!    ETKE_BETA_EPS:parameter for too small tau_epsilon security:
!                  tau_eps=tau_eps+beta_eps.dt
!    ETKE_GAMMA_EPS:parameter for too large tau_epsilon security:
!                  tau_eps=tau_eps/(1+gamma_eps.dt.tau_eps)
!    ENT_LAMBDA: LAMBDA to compute Theta_S1 after P. Marquet (2011)
!    ETKE_GAMD:Gamma_d for prognostic SCC
!    ETKE_TALPH: T_alpha for prognostic SCC 
!    ETKE_ALPH0: alpha_0 for ptognostic SCC
!    ETKE_ENTRX: maximal entrainment value for MF SCC diagnostics
!    ETKE_ENTRN: minimal entrainment value for MF SCC diagnostics
!    ETKE_KLM:   mixing length modulation parameter K
!    ETKE_TAULM: mixing length modulation parameter TAU
!    ETKE_C0SHEAR: tuning parameter for shear term in extended BL89 mix. length
!    ETKE_R1SIM: z/h_PBL where transition from kappa.(z+z0) to BL89 mxl starts
!    ETKE_R2SIM: z/h_PBL where transition from kappa.(z+z0) to BL89 mxl ends
!    ETKE_GB08A: tuning parameter for buyancy term in GB08 mixing length
!    ETKE_GB08B: tuning parameter for shear term in GB08 mixing length
!    ETKE_MIN:   minimum value of TKE or TTE
!    ETKE_CRIT:  critical value of SQRT(TKE^2 + TTE^2),
!                pushing Rif to Rifc with weight 1/2
!    ETKE_DELTA: weight given to TKE_tild* and TTE_tild* in solvers for
!                prognostic TKE and TTE
!    TOUCANS - EFB scheme
!    EFB_AZ0
!    EFB_UR   : Unstable prolongation of R of EFB
!    REFB_1, REFB_2, REFB_3 : R  in Rif for stable startification

! Prognostic convection scheme
!     TUDBU   : UPDRAUGHT VIRTUAL MASS PARAMETER
!     TUDFR   : UPDRAUGHT DISSIPATION COEFFICIENT
!     TDDBU   : DOWNDRAUGHT VIRTUAL MASS PARAMETER
!     TDDFR   : DOWNDRAUGHT DISSIPATION COEFFICIENT
!     GCVACHI : Activity History, absolute minimum draught advected
!               velocity to declare continued activity whichever be ZKUO
!     GCVBEE  : IMPACT OF ACCELERATION on ENTRAINMENT
!     GCVEEX  : EXPONENT FOR impact of accel on entr

!   GCVALMX   : MAXIMUM ACCEPTABLE VALUE FOR TOTAL MESH FRACTION
!     GCVTAUDE: TIME CONSTANT FOR CONVECTIVE CLOUDINESS.

!              Ascent properties
!      ECMNPI : ECMNP for ice, the original ECMNP being kept for liquid.

!              Downdraught:
!   GDDWPF    : INFLUENCE OF RAIN FALL VELOCITY ON DOWNDRAUGHT
!   GDDEVF    : FOR ACMODO, CFR GDDEVA IN ACCVIMP
!   GDDBETA   : DOWNDRAUGHT EXPLICIT DETRAINMENT COEFFICIENT
!   GDDDP     : DELTAp FROM SURFACE BRAKING LAYER
!   GDDFXM    : LIMITATION OF FLUX DECREMENT BETWEEN LAYERS
!   TENTRD    : DOWNDRAUGHT ENTRAINMENT RATE (s^2/m^2)

!              Updraught:
!   GPEIPHI   : MINIMUM VALUE OF GCVNU IN PROGNOSTIC ENTRAINMENT
!   GPETAU    : TIME SCALE FOR PROGNOSTIC ENTRAINMENT
!   GPEFDC    : SCALING FACTOR OF PROGNOSTIC ENTRAINMENT
!   GENVSRH   : ENTRAINMENT DEPENDENCY ON RELATIVE HUMIDITY RATIO BETWEEN
!               CLOUD AND ENVIRONMENT - DRIVING PARAMETER.

!              Intensive Precipitation:
!   GRRMINA   : MINIMUM REALISTIC PRECIPITATING MESH FRACTION
!
!*CSD UPDRAUGHT SCHEME
!       GCVKSKV : RATIO OF (TOTAL CKE)/(UPWARDS CKE)
!       GCVALBU : COEFF OF BUOYANCY ACCOUNTING FOR VARIOUS EFFECTS
!      GCVENDY1 : COEFFICIENT FOR GUESS OF ORGANIZED ENTRAINMENT
!      GCVENDY2 : COEFFICIENT FOR GUESS OF ORGANIZED ENTRAINMENT
!     GCVENDYMX : MAX VALUE OF ORGANIZED ENTRAINMENT/DPHI
!     GCVIDPBAS : INVERSE SCALING DP FOR ESTIMATING UD BASE VELOCITY
!     GCVTAUSIG : <0: USE PROGNOSTIC RELATION FOR MESH FRACTION
!                 =0: USE STEADY-STATE MESH FRACTION
!                 >0: RELAXATION TIME TOWARDS STEADY-STATE MESH FRACTION
!
!* CELLULAR AUTOMATA  PARAMETERS IN CSD
!     GCVCATAU  : REFERENCE TIME SCALE FOR CA IN PROGNOSTIC CLOSURE
!     GCATHRCAP : THRESHOLD OF CAPE FOR SEEDING
!     GCATHRMOC : THRESHOLD OF MOISTURE CONVERGENCE FOR SEEDING
!     GCATHRCND : THRESHOLD OF ABSOLUTE UD CONDENSATION FOR SEEDING
!     GCAOMCND  : REFERENCE RESOLVED VELOCITY FOR GCATHRCND CRITERION
!
!*USL TRIGGERING
!     GTRGDPMIX : PRESSURE HEIGHT OF MIXED PARCEL FOR TRIGGERING
!    GTRGDPHIMN : MINIMUM HEIGHT (DPHI) OF ASCENT TO ACKNOWLEDGE TRIGGERING
!    GTRGPUSLMN : PRESSURE DIFF FROM SURFACE OF HIGHEST LEVEL TO SEARCH USL
!      GTRGKCK9 : MODULATION OF NEGATIVE TRIGNG KICK ON PREVIOUSLY ACTIVE LAYERS
!       GTRGAIN : GAIN FOR RC TRIGGERING
!       GTRTHRS : THRESHOLD FOR RC TRIGGERING
!       GTRTHCK : REF THICKNESS FOR RC TRIGGERING
!       GTRBRC  : FRACTION OF RC THRESHOLD TO FIND IN 300hPa ABOVE LCL
!      GTRKGAIN : GAIN FOR KF TRIGGERING
!      GTRKTHRS : THRESHOLD FOR KF TRIGGERING
!      GTRKTHCK : REF HEIGHT FOR KF TRIGGERING
!
!*NON SATURATED DOWNDRAFT
!       GDDALBU : COEFF OF BUOYANCY ACCOUNTING FOR VARIOUS EFFECTS
!       GDDFRAC : FRACTION OF PRECIPITATION AREA OCCUPIED BY DD
!     GDDENDYMX : LIMITATION OF DYNAMICAL ENTRAIMENT IN DD
!    GDDFP(1:3) : GAIN, EXPONENT AND INTENSIFICATION OF F(PRECIP) IN ACNSDO
!     GDDTAUSIG : RELAXATION TIME FOR DOWNDRAFT MESH FRACTION
!     GDDINHOM  : GAIN FOR PRECIP INHOMOGENEITY IN DOWNDRAFT
!     GDDFREVS  : FRACTION OF STRATIFORM EVAPORATION TO SCALE DD EVAPORATION


! ------------------------------------------------------------------

REAL(KIND=JPRB) :: TYM(5)
INTEGER(KIND=JPIM) :: NPCLO1
INTEGER(KIND=JPIM) :: NPCLO2
REAL(KIND=JPRB) :: A0ML_AU
REAL(KIND=JPRB) :: A0ML_AT
REAL(KIND=JPRB) :: A0ML_BU
REAL(KIND=JPRB) :: A0ML_BT
REAL(KIND=JPRB) :: AERCS1
REAL(KIND=JPRB) :: AERCS3
REAL(KIND=JPRB) :: AERCS5
REAL(KIND=JPRB) :: ADJTAU
REAL(KIND=JPRB) :: ALMAV
REAL(KIND=JPRB) :: BEDIFV
REAL(KIND=JPRB) :: ECMNP
REAL(KIND=JPRB) :: EDB
REAL(KIND=JPRB) :: EDC
REAL(KIND=JPRB) :: EDD
REAL(KIND=JPRB) :: EVAP
REAL(KIND=JPRB) :: FONT
REAL(KIND=JPRB) :: GALP
REAL(KIND=JPRB) :: GCISMIN
REAL(KIND=JPRB) :: GEVAVF
REAL(KIND=JPRB) :: GCCSV
REAL(KIND=JPRB) :: GCVADS
REAL(KIND=JPRB) :: GCVBETA
REAL(KIND=JPRB) :: GCVIMPT
REAL(KIND=JPRB) :: GCVOMGE
REAL(KIND=JPRB) :: GCVOMGQ
REAL(KIND=JPRB) :: GCVOMGS
REAL(KIND=JPRB) :: GCVTURB
REAL(KIND=JPRB) :: GCVOMDPS
REAL(KIND=JPRB) :: GCVOMGSX
REAL(KIND=JPRB) :: GCVRHMIN
REAL(KIND=JPRB) :: GCVRHMAX
REAL(KIND=JPRB) :: GCVOMCA
REAL(KIND=JPRB) :: GCVOMCC
REAL(KIND=JPRB) :: GDDEVA
REAL(KIND=JPRB) :: GDDSDE
REAL(KIND=JPRB) :: GDDFREVS
REAL(KIND=JPRB) :: GDDINHOM
REAL(KIND=JPRB) :: GRCVPP
REAL(KIND=JPRB) :: GWDAMP
REAL(KIND=JPRB) :: GWDBC
REAL(KIND=JPRB) :: GWDCCO
REAL(KIND=JPRB) :: GWDCD
REAL(KIND=JPRB) :: GWDLT
REAL(KIND=JPRB) :: GWDSE
REAL(KIND=JPRB) :: GWDPROF
REAL(KIND=JPRB) :: GWDVALI
REAL(KIND=JPRB) :: HOBST
REAL(KIND=JPRB) :: HUCOE
REAL(KIND=JPRB) :: HUTIL
REAL(KIND=JPRB) :: HUTIL1
REAL(KIND=JPRB) :: HUTIL2
REAL(KIND=JPRB) :: QSMIN
REAL(KIND=JPRB) :: QSMODC
REAL(KIND=JPRB) :: QSNEBC
REAL(KIND=JPRB) :: QSNEBS
REAL(KIND=JPRB) :: QSSUSC
REAL(KIND=JPRB) :: QSSUSS
REAL(KIND=JPRB) :: QSSUSV
REAL(KIND=JPRB) :: QSUSXC
REAL(KIND=JPRB) :: QSUSXS
REAL(KIND=JPRB) :: RPHI0
REAL(KIND=JPRB) :: RPHIR
REAL(KIND=JPRB) :: QXRAL
REAL(KIND=JPRB) :: QXRAL_ADJ
REAL(KIND=JPRB) :: QXRDEL
REAL(KIND=JPRB) :: QXRHX
REAL(KIND=JPRB) :: QXRR
REAL(KIND=JPRB) :: QXRTGH
REAL(KIND=JPRB) :: QXRCDIL
REAL(KIND=JPRB) :: RCIN
REAL(KIND=JPRB) :: RCVEVAP
REAL(KIND=JPRB) :: RDECRD
REAL(KIND=JPRB) :: RDECRD1
REAL(KIND=JPRB) :: RDECRD2
REAL(KIND=JPRB) :: RDECRD3
REAL(KIND=JPRB) :: RDECRD4
REAL(KIND=JPRB) :: RDECRDRED
REAL(KIND=JPRB) :: RDTFAC
REAL(KIND=JPRB) :: REVAPN
REAL(KIND=JPRB) :: REVGSL
REAL(KIND=JPRB) :: RGELSFON
REAL(KIND=JPRB) :: RFLCHCE
REAL(KIND=JPRB) :: RTCAPE
REAL(KIND=JPRB) :: SCO
REAL(KIND=JPRB) :: SENSL
REAL(KIND=JPRB) :: SNNBCO
REAL(KIND=JPRB) :: SPNBCO
REAL(KIND=JPRB) :: SXNBCO
REAL(KIND=JPRB) :: TCA
REAL(KIND=JPRB) :: TCT
REAL(KIND=JPRB) :: TCW
REAL(KIND=JPRB) :: TENTR
REAL(KIND=JPRB) :: TENTRX
REAL(KIND=JPRB) :: TUDGP
REAL(KIND=JPRB) :: TDDGP
REAL(KIND=JPRB) :: TURB
REAL(KIND=JPRB) :: TVF
REAL(KIND=JPRB) :: UHDIFV
REAL(KIND=JPRB) :: USDMLT
REAL(KIND=JPRB) :: USUPRC
REAL(KIND=JPRB) :: USURIC
REAL(KIND=JPRB) :: VCHRNK
REAL(KIND=JPRB) :: VKARMN
REAL(KIND=JPRB) :: VZ0CM
REAL(KIND=JPRB) :: VZIUSTAR0
REAL(KIND=JPRB) :: XNBMAX
REAL(KIND=JPRB) :: AECLS3
REAL(KIND=JPRB) :: AECLS4
REAL(KIND=JPRB) :: ALD
REAL(KIND=JPRB) :: AKN
REAL(KIND=JPRB) :: ALPHAT
REAL(KIND=JPRB) :: ALPHAE
REAL(KIND=JPRB) :: EPS
REAL(KIND=JPRB) :: ETACUT
REAL(KIND=JPRB) :: ADISI
REAL(KIND=JPRB) :: ADISE
REAL(KIND=JPRB) :: ECTMIN
REAL(KIND=JPRB) :: ECTMAX
REAL(KIND=JPRB) :: AHCLPV
REAL(KIND=JPRB) :: RICRLM
REAL(KIND=JPRB) :: RMULACVG
REAL(KIND=JPRB) :: XBLM
REAL(KIND=JPRB) :: XMINLM
REAL(KIND=JPRB) :: XMAXLM
REAL(KIND=JPRB) :: XWSALM
REAL(KIND=JPRB) :: XWSBLM
REAL(KIND=JPRB) :: GCVALFA
REAL(KIND=JPRB) :: GCVPSI
REAL(KIND=JPRB) :: GCVPSIE
REAL(KIND=JPRB) :: USURICE
REAL(KIND=JPRB) :: USURICL
REAL(KIND=JPRB) :: QSSC
REAL(KIND=JPRB) :: USURID
REAL(KIND=JPRB) :: GCVNU
REAL(KIND=JPRB) :: USURIDE
REAL(KIND=JPRB) :: GCVMLT
REAL(KIND=JPRB) :: UTILGUST
REAL(KIND=JPRB) :: RRGAMMA
REAL(KIND=JPRB) :: RRSCALE
REAL(KIND=JPRB) :: GPBLHK0
REAL(KIND=JPRB) :: GPBLHRA
REAL(KIND=JPRB) :: WMXOV

REAL(KIND=JPRB) :: ACBRPHIM
REAL(KIND=JPRB) :: ALMAVE
REAL(KIND=JPRB) :: ALMAVX
REAL(KIND=JPRB) :: ARSCH
REAL(KIND=JPRB) :: ARSCQ
REAL(KIND=JPRB) :: ARSC1
REAL(KIND=JPRB) :: ARSB2
REAL(KIND=JPRB) :: RICRET
REAL(KIND=JPRB) :: STTBMIN
REAL(KIND=JPRB) :: UCWSTAR
REAL(KIND=JPRB) :: UDECT
REAL(KIND=JPRB) :: UPRETMIN
REAL(KIND=JPRB) :: UPRETMAX
REAL(KIND=JPRB) :: USHEARM

!*   Variables pour la microphysique dite de Lopez
REAL(KIND=JPRB) :: RAUTEFR
REAL(KIND=JPRB) :: RRAUTCS
REAL(KIND=JPRB) :: RAUTEFS
REAL(KIND=JPRB) :: RAUTSBET
REAL(KIND=JPRB) :: RAUTEFG
REAL(KIND=JPRB) :: REVASX
REAL(KIND=JPRB) :: RNINTR
REAL(KIND=JPRB) :: RNINTS
REAL(KIND=JPRB) :: RQLCR
REAL(KIND=JPRB) :: RSPCRR
REAL(KIND=JPRB) :: RQICRMAX
REAL(KIND=JPRB) :: RQICRMIN
REAL(KIND=JPRB) :: RQLCV
REAL(KIND=JPRB) :: RQICVMAX
REAL(KIND=JPRB) :: RQICVMIN
REAL(KIND=JPRB) :: RQICRT1
REAL(KIND=JPRB) :: RQICRT2
REAL(KIND=JPRB) :: RQICRSN
REAL(KIND=JPRB) :: RQCRNS
REAL(KIND=JPRB) :: RACCEF
REAL(KIND=JPRB) :: RAGGEF
REAL(KIND=JPRB) :: RRIMEF
REAL(KIND=JPRB) :: RHCRIT1
REAL(KIND=JPRB) :: RHCRIT2
REAL(KIND=JPRB) :: RETAMIN
REAL(KIND=JPRB) :: RFACNSM
REAL(KIND=JPRB) :: TFVL
REAL(KIND=JPRB) :: TFVI
REAL(KIND=JPRB) :: TFVR
REAL(KIND=JPRB) :: TFVS
REAL(KIND=JPRB) :: GRHCMOD
REAL(KIND=JPRB) :: RHCEXPDX
REAL(KIND=JPRB) :: NUPTKE
REAL(KIND=JPRB) :: TKEMULT
REAL(KIND=JPRB) :: C_EPSILON
REAL(KIND=JPRB) :: C3TKEFREE
REAL(KIND=JPRB) :: ETKE_CTHETA
REAL(KIND=JPRB) :: ETKE_RIFC_MAF
REAL(KIND=JPRB) :: ETKE_RIFC
REAL(KIND=JPRB) :: ETKE_R
REAL(KIND=JPRB) :: ETKE_OLAM
REAL(KIND=JPRB) :: ETKE_LAM0
REAL(KIND=JPRB) :: ETKE_LAM1
REAL(KIND=JPRB) :: ETKE_LAM2
REAL(KIND=JPRB) :: ETKE_LAM3
REAL(KIND=JPRB) :: ETKE_LAM4
REAL(KIND=JPRB) :: ETKE_KA1
REAL(KIND=JPRB) :: ETKE_KA2
REAL(KIND=JPRB) :: ETKE_KA3
REAL(KIND=JPRB) :: ENT_LAMBDA
REAL(KIND=JPRB) :: ETKE_CG01
REAL(KIND=JPRB) :: ETKE_CG02
REAL(KIND=JPRB) :: ETKE_CG03
REAL(KIND=JPRB) :: ETKE_BETA_EPS
REAL(KIND=JPRB) :: ETKE_GAMMA_EPS
REAL(KIND=JPRB) :: ETKE_GAMD
REAL(KIND=JPRB) :: ETKE_TALPH
REAL(KIND=JPRB) :: ETKE_ALPH0
REAL(KIND=JPRB) :: ETKE_ENTRX
REAL(KIND=JPRB) :: ETKE_ENTRN
REAL(KIND=JPRB) :: ETKE_KLM
REAL(KIND=JPRB) :: ETKE_TAULM
REAL(KIND=JPRB) :: ETKE_C0SHEAR
REAL(KIND=JPRB) :: ETKE_R1SIM
REAL(KIND=JPRB) :: ETKE_R2SIM
REAL(KIND=JPRB) :: ETKE_GB08A
REAL(KIND=JPRB) :: ETKE_GB08B
REAL(KIND=JPRB) :: ETKE_MIN
REAL(KIND=JPRB) :: ETKE_CRIT
REAL(KIND=JPRB) :: ETKE_DELTA
REAL(KIND=JPRB) :: EFB_AZ0
REAL(KIND=JPRB) :: EFB_UR
REAL(KIND=JPRB) :: REFB_1
REAL(KIND=JPRB) :: REFB_2
REAL(KIND=JPRB) :: REFB_3
!*   Variables pour la convection pronostique
REAL (KIND=JPRB) :: TUDBU, TDDBU
REAL (KIND=JPRB) :: TUDFR, TDDFR
REAL (KIND=JPRB) :: GCVALMX
REAL (KIND=JPRB) :: GCVTAUDE
REAL (KIND=JPRB) :: GCVACHI
REAL (KIND=JPRB) :: GCVBEE,GCVEEX
REAL (KIND=JPRB) :: ECMNPI
REAL (KIND=JPRB) :: GRRMINA
! Downdraught:
REAL (KIND=JPRB) :: GDDBETA,GDDDP,GDDFXM,GDDWPF,GDDEVF
REAL (KIND=JPRB) :: TENTRD
! Non Saturated downdraught:
REAL(KIND=JPRB) :: GDDALBU
REAL(KIND=JPRB) :: GDDFRAC
REAL(KIND=JPRB) :: GDDENDYMX
REAL(KIND=JPRB) :: GDDFP(3)
REAL(KIND=JPRB) :: GDDTAUSIG
! Updraught:
REAL (KIND=JPRB) :: GPEIPHI, GPETAU, GPEFDC, GENVSRH      
! CSD Updraught:
REAL(KIND=JPRB) :: GCVKSKV
REAL(KIND=JPRB) :: GCVALBU
REAL(KIND=JPRB) :: GCVENDY1
REAL(KIND=JPRB) :: GCVENDY2
REAL(KIND=JPRB) :: GCVENDYMX
REAL(KIND=JPRB) :: GCVIDPBAS
REAL(KIND=JPRB) :: GCVTAUSIG
! Updraught triggering:
REAL(KIND=JPRB) :: GTRGDPMIX
REAL(KIND=JPRB) :: GTRGDPHIMN
REAL(KIND=JPRB) :: GTRGPUSLMN
REAL(KIND=JPRB) :: GTRGKCK9
REAL(KIND=JPRB) :: GTRGAIN
REAL(KIND=JPRB) :: GTRTHRS
REAL(KIND=JPRB) :: GTRTHCK
REAL(KIND=JPRB) :: GTRBRC
REAL(KIND=JPRB) :: GTRKGAIN
REAL(KIND=JPRB) :: GTRKTHRS
REAL(KIND=JPRB) :: GTRKTHCK
! CA-parameters in CSD:
REAL(KIND=JPRB) :: GCVCATAU
REAL(KIND=JPRB) :: GCATHRCAP
REAL(KIND=JPRB) :: GCATHRMOC
REAL(KIND=JPRB) :: GCATHRCND
REAL(KIND=JPRB) :: GCAOMCND
! Other uses of CA-scheme:
REAL (KIND=JPRB) :: NWEIGHT, NCATAU, NCAPEMAX, NCVGMAX
!*
!     ------------------------------------------------------------------
!     CONSTANTES PHYSIQUES REGLABLES PROPRES A L'ATMOSPHERE
!     DANS LA PHYSIQUE SIMPLIFIEE SEULEMENT:
!     ------------------------------------------------------------------
! RNEGAT    : first Pisvejc's constant in ACQWLSR and TL/AD
! RNLCURV   : second Pisvejc's constant in ACQWLSR and TL/AD
REAL(KIND=JPRB) :: RNEGAT
REAL(KIND=JPRB) :: RNLCURV
!     EDK : NOUVEAU PARAMETRE POUR LES FONCTIONS DE LOUIS EN CAS STABLE.
!     XKLM : PARAMETRE POUR L UTILSATION DE HCLP POUR LE CALCUL DE L.
REAL(KIND=JPRB) :: EDK
REAL(KIND=JPRB) :: XKLM
!     PARAMETRE POUR LE TKE AVEC LPBLE (Top-entrainment).
REAL(KIND=JPRB) :: AGRE1
REAL(KIND=JPRB) :: AGRERICR
REAL(KIND=JPRB) :: AJBUMIN
REAL(KIND=JPRB) :: RCOFLM


!*
!     ------------------------------------------------------------------
!     PARAMETRES POUR LA PHYSIQUE
!     ------------------------------------------------------------------

! TRENTRV : Taux Relatif d'ENTRainement du Vent.
! TRENTRV : RELATIVE WIND'S ENTRAINMENT RATE.

! TENTRVL : TAUX D'ENTRAINEMENT V. Lorant
! TENTRVL : V. Lorant ENTRAINMENT RATE.

!*
!     ------------------------------------------------------------------
!     For ACCVIMP :
!     ------------------------------------------------------------------
REAL(KIND=JPRB) :: TENTRVL
REAL(KIND=JPRB) :: TRENTRV
REAL(KIND=JPRB) :: GCVGAMMA ! 1/alpha, for subcloud evaporation in ACCVIMP.
LOGICAL :: LKESC ! KESsler Control of evaporation in ACCVIMP.

!*
!     ------------------------------------------------------------------
!     For Grenier (2000) top-PBL entrainment scheme :
!     ------------------------------------------------------------------
REAL(KIND=JPRB) :: AGRE2
REAL(KIND=JPRB) :: AGREF

!*
!     ------------------------------------------------------------------
!     For ACCVIMPGY and PCMT :
!     ------------------------------------------------------------------
! ALFX    : FRACTION D'ASCENDANCE CONVECTIVE MAXIMUM
! TCTC    : PARAMETRE POUR LE SCHEMA DE PRECIPITATIONS CONVECTIVES
! TVFC    : PARAMETRE POUR LE SCHEMA DE PRECIPITATIONS CONVECTIVES
! GAMAP1  : PARAMETRE DE MASSE VIRTUELLE + 1.
! RKDN    : COEFFICIENT DE RESISTANCE MINIMUM
! VVN     : VITESSE VERTICALE MIN POUR L'ENTRAINEMENT TURBULENT.
! VVX     : VITESSE VERTICALE MAX POUR L'ENTRAINEMENT TURBULENT.
! FENTRT  : FACTEUR DE L'ENTRAINEMENT TURBULENT POUR NIVEAU DE DETRAINEMENT.
! FQLIC   : FACTEUR DE L'EAU LIQUIDE CONVECTIVE
! FNEBC   : FACTEUR DE LA NEBULOSITE CONVECTIVE
! FEVAPC  : FACTEUR D'EVAPAPORATION DES PRECIPITATIONS
REAL(KIND=JPRB)    :: ALFX
REAL(KIND=JPRB)    :: ALFX_LR ! FRACTION D'ASCENDANCE CONVECTIVE MAXIMUM (basse resolution).
REAL(KIND=JPRB)    :: ALFX_HR ! FRACTION D'ASCENDANCE CONVECTIVE MAXIMUM (haute resolution).
REAL(KIND=JPRB)    :: TCTC
REAL(KIND=JPRB)    :: TVFC
REAL(KIND=JPRB)    :: GAMAP1
REAL(KIND=JPRB)    :: RKDN
REAL(KIND=JPRB)    :: VVN
REAL(KIND=JPRB)    :: VVX
REAL(KIND=JPRB)    :: FENTRT
REAL(KIND=JPRB)    :: FQLIC
REAL(KIND=JPRB)    :: FNEBC
REAL(KIND=JPRB)    :: FEVAPC

!*
!     ------------------------------------------------------------------
!     For ALARO-0 :
!     ------------------------------------------------------------------

! RDPHIC   : REFERENCE GEOPOTENTIAL FOR CLOUDINESS ADJUSTMENT.
! RWBF1    : FIRST TUNING CONSTANT FOR BERGERON FINDEISEN PROCESS
! RWBF2    : SECOND TUNING CONSTANT FOR BERGERON FINDEISEN PROCESS
!               IN ACPLUIE_PROG
! SCLESPR  : CRITICAL LENGTH SCALE FOR CLOUD-DEPENDENT LIQUID COND.
! SCLESPS  : CRITICAL LENGTH SCALE FOR CLOUD-DEPENDENT SOLID  COND.
! HUCRED   : REDUCTION COEFFICIENT TO CRITICAL RELATIVE HUMIDITY DEFICIT.
! HUCREDRA : REDUCTION COEFFICIENT TO CRITICAL RELATIVE HUMIDITY DEFICIT IN RADIATION.
! FSPRAIN  : CONSTANT TO COMPUTE SPECTRUM OF FALL-SPEEDS OF RAIN
! EFFCOLL  : EFFICIENCY OF COLLECTION

! RSMDNEBX : MAX CLOUDINESS VERTICAL INCREMENT ALLOWED
!            IF MSMDNEB=2 (ACSMI1)
! RSMDTX   : MAX TEMPERATURE INCREMENT IN 1 TIME STEP
!            ALLOWED FROM RESOLVED CONDENSATION (ACQMESM)
! NSMTPA   : NUMBER OF LEVELS BELOW Tt LEVEL FOR LSMTPS SMOOTHING
! NSMTPB   : NUMBER OF LEVELS ABOVE Tt LEVEL FOR LSMTPS SMOOTHING
! RPRTH    : COEFF. FOR THERMAL PRODUCTION OF TKE FROM FROM THE SHALLOW SCHEME.

! ------------------------------------------------------------------

REAL(KIND=JPRB) :: RDPHIC
REAL(KIND=JPRB) :: RWBF1
REAL(KIND=JPRB) :: RWBF2
REAL(KIND=JPRB) :: SCLESPR
REAL(KIND=JPRB) :: SCLESPS
REAL(KIND=JPRB) :: HUCRED
REAL(KIND=JPRB) :: HUCREDRA
REAL(KIND=JPRB) :: FSPRAIN
REAL(KIND=JPRB) :: EFFCOLL
REAL(KIND=JPRB) :: RSMDNEBX
REAL(KIND=JPRB) :: RSMDTX
INTEGER (KIND=JPIM) :: NSMTPA
INTEGER (KIND=JPIM) :: NSMTPB

! Pour la CVPP d'AROME (LCVPPKF)
REAL(KIND=JPRB)    :: RKFBTAU
REAL(KIND=JPRB)    :: RKFBNBX
! Limitation de la convection
REAL(KIND=JPRB)    :: GCVHMIN

! Minimal resolution for ZALF computation (in ACMTUD).
REAL(KIND=JPRB)    :: GCVRESN
! Maximal resolution for ZALF computation (in ACMTUD).
REAL(KIND=JPRB)    :: GCVRESX
REAL(KIND=JPRB)    :: GMIRH ! MIcrophysics: threshold for Relative Humidity of saturated air.


! ------------------------------------------------------------------
!     For the "Lenderink & Holtslag" mixing Length : (ACNEBR)
! ------------------------------------------------------------------

REAL(KIND=JPRB)   :: RLMLH1
REAL(KIND=JPRB)   :: RPRTH
!     ------------------------------------------------------------------
!    Smoothing of melting of snow in advprcs
REAL(KIND=JPRB)   :: RSMOOTHMELT


! LADVLIM: in ACADVEC, minimises p2 to the value such that the transport scheme cannot transport
! beyond a distance of w*deltat, in a time-step.
LOGICAL :: LADVLIM

!*
!     ------------------------------------------------------------------
!     For PCMT convection scheme:
!     ------------------------------------------------------------------

! LGDDD   : ACTIVATES DIAGNOSTIC DOWNDRAFTS.
! LCVNHD  : ACTIVATES NON-HYDROSTATIC DRAFTS DYNAMICS.
! LCVRESDYN : Activates RESolved effects of DYNamics on subgrid convection.
! LCVMICC : type of link between cloudiness and cloud condensates.
! GMUKEDD : link between kinetic energy of downdraft and alpha tendency.
! GNHDTAT : control tendency magnitude: multiplicative factor (> 1.) to control this magnitude.
! GFRIC   : aerodynamic friction of wu and wd.
! GUDDD   : dd fraction is equal to ud fraction multiplied by GUDDD.
! GSIGA   : vertical SIGma level where 3D Alpha value is used to initialize 2D alpha.
! GNHDSMOW: VERTICAL SMOOTHING FACTOR FOR NHD DD DYNAMICS.
! GSINHD  : SImple NH effect: Depth (in geopotential units) for buoyancy vertical smoothing.
! GSINHR  : SImple NH effect: Ratio: multiplicative factor defining magnitude of this effect.
! GDEPTH  : minimal ud depth to get a dd.
! GALTAU  : inverse time response (TAU) for decaying ALpha.
! GKEDDRE : link between Kinetic Energy of DD and REduction of entrainment.
! GNHACC  : vertical UD NH acceleration value, for which a level is legible as a start of the updraft.
! GTDCL   : threshold to define convective levels (in m/s).
! GNHDSMOS: VERTICAL SMOOTHING FACTOR FOR EVAPORATION.
! GNHDSMOT: TIME SMOOTHING FACTOR FOR NHD CONVECTIVE DYNAMICS.
! GNHDEV  : Link between precipitation evaporation and downdraft temperature.
! LGVVEX  : ACTIVATES VERT VELOCITY EXCESS AT ASCENT BASE.
! GCVENTRN: MINIMAL VALUE OF ENTRAINMENT (CASE NCVENTR=6 ('V1') OR NCVENTR=7 ('V1DEV')).
! GCVENTRX: MAXIMAL VALUE OF ENTRAINMENT (CASE NCVENTR=6 ('V1') OR NCVENTR=7 ('V1DEV')).
! ADOE    : FACTOR OF ENTRAINMENT TO GET THE AERODYMANIC DRAG COEFFICIENT.
! RFRAC_ENTR_N: MINIMUM VALUE OF FRACTIONAL ENTRAINMENT.
! RFRAC_ENTR_X: MAXIMUM VALUE OF FRACTIONAL ENTRAINMENT.
! GCVENTR_MIN: MINIMAL VALUE OF ENTRAINMENT (IN S**-1).
! THPCMT: THRESHOLD VALUE, THAT DEFINES THE ACTIVATION OF PCMT VERSUS SHALLOW CONVECTION SCHEMES.
! GAEPS: "Alpha EPSilon" TUNING REDUCTIVE FACTOR, TO BE APPLIED TO CLOUDINESS.
! GCVEZ: DEPENDENCY OF ENTRAINEMENT TO Z.
! GCVTRMIN: MINIMUM TRANSPORT HEAT FLUX.
! LCVFEVV: Feedback of Evaporation on Vertical Velocity.
! GCVFEVV: magnitude of the Feedback of Evaporation on Vertical Velocity.
! LCVCONTAU: CONtrol TAU (TAU = response time of convection) min and max values.
! GCVTEXC: Temperature EXCess coefficient.
! GCWTEXC: Vertical velocity EXCess coefficient.
! LCVNAUV: New Algorithmics for computing U and V convective effects.
! GCVFRR: Fraction of entrainment/detrainment, to be applied to the downdraft.
! GCVPNH: if /= 0., time response of mass divergeny accumulation.
! GCVORGED: link between ORGanized Entrainment-Detrainment and NH pressure.
! LCVIMPT: IMPlicit Transport.
! GCVTAUREM: remanance time of NH rho'.
! GCLOEA, GCLOEB: link between cloud depth and effective transport.
! GFRAE: FRActional Entrainment.
! GCVADET: Fraction of zero buoyancy variable in the detrainmemnt.
! GCVCINC: CIN threshold for triggering condition.
! LCVEOD: Activates large entrainment/detrainment rates below ou over the cloud (Entrainment Outside Draft).
! GSDMIN, GSDMAX: min and max values of Saturation Deficit, to compute reduction of entrainment.
! GALMIN,GALMAX: EXTREMAL VALUES OF THE CONVECTIVE FRACTION ALPHA.
! GSDAMIN,GSDAMAX: min and max values of Saturation Deficit, to compute the convective fraction alpha.
! GEXPKD: Exponent to compute updraft w friction from the reduction factor due to saturation deficit.
! GREMIN,GREMAX: MIN AND MAX VALUE OF THE "REDUCING ENTRAINMENT FACTOR".
! GSHELL: "shell effect": fraction of microphysics (evaporation of resolved condensates) 
! which occurs in the updraft, vs environment.
! GCHI0: FACTOR TO BE APPLIED TO DETRAINMENT.
! NCVENTR : TYPE OF ENTRAINMENT.
! NCVCLOS: TYPE OF CONVECTIVE CLOSURE (ALPHA COMPUTATION).
! NCVSIG: TYPE OF SIGMA COMPUTATION (ACTIVE FRACTION = SIGMA*ALPHA).
! LCVUVM: ESTIMATES THE U AND V UPDRAFT VALUES AS UNIFORM, EQUAL TO THE MEAN OF PU AND PV ALONG THE CONVECTIVE LEVELS.
! GFSURF: Fraction of surface vs lowest model level in the computation of diagnostic updraft ascent initial state.
! GCVFNER: Fraction of NEbulosity Reduction: 0.: no reduction, 1.: total reduction.
! GCVFNEO: Fraction of NEbulosity: Omega threshold governing the transition from no reduction to GCVFNER reduction.
! GCVFNEP1, GCVFNEP2: Fraction of NEbulosity: Pressure at which detrained condensates are "close" to the updraft.
! GRBCC: Reduction of Buoyant Convective Condensation.
! GTOPDEPTH : Minimal depth (m) to compute top of convection (diagnostic) in ACNPART

! GCVTSMO : transport fluxes smothing coefficient (between 0. and 1.).
! RKDX : Maximum aerodynamic drag coefficient.
! LCAPCIN: grid CAPE computation including CIN (.F. as default).
! LCORSEDIM: sedimentation fluxes (.F. as default).


LOGICAL :: LGDDD
LOGICAL :: LCVNHD
LOGICAL :: LCVRESDYN
LOGICAL :: LCVMICC
REAL(KIND=JPRB)   :: GMUKEDD
REAL(KIND=JPRB)   :: GNHDTAT
REAL(KIND=JPRB)   :: GNHDSMOS
REAL(KIND=JPRB)   :: GNHDSMOT
REAL(KIND=JPRB)   :: GNHDEV
LOGICAL :: LGVVEX
LOGICAL :: LCVUVM
INTEGER (KIND=JPIM) :: NCVENTR
INTEGER (KIND=JPIM) :: NCVSIG
INTEGER (KIND=JPIM) :: NCVCLOS
INTEGER (KIND=JPIM) :: NCVQLI ! Option for radiative condensate, in PCMT scheme.
REAL(KIND=JPRB)   :: GCVENTRN
REAL(KIND=JPRB)   :: GCVENTRX
REAL(KIND=JPRB)   :: ADOE
REAL(KIND=JPRB)   :: RFRAC_ENTR_N
REAL(KIND=JPRB)   :: RFRAC_ENTR_X
REAL(KIND=JPRB)   :: GCVENTR_MIN
REAL(KIND=JPRB)   :: THPCMT
REAL(KIND=JPRB)   :: AJ1PEPS
REAL(KIND=JPRB)   :: AJ1MEPS
INTEGER (KIND=JPIM) :: NAJITER
REAL(KIND=JPRB)   :: GAEPS
REAL(KIND=JPRB)   :: GCVEZ
REAL(KIND=JPRB)   :: GCVTRMIN
LOGICAL :: LCVFEVV
REAL(KIND=JPRB)   :: GCVFEVV
LOGICAL :: LCVCONTAU
REAL(KIND=JPRB)   :: GCVTEXC
REAL(KIND=JPRB)   :: GCVWEXC
LOGICAL :: LCVNAUV
REAL(KIND=JPRB)   :: GCVFRR
REAL(KIND=JPRB)   :: GCVPNH
REAL(KIND=JPRB)   :: GCVORGED
LOGICAL :: LCVIMPT
REAL(KIND=JPRB)   :: GCVTAUREM
REAL(KIND=JPRB)   :: GCLOEA
REAL(KIND=JPRB)   :: GCLOEB
REAL(KIND=JPRB)   :: GFRAE
REAL(KIND=JPRB)   :: GCVADET
REAL(KIND=JPRB)   :: GCVCINC
REAL(KIND=JPRB)   :: GSDMIN
REAL(KIND=JPRB)   :: GSDMAX
REAL(KIND=JPRB)   :: GALMIN
REAL(KIND=JPRB)   :: GALMAX
REAL(KIND=JPRB)   :: GSDAMIN
REAL(KIND=JPRB)   :: GSDAMAX
REAL(KIND=JPRB)   :: GEXPKD
LOGICAL :: LCVEOD

REAL(KIND=JPRB)   :: GREMIN,GREMAX,GCHI0,GFSURF
REAL(KIND=JPRB)   :: GSHELL
REAL(KIND=JPRB)   :: GFRIC,GUDDD,GSIGA,GNHDSMOW,GDEPTH,GALTAU,GKEDDRE,GNHACC
REAL(KIND=JPRB)   :: GTDCL

REAL(KIND=JPRB)   :: GSINHD,GSINHR
REAL(KIND=JPRB)   :: GCVFNER,GCVFNEO,GCVFNEP1,GCVFNEP2,GRBCC

REAL(KIND=JPRB)   :: GTOPDEPTH

REAL(KIND=JPRB)   :: GCVTSMO, RKDX
LOGICAL :: LCAPCIN
LOGICAL :: LCORSEDIM

! GNHDTAU: time response pour NHD effet in updraft.
REAL(KIND=JPRB)   :: GNHDTAU

! GRSO, GRTH, GRFCS: tuning factor for resp. SOlar radiation, THermal radiation, Flux de Chaleur Sensible.
REAL(KIND=JPRB)   :: GRSO,GRTH,GRFCS
REAL(KIND=JPRB)   :: GCVRE ! Reduce ConVective Entrainment.

! LSBUO: Smooth BUOyancy.
LOGICAL :: LSBUO
REAL(KIND=JPRB)   :: GREDDI ! REDuction of Detrainment for Ice water.
REAL(KIND=JPRB)   :: GREDDL ! REDuction of Detrainment for Liquid water.
REAL(KIND=JPRB)   :: GREDDR ! REDuction of Detrainment for Rain.
REAL(KIND=JPRB)   :: GREDDS ! REDuction of Detrainment for Snow.
LOGICAL :: LCVTADV ! ConVective Transport by double ADVection.
LOGICAL :: LCVDS ! activates debug of sigma.
REAL(KIND=JPRB) :: GCVUV ! factor of transport for U and V, versus thermodynamic variables (theta, qt).
REAL(KIND=JPRB) :: GCVGAW ! vertical velocity to reach resolved ascent inside updraft.
REAL(KIND=JPRB) :: GCVGAX ! maximum factor inside updraft (1/(0.04) in practice).
REAL(KIND=JPRB) :: GCHECKMV_TMIN ! Check Model Variables: minimal value for T difference.
REAL(KIND=JPRB) :: GCHECKMV_TMAX ! Check Model Variables: maximal value for T difference.
REAL(KIND=JPRB) :: GCHECKMV_QVMIN ! Check Model Variables: minimal value for qv.
REAL(KIND=JPRB) :: GCHECKMV_QVMAX ! Check Model Variables: maximal value for qv.
LOGICAL :: LGPRONI1 ! PROtection against Non-linear Instability: integrate fluxes vertically.
INTEGER(KIND=JPIM) :: NPRONI ! PROtection against Non-linear Instability: check massflux CFL.
REAL(KIND=JPRB) :: GPRONI ! PROtection against Non-linear Instability: check massflux CFL.
REAL(KIND=JPRB)    :: RNEBCX ! MAXIMUM CONVECTIVE CLOUDINESS.
REAL(KIND=JPRB)    :: GLIGHTT1 ! Lightning parametrization tuning parameter.
REAL(KIND=JPRB)    :: GLIGHTT2 ! Lightning parametrization tuning parameter.
REAL(KIND=JPRB)    :: GLIGHTT3 ! Lightning parametrization tuning parameter.
!     ------------------------------------------------------------------

!*    * Defining the transformed sphere: physics input

!  REFLRHC :  reference length for critical relative humidity (cloud scheme)
!  REFLKUO, REFLCAPE, REFLRHC are ONLY to be used in the SETUP
!  of TEQK and TEQC and TEQH

!  TEQK : ratio between REFLKUO and the model equivalent mesh size
!  TEQC : ratio between REFLCAPE and the model equivalent mesh size
!  TEQH : ratio between REFLRHC and the model equivalent mesh size

!  TEQK, TEQC, TEQH are to be used in the PHYSICS.

REAL(KIND=JPRB) :: REFLRHC
REAL(KIND=JPRB) :: TEQH
REAL(KIND=JPRB) :: REFLKUO
REAL(KIND=JPRB) :: REFLCAPE
REAL(KIND=JPRB) :: TEQK
REAL(KIND=JPRB) :: TEQC

REAL(KIND=JPRB) :: REPS
! RHUC      : HUMIDITE CRITIQUE PAR NIVEAU POUR LE CALCUL DE PNEB
! RHUC      : CRITICAL MOISTURE FOR EACH LEVEL FOR PNEB CALCULATION.
REAL(KIND=JPRB), ALLOCATABLE :: RHUC (:)
REAL(KIND=JPRB), ALLOCATABLE :: RQSMOD (:)
REAL(KIND=JPRB), ALLOCATABLE :: RSURF (:)
! Tableaux pour les fonctions de "condens.f90" de Meso-NH
REAL(KIND=JPRB), ALLOCATABLE :: RN1D (:), RRC1D (:), RSRC1D (:)

REAL(KIND=JPRB) :: RCOEFRAIN (2), RCOEFSNOW (2)

END TYPE TPHY0

TYPE(TPHY0), POINTER :: YRPHY0 => NULL()

END MODULE YOMPHY0
