MODULE YOMRANDOM_STREAMS

!**** *YOMRANDOM_STREAMS*  - Globally-available random number streams 

!  Original :      2004-05-06 - Mike Fisher
!  Modifications: 07-09-2006 - Judith Berner
!                              added random number streams for stochastic physics
!                  Jan-2016   - SJ Lock : removed LSTOPH option   
                  

USE RANDOM_NUMBERS_MIX, ONLY: RANDOMNUMBERSTREAM

IMPLICIT NONE

SAVE

TYPE :: TRANDOM_STREAMS
TYPE (RANDOMNUMBERSTREAM) :: SCAN2MTL
TYPE (RANDOMNUMBERSTREAM) :: STOCHPHYS_CABS
TYPE (RANDOMNUMBERSTREAM) :: STOCHPHYS_SPBS
TYPE (RANDOMNUMBERSTREAM) :: STOCHPHYS_RVP
TYPE (RANDOMNUMBERSTREAM) :: STOPH_SPBS_T
TYPE (RANDOMNUMBERSTREAM) :: STOPH_RVP_T
END TYPE TRANDOM_STREAMS

!!TYPE(TRANDOM_STREAMS), POINTER :: YR_RANDOM_STREAMS => NULL()

END MODULE YOMRANDOM_STREAMS
