SUBROUTINE CPG_DIA_FLU (YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS_OUT, YDCPG_DYN0, &
& YDMF_PHYS_SURF, YDVARS, YDCFU, YDXFU, YDMODEL)

!=GENERATE= TARGET=SyncDevice
!=GENERATE= TARGET=SyncHost/ParallelView/ParallelFieldAPI/SingleColumnFieldAPIHost/FieldAPIHost

USE YOMHOOK                 , ONLY : DR_HOOK, LHOOK
USE PARKIND1                , ONLY : JPIM, JPRB

USE CPG_OPTS_TYPE_MOD       , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD            , ONLY : CPG_DYN_TYPE, CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD        , ONLY : MF_PHYS_OUT_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD, ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD     , ONLY : FIELD_VARIABLES
USE YOMCFU                  , ONLY : TCFU
USE YOMXFU                  , ONLY : TXFU
USE TYPE_MODEL              , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_BNDS_TYPE)     ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)     ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE)     ,INTENT(IN)     :: YDCPG_MISC
TYPE(MF_PHYS_OUT_TYPE)  ,INTENT(IN)     :: YDMF_PHYS_OUT
TYPE(CPG_DYN_TYPE)      ,INTENT(IN)     :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE) ,INTENT(IN)     :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES)   ,INTENT(IN)     :: YDVARS
TYPE(TCFU)              ,INTENT(INOUT)  :: YDCFU
TYPE(TXFU)              ,INTENT(INOUT)  :: YDXFU
TYPE(MODEL)             ,INTENT(IN)     :: YDMODEL

#include "cpcfu.intfb.h"
#include "cpxfu.intfb.h"
!include "cumcpl.intfb.h"
!include "cpcls_assim.intfb.h"

LOGICAL :: LLCALL_CPCFU
LOGICAL :: LLCALL_CPXFU
LOGICAL :: LLCALL_CUMCPLDM
REAL(KIND=JPRB) :: ZDPRECIPS(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC)
REAL(KIND=JPRB) :: ZDPRECIPS2(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2)
REAL(KIND=JPRB) :: ZSTRCU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZSTRCV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZSTRDU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZSTRDV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZSTRTU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZSTRTV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZUGST(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZVGST(YDCPG_OPTS%KLON)

REAL(KIND=JPRB) :: ZUCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZNUCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZVCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZNVCLS(YDCPG_OPTS%KLON)

INTEGER (KIND=JPIM) :: JLEV

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CPG_DIA_FLU', 0, ZHOOK_HANDLE)

!     ------------------------------------------------------------------

!*       2.    CFU AND XFU:
!              ------------

!*    2.1   DEFINE THE CONDITIONS OF CALLING SOME ROUTINES.

LLCALL_CPCFU=&
 & YDCFU%LCUMFU.AND.(.NOT.YDCPG_OPTS%LINITER).AND.(.NOT.YDCPG_OPTS%LCONFX).AND.(.NOT.YDMODEL%YRML_PHY_EC%YREPHY%LAGPHY)
LLCALL_CPXFU=YDXFU%LXFU.AND.YDCPG_OPTS%LDIAB.AND.(.NOT.YDCPG_OPTS%LINITER).AND..NOT.YDCPG_OPTS%L_DFISTEP
LLCALL_CUMCPLDM= (&
 & YDMODEL%YRML_AOC%YRMCC%NFRCPL /= 0).AND.(YDMODEL%YRML_AOC%YRMCC%NFRCPL <= YDMODEL%YRML_GCONF%YRRIP%NSTOP).AND.(.NOT.YDCPG_OPTS%LCONFX).AND.(.NOT.YDMODEL%YRML_PHY_EC%YREPHY%LAGPHY).AND.(.NOT.YDCPG_OPTS%LAROME)

!=PARALLEL TARGET=HOST

!*    2.2   DIVIDE SOME QUANTITIES LINKED TO (U,V) BY THE MAPPING FACTOR.

! * ZSTR.. arrays are used for CFU, XFU and in CUMCPL.
IF (LLCALL_CPCFU.OR.LLCALL_CPXFU.OR.LLCALL_CUMCPLDM) THEN
  DO JLEV=0,YDCPG_OPTS%KFLEVG
    ZSTRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS_OUT%STRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS_OUT%STRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS_OUT%STRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS_OUT%STRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS_OUT%STRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS_OUT%STRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
  ENDDO
ENDIF

! * Z(U,V)CLS and Z(U,V)GST are used for XFU.
IF (LLCALL_CPXFU .OR. YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD) THEN
  ZUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%UCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%VCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZNUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%NUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZNVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%NVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZUGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%UGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZVGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%VGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF

! * Divide the arrays by the mapping factor for the cases
!   where the quantities to diagnose are the reduced ones.
!!! -- Test to be checked, seems suspicious -- !!!
IF (YDCPG_OPTS%LDIAB.OR.(YDMODEL%YRML_PHY_MF%YRSIMPHL%LSIMPH.AND.(.NOT.YDMODEL%YRML_PHY_MF%YRSIMPHL%LTRAJPS))) THEN  
  IF (LLCALL_CPCFU.OR.LLCALL_CPXFU.OR.LLCALL_CUMCPLDM) THEN
    DO JLEV=0,YDCPG_OPTS%KFLEVG
      ZSTRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ENDDO
  ENDIF
  IF (LLCALL_CPXFU .OR. YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD) THEN
    ZUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)  /YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)  /YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZNUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZNUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZNVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZNVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZUGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZUGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)  /YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZVGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZVGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)  /YDVARS%GEOMETRY%GM%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF
ENDIF

!=END PARALLEL

!*    2.3   CUMUL OF FLUX DIAGNOSTICS

IF(LLCALL_CPCFU)THEN  
  CALL CPCFU(YDMODEL%YRCST, YDCFU, YDMODEL%YRML_GCONF%YRRIP, YDCPG_OPTS, YDCPG_BNDS, YDMF_PHYS_OUT, &
  & YDCPG_MISC, YDCPG_DYN0, YDVARS, YDMF_PHYS_SURF, ZSTRCU, ZSTRCV, ZSTRDU, ZSTRDV, ZSTRTU, ZSTRTV)
ENDIF

IF(LLCALL_CUMCPLDM) THEN  
! CALL CUMCPL(YDMODEL%YRCST, YDCPG_OPTS, YDCPG_BNDS, YDMODEL%YRML_GCONF%YRRIP, YDMODEL%YRML_PHY_MF%YRPHY,   &
! & YDMF_PHYS_OUT, ZSTRTU(:, YDCPG_OPTS%KFLEVG), ZSTRTV(:, YDCPG_OPTS%KFLEVG), YDMF_PHYS_SURF%GSP_RR%PT_T0, &
! & ZUCLS, ZVCLS)
ENDIF

!*    2.5   INTERFACE FOR INSTANTANEOUS FLUXES

IF (LLCALL_CPXFU) THEN

!=PARALLEL TARGET=DEVICE,VECTOR=SINGLECOLUMN

  IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS) THEN
    ZDPRECIPS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC)=YDMF_PHYS_SURF%GSD_XP%PPRECIP(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC)
  ENDIF
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS2) THEN
    ZDPRECIPS2(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2)=YDMF_PHYS_SURF%GSD_XP2%PPRECIP2(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2)
  ENDIF
  CALL CPXFU(YDXFU, YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS, YDCPG_OPTS, YDCPG_BNDS, YDMF_PHYS_OUT,     &
  & YDCPG_MISC, ZSTRCU, ZSTRCV, ZSTRDU, ZSTRDV, ZSTRTU, ZSTRTV, ZUCLS, ZVCLS, ZNUCLS, ZNVCLS, ZUGST, &
  & ZVGST, ZDPRECIPS, ZDPRECIPS2)

!=END PARALLEL

ENDIF

!*    2.6   INTERFACE FOR CLS FIELDS FOR ASSIMILATION

IF (YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD) THEN
! CALL CPCLS_ASSIM(YDMODEL, YDCPG_OPTS, YDCPG_BNDS, YDMF_PHYS_SURF, YDMF_PHYS_OUT, ZUCLS, ZVCLS, &
! & ZNUCLS, ZNVCLS)
ENDIF

IF (LHOOK) CALL DR_HOOK('CPG_DIA_FLU', 1, ZHOOK_HANDLE)

END SUBROUTINE CPG_DIA_FLU


